ECOM-6217 Added logs and try catch on order creation
openedx-unsupported/ecommerce pull request #1005
Opened 2016-11-09 10:44 UTC by Ayub-Khan

ECOM-6217

**Description :**
Added try catch around the order.save and logged exception to check if it faces any exception on order.save and cause Missing Order issue. 

**Reviewers :** 
- [ ]  @noraiz-anwar 
- [ ]  @Qubad786

2016-11-09 11:11 UTC, noraiz-anwar submitted a review, later dismissed

2016-11-09 11:11 UTC, noraiz-anwar commented on ecommerce/extensions/order/utils.py
> +        except Exception:
I don't think quality test will pass here. It is too broad exception handling and quality check script don't like it.

2016-11-09 12:43 UTC, noraiz-anwar reviewed
Need to add tests

2016-11-09 14:34 UTC, schenedx commented
@clintonb @rlucioni Please review. This will have an impact to the splunk alerts as well

2016-11-09 14:43 UTC, schenedx approved these changes
👍

2016-11-09 15:58 UTC, clintonb approved these changes

2016-11-09 15:58 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +        except Exception:  # pylint: disable=broad-except
You don't need `Exception` here.

2016-11-09 16:18 UTC, rlucioni commented on ecommerce/extensions/order/utils.py
> +            logger.exception('Failed to save Order [%s]', order_number)
Should the exception be re-raised here? Can this method safely continue of saving the order fails?

2016-11-09 17:42 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +            logger.exception('Failed to save Order [%s]', order_number)
Yes, the exception should be raised. Now that I think about it, any exceptions that previously occurred should already be logged...unless they are caught, squashed, and not logged.

2016-11-09 18:38 UTC, rlucioni commented on ecommerce/extensions/order/utils.py
> +            logger.exception('Failed to save Order [%s]', order_number)
Is the goal of this work simply to log something when orders fail to save? If that's the case, to @clintonb's point, this PR seems unnecessary. It only makes sense if we want this method to proceed in spite of the order being unsaved.

2016-11-09 18:39 UTC, clintonb requested changes
Rescinding approval until we determine the goals and necessity of this logging.

2016-11-10 12:14 UTC, closed without merging

2016-11-10 19:15 UTC, adampalay commented on ecommerce/extensions/order/utils.py
> +            logger.exception('Failed to save Order [%s]', order_number)
We wanted to add more nuanced logging to help us get to the root cause; it seems to me that adding `raise` after we log the exception is the way to go. @rlucioni , the PR is necessary to get that extra information and to make it easier to find in splunk.

2016-11-10 19:43 UTC, rlucioni commented on ecommerce/extensions/order/utils.py
> +            logger.exception('Failed to save Order [%s]', order_number)
@adampalay there should already be stacktraces being logged to Splunk. I'm not convinced this change adds any value. It should already be easy to find instances of the exception in the logs.

2016-11-14 14:44 UTC, Ayub-Khan commented on ecommerce/extensions/order/utils.py
> +            logger.exception('Failed to save Order [%s]', order_number)
@adampalay  Sorry my mistake it's not going to help us in any way. @rlucioni  is right if there is exception its already logged and we can check it using file name search.

2016-11-14 14:47 UTC, adampalay commented on ecommerce/extensions/order/utils.py
> +            logger.exception('Failed to save Order [%s]', order_number)
I see. What about having the order number in the logs? Would that be useful?

2016-11-16 09:40 UTC, Ayub-Khan commented on ecommerce/extensions/order/utils.py
> +            logger.exception('Failed to save Order [%s]', order_number)
@adampalay No its same.