[SOL-2111] Add Backend Validation for Coupon Creation - Benefit Type
openedx-unsupported/ecommerce pull request #1008
Opened 2016-11-11 11:29 UTC by iivic

@clintonb  @mjfrey  @vkaracic  Oscar is not validating the benefit type so I added this validation. Please note that I extend the oscar AbstractBenefit class and override the save method to do the validation before the model instance is saved. There will be more backend validation for the coupon form fields so confirm this is the right way to do it or provide another solution.
https://openedx.atlassian.net/browse/SOL-2111

2016-11-11 11:30 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1008"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-11-14 08:56 UTC, marjev commented
LGTM

2016-11-14 08:56 UTC, marjev approved these changes

2016-11-14 15:00 UTC, clintonb requested changes

2016-11-14 15:00 UTC, clintonb commented on ecommerce/extensions/api/v2/views/coupons.py
> +        except ValidationError as e:
1. Where is this actually being raised? Move the try-except there.
2. Log the exception with `logger.exception()`.

2016-11-14 15:00 UTC, clintonb commented on ecommerce/extensions/api/v2/views/coupons.py
> +            return HttpResponseBadRequest(e)
This is an API recall. You want to use DRF to properly serialize your error responses. See http://www.django-rest-framework.org/api-guide/exceptions/#validationerror.

2016-11-14 15:00 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +            raise ValidationError("Unrecognised benefit type {type}".format(type=self.type))
1. Single quotes.
2. Mark for translation.

2016-11-15 11:11 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +        except ValidationError as e:
1. It's raised in the benefit model https://github.com/edx/ecommerce/pull/1008/files#diff-49b6e1e79e2754be1784cc6dc9a1fe84R27. The documentation suggests that we should avoid catching exceptions inside atomic https://docs.djangoproject.com/en/1.9/topics/db/transactions/#controlling-transactions-explicitly that's why I do it here.

2016-11-15 11:37 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +            return HttpResponseBadRequest(e)
I don't understand what's wrong here. The documentation didn't help...

2016-11-15 12:40 UTC, clintonb commented on ecommerce/extensions/api/v2/views/coupons.py
> +            return HttpResponseBadRequest(e)
What you are returning will return a simple HTTP 400 with no body. [DRF's default error handler](http://www.django-rest-framework.org/api-guide/exceptions/#exception-handling-in-rest-framework-views) will serialize error responses with detail messages. We aren't necessarily using them today; but, we should stay in the habit ensuring all of our responses, success and error, are JSON and handled by DRF.

2016-11-15 12:41 UTC, clintonb commented on ecommerce/extensions/api/v2/views/coupons.py
> +        except ValidationError as e:
Got it. The exception should still be logged.

2016-11-15 13:55 UTC, iivic commented
@clintonb Comments addressed. Make sure I understood you correctly.

2016-11-15 14:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/coupons.py
> +            return Response({'error': e.message}, status=status.HTTP_400_BAD_REQUEST)
Raise [`ValidationError`](http://www.django-rest-framework.org/api-guide/exceptions/#validationerror), and DRF will handle the rest.

2016-11-15 14:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/coupons.py
> +            logger.exception(e.message)
`logger.exception()` already includes the original exception message. The message should here should be more informative.

2016-11-15 15:08 UTC, clintonb approved these changes
Remember to squash your commits.

2016-11-15 15:40 UTC, merged