Adding logs for payment processors
openedx-unsupported/ecommerce pull request #1009
Opened 2016-11-11 12:03 UTC by uzairr

## [ECOM-6155](https://openedx.atlassian.net/browse/ECOM-6155)

### Description
Following error continues to occur in ecommerce system.
`[checkout.py:43]` - Failed to get payment processor []`
In order to properly investigate this error, logs are added.

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review: @noraiz-anwar
- [ ] Code review: @Qubad786

FYI: @awaisdar001

### Post-review
- [ ] Rebase and squash commits

2016-11-11 12:03 UTC, edx-webhook commented
Thanks for the pull request, @uzairr! I've created [OSPR-1576](https://openedx.atlassian.net/browse/OSPR-1576) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/ecommerce/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2016-11-14 09:58 UTC, Qubad786 commented
@uzairr , we should be logging around https://github.com/edx/ecommerce/pull/1009/files#diff-a99d49b60ee66aa7a6b3d9666984c7caR44, so that we see these loggings on only `ProcessorNotFoundError ` exception.

2016-11-14 10:15 UTC, Qubad786 requested changes

2016-11-14 10:15 UTC, Qubad786 commented on ecommerce/extensions/api/v2/views/checkout.py
> +        logger.info('Starting Checkout process for basket with id: {0} has price: {1}'.format(basket_id, basket.total_excl_tax))
Should be changed to:
`logger.info('Starting checkout process for basket with id: [ %d ] having price: [ %d ]', basket_id, basket.total_excl_tax)`

2016-11-14 10:15 UTC, Qubad786 commented on ecommerce/extensions/basket/views.py
> +            logger.info('{}(Product) is available for purchase'.format(product))
Should be changed to:
`logger.info('Product: [ %s ] is available for purchase', product)`

2016-11-14 18:37 UTC, gsong commented
@uzairr Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but you only have to do this *once* and we're hoping you would make future contributions as well.

2016-11-16 09:24 UTC, noraiz-anwar submitted a review, later dismissed

2016-11-16 09:38 UTC, uzairr commented
@gsong -- I am part of Arbisoft Pvt Ltd. Please cover this PR under Arbisoft's contributor license agreement.
Thank You.

2016-11-16 15:53 UTC, schenedx commented on ecommerce/extensions/api/v2/views/checkout.py
>              payment_processor = get_processor_class_by_name(payment_processor)(request.site)
This assignment basically overrides the `payment_processor` string value with the instance returned. Can we update the `payment_processor` variable before this line to a new name like `payment_processor_name`?

2016-11-17 11:46 UTC, Qubad786 approved these changes

2016-11-17 11:46 UTC, Qubad786 commented
Looks good 👍 !

2016-11-17 15:05 UTC, schenedx approved these changes
👍

2016-11-18 11:37 UTC, noraiz-anwar commented
👍

2016-11-18 11:54 UTC, awaisdar001 commented
`This branch is out-of-date with the base branch`
I think its ready for merge after having the thumbs up. Is there any reason why haven't merged it? 

@uzairr Please rebase your branch. 
FYI: @adampalay

2016-11-18 13:29 UTC, uzairr commented
@gsong I am unable to merge this PR. Please give me permissions.
FYI: @awaisdar001

2016-11-18 13:34 UTC, adampalay commented
@awaisdar001 , you should merge this PR until @uzairr starts

2016-11-18 13:49 UTC, Qubad786 commented
@uzairr , in that case, i'm going to merge it for you.

2016-11-18 13:51 UTC, merged

2016-11-18 14:29 UTC, uzairr commented
Thank you @Qubad786 for the merge

2016-11-18 17:51 UTC, awaisdar001 commented
@Qubad786 Thank you, and Congratulations @uzairr for your first contribution in Edx.