Add error message template.
openedx-unsupported/ecommerce pull request #1010
Opened 2016-11-11 16:09 UTC by vkaracic

An increasing number of apps are displaying error message by copying
the structure of the coupon error message. This commit introduces a
general template for displaying error regardless of application.

https://openedx.atlassian.net/browse/SOL-2134

@iivic @marjev @mjfrey please review.

2016-11-11 16:09 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1010"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-11-14 08:26 UTC, marjev requested changes

2016-11-14 08:26 UTC, marjev commented on ecommerce/templates/edx/partials/_error.html
> +    {% blocktrans %}
I think you can remove the blocktrans.

2016-11-14 08:26 UTC, marjev commented on ecommerce/coupons/tests/test_views.py
> +    def test_invalid_code_voucher(self):
nitpick: test_invalid_voucher_code

2016-11-14 08:26 UTC, marjev commented on ecommerce/coupons/tests/test_views.py
> +    def test_invalid_voucher(self):
if you're already renaming the test method above, you can name this something like:
`test_expired_voucher`

2016-11-14 08:26 UTC, marjev commented on ecommerce/coupons/views.py
> +        return error_context
Perhaps we can dry this up a bit:
```
if code is None:
    # set error message
else:
   # do everything currently under if code is not None
   # set error messages accordingly

# update error context with error message only once
# return error context after it's sure the error template will be rendered
```

2016-11-14 08:26 UTC, marjev commented on ecommerce/coupons/views.py
> +        template_name = 'edx/partials/_error.html'
No. You should still use offer_error template and extend the "partial" template from there.

2016-11-14 08:26 UTC, marjev commented on ecommerce/coupons/views.py
same comment as above: I think we can dry this a bit.

Set error message for each case. Update context and render once everything is ready to rock and roll.

2016-11-14 08:26 UTC, marjev commented on ecommerce/templates/edx/partials/_error.html
> +{% endblock %}
This looks to me like a base template rather than a partial template.
Partials are injected in other templates when certain conditions are met.
This will be a base template for each error-specific template.

You should extend the base.html in this one, and extend this template in other error templates.

2016-11-14 10:55 UTC, vkaracic commented
@marjev I've changed the file structure as you said. There is now a base error template and the offer one extends it and adds a custom title to it, this way there is no need to send anything more than the error message in the context which makes the code simpler. Take another look please.

2016-11-14 11:34 UTC, iivic approved these changes

2016-11-14 11:38 UTC, marjev approved these changes

2016-11-14 12:40 UTC, merged

2016-11-14 12:43 UTC, vkaracic commented
Forgot to squash commits, sorry! :disappointed: