[WIP][SOL-2121] Implement SDN check
openedx-unsupported/ecommerce pull request #1012
Opened 2016-11-11 17:18 UTC by vkaracic

TBA

Dependency: https://github.com/edx/ecommerce/pull/1010

TODO:
- [ ] Change the error template once dependency lands
- [ ] Add/adjust documentation

2016-11-11 17:18 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1012"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-11-14 13:43 UTC, mjfrey commented on ecommerce/core/models.py
> +    def sdn_check_url(self, full_name):
need to add &address={query} to this.  Search on both full name and billing address.

2016-11-14 13:43 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> +    def get(self, *args, **kwargs):
Not going to call this here.  Will be called from the unified basket page once we have billing name and address.

2016-11-14 13:44 UTC, vkaracic commented on ecommerce/core/models.py
> +    def sdn_check_url(self, full_name):
Users don't have an address. We get the billing address for the payment processor after the payment has been made.

2016-11-14 13:45 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +    def get(self, *args, **kwargs):
Oh. So I should wait for that unified basket to land in order to see what information I can use from it then.

2016-11-14 13:45 UTC, mjfrey commented on ecommerce/core/models.py
> +    def sdn_check_url(self, full_name):
We will have the billing address from the client side payment page.  We need to use the purchaser name / address not the learner account name.

2016-11-15 18:54 UTC, mjfrey commented on ecommerce/extensions/payment/models.py
> +    sdn_check_response = JSONField()
I think we are going to want to pull out specific info from the response.  Let me check on this.

2016-12-01 20:54 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +        logger.info(
Make this a logger.error so we get a Splunk alert.  Also log the Full Name, basket id, and course trying to be purchased.

2017-01-11 12:28 UTC, mjfrey commented on ecommerce/core/models.py
> +            '&name={full_name}&address={address}&country={country}'
it is countries not country.

2017-01-11 12:40 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +            'Unable to connect to US Treasury SDN API. Status code [%d] with message: %s',
We need to log the basket id when this happens so we have a record for which transaction.

2017-01-24 15:24 UTC, mjfrey commented on ecommerce/extensions/payment/urls.py
> +    url(r'^sdn-failure/$', SdnFailure.as_view(), name='sdn-failure'),
SDNFailure.as_view
sdn_failure

2017-01-24 15:24 UTC, mjfrey commented on ecommerce/templates/oscar/checkout/sdn_failure.html
> +                    "Unfortunately, your account profile or payment information appears to match one or more records on a U.S. Treasury Department sanctions list. This means we cannot complete your t
No need for " around this message.

2017-01-26 12:19 UTC, marjev approved these changes
Nitpick comments. LGTM

2017-01-26 12:19 UTC, marjev commented on ecommerce/extensions/payment/models.py
> +        return _(u'{full_name} [{country}] - basket [{basket_id}]').format(
Import `from __future__ import unicode_literals`

2017-01-26 12:19 UTC, marjev commented on ecommerce/extensions/payment/tests/test_models.py
> +        self.failure_object = SDNCheckFailure.objects.create(
Create a factory

2017-01-26 12:19 UTC, marjev commented on ecommerce/extensions/payment/tests/test_models.py
> +        expected = u'{full_name} [{country}] - basket [{basket_id}]'.format(
`from __future__ import unicode_literals`

2017-01-26 12:19 UTC, marjev commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        self.assertNotIn('sdn_failure', response_content.keys())
No need to call `keys`

2017-01-26 12:19 UTC, marjev commented on ecommerce/extensions/payment/utils.py
> +import logging
Why is there an empty row between `re` and `json`?

2017-01-26 12:19 UTC, marjev commented on ecommerce/extensions/payment/utils.py
> +    else:
no need for else

2017-01-26 12:28 UTC, iivic approved these changes

2017-01-26 12:28 UTC, iivic commented on ecommerce/extensions/payment/models.py
> +        return _(u'{full_name} [{country}] - basket [{basket_id}]').format(
Nitpick: I don't see how this can be translated.

2017-01-26 15:36 UTC, mjfrey commented on ecommerce/extensions/payment/views/cybersource.py
> +        if not sdn_check(request, full_name, data['country']):
let's make this a waffle sample.  That way we can ramp up the percentage.  Like we did for the basket page.  This way we can monitor it before we go to 100%.

2017-01-26 17:33 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +    response = requests.get(site_config.sdn_check_url(full_name, country))
We should specify a timeout on this request.  We do not want to wait around and hangup the checkout process if the API is slow.

2017-01-27 14:31 UTC, mjfrey commented
@douglashall FYI

2017-01-30 14:56 UTC, mjfrey commented
@clintonb Please take a look.

2017-02-01 09:15 UTC, vkaracic commented
Since deactivating an account can only be done by the ecommerce worker, and since I have 0 experience with the ecommerce worker, to avoid multiple deployments to stage and reverts, I'd like to ask @clintonb to take a look at the last commit to see if it can be done that way. Basically what needs to happen is a POST request to the LMS account deactivation endpoint, made by the ecommerce worker. Can the ecom worker be authenticated to make the request with ``oauth_access_token`` or should I do it this way: https://github.com/edx/ecommerce-worker/blob/master/ecommerce_worker/utils.py#L60 ?

2017-02-01 17:11 UTC, clintonb requested changes

2017-02-01 17:11 UTC, clintonb commented on ecommerce/core/models.py
> +            '{sdn_api}/?sources={sdn_list}&api_key={sdn_key}&type=individual'
Use `urlencode` and `urllib.parse`.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/core/models.py
> +        """Deactive the user's account. Ecommerce worker is the only that has the necessary
Remove this talk about ecommerce worker. That is not actually relevant.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/core/models.py
> +            ecom_worker = User.objects.get(username=settings.ECOMMERCE_SERVICE_WORKER_USERNAME)
```python
site_configuration = site.siteconfiguration
user_api_client = EdxRestApiClient(site_configuration.build_lms_url('/api/user/v1'), jwt=site_configuration.access_token)
```

2017-02-01 17:11 UTC, clintonb commented on ecommerce/core/models.py
> +                oauth_access_token=ecom_worker.access_token
We should be using JWT authentication for all of our APIs. If the User API doesn't support JWT authentication, please update the API.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/core/models.py
> +        except (ConnectionError, SlumberBaseException, Timeout):
The exception type doesn't matter, especially since you are re-raising it.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/core/models.py
> +                'Failed to retrieve account details for [%s]',
`'Failed to deactivate account for user [%s]'`

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +    basket = models.ForeignKey('basket.Basket')
This field needs to support the case when we delete old baskets. `on_delete=models.SET_NULL`

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +        verbose_name = "SDN Check Failure"
Single quotes.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +        return '{full_name} [{country}] - basket [{basket_id}]'.format(
What's the use case for this? This is a lot of info. I worry that it will be too much when displayed in Django admin.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +        site_configuration = SiteConfigurationFactory(
Why not simply update `self.site.siteconfiguration`? Alternatively, you can update `SiteConfigurationFactory`.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +    def assert_sdn_check_failure(self, basket, response):
`assert_sdn_check_failure_recorded`

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        self.site.siteconfiguration.sdn_api_url = 'http://sdn.check'
Consider updating `SiteConfigurationFactory`.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +    def mock_sdn_check_api_response(self, results):
Why is there SDN code in the CyberSource test module? The two should be independent, so I would not expect to see any SDN code here. If there needs to be some form of integration test, the code should be refactored to avoid the co-mingling.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            logger.info('Connection to US Treasury SDN API timed out for basket [%d].', basket.id)
`logger.warning`

2017-02-01 17:11 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            logger.info(
`logger.warning`

2017-02-01 17:11 UTC, clintonb commented on ecommerce/settings/base.py
> +SDN_CHECK_REQUEST_TIMEOUT = 5
Include a comment denoting the units.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/static/js/payment_processors/cybersource.js
> +                        } else if (error.sdn_failure) {
We definitely should not have SDN-related JS here. The ultimate goal is to support additional payment processors. That doesn't scale if they all need to know about SDN.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/core/models.py
> +    def sdn_check_url(self, full_name, country):
This doesn't belong here. It would be ideal if the SDN code is confined to its own class:

```python
class SDNValidator(object):
  def __init__(self, api_url, api_key, api_list):
    ...

  def search(self, name, country):
     ...
```

2017-02-01 17:11 UTC, clintonb commented on ecommerce/templates/oscar/checkout/sdn_failure.html
> +{% block title %}{% endblock %}
You need a title.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/templates/oscar/checkout/sdn_failure.html
> +                    Unfortunately, your account profile or payment information appears to match one or more records on a U.S. Treasury Department sanctions list. This means we cannot complete your tr
Use a line break to make this legible for development.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/templates/oscar/checkout/sdn_failure.html
> +    <div id="error-message">
Nit: this should be a class, not an ID.

2017-02-01 17:11 UTC, clintonb commented on ecommerce/templates/oscar/checkout/sdn_failure.html
> +                <h3>SDN check failure.</h3>
SDN Check Failure

2017-02-02 07:39 UTC, vkaracic commented on ecommerce/extensions/payment/models.py
> +        return '{full_name} [{country}] - basket [{basket_id}]'.format(
To have a quick overview of all the matches, should be easier to find someone instead of searching through each object. I don't think it will be too much, the country is two characters and basket_id just a number. Perhaps I should change the full name to username?

2017-02-02 17:58 UTC, vkaracic commented
@clintonb I believe I have addressed all the comments. Can you take another look please?

2017-02-02 18:57 UTC, mjfrey requested changes

2017-02-02 18:57 UTC, mjfrey commented on ecommerce/core/models.py
> +    def deactivate(self, site_configuration):
deactivate_user_account

2017-02-02 18:57 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/sdn_check.py
> +class SDNCheckViewSet(APIView):
The only problem I have with this is any logged in user can call this endpoint.  Do we want that? Can this be part of the payment form validation on the server?  Have it be a mixin so it is not payment processor specific?

2017-02-02 20:28 UTC, clintonb requested changes

2017-02-02 20:28 UTC, clintonb commented on ecommerce/core/models.py
> +            return response
Nit: single line

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +class SDNValidator(object):
`SDNClient`

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +    basket = models.ForeignKey('basket.Basket', blank=True, null=True, on_delete=models.SET_NULL)
How/why is the basket relevant?

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +                account_deactivated=request.user.has_usable_password(),
This is not the correct method to use. At no point do we set the user's password on Otto.

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            request.user.deactivate(request.site.siteconfiguration)
You should record the response before attempting to deactivate the account. If the account deactivation fails, you will have no record of the SDN failure.

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +    def search(self, request, name, country):
Pass in the basket, if it's actually needed, and pull the user and site from it. Avoid relying on `Request` objects, as that makes testing difficult and limits the usefulness of the class.

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            if response.status_code != status.HTTP_200_OK:
Use `200`. There is no need to introduce a DRF dependency here.

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn_check.py
> +        if not sdn_check.search(request, name, country):
A bit more future-proofing. We made the mistake with the Refunds API of making assumption about our responses. I would make `sdn_check.search` return the number of hits, instead of a simple boolean. This allows the API to later be expanded, if necessary. Additionally, your client(s) can make decisions on their own regarding how to interpret the data. In this specific case that may not be useful; but, we should still maintain good API practices.

`return Response({'hits': sdn_check.search(request, name, country)})`

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^sdn-check/$', sdn_check_views.SDNCheckViewSet.as_view(), name='sdn_check')
Future-proof this with name-spacing. This should be at `/sdn/search/`.

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn_check.py
> +"""API endpoint for performing an SDN check on users."""
`views/sdn.py`

2017-02-02 20:28 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn_check.py
> +from rest_framework.permissions import IsAuthenticated
Alphabetize.

2017-02-02 21:34 UTC, mjfrey commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^sdn-check/$', sdn_check_views.SDNCheckViewSet.as_view(), name='sdn_check')
@clintonb Do you think this is ok to have this public endpoint?  Meaning anyone logged into Otto can call this directly.

2017-02-02 21:35 UTC, vkaracic commented on ecommerce/extensions/payment/models.py
> +    basket = models.ForeignKey('basket.Basket', blank=True, null=True, on_delete=models.SET_NULL)
@mjfrey is the basket relevant?

2017-02-02 21:38 UTC, mjfrey commented on ecommerce/extensions/payment/models.py
> +    basket = models.ForeignKey('basket.Basket', blank=True, null=True, on_delete=models.SET_NULL)
No.

2017-02-02 21:48 UTC, clintonb commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^sdn-check/$', sdn_check_views.SDNCheckViewSet.as_view(), name='sdn_check')
Not really, no. The issue I see with leaving this open is that the learner can potentially lock him/herself out of an account if the wrong name is entered or country selected. That's a problem, whether this is open or locked down, so I'll leave it to you to ponder/decide.

Did we do any analysis of how many existing users this might affect? If we look at every user who has placed an order in the past year, how many might be locked out by this?

2017-02-02 22:00 UTC, mjfrey commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^sdn-check/$', sdn_check_views.SDNCheckViewSet.as_view(), name='sdn_check')
No, not yet.  Good idea.

2017-02-03 08:07 UTC, vkaracic commented on ecommerce/extensions/payment/utils.py
> +    def search(self, request, name, country):
It seems that the basket is not necessary, but in this case the request is needed to check if the waffle flag is active.

2017-02-03 13:37 UTC, vkaracic commented
@clintonb comments addressed! Please don't mind the failing JS test, I'm still working on it. Can you please take another look?

2017-02-03 14:52 UTC, clintonb requested changes

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn.py
> +        site_configuration = request.site.siteconfiguration
Do your waffle checking here.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +    def search(self, request, name, country):
If the flag isn't on, we shouldn't even call this method. Do the switching in the code that calls this method.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            The number of matches that have been found on the SDN list for the user.
int: The number....

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            elif json.loads(response.content)['total'] == 0:
This can be cleaned up...

```python
response = response.json()
total = response['total']

if total > 0:
  # Log SDN failure

return total
```

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            sdn_failure = SDNCheckFailure.objects.create(
After further thought, this should be a separate method. `search` should only worry about search. A separate method, `deactivate_user`, should worry about user deactivation. Why? 

1. This separation keeps the code cleaner, by ensuring that each method does one thing well.
2. This separation allows us to use the `search` method later (e.g. for debugging) without fear of deactivating a user.


```python
from django.conf import settings


class SDNClient(object):
    def __init__(self, api_url, api_key, sdn_list):
        self.api_url = api_url
        self.api_key = api_key
        self.sdn_list = sdn_list
        self.timeout = settings.SDN_CHECK_REQUEST_TIMEOUT

    def search(self, name, country):
        """ Searches the OFAC list for an individual with the specified details.

        Args:
            name (str): Full name.
            country (str): ISO 3166-1 alpha-2 country code.

        Returns:
            dict: Search results.

        Raises:
            Timeout: if the request to the external API times out.
        """
        pass

    def deactivate_user(self, user, search_results):
        """ Deactivates a user account.

        Args:
            user (User): User whose account should be deactivated.
            search_results (dict): Results from a call to `search` that will
                be recorded as the reason for the deactivation.
        """
        pass

```

2017-02-03 14:52 UTC, clintonb commented on ecommerce/static/js/pages/basket_page.js
> +            console.log('got here');
Remove.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +        if waffle.flag_is_active(request, SDN_CHECK_FLAG_NAME):
Actually...why is `waffle` necessary? Use `SiteConfiguration.enable_sdn_check`.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/static/js/pages/basket_page.js
> +                sdnCheck(e);
This should only be called if SDN validation is active for the site.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/urls.py
> +    url(r'^sdn-failure/$', SDNFailure.as_view(), name='sdn_failure'),
`sdn/failure`

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +    created = models.DateTimeField(auto_now_add=True)
Inherit `TimeStampedModel`, and this can go away.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/admin.py
> +admin.site.register(SDNCheckFailure)
Put yourself in the shoes of someone tracking down an SDN failure. We're going to need search—on user.username and user.email—and a more useful list view—without the search results.

General rule of thumb: if a model is worth adding to the admin (and most are), customize it to make it truly useful.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
> +        self.assertEqual(self.make_request().status_code, status.HTTP_200_OK)
Without mocking, this call will simply wait for the API call to fail. This will further increase the time it takes to run tests. Remove this line since this test only wants to validate that unauthenticated users are turned away.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
> +            self.assertEqual(json.loads(response.content)['hits'], sdn_hits)
Add: `self.assertTrue(sdn_validator_mock.called)`

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +        BasketFactory(owner=self.request.user, site=self.request.site)
This is not needed.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +        BasketFactory(owner=self.request.user, site=self.request.site)
This is not needed.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +from oscar.test.factories import BasketFactory
This is not needed.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +        self.request = RequestFactory()
You should not need to make any changes to `self.request`.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +        self.request.site = self.site_configuration.site
Remove, along with the other changes to `self.request`.

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +        self.site_configuration = SiteConfigurationFactory(
You're duplicating a lot of work done by the base `TestCase` class:

```python
self.site_configuration = self.site.siteconfiguration
self.site_configuration. enable_sdn_check = True
...
self.site_configuration.save()
```

2017-02-03 14:52 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_utils.py
> +@override_flag(SDN_CHECK_FLAG_NAME, active=True)
This should not be needed if we're relying on `SiteConfiguration`.

2017-02-03 14:56 UTC, vkaracic commented on ecommerce/extensions/payment/utils.py
> +        if waffle.flag_is_active(request, SDN_CHECK_FLAG_NAME):
@mjfrey should we drop the waffle requirement?

2017-02-03 15:11 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +                'country': country
This should be countries not country.

2017-02-03 15:12 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +        if waffle.flag_is_active(request, SDN_CHECK_FLAG_NAME):
Product wants to do a percentage based rollout so we can monitor and make sure we are not getting false positives.

2017-02-03 16:05 UTC, vkaracic commented on ecommerce/static/js/pages/basket_page.js
> +                sdnCheck(e);
A GET endpoint on the SDN API that serves information if SDN is active or not, or a context variable in the basket view to send to the JS part?

2017-02-03 16:06 UTC, clintonb commented on ecommerce/static/js/pages/basket_page.js
> +                sdnCheck(e);
Context variable.

2017-02-06 08:14 UTC, vkaracic commented on ecommerce/extensions/payment/utils.py
> +            sdn_failure = SDNCheckFailure.objects.create(
Should the ``search`` method raise ``Timeout``? The idea was to silently fail and log the failure. That way if the Treasury API goes down it won't cause all payments to fail on our side.

2017-02-06 08:36 UTC, vkaracic commented on ecommerce/extensions/payment/utils.py
> +            sdn_failure = SDNCheckFailure.objects.create(
Actually is this class needed? I think I could move all of this to the SDN API endpoint.

2017-02-06 14:44 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            json: SDN API response.
Return the `dict`. There is no need to make the callers have to convert JSON to a `dict`.

2017-02-06 14:44 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +        if response.status_code != 200:
Ideally, you should raise an exception here and above. We should avoid special return values where possible. In the past I've established a base exception class (e.g. `SDNClientError`) and caught that. Given that the response to a timeout and a server error will be the same, you can differentiate with an error message rather than subclasses. If, however, we chose to retry a timeout, you'd want to make an appropriate exception subclass.

2017-02-06 14:57 UTC, davec-edx commented on ecommerce/extensions/payment/utils.py
> +        # TODO: Check if the user has actually been deactivated
Does this TODO still need to be done?

2017-02-06 15:17 UTC, mjfrey approved these changes
Once last couple comments addressed.

2017-02-06 15:30 UTC, davec-edx commented on ecommerce/extensions/payment/utils.py
> +        logger.warning('SDN check failed for user [%s]', search_results['name'])
I'm not following what's happening here.  user.deactivate_account is being called, which returns a value if successful or throws an error if not.  Then we're always logging a warning about the SDN check failing.

2017-02-06 15:53 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +        logger.warning('SDN check failed for user [%s]', search_results['name'])
We always will log a positive SDN match regardless of user deactivation.

2017-02-06 16:27 UTC, davec-edx commented on ecommerce/extensions/payment/utils.py
> +        logger.warning('SDN check failed for user [%s]', search_results['name'])
Let me rephrase:

Primarily: If we call call into deactivate_account and it throws an error we will never hit the log message so perhaps the logging (line 135) should come before the call to deactivate.

Secondarily, if we call deactivate_account and it doesn't throw an error, we're never doing anything with the results of the POST (such as checking the return code for success); will that cause an inconsistency anyplace?  Will that appear to be a successful deactivation when in reality it wasn't?

2017-02-07 03:05 UTC, clintonb requested changes

2017-02-07 03:05 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn.py
> +        if waffle.flag_is_active(request, SDN_CHECK_FLAG_NAME) and site_configuration.enable_sdn_check:
Ditch `waffle`. It makes no sense. We are either using SDN, or we are not. FYI @mjfrey

2017-02-07 03:05 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +    country = models.CharField(max_length=255)
Country codes should be 2 characters.

2017-02-07 03:05 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            full_name=search_results['name'],
These should be separate arguments. Don't overload the search response argument in this manner.

2017-02-07 03:05 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn.py
> +            response = json.loads(sdn_check.search(name, country))
No need for `json.loads()` here.

2017-02-07 08:44 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/sdn.py
> +        if waffle.flag_is_active(request, SDN_CHECK_FLAG_NAME) and site_configuration.enable_sdn_check:
Since this decision is a bit over my rank I'll let you guys (+ @edx/product) discuss it.

2017-02-07 14:37 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/sdn.py
> +        if waffle.flag_is_active(request, SDN_CHECK_FLAG_NAME) and site_configuration.enable_sdn_check:
@clintonb @vkaracic We can remove the waffle switch.  We will just turn on / off as needed.

2017-02-08 14:12 UTC, vkaracic commented
@clintonb comments addressed, please take another look.

2017-02-08 14:31 UTC, clintonb requested changes

2017-02-08 14:31 UTC, clintonb commented on ecommerce/core/models.py
> +        blank=True,
`blank` is not applicable here.

2017-02-08 14:31 UTC, clintonb commented on ecommerce/core/models.py
> +        help_text=_('US Treasury SDN API key.'),
If the verbose name and help text are the same, the help text needs to go.

2017-02-08 14:31 UTC, clintonb commented on ecommerce/core/models.py
> +        help_text=_('US Treasury SDN API URL.'),
If the verbose name and help text are the same, the help text needs to go.

2017-02-08 14:31 UTC, clintonb commented on ecommerce/core/models.py
> +            api = EdxRestApiClient(
Nit: Move this to `SiteConfiguration.user_api_client`.

2017-02-08 14:31 UTC, clintonb commented on ecommerce/core/models.py
> +        except:  # pragma: no cover pylint: disable=bare-except
`# pragma: no cover` is not acceptable here. You need to test the failure case.

2017-02-08 14:31 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
> +                self.make_request()
You need to validate the view's response.

2017-02-08 14:31 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +        return 'SDN check failure [{username}]'.format(  # pragma: no cover
This is a very easy to test to write. Also, it should return a Unicode string.

2017-02-08 14:31 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +        if response.status_code != 200:
This needs to be addressed.

2017-02-08 14:31 UTC, clintonb commented on ecommerce/static/js/pages/basket_page.js
> +                sdnCheck(e);
This needs to be addressed.

2017-02-08 14:43 UTC, vkaracic commented on ecommerce/core/models.py
> +        except:  # pragma: no cover pylint: disable=bare-except
Test that a log entry was created?

2017-02-08 14:46 UTC, clintonb commented on ecommerce/core/models.py
> +        except:  # pragma: no cover pylint: disable=bare-except
Yes. If it's worth logging, it's worth testing.

2017-02-08 14:47 UTC, clintonb commented on ecommerce/core/models.py
> +        except:  # pragma: no cover pylint: disable=bare-except
Otherwise, drop the exception handler.

2017-02-08 15:57 UTC, vkaracic commented on ecommerce/extensions/payment/models.py
> +        return 'SDN check failure [{username}]'.format(  # pragma: no cover
I understand that it's not necessary to prefix a string with ``u`` if ``from __future__ import unicode_literals`` is imported?

2017-02-08 16:53 UTC, vkaracic commented on ecommerce/extensions/payment/utils.py
> +        if response.status_code != 200:
I'm inclined not to subclass new exception classes. For the above case a ``Timeout`` exception could be raised. For this one I'm thinking maybe ``HTTPError('Unable to connect to SDN API')``?

2017-02-09 09:46 UTC, vkaracic commented
@clintonb comments addressed.

2017-02-09 14:06 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/sdn.py
> +            hits = response['total']
You might want to use response.get in case response does not contain 'total'

2017-02-09 15:01 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn.py
> +            hits = response['total']
Given this is from the Treasury API, there should always be a `'total'` key. Otherwise, they've violated their API contract. The government would *never* do that!

2017-02-09 15:07 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/sdn.py
> +            hits = response['total']
![b5af8c5a51915aa14b9bcf695fd01e954610f9dbdd162beea1e58201b0e1b253](https://cloud.githubusercontent.com/assets/2808092/22788937/b9bb5aae-eee1-11e6-999b-72d2d71d4f7d.jpg)

2017-02-09 15:13 UTC, clintonb approved these changes

2017-02-09 15:13 UTC, clintonb commented on ecommerce/core/models.py
> +        help_text=_('A comma seperated list of Treasury OFAC lists to check against.'),
Nit: comma-separated

2017-02-09 15:13 UTC, clintonb commented on ecommerce/core/models.py
> +        return EdxRestApiClient(self.build_lms_url('/api/user/v1/'), jwt=self.access_token)
Does this need `append_slash=False`?

2017-02-09 15:13 UTC, clintonb commented on ecommerce/core/models.py
>              api = EdxRestApiClient(
`request.site_configuration.user_api_client`

2017-02-09 15:13 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn.py
> +            hits = response['total']
/s

2017-02-09 15:13 UTC, clintonb commented on ecommerce/extensions/payment/admin.py
> +    show_full_result_count = False
Nit: I highly doubt we will get enough hits—order of hundreds of thousands—for this to matter.

2017-02-09 15:13 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +        return 'SDN check failure [{username}]'.format(  # pragma: no cover
Get rid of the `# pragma: no cover`.

2017-02-09 15:13 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +            'sdn_check': 'enabled' if site_configuration.enable_sdn_check else 'disabled'
Just use `True` or `False`. Avoid the special strings.

2017-02-09 15:13 UTC, clintonb approved these changes

2017-02-09 15:20 UTC, vkaracic commented on ecommerce/core/models.py
> +        return EdxRestApiClient(self.build_lms_url('/api/user/v1/'), jwt=self.access_token)
That depends. For account details endpoint there is no trailing slash, but for the deactivation endpoint there is.

2017-02-09 17:15 UTC, merged

2017-02-09 17:26 UTC, clintonb commented on ecommerce/static/js/pages/basket_page.js
> +                if ($('input[name=sdn-check]').val() === 'enabled') {
This needs to be updated since the value was changed to `True`/`False`.

2017-02-09 17:27 UTC, vkaracic commented on ecommerce/static/js/pages/basket_page.js
> +                if ($('input[name=sdn-check]').val() === 'enabled') {
I've changed the template as well:
https://github.com/edx/ecommerce/pull/1012/files#diff-67f74e748e826f7ceb2290e1f960a1f1R139