[SOL-2137] Add Backend Validation for Coupon Creation - Benefit Value
openedx-unsupported/ecommerce pull request #1017
Opened 2016-11-16 12:54 UTC by iivic

Values for benefit value that are not allowed: string, empty, negative numbers, when benefit type 'Percentage' max value is 100. https://openedx.atlassian.net/browse/SOL-2137
@vkaracic @mjfrey @marjev  Please review.

2016-11-16 12:54 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1017"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-11-16 13:15 UTC, vkaracic requested changes

2016-11-16 13:15 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +import logging
Alphabetize this please. :)

2016-11-16 13:15 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +        if self.value < 0:
And what happens if it's > 100?

2016-11-16 13:15 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +                'Failed to create Benefit. Benefit value may not be a negative number.'
This and the logger message above can fit in one line.

2016-11-16 13:18 UTC, iivic commented on ecommerce/extensions/offer/models.py
> +        if self.value < 0:
Oscar validates this case if the type is Percentage oscar raises a ValidationError if the type is 'Absolute' nothing happens.

2016-11-16 14:07 UTC, iivic commented
@clintonb

2016-11-16 15:57 UTC, vkaracic approved these changes
LGTM

2016-11-16 17:25 UTC, clintonb approved these changes
Remember to squash your commits.

2016-11-17 07:25 UTC, marjev requested changes

2016-11-17 07:25 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> -        ({'category': {'a': 'a', 'b': 'b'}}, status.HTTP_400_BAD_REQUEST),
Why is this removed? This should still fail and is there as something that can happen and should return at least 400 BAD REQUEST status or something better.

2016-11-17 08:14 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> -        ({'category': {'a': 'a', 'b': 'b'}}, status.HTTP_400_BAD_REQUEST),
It's not removed I moved it to `test_create_coupon_product_invalid_data` test method.

2016-11-17 09:23 UTC, marjev approved these changes

2016-11-17 10:40 UTC, merged