This prevents errors in attribute_cookie_data from rolling back all basket-related transactions.
openedx-unsupported/ecommerce pull request #1022
Opened 2016-11-17 20:23 UTC by schenedx

@edx/ecommerce Please review
This is to fix the issue in ECOM-6366 for the long term

2016-11-18 16:35 UTC, rlucioni requested changes

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +        """ Verify a basket is returned and referral captured if there are cookie info """
"if there is no cookie info"

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +        # If there are no cookie info, no referral captured
"If there is no cookie info, verify no referral is created."

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +        # Make sure no referral is created
This comment adds no value.

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +        # If there are cookie info, the referral is captured
"If there is cookie info, verify a referral is created."

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +            Verify db error raised from attributing cookie to basket
Nitpick: let's try to keep our docstrings consistent, please. We don't typically indent like this.
```py
"""
Verify that an IntegrityError raised while creating a referral
does not prevent a basket from being created.
"""
```

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +                # Mock to return a duplicated referral object, so when saved, a DB integrity error is raised
Please add a comment about how mocking an exception as a side effect doesn't trigger a rollback. That's valuable knowledge we don't want to lose.

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +class BasketUtilsTranactionTests(UserMixin, TransactionTestCase):
BasketUtilsTransactionTests

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +    def test_attribution_atomic_transation(self):
test_attribution_atomic_transaction

2016-11-18 16:35 UTC, rlucioni commented on ecommerce/extensions/basket/utils.py
> +            # Required to prevent rolling back other atomic commits if exception is found
You can add a little more detail here:
```py
# If an exception is raised below, this nested atomic block prevents the
# outer transaction created by ATOMIC_REQUESTS from being rolled back.
```

2016-11-18 16:38 UTC, MatthewPiatetsky commented on requirements/test.txt
> +coverage==4.2
is there a reason we're not specifying the patch version here?

2016-11-18 16:55 UTC, rlucioni commented on requirements/test.txt
> +coverage==4.2
@MatthewPiatetsky the coverage package doesn't specify one: https://pypi.python.org/pypi/coverage.

2016-11-18 16:55 UTC, MatthewPiatetsky commented on ecommerce/extensions/basket/utils.py
>      except:  # pylint: disable=broad-except, bare-except
Do we want to differentiate an IntegrityError due to the atomic condition vs other unrelated errors?

2016-11-18 16:55 UTC, rlucioni commented on ecommerce/extensions/basket/utils.py
>      except:  # pylint: disable=broad-except, bare-except
Any exceptions raised in this block will trigger a rollback of the inner block.

2016-11-18 18:16 UTC, schenedx commented on ecommerce/extensions/basket/tests/test_utils.py
> +        """ Verify a basket is returned and referral captured if there are cookie info """
@rlucioni should be `if there is cookie info`. We should not have referral captured if there is no cookie info

2016-11-18 18:25 UTC, schenedx commented
@rlucioni Could you please review again?

2016-11-18 19:24 UTC, bderusha commented on ecommerce/extensions/basket/utils.py
>      except:  # pylint: disable=broad-except, bare-except
@MatthewPiatetsky I don't think we do.  The point is to log, but not raise any issues that happen during attribution

2016-11-18 19:27 UTC, bderusha approved these changes
👍

2016-11-18 22:07 UTC, rlucioni reviewed
@schenedx looks good, just one last small thing.

2016-11-18 22:07 UTC, rlucioni commented on ecommerce/extensions/basket/tests/test_utils.py
> +                # This would result in the transaction being committed
Thanks for adding this. However, are we sure that what you've written is entirely true? We don't want to mislead future maintainers with false assumptions. We know that using a mock side effect to raise an exception isn't enough to trigger a rollback, and we know that forcing a genuine IntegrityError is. Unless we know why that is, I wouldn't go any further here.

2016-11-21 19:27 UTC, schenedx commented
@rlucioni Took in your last feedback. Can you review and comment?

2016-11-21 21:28 UTC, rlucioni approved these changes

2016-11-21 21:57 UTC, merged