[SOL-1955] Add interstitial for CyberSource payments
openedx-unsupported/ecommerce pull request #1025
Opened 2016-11-20 08:58 UTC by marjev

@clintonb Here's a separate PR for Interstitial CyberSource View. We can continue discussion here.

Related story: https://openedx.atlassian.net/browse/SOL-1955

FYI
@mjfrey @vkaracic

2016-11-20 08:58 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1025&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-11-20 17:42 UTC, clintonb requested changes
I have updated the ticket to better describe the intent of these changes. Notably, you are not processing transaction responses in the new view.

2016-11-20 17:42 UTC, clintonb commented on ecommerce/extensions/checkout/mixins.py
> +            response(HttpRedirectResponse): Redirect Response.
Redirect to the specified receipt page URL.

2016-11-20 17:42 UTC, clintonb commented on ecommerce/extensions/checkout/mixins.py
> +            receipt_page_url(str): Receipt Page URL
Lower case "page".

2016-11-20 17:42 UTC, clintonb commented on ecommerce/extensions/checkout/mixins.py
> +        Arguments:
Add a newline before this.

2016-11-20 17:42 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_views.py
> +class CybersourceInterstitialViewTests(RefundTestMixin, TestCase):
This view has nothing to do with refunds, so that mixin should not be included. It might be simpler to inherit `CybersourceNotifyViewTests`.

2016-11-20 17:42 UTC, clintonb commented on ecommerce/extensions/payment/views.py
> +    def post(self, request, *args, **kwargs):  # pylint: disable=unused-argument
You need to take advantage of the logic of `CybersourceNotifyView` here to actually process the response from CyberSource.

2016-12-02 11:36 UTC, marjev commented on ecommerce/extensions/payment/tests/test_views.py
> +class CybersourceInterstitialViewTests(RefundTestMixin, TestCase):
I included that mixin because it had order creation method.
I'll create a new mixin for that purpose and make the necessary changes.

2016-12-02 23:29 UTC, clintonb requested changes

2016-12-02 23:29 UTC, clintonb commented on ecommerce/extensions/checkout/mixins.py
> +    def redirect_to_receipt_page_on_success(self, request, receipt_page_url):
This method is only used by `CybersourceInterstitialView`. Move it there.

2016-12-02 23:29 UTC, clintonb commented on ecommerce/extensions/offer/tests/mixins.py
> +class OfferTestMixin(CourseCatalogTestMixin):
This has nothing to do with offers, and does not belong here. Now that I see your use case, this mixin is not necessary. Oscar has an `OrderFactory`. Use it for your new tests and leave `RefundTestMixin` alone.

2016-12-02 23:29 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        order = self.create_order()
Use Oscar's `OrderFactory`.

2016-12-02 23:29 UTC, clintonb commented on ecommerce/extensions/payment/views/cybersource.py
> +        # CyberSource responses will indicate whether a payment failed due to a transaction on their end. In this case,
This implementation is still wrong. The purpose of subclassing `CybersourceNotifyView` is to take advantage of its ability to create orders. Let's pretend we got rid of the `/payment/cybersource/notify/` endpoint. Under that scenario I expect this view (`CybersourceInterstitialView`) at `/payment/cybersource/redirect/` to be able to process the CyberSource response. That's the end goal of the interstitial: do the work of `CybersourceNotifyView` and redirect the user to the receipt page.

2016-12-05 08:50 UTC, marjev commented on ecommerce/extensions/checkout/mixins.py
> +    def redirect_to_receipt_page_on_success(self, request, receipt_page_url):
It should also be used in the PayPal scenarios, right?

2016-12-05 09:18 UTC, marjev commented on ecommerce/extensions/payment/views/cybersource.py
> +        # CyberSource responses will indicate whether a payment failed due to a transaction on their end. In this case,
I still haven't got to this. I'm working on fixing the tests and increasing coverage.

2016-12-05 13:19 UTC, clintonb commented on ecommerce/extensions/checkout/mixins.py
> +    def redirect_to_receipt_page_on_success(self, request, receipt_page_url):
No. This is only necessary for CyberSource. We already do something similar for PayPal, and we do not want to mix payment processing code.

2016-12-06 09:28 UTC, marjev commented
@clintonb, could you please take another look? I think I addressed all comments and I think that Interstitial View now has everything we need.

2016-12-06 18:12 UTC, clintonb requested changes
The shared code must be extracted to a mixin, not duplicated.

2016-12-06 18:12 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        self.cybersource_processing_failure_status_code = 502
This should not differ from the value returned by `CybersourceNotifyViewTests`.

2016-12-06 18:12 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +class CybersourceInterstitialViewTests(CybersourceNotifyViewTests, TestCase):
`CybersourceNotifyViewTests` already inherits `TestCase`.

2016-12-06 18:12 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        self.go_to_receipt_page_status_code = 200
`CybersourceNotifyView` doesn't know/care about receipts. `successful_payment_status_code` is more appropriate.

2016-12-06 18:12 UTC, clintonb commented on ecommerce/extensions/payment/views/cybersource.py
> +        # Note (CCB): Orders should not be created until the payment processor has validated the response's signature.
This code appears to be copied verbatim from `CybersourceNotifyView`. Don't copy code. Extract it to a mixin.

2016-12-06 18:12 UTC, clintonb commented on ecommerce/extensions/payment/views/cybersource.py
> +class CybersourceInterstitialView(CybersourceNotifyView, TemplateView):
Keep this view simple. It should only be redirecting. In the case of a successful payment, redirect to the receipt page. In the case of a failed payment, redirect to an error page. The error page doesn't need to be processor-specific (e.g. /payment/error/). Just remember to thaw the basket so the user can attempt payment again.
![image](https://cloud.githubusercontent.com/assets/910510/20937250/202a53f0-bbb4-11e6-814b-0c3e2682faad.png)

2016-12-06 18:12 UTC, clintonb commented on ecommerce/templates/oscar/checkout/cybersource_error.html
> +        A system error occurred while processing your payment. <b>You have not been charged.</b>
Use `<strong>` instead of `<b>`

2016-12-06 18:12 UTC, clintonb commented on ecommerce/tests/mixins.py
> +    def toggle_ecommerce_receipt_page(self, enable_otto_receipt_page):
Given that this is only used in one place, I'm not sure how useful it is as a method.

2016-12-06 18:12 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +class CybersourceInterstitialViewTests(CybersourceNotifyViewTests, TestCase):
Also, at no point are you testing the rendering of the error page.

2016-12-07 11:44 UTC, marjev commented on ecommerce/extensions/payment/views/cybersource.py
> +class CybersourceInterstitialView(CybersourceNotifyView, TemplateView):
Is this ok:
```
def post(self, request, *args, **kwargs):  # pylint: disable=unused-argument
        """Process a CyberSource merchant notification and place an order for paid products as appropriate."""

        cybersource_response = request.POST.dict()
        order_number = cybersource_response.get('req_reference_number')

        if cybersource_response.get('decision') != 'ACCEPT':
            basket_id = OrderNumberGenerator().basket_id(order_number)
            basket = self._get_basket(basket_id)
            if basket:
                basket.thaw()
                redirect(reverse('checkout:error'))
        else:
            shipping_charge = shipping_method.calculate(basket)
            self.handle_order_placement(
                order_number,
                basket.owner,
                basket,
                None,
                NoShippingRequired(),
                shipping_charge,
                self._get_billing_address(cybersource_response),
                OrderTotalCalculator().calculate(basket, shipping_charge),
                request=request
            )
            receipt_page_url = get_receipt_page_url(
                order_number=order_number,
                site_configuration=self.request.site.siteconfiguration
            )
            self._redirect_to_receipt_page_on_success(request, receipt_page_url)
```

I assumed that txn is the same thing that's used on the LMS receipt page. If it's not, I need an explanation of what it stands for, how it's used and where we use it.

2016-12-07 16:39 UTC, clintonb commented on ecommerce/extensions/payment/views/cybersource.py
> +class CybersourceInterstitialView(CybersourceNotifyView, TemplateView):
Not quite. See https://github.com/edx/ecommerce/commits/clintonb/payment-explain.

2016-12-12 15:01 UTC, marjev commented on ecommerce/tests/mixins.py
> +    def toggle_ecommerce_receipt_page(self, enable_otto_receipt_page):
This is shared with #978

2016-12-12 15:01 UTC, marjev commented
@clintonb Can you please take another look?

2016-12-12 17:27 UTC, mjfrey commented on ecommerce/extensions/checkout/utils.py
> +        base_url = site_configuration.build_ecommerce_url(settings.RECEIPT_PAGE_PATH)
Do not use settings.RECEIPT_PAGE_PATH but rather make this a constant within the processor itself.  We can avoid changing settings files as well as have an endpoint per processor.

2016-12-12 19:04 UTC, mjfrey requested changes

2016-12-12 19:04 UTC, mjfrey commented on ecommerce/extensions/payment/views/cybersource.py
> +class CybersourceInterstitialView(CybersourceNotificationMixin, View):
you are missing @method_decorator(csrf_exempt)
This throws an error when cybersource tries to POST back.

2016-12-13 05:34 UTC, clintonb commented on ecommerce/extensions/checkout/utils.py
> +        base_url = site_configuration.build_ecommerce_url(settings.RECEIPT_PAGE_PATH)
Agreed. This PR shouldn't deal with receipts at all aside from redirecting the user there. I understand this was extracted from the receipt page PR; but, let's keep the two separated to avoid confusion and maintain independence.

2016-12-13 05:34 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> -    @ddt.data(
Why was all of this removed?

2016-12-13 05:34 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> -    def test_unable_to_place_order(self):
Why is this change necessary?

2016-12-13 05:34 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +class CybersourceInterstitialViewTests(CybersourceMixin, TestCase):
Similar to the view being tested, you should extract the appropriate tests from `CybersourceNotifyViewTests` to a mixin shared with `CybersourceInterstitialViewTests` in order to fully test the view.

2016-12-13 05:34 UTC, clintonb commented on ecommerce/extensions/payment/urls.py
> +    url(r'^payment/error/$', PaymentFailedView.as_view(), name='payment_error'),
Keep these alphabetized. See `lms/urls.py` on edx/edx-platform to understand my desire for order.

2016-12-13 05:34 UTC, clintonb commented on ecommerce/extensions/payment/urls.py
> +    url(r'^payment/error/$', PaymentFailedView.as_view(), name='payment_error'),
Also, no need for the payment prefix on the path. That's already taken care of.

2016-12-13 05:34 UTC, clintonb commented on ecommerce/extensions/payment/views/cybersource.py
> +class CybersourceInterstitialView(CybersourceNotificationMixin, View):
This can be resolved by moving the `dispatch` method to `CybersourceNotificationMixin`.

2016-12-13 05:34 UTC, clintonb commented on ecommerce/templates/oscar/checkout/payment_error.html
> +        A system error occurred while processing your payment. <b>You have not been charged.</b>
Use `<strong>` instead of `<b>`. See http://stackoverflow.com/a/271776/592820.

2016-12-13 05:34 UTC, clintonb commented on ecommerce/templates/oscar/checkout/payment_error.html
> +      {% with "<a class='nav-link' href='|add:basket_url|add:'>"|safe as start_link %}
`basket_url` is not defined in the view...which is not tested.

2016-12-13 11:24 UTC, marjev commented on ecommerce/extensions/checkout/utils.py
> +        base_url = site_configuration.build_ecommerce_url(settings.RECEIPT_PAGE_PATH)
I moved this into the Receipt Page PR: https://github.com/edx/ecommerce/pull/978/commits/ca2ab7f1569b3f3979011e9f1ae6c41f7c12020b

2016-12-14 09:03 UTC, marjev commented
@mjfrey @clintonb Comments addressed.

2016-12-15 01:37 UTC, clintonb approved these changes
Remember to squash your commits.

2016-12-15 01:37 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +class CybersourceNotifyViewTests(CybersourceNotificationTestsMixin, PaymentEventsMixin, TestCase):
Update `CybersourceMixin` to inherit `PaymentEventsMixin` and remove `PaymentEventsMixin` from here and the class below.

2016-12-15 01:37 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +            response = self.client.post(self.path, notification, follow=True)
Don't follow. Verify the the location of the redirect with `self.assertRedirects()`.

2016-12-15 01:37 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +                dict(response.context)
Is the casting actually necessary? If not, get rid of it.

2016-12-15 01:37 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +                    'payment_support_email': self.request.site.siteconfiguration.payment_support_email
There is no need for `self.request`. Use `self.siteconfiguration.payment_support_email`.

2016-12-15 01:37 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +                    'payment_support_email': self.request.site.siteconfiguration.payment_support_email
Where is `self.request` coming from? We shouldn't have this if it's not used.

2016-12-15 11:55 UTC, marjev commented
@mjfrey anything else needed in this PR?

2016-12-15 12:40 UTC, mjfrey approved these changes

2016-12-16 14:30 UTC, merged