[Sol-2131] Enable single course to dynamic query switching on coupon edit page
openedx-unsupported/ecommerce pull request #1028
Opened 2016-11-22 12:25 UTC by iivic

https://openedx.atlassian.net/browse/SOL-2131
Switching from single course to catalog query is enabled.
Switching from catalog query to single course is disabled.
@mjfrey @vkaracic @marjev Please review.

2016-11-22 12:25 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1028"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-11-22 12:49 UTC, vkaracic requested changes

2016-11-22 12:49 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                range_data['catalog'] = None
Mind updating the docstring on this method, please?

2016-11-22 12:49 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/coupon_detail_view_spec.js
> +                // Unset all attributes set here in order that other tests work as planned
Huh?

2016-11-22 12:49 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> +                it('should reset catalog type and related fields when cancelButtonClicked called', function() {
I believe this can be in ``it`` in the upper ``describe`` section.

2016-11-22 12:49 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> +                    expect(view.model.get('course_seat_types')).toEqual([]);
How come this equals ``[]`` here and ``undefined`` on line 295?

2016-11-22 12:49 UTC, vkaracic commented on ecommerce/static/js/views/coupon_form_view.js
> +            },
Something like [this](http://stackoverflow.com/a/33400454) might be easier. Clone all the attributes when someone opens the edit view and when cancel is clicked just apply the saved initial variables back to the model. This way all the variables are rolled back instead of just the ones you used.

2016-11-22 12:49 UTC, vkaracic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        }
What is happening here?

2016-11-22 12:54 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                range_data['catalog'] = None
Since you asked nicely.

2016-11-22 12:57 UTC, iivic commented on ecommerce/static/js/test/specs/views/coupon_detail_view_spec.js
> +                // Unset all attributes set here in order that other tests work as planned
While I was writing my test I discovered that the values set in this test remained in the model. This caused issues so after hours of debugging I found the source and it works. If you have a better idea please share it with me.

2016-11-22 13:00 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/coupon_detail_view_spec.js
> +                // Unset all attributes set here in order that other tests work as planned
In that case you could move these actions to a ``afterEach`` method.

2016-11-22 13:08 UTC, iivic commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> +                    expect(view.model.get('course_seat_types')).toEqual([]);
On model init course_seat_types is set to [],  and on view init this value is being saved so when calling `view.cancelButtonClicked()` the value is reset to [] while on line 295 the value is undefined because toggling single-course radio button will unset catalog_query and course_seat_types.

2016-11-22 13:42 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +            },
The only issue with the example is that it makes a shallow copy what I need is a deep copy.

2016-11-22 13:46 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        }
`this.model.get('course_seat_types')[0]` would result with an error because course_seat_types can be undefined that is why I added the if statement `if (this.model.get('course_seat_types'))`.

2016-11-22 14:21 UTC, marjev requested changes

2016-11-22 14:21 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +                range_data['catalog'] = None
Write a test on the backend side to make sure this works.

2016-11-23 13:24 UTC, marjev approved these changes

2016-11-24 08:34 UTC, vkaracic reviewed
A few questions.

2016-11-24 08:34 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(voucher_range.catalog_query, data['catalog_query'])
Why are you doing this here?

2016-11-24 08:34 UTC, vkaracic commented on ecommerce/static/js/views/coupon_form_view.js
> +                     * In case cancel is clicked reset values in cancelButtonClicked function
``Store initial model attribute values in order to revert to them when cancel button is clicked.``

2016-11-24 08:34 UTC, vkaracic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        this.model.set('course_seat_types', []);
Shouldn't you unset this value?

2016-11-24 08:42 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(voucher_range.catalog_query, data['catalog_query'])
I need to test updating a multiple courses coupon without catalog. The multi course coupon is already created in this test but if I write another test I would have to copy all this again so I figured it's better to do it here ...

2016-11-24 08:43 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +    def test_update_catalog_type(self):
Add a docstring explaining this test, please.

2016-11-24 08:46 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(voucher_range.catalog_query, data['catalog_query'])
It might be more time consuming, but the better way would be to extract all the operations that are needed for this new test into a shared helper method, write the new test and use that method there and in this one here.

2016-11-24 08:47 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        this.model.set('course_seat_types', []);
No. In case of multi course coupon `course_seat_types` must be set for validation to kick in. In case that `course_seat_types` is unset the validation would not kick in for empty `course_seat_types` which we currently don't allow.

2016-11-24 09:54 UTC, iivic commented
Ready for another review.

2016-11-24 09:57 UTC, vkaracic approved these changes
LGTM

2016-11-24 09:57 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +    def _get_voucher_range_with_updated_dynamic_catalog_values(self):
Nit: add docstring, please.

2016-11-24 11:07 UTC, merged