[SOL-2144] New Basket Page Design
openedx-unsupported/ecommerce pull request #1029
Opened 2016-11-22 15:43 UTC by marjev

@mjfrey, @clintonb Here's the 1st PR for the new basket page.

It contains design changes. The following screenshot shows the look of it:
![image](https://cloud.githubusercontent.com/assets/6833568/20530030/6685955e-b0d2-11e6-98d9-d37f752b8ff0.png)

Once the implementation has been approved, I would move to mobile design and a11y because those require external reviews (outside of our team). Once those land, we can focus on the functionality that we provide.

Please tag anyone who needs to review this.

2016-11-22 15:43 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1029"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-11-22 15:49 UTC, mjfrey commented on ecommerce/templates/oscar/basket/basket.html
> +                    {% include 'basket/partials/new_basket_page.html' %}
client_side_basket_page.html
hosted_basket_page.html

2016-11-22 16:04 UTC, clintonb requested changes
This cannot be merged to master without being both accessible and responsive.

2016-11-22 16:04 UTC, clintonb commented on ecommerce/extensions/payment/forms.py
> +    email_address = forms.EmailField(label=_('Email Address'))
This field is never used. Every user account has a valid email address.

2016-11-22 16:04 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +            (str, str, str): Course name, short description and image URL.
Use a [`namedtuple`](https://docs.python.org/2/library/collections.html#collections.namedtuple) to make this more manageable.

2016-11-22 16:04 UTC, clintonb commented on ecommerce/extensions/payment/forms.py
> +    postal_code = forms.CharField(max_length=10, required=False, label=_('Zip/Postal Code'))
This change is not necessary.

2016-11-22 16:04 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/old_basket_page.html
> +                        <div class="col-md-2 col-sm-12 course_image">
`course-image`

2016-11-22 16:04 UTC, clintonb commented on ecommerce/static/sass/partials/views/_basket.scss
> +                    #div_id_first_name,
Where are these `id`s used? Why not use classes?

2016-11-22 16:04 UTC, clintonb commented on ecommerce/static/sass/partials/views/_basket.scss
> +
Remove the unnecessary newlines.

2016-11-22 16:04 UTC, clintonb commented on ecommerce/templates/oscar/basket/basket.html
> +            {% if not basket.is_empty %}
Invert this logic (`{% if basket.is_empyt %}`) to make this simpler to parse.

2016-11-22 16:04 UTC, clintonb commented on ecommerce/templates/oscar/basket/basket.html
> +                        <h3>{% trans "Your purchase could not be completed" %}</h3>
If the basket is empty, tell the user the basket is empty. This messaging is confusing.

2016-11-22 16:04 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                    <div id="div_id_card_number" class="form-group">
Adding the element name to the ID is strange. I prefer camel-casing for ID's (e.g. `cardNumber`) and slugs for classes (e.g. `card-number`).

2016-11-22 16:04 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                        data-track-category="checkout" data-processor-name="cybersource_sop"
Pass the payment processor in context.

2016-11-22 16:04 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                                    {# Hide the entire section if a custom BasketView doesn't pass in a voucher form #}
Why is this ever hidden?

2016-11-22 16:04 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                            Upon course completion, we will email your certificate to {{email_address}}
This is not relevant to all orders, and should be removed.

2016-11-22 16:11 UTC, clintonb commented
Rename the image to `credit_card_options.png`. Also, is there a higher resolution version of the image?

2016-12-06 09:20 UTC, vkaracic commented
Screenshots are here:
https://drive.google.com/drive/folders/0ByBQUYJ4LMyANll2VmtNNDRHY28?usp=sharing

2016-12-06 09:40 UTC, vkaracic commented on ecommerce/templates/oscar/basket/basket.html
> +                    {% include 'basket/partials/new_basket_page.html' %}
How about client_side_payment_basket_page.html and hosted_payment_basket_page.html? It's more descriptive this way.

2016-12-06 09:51 UTC, vkaracic commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                    <div id="div_id_card_number" class="form-group">
I'm guessing that's because the crispy form generates ID names that way.

2016-12-06 09:54 UTC, vkaracic commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                                    {# Hide the entire section if a custom BasketView doesn't pass in a voucher form #}
If the basket already contains an applied voucher, which is the case for coupons, the voucher form is hidden. If the voucher is removed or not contained the voucher form will appear.

2016-12-06 22:14 UTC, clintonb requested changes

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +            {% for processor in payment_processors %}
Why is this here? We will support either credit cards or PayPal. There is no need to iterate over payment processors.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                <a href="#payment-information" id="payment-method-image" aria-label="Pay with a Credit Card" role="button"></a>
Why is the image being included via CSS rather HTML?

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/partials/alert_messages.html
> +                    {% if 'success' in message.tags %}
Why are you relying on `message.tags` instead of `message.level`?

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/partials/alert_messages.html
> +- noicon: don't show an icon
This doesn't appear to be used anywhere. It's unnecessary complexity that can be avoided.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +            except AttributeError:  # Bulk enrollment codes don't have the certificate_type attribute.
Be proactive and check the product type.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +                if not is_verification_required:
I initially found this variable name confusing as it implies an attribute on a single line item, when it is actually indicating if we should be displaying certain messaging. Consider renaming to something that better describes the intended usage: `display_verification_message`.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
>          for line in lines:
Echoing an earlier comment...you can simplify this view code by moving the complexity associated with retrieving line-level data to template tags and/or partials. Doing this sets us up to later render other product types without having to change this view. This view should not necessarily care about line-level data.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
>                  if payment_processor_class:
This variable name is confusing (says the person who created it). Rename this to `client_side_payment_processor_class`.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +                        'months': calendar.month_name[1:],
Use numbers unless you want to deal with i18n and translations.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +                if not is_certifiable:
Similar to the comment above, this variable name is confusing. Use `display_certificate_message` instead.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +                    is_certifiable = seat_type == 'Verified' or seat_type == 'Professional'
All seats have a `certificate_type` attribute. If that value is non-empty, the seat includes a certificate.

`display_certificate_message = display_certificate_message or bool(line.product.attr.certificate_type)`

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +                    # Excluding the client side payment processor from the processors list.
This is not necessary. We have no plans to include the client-side payment processor in the full list of processors, primarily to avoid things like this.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
>              'partner_sku': partner_sku,
This needs to go. We cannot retain code that is focused on single item baskets.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/payment/forms.py
> +                self.fields[bound_field.name].label = '{label} (required)'.format(label=bound_field.label)
Mark for translation.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_forms.py
> +            'email_address': self.user.email,
The form doesn't accept an email address.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +            'bill_to_email': data['email_address'],
Revert all changes in this file.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/static/js/apps/basket_app.js
> +                if (/^[0-9]$/.test(parseInt(cardExpiryMonth))) {
Render the months as numbers with a prefixed `0` and you can avoid this.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                                <option value="{{forloop.counter}}">{{month}}</option>
`forloop.counter|stringformat:"02d"`

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                    <input type="hidden" name="card_expiry_date" value="" class="pci-field">
No need for the value attribute.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +        <div id="basket-information">
Nit: use camelCasing for IDs and hyphenated-slugs for classes.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                        Upon course completion, we will email your certificate to {{email_address}}
No we won't. We no longer offer PDF certificates. I would push back on including any special messaging here. We do not do so today, and it has not been a problem.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                        <img class="card-type-icon" src="">
No need for an empty src attribute.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                        data-course-id="{{ course.id }}">
Remove.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +                        data-processor-name="{{ client_side_payment_processor.NAME }}"
This is not necessary.

2016-12-06 22:14 UTC, clintonb commented on ecommerce/templates/oscar/partials/alert_messages.html
> +{% if messages %}
Where are you using the messages framework?

2016-12-07 12:13 UTC, vkaracic commented on ecommerce/templates/oscar/partials/alert_messages.html
> +{% if messages %}
Oscar uses it to display notification messages in the basket page. I'm extending it to add the ``aria-live`` attribute.

2016-12-07 15:55 UTC, vkaracic commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +        <div id="basket-information">
Is there a style guide for HTML/CSS that we follow? I'm looking through the ecommerce app HTML templates and there is not much consistency.

2016-12-07 19:13 UTC, mjfrey commented on ecommerce/templates/oscar/basket/partials/new_basket_page.html
> +        <legend>{% trans "SELECT PAYMENT METHOD" %}</legend>
We should not have this text if there is only a single payment method.  WL sites currently do not use PayPal and only use a credit card processor.  It seems odd to say this if there is only one.

2016-12-19 16:06 UTC, vkaracic commented
Closing in favor of https://github.com/edx/ecommerce/pull/1048

2016-12-19 16:06 UTC, closed without merging