[SOL-2140] Add Backend Validation for Catalog Query
openedx-unsupported/ecommerce pull request #1032
Opened 2016-11-28 12:40 UTC by iivic

@marjev @vkaracic @mjfrey I made backend validation for `catalog_query` parameter and since it's tied closely with the `course_seat_types` field some validation is included for this field as well but there will be a separate PR for it with more validation.
https://openedx.atlassian.net/browse/SOL-2140

2016-11-28 12:40 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1032&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-11-28 14:55 UTC, iivic commented
I'm done with the changes. Please review.

2016-11-28 15:39 UTC, marjev requested changes

2016-11-28 15:39 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        )
Why do you need validation here as well as in `Range` model? Shouldn't one be more than enough?

2016-11-28 15:39 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +                if request.data.get('catalog_type') == 'Multiple courses':
Do we actually need the `catalog_type`? As I recall, it was only a front-end attribute.

2016-11-29 08:24 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                if request.data.get('catalog_type') == 'Multiple courses':
I'm checking `catalog_type` to be sure `catalog_query` and `course_seat_types` are required.
Maybe checking if `catalog` is sent would be a good replacement??

2016-11-29 08:38 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        )
I assumed that we use the Range model in various places and not only in the coupon creation method. Notice that the model validation will pass if both of the attributes are set (catalog_query and course_seat_types) or non of them since there can be only the catalog.

2016-11-29 10:49 UTC, vkaracic requested changes

2016-11-29 10:49 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +        # If catalog_query is sent course_seat_types must be sent as well and vice versa
Convert these to docstrings.

2016-11-29 10:49 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +        elif self.catalog_query and not self.course_seat_types:
You could combine these into something like:
```
if not (self.catalog_query and self.course_seat_types)
```

2016-11-29 10:49 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +    def clean_catalog_query(self):
I don't think this was necessary to extract to a separate method.

2016-11-29 10:49 UTC, vkaracic commented on ecommerce/extensions/offer/tests/test_models.py
> +    def test_creating_range_without_required_data(self, data):
Create another unit test that verifies when the data passes without a validation error.

2016-11-29 10:49 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        )
The validation should kick in on saving the model and bubble up to the view. There will be more validations added later and this could easily become redundant. The more business logic in the model layer the better.

2016-11-29 12:30 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        )
@vkaracic  Yes but we need the `catalog_type` in order to know which fields are required or like I mentioned already would it be vise to check for the catalog instead??

2016-11-29 12:39 UTC, iivic commented on ecommerce/extensions/offer/models.py
> +        elif self.catalog_query and not self.course_seat_types:
No. This will require catalog_query and course_seat_types to be set on every range but there is the case when only the catalog is set.

2016-11-29 12:41 UTC, iivic commented on ecommerce/extensions/offer/models.py
> +    def clean_catalog_query(self):
I think this is good practice. There will be more validation for other fields and if the validation is for one field only it's better to separate them instead of putting them into one method.

2016-11-29 13:07 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +    def clean_catalog_query(self):
In that case you can move the existing code in ``clean()`` to a method of it's own as well, like [here](https://github.com/edx/ecommerce/blob/6640de3848f3ee077bf403f6d6147fac94e63677/ecommerce/extensions/offer/models.py#L23), because this now seems like a half-measure.

2016-11-29 13:10 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +        elif self.catalog_query and not self.course_seat_types:
```
if (self.catalog_query or self.course_seat_types) and not (self.catalog_query and self.course_seat_types)
```
but this is complicating it too much. Leave as is :+1:

2016-11-29 13:12 UTC, iivic commented on ecommerce/extensions/offer/models.py
> +    def clean_catalog_query(self):
I was thinking about that as well but this validation includes two fields so it makes sense to me keeping them in this "common" clean method. What makes more sense to you?

2016-11-29 13:15 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        )
IMHO model constraining should happen at the model layer, not the view/controller layer.

2016-11-29 13:25 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        )
I will remove this validation and redo the model validation.

2016-11-29 13:26 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +    def clean_catalog_query(self):
Not really, it's one segment defining the business logic of the model, doesn't matter if it includes two fields.

2016-11-30 14:07 UTC, iivic commented
Lots of tests failed after the model validation. Please review.

2016-12-01 09:15 UTC, vkaracic approved these changes
I left you one nitpick, up to you if you want to apply it.
The ``RangeFactory`` should ideally be able to be called without any required arguments. I'm not sure if that is in the scope of this PR/ticket so I'll leave that decision to you as well. If you decide not to change that at least create a tech debt ticket for creating a custom ``RangeFactory`` (possibly assign to me, I'd like to dabble with factories :smiley: )

2016-12-01 09:15 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +                raise ValidationError(
How about:
```
if not (self.catalog_query and self.course_seat_types)
```

2016-12-01 09:24 UTC, marjev requested changes

2016-12-01 09:24 UTC, marjev commented on ecommerce/coupons/tests/test_views.py
>  )
A lot of Factories are being used from `oscar.test.factories`. It makes no sense to list all of them like this.
Just import the factories:
`from oscar.test import factories` and apply the change to all the tests.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        new_range = RangeFactory(products=[seat, ], catalog=self.catalog)
You can DRY this.
```
course, seat = self.create_course_and_seat()
new_range = RangeFactory(products=[seat, ], catalog=self.catalog)
```
These two lines are almost in every test method.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        new_range = RangeFactory(products=[seat, ], catalog=self.catalog)
Why do we need both products and catalog in Range?

If not, you should leave only one of them (which is necessary) and update the entire PR with the necessary change.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        benefit = BenefitFactory(range=_range)
DRY this as well.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/fulfillment/modules.py
> +            _range, created = Range.objects.get_or_create(name=name, catalog=CatalogFactory(name='test'))
why do you need to set a name for the catalog here?
I didn't notice you doing that in any of the previous tests.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/offer/models.py
> +        super(Range, self).save(*args, **kwargs)  # pylint: disable=bad-super-call
My OCD senses are tingling. We're adding `# pylint: disable=bad-super-call` together with `super` without giving much thought to it.

Can we replace `Range` with `self.__class__` to avoid disabling Pylint's bad-super-call quality issue?
@clintonb any objections to my suggestion? 
I tried replacing `Range` with `type(self)` but it didn't work.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/offer/models.py
> +
All of these messages are mentioning `Coupon` even though this is a Range validation.
Do we want to couple the two that tightly?

In future, we or someone from the Open Source Community might decide to create a Range for a new type of products (that aren't Coupons).

I think we shouldn't make an assumption that Ranges will be created solely for the purpose of Coupon creation.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/offer/tests/test_models.py
> -        self.assertTrue(self.range.contains_product(self.product))
If we have a line `self.range.add_product(self.product)`, shouldn't this assertion remain to make sure we didn't break existing Django Oscar functionality?

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/offer/tests/test_models.py
> -        self.assertFalse(self.range.contains_product(not_in_range_product))
One should remain. Other one is redundant.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/offer/tests/test_models.py
> -        self.assertTrue(self.range.contains_product(self.product))
A lot of these tests assumed that someone might add a `Product` to a `Range` using `add_product` method which is inherited from Django Oscar's `AbstractBenefit` class.

We should extend the existing code with additional features, without breaking any existing code.

2016-12-01 09:24 UTC, marjev commented on ecommerce/extensions/offer/tests/test_models.py
> +        self.assertEqual(self.range.num_products(), 0)
Should be 1 if we used `add_product()` to add a product to the `Range`.

2016-12-01 09:24 UTC, marjev commented on ecommerce/tests/factories.py
> +    """Factory for Catalog objects."""
This docstring can be removed. 
It's not adding anything that the name isn't already describing.

2016-12-01 16:04 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        new_range = RangeFactory(products=[seat, ], catalog=self.catalog)
I created a new RangeFactory it will automatically create a catalog. The products parameter is optional but is needed is some tests because it's somehow involved in the test. I went through all the tests and removed the products parameter where not needed.

2016-12-01 16:11 UTC, iivic commented on ecommerce/extensions/fulfillment/modules.py
> +            _range, created = Range.objects.get_or_create(name=name, catalog=CatalogFactory(name='test'))
Since this is get_or_create if the catalog with name test exists it will be found otherwise a Range instance will be created every time. Is there something wrong with this logic?

2016-12-02 08:56 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        new_range = RangeFactory(products=[seat, ], catalog=self.catalog)
My point is that the catalog is currently empty so `new_range` isn't benefiting from it. Also, if I'm not mistaken, the catalog is an optional field.

A Range can have:
1) Catalog query and course_seat_types
2) Products (list of products)
3) Catalog (list of stock records -- I think)

2016-12-02 09:00 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        new_range = RangeFactory(products=[seat, ], catalog=self.catalog)
The new validation requires either catalog or catalog_query and course_seat_types to be set. If none of them is set an exception will be raised.

2016-12-02 09:03 UTC, marjev commented on ecommerce/extensions/fulfillment/modules.py
> +            _range, created = Range.objects.get_or_create(name=name, catalog=CatalogFactory(name='test'))
Factories should be used only in tests.

Also, this catalog doesn't contain any StockRecords and is useless. Catalog, therefore, should be an optional field and added to Range only if it contains StockRecords.

Products are added via `add_products` method and will be found in the `products` list.

2016-12-02 11:24 UTC, iivic commented on ecommerce/extensions/offer/models.py
> +        super(Range, self).save(*args, **kwargs)  # pylint: disable=bad-super-call
http://stackoverflow.com/questions/18208683/when-calling-super-in-a-derived-class-can-i-pass-in-self-class
It looks like a bad idea.

2016-12-05 08:34 UTC, marjev approved these changes

2016-12-05 09:21 UTC, merged