[SOL-2151] Allow max number of uses to be increased on a multi-use coupon
openedx-unsupported/ecommerce pull request #1037
Opened 2016-12-01 11:44 UTC by iivic

@vkaracic @marjev @mjfrey While enabling this feature I noticed a bug: on editing once per customer coupon the max_uses field value was always 1. Now this is fixed. The max_uses field editing is only enabled for multi-use and not for once per customer coupons. Please review.

2016-12-01 11:44 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1037&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-01 11:44 UTC, iivic commented
<img width="643" alt="screen shot 2016-12-01 at 12 35 04" src="https://cloud.githubusercontent.com/assets/16685686/20792762/ed10289e-b7c3-11e6-8f7c-b918f39a4f59.png">

2016-12-02 08:36 UTC, marjev requested changes

2016-12-02 08:36 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +                voucher.offers.update(max_global_applications=request.data.get('max_uses'))
update `UPDATEABLE_VOUCHER_FIELDS` with `max_uses` and do the bulk update on line 223.

2016-12-02 08:36 UTC, marjev commented on ecommerce/static/js/test/specs/views/coupon_edit_view_spec.js
> +                    expect(view.$('[name=max_uses]').attr('disabled')).toBe(undefined);
https://api.jquery.com/has-attribute-selector/

2016-12-02 12:12 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                voucher.offers.update(max_global_applications=request.data.get('max_uses'))
max_uses is an offer field so I don't see how this will work or maybe I misunderstood you?

2016-12-05 08:44 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +                voucher.offers.update(max_global_applications=request.data.get('max_uses'))
combine the `max_global_applications` with `email_domains` update so we might do the bulk_update instead of two separate updates.

2016-12-06 09:25 UTC, marjev requested changes

2016-12-06 09:25 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +            offer_data = self.create_update_data_dict(data=request.data, fields=ConditionalOffer.UPDATABLE_OFFER_FIELDS)
```
offer_data = self.create_update_data_dict(data=request.data, fields= ConditionalOffer. UPDATABLE_OFFER_FIELDS):
    if offer_data:
        ConditionalOffer.objects.filter(vouchers__in=vouchers.all()).update(**offer_data)
```

2016-12-06 12:03 UTC, vkaracic commented on ecommerce/static/js/views/coupon_form_view.js
> +                            this.$(maxUsesFieldSelector).removeAttr('disabled');
When exactly is this field disabled then?

2016-12-06 12:05 UTC, marjev approved these changes

2016-12-06 12:05 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                            this.$(maxUsesFieldSelector).removeAttr('disabled');
It is disable when voucherType is Once per customer on edit page.

2016-12-06 12:16 UTC, vkaracic commented on ecommerce/static/js/views/coupon_form_view.js
> +                            this.$(maxUsesFieldSelector).removeAttr('disabled');
It's hidden for once-per-customer on edit page. Anyway, all you should do is remove the ``non-editable`` class from the HTML template so that this is not triggered: https://github.com/edx/ecommerce/blob/master/ecommerce/static/js/views/coupon_form_view.js#L572

You can also remove the test that checks if this field has disabled attribute.

2016-12-07 14:34 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                            this.$(maxUsesFieldSelector).removeAttr('disabled');
It's not hidden but I will make it editable.

2016-12-07 15:40 UTC, iivic commented
Comments addressed and commits squashed.

2016-12-08 10:00 UTC, vkaracic approved these changes
LGTM

2016-12-12 10:01 UTC, merged