[SOL-2153] When editing coupon and save without actualy changing anything invoice amount changes
openedx-unsupported/ecommerce pull request #1039
Opened 2016-12-05 14:05 UTC by iivic

@mjfrey  @vkaracic @marjev It's just one line but still review and check if the bug is fixed and if other bugs occurred because of the fix I already did but one can not be careful enough.

2016-12-05 14:05 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1039"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-05 14:57 UTC, vkaracic approved these changes
![LGTM](https://i.imgflip.com/1fdq7d.jpg)

2016-12-06 07:46 UTC, marjev requested changes

2016-12-06 07:46 UTC, marjev commented on ecommerce/static/js/views/coupon_form_view.js
> +                if (seatType && !this.editing) {
Do we have a test case for this?

Usually, when a bug is caught, it would be great if we could have a test for that case?

So, I guess we have the one for the automatic update of the invoice amount. Can we add one for editing use-case, just to make sure that someone doesn't break it in the future?

2016-12-06 09:58 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                if (seatType && !this.editing) {
Done.

2016-12-06 12:04 UTC, marjev approved these changes

2016-12-06 12:58 UTC, merged