[SOL-2149] Pagination is not showing correct range of coupons on the last page.
openedx-unsupported/ecommerce pull request #1040
Opened 2016-12-05 15:46 UTC by iivic

@mjfrey @vkaracic @marjev Quick review.

2016-12-05 15:59 UTC, iivic commented
![screen shot 2016-12-05 at 16 53 20](https://cloud.githubusercontent.com/assets/16685686/20891808/2eda984a-bb0c-11e6-899a-3e702e2d8fa4.png)

2016-12-05 16:10 UTC, vkaracic approved these changes
LGTM

2016-12-06 07:50 UTC, marjev requested changes

2016-12-06 07:50 UTC, marjev commented on ecommerce/static/js/collections/offer_collection.js
> +                this.upperLimit = this.onLastPage() ? this.length : this.page * this.perPage;
Can you write additional test that would catch this bug, in case this breaks in the future?

2016-12-06 09:34 UTC, iivic commented on ecommerce/static/js/collections/offer_collection.js
> +                this.upperLimit = this.onLastPage() ? this.length : this.page * this.perPage;
Done.

2016-12-06 09:35 UTC, marjev approved these changes

2016-12-06 11:40 UTC, merged