[SOL-2162] Add Backend Validation for Client
openedx-unsupported/ecommerce pull request #1042
Opened 2016-12-08 09:57 UTC by iivic

@mjfrey @vkaracic @marjev The client model doesn't allow empty values for name field so if a post request without the name parameter is sent to our coupon api it will break. This ensures the error is handled properly.

2016-12-08 09:57 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1042&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-08 10:16 UTC, vkaracic approved these changes
Nitpick: remove ``blank`` and ``null`` arguments here https://github.com/edx/ecommerce/pull/1042/files#diff-c35ba6c955b6de8aba48f3a0f17be18eR502

2016-12-09 09:45 UTC, marjev requested changes

2016-12-09 09:45 UTC, marjev commented on ecommerce/core/models.py
> +    name = models.CharField(_('Name'), unique=True, max_length=255)
I think this requires a new migration.

2016-12-09 09:52 UTC, iivic commented on ecommerce/core/models.py
> +    name = models.CharField(_('Name'), unique=True, max_length=255)
Those are the default values so removing them changes nothing hence no migration is needed.

2016-12-09 10:38 UTC, marjev approved these changes

2016-12-09 14:05 UTC, davec-edx commented on ecommerce/core/models.py
> +    name = models.CharField(_('Name'), unique=True, max_length=255)
Will they be noticed during a make migrations?  The next commit that will require it might pick up on that and raise a question about it.

2016-12-09 14:32 UTC, iivic commented on ecommerce/core/models.py
> +    name = models.CharField(_('Name'), unique=True, max_length=255)
Removing the values doesn't change the model because the values are already set by default so the change will not be picked up by django makemigrations. I just tried to make sure there shouldn't be any problems. You are welcome to double check 😄

2016-12-12 10:24 UTC, merged