[SOL-2166] Add Backend Validation for Code
openedx-unsupported/ecommerce pull request #1045
Opened 2016-12-09 11:03 UTC by iivic

The following cases are covered: 
1. Voucher can not be created without code
2. Voucher can only be created with alphanumeric code value
3. Enrollment coupon can not be created if code is sent (random code will be created)
4. Coupon will not be created if quantity is greater than one and code sent (random codes will be created depending of quantity value).

2016-12-09 11:03 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1045&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-09 14:13 UTC, davec-edx commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
I'm unclear what this is testing. It looks like this is testing a val of 90 with a code, but the docstring says it is testing a quantity.

2016-12-09 14:13 UTC, davec-edx commented on ecommerce/extensions/api/v2/views/coupons.py
> +                if benefit_type == Benefit.PERCENTAGE and benefit_value == 100 and code:
Is this being tested?

2016-12-09 14:20 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
The data is set in the setUp method (quantity=2). The value is changed to 90 to get a discount coupon if the value is 100 and type percentage it will be an enrollment coupon and that is not what I need.

2016-12-09 14:24 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                if benefit_type == Benefit.PERCENTAGE and benefit_value == 100 and code:
https://github.com/edx/ecommerce/pull/1045/files/13a6e5e7e5788379acaafb94c25e6636050c3289#diff-3bdba75be46de6780d19faac1f58ded3R699

2016-12-10 09:12 UTC, marjev requested changes

2016-12-10 09:12 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        """ Test that an exception is raised when creating enrollment coupon with code parameter set. """
Actually, you're testing that the `bad request` response is returned, not that an exception is raised.

Change the docstring so it doesn't confuse any code readers.

2016-12-10 09:12 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        Test that an exception is raised when creating discount coupon with code set and quantity greater than one.
same comment I left for the previous test.

2016-12-10 09:12 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +                    return Response(_('Code may not be set for Enrollment Coupon.'), status=status.HTTP_400_BAD_REQUEST)
Move this to the utility method that calls the `Voucher.objects.create()` for now.

This is not the ideal solution, and we'll have to create a `Voucher` model later when we get to Vouchers app cleanup, but for now, this is the best we can do.

Again, backend validation should not reside within API endpoint.

2016-12-10 09:12 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +                if quantity > 1 and code:
Is this actually needed?

I thought Django Oscar placed the unique restriction on the code field. If you remove this and catch the Integrity error, I think you'll be able to remove this.

Just pass the exception message to the Response and leave the same status.

2016-12-10 09:12 UTC, marjev commented on ecommerce/extensions/catalogue/tests/test_utils.py
> +        custom_code = 'CUSTOMCODE'
You don't need to change this.

2016-12-10 09:12 UTC, marjev commented on ecommerce/extensions/voucher/models.py
> +            raise ValidationError(_('Voucher code must contain only alphanumeric characters.'))
make a `clean` method and call it here instead.

2016-12-12 11:54 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                if quantity > 1 and code:
You are right. The code field is unique and IntegrityError is raised.

2016-12-12 12:04 UTC, iivic commented on ecommerce/extensions/catalogue/tests/test_utils.py
> +        custom_code = 'CUSTOMCODE'
The code must contain only alphanumeric values. Diacritic characters are not allowed. That's why this will not pass the validation.

2016-12-12 12:04 UTC, vkaracic requested changes

2016-12-12 12:04 UTC, vkaracic commented on ecommerce/extensions/voucher/models.py
> +        if not re.match('^[a-zA-Z0-9]+$', self.code):
``if not self.code.isalnum()``

2016-12-12 12:04 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
Nevertheless there is no harm in explicitly setting the quantity to be more than two.

2016-12-13 14:02 UTC, iivic commented
All comments addressed please review the changes.

2016-12-13 14:39 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
Perhaps wait for this to merge: https://github.com/edx/ecommerce/pull/1050/files#diff-3bdba75be46de6780d19faac1f58ded3R246

2016-12-13 14:39 UTC, vkaracic commented on ecommerce/extensions/voucher/models.py
>  # noinspection PyUnresolvedReferences
Is this some PyCharm crap? :smile:

2016-12-13 14:39 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
> +        raise ValidationError(_('Voucher can not be created when code is set in enrollment coupon.'))
I would rather see this in the voucher model validation method than here.

2016-12-13 14:51 UTC, iivic commented on ecommerce/extensions/voucher/models.py
>  # noinspection PyUnresolvedReferences
It seems so...

2016-12-13 15:05 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
> +        raise ValidationError(_('Voucher can not be created when code is set in enrollment coupon.'))
I don't see how this will work. A Voucher must have a code field set so this validation makes no sense in the model it would disallow creating enrollment codes.

2016-12-13 15:08 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
> +        raise ValidationError(_('Voucher can not be created when code is set in enrollment coupon.'))
Right. My mistake.

2016-12-14 09:10 UTC, marjev approved these changes

2016-12-14 15:18 UTC, vkaracic requested changes

2016-12-14 15:18 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_models.py
> +            Voucher.objects.create(code='Only alphanumeric without spaces')
Add a test case which should pass and create a voucher.

2016-12-15 07:35 UTC, vkaracic approved these changes

2016-12-15 08:46 UTC, merged