Client side checkout basket
openedx-unsupported/ecommerce pull request #1048
Opened 2016-12-09 21:12 UTC by vkaracic

_Note: I'm opening this PR to keep more detailed notes about the changes in the PR text. This is still a work in progress._

This PR consists of:

- Generalizing basket page: changes to the current basket so that it accepts different type of products and can accept multiple products. In the basket view each line is 'handled' based on the product class of that line's product. If no handler is specified it falls back to 'regular type' product handler. Screenshots: https://drive.google.com/drive/folders/0ByBQUYJ4LMyAb3lDTl96ZVpleXM?usp=sharing
     - [ ] Bulk enrollment code quantity is not updating if in a multiline basket
     - [ ] Voucher form not visible if bulk enrollment code is within other products

- Client side checkout basket: Redesign of the new client side checkout basket with keeping in mind backwards compatibility with old/current basket. Screenshot available here: https://drive.google.com/drive/folders/0ByBQUYJ4LMyANll2VmtNNDRHY28?usp=sharing
     - [ ] Smoother screen reader experience

- Credit card recognition and validation: credit cards are recognized automatically on user input (if the credit card information [regex pattern, CyberSource type ID, CVV number length] is available in the ``getCreditCardType`` function).
The credit card regex matches are created according to [these rules](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_.28IIN.29). The credit card number is validated against [Luhn's algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm). CVN inputted length is checked if it matches the inputted credit card type's CVN length. The expiry month and year validation fires if a non-number is sent or the selected combination of month and year is less than current month and year.
     - [ ] Card validity check fails for VISA cards with 13 numbers

- Factoring out payment processor specifics: namely the CyberSource specific field signing code in ``basket_app.js``. This way different payment processors can be plugged in.

https://openedx.atlassian.net/browse/SOL-2113

2016-12-09 21:12 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1048&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-12 13:40 UTC, mjfrey commented on ecommerce/extensions/basket/utils.py
> +    structure = product.structure
what are these used for?

2016-12-12 13:45 UTC, mjfrey commented on ecommerce/static/js/apps/basket_app.js
> +              CyberSource) {
Is there anyway we can dynamically pull these in based on the client side processor setting?

2016-12-12 19:13 UTC, mjfrey requested changes

2016-12-12 19:13 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> +                    'paypal_enabled': len(payment_processors) > 1,
How does this ensure PayPal?  Need to check if it is in the list.

2016-12-12 19:13 UTC, mjfrey commented on ecommerce/templates/oscar/basket/basket.html
> +    <div class="basket {% if enable_client_side_checkout %}basket-new{% endif %}">
basket-client-side instead of basket-new

2016-12-12 20:35 UTC, mjfrey commented on ecommerce/static/js/pages/basket_page.js
> +                appendValidationErrorMsg(event, cvnNumberField, 'Wrong CVN number');
Invalid CVN

2016-12-13 13:04 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +                self.fields[bound_field.name].label = _('{label} (required)'.format(label=bound_field.label))
Can we change all the (required) to * to be consistent.

2016-12-13 13:06 UTC, vkaracic commented on ecommerce/extensions/payment/forms.py
> +                self.fields[bound_field.name].label = _('{label} (required)'.format(label=bound_field.label))
No. The ticket specifically stated to use ``(required)`` instead of *.

2016-12-13 14:20 UTC, vkaracic commented
@clintonb can you please review this? Each commit is _mostly_ a separate change so you can go through it commit by commit if it's easier.

2016-12-13 15:54 UTC, mjfrey commented on ecommerce/extensions/payment/views/cybersource.py
> +                logger.info('Received a non-accept decision. Basket [%s] thawed.', basket.id)
Can we add to the log if this was using the client or hosted page?  Will be nice to understand failures for each.

2016-12-13 15:56 UTC, mjfrey commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                        data-processor-name="{{ client_side_payment_processor_name }}"
Let's add an additional attribute that specifies this is from the client-side checkout page.

2016-12-15 02:45 UTC, mjfrey commented
@clintonb please take a look.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +            # TODO: handle these links for multi-line baskets.
Handle what links? Is this going to be done?

2016-12-15 05:12 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +                if (hasattr(line.product.attr, 'id_verification_required') and
`if getattr(line.product.attr, 'id_verification_required', False) and line.product.attr.certificate_type != 'credit':`

2016-12-15 05:12 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +        course_key = lines_data[0].get('course_key') if len(lines) == 1 else None
Nope! Any code that is still assuming we are using single-item baskets needs to be updated or removed.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/extensions/payment/forms.py
> +    countries.insert(0, ('', '<Choose country>'))
Mark for translation.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/extensions/payment/forms.py
> +                self.fields[bound_field.name].label = _('{label} (required)'.format(label=bound_field.label))
Add a translators comment on the line above explaining how this should be translated.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/extensions/payment/views/cybersource.py
> +                logger.info('Received a non-accept decision. Basket [%s] thawed.', basket.id)
What's the plan here? Why is the payment processor code being modified?

2016-12-15 05:12 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        # The basket should be in open.
The basket should be in the OPEN state.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/static/js/utils/utils.js
> +            /**
Move this to `ecommerce/static/js/utils/credit_card.js`.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/static/js/apps/basket_app.js
> +              CyberSource) {
We must pull these in dynamically to support other payment processors. It seems I never documented/shared the plan for payment processors. Here it is:

> The idea is that we maintain the existing backend architecture. Each client-side processor will have an associated Django template that will load JS. (I don't think there is a need for anything else.) We will build  the payment form. The processor-specific JS can add hidden fields, loads Stripe.js, etc. Essentially the payment form, and its element IDs, is our contract.

We will need to do the following:
1. Create `templates/payment/_cybersource.html` which loads the CyberSource JS.
2. Add a variable to the processor, `template_name`, and set it to `'payment/_cybersource.html'`.
2. Update the checkout view/template to render this template.

I realize this is a bit of extra work. I can take this on after this lands. For now, please load the CyberSource file on its own, separately from `basket_app.js`.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/static/js/payment_processors/cybersource.js
> +        // Format the date to a format that CyberSource accepts (MM-YYYY).
Add a new line above this to make the code a bit more legible.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/static/js/payment_processors/cybersource.js
> +                // TODO Handle errors. Ideally the form should be validated in JavaScript
This needs to be handled.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/hosted_checkout_basket.html
> +        <form action="." method="post" class="basket_summary" id="basket_formset">
This ID attribute is unused, and should be removed.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +        <form action="." method="post" class="basket_summary row" id="basket_formset">
This ID attribute is unused, and should be removed.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                        <button aria-label="Pay with paypal"
Mark this, and all of your labels, for translation.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                                data-course-id="{{ course_key }}"
Nope!

2016-12-15 05:12 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                                id="paypal"
This ID is unused, and should be removed.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                        <label for="card-number-input" class="control-label">{% trans "Card Number (required)" %}<span class="sr">, Secure</span></label>
Mark the screen reader text for translation. The same goes for the other text you have in this template.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/hosted_checkout_basket.html
> +            {# Translators: <b></b> tags will bold the text within. Keep the tags and translate the text within. #}
Use `<strong>` instead of `<b>`. It provides better semantics.

2016-12-15 05:12 UTC, clintonb commented on ecommerce/templates/oscar/basket/partials/hosted_checkout_basket.html
> +</div>
Add a new line.

2016-12-15 05:13 UTC, clintonb commented
Where can I see this in action?

2016-12-15 08:02 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +            # TODO: handle these links for multi-line baskets.
The links for switching between bulk enrollment codes and individual seats. AFAIK only white label sites are using this and when they decide to introduce multi-line baskets the whole logic for handling these use cases needs to be changed. I thought I could change it in this PR but it's too much out of scope and the PR is already too big so I just left a note.

2016-12-15 08:11 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +        course_key = lines_data[0].get('course_key') if len(lines) == 1 else None
I think we'll need to talk to the analytics team about how they'd want to handle multi-line basket analytics. This line was just for backwards compatibility.

2016-12-15 08:21 UTC, vkaracic commented on ecommerce/extensions/payment/views/cybersource.py
> +                logger.info('Received a non-accept decision. Basket [%s] thawed.', basket.id)
If a user makes a mistake, for example inputs the wrong ZIP code, or there is a problem with the payment processor servers and proceeds to payment, CyberSource will decline the transaction and the basket will be frozen and as such cannot be accessed again so the user in that case would have to add the item(s) to a new basket all over again. This will thaw the basket in that case and the user can fix the mistake and try again.

@mjfrey we'll need to think about adding a 'remove item' button to the form.

2016-12-19 16:00 UTC, vkaracic commented
@clintonb comments addressed, please take another look.

2016-12-19 16:16 UTC, clintonb approved these changes
Please start the conversation with Analytics regarding reporting. We must NOT continue assuming we have single item baskets. FYI @mulby

2016-12-19 16:16 UTC, clintonb commented on ecommerce/extensions/basket/utils.py
> +    structure = product.structure
I have the same question.

2016-12-19 16:16 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +        course_key = lines_data[0].get('course_key') if len(lines) == 1 else None
Has this conversation been started?

2016-12-19 16:16 UTC, clintonb commented on ecommerce/extensions/payment/tests/mixins.py
> +        self.user = factories.UserFactory(password=self.password)
I don't think this will do what you intend.

2016-12-19 16:16 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +    def setUp(self):
Why are any changes necessary to this file?

2016-12-19 16:22 UTC, vkaracic commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +    def setUp(self):
Because ``self.client`` needs to have a user in order to retrieve and use that user's basket. If the user is not authenticated the basket in the request(s) is an empty basket object instead of the basket created in the ``CybersourceNotificationTestsMixin`` mixin, which would be fine if the basket summary view didn't need the actual (saved to the database) basket object which it does in the  ``test_payment_cancelled_error`` tests.

Without the changes in this file and the added password in the mixin file above, this error would occur: https://gist.github.com/vkaracic/5a4dab7d944f3a58c1ff72ad425307c7

2016-12-19 16:26 UTC, vkaracic commented on ecommerce/extensions/basket/utils.py
> +    structure = product.structure
These are used to construct the link for switching between a seat and bulk enrollment coupon purchase (BEC). I've added default values for these because, if you look a few lines below, these are set only for BEC and seats and in case of a 'regular' product, ie. not one of those two, this would break.

2016-12-19 16:27 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +        course_key = lines_data[0].get('course_key') if len(lines) == 1 else None
@mjfrey please advise on how / when are we going to address multi-line basket analytics questions.

2016-12-19 16:29 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +    def setUp(self):
You don't need to modify as much as you have. Set `fetch_redirect_response=False` on the call to [`assertRedirects`](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#django.test.SimpleTestCase.assertRedirects).

2016-12-19 16:31 UTC, vkaracic commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +    def setUp(self):
You are correct :+1:

2016-12-19 18:29 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> +        course_key = lines_data[0].get('course_key') if len(lines) == 1 else None
I will speak with Gabs and see how they want to handle this.

2016-12-19 19:57 UTC, mjfrey commented
@vkaracic  please squash commits.

2016-12-19 19:57 UTC, mjfrey approved these changes

2016-12-19 20:22 UTC, clintonb commented
@vkaracic please add the ticket number, SOL-2113, to your ultimate commit(s).

2016-12-20 09:43 UTC, merged

2016-12-20 09:44 UTC, vkaracic commented
@mjfrey this now leaves the question of documentation. Do we write the documentation for this or notify the documentation team?

2016-12-20 12:41 UTC, clintonb commented
Even if the Doc Team were fully-staffed, you should write your own first draft of documentation. As the implementer of the component you have the most knowledge to write the most knowledgeable documentation. 



On Tue, Dec 20, 2016 at 4:44 AM -0500, "Vedran Karačić" <notifications@github.com> wrote:












@mjfrey this now leaves the question of documentation. Do we write the documentation for this or notify the documentation team?



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-12-20 17:14 UTC, mulby commented
@mjfrey @clintonb @vkaracic - Does this change allow us to process multiple items per transaction?

We built our audit process to handle this case (in theory), however, it has not be vetted very thoroughly since there have not been very many ways this could happen.

If this is going to become more commonplace, some subset of our two teams should probably figure out what the impact will be on the audit.

2016-12-20 17:14 UTC, mulby commented
@katymyw @stroilova @brianhw FYI

2016-12-21 08:17 UTC, vkaracic commented
Adding an item to the basket in our current flow does not support adding more than one product, but changes in this PR allow the basket to support multiple lines. The product adding logic is going to change at some point and we want everything else to be ready for supporting multiple lines, among which are analytics.

2017-01-02 12:16 UTC, saleem-latif commented on ecommerce/static/js/test/specs/pages/basket_page_spec.js
> +                        lastMonth = moment().subtract(1, 'month').month();
@vkaracic For some reason `moment().subtract(1, 'month').month()` is giving wrong number.

```
> moment().year()
 2017
> moment().month()
 0
> moment().subtract(1, 'month').month()
 11
```
I think this is the correct approach
```
> moment().subtract(1, 'month').year()
2016
> moment().subtract(1, 'month').month()
11
```
I am updating this here https://github.com/edx/ecommerce/pull/1071, please let me know if you have any concerns.

2017-01-02 14:20 UTC, saleem-latif commented on ecommerce/static/js/pages/basket_page.js
> +                Number(cardExpiryMonth) > 12 || Number(cardExpiryMonth) < 1) {
@vkaracic Upon further discovery I tracked another test failure to this place, in Javascript monthly numbering starts from 0 i.e. (Jan is represented by a 0, Feb with 1 and so on. so this check alsi needs to be updated.) I think it would be better to create a JIRA ticker for this to track the work.
@mattdrayer FYI

2017-01-03 02:02 UTC, mattdrayer commented on ecommerce/static/js/pages/basket_page.js
> +                Number(cardExpiryMonth) > 12 || Number(cardExpiryMonth) < 1) {
https://openedx.atlassian.net/browse/ENT-127