[SOL-2168] Add Backend Validation for Course Seat Types
openedx-unsupported/ecommerce pull request #1052
Opened 2016-12-14 13:02 UTC by iivic

The following cases are covered:
1. Value must be string or unicode (in range model)
2. 'credit' type can't be paired with other types (in range model)
3. Model values must be subset of ['credit', 'professional', 'verified'] (in range model)
4. On coupon creation course seat types must be a list or the method that joins the values will return a TypeError exception. I caught and handled the exception.

2016-12-14 13:03 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1052&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-14 14:12 UTC, davec-edx commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +
Should there be a corresponding positive test to confirm that list does work?

2016-12-14 14:29 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +
It doesn't hurt to add one 😄

2016-12-14 15:06 UTC, vkaracic requested changes

2016-12-14 15:06 UTC, vkaracic commented on ecommerce/extensions/offer/migrations/0006_auto_20161025_1446.py
> -            field=models.CharField(blank=True, max_length=255, null=True, validators=[ecommerce.extensions.offer.models.validate_credit_seat_type]),
Don't edit past migrations, create new one with the changes applied.

2016-12-14 15:06 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +                'Failed to create Range. Allowed values for course seat types are %s',
Nit: maybe indicate what exactly failed.

2016-12-14 15:06 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +    COURSE_SEAT_TYPES_VALUES = ['credit', 'professional', 'verified']
Nit: ``ALLOWED_SEAT_TYPES`` sounds better.

2016-12-15 08:51 UTC, iivic commented on ecommerce/extensions/offer/migrations/0006_auto_20161025_1446.py
> -            field=models.CharField(blank=True, max_length=255, null=True, validators=[ecommerce.extensions.offer.models.validate_credit_seat_type]),
That will not work. This is the only way I managed to remove it.

2016-12-15 10:44 UTC, iivic commented
Review once more.

2016-12-15 10:52 UTC, vkaracic approved these changes

2016-12-16 13:23 UTC, marjev requested changes

2016-12-16 13:23 UTC, marjev commented on ecommerce/extensions/offer/migrations/0006_auto_20161025_1446.py
> -            field=models.CharField(blank=True, max_length=255, null=True, validators=[ecommerce.extensions.offer.models.validate_credit_seat_type]),
create a new migration. Either generate it or do it manually.
In that migration, alter the field.

2016-12-19 13:59 UTC, iivic commented
@marjev

2016-12-19 14:56 UTC, marjev approved these changes

2016-12-19 15:02 UTC, merged

2017-02-03 10:13 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +def validate_credit_seat_type(course_seat_types, allowed_seat_types):
@iivic While trying to update a range, I am getting this error on django admin
```
TypeError at /admin/offer/range/3/
validate_credit_seat_type() takes exactly 2 arguments (1 given)
```
`validate_credit_seat_type` is used as a validator [here](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/offer/models.py#L191) which expects the method to require only one argument. So, I think this method should either not have a second arguments or second argument should have a default value.

2017-02-03 11:41 UTC, iivic commented on ecommerce/extensions/offer/models.py
> +def validate_credit_seat_type(course_seat_types, allowed_seat_types):
@saleem-latif I agree with you. The second argument is not required. I created a PR with the fix please review and test if it works for you (it did for me). https://github.com/edx/ecommerce/pull/1129