WIP WL-862 Multi-source analytics event tracking
openedx-unsupported/ecommerce pull request #1053
Opened 2016-12-14 19:10 UTC by douglashall

2016-12-22 21:31 UTC, douglashall commented
@mulby @bderusha @clintonb Please review. Thanks.

2016-12-29 14:21 UTC, douglashall commented
@rlucioni Would you be able to review this?

2016-12-29 15:44 UTC, clintonb requested changes
I see no need to include GA directly. We are already using Segment to contact GA. If multiple GA integrations are needed, you can either [add them to Segment](https://segment.com/docs/integrations/google-analytics/#multiple-trackers) or [use Google Tag Manager](http://www.kristaseiden.com/step-by-step-adding-a-second-ga-property-via-google-tag-manager/). 
Introducing multiplexing of this sort is something I'd rather outsource to companies that already do it, and keep our analytics footprint to a minimum.

2016-12-29 15:59 UTC, douglashall commented
@clintonb This PR implements the Segment-recommended way of including multiple GA trackers on a page which you have linked in your comment.

We could use GTM for sending page views to multiple GA properties, but we wouldn't be able to track other events that we may want to send client-side.

2016-12-29 16:00 UTC, douglashall commented
@clintonb Also, this can totally wait until next week. I have no plans to merge this today. No reason to cut your vacation short. :)

2017-01-09 15:42 UTC, douglashall commented
No longer needed.

2017-01-09 15:42 UTC, closed without merging