[SOL-2170] Unable to change single to multi courses once course id entered
openedx-unsupported/ecommerce pull request #1054
Opened 2016-12-16 12:51 UTC by iivic

Fixed bug on coupon creation page when course id entered and then changed from single course to multiple courses an error would appear on save because stock_record_ids would be set and because of that our api would create a catalog. In this case the coupon would have catalog and dynamic catalog set this will cause our validation to fail.

2016-12-16 12:52 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1054"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-16 13:08 UTC, vkaracic approved these changes

2016-12-19 13:58 UTC, iivic commented
@marjev

2016-12-19 14:54 UTC, marjev requested changes

2016-12-19 14:54 UTC, marjev commented on ecommerce/static/js/views/coupon_form_view.js
> +                    this.model.unset('stock_record_ids');
nitpick: order the calls semantically. remove/add class, remove element, unset model attribute ...

2016-12-19 14:54 UTC, marjev commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> +                    view.model.set('stock_record_ids', [1]);
```
view.model.set({
    'course_id': 'course id',
    'seat_type': 'seat type',
    'stock_record_ids': [1]
});
```

2016-12-20 14:33 UTC, iivic commented
@marjev

2016-12-20 14:53 UTC, marjev approved these changes

2016-12-20 14:54 UTC, merged