[SOL-2171] Add Backend validation for Email Domains
openedx-unsupported/ecommerce pull request #1056
Opened 2016-12-19 13:51 UTC by iivic

@vkaracic @marjev  The validation includes regex pattern validation from our frontend and validates if an empty string is sent for email_domains.

2016-12-19 13:52 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1056"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-19 14:21 UTC, marjev requested changes

2016-12-19 14:21 UTC, marjev commented on ecommerce/extensions/offer/models.py
> +            pattern = r'^((xn--)?[a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}(,((xn--)?[a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,})*$'
split and validate individually

2016-12-19 17:41 UTC, vkaracic commented on ecommerce/extensions/offer/tests/test_models.py
> +        offer = ConditionalOffer.objects.create(
Have you tried ``offer = ConditionalOfferFactory(email_domains=email_domains)`` ?

2016-12-19 17:41 UTC, vkaracic commented on ecommerce/extensions/offer/tests/test_models.py
> +            ConditionalOffer.objects.create(
Same here.

2016-12-20 14:34 UTC, iivic commented
Ready for second round.

2016-12-20 14:36 UTC, vkaracic commented on ecommerce/extensions/offer/tests/test_models.py
> +    def test_email_domains_validation(self, email_domains):
``test_invalid_email_domains_validation`` seems to be more appropriate.

2016-12-20 14:47 UTC, davec-edx commented on ecommerce/extensions/offer/tests/test_models.py
> +    def test_email_domains_validation(self, email_domains):
Suggest adding some with an extended character-set as well, that should also be in a valid email test as well.

2016-12-20 14:50 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +                    raise ValidationError(_('Email domain [{}] is invalid.'.format(domain)))
[4. Use placeholders with descriptive names](http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/conventions/internationalization/i18n.html#id2)

2016-12-22 11:05 UTC, iivic commented
@vkaracic @marjev

2017-01-19 09:21 UTC, iivic commented
Please take another look. I have completely redone the validation to cover all cases I could think of.

2017-01-19 09:58 UTC, marjev requested changes

2017-01-19 09:58 UTC, marjev commented on ecommerce/extensions/offer/models.py
> +                raise ValidationError(_('ConditionalOffer email domains must be type str or unicode.'))
nitpick: `must be of type string`

2017-01-19 09:58 UTC, marjev commented on ecommerce/extensions/offer/models.py
> +def log_message_and_raise_validation_error(message='Something went wrong.'):
Move this to `core/utils.py` so that it's reusable everywhere in the code.
Also, go through the code and see if this method can be used elsewhere.

2017-01-19 13:28 UTC, iivic commented
@clintonb I used punycode [](https://github.com/bestiejs/punycode.js/tree/v1.4.1) to encode email domains with extended character-set and validate them. The VersionEye is failing because it can't find the licence of punycode and I don't know how to fix this issue any advice?

2017-01-19 14:01 UTC, clintonb commented
@iivic ignore VersionEye for now.

2017-01-19 14:20 UTC, vkaracic requested changes

2017-01-19 14:20 UTC, vkaracic commented on ecommerce/core/models.py
> +            log_message_and_raise_validation_error(error_message)
Can you directly feed the string to the function without an additional variable?

2017-01-19 14:20 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +            log_message_and_raise_validation_error(error_message)
Same question here and at the change below. Omit declaring a new variable unnecessarily?

2017-01-19 14:20 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +            log_message_and_raise_validation_error(error_message)
Actually, to avoid leaving same comments throughout the PR, please change it everywhere that it's applicable.

2017-01-19 14:20 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +                    if not re.match(r'^([a-z0-9-]+)$', domain_part.encode('idna')):
For consistency sake, add a comment explaining what you are matching here.

2017-01-19 14:20 UTC, vkaracic commented on ecommerce/extensions/offer/tests/test_models.py
> +    def test_creating_offer_with_email_domains(self, email_domains):
Nit: I'd rename these two to ``test_creating_offer_with_valid_email_domains`` and ``test_creating_offer_with_invalid_email_domains``.

2017-01-19 14:20 UTC, vkaracic commented on ecommerce/static/js/models/coupon_model.js
> +                             * ...
What do the three dots mean?

2017-01-19 14:20 UTC, vkaracic commented on ecommerce/static/js/models/coupon_model.js
> +                    if (!_.isEmpty(val)) {
I'd move this check into an utility function.

2017-01-19 14:20 UTC, vkaracic commented on ecommerce/static/js/models/coupon_model.js
> +                                if (!domainRegex.test(encodedDomainPart)) {
Nit: Maybe just move the regex here and remove the variable since it's not used anywhere else.

2017-01-19 14:46 UTC, iivic commented on ecommerce/static/js/models/coupon_model.js
> +                             * ...
There are more conditions to be expected.

2017-01-20 09:56 UTC, iivic commented
@vkaracic Comments addressed.

2017-01-20 10:01 UTC, vkaracic commented on ecommerce/static/js/utils/utils.js
> +             * @returns {String} Returns invalid domain or undefined if all domains are valid.
The return value should be a boolean clearly indicating whether an email domain/s is/are valid or not.

2017-01-20 10:06 UTC, vkaracic approved these changes

2017-01-20 10:52 UTC, marjev requested changes

2017-01-20 10:52 UTC, marjev commented on ecommerce/core/utils.py
> +def log_message_and_raise_validation_error(message='Something went wrong.'):
remove default value. We don't want to call this method without providing a descriptive message. The default value is very non-descriptive and this would allow a programmer to use this method without providing a meaningful message.

2017-01-20 10:56 UTC, iivic commented
@marjev Default value removed.

2017-01-20 13:55 UTC, marjev approved these changes

2017-01-20 13:56 UTC, marjev commented
don't forget to squash the commits.

2017-01-20 15:30 UTC, merged