[SOL-2173] Add Backend Validation for End Datetime and Start Datetime
openedx-unsupported/ecommerce pull request #1058
Opened 2016-12-20 13:43 UTC by iivic

Added validation for the voucher model: 
 - when end_datetime or start_datetime is not set
 - when end_datetime or start_datetime is set but not type datetime
Moved the parse call from api to helper function and included more validation in the helper function in case that the value sent can't be parsed.

2016-12-20 13:43 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1058&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-21 08:52 UTC, iivic commented
@marjev @vkaracic

2016-12-21 09:16 UTC, vkaracic requested changes

2016-12-21 09:16 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_models.py
> +            Voucher.objects.create(**self.data)
You can combine these two, where no start or end datetime is passed, with ddt.

2016-12-21 09:16 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_models.py
> +            Voucher.objects.create(**self.data)
You can combine these two with ddt as well.

2016-12-21 09:16 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +            )
Again, ddt to combine the two tests above.

2016-12-21 09:16 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
> +            raise ValidationError(_('Voucher start datetime value [{date}] is invalid.'.format(date=start_datetime)))
And are validation errors raised when you remove all these changes here anyway?

2016-12-21 11:33 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
> +            raise ValidationError(_('Voucher start datetime value [{date}] is invalid.'.format(date=start_datetime)))
The validation here are set because of the dateutil.parser.parse(start_datetime). Exceptions are raised if the value can't be parsed or is not even a string.

2016-12-21 15:02 UTC, vkaracic approved these changes
The voucher tests look much better and slimmer now! Good job!

2016-12-21 15:02 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +            'max_uses': 1
Nit: Alphabetize this :smiley:

2016-12-21 15:21 UTC, marjev approved these changes

2016-12-21 15:40 UTC, merged