Fix Order API endpoint filtering
openedx-unsupported/ecommerce pull request #1060
Opened 2016-12-21 12:05 UTC by marjev

@mjfrey:

Here's the fix for the Order API endpoint. Let's discuss this after standup.
I would like to discuss the use-case and how this behaves when the old Receipt page is turned on.

2016-12-21 12:05 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1060"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-23 08:28 UTC, marjev commented
@mjfrey Is this still needed? If so, I'll write a test before we merge this.

2017-04-10 10:24 UTC, marjev commented
@edx/helio can someone review this?

We want to filter orders by site and show only those Orders fulfilled on the current ecommerce site.

2017-04-10 10:53 UTC, vkaracic approved these changes

2017-04-10 13:46 UTC, clintonb requested changes

2017-04-10 13:46 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
> +        factories.create_order(site=SiteFactory())
This test isn't doing what you think it is. Both of the orders are associated with different sites. I suspect this is only passing because `order.site` and `request.site` are `None`.

2017-04-10 13:46 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
> +        self.assertEqual(Order.objects.count(), 2)
Move this up a line. It seems strange to put it in the middle of assertions for `content`.

2017-04-10 13:46 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
>          order = factories.create_order(user=self.user)
```python
from ecommerce.extensions.test.factories import create_order
order = create_order(site=self.site)
```

2017-04-11 06:24 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
> +        factories.create_order(site=SiteFactory())
I think not. I've added two additional assertions to make sure that's not the case.

2017-04-11 12:42 UTC, clintonb requested changes

2017-04-11 12:42 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
> +        order = create_order(user=self.user)
Please explicitly associate all orders in this test with a `Site`. This only works because `OrderCreator` relies on `threadlocals`: https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/order/utils.py#L80-L81. In the future, I want to get rid of that library. Just as it lead to confusion here, it can lead to confusion in production. Our actions should always be explicit.

2017-04-11 13:53 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
> +        order = create_order(user=self.user)
Done.

2017-04-11 13:54 UTC, clintonb approved these changes

2017-04-11 13:54 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
> +        order_2 = create_order(user=self.user)
`site=self.site`

2017-04-12 06:46 UTC, clintonb approved these changes

2017-04-12 09:55 UTC, merged