add course catalog selection functionality to coupon admin tool
openedx-unsupported/ecommerce pull request #1066
Opened 2016-12-26 09:27 UTC by zubair-arbi

ENT-110

### WIP
@asadiqbal08 @saleem-latif @mattdrayer 

There were two ways to add catalogs selection functionality:

1. Provide catalogs lists from view and pass the list as an argument all the way to `coupon_form_view.js` from `coupon_app.js`
2. Get catalogs list through `ajax` while rendering the page `coupon_form.html`

I followed second approach which seems more suitable for our current requirement.
We also needed a new field to save the catalog id returned from the discovery service to display the selected catalog on edit coupon view and also to display catalog courses on offer redeem page.

* Add new field `course_catalog` to save the id for the related catalog in coupon range model
* Add migration for the `offer` model `Range`
* Update coupon form to display the new course type selection `Course catalog`
* Update coupon form to add a new field `course_catalog` to allow catalogs selection while creating coupons
* Update backend code to get the `course_catalog` value in the model `Range`
* Add method `get_all_course_catalogs` to recursively get all catalogs from the service `discovery`

<img width="1215" alt="screen shot 2016-12-26 at 2 26 42 pm" src="https://cloud.githubusercontent.com/assets/5072991/21479589/670d99ee-cb77-11e6-98f3-46707f4c06e4.png">

2016-12-26 11:38 UTC, saleem-latif reviewed
@zubair-arbi Some changes after going through the code.

2016-12-26 11:38 UTC, saleem-latif commented on ecommerce/coupons/utils.py
> +        if resource_id:
wouldn't `resource_id` alway be `None` ?

2016-12-26 11:38 UTC, saleem-latif commented on ecommerce/extensions/api/v2/views/catalog.py
> +            results = get_all_course_catalogs(site=request.site)
I think it would a good idea to add caching here, (We also discussed this in person)

2016-12-26 11:38 UTC, saleem-latif commented on ecommerce/static/js/views/coupon_form_view.js
> +                    url: window.location.origin + '/api/v2/catalogs/all_catalogs/',
why are we using `window.location.origin + '/api/v2/catalogs/all_catalogs/'` instead of using absolute url path `'/api/v2/catalogs/all_catalogs/'` ?

2016-12-26 11:38 UTC, saleem-latif commented on ecommerce/static/js/views/coupon_form_view.js
> +                    option = document.createElement('option');
nit: I think it would be readable to create `option` element using jquery.
```
option = $("<option></option>").val(catalog.id).text(catalog.name)
```

2016-12-26 16:03 UTC, asadiqbal08 commented on ecommerce/static/templates/coupon_form.html
> +            <label for="course-catalog"><%= gettext('Select from course catalogs:') %> *</label>
mark for translations  ?

2016-12-26 16:03 UTC, asadiqbal08 commented on ecommerce/static/templates/coupon_form.html
> +                <label for="catalog"><%= gettext('Course catalog') %></label>
mark for translation.

2016-12-26 16:03 UTC, asadiqbal08 commented on ecommerce/coupons/utils.py
> +log = logging.getLogger(__name__)
nit: LOGGER instead of log.

2016-12-26 16:05 UTC, asadiqbal08 commented on ecommerce/coupons/utils.py
> +def _traverse_pagination(response, endpoint, querystring, no_data):
what represent `endpoint` , `querystring` here? should include description in method docstring.

2016-12-26 16:07 UTC, asadiqbal08 commented on ecommerce/extensions/api/v2/views/catalog.py
> +    def all_catalogs(self, request):
it is returning catalogs. Name should be descriptive. get_all_course_catalogs ?

2016-12-26 16:08 UTC, asadiqbal08 commented on ecommerce/extensions/api/v2/views/catalog.py
> +        Get all course catalogs.
nit: return all course catalogs.

2016-12-26 16:09 UTC, asadiqbal08 commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        course_catalog=request.data.get('catalog'),
is `catalog` here referring to only one catalog ?

2016-12-26 16:14 UTC, asadiqbal08 commented on ecommerce/static/js/models/coupon_model.js
> +                        return this.get('catalog_type') === 'Course catalog';
can we use JS dict / hash here that can contain the course types in it  instead of matching like that ? 
e.g. 
CATALOG_TYPES = {
  DISCOUNT_CODE: 'Discount code', 
  . 
  . 
}

2016-12-26 16:15 UTC, asadiqbal08 commented on ecommerce/static/js/models/coupon_model.js
> +                if (this.has('catalog_query')) {
better to have `course_catalog_query` name here .

2016-12-27 19:42 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +        if resource_id:
Likewise for `querystring` -- it would always be `{}`

2016-12-27 19:47 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +def _traverse_pagination(response, endpoint, querystring, no_data):
While this method needs some tuning, it seems like a useful piece of functionality that could be added to https://github.com/edx/edx-rest-api-client.  This way other workflows could leverage the same capability.

2016-12-27 19:47 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +def _traverse_pagination(response, endpoint, querystring, no_data):
+1 on that

2016-12-27 19:49 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    results = response.get('results', no_data)
I guess I don't really see the point of passing around this `no_data` container -- is the re-use just an attempt to minimize the memory footprint, or is there a logical reason to share this structure that I am not seeing?

2016-12-27 19:51 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/catalog.py
> +    def all_catalogs(self, request):
if this is a wrapper around `get_all_course_catalogs` then I would name it the same and reference the imported method using its module namespace.

2016-12-27 19:52 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/catalog.py
> +        catalogs = sorted(results, key=lambda catalog: catalog.get('name', '').lower())
it would be nice if we could send the sort order to `get_all_course_catalogs`, instead of doing it here.

2016-12-27 19:55 UTC, mattdrayer commented on ecommerce/extensions/offer/models.py
> +    course_catalog = models.PositiveIntegerField(help_text=_('Course catalog id.'), null=True, blank=True)
Wait, I'm confused -- we are adding `course_catalog`, but there is already a `catalog` -- what is the difference between these two fields?  We will need to be very clear about the use for each.

2016-12-27 19:57 UTC, mattdrayer commented on ecommerce/extensions/voucher/utils.py
> +        benefit_type (str): Type of benefit associated with vouchers.
It seems this list follows the order of the arguments in the method signature.  I'm not sure if that is a standard/convention, but IMHO we should instead alphabetize this list.

2016-12-27 20:00 UTC, mattdrayer commented on ecommerce/static/js/views/coupon_form_view.js
> +                    option = document.createElement('option');
I actually think the current proposal reads easier than the jQuery version, so I'm okay keeping it as-is.

2016-12-27 20:01 UTC, mattdrayer commented on ecommerce/static/js/views/coupon_form_view.js
> +                        'course_catalog': this.catalogData[0].value,
Do we need to protect against an empty array here?

2016-12-28 10:49 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +log = logging.getLogger(__name__)
@asadiqbal08 there are two different conventions implemented in ecom for the logging variable name these are `log` and `logger`. Also the [python docs also gives example of using `logger` as variable name](https://docs.python.org/2/howto/logging.html#advanced-logging-tutorial).
I will  change the name to `logger`.

2016-12-28 11:00 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +def _traverse_pagination(response, endpoint, querystring, no_data):
@mattdrayer I agree that this is very useful functionality and in LMS we are already using it for `programs`, `credentials`, `catalogs` etc.
Would it make sense to have a separate story to add this functionality in `edx-rest-api-client` and update this code once we have new version available?

2016-12-28 11:06 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +    results = response.get('results', no_data)
@mattdrayer I am reusing the code from LMS. I believe the idea is to have a default in case the API we are using, does not provide the desired format causing exception or don't return anything.

2016-12-28 11:24 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/catalog.py
> +    def all_catalogs(self, request):
@mattdrayer Since this name become part of url so we cannot name it `get_all_course_catalogs`. Also I think we can change it to `course_catalogs`, this way the url will become: `/api/v2/catalogs/course_catalogs/`

2016-12-28 11:34 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        course_catalog=request.data.get('catalog'),
yes. I am updating it to `course_catalog`.

2016-12-28 11:49 UTC, zubair-arbi commented on ecommerce/extensions/offer/models.py
> +    course_catalog = models.PositiveIntegerField(help_text=_('Course catalog id.'), null=True, blank=True)
@mattdrayer The thing is that while creating the coupon the admin can provide a catalog query by selecting the `Multiple courses` option on `Coupon Admin Tool` page. Now interesting thing is that the catalog query is saved in the `Range` model instead of creating a catalog in the `discovery` service.

In our case we are managing the course catalogs provided by the `discovery`. So we had 2 possible solutions:

1. When admin will select a course catalog from discovery in CAT tool, use the existing `catalog_query` to save the query against the catalog. But then while viewing the coupon details and editing a coupon we will just have a query for a course catalog but we will not be able to tell which catalog (name of the catalog) it was in the discovery and this will be become problematic in case there are multiple catalog in discovery with same query or if the catalog query changes in the `discovery` service.
2. Add a new field `course_catalog` and just save the catalog id from the discovery service and then we wont have to worry if the name or the query change in the `discovery` service we will always be able to fetch fresh data from `discovery` this will increase the inter-services API calls but gives us flexibility. 

After some thinking we started following the second solution. Please let me know if this make sense or we can have a better approach.

2016-12-28 11:57 UTC, zubair-arbi commented on ecommerce/static/templates/coupon_form.html
> +                <label for="catalog"><%= gettext('Course catalog') %></label>
this is the default format for translation.

2016-12-28 11:57 UTC, zubair-arbi commented on ecommerce/static/templates/coupon_form.html
> +            <label for="course-catalog"><%= gettext('Select from course catalogs:') %> *</label>
already marked. `gettext` handles it.

2016-12-28 14:05 UTC, zubair-arbi commented on ecommerce/static/js/models/coupon_model.js
> +                if (this.has('catalog_query')) {
this is existing form field so don't want to change it.

2016-12-28 14:27 UTC, zubair-arbi commented on ecommerce/extensions/voucher/utils.py
> +        benefit_type (str): Type of benefit associated with vouchers.
It looks like we are following your suggested pattern in some other place in ecommerce and I think this would also  increase the readability so I will make the changes.

2016-12-28 14:32 UTC, zubair-arbi commented
@saleem-latif @mattdrayer @asadiqbal08 I have addressed almost all of your feedback. Please take another look.

2016-12-28 15:16 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    if cache_key:
It seems like there will always be a value for `cache_key` here.

2016-12-28 15:20 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +        cached = cache.get(cache_key)
Caching and cache control is another area that we should consider moving into the https://github.com/edx/edx-rest-api-client library.  Caching should be invisible to the service, although it should be possible to configure aspects of the caching mechanism (eg, TTL) in order to maintain control over performance and resource utilization.

2016-12-28 15:31 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    if cache_key:
As with above, it appears there will always be a value for cache_key

2016-12-28 15:32 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +def get_course_catalogs(site, resource_id=None):
This entire function seems like it should be moved into a "catalog service helpers" module.

2016-12-28 15:32 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +def _traverse_pagination(response, endpoint, no_data):
If `get_course_catalogs` is moved into a "helpers" module, this should accompany it.

2016-12-28 15:35 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/catalog.py
> +        except (ConnectionError, SlumberBaseException, Timeout):
It looks like this except may not be hit because `get_course_catalogs` has a catch-all `except` handler that swallows all exceptions and returns `no_data`

2016-12-28 15:37 UTC, mattdrayer commented on ecommerce/extensions/offer/models.py
> +    course_catalog = models.PositiveIntegerField(help_text=_('Course catalog id.'), null=True, blank=True)
Thank you for the explanation -- the second approach described above is the proper solution.

2016-12-28 15:38 UTC, mattdrayer commented on ecommerce/extensions/voucher/utils.py
> +        course_catalog=None,
Is it safe to reorder these arguments?  We need to be careful when modifying method signatures.

2016-12-28 15:39 UTC, mattdrayer commented on ecommerce/extensions/voucher/utils.py
> +        max_uses (int): Number of Voucher max uses. Defaults to None.
Looks like `max_uses` and `_range` missed out on the alphabetization party

2016-12-28 15:41 UTC, mattdrayer commented on ecommerce/static/js/models/coupon_model.js
> +                    catalog_type = 'Catalog course'
I think this should just be "Catalog"

2016-12-28 15:43 UTC, mattdrayer commented on ecommerce/static/templates/coupon_form.html
> +                <label for="catalog"><%= gettext('Course catalog') %></label>
Let's be sure we are consistent with capitalization -- above we have `Course Catalog`

2016-12-29 09:21 UTC, zubair-arbi commented on ecommerce/static/templates/coupon_form.html
> +                <label for="catalog"><%= gettext('Course catalog') %></label>
@mattdrayer existing values have only first word in camel case, e.g, `Single course`, `Multiple courses`.

2016-12-29 09:22 UTC, zubair-arbi commented on ecommerce/static/js/models/coupon_model.js
> +                    catalog_type = 'Catalog course'
I will update this

2016-12-29 09:23 UTC, zubair-arbi commented on ecommerce/extensions/voucher/utils.py
> +        max_uses (int): Number of Voucher max uses. Defaults to None.
Aaah, I will fix it.

2016-12-29 09:35 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +def get_course_catalogs(site, resource_id=None):
@mattdrayer We don't have any catalog service app available in the Ecom, so should we create `catalog_service_helpers.py` in `coupons` app?

2016-12-29 09:42 UTC, zubair-arbi commented on ecommerce/extensions/voucher/utils.py
> +        course_catalog=None,
I am not sure, I will revert the change to method signature.

2016-12-29 09:48 UTC, zubair-arbi commented on ecommerce/extensions/voucher/utils.py
> +        max_uses (int): Number of Voucher max uses. Defaults to None.
Oho, I have updated the order for `max_uses` but I am not sure where to put `_range` in this order.
[This site](http://alphabetizer.flap.tv) suggests moving it at the top of list but it seems more appropriate to put it at the end.

2016-12-29 10:01 UTC, zubair-arbi commented on ecommerce/static/js/models/coupon_model.js
> +                        return this.get('catalog_type') === 'Course catalog';
Sure, I am going to add a dict:
```javascriptcatalogTypes: {
    single_course: 'Single course',
    multiple_courses: 'Multiple courses',
    catalog: 'Catalog'
},
```

2016-12-29 10:04 UTC, zubair-arbi commented on ecommerce/static/js/models/coupon_model.js
> +                    catalog_type = 'Catalog course'
I will update the field

2016-12-29 14:32 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +def get_course_catalogs(site, resource_id=None):
I'm okay doing that to start, although it seems like a better place would be a `utils` package.

2016-12-29 14:34 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +def get_course_catalogs(site, resource_id=None):
Actually I would prefer introducing a `services` package, but I haven't seen that convention anywhere else.  It makes sense to me, however.

2016-12-29 14:41 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    cache.set(cache_key, results, settings.COURSES_API_CACHE_TIMEOUT)
We should introduce a new setting for the catalog service, which I think is different from the "courses API" -- eg `CATALOG_API_CACHE_TIMEOUT`

2016-12-29 14:45 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +                    return Response('Invalid coupon Course Catalog data.', status=status.HTTP_400_BAD_REQUEST)
"Unexpected catalog data format received for coupon."

2016-12-29 14:46 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +                range_data['course_catalog'] = course_catalog_data.get('id')
Do we care about an unexpected catalog data schema here, as on line 119?

2016-12-29 14:48 UTC, mattdrayer commented on ecommerce/extensions/offer/models.py
> +    course_catalog = models.PositiveIntegerField(help_text=_('Course catalog id.'), null=True, blank=True)
Maybe we can add something to the help text about being from the Catalog/Discovery service.

2016-12-29 14:51 UTC, mattdrayer commented
Looking good @zubair-arbi!  I think we are almost there with this PR.  Just a few more items to address.

2016-12-29 15:01 UTC, zubair-arbi commented on ecommerce/extensions/offer/models.py
> +    course_catalog = models.PositiveIntegerField(help_text=_('Course catalog id.'), null=True, blank=True)
@mattdrayer Can you please suggest some text? I am thinking of `Course catalog id from catalog service`.

2016-12-29 15:05 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +def get_course_catalogs(site, resource_id=None):
Where do you think we be best place for that package? At the same level of main apps, e.g. `core`, `coupons` etc or in `ecommerce/extensions`? I believe `extensions` dir is for overriding oscar apps so we can create at main apps level.

2016-12-29 15:07 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +    cache.set(cache_key, results, settings.COURSES_API_CACHE_TIMEOUT)
Would it be sufficient to set the default value at `3600  # Value is in seconds`?
If we add this new settings variable then we will also need to make sure that the devops can update this setting through configuration.

2016-12-29 15:14 UTC, mattdrayer commented on ecommerce/extensions/offer/models.py
> +    course_catalog = models.PositiveIntegerField(help_text=_('Course catalog id.'), null=True, blank=True)
That works for me, although I would capitalize "Catalog Service"

2016-12-29 15:18 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    cache.set(cache_key, results, settings.COURSES_API_CACHE_TIMEOUT)
Yes, that is the default value for the COURSES API setting, so I think it makes sense.  Agreed that we should add support for this setting to https://github.com/edx/configuration/blob/master/playbooks/roles/ecommerce/defaults/main.yml but I do not see anything in that repository for `COURSES_API_CACHE_TIMEOUT`

2016-12-29 15:19 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    cache.set(cache_key, results, settings.COURSES_API_CACHE_TIMEOUT)
@edx/devops  FYI ^^ -- do you have a recommendation for what to do here?

2016-12-29 16:23 UTC, mattdrayer commented
@vkaracic FYI on this PR

2016-12-30 06:15 UTC, asadiqbal08 commented on ecommerce/static/templates/coupon_form.html
> +                <label for="catalog"><%= gettext('Course catalog') %></label>
ah. I forgot it.

2016-12-30 06:32 UTC, asadiqbal08 commented on ecommerce/static/js/collections/catalog_collection.js
> +              Catalog) {
why breaking the line here ?

2016-12-30 06:37 UTC, asadiqbal08 commented on ecommerce/static/js/collections/catalog_collection.js
> +                model: Catalog,
Is the collection here keeping the list of catalog models ?

2016-12-30 06:37 UTC, asadiqbal08 commented on ecommerce/static/js/collections/catalog_collection.js
> +              Catalog) {
would it be `catalog` of `catalogs` ?

2016-12-30 06:41 UTC, asadiqbal08 commented on ecommerce/static/js/models/catalog_model.js
> +        return Backbone.RelationalModel.extend({
you are making a relational model here. can you tell me where are you defining the relations ? 
do you not require to specify the key here in case of relational model ?? To which model it is related ?

2016-12-30 07:32 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +                range_data['course_catalog'] = course_catalog_data.get('id')
I don't think we need same logic here, since on coupon creation we are doing all stuff in `transaction.atomic` so any error will roll back the transaction. But here we are only updating individual fields so it would make sense to let the exception raise and this is the current behavior too.

2016-12-30 07:35 UTC, zubair-arbi commented on ecommerce/static/js/collections/catalog_collection.js
> +              Catalog) {
1. We are breaking line after each param and this is convention we are following.
2. It would be Catalog (as its a model not multiple objects of a model)

2016-12-30 07:35 UTC, zubair-arbi commented on ecommerce/static/js/collections/catalog_collection.js
> +                model: Catalog,
That's correct.

2016-12-30 07:44 UTC, zubair-arbi commented on ecommerce/static/js/models/catalog_model.js
> +        return Backbone.RelationalModel.extend({
Catalog. The data will be fetched from `course_catalogs` api.

2016-12-30 07:46 UTC, asadiqbal08 commented on ecommerce/static/js/collections/catalog_collection.js
> +              Catalog) {
collection contain the multiple objects of model

2016-12-30 08:02 UTC, asadiqbal08 commented
Beside some @mattdrayer comments. changes overall LGTM 👍

2017-01-02 09:51 UTC, saleem-latif commented on ecommerce/static/templates/coupon_detail.html
> +        <div class="info-item grid-item catalog-query">
nit change `catalog-query` to something like `catalog-name`

2017-01-03 02:16 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +def get_course_catalogs(site, resource_id=None):
I think the main apps level is the proper place for this new package.  You are correct in that `extensions` is intended for overriding the base oscar apps.

2017-01-03 02:17 UTC, mattdrayer commented on ecommerce/static/js/models/catalog_model.js
> +        return Backbone.RelationalModel.extend({
If it's not clear we could add a code comment.

2017-01-03 02:45 UTC, mattdrayer commented
So very very close!  If we can address the refactoring concern above (services package), rebase, and see some green checks, I'm a 👍 .  It would be great if @vkaracic could take a spin through as well.

2017-01-03 13:40 UTC, zubair-arbi commented
@mattdrayer I have added `services` package, Please let me know about your thoughts on this.

2017-01-03 13:59 UTC, mattdrayer commented on ecommerce/services/__init__.py
> +This package will be used as a wrapper for interacting with the edX services
Here I would say "This package contains clients and related tools for communicating with other Open edX services.

2017-01-03 14:00 UTC, mattdrayer commented on ecommerce/settings/base.py
> +    'ecommerce.services',
This is interesting -- I didn't realize we had to declare this package as a "local app" -- I guess I don't have a problem with doing so, more just a TIL (Today I Learned) thing.

2017-01-03 14:02 UTC, mattdrayer commented
@zubair-arbi -- overall this is what I had in mind.  Just one small change request, and we'll need to add/move pertinent tests as well.

2017-01-03 17:34 UTC, jibsheet commented on ecommerce/services/course_discovery.py
> +    cache.set(cache_key, results, settings.CATALOG_API_CACHE_TIMEOUT)
@mattdrayer I'm not sure what devops input you were looking for here.
As long as it follows the patterns set out elsewhere in ecommerce (which @clintonb recently cleaned up) I believe it will be fine.

Remember that ecommerce does not currently have a memcache deployed (because it was never requested).  There's a ticket to build and deploy one, but until then, this will use whatever the django default cache is for things (per process I believe) - so be certain your code will perform in that use case.

2017-01-04 15:16 UTC, vkaracic reviewed
Mostly questions and nits. Overall looks good.

2017-01-04 15:16 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/catalog.py
> +        data = {'results': sorted_catalogs}
Nit: You could just add the dict directly to the response, no need for initializing another variable.

2017-01-04 15:16 UTC, vkaracic commented on ecommerce/services/utils.py
> +        no_data (list): Response in case of empty API result
Is this parameter relevant? When/why will ``no_data`` be anything than an empty list?

2017-01-04 15:16 UTC, vkaracic commented on ecommerce/services/tests/test_course_discovery.py
> +        self.assertEqual(cached_course, response)
These two tests, this one and the one above, are pretty much the same. You could combine them with ``ddt``.

2017-01-04 15:16 UTC, vkaracic commented on ecommerce/services/tests/test_course_discovery.py
> +        self.assertEqual(cached_course, response)
You could DRY these lines. Factor out lines 96-98 to a ``assert_empty_cache(cache_key)`` method and the rest of the code below that to another method, maybe ``verify_catalog_response()``.

2017-01-04 15:16 UTC, vkaracic commented on ecommerce/static/js/models/coupon_model.js
> +        var CATALOG_TYPES = {
Out of curiosity, have you tried using ``const``?

2017-01-04 15:16 UTC, vkaracic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        } else if (!$.isEmptyObject(this.model.get('course_catalog'))) {
I'm curious, when will ``course_catalog`` be an empty object?

2017-01-05 08:49 UTC, zubair-arbi commented on ecommerce/services/utils.py
> +        no_data (list): Response in case of empty API result
For our current implementation the default response `no_data` is always set to empty list. This is to ensure the default value remains same in case we get empty response while traversing the paginated API responses.

2017-01-05 08:56 UTC, zubair-arbi commented on ecommerce/static/js/models/coupon_model.js
> +        var CATALOG_TYPES = {
Nope. Nice suggestion to use [`const`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/const). I will make the change.

2017-01-05 09:06 UTC, zubair-arbi commented on ecommerce/static/js/views/coupon_form_view.js
> +                        } else if (!$.isEmptyObject(this.model.get('course_catalog'))) {
If there are not catalogs and default empty value is selected.

2017-01-05 10:58 UTC, vkaracic commented on ecommerce/services/utils.py
> +        no_data (list): Response in case of empty API result
I get that, but I don't see when will this ever be anything than an empty list.

2017-01-05 11:51 UTC, zubair-arbi commented on ecommerce/services/utils.py
> +        no_data (list): Response in case of empty API result
You are right, So what do you suggest?

2017-01-05 11:53 UTC, vkaracic commented on ecommerce/services/utils.py
> +        no_data (list): Response in case of empty API result
Just remove the ``no_data`` parameter and change line 29 here to user ``[]`` instead of ``no_data``.

2017-01-06 16:20 UTC, mattdrayer commented
Welcome back, @mjfrey!  Here's the PR we've discussed -- please feel free to take a walk thru.

2017-01-06 16:47 UTC, mjfrey requested changes
A quick first pass.

2017-01-06 16:47 UTC, mjfrey commented on ecommerce/coupons/tests/mixins.py
> +            course_catalog (int): Course catalog id from discovery service
Course catalog id from Catalog Service

2017-01-06 16:47 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/catalog.py
> +from ecommerce.services.course_discovery import get_course_catalogs
No need to put this in a new app.  We already call the catalog service from courses/utils.  I would re-locate this there.

2017-01-06 16:47 UTC, mjfrey commented on ecommerce/services/course_discovery.py
> +"""
move this function to courses/utils.py

2017-01-06 16:47 UTC, mjfrey commented on ecommerce/services/course_discovery.py
> +        response = endpoint(resource_id).get()
Are there permissions we need to care about?  For example this is pulling all catalogs for a site.

2017-01-06 16:47 UTC, mjfrey commented on ecommerce/services/course_discovery.py
> +        response = endpoint(resource_id).get()
Do catalogs contains course_runs or courses?  Coupons / Vouchers expect course_runs so we should be careful.  I also do not see the logic that checks for this upon redemption.  Is that not here yet?

2017-01-09 08:12 UTC, zubair-arbi commented on ecommerce/services/course_discovery.py
> +        response = endpoint(resource_id).get()
@mjfrey We need to get all catalogs for a site.
We have a separate story to update the redemption logic to handle course runs based on the course catalog id.

2017-01-09 13:55 UTC, zubair-arbi commented
@mattdrayer Hurray the build is green now :)
@mjfrey I have addressed your feedback, Please have another look.

2017-01-09 18:36 UTC, mjfrey requested changes

2017-01-09 18:36 UTC, mjfrey commented on ecommerce/courses/utils.py
> +    cache_key = '{}.{}'.format(base_cache_key, resource_id) if resource_id else base_cache_key
I think we want to add the site in the key so we do not get a cached version for a different site.

2017-01-09 18:36 UTC, mjfrey commented on ecommerce/courses/utils.py
> +        logger.exception('Failed to retrieve data from the Course Discovery API.')
This method should throw an exception not log an error.  The caller should try / catch this call and do what is appropriate.  See get_course_info_from_catalog.

2017-01-09 18:36 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/catalog.py
> +        results = get_course_catalogs(site=request.site)
this should be in a try / catch around get_course_catalogs.

2017-01-09 18:36 UTC, mjfrey commented on ecommerce/settings/base.py
> +CATALOG_API_CACHE_TIMEOUT = 3600  # Value is in seconds
Do we really need another setting or can we just share COURSES_API_CACHE_TIMEOUT?

2017-01-09 18:51 UTC, mattdrayer commented on ecommerce/settings/base.py
> +CATALOG_API_CACHE_TIMEOUT = 3600  # Value is in seconds
We could share it but semantically speaking I think these two things are different

2017-01-09 19:46 UTC, mjfrey commented on ecommerce/settings/base.py
> +CATALOG_API_CACHE_TIMEOUT = 3600  # Value is in seconds
COURSES_API_CACHE_TIMEOUT is the setting we use today for the TTL of the results from the catalog service.

2017-01-09 20:02 UTC, mattdrayer commented on ecommerce/settings/base.py
> +CATALOG_API_CACHE_TIMEOUT = 3600  # Value is in seconds
Okay, we'll just use that, then -- @zubair-arbi FYI ^^

2017-01-10 12:20 UTC, zubair-arbi commented
@mjfrey Thanks for providing valuable feedback. I have addressed your comments. Please give another review.

2017-01-11 16:38 UTC, mikedikan reviewed
Overall, this looks pretty good.  I couldn't see any big architectural problems, just a few questions, some code style suggestions, and some nitpicks.

2017-01-11 16:38 UTC, mikedikan commented on ecommerce/courses/tests/test_utils.py
> +        # Verify the API was hit for once
nit: "was hit once"

2017-01-11 16:38 UTC, mikedikan commented on ecommerce/extensions/api/v2/views/coupons.py
> +    def create(self, request, *args, **kwargs):  # pylint: disable=too-many-statements
I don't think this is the right response to this pylint error - this method should be broken up with some private helpers.

2017-01-11 16:38 UTC, mikedikan commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        course_catalog_vouchers = course_catalog_coupon.attr.coupon_vouchers.vouchers.all()
this whole method has a lot of chaining objects/methods.  (this.that.other_thing.other_other_thing.first().final_thing).  If it wasn't a test method, i'd be concerned about testing for null conditions to avoid exceptions.  I didn't see any occurences in the actual code of this kind of chaining, but It might be valuable to add a helper method to the coupon and voucher objects to make this a little cleaner.

2017-01-11 16:38 UTC, mikedikan commented on ecommerce/static/js/test/spec-runner.js
> +window.ecommerce.catagories = window.ecommerce.catagories || {};
nit: catagories -> categories

2017-01-11 16:38 UTC, mikedikan commented on ecommerce/static/js/test/specs/models/coupon_model_spec.js
> +                    expect(model.isValid()).toBeFalsy();
curious - do we not know exactly if this is false?  why tobefalsy?

2017-01-11 16:39 UTC, mikedikan commented
I've asked @AlasdairSwan to do a quick sanity check (this afternoon) on the backbone app changes.  They look fine to me, but I bow to his superior knowledge.

2017-01-11 18:37 UTC, mjfrey approved these changes

2017-01-11 18:46 UTC, AlasdairSwan requested changes

2017-01-11 18:46 UTC, AlasdairSwan commented on ecommerce/static/js/apps/coupon_admin_app.js
> +            ecommerce.coupons.catalogs.url = '/api/v2/catalogs/course_catalogs/';
This url is already being set in the Collection itself, why is it being added here too?

2017-01-11 18:46 UTC, AlasdairSwan commented on ecommerce/static/js/models/coupon_model.js
> +        const CATALOG_TYPES = {
This is ES2015, are you running Babel to ensure it doesn't break legacy browsers?

2017-01-11 18:46 UTC, AlasdairSwan commented on ecommerce/static/js/test/specs/models/coupon_model_spec.js
> +                    expect(model.isValid()).toBeFalsy();
Yeah, this seems very loose. I would prefer a check to determine that ```model.isValid()``` is ```false```.

2017-01-12 07:27 UTC, zubair-arbi commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        course_catalog_vouchers = course_catalog_coupon.attr.coupon_vouchers.vouchers.all()
@mikedikan You are right about doing lot of chaining here but since this is a test and if some exception or null condition occurs then test would fail and that's what we want to happen. There are other tests where we are chaining like here.

2017-01-12 09:46 UTC, zubair-arbi commented on ecommerce/static/js/models/coupon_model.js
> +        const CATALOG_TYPES = {
@AlasdairSwan I haven't used Babel for legacy browsers but the tests are running fine for Firefox 42 which is default for the ecommerce devstack. Here are the browser compatibility stats:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/const#Browser_compatibility
The desktop version of browsers seen supporting this but the mobile version don't seen sure about this constant. So I am going to use var instead to avoid any issues.

2017-01-12 09:55 UTC, zubair-arbi commented on ecommerce/static/js/apps/coupon_admin_app.js
> +            ecommerce.coupons.catalogs.url = '/api/v2/catalogs/course_catalogs/';
This is redundant, I am removing this line.

2017-01-12 10:33 UTC, zubair-arbi commented on ecommerce/static/js/test/specs/models/coupon_model_spec.js
> +                    expect(model.isValid()).toBeFalsy();
From your discussion what I understood is to modify the statement like:
```javascript
expect(model.isValid()).toBe(false);
```
Reference: http://stackoverflow.com/questions/32615713/tobetrue-vs-tobetruthy-vs-tobetrue

2017-01-12 13:00 UTC, zubair-arbi commented
@mikedikan @AlasdairSwan I have addressed your feedback, please review again.

2017-01-12 13:42 UTC, mikedikan approved these changes

2017-01-12 14:29 UTC, AlasdairSwan approved these changes

2017-01-12 14:39 UTC, mattdrayer commented
@zubair-arbi -- looks like we have at least 27 +1's now 😉 -- please rebase, squash, and merge after final Jenkins checks are passing.  Nice job sticking with this one!

2017-01-13 09:46 UTC, merged