Change state and postal code fields to be required.
openedx-unsupported/ecommerce pull request #1072
Opened 2016-12-29 12:57 UTC by vkaracic

Basket checkout validation now:
![screenshot from 2016-12-29 13-51-44](https://cloud.githubusercontent.com/assets/2808092/21544377/a382b6ee-cdce-11e6-8ac1-6a0adadef1b6.png)

FYI @clintonb 

https://openedx.atlassian.net/browse/ECOM-6693

2016-12-29 12:57 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1072&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2016-12-29 15:17 UTC, clintonb requested changes
Margining this as-is will cause issues for users outside of North America.

2016-12-29 15:17 UTC, clintonb commented on ecommerce/extensions/payment/forms.py
> +    state = forms.CharField(max_length=60, label=_('State/Province'))
These should only be required for buyers in the U.S. and Canada. See the clean method below.

2016-12-29 16:21 UTC, vkaracic commented on ecommerce/extensions/payment/forms.py
> +    state = forms.CharField(max_length=60, label=_('State/Province'))
Okay, so that then leaves the question do we need the state and postal code information for non-US/CA buyers, @mjfrey? Just the address is enough for the SDN check.

2016-12-29 23:37 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +    state = forms.CharField(max_length=60, label=_('State/Province'))
Why are these only required for US/CA buyers?  Are there counties that do not have these and can still purchase things with a CC?

2016-12-29 23:39 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +    state = forms.CharField(max_length=60, label=_('State/Province'))
I see now that there are many countries without postal codes.  So yes @vkaracic just move to the clean method for US/CA learners and we will use what we have for address SDN checking.

2017-01-04 15:38 UTC, vkaracic commented
I've changed this PR to make the postal code field optional. Please take another look.

2017-01-04 16:18 UTC, mjfrey requested changes

2017-01-04 16:18 UTC, mjfrey commented on ecommerce/extensions/payment/views/cybersource.py
> +            # Postal code is optional
I still think we need to not have this optional for US / CA.  Add a check in the clean method.

2017-01-04 16:28 UTC, vkaracic commented on ecommerce/extensions/payment/views/cybersource.py
> +            # Postal code is optional
Actually that's in an older PR: https://github.com/edx/ecommerce/pull/1062 I'd appreciate if you could review it though.

2017-01-05 15:20 UTC, mjfrey commented on ecommerce/extensions/payment/views/cybersource.py
> +            # Postal code is optional
So what happens if I am in CA / US and I leave out the postal code.

2017-01-05 15:25 UTC, mjfrey approved these changes

2017-01-05 15:55 UTC, vkaracic commented on ecommerce/extensions/payment/views/cybersource.py
> +            # Postal code is optional
This happens in that case.
![screenshot from 2017-01-05 16-54-48](https://cloud.githubusercontent.com/assets/2808092/21686994/bcb0f25e-d367-11e6-844c-57423861a903.png)

2017-01-05 15:56 UTC, vkaracic commented
@clintonb can you please take a second look?

2017-01-05 16:04 UTC, clintonb approved these changes

2017-01-05 16:16 UTC, merged