[ECOM-6746] Editing Single Course Coupon Code to Multi-Course Redeems…
openedx-unsupported/ecommerce pull request #1088
Opened 2017-01-09 12:45 UTC by iivic

https://openedx.atlassian.net/browse/ECOM-6746
On coupon edit page when saving changes in case of single-use vouchers the max_uses field is set to 1. This will set the global_max_applications to 1 which means that the coupon can be redeemed only once. The max_uses field should not be set in case of single-use vouchers.
@mjfrey @vkaracic @marjev

2017-01-09 12:45 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1088"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-01-10 09:07 UTC, vkaracic commented
Have you tested that a single-use coupon can be redeemed only once now?

2017-01-10 09:13 UTC, vkaracic approved these changes

2017-01-10 09:14 UTC, iivic commented
@vkaracic Yes I did.

2017-01-10 09:15 UTC, marjev approved these changes

2017-01-10 11:54 UTC, iivic commented
Please review one more time I included the management command.

2017-01-10 15:44 UTC, mjfrey approved these changes

2017-01-10 15:46 UTC, vkaracic requested changes

2017-01-10 15:46 UTC, vkaracic commented on ecommerce/extensions/offer/tests/test_commands.py
> +    def test_command_without_sample(self):
Please add a unit test to verify vouchers other than the ones within filter conditions are remain unaffected after running this command.

2017-01-11 12:51 UTC, vkaracic approved these changes

2017-01-11 12:55 UTC, merged