[SOL-2188] Make state field required for CA and US.
openedx-unsupported/ecommerce pull request #1091
Opened 2017-01-12 14:58 UTC by vkaracic

https://openedx.atlassian.net/browse/SOL-2188

2017-01-12 14:58 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1091"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-01-12 15:38 UTC, mjfrey approved these changes

2017-01-13 09:51 UTC, iivic requested changes

2017-01-13 09:51 UTC, iivic commented on ecommerce/static/js/pages/basket_page.js
> +            if ($('select[name=country').val() === 'US' || $('select[name=country').val() === 'CA') {
You forgot to close the parenthesis [name=country].
Just an idea `if (['US', 'CA'].indexOf($('select[name=country]').val()) > -1)`. You decide if you want to use it.

2017-01-13 09:51 UTC, iivic commented on ecommerce/static/js/pages/basket_page.js
> +                    $('#div_id_state label').text('State/Province (required)');
Nitpick: `$('#div_id_state label') `is a good selector but `$('#div_id_state').find('label')` is better according to https://learn.jquery.com/performance/optimize-selectors/

2017-01-13 09:51 UTC, iivic commented on ecommerce/static/js/pages/basket_page.js
> +                    $('#div_id_state label').text('State/Province');
Nitpick: jquery selector like mentioned.

2017-01-13 09:51 UTC, iivic commented on ecommerce/static/js/test/specs/pages/basket_page_spec.js
> +                        '<div class="controls"><input name="state"></div></div>' +
Not your fault but it seems that one div closing tag is missing `</div>`?

2017-01-13 09:51 UTC, iivic commented on ecommerce/static/js/test/specs/pages/basket_page_spec.js
> +                    expect($('#div_id_state label').text()).toEqual('State/Province (required)');
Nitpick: jquery selector like mentioned.

2017-01-13 11:31 UTC, vkaracic commented on ecommerce/static/js/pages/basket_page.js
> +                    $('#div_id_state label').text('State/Province (required)');
I'm not sure if there is an increase in speed.
```
although the speed improvement may be diminished by the subsequent call to .find().
```

2017-01-13 11:55 UTC, vkaracic commented
@iivic comments addressed, please take another look.

2017-01-13 12:02 UTC, iivic approved these changes

2017-01-13 14:32 UTC, merged