ENT-110: Add Catalog selection option to Coupon create/edit form
openedx-unsupported/ecommerce pull request #1093
Opened 2017-01-13 13:06 UTC by zubair-arbi

ENT-110
@asadiqbal08 @saleem-latif @mattdrayer 

This is a rework of adding catalog selection functionality on coupon create/edit form which I merged today "13-Jan-2016" and had to revert since the field `catalog` in `Range` model was passed as empty value.
## Branch History:
**Original PR:** https://github.com/edx/ecommerce/pull/1066
**Reverted PR:** https://github.com/edx/ecommerce/pull/1092

There were two ways to add catalogs selection functionality:

1. Provide catalogs lists from view and pass the list as an argument all the way to `coupon_form_view.js` from `coupon_app.js`
2. Get catalogs list through `ajax` while rendering the page `coupon_form.html`.

I followed second approach which is currently being used for populating the `catagories` field and also seems more suitable for our current requirement.

We also needed a new field to save the catalog id returned from the discovery service to display the selected catalog on edit coupon view and also to display catalog courses on offer redeem page. Saving the catalog id on our end will abstract us away from any changes (name, query etc) being made in the service `discovery`. 

> _**Note:** We will need to create a follow up story to update the `Redeem` coupon page to use the new field `course_catalog` for displaying the courses against some coupon._

## Completed tasks:
* Add new field `course_catalog` to save the id for the related catalog in coupon range model
* Add migration for the `offer` model `Range`
* Update coupon form to display the new course type selection `Catalog`
* Update coupon form to add a new field `course_catalog` to allow catalogs selection while creating coupons
* Update backend code to save the `course_catalog` value in the model `Range`
* Add method `get_course_catalogs` to recursively get all catalogs or a single course catalog from the service `discovery`
* Update serializer `CouponSerializer` to include `course_catalog` field
* Display course catalog name on the coupon detail page in case of `Catalog`
* Update the `Coupon edit page` for course catalogs
* Use existing settings variable `COURSES_API_CACHE_TIMEOUT` for caching the Course Catalogs API response which has default value of `3600  # Value is in seconds`.
* Refactor the method `create` of class `CouponViewSet` and move all cleaning/validation logic to separate class method `clean_voucher_request_data`.
* Add unit tests
* Add js tests (https://github.com/edx/ecommerce/pull/1071)

### Coupon create page
<img width="609" alt="screen shot 2016-12-30 at 4 15 46 pm" src="https://cloud.githubusercontent.com/assets/5072991/21564125/879db70c-ceab-11e6-9a54-ef86ed5809ac.png">

### Coupon detail page
<img width="605" alt="screen shot 2016-12-30 at 4 16 07 pm" src="https://cloud.githubusercontent.com/assets/5072991/21564129/8ff0cb06-ceab-11e6-8b15-8b73c59fa021.png">

### Coupon edit page
<img width="605" alt="screen shot 2016-12-30 at 4 16 33 pm" src="https://cloud.githubusercontent.com/assets/5072991/21564133/97fac694-ceab-11e6-9f94-67e3f0ff9d04.png">

## Related stories to this feature (future):
* Update coupon redemption logic to handle course runs based on the catalog fetched on the basis of new `Range` model field `course_catalog`
* Update coupon report generation method to include course catalogs

2017-01-13 13:18 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +            'coupon_catalog': coupon_catalog,
Good catch on this issue, @zubair-arbi -- let's be sure to cover it with a test, and then I am good with the fix.

2017-01-13 13:39 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +            'coupon_catalog': coupon_catalog,
@mattdrayer I am now using the key lookup instead of using dict get method. This way if the key in not available we will get the `KeyError`. For our current case the tests will throw:
```python
KeyError: u'coupon_catalog'
```

2017-01-13 13:46 UTC, zubair-arbi commented
@mattdrayer @mikedikan @mjfrey I would really appreciate if you guys can do another review. We had to revert the [original PR|https://github.com/edx/ecommerce/pull/1066] due to the `catalog` field being set to `None`.

The reason for `catalog` field being set to `None` was a typo in the keys returned by the new helper method `clean_voucher_request_data` which I created in order to refactor the main `create` method of class `CouponViewSet`. Now I have updated to code to throw `KeyError` if a key is missing or wrong in the response dict returned by the method `clean_voucher_request_data`.

2017-01-13 13:47 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +            'coupon_catalog': coupon_catalog,
okay -- I think we should have @vkaracic take a look at this change as well -- if I understand this change correctly then we are now requiring all of these parameters to be provided in `request.data`, whereas using `.get()` the parameters could be passed through as null values if not present.

2017-01-13 13:53 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +            'coupon_catalog': coupon_catalog,
@iivic is working with validations, he'll be of more use here.

2017-01-16 10:53 UTC, iivic requested changes
A few things:
- on coupon creation when changing number of codes field a TypeError appears in the console (edited: this is a legacy issue I will fix this bug you can ignore it.)
![screen shot 2017-01-16 at 11 47 02](https://cloud.githubusercontent.com/assets/16685686/21979982/9589dd8a-dbe1-11e6-84c4-a294c5862936.png)
- when the default value is left for the catalog another type error appears on details page 
![screen shot 2017-01-16 at 11 47 56](https://cloud.githubusercontent.com/assets/16685686/21980033/d08da6c8-dbe1-11e6-8d83-d342120ad3ff.png)
- when catalog changed it creates the coupon and displays the details page however the edit page didn't appear
![screen shot 2017-01-16 at 11 53 15](https://cloud.githubusercontent.com/assets/16685686/21980173/6a838e96-dbe2-11e6-9b75-dd9ef56889d2.png)

2017-01-16 14:05 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        this.model.set('course_catalog', ecommerce.coupons.catalogs[catalogId]);
ecommerce.coupons.catalogs will return an object. I don't see how `ecommerce.coupons.catalogs[catalogId]` fits in.

2017-01-16 14:44 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                    this.formGroup('[name=course_catalog]').removeClass(this.hiddenClass);
You should include `this.$('[name=seat_type] option').remove();` When course_id entered and switched to catalog the seat_type would remain in the field this will remove it.

2017-01-17 09:53 UTC, iivic requested changes

2017-01-17 09:53 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                except ValidationError as error:
You don't have to catch the exception here. There is a try except outside of the atomic transaction for this purpose just add the logger there.

2017-01-17 09:53 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        voucher_type=cleaned_voucher_data['voucher_type'],
You should catch the KeyError.

2017-01-17 09:53 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +            validation_message = 'A coupon with code {code} already exists.'.format(code=code)
I noticed you removed the translations from the exception messages. Is there a reason for that?

2017-01-17 09:53 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                course_catalog = course_catalog_data.get('id') if course_catalog_data.get('id') else None
I don't understand this. If course_catalog_data is empty it will not pass the if statement. Please explain and change the comment to cover what is really happening if I misunderstood.

2017-01-17 09:53 UTC, iivic commented on ecommerce/static/js/models/coupon_model.js
> +                course_catalog: '',
Why is course_catalog set by default? It makes more sense to me to set it when it's actually selected this will save you unnecessary work on the backend.

2017-01-17 09:53 UTC, iivic commented on ecommerce/static/js/models/coupon_model.js
> +                    this.set('course_catalog', this.defaults.course_catalog);
This is what I mentioned. Why is course_catalog set when catalog_type is not 'Catalog'?

2017-01-17 09:53 UTC, iivic commented on ecommerce/static/js/views/coupon_detail_view.js
> +                    courseCatalog = this.model.get('course_catalog'),
What are you expecting courseCatalog to be and why can it differ (number or something else)?

2017-01-17 09:53 UTC, iivic commented on ecommerce/static/js/views/coupon_detail_view.js
> +                if (typeof courseCatalog === 'number') {
This check is why I asked https://github.com/edx/ecommerce/pull/1093/files#r96374710. The value shouldn't differ from time to time instead it should be always the same.

2017-01-17 09:53 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                    if (catalogId !== '') {
https://github.com/edx/ecommerce/pull/1093/files#r96374710

2017-01-17 10:14 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +                except ValidationError as error:
@iivic the outside `ValidationError` exception handling is for the serializers. This is for our custom validation and its consistent with our previous code logic.

2017-01-17 10:18 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +            validation_message = 'A coupon with code {code} already exists.'.format(code=code)
We aren't displaying these messages to the user instead we are just using these for logs. There were just a few places where we used translations and all other places we didn't so for consistency I removed all translation markings. I you think we should mark these messages for translation then let me know.

2017-01-17 10:33 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                except ValidationError as error:
The outside ValidationError is used to catch model validation exceptions (and other ValidationErrors) and to handle them appropriately. It will catch this exception as well so this code is unnecessary since it does the same thing. serializers.ValidationError will return a response with status code "400 Bad Request" and the message provided.
My point is you do the same thing twice.

2017-01-17 10:39 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +            validation_message = 'A coupon with code {code} already exists.'.format(code=code)
I think you are right. Tag someone with more experience who could enlighten us what to do here.

2017-01-17 10:49 UTC, zubair-arbi commented on ecommerce/static/js/views/coupon_detail_view.js
> +                if (typeof courseCatalog === 'number') {
This id due to the fact that if there is selected value then the model will return a dict like `{id: '1', name: 'Dummy catalog'}` but if we are editing a coupon then from server we get only course catalog id `1`.

2017-01-17 10:53 UTC, zubair-arbi commented on ecommerce/static/js/views/coupon_form_view.js
> +                    this.formGroup('[name=course_catalog]').removeClass(this.hiddenClass);
added

2017-01-17 10:53 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        voucher_type=cleaned_voucher_data['voucher_type'],
Done

2017-01-17 10:53 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +            validation_message = 'A coupon with code {code} already exists.'.format(code=code)
@mjfrey can you please provide your thoughts on this?

2017-01-17 10:54 UTC, zubair-arbi commented on ecommerce/static/js/views/coupon_detail_view.js
> +                    courseCatalog = this.model.get('course_catalog'),
yes `number` and `dict` as described in my comment below

2017-01-17 11:02 UTC, zubair-arbi commented
@iivic I addressed your feedback. Please review again.

2017-01-17 11:45 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +                except ValidationError as error:
@iivic I have tried changing this but there are lots of tests failing due to this change as this way we are not returning the errors with custom code. I have tried providing error code to `serializers.ValidationError` but it gives error `TypeError: __init__() takes exactly 2 arguments (3 given)`.

2017-01-17 12:24 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                except ValidationError as error:
I just confirmed in the django rest framework source code. It looks like we are using an older version of the rest framework which doesn't support the code parameter. What you should do is replace the serializers.ValidationError outside with your code.

2017-01-17 12:53 UTC, iivic requested changes

2017-01-17 12:53 UTC, iivic commented on ecommerce/static/js/views/coupon_detail_view.js
> +                if (typeof courseCatalog === 'number') {
That makes sense but this is the coupon details page. Why is it changing on this page?

2017-01-17 12:53 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        if (typeof this.model.get('course_catalog') === 'number') {
Your comment on this matter that says it will be a number on edit page makes me conclude that this will always be the case since this is inside `if (this.editing) {`

2017-01-17 12:53 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        this.model.set('course_catalog', this.model.defaults.course_catalog);
Once again why are you setting course_catalog if the catalog_type != 'Catalog'?

2017-01-17 13:58 UTC, zubair-arbi commented on ecommerce/extensions/api/v2/views/coupons.py
> +                except ValidationError as error:
@iivic @mattdrayer I have created a separate story ENT-146 to handle further refactoring as the scope of this story is already big enough.

2017-01-17 15:13 UTC, zubair-arbi commented on ecommerce/static/js/views/coupon_detail_view.js
> +                if (typeof courseCatalog === 'number') {
@iivic I am going to update this line to check if `courseCatalog` in not empty.

2017-01-17 15:49 UTC, zubair-arbi commented
@iivic I have addressed your remaining feedback. Please review.

2017-01-18 08:51 UTC, iivic approved these changes
Good job.
Don't forget to squash the commits before merging.

2017-01-19 07:06 UTC, zubair-arbi commented
@mattdrayer I have rebased and squashed the changes. Please have a look after that I can merge it.

2017-01-19 12:16 UTC, mattdrayer commented
👍 :shipit:

2017-01-19 12:19 UTC, merged