[SOL-2194] Bug fix TypeError: seatData is undefined
openedx-unsupported/ecommerce pull request #1097
Opened 2017-01-17 15:03 UTC by iivic

Upon changing quantity field on coupon creation form console would log an error because the seatData variable is undefined and that happened because the seat_type field is not set. This bug did not interrupt our creation flow but it was annoying so I fixed it.
https://openedx.atlassian.net/browse/SOL-2194
@vkaracic @marjev

2017-01-17 15:03 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1097&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-01-17 15:10 UTC, vkaracic requested changes

2017-01-17 15:10 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> +                    view.changeTotalValue();
Add a line that asserts the model's ``catalog_type`` is indeed set to ``Single course``. Same for the unit test below, that it is not set that is.

2017-01-18 09:17 UTC, iivic commented
@vkaracic Comment addressed.

2017-01-18 09:18 UTC, vkaracic approved these changes

2017-01-18 09:47 UTC, marjev approved these changes

2017-01-18 10:04 UTC, merged