[WIP] ENT-2256
openedx-unsupported/ecommerce pull request #1101
Opened 2017-01-20 00:02 UTC by haikuginger

**Description:**

This pull request adds the ability for an ecommerce administrator to create coupon codes that are linked to a particular Enterprise Customer object.

**JIRA:** Link to JIRA ticket

**Dependencies:** Depends on [ENT-112](https://github.com/edx/edx-enterprise/pull/30); in addition, this cannot be tested effectively until changes are made to that PR to enable OAuth API integration.

**Merge deadline:** 30 January 2017

**Installation instructions:**

To do manual testing, you must have edx-enterprise from the above-linked branch installed in your LMS. In addition, if the changes there haven't been made yet, you must modify the `EnterpriseCustomerViewSet` in that PR to use the `OAuth2Authentication` class, as [here](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/course_structure_api/v0/views.py#L32) in `edx-platform`.

**Testing instructions:**

1. With the ecommerce stack and LMS running, go to http://localhost:8002/login; grant access to the ecommerce stack. You must be using a staff user or above.
2. Go to http://localhost:8002/coupons/new.
    - Note that when using a course selection mode that is not a single catalog selection, an Enterprise Customer dropdown is visible, and it shows a list of the Enterprise Customer objects installed in your LMS.
3. Create a new coupon using one of your Enterprise Customers; go to the Edit view and observe that the dropdown still shows the Enterprise Customer you chose.
    - Change the name of the EC in the LMS and refresh this page; observe that the name changes here as well.

**Reviewers:**
- [ ] @bradenmacdonald 
- [ ] edX TBD

**Author concerns:**

I discovered while implementing this that it does not appear to be possible to edit existing coupons; based on checking against master, I do not believe this regression was introduced in this code, nor did I want to spend the time to properly diagnose and fix the issue.

2017-01-20 00:03 UTC, edx-webhook commented
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1101&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-01-23 08:41 UTC, haikuginger commented
Rebased from 0d885d9.

2017-01-23 10:09 UTC, pomegranited requested changes
@haikuginger  Thanks for fixing the pylint error, and the issue I was having with Creating Coupons.  I've got one remaining issue with Editing coupons, and have left some comments, but the code itself looks good.

Would also like to see [docs/coupons.rst](https://github.com/edx/ecommerce/blob/master/docs/coupons.rst) updated to describe the change.

Also, looks like you might need to [improve your test coverage to 95% of the diff](https://codecov.io/gh/edx/ecommerce/compare/1ddc8877da886e48754f29be097cbaab291fe4bd...ff993776b8fc5085a22e15ce632157415db3a046).

- [x] I tested this using the PR description.
- [x] I read through the code.
- [x] I checked for accessibility issues - existing form, works with keyboard nav.  Standard input elements added, with labels.
- [ ] Includes documentation - some docstrings

2017-01-23 10:09 UTC, pomegranited commented on ecommerce/extensions/api/v2/views/coupons.py
> +            enterprise_customer = enterprise_customer_data['uuid'] if enterprise_customer_data else None
nit: I don't much like inline `if`/`else`'s..  Brings back perl memories.  Could this whole `try`/`except` block be wrapped in an `if enterprise_customer_data is not None:`?

2017-01-23 10:09 UTC, pomegranited commented on ecommerce/extensions/api/v2/views/coupons.py
> +                range_data['enterprise_customer'] = enterprise_customer_data['uuid'] if enterprise_customer_data else None
same nit as above re inline `if`/`else`'s.

2017-01-23 10:09 UTC, pomegranited commented on ecommerce/extensions/api/v2/views/coupons.py
> +                    range_data['enterprise_customer'] = enterprise_customer_data['id']
I don't understand why, but when I [create a new Coupon, it's using "id"](https://github.com/edx/ecommerce/pull/1101/files#diff-c9a451f0afeebe0481e4cee1c16b7c94R168), but when I save an existing one, it uses "uuid".

So attempting to save an existing Coupon with an Enterprise Customer associated now throws: 
```
  File "/edx/app/ecommerce/ecommerce/ecommerce/extensions/api/v2/views/coupons.py", line 327, in update
    self.update_range_data(request, vouchers)
  File "/edx/app/ecommerce/ecommerce/ecommerce/extensions/api/v2/views/coupons.py", line 311, in update_range_data
    raise ValidationError(validation_message, code=status.HTTP_400_BAD_REQUEST)
ValidationError: [u'Unexpected EnterpriseCustomer data format received for coupon.']
```

2017-01-23 10:09 UTC, pomegranited commented on ecommerce/extensions/api/v2/views/coupons.py
> +        coupon_catalog = cls.get_coupon_catalog(stock_record_ids, partner)
Why was this change made?  It looks unrelated to the PR.

2017-01-23 10:09 UTC, pomegranited commented on ecommerce/extensions/api/v2/views/coupons.py
> +                    range_data['enterprise_customer'] = enterprise_customer_data['id']
On the plus side, if I change the "id" here to "uuid", then the coupon saves its changes.

2017-01-23 15:18 UTC, haikuginger commented on ecommerce/extensions/api/v2/views/coupons.py
> +        coupon_catalog = cls.get_coupon_catalog(stock_record_ids, partner)
Pylint started complaining about too many clauses in the function; I decided that doing the minor refactor was better than just shutting it up with a pragma.

2017-01-23 16:53 UTC, haikuginger commented
@pomegranited, I've switched to using `id` across the board to avoid issues like this.

2017-01-23 17:45 UTC, mattdrayer commented on ecommerce/extensions/api/serializers.py
> +        return retrieve_offer(obj).condition.range.enterprise_customer
Do we need a docstring here?  Also, are there any exception conditions to consider?

2017-01-23 17:46 UTC, mattdrayer commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +                'id': 'f6e9dbcb23df4432b1c81eb53365841d'
Is there a reason for this value to be static?  Would it be better to auto-generate it?

2017-01-23 17:47 UTC, mattdrayer commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +                'id': 'f6e9dbcb23df4432b1c81eb53365841d',
This looks like a dupe of the one on L67 -- maybe we can move it into a constant and reference in both places.

2017-01-23 17:48 UTC, mattdrayer commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +                                'name': 'Starfleet Academy',
I've seen things like this imported as test/dummy data -- it might be worth exploring that approach so we can reuse in other test cases as well.

2017-01-23 19:58 UTC, pomegranited commented on ecommerce/extensions/api/v2/views/coupons.py
> +        coupon_catalog = cls.get_coupon_catalog(stock_record_ids, partner)
+1

2017-01-24 07:57 UTC, pomegranited requested changes
Nearly working now, @haikuginger !

- [ ] I tested this by:
   * *OK* Creating a new Coupon A without an Enterprise customer.
   * *OK* Editing Coupon A, and saving without an Enterprise customer.
   * *OK* Editing Coupon A, and saving with an Enterprise customer
   * *OK* Creating Coupon B with an Enterprise customer.
   * *OK* Editing Coupon B, and saving with a different Enterprise customer.
   * *FAIL* Editing Coupon B, and saving without an Enterprise customer.  Throws a ValidationError, see inline comment.
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] Includes documentation - Could you please update [docs/coupons.rst](https://github.com/edx/ecommerce/blob/master/docs/coupons.rst) to explain where the Enterprise customer choices come from?

2017-01-24 07:57 UTC, pomegranited commented on ecommerce/extensions/api/v2/views/coupons.py
> +                    range_data['enterprise_customer'] = enterprise_customer_data['id']
Only one issue remaining:  If I edit a coupon that has an Enterprise customer, and try to select empty/no Enterprise customer and save, it throws a [ValidationError at line 310](https://github.com/edx/ecommerce/pull/1101/files#diff-c9a451f0afeebe0481e4cee1c16b7c94R310), and the `enterprise_customer_data={u'name': u''}`.

This diff fixes it:
```diff
diff --git a/ecommerce/extensions/api/v2/views/coupons.py b/ecommerce/extensions/api/v2/views/coupons.py
index 3b8abe1..abfd1a5 100644
--- a/ecommerce/extensions/api/v2/views/coupons.py
+++ b/ecommerce/extensions/api/v2/views/coupons.py
@@ -302,9 +302,7 @@ class CouponViewSet(EdxOrderPlacementMixin, viewsets.ModelViewSet):
             enterprise_customer_data = request.data.get('enterprise_customer')
             try:
                 if enterprise_customer_data:
-                    range_data['enterprise_customer'] = enterprise_customer_data['id']
-                else:
-                    range_data['enterprise_customer'] = None
+                    range_data['enterprise_customer'] = enterprise_customer_data.get('id')
             except (KeyError, TypeError):
                 validation_message = 'Unexpected EnterpriseCustomer data format received for coupon.'
                 raise ValidationError(validation_message, code=status.HTTP_400_BAD_REQUEST)
```

2017-01-24 19:20 UTC, mattdrayer commented on ecommerce/coupons/tests/mixins.py
> +            enterprise_customer=enterprise_customer,
Need to add to docstring

2017-01-24 19:33 UTC, mattdrayer commented on ecommerce/static/templates/coupon_form.html
> +        <div class="form-group enterprise-customer">
Does the display of this HTML block need to be controlled with any sort of switch or conditional logic?

2017-01-24 21:41 UTC, haikuginger commented
@pomegranited, I've made that fix, along with some test fixes.

@mattdrayer, I'll go ahead and address your comments as soon as I've got signoff from @pomegranited on the existing code. :)

2017-01-25 00:06 UTC, pomegranited approved these changes
👍  @haikuginger  That change did the trick!  All my [manual tests](https://github.com/edx/ecommerce/pull/1101#pullrequestreview-18100288) are now working.

Re the documentation change, I'm happy to defer to upstream on what documentation is required.

Thanks for your patience and persistence 😄

2017-01-27 22:26 UTC, haikuginger commented on ecommerce/static/templates/coupon_form.html
> +        <div class="form-group enterprise-customer">
No; Backbone handles that for us.

2017-01-27 22:28 UTC, haikuginger commented on ecommerce/extensions/api/serializers.py
> +        return retrieve_offer(obj).condition.range.enterprise_customer
I'll stick in a pro-forma docstring, but I don't think we need to worry about exceptions. We're just traversing the DB to get a field value.

2017-01-29 18:43 UTC, haikuginger commented
@mattdrayer, rebased and comments addressed from af27276.

2017-01-30 12:10 UTC, mattdrayer commented
👍  -- ready for @mjfrey @vkaracic @iivic @marjev to take a look

2017-01-30 13:27 UTC, marjev approved these changes
Mostly nitpick comments, but overall LGTM

2017-01-30 13:27 UTC, marjev commented on ecommerce/coupons/tests/mixins.py
> +            enterprise_customer (str): Hex-encoded UUID for an Enterprise Customer object from the Enterprise app.
nitpick: alphabetize.
Mostly because there are a lot optional parameters and by using alphabet, we increase readability of this doc string. This is not a showstopper, but if you're going to commit other changes, this is something you might want to change as well.

2017-01-30 13:27 UTC, marjev commented on ecommerce/extensions/api/serializers.py
> +    enterprise_customer = serializers.SerializerMethodField()
Renaming this to `enterprise_customer_uuid` would remove the need for a doc string in the `get_enterprise_customer` below. Name of the Django REST Framework serializer `get` method should be self-descriptive. That's why most of those methods (perhaps all of them) don't contain a doc string.

2017-01-30 13:27 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        request.COOKIES = {}
It looks like this is reused in a couple of places, perhaps more.
Could you refactor this into a separate method that returns the request? Request can be updated with data in the test method, but `user`, `site` and `COOKIES` seems to be initialized to the same values each time.

2017-01-30 13:27 UTC, marjev commented on ecommerce/static/js/test/mock_data/enterprise_customers.js
> +});
please add an empty line at the end of the file.

2017-01-30 15:57 UTC, haikuginger commented on ecommerce/coupons/tests/mixins.py
> +            enterprise_customer (str): Hex-encoded UUID for an Enterprise Customer object from the Enterprise app.
Will do!

2017-01-30 16:09 UTC, haikuginger commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        request.COOKIES = {}
Sure!

2017-01-30 16:10 UTC, haikuginger commented on ecommerce/static/js/test/mock_data/enterprise_customers.js
> +});
You got it!

2017-01-30 16:10 UTC, haikuginger commented on ecommerce/extensions/api/serializers.py
> +    enterprise_customer = serializers.SerializerMethodField()
So, for this one I'd rather keep it as-is; Backbone converts the value to an object, and then we post an object back. Is that OK?

2017-01-30 16:16 UTC, haikuginger commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        request.COOKIES = {}
Heh, this comment seems to have attached itself to the new build_request method.

2017-01-30 16:16 UTC, haikuginger commented
@marjev, changes have been made. @mattdrayer, who else do we need to review?

2017-01-30 16:43 UTC, mattdrayer commented
@mjfrey are you able to take a pass through this PR?

2017-01-31 18:38 UTC, bradenmacdonald commented
@haikuginger A request from @griffresch: Please don't merge this PR (or at least don't deploy to prod) until How To docs are ready for other teams and Griff has given the go-ahead.

2017-02-06 23:20 UTC, bdero commented
I rebased this PR as Jessie's away for a few days and https://github.com/edx/ecommerce/pull/1127 is based on it.

@griffresch @mattdrayer VersionEye is showing a failure for a dependency that doesn't have a version, but that appears to not be an issue introduced by this PR. Is this expected and OK to ignore, or is this a previously unknown issue?

2017-02-07 01:35 UTC, bdero commented
@bradenmacdonald For the docs, should I just add the necessary changes to this section in the ecommerce docs (https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/ecommerce/create_products/create_coupons.html#create-a-coupon) to mention the new Enterprise Customer selection?

Or, should I write up a separate guide for creating a coupon linked to an Enterprise Customer?

2017-02-07 04:10 UTC, bradenmacdonald commented
@bdero I asked on the ticket; not sure.

2017-02-07 04:24 UTC, bdero commented
Thanks @bradenmacdonald

2017-02-07 07:03 UTC, marjev commented on ecommerce/extensions/api/serializers.py
> +    enterprise_customer = serializers.SerializerMethodField()
yeah, makes sense. I didn't notice that. Sorry for the late response.

2017-02-07 22:59 UTC, bdero commented
Rebased again and squashed. Original branch is preserved as `open-craft:haikuginger/add-enterprise-customer-to-coupon-bak`.

2017-02-07 23:07 UTC, bdero commented
The VersionEye failure was introduced by #1056 and context can be found here: https://github.com/edx/ecommerce/pull/1056#issuecomment-273783118

So I think it's expected and being ignored in all PRs right now.

2017-02-09 22:38 UTC, bdero commented
Rebased again.

2017-02-13 16:16 UTC, bdero commented
Rebased again.

2017-02-13 19:53 UTC, bradenmacdonald commented
@bdero Since this PR involves a UI change, could you please add a screenshot?

2017-02-13 20:25 UTC, bdero commented
@bradenmacdonald Screenshot added!

2017-02-13 21:58 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if stock_record_ids:
@haikuginger can you flip this around to a guard?   `if not stock_record_ids:  return None`

2017-02-13 21:58 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if range_data:
@haikuginger can you flip this around to a guard?  `if not range_data:  return None`

2017-02-13 23:19 UTC, bdero commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if stock_record_ids:
Done, thanks.

2017-02-13 23:19 UTC, bdero commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if range_data:
Done, thanks.

2017-02-13 23:22 UTC, bdero commented
Looks like @griffresch gave the go-ahead ENT ticket. Do you think all is well for me to merge this once tests pass @mattdrayer ?

2017-02-13 23:43 UTC, bdero commented
Rebased and tests are passing - all comments addressed @mattdrayer!

2017-02-14 01:36 UTC, mattdrayer commented
Nice -- we have a 👍 from @marjev on this and I'll give my second 👍 after going thru it again 😉 -- I think we are in good shape to merge at this point!

2017-02-14 01:45 UTC, bdero commented
> I'll give my second :+1: after going thru it again :wink:

@mattdrayer Great! Just to be clear, will you be taking another review pass? :)

2017-02-14 01:52 UTC, mattdrayer commented
ah, sorry, I was trying to be funny because I realized I had already given a 👍 15 days ago -- I am D.O.N.E.  😃

2017-02-14 02:29 UTC, bdero commented
@mattdrayer Ah ok, thanks! :) Merging now.

2017-02-14 02:30 UTC, merged