WIP automated entitlemetns applying for the enterprise learners
openedx-unsupported/ecommerce pull request #1104
Opened 2017-01-23 11:00 UTC by zubair-arbi

ENT-121
@asadiqbal08 @saleem-latif @mattdrayer 

Automatically find and apply active entitlements (coupons) on the order basket, for an enterprise learner.

**Q. How to activate this feature?**
**A.** Add active waffle switch with name `enable_enterprise_on_runtime`  to enable this feature

_**NOTE:** This is an WIP PR and it contains dummy response in the file `ecommerce/enterprise/tmp/enterprise-learner.json ` from the enterprise service (currently hosted by LMS env) API `enterprise/api/v1/enterprise-customer-user/` and will be removed once the main functionality is completed. Also this code is written with the assumption that for now every enterprise will have only one entitlement/voucher._

**Related PR for enterprise API (In-progress):** https://github.com/edx/edx-enterprise/pull/30

**TODO:** Add a related PR in edx configuration repo for overriding the production value for the setting `ENTERPRISE_API_URL`

2017-01-23 16:35 UTC, mattdrayer commented on ecommerce/enterprise/__init__.py
> +
We'll need to add some documentation here describing the package.

2017-01-23 16:36 UTC, mattdrayer commented on ecommerce/core/models.py
> +        Returns an API client to access the Enterprise service.
This line is redundant, so we should revise to something more explanatory -- perhaps describe the intended use, how to create a client, any gotchas to watch out for, exception conditions, etc.

2017-01-23 16:41 UTC, mattdrayer commented on ecommerce/enterprise/tmp/__init__.py
> +
Hmm, after looking at this directory...it's sort of a weird sub-package -- is there a better name to use versus `tmp`?  Can it be entirely eliminated?  If it *must* remain, we'll need to be very clear with our documentation about its intended purpose/use.

2017-01-23 16:42 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    # TODO: Handle multiple entitlements/vouchers for an enterprise WRT some criterion
Will this TODO be addressed in this PR?  If not, I recommend logging a ticket versus keeping track of future development work in the code.

2017-01-23 16:42 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    # TODO: Cache the response from enterprise API in case of 200 status
Will this TODO be addressed in this PR? If not, I recommend logging a ticket versus keeping track of future development work in the code.

2017-01-23 16:44 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +Helper methods for enterprise entitlements.
This line doesn't really explain the purpose of this module to an edx/ecommerce project developer.  What is an "enterprise entitlement"?  How do I use it?

2017-01-23 16:50 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +            vouchers.append(voucher)
It looks like this line should be relocated to below the `try/except`, because it's not the actual work requiring protection.  We could add a `continue` to the `except` in order to skip to the next iteration in the case of a failure. and perform the append after we have ascertained the `Voucher` call was successful.

2017-01-23 16:52 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    except:  # pylint: disable=bare-except
Is it not feasible to be explicit about the possible exceptions here?

2017-01-23 16:53 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    try:
I think it would be useful to describe the expected structure of the enterprise_learner_data in a code comment here.

2017-01-23 16:55 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +@utils.dummy_data("enterprise_api_response_for_learner")
I guess I'm not really understanding the whole `tmp/utils` thing that is going on here.  Is this a supporting mechanism for the test framework?  It seems like there should be a more straightforward way of accomplishing what is needed.

2017-01-23 16:56 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    Fetch data related to enterprise learners.
What data?  What does it look like?  What is the failure mode?  All good information to include.

2017-01-23 16:57 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    response = site.siteconfiguration.enterprise_api_client.enterprise-learner(learner.username).get()
It feels like we should have a `try/except` here, or at least a gate on the `learner` object

2017-01-23 17:58 UTC, mattdrayer commented on ecommerce/enterprise/tmp/utils.py
> +def dummy_data(key):
I know that this is a decorator based on my code review, and the style/layout of the function, but I still think a code comment or docstring would be good to have here.

2017-01-24 07:40 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +@utils.dummy_data("enterprise_api_response_for_learner")
@mattdrayer This `tmp\utils` code is just for temporary purpose. I will remove it once I have the functionality working.

2017-01-24 07:53 UTC, zubair-arbi commented on ecommerce/enterprise/tmp/__init__.py
> +
@mattdrayer don't worry, this will be entirely eliminated :)

2017-01-24 08:08 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +    try:
@mattdrayer I have added this as an output from the method `get_enterprise_learner_data` as it makes more sense to put it there.

2017-01-24 08:09 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +    # TODO: Handle multiple entitlements/vouchers for an enterprise WRT some criterion
@mattdrayer I have added a ticket https://openedx.atlassian.net/browse/ENT-159 for this TODO.

2017-01-24 10:49 UTC, saleem-latif commented on ecommerce/coupons/utils.py
> +def get_all_range_catalog_query_results(site, query):
nit: wouldn't it be better to have a name something like `get_catalog_course_runs`

2017-01-24 10:57 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +            logger.warning(
It would be better to use `logger.exception` as it will also log error trace

2017-01-24 10:58 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +        enterprise_learner_data = get_enterprise_learner_data(site, learner)['results']
Please handle `KeyError` here

2017-01-24 11:00 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +    entitlements = enterprise_learner_data[0]['enterprise_customer']['entitlements']
Add `KeyError` exception handling.

2017-01-24 11:02 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +        response = site.siteconfiguration.enterprise_api_client.enterprise-learner(learner.username).get()
Add network error handling for this API call.

2017-01-24 11:08 UTC, asadiqbal08 commented on ecommerce/enterprise/__init__.py
> +communication with the Enterprise Service.
can you make it better? specially `... and communication with the Enterprise Service.`

2017-01-24 11:10 UTC, saleem-latif commented on ecommerce/extensions/basket/views.py
> +        if voucher is None:
Can we update it to something like this.
```
if voucher is None:
    voucher  = get_entitlement_voucher(request, product)
```

2017-01-24 11:15 UTC, asadiqbal08 commented on ecommerce/enterprise/utils.py
> +        return True
make it simple `return waffle.switch_is_active(settings.ENABLE_ENTERPRISE_ON_RUNTIME_SWITCH)`

2017-01-24 11:35 UTC, saleem-latif commented on ecommerce/coupons/utils.py
> +    cache_key = hashlib.md5(cache_key).hexdigest()
I think you forgot to import `hashlib` and `cache`, I am getting this error
```
  File "/edx/app/ecommerce/ecommerce/ecommerce/extensions/basket/views.py", line 58, in get
    enterprise_voucher = get_entitlement_voucher(request, product)
  File "/edx/app/ecommerce/ecommerce/ecommerce/enterprise/entitlements.py", line 43, in get_entitlement_voucher
    vouchers = get_vouchers_for_learner(request.site, request.user)
  File "/edx/app/ecommerce/ecommerce/ecommerce/enterprise/entitlements.py", line 59, in get_vouchers_for_learner
    entitlements = get_entitlements_for_learner(site, learner)
  File "/edx/app/ecommerce/ecommerce/ecommerce/enterprise/entitlements.py", line 87, in get_entitlements_for_learner
    enterprise_learner_data = get_enterprise_learner_data(site, learner)['results']
  File "/edx/app/ecommerce/ecommerce/ecommerce/enterprise/entitlements.py", line 176, in get_enterprise_learner_data
    cache_key = hashlib.md5(cache_key).hexdigest()
NameError: global name 'hashlib' is not defined
```

2017-01-24 11:40 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +def get_available_voucher_for_product(request, product, vouchers):
there should be 2 blank lines between module level functions

2017-01-24 11:40 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +def get_course_ids_from_voucher(site, voucher):
2 blank line instead of 1, other functions in the module also need to be fixed.

2017-01-24 11:43 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +    cache_key = hashlib.md5(cache_key).hexdigest()
Thanks for pointing this out.

2017-01-24 11:55 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +        response = site.siteconfiguration.enterprise_api_client.enterprise-learner(learner.username).get()
This is the desired flow. This method will raise exceptions and these exception will be handled in the method `get_entitlements_for_learner` where we are calling this method.

2017-01-24 12:37 UTC, zubair-arbi commented on ecommerce/extensions/basket/views.py
> +        if voucher is None:
updated

2017-01-24 12:57 UTC, zubair-arbi commented
@mattdrayer @iivic @mjfrey This PR is ready for review. I will start adding unittests by tomorrow. You cannot run it on local machine as it depends on an Enterprise API endpoint which is in progress.

2017-01-24 18:59 UTC, mattdrayer commented on ecommerce/core/models.py
> +        Returns an Slumber based REST API client for the provided site.
"Returns a Slumber-based..."

2017-01-24 19:00 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    Get all catalogs on the basis of provided query from the Course Catalog
Are we getting catalogs or course runs?

2017-01-24 19:01 UTC, mattdrayer commented on ecommerce/core/models.py
> +        Returns an Slumber based REST API client for the provided site.
Actually instead of "Returns" here you might say "Constructs"

2017-01-24 19:03 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    cache_key = '{}_{}_{}_{}.api.data'.format(site.domain, partner_code, resource, query)
This cache key format follows a similar pattern to other cache keys found in Otto, yes?

2017-01-24 19:06 UTC, mattdrayer commented on ecommerce/enterprise/__init__.py
> +Client app for or containing all enterprise related functionality and
This sentence needs to be revised -- how about something like:

"This package contains all workflows and communications related to the Open edX Enterprise service.

2017-01-24 19:07 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +enterprise entitlements are provided by the Enterprise Service on the bases
bases -> basis (of)

2017-01-24 19:16 UTC, mattdrayer commented
This is looking good so far, @zubair-arbi -- just a couple small nits from me at this point since you've already addressed the big things from my earlier review -- 👍 from my side.  @mjfrey @iivic @vkaracic if one of you guys can take a pass through this PR as well that would be great.

2017-01-24 19:17 UTC, mattdrayer commented
FYI, the PR for the Enterprise service API is https://github.com/edx/edx-enterprise/pull/30

2017-01-25 10:27 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +    cache_key = '{}_{}_{}_{}.api.data'.format(site.domain, partner_code, resource, query)
correct, I rearranged the key structure a bit for better readability and their precedence, e.g. putting site domain at start of key for site base uniqueness.

2017-01-25 10:28 UTC, zubair-arbi commented on ecommerce/enterprise/__init__.py
> +Client app for or containing all enterprise related functionality and
Sounds good

2017-01-25 10:49 UTC, asadiqbal08 commented on ecommerce/enterprise/entitlements.py
> +        return None
`logger.info(` here ? `enterprise feature is not enabled`

2017-01-26 10:25 UTC, asadiqbal08 commented on ecommerce/enterprise/entitlements.py
> +                "count": 1,
is the api always return count 1 ?

2017-01-26 10:25 UTC, asadiqbal08 commented on ecommerce/enterprise/entitlements.py
> +    if len(enterprise_learner_data) == 0:
`if not enterprise_learner_data:`

2017-01-26 10:40 UTC, asadiqbal08 commented on ecommerce/enterprise/entitlements.py
> +            coupon_product = Product.objects.filter(product_class__name='Coupon').get(id=entitlement['entitlement_id'])
can you add a comment line that indicate the structure of coupon_product after executing the query ?

2017-01-26 10:42 UTC, asadiqbal08 commented on ecommerce/enterprise/entitlements.py
> +    provided learner.
kindly add the vouchers structure that is going to be returned.

2017-01-26 12:02 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +        return None
Since this feature is enabled explicitly by a waffle switch I don't think it will help much in production.

2017-01-26 12:17 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +            coupon_product = Product.objects.filter(product_class__name='Coupon').get(id=entitlement['entitlement_id'])
@asadiqbal08 Clean code suggests to avoid comments as much as possible and use expressive names for readability, since here we can check the model for fields so its unnecessary to explicitly add Product class structure here. The basic reason for this is that code is ever evolving and being refactored by the developers but this is not true for the comments specifically if they are representing the data structure. If the related class/model is changed then there will be no error to change the class/model structure in the comments and it would miss guide the new developer.

2017-01-26 12:18 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +                "count": 1,
Yes, In case the learner is affiliated with an enterprise.

2017-01-26 12:23 UTC, asadiqbal08 commented on ecommerce/enterprise/entitlements.py
> +            coupon_product = Product.objects.filter(product_class__name='Coupon').get(id=entitlement['entitlement_id'])
I was not saying to add the whole Product class structure here :)

2017-01-26 12:53 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +    provided learner.
@asadiqbal08 I have add `Returns` statement.

2017-01-26 12:56 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +            coupon_product = Product.objects.filter(product_class__name='Coupon').get(id=entitlement['entitlement_id'])
@asadiqbal08 I am sorry if I miss understood. If you were referring to the entitlement structure then I have added a complete response structure of enterprise learner API response in the method `get_enterprise_learner_data` and I think I will be a duplicate to add a portion of that structure here again.

2017-01-26 12:59 UTC, zubair-arbi commented
@asadiqbal08 I have addressed you feedback.
@mattdrayer @saleem-latif @mjfrey @iivic I have added unittests too. Please review.

2017-01-26 17:30 UTC, mattdrayer commented
I'm good with the changes -- 👍 -- @mjfrey @iivic @vkaracic @marjev please jump in when available.

2017-01-26 21:03 UTC, mjfrey requested changes
quick first pass.  Seems that we can re-use a bunch of logic we already have regarding Voucher / catalog lookup.

2017-01-26 21:03 UTC, mjfrey commented on ecommerce/coupons/tests/mixins.py
> +    def mock_get_catalog_course_runs_api(self, course_run, query, partner_code):
we should just augment mock_dynamic_catalog_single_course_runs_api rather than adding a new mock.

2017-01-26 21:03 UTC, mjfrey commented on ecommerce/coupons/utils.py
> +def get_catalog_course_runs(site, query):
why this new method? We already have get_range_catalog_query_results

2017-01-26 21:03 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +def get_available_voucher_for_product(request, product, vouchers):
there is already get_voucher_and_products_from_code that does basically what you are trying to do here.  If it does not do exactly what you want -- we should update it.

2017-01-27 07:52 UTC, marjev requested changes

2017-01-27 07:52 UTC, marjev commented on ecommerce/enterprise/entitlements.py
> +        learner: (django.contrib.auth.User) django auth user
nitpick: I think `User` will suffice, mostly for consistency because I think we used only `User` in other docstrings. 
Same think with the `Site`.

2017-01-27 07:52 UTC, marjev commented on ecommerce/enterprise/entitlements.py
> +            coupon_product = Product.objects.filter(product_class__name='Coupon').get(id=entitlement['entitlement_id'])
Can we optimize this by doing the following:
```
entitlement_ids = [entitlement['entitlement_id'] for entitlement in entitlements]
coupon_products = Product.objects.filter(product_class__name='Coupon').filter(id__in=entitlement_ids)
```

This way, only a single query is made to the database. You get a set of coupon_products in a single call. Use a loop to iterate over the results. No need to exception handling either, just check to see if the result set is empty or not.

2017-01-27 07:52 UTC, marjev commented on ecommerce/enterprise/entitlements.py
> +        response = endpoint().get(**querystring)
If think you should handle API exceptions here and not in the place where you call `get_enterprise_learner_data()`.
The reasons why I say this are:
1. If this is ever reused, it would require another set of exception handling. It's basically duplicating code. Someone can, also, forget to add exception handling, as well, which means this method would not handle the exception it caused.
2. This is open-source code, so we should either handle the exceptions our code stumbles upon or document in docstring that we're raising/passing an exception.

I'm suggesting moving the exception handling from https://github.com/edx/ecommerce/pull/1104/files#diff-50449a66b32057163f5619acfe7bc17eR94 to this line, since this line might cause an exception to be raised.

2017-01-27 07:52 UTC, marjev commented on ecommerce/coupons/utils.py
> +        response = endpoint().get(
If this method is not removed, as suggested by Michael in a comment above, you should handle API exceptions this might raise.

2017-01-27 07:52 UTC, marjev commented on ecommerce/enterprise/entitlements.py
> +"""
@zubair-arbi @mjfrey There are a lot of methods in this file that do something when a voucher is sent as an argument.

I'm wondering if we should move those to voucher utils or Voucher model. Subjectively, I would never think of looking for such methods in this file, or even this app (`enterprise`). I would expect something like that to be within the `voucher` app.

Let me know what are your thoughts on this matter.

2017-01-27 10:09 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +def get_catalog_course_runs(site, query):
@mjfrey  the main difference is that this method gets all catalog course runs by recursively retrieving the results. I will see if I can refactor the the method `get_range_catalog_query_results` to include this functionality.

2017-01-27 11:21 UTC, zubair-arbi commented on ecommerce/coupons/tests/mixins.py
> +    def mock_get_catalog_course_runs_api(self, course_run, query, partner_code):
Since I need to mock the course_runs api so I will use the mock `mock_dynamic_catalog_course_runs_api`

2017-01-27 15:21 UTC, zubair-arbi commented on ecommerce/coupons/utils.py
> +def get_catalog_course_runs(site, query, limit=None, offset=None):
@mjfreyn @marjev I have refactored the method `get_range_catalog_query_results` into `get_catalog_course_runs` to incorporate the needs for existing usage and for enterprise usage. Please review that if this is what you were suggesting.

2017-01-27 15:37 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +"""
@mjfrey @marjev @mattdrayer these method are kept separate since we wanted to isolate the enterprise logic to the existing flow. Please note that the enterprise service returns the coupon product id (`entitlement_id`), from that we fetch the coupon product then we check if the course in the user basket exists in the coupon voucher range and if that's the case we just return the first active voucher code which is automatically applied for the enterprise learners.

2017-01-30 07:48 UTC, marjev commented on ecommerce/coupons/utils.py
> +def get_catalog_course_runs(site, query, limit=None, offset=None):
LGTM

2017-01-30 07:51 UTC, marjev commented on ecommerce/enterprise/entitlements.py
> +"""
Ok, sounds reasonable enough.

2017-01-30 07:54 UTC, marjev approved these changes
LGTM

2017-01-30 12:58 UTC, mjfrey requested changes

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +            return []
Why return an empty list?  We should return None.

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +            return []
Same here

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +            return []
and here.

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +            return []
We should return None if no Vouchers where found.

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +    entitlement_voucher = get_available_voucher_for_product(request, product, vouchers)
you should check if you have any vouchers before calling this.  Why call this if you have no vouchers.

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +        return []
None

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +        return []
None

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +        return []
None

2017-01-30 12:58 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +        return None
you return None here but empty set below.  Always return None if nothing is found.

2017-01-30 13:45 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +        return None
@mjfrey thanks for pointing this out.

2017-01-30 13:46 UTC, zubair-arbi commented
@mjfrey  I have addressed your feedback. Please take another look.

2017-01-30 13:57 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +    return vouchers
What happens if there are no entitlements?  Do we return []?

2017-01-30 14:01 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +    return vouchers
@mjfrey yes.

2017-01-30 14:08 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +    return vouchers
it should be None right?

2017-01-30 14:12 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +    return vouchers
I think it will be redundant to check if vouchers list is empty then return None, since we are populating the vouchers list on runtime so it makes sense if the response is empty list.

2017-01-31 10:50 UTC, zubair-arbi commented
@mjfrey can you please give a final review?

2017-01-31 21:43 UTC, mjfrey approved these changes

2017-02-02 07:37 UTC, saleem-latif commented
👍 once all checks are passing

2017-02-02 07:57 UTC, zubair-arbi commented
Ignoring the VersionEye failure.
```
 punycode 	1.4.1 	2.1.0 	UNKNOWN 	0 
```

2017-02-02 07:57 UTC, merged