[SOL-2174] Add backend Validation for Max Uses
openedx-unsupported/ecommerce pull request #1106
Opened 2017-01-24 11:34 UTC by iivic

@mjfrey @vkaracic @marjev 
The max uses field can't be set for Single use vouchers and must be a number greater than 0. The validation is done for create and update. I couldn't do the validation inside the model so review with this in mind and feel free to suggest a better solution.

2017-01-24 11:34 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1106&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-01-25 13:45 UTC, marjev approved these changes

2017-01-25 13:45 UTC, marjev commented on ecommerce/coupons/tests/test_utils.py
> +        self.assertEqual(returned_value, expected_result)
why not
```
self.assertEqual(prepare_course_seat_types(course_seat_types), excepted_result)
```

2017-01-26 07:49 UTC, vkaracic requested changes

2017-01-26 07:49 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(response['max_uses'], updated_max_uses)
You don't need a new variable here. Just use ``self.data['max_uses']``

2017-01-26 07:49 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +    def test_creating_coupon_with_max_uses_and_single_use_set(self):
``test_create_single_use_coupon_with_max_uses``

2017-01-26 07:49 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(details['voucher_type'], Voucher.SINGLE_USE)
If possible, could you try and combine these lines into a general helper function, since mostly the same thing is done on line 804-7 and 905-9?

2017-01-26 07:49 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(response_data.status_code, status.HTTP_200_OK)
``assert_post_response_status()``?

2017-01-26 07:49 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +    def test_creating_coupon_with_max_uses_and_single_use_set(self):
Maybe even change the rest of the test names accordingly.

2017-01-26 07:49 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                        'Max_global_applications field cannot be set for voucher type [{voucher_type}].'.format(
Lowercase _m_.

2017-01-26 07:49 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
> +        try:
``elif isinstance(max_uses, int)``

2017-01-26 07:49 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
> +                'Failed to create Voucher. Max_uses field cannot be set for voucher type [{voucher_type}].'.format(
Lowercase _M_ again, grammar does not apply to variable names.

2017-01-26 08:56 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(details['voucher_type'], Voucher.SINGLE_USE)
There already is one `get_response_json` I just didn't use it.

2017-01-26 09:15 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
> +        try:
This will not work for us because our frontend will always send the max_uses as a string.

2017-01-26 12:15 UTC, iivic commented on ecommerce/coupons/tests/test_utils.py
> +
comment

2017-01-30 08:58 UTC, iivic commented
@vkaracic Review once more..

2017-01-30 09:14 UTC, vkaracic approved these changes

2017-02-02 09:04 UTC, merged