Basket checkbox for enrollment codes.
openedx-unsupported/ecommerce pull request #1114
Opened 2017-01-31 08:14 UTC by vkaracic

![out](https://cloud.githubusercontent.com/assets/2808092/22456775/d3d5e584-e794-11e6-8af5-1d7a770e1c83.gif)

Locally this works as expected for me, but I still would like to try it out on a WL site. @douglashall and/or @mattdrayer do you have any WL sandbox on which this can be tested out?

https://openedx.atlassian.net/browse/SOL-2176

2017-01-31 08:14 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1114"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-02-09 11:07 UTC, vkaracic commented
@douglashall @mattdrayer this is ready for review. Since it concerns enrollment codes I'd like you or someone from your team's to review this, please.

2017-02-09 20:53 UTC, douglashall commented
@mjfrey and team should be able to handle the code review for you.

Please also reach out to Janaky and Liz Cohen for final approval of the UX. Thanks!

2017-02-09 21:35 UTC, lizcohen commented
UX looks good 👍

2017-02-10 07:59 UTC, marjev requested changes

2017-02-10 07:59 UTC, marjev commented on ecommerce/extensions/basket/tests/test_utils.py
> +    def prepare_seat_with_enrollment_code(self):
nitpick: perhaps moving this between setup and test methods would be better.

Having all test classes have the following format would increase readability:
```
TestClass
    # override methods
    # utility methods
    # test methods
```

2017-02-10 07:59 UTC, marjev commented on ecommerce/extensions/basket/tests/test_utils.py
> +        """Helper function for creating a seat with an enrollment code."""
Should this docstring also contain information about return values?

2017-02-10 07:59 UTC, marjev commented on ecommerce/extensions/basket/tests/test_views.py
> +    def prepare_course_seat_and_enrollment_code(self):
This looks really similar to a method also available in this PR. Perhaps it's time to consider using a mixin.

2017-02-10 07:59 UTC, marjev commented on ecommerce/extensions/basket/utils.py
> +    else:
you don't need `else`

2017-02-10 07:59 UTC, marjev commented on ecommerce/extensions/basket/utils.py
> +        course = Course.objects.get(id=seat.attr.course_key)
what if `Course` object doesn't exist? Should we return None in that case?

2017-02-10 07:59 UTC, marjev commented on ecommerce/extensions/basket/utils.py
> +    course = Course.objects.get(id=enrollment_code.attr.course_key)
same question as in line 189.

2017-02-10 07:59 UTC, marjev commented on ecommerce/extensions/basket/views.py
> +            if line.product.get_product_class().name == SEAT_PRODUCT_CLASS_NAME and add_enrollment_code:
We could DRY this `line.product.get_product_class().name == SEAT_PRODUCT_CLASS_NAME` by implementing a property in Product class named `is_seat_product`. Similar thing might be done on other places that do similar thing.

So, Product can have properties for each product type. That will shorten lines like this. This line, for example, would be shortened to `if line.product.is_seat_product and add_enrollment_code`.

2017-02-10 07:59 UTC, marjev commented on ecommerce/extensions/basket/views.py
> +            elif line.product.get_product_class().name == ENROLLMENT_CODE_PRODUCT_CLASS_NAME and \
same comment as in line 329.

2017-02-10 08:50 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_utils.py
> +    def prepare_seat_with_enrollment_code(self):
I am for keeping placements uniform throughout the codebase, but I'm more for [keeping case and effect close together](https://testing.googleblog.com/2017/01/testing-on-toilet-keep-cause-and-effect.html).

2017-02-10 09:22 UTC, vkaracic commented on ecommerce/extensions/basket/utils.py
> +        course = Course.objects.get(id=seat.attr.course_key)
Honestly if a seat does not have a course tied to it I'd much rather have the ``DoesNotExist`` exception raised here. Although I believe in that case it would never get to this point, an exception would be raised somewhere before since this would be a major database defect.

2017-02-10 09:49 UTC, vkaracic commented
@marjev comments addressed.

2017-02-10 11:02 UTC, marjev commented on ecommerce/extensions/basket/views.py
> +                ) else False,
You don't need if-else. `get_enrollment_code(self.request.site.siteconfiguration, product)` is enough.

2017-02-10 11:03 UTC, marjev approved these changes
Other than one additional comment, LGTM!

2017-02-10 11:47 UTC, iivic approved these changes
Everything is alphabetized 👍

2017-02-21 09:54 UTC, vkaracic commented
Closing this because we don't want the checkbox anymore.

2017-02-21 09:54 UTC, closed without merging