WIP: Update offer's Range model to use course catalog query for applying e…
openedx-unsupported/ecommerce pull request #1123
Opened 2017-02-02 11:57 UTC by zubair-arbi

…nterprise coupon

ENT-169
@asadiqbal08 @saleem-latif

2017-02-06 13:39 UTC, saleem-latif requested changes

2017-02-06 13:39 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +        logger.error('Invalid structure for enterprise learner API response for the learner [%s]', user.username)
@zubair-arbi This exception handling seems to be covering the case when API got updated and this code did not, in those scenarios we would like to let the error propagate instead of suppressing it. So, I think it would be better to raise the exception here after logging it using `logger.exception`

2017-02-06 13:39 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +def is_product_in_enterprise_courses(site, product, enterprise_catalog_id):
Since, we only want to check if given course is present in the given course catalog, I think it would be better to abstract away some details here. e.g. we can abstract away terms like `product` and `enterprise` from this method. If we could divide it into smaller functions into something like
```
catalog = fetch_catalog_courses(site, catalog_id)
def is_course_in_catalog(site, course_id, catalog)
```

2017-02-06 13:39 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +    except (ConnectionError, SlumberBaseException, Timeout, KeyError):
Again we would not want to suppress exceptions like `KeyError` that hide API changes.

2017-02-06 13:39 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +    def run_catalog_query(self, product, query=None):
I think we can abstract `product` here also and directly pass in `course_id`

2017-02-06 13:39 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +            return ((response['course_runs'][product.course_id]) or
I think `response['course_runs'][product.course_id]` would raise a `KeyError` instead of running False if `product.course_id ` is not present in response.

2017-02-06 13:39 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +def get_product_entitlements_for_learner(site, user, product):
I think it would be better if we can change `product` to `course_id` as entitlement flow depends on course id and not product.

2017-02-07 07:11 UTC, zubair-arbi commented on ecommerce/extensions/offer/models.py
> +            return ((response['course_runs'][product.course_id]) or
@saleem-latif this is the desired behavior and its consistent with our dynamic range `self.catalog_query and self.course_seat_types`. The response is expected to be like:
```javascript
{u'course_runs': {u'course-v1:test-org+course+TZAzXRxXaIdA': True}}
```

2017-02-07 07:29 UTC, zubair-arbi commented on ecommerce/extensions/offer/models.py
> +    def run_catalog_query(self, product, query=None):
@saleem-latif I think we should avoid changes the existing naming convention for coupons as we have to update/add the related tests for validation.

2017-02-07 07:39 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +        logger.error('Invalid structure for enterprise learner API response for the learner [%s]', user.username)
@saleem-latif since we are stubbing the existing basket checkout flow with the enterprise entitlements logic so it would make sense to log the exceptions instead of raising it to avoid basket page crash. I think the entitlements error handling should be contained in the enterprise app. Also we can create custom entitlements alerts on `Splunk` if we think this logging might get missed.

2017-02-07 08:12 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +def get_product_entitlements_for_learner(site, user, product):
I will update the methods/tests for `course_id`

2017-02-07 12:21 UTC, zubair-arbi commented
@saleem-latif I have addressed your feedback.
@mattdrayer Please review.

2017-02-07 13:33 UTC, zubair-arbi commented
@iivic @mjfrey I would appreciate if one of you review the changes.

2017-02-08 09:36 UTC, saleem-latif commented
@zubair-arbi overall code looks good to me, can you create a sandbox with these changes and share testing details ?

2017-02-08 11:05 UTC, zubair-arbi commented
@saleem-latif here is the sandbox with current changes: https://zubair-arbi.sandbox.edx.org/

2017-02-08 13:20 UTC, iivic approved these changes
LGTM

2017-02-09 04:54 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
>          product (Product): A product that has course_key as attribute (seat or
`course_key` or `course_id`?  I see `course_id` being referenced below?

2017-02-09 04:55 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    course_id = product.course_id
Nit: I think you can avoid this particular initialization -- it appears to be referenced only once in this function, and we're not doing any sort of validation or guarding prior to its use.

2017-02-09 04:56 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    return entitlement_voucher
Is there any sort of protection or validation we need to consider for this workflow prior to the return?

2017-02-09 05:15 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +            voucher_offer = voucher.offers.first()
Will there always be offers available?

2017-02-09 05:16 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +            offer_range = voucher_offer.condition.range
Will there always be `condition` and/or `range` attributes?

2017-02-09 05:17 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +            if offer_range.contains_product(product):
is it okay for this function to terminate without a catch-all `return` at the end?

2017-02-09 05:18 UTC, mattdrayer commented on ecommerce/extensions/offer/models.py
> +            query = self.catalog_query
Do we need to verify that a catalog_query attribute is available and/or has a value?

2017-02-09 10:28 UTC, saleem-latif approved these changes

2017-02-09 12:14 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +    return entitlement_voucher
@mattdrayer we are already verifying the vouchers in the method `get_course_vouchers_for_learner` and `get_available_voucher_for_product`. We only return the valid and active voucher or `None` in case no vocher is found. 

**These validations include:**
1. Enterprise feature is enabled
2. User is enterprise learner
3. Basket course is available for enterprise catalog
4. Enterprise has entitlements
5. Get active vouchers for the enterprise
6. Return only voucher which has the basket course

Please let me know if I have missed something.

2017-02-09 12:15 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +            voucher_offer = voucher.offers.first()
Yes, according to my understanding there is always going to be an offer for a voucher. @mjfrey can confirm.

2017-02-09 12:16 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +            offer_range = voucher_offer.condition.range
Yes, @mjfrey can you please confirm.

2017-02-09 12:19 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +            if offer_range.contains_product(product):
I am going to explicitly add a `return None` statement

2017-02-09 12:22 UTC, zubair-arbi commented on ecommerce/extensions/offer/models.py
> +            query = self.catalog_query
This should always have some value (existing behavior for dynamic coupons).

2017-02-10 15:32 UTC, mattdrayer commented
Thanks for addressing all of my concerns (thru changes and/or clarifications) -- 👍

2017-02-10 19:51 UTC, mjfrey requested changes

2017-02-10 19:51 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +        enterprise_course_catalog = get_course_catalogs(site=site, resource_id=enterprise_catalog_id)
Couple things here:
1: I would add an endpoint to the catalog service to return course_runs for a given catalog_id. This way you avoid multiple network trips.

2017-02-10 19:51 UTC, mjfrey commented on ecommerce/enterprise/entitlements.py
> +        enterprise_course_runs = get_catalog_course_runs(site, enterprise_course_catalog.get('query'))['results']
The results of this call could be many pages of results which I can not see being handled.  There also should be caching.

2017-02-13 07:19 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +        enterprise_course_catalog = get_course_catalogs(site=site, resource_id=enterprise_catalog_id)
@mjfrey @mattdrayer  I have added a new ticket [ENT-201](https://openedx.atlassian.net/browse/ENT-201) to implement this new end point.

2017-02-13 07:30 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +        enterprise_course_runs = get_catalog_course_runs(site, enterprise_course_catalog.get('query'))['results']
@mjfrey we are using the method [get_catalog_course_runs](https://github.com/edx/ecommerce/blob/master/ecommerce/coupons/utils.py#L14) which provide all course runs if no limit is provided by traversing pagination recursively. Also this method caches the result too. Please let me know if this clarify things.

2017-02-13 12:51 UTC, zubair-arbi commented
@mjfrey Please let me know if you are okay with merging this PR.

2017-02-13 13:57 UTC, mjfrey commented
I would rather see the new endpoint in catalog service before this is merged.  Why merge if it is not what we want?

2017-02-16 14:28 UTC, zubair-arbi commented
@mjfrey @mattdrayer I have updated the entitlements code to use catalog course runs contain endpoint to verify if a course exists against the enterprise catalog query. So now we don't need to get all course runs recursively from catalog service.
Since this PR is required for @saleem-latif work with consent based entitlements so we can focus on ENT-201 after this PR is merged.

2017-02-17 04:02 UTC, mattdrayer commented
@zubair-arbi please update this branch and when green you can merge in order to unblock @saleem-latif with the expectation that we will continue the work to revise this implementation to reflect the changes discussed with @mjfrey represented by ENT-201.

2017-02-17 07:15 UTC, zubair-arbi commented
@mattdrayer @mjfrey @saleem-latif  I am merging this PR and will address suggested improvements as part of ENT-201.

2017-02-17 07:16 UTC, merged