[WIP] ENT-134: Add consent gate when redeeming coupons from enterprise customers
openedx-unsupported/ecommerce pull request #1127
Opened 2017-02-03 03:13 UTC by bdero

This PR is based on [#1101](https://github.com/edx/ecommerce/pull/1101), which needs to be merged first. For now, view the [commit](https://github.com/open-craft/ecommerce/commit/03bfe815e138f3ce797075aece83e0cc9d034212) to see the diff of this PR.

This PR implements consent gating for coupon use by redirecting the user to the LMS course-specific consent UI when an enterprise customer is associated with a coupon. However, the coupon is not consumed nor does the user have to be associated with an Enterprise Customer until after consent is given and the order has been fulfilled.

This is achieved by a [change in edx-enterprise](https://github.com/edx/edx-enterprise/pull/40), where an option "enrollment_deferred" is added to allow removing the assumption that a user has an EnterpriseCourseEnrollment. For confirming the consent, this change leverages the redirect URL passed via the "next" GET parameter to the enterprise consent view.

- Say the user visits a coupon redeem URL (e.g. `/coupons/redeem/?code=IYO3SSQVEMHY2R5S&sku=BB3ECA9`), the view checks for the presence of a `consent_token` in the GET parameters (`content_token` has three degrees of uniqueness; the current OAuth2 access token (as the hmac key), the voucher ID, and the Enterprise Customer UUID).
- Because there isn't a `consent_token` in the URL, the view constructs a redirect to the enterprise consent page in the LMS, but with `enrollment_deferred` enabled and a `next` parameter containing an absolute URL that looks something like this (notice it's the same URL as before, but with the added `content_token` parameter):
    ```
    http://localhost:8002/coupons/redeem/?code=IYO3SSQVEMHY2R5S&sku=BB3ECA9&consent_token=524684104aecccb220ee362e4fccb57ce72f03fb1359970b6556a9f7d808695c
    ```
- So after the user provides consent and presses "Submit", they're redirected to the URL provided in the `next` parameter, which provides a `consent_token`.
- Now that the `consent_token` has been given, the coupon redeem view validates that it's correct before processing the coupon and order.

The security lies in the fact that constructing the valid `consent_token` requires knowledge of the user's current OAuth2 access token with the LMS. So for a third party adversary, constructing a URL that directly enrolls a user without asking for consent isn't feasible.

**JIRA tickets**: ENT-134.

**Discussions**: Architecture discussed extensively on the wiki and in meetings, then the revised proposal was presented to the Arch Council on Oct. 21 and given thumbs up.

**Dependencies**: #1101 and https://github.com/edx/edx-enterprise/pull/40

**Testing instructions**:

Initial setup:
1. Setup a devstack.
1. Override the ecommerce version with the [correct branch](https://github.com/edx/edx-enterprise/pull/40):
   ```
   /edx/bin/pip.edxapp install -e git+https://github.com/open-craft/edx-enterprise.git@bdero/optional-consent-enrollment#egg=edx-enterprise==optional-consent-enrollment
   /edx/bin/manage.edxapp lms migrate --settings=devstack
   ```
1. Checkout this branch (open-craft:bdero/coupon-enrollment-consent) for ecommerce.
1. Connect [ecommerce to the LMS](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/ecommerce/install_ecommerce.html#configure-edx-openid-connect-oidc).
1. (Optionally) setup the [course discovery](https://open-edx-course-catalog.readthedocs.io/en/latest/getting_started.html) service and [connect it to the LMS](https://open-edx-course-catalog.readthedocs.io/en/latest/oidc.html).
1. Create an Enterprise Customer in the LMS: http://localhost:8000/admin/enterprise/enterprisecustomer/add/
    1. Give it any name.
    1. Check the **Enable data sharing consent** box.
    1. For **Enforce data sharing consent**, select **At Enrollment**.
1. Add a new Course in Ecommerce: http://localhost:8002/courses/new/
    1. For the course ID, use "course-v1:edX+DemoX+Demo_Course".
    1. Name it "edX Demonstration Course".
    1. Choose "Professional Education" for the Course Type.
1. Create a new Coupon in Ecommerce: http://localhost:8002/coupons/new
    1. Give it any Coupon Name.
    1. Under Code Type choose "Enrollment Code".
    1. Give it a valid date range that includes today.
    1. For Client, type any name. E.g. "Some Client".
    1. Select the "Single course" radio button.
    1. For the Course ID, use "course-v1:edX+DemoX+Demo_Course"
    1. The only available Seat Type should be automatically populated: "Professional"
    1. For the Enterprise Customer, select the name of the customer created in step 6.

Testing the PR:
1. Navigate to the [coupon list](http://localhost:8002/coupons/) and click "Download Coupon Report" to retrieve a CSV containing the coupon URL.
    ![coupon report button screenshot](https://i.imgur.com/icRxZMr.png)
1. Log out of the LMS/ecommerce.
1. The coupon report CSV should contain an offer URL that looks like this:
    ```
    http://localhost:8002/coupons/offer/?code=EGGZYLXDKNZK6W7C
    ```
    Navigate to that URL.
1. The first screen is the offer landing page.
    ![offer landing page screenshot](https://i.imgur.com/Ppfb6OC.png)
    Click "Enroll Now".
1. Next, you should be redirected to the LMS to login.
    ![login page screenshot](https://i.imgur.com/WuMSvC5.png)
    Login using a user that's not already enrolled in the Demo course.
1. Upon logging in, you should be redirected to the course-specific Data Sharing Consent screen. The correct Enterprise Customer name and Course name should show up in the dialog.
    ![data sharing consent screenshot](https://i.imgur.com/vxA01hn.png)
    **Leave the "I agree" checkbox unchecked** and click Submit.
1. An alert dialog should show up alerting you that if you don't agree, you won't be given access to the course. Click Ok and note that you're redirected to the dashboard.
1. Navigate back to the offer URL (from step 3). This time, **check the "I agree" box** and click Submit. You should be redirected to the dashboard and now be enrolled in the course.
1. Navigate to the offer URL (from step 3) again. This time, there should be an error saying "This coupon has already been used."
    ![coupon error screenshot](https://i.imgur.com/P8y9ev1.png)

**Author notes and concerns**:

This still needs tests!

**Reviewers**
- [ ] @mtyaka 
- [ ] edX reviewer[s] TBD

2017-02-03 03:13 UTC, edx-webhook commented
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1127&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-02-04 07:43 UTC, bdero commented
@mtyaka Agreed - I went ahead and added an alternative method to collect a single enterprise customer after verifying the endpoint is built with django rest framework.

2017-02-07 05:56 UTC, mattdrayer commented on ecommerce/core/models.py
> +        return self.build_lms_url('/enterprise/grant_data_sharing_permissions')
Looks like we might be letting a verb-oriented API sneak in here?

2017-02-07 05:57 UTC, mattdrayer commented on ecommerce/coupons/views.py
> +            # Get information about the enterprise customer from the LMS.
Not really getting it from the LMS -- we're getting it from the Enterprise service, which at the moment is hosted in the LMS

2017-02-07 05:59 UTC, mattdrayer commented on ecommerce/coupons/views.py
> +            enterprise_customer_uuid = offer.benefit.range.enterprise_customer
It would be great if we could move this customer data retrieval logic into the `enterprise` module

2017-02-07 06:00 UTC, mattdrayer commented on ecommerce/coupons/views.py
> +                consent_token_hmac = hmac.new(
Along the lines of above, I think it would be good to move this consent logic out of the coupon view, if possible.

2017-02-07 06:04 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if range_data:
Can we flip this `if` around to a guard clause?  ie `if not range_data: ...`

2017-02-07 06:06 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +            Range.objects.filter(id=voucher_range.id).update(**range_data)
Is there a `return` missing here?

2017-02-07 06:08 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +            Range.objects.filter(id=voucher_range.id).update(**range_data)
Why use `filter` here?  Can there be more than one `Range`?  What if no Range objects are retrieved?

2017-02-07 06:09 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/enterprise.py
> +
Need a docstring

2017-02-07 18:23 UTC, bdero commented on ecommerce/extensions/api/v2/views/coupons.py
> +            Range.objects.filter(id=voucher_range.id).update(**range_data)
@mattdrayer This particular bit of code is not part of this PR, it's part of https://github.com/edx/ecommerce/pull/1101, which looks like it's already been reviewed twice. Maybe there's more context there?

2017-02-07 18:27 UTC, bdero commented on ecommerce/extensions/api/v2/views/coupons.py
> +            Range.objects.filter(id=voucher_range.id).update(**range_data)
Also, looking at the [base PR](https://github.com/edx/ecommerce/pull/1101), this new function contains little new code, it's mostly factoring out existing stuff as seen in [this diff](https://github.com/edx/ecommerce/pull/1127/files#diff-c9a451f0afeebe0481e4cee1c16b7c94L285).

2017-02-07 18:28 UTC, bdero commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if range_data:
@mattdrayer Same comments as https://github.com/edx/ecommerce/pull/1127/files#r99751380!

2017-02-07 18:34 UTC, bdero commented on ecommerce/core/models.py
> +        return self.build_lms_url('/enterprise/grant_data_sharing_permissions')
@mattdrayer I'm not sure I have the complete context to address this. This URL is used when constructing the destination of a 301 sent to the client browser. Would it make more sense to construct this URL somewhere else?

2017-02-07 22:53 UTC, bdero commented on ecommerce/coupons/views.py
> +            # Get information about the enterprise customer from the LMS.
Fixed, thanks.

2017-02-07 22:53 UTC, bdero commented on ecommerce/coupons/views.py
> +            enterprise_customer_uuid = offer.benefit.range.enterprise_customer
Sounds good, I separated this out.

2017-02-07 22:53 UTC, bdero commented on ecommerce/coupons/views.py
> +                consent_token_hmac = hmac.new(
Will there be another place we reuse deferred enrollment consent stuff in ecommerce? I'm having trouble thinking of a reasonable abstraction for this that wouldn't add complexity since the consent_token and URL construction is so tightly coupled with the context of coupons and specifically this view.

2017-02-07 23:36 UTC, bdero commented
@mattdrayer I've responded to your comments and this is ready for another look. Note that none of the code in f91f023 is actually part of this PR, it's #1101.

2017-02-13 21:37 UTC, mattdrayer commented on ecommerce/core/models.py
> +        return self.build_lms_url('/enterprise/grant_data_sharing_permissions')
I guess I'm trying to understand what resource we're working with here -- it's not clear from the URL what entity we are modifying on the server / retrieving for the user.

2017-02-13 21:37 UTC, mattdrayer commented on ecommerce/core/models.py
> +        return self.build_lms_url('/enterprise/grant_data_sharing_permissions')
also does this URL need an `/api/v1` URI stem?

2017-02-13 21:38 UTC, mattdrayer commented on ecommerce/coupons/views.py
> +        if enterprise_customer is not None and enterprise_customer['enable_data_sharing_consent']:
Can we count on `enable_data_sharing_consent` to always be present?  ie, do we need to think about `KeyError`?

2017-02-13 21:40 UTC, mattdrayer commented on ecommerce/coupons/views.py
> +            consent_token_hmac = hmac.new(
I still feel like this would be useful as its own little utility function, but if we're not going to use it anywhere else then I will yield to the YAGNI priniciple 😄

2017-02-13 21:43 UTC, mattdrayer commented on ecommerce/coupons/views.py
> +                # If the content token is set, then the user is returning from the consent view. Validate
"content" -> "consent"

2017-02-13 21:43 UTC, mattdrayer commented on ecommerce/coupons/views.py
> +                # that the computed token is the same as the one received from the redirect URL.
semantics, but the comment logic is the inverse of the actual check

2017-02-13 21:47 UTC, mattdrayer commented on ecommerce/enterprise/enrollments.py
> +def get_auth_user(site, username):
should we include "enterprise" in the name of this method?

2017-02-13 21:51 UTC, mattdrayer commented on ecommerce/enterprise/enrollments.py
> +def create_enterprise_service_client(site, resource):
It would help with the context for this module if we moved this particular function to the top of the file, since many of the other functions refer to it.

2017-02-13 21:54 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +        else:
Can we convert this into a guard:

```
if not stock_record_ids:
    return None

[rest of code]
```

2017-02-13 21:56 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/coupons.py
> +        else:
ah, perhaps this is the same deal as below...

2017-02-13 22:03 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/enterprise.py
> +def get_enterprise_customers(site, token):
I was going to suggest moving this to `ecommerce/enterprise/enrollments.py` but realized that this module is semantically scoped to enrollments.  It might be a good time to introduce an "enterprise_helpers.py" (or "enterprise/api.py" for all other parts of the ecommerce system to interact with the Enterprise service.

2017-02-13 22:04 UTC, mattdrayer commented on ecommerce/extensions/fulfillment/modules.py
> +from ecommerce.enterprise.enrollments import post_enterprise_course_enrollment
yeah, seeing this now I'm thinking that having an `api.py` module to hide away the implementation specifics for interacting with the Enterprise service would be a good thing

2017-02-14 05:03 UTC, bdero commented on ecommerce/coupons/views.py
> +        if enterprise_customer is not None and enterprise_customer['enable_data_sharing_consent']:
Good catch, this really should be doing a `.get` instead. I changed it, thanks!

2017-02-14 05:03 UTC, bdero commented on ecommerce/coupons/views.py
> +            consent_token_hmac = hmac.new(
Alrighty. Thanks for introducing "YAGNI" into my vocab. :)

2017-02-14 05:03 UTC, bdero commented on ecommerce/coupons/views.py
> +                # If the content token is set, then the user is returning from the consent view. Validate
Fixed, thanks!

2017-02-14 05:03 UTC, bdero commented on ecommerce/coupons/views.py
> +                # that the computed token is the same as the one received from the redirect URL.
Fixed.

2017-02-14 05:03 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +def get_auth_user(site, username):
Seems reasonable, added it in.

2017-02-14 05:03 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +def create_enterprise_service_client(site, resource):
Yeah, I went ahead and moved it to the top.

2017-02-14 05:03 UTC, bdero commented on ecommerce/extensions/fulfillment/modules.py
> +from ecommerce.enterprise.enrollments import post_enterprise_course_enrollment
@mattdrayer I'm actually considering refactoring it into an `EnterpriseApiClient` as suggested by @e-kolpakov (similar to the [CourseCatalogApiClient](https://github.com/edx/edx-enterprise/pull/29/files#diff-c59e08ddfc189e27b159a7151e1a87a3R27) in edx-enterprise).

2017-02-15 07:32 UTC, asadiqbal08 commented on ecommerce/enterprise/enrollments.py
> +    response = endpoint.post(data)
Why is it required to create an enterprise customer user explicitly here ?

2017-02-15 07:36 UTC, asadiqbal08 commented on ecommerce/enterprise/enrollments.py
> +    enterprise_customer_user = get_or_post_enterprise_customer_user(site, enterprise_customer_uuid, username)
What happened if API raise an exception while creating a `enterprise_customer_user` ?

2017-02-15 07:37 UTC, asadiqbal08 commented on ecommerce/enterprise/enrollments.py
> +    response = endpoint.post(data)
Here we are making two network calls. I think, @mattdrayer has some concern on that.

2017-02-15 07:38 UTC, asadiqbal08 commented on ecommerce/enterprise/enrollments.py
> +    response = endpoint.post(data)
We should handle any possible exceptions here too.

2017-02-15 07:45 UTC, asadiqbal08 commented on ecommerce/extensions/fulfillment/modules.py
> +                    post_enterprise_course_enrollment(
eager to know, What is the actual difference here and [LINE#233](https://github.com/edx/ecommerce/pull/1127/files#diff-c9f38bb98fd490cc1127bb1cbdd272a3R233) ?

2017-02-15 07:49 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +    response = endpoint.post(data)
Users that are not already an EnterpriseCustomerUser may redeem coupons associated with an EnterpriseCustomer. Since the coupons need to result in EnterpriseCourseEnrollments being created, we need to make sure an EnterpriseCustomerUser exists for the user.

2017-02-15 09:26 UTC, bdero commented on ecommerce/extensions/fulfillment/modules.py
> +                    post_enterprise_course_enrollment(
I just pushed the changes I made since rebasing, which involves removal of the duplicate parts, so this is now just making a call to create an Enterprise Customer User if one doesn't exist.

2017-02-15 09:26 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +    enterprise_customer_user = get_or_post_enterprise_customer_user(site, enterprise_customer_uuid, username)
Since this function does the same thing as the base PR, I removed it.

2017-02-15 09:27 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +    response = endpoint.post(data)
Since this function does the same thing as another in the base PR, I removed it.

2017-02-15 10:48 UTC, asadiqbal08 commented on ecommerce/extensions/fulfillment/modules.py
> +                    get_or_post_enterprise_customer_user(
I still need to understand the purpose of these same multiple network calls  to the same model(s) [HERE#220](https://github.com/edx/ecommerce/pull/1127/files#diff-c9f38bb98fd490cc1127bb1cbdd272a3R220) and [HERE#33](https://github.com/edx/ecommerce/pull/1127/files#diff-c9f38bb98fd490cc1127bb1cbdd272a3R233).

2017-02-15 13:05 UTC, asadiqbal08 commented on ecommerce/extensions/fulfillment/modules.py
> +                    get_or_post_enterprise_customer_user(
@mattdrayer

2017-02-15 17:45 UTC, bdero commented on ecommerce/extensions/fulfillment/modules.py
> +                    get_or_post_enterprise_customer_user(
@asadiqbal08 They're not the same. `get_or_post_enterprise_customer_user` create's an EnterpriseCustomerUser, `enterprise_api.link_course_enrollment_to_enterprise_customer` creates an EnterpriseCourseEnrollment.

But there is one additional route for round trip saving that I just implemented here: If there's a coupon being redeemed with an associated EnterpriseCustomer, we have to create an EnterpriseCustomerUser, which returns the ID. So I refactored this logic to not fetch the EnterpriseCustomerUser again when creating the EnterpriseCourseEnrollment in the event that we already know the EnterpriseCustomerUser ID.

2017-02-15 18:08 UTC, asadiqbal08 commented on ecommerce/extensions/fulfillment/modules.py
> +                    get_or_post_enterprise_customer_user(
I know, these are not the same but I have the concern to fetch enterprise-customer-learner multiple times but I can see you have updated the code under a condition. Thanks for the clarification.

2017-02-15 18:15 UTC, mattdrayer commented
@mjfrey FYI

2017-02-15 18:16 UTC, mattdrayer commented on ecommerce/core/models.py
> +        return self.build_lms_url('/enterprise/grant_data_sharing_permissions')
Instead of `build_lms_url` here we should instead introduce a `build_enterprise_service_url` method -- remember that we are secretly leeching off the LMS for hosting :)

2017-02-15 20:28 UTC, bdero commented on ecommerce/extensions/fulfillment/modules.py
> +                    get_or_post_enterprise_customer_user(
@asadiqbal08 Ah, gotcha. I'm glad I addressed the concern, your comment prompted me to notice, thanks! :)

2017-02-16 04:08 UTC, mattdrayer commented on ecommerce/enterprise/enrollments.py
> +    user = get_enterprise_auth_user(site, username)
Seems like the enterprise service should be able to do a lookup of a user using the `username` during the POST to the `enterprise-learner` endpoint instead of having to call `auth-user` first just to get an identifier which we then turn right around and send back to the enterprise service...

2017-02-16 04:10 UTC, mattdrayer commented on ecommerce/enterprise/enrollments.py
> +"""
None of the functions here appear to be specific to "enrollments", so they should probably instead be moved to a `utils.py` module

2017-02-16 04:11 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +def link_course_enrollment_to_enterprise_customer(site, course_id, enterprise_customer_user_id):
the name of this function leads me to believe it should be moved to the `enrollments.py` module

2017-02-16 04:13 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +def link_course_enrollment_to_enterprise_customer(site, course_id, enterprise_customer_user_id):
In addition -- and I feel like we may have already discussed so please forgive my amnesia -- the name of this function doesn't really fit with the arguments it's asking for.  That is, we're not giving it a course enrollment, and we're not giving it an enterprise customer.

2017-02-16 04:15 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/enterprise.py
>  class EnterpriseCustomerViewSet(generics.GenericAPIView):
The `get_enterprise_customers` workflow in this view should probably call some internal logic such vs. connecting directly to the enterprise service.

2017-02-16 04:23 UTC, mattdrayer commented on ecommerce/extensions/fulfillment/modules.py
> +                        enterprise_api.link_course_enrollment_to_enterprise_customer(
So I still feel like we should be able to accomplish all of this simply by passing the course enrollment and the enterprise customer information to `link_course_enrollment_to_enterprise_customer`  -- there's really no need to do all the EnterpriseCustomerUser back-and-forth.

Let's take a further step back from that, even.  I discussed this particular part of the PR with @mjfrey today, and it actually looks like the wrong place to be handling this work.  Instead, the EnterpriseCourseEnrollment record should be added during he CourseEnrollment workflow in LMS, not here in Otto.  The LMS is perfectly capable of determining if this is an enterprise context, and if so hitting the enterprise service after the course enrollment record has been written -- Otto can remain ignorant of the entire thing.

2017-02-16 04:58 UTC, asadiqbal08 commented on ecommerce/enterprise/entitlements.py
> +def link_course_enrollment_to_enterprise_customer(site, course_id, enterprise_customer_user_id):
is it make sense -- `link_course_with_enterprise_learner` ?

2017-02-16 06:12 UTC, bdero commented on ecommerce/extensions/fulfillment/modules.py
> +                        enterprise_api.link_course_enrollment_to_enterprise_customer(
Alright, after we discussed, I setup this PR for such a change by dropping the ENT-115 from the dependencies, leaving only the creation of the EnterpriseCustomerUser in the case of coupons if need be, and I will be opening a new PR to add the new EnterpriseCourseEnrollment post to the LMS enrollment view.

2017-02-17 02:04 UTC, bdero commented on ecommerce/core/models.py
> +        return self.build_lms_url('/enterprise/grant_data_sharing_permissions')
Ok, this required a setting change. I replaced ENTERPRISE_API_URL with ENTERPRISE_SERVICE_URL because the full API URL is too specific for this case: https://github.com/edx/ecommerce/pull/1127/commits/a7ccd054fff65edcb551c313b25c83cd1c4252a0

2017-02-17 03:01 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +    user = get_enterprise_auth_user(site, username)
Done. I removed `get_enterprise_auth_user` and implemented this view functionality here: https://github.com/edx/edx-enterprise/pull/40/commits/e78e793cdb525a22572ffb1e2911a06148ed8faa

2017-02-17 03:04 UTC, bdero commented on ecommerce/enterprise/entitlements.py
> +def link_course_enrollment_to_enterprise_customer(site, course_id, enterprise_customer_user_id):
This was dropped from this PR since we're downstreaming this call to the LMS enrollment view

2017-02-17 03:09 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +"""
Done.

2017-02-17 03:12 UTC, bdero commented on ecommerce/extensions/api/v2/views/enterprise.py
>  class EnterpriseCustomerViewSet(generics.GenericAPIView):
Ok, I moved get_enterprise_customers to the enterprise module

2017-02-17 04:06 UTC, mattdrayer commented on ecommerce/coupons/views.py
> +            consent_token_hmac = hmac.new(
...still think we should move this consent token generator into a function like `get_enterprise_customer_data_sharing_consent_token`...

2017-02-17 04:07 UTC, mattdrayer commented on ecommerce/core/models.py
> +        return settings.ENTERPRISE_API_URL
I'm slightly confused with why we need both ENTERPRISE_API_URL and ENTERPRISE_SERVICE_URL -- can we just have SERVICE?

2017-02-17 04:15 UTC, mattdrayer commented
This PR looks great now -- @mjfrey will be happy 😉

2017-02-17 04:15 UTC, mattdrayer commented on ecommerce/core/models.py
> +        return settings.ENTERPRISE_API_URL
Discussed offline -- I get it now

2017-02-17 09:54 UTC, mtyaka requested changes
@bdero I've run into some issues while testing this. See inline comments for more info.

2017-02-17 09:54 UTC, mtyaka commented on ecommerce/core/models.py
> +        return urljoin(settings.ENTERPRISE_SERVICE_URL, path)
It looks like you have to be very careful with slash characters when using `urljoin` - the way this is currently set up is not working for me in devstack. This is how `urljoin` works with different combinations of slashes:

```python
urljoin('http://localhost:8000/enterprise/', '/grant_data_sharing_permission') 
# -> 'http://localhost:8000/grant_data_sharing_permissions'

urljoin('http://localhost:8000/enterprise', 'grant_data_sharing_permission') 
# -> 'http://localhost:8000/grant_data_sharing_permissions'

urljoin('http://localhost:8000/enterprise/', 'grant_data_sharing_permission') 
# -> 'http://localhost:8000/enterprise/grant_data_sharing_permissions'
```

The last combination is the only combination that works as you'd expect.

2017-02-17 09:54 UTC, mtyaka commented on ecommerce/core/models.py
> +        return self.build_enterprise_service_url('/grant_data_sharing_permissions')
Does not build correct URL for me - the leading slash character should be removed.

2017-02-17 09:54 UTC, mtyaka commented on ecommerce/settings/local.py
> +ENTERPRISE_API_URL = urljoin(ENTERPRISE_SERVICE_URL, '/api/v1/')
Does not work correctly because of the leading slash.

2017-02-17 09:54 UTC, mtyaka commented on ecommerce/settings/production.py
> +ENTERPRISE_API_URL = urljoin(ENTERPRISE_SERVICE_URL, '/api/v1/')
Does not work correctly because of the leading slash.

2017-02-17 09:54 UTC, mtyaka commented on ecommerce/settings/test.py
> +ENTERPRISE_API_URL = urljoin(ENTERPRISE_SERVICE_URL, '/api/v1/')
Does not work correctly because of the leading slash.

2017-02-17 09:54 UTC, mtyaka commented on ecommerce/enterprise/utils.py
> +    return response['id']
This is possibly due to some kind of misconfiguration on my part, but I can't figure it out :/
This fails for me on this line because the `'id'` attribute is not present in the response. I logged the response that I get and it looks like this:

```python
{u'username': u'mtyaka', u'enterprise_customer': u'46f5f645-af20-4f56-ad4c-6d8705fcf8e9'}
```

The `EnterpriseCustomerUser` does not get created. Any idea why?

2017-02-18 02:20 UTC, bdero commented on ecommerce/enterprise/utils.py
> +    return response['id']
Ah, sorry, you are right, this endpoint is no longer be returning an ID (we don't need the ID anymore). I fixed this and it should be all set now.

2017-02-18 02:20 UTC, bdero commented on ecommerce/settings/test.py
> +ENTERPRISE_API_URL = urljoin(ENTERPRISE_SERVICE_URL, '/api/v1/')
Fixed, thanks

2017-02-18 02:20 UTC, bdero commented on ecommerce/settings/production.py
> +ENTERPRISE_API_URL = urljoin(ENTERPRISE_SERVICE_URL, '/api/v1/')
Fixed, thanks

2017-02-18 02:20 UTC, bdero commented on ecommerce/settings/local.py
> +ENTERPRISE_API_URL = urljoin(ENTERPRISE_SERVICE_URL, '/api/v1/')
Fixed, thanks

2017-02-18 02:20 UTC, bdero commented on ecommerce/core/models.py
> +        return self.build_enterprise_service_url('/grant_data_sharing_permissions')
Fixed, thanks

2017-02-18 02:20 UTC, bdero commented on ecommerce/core/models.py
> +        return urljoin(settings.ENTERPRISE_SERVICE_URL, path)
Yeah, sorry - I had just made this change quickly without manually testing it, and this code path isn't covered yet in tests. I've fixed it. Thanks for figuring out that odd urljoin nuance. It looks urljoin might be distinguising between absolute vs relative URLs, although I've got no idea what's going on with that second example. ;)

2017-02-18 04:51 UTC, bdero commented on ecommerce/coupons/views.py
> +            consent_token_hmac = hmac.new(
Alright, I factored this out, and I also factored out the redirect URL construction code, which simplified test building for these code paths.

2017-02-18 09:34 UTC, bdero commented
@mtyaka This is ready for your continued review. :)

2017-02-20 09:19 UTC, mtyaka commented
:+1: It all works for me now!

- [x] I tested this: I followed the testing procedure in the PR with several variations.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

2017-02-20 09:19 UTC, mtyaka approved these changes

2017-02-20 18:44 UTC, bdero commented
Thanks @mtyaka!

@mattdrayer Could you let me know if you have any more comments for this?

2017-02-21 02:14 UTC, mattdrayer commented
@bdero I think the PR looks really great now -- thanks so much for sticking with this one as it evolved -- you're a trooper 😄     👍 :shipit:

2017-02-21 03:07 UTC, bdero commented
@mattdrayer Great! Before merging this, I think we need to wait until https://github.com/edx/edx-platform/pull/14542 is merged too, since it will contain the edx-enterprise version bump to `0.23.0` (https://github.com/edx/edx-enterprise/pull/40).

2017-02-22 13:49 UTC, e-kolpakov reviewed
I don't want it to become a blocker here, but I'd  strongly suggest to make get_enterprise_customer(s) methods to return data of identical structure (with ..._customers returning an array of course).

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/coupons/views.py
> +            consent_token_hmac = hmac.new(
@bdero I'd suggest moving the `if .. else ..` branches into methods.

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/enterprise/enrollments.py
> +        client = getattr(client, nav)
@bdero I''m not suggesting to actually do that here, but if you'd like to show off:

    parts = ['enterprise-customer', str(uuid)]
    reduce(operator.attrgetter, parts, client)

Yes, now I'm showing off :)

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/enterprise/enrollments.py
> +def get_or_post_enterprise_customer_user(site, enterprise_customer_uuid, username):
@bdero nit: I don't feel like this is a good idea, or at least a good name.

Options to address mine "I have a baaaad feeling about this":

1. Totally ignore :)
2. Rename to something like `get_or_create_enterprise_customer_user`.
3. Better yet: split  into get and create and let caller do the logic (of creating if it does not exist).

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +                        'name': 'Millennium Falcon',
@bdero nit: How's entire academy get in one list with just one ship? Or do you claim that Millenium Falcon is an "organization" on it's own (i.e. travelling band)? :)

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +                        'name': 'Millennium Falcon',
@bdero Oh, right it's not from this PR. Question to you then @haikuginger.

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/coupons/views.py
> +                {'error': _('An unexpected error occured while redeeming this coupon.')}
@bdero Might make sense to be more specific here - if I understand right this message is shown to users, so they will have little to no understanding of what exactly went wrong. Dev team will be able to debug it (since log record is added), but it would require slightly less development involvement if user-facing message could be more specific, i.e. "Was unable to redeem the coupon due to {enteprise customer not found / disabled / we don't like it / we don't like you}".

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/coupons/views.py
> +        if enterprise_customer is not None and enterprise_customer.get('enable_data_sharing_consent'):
@bdero nit: IDE should have complained that you're referencing potentially uninitialized `enterpise_customer` here. Not a big deal, but I recall I once had some trouble refactoring such a flow - details are fuzzy though. Might be good to add something like `enterprise_customer = None` above the try.

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/enterprise/utils.py
> +def get_enterprise_customers(site, token):
@bdero may I suggest enforcing uniform Enterprise Customer structure across singular GET (`get_enterprise_customer`) and plural GET (`get_enterprise_customers`) requests? I mean, return value of `get_enterprise_customers` should contain a list of exactly same results as if you just called `get_enterprise_customer` multiple times.

Having different structure for plurals and singulars is a mine - one wouldn't be able to tell it exists without looking at the code or facing an error in runtime.

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/enterprise/utils.py
> +def get_or_post_enterprise_customer_user(site, enterprise_customer_uuid, username):
@bdero nit: `get_or_create_` ?

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/enterprise/utils.py
> +    response = endpoint.post(data)
@bdero Might be good to have the same return value structure as with GET methods. Maybe even to an extent of doing a "get by id" request additionally.

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/enterprise/utils.py
> +        raise EnterpriseException(
@bdero might be a good idea to throw a differentiated exception type - i.e. dedicated exception type for this scenario, inherited from `EnterpriseException`

2017-02-22 13:49 UTC, e-kolpakov commented on ecommerce/extensions/api/v2/views/enterprise.py
> +ConditionalOffer = get_model('offer', 'ConditionalOffer')
@bdero Seems to not be used in this file - please explain (is it here for side-effects?) or remove

2017-02-23 17:31 UTC, bdero commented on ecommerce/extensions/api/v2/views/enterprise.py
> +ConditionalOffer = get_model('offer', 'ConditionalOffer')
Yup, you're right, I removed this.

2017-02-23 17:31 UTC, bdero commented on ecommerce/enterprise/utils.py
> +        raise EnterpriseException(
I actually made this exception for this specific scenario, and this is actually the only place it's being raised, so I feel like it might be better to leave it as-is for now rather than make child exceptions. :) It could be that I'm just missing the point, but what do you think?

2017-02-23 17:31 UTC, bdero commented on ecommerce/enterprise/utils.py
> +    response = endpoint.post(data)
I feel we shouldn't add new requests to this, since there are actually some operations compressed into the corresponding edx-enterprise view in order to minimize extra request overhead for e.g. large orders. (See previous addressed comments in this PR for details)

2017-02-23 17:31 UTC, bdero commented on ecommerce/enterprise/utils.py
> +def get_or_post_enterprise_customer_user(site, enterprise_customer_uuid, username):
Changed it, thanks.

2017-02-23 17:31 UTC, bdero commented on ecommerce/enterprise/utils.py
> +def get_enterprise_customers(site, token):
Alright, I made it so they return the same structure for an Enterprise Customer.

2017-02-23 17:31 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +def get_or_post_enterprise_customer_user(site, enterprise_customer_uuid, username):
Alright, I renamed this to `get_or_create_enterprise_customer_user`.

2017-02-23 17:31 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +        client = getattr(client, nav)
Ah, true. I changed it to this:

```python
    path = ['enterprise-customer', str(uuid)]
    reduce(operator.attrgetter, path, client)
```

Thanks!

2017-02-23 17:31 UTC, bdero commented on ecommerce/coupons/views.py
> +        if enterprise_customer is not None and enterprise_customer.get('enable_data_sharing_consent'):
Since the except path returns, this is safe. I believe that's why pycharm nor pylint is complaining about it. :)

2017-02-23 17:31 UTC, bdero commented on ecommerce/coupons/views.py
> +                {'error': _('An unexpected error occured while redeeming this coupon.')}
Ok, I changed it to be more specific, thanks!

```python
_('Couldn\'t find a matching Enterprise Customer for this coupon.')
```

2017-02-23 17:31 UTC, bdero commented on ecommerce/coupons/views.py
> +            consent_token_hmac = hmac.new(
This was refactored a bit and separated a bit more into functions since the diff that this comment is on.

2017-02-23 17:32 UTC, bdero commented
All comments addressed @e-kolpakov !

2017-02-23 20:00 UTC, bdero commented on ecommerce/enterprise/enrollments.py
> +        client = getattr(client, nav)
Had to use `getattr` since `operator.attrgetter` returns a callable rather than the attribute value itself.

2017-02-24 14:04 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    response = endpoint.post(data)
I agree with @bdero. If we don't actually make use of the extra data right now, performing an extra request seems like a bad idea.

2017-02-24 14:04 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +        raise EnterpriseException(
`EnterpriseException` does feel a bit overbroad as a naming scheme. I don't think it's necessary to create an entire hierarchy of exceptions based around it, but I might rename it to something like `EnterpriseDoesNotExist`.

2017-02-24 21:02 UTC, bdero commented on ecommerce/enterprise/utils.py
> +        raise EnterpriseException(
Ok, I changed it to EnterpriseDoesNotExist

2017-02-24 21:30 UTC, bdero commented
After a little offline discussion, I will merge this now since it has already had two approvals, currently has no explicit disapprovals, this PR has gone through extensive internal and external review in general, and the blocking edx-platform PR is now merged! :)

2017-02-24 21:30 UTC, merged

2017-04-04 17:33 UTC, clintonb commented on ecommerce/extensions/fulfillment/modules.py
> +                    enterprise_customer_uuid = discount.voucher.benefit.range.enterprise_customer
The assumption that all discounts are linked to vouchers is wrong. This breaks fulfillment of orders that include a conditional offer not linked to a voucher (e.g. site-wide discount).

2017-04-04 18:05 UTC, mattdrayer commented on ecommerce/extensions/fulfillment/modules.py
> +                    enterprise_customer_uuid = discount.voucher.benefit.range.enterprise_customer
@clintonb would it be an acceptable band-aid to add a check here for the existence of a linked voucher until the new benefit-based approach has been implemented?

2017-04-04 18:07 UTC, clintonb commented on ecommerce/extensions/fulfillment/modules.py
> +                    enterprise_customer_uuid = discount.voucher.benefit.range.enterprise_customer
That's fine for now, sure. But, we need to fix this functionality soon. Fulfillment should not be concerned with vouchers. I am concerned about other pitfalls that may await us.