[WIP] Get account details with site configuration access token
openedx-unsupported/ecommerce pull request #1130
Opened 2017-02-06 13:11 UTC by iivic

@clintonb Did I understand your comment correctly https://openedx.atlassian.net/browse/SOL-2163?focusedCommentId=241447&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-241447
Instead of using the users access token we should use site configuration access token on every server-to-server API call?
If that's the case can you tell me what I'm missing because the change doesn't work. The 401 HttpClientError is still getting raised.

2017-02-06 13:11 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1130&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-02-06 13:52 UTC, clintonb requested changes
This needs to be tested.

2017-02-06 13:52 UTC, clintonb commented on ecommerce/core/models.py
> +                oauth_access_token=request.site.siteconfiguration.access_token,
`jwt`

https://github.com/edx/ecommerce/blob/master/ecommerce/core/models.py#L319

2017-02-06 13:54 UTC, clintonb commented
@iivic this change is exactly what I was referring to. If you're still seeing a 401 after fixing the call, you're going to need to share more information. Particularly, I need to know what your `JWT_AUTH` settings are for both services.

2017-02-06 13:56 UTC, iivic commented on ecommerce/core/models.py
> +                oauth_access_token=request.site.siteconfiguration.access_token,
It works after changing the argument to jwt.

2017-02-07 07:57 UTC, iivic commented
@clintonb 
I was thinking about mocking the EdxRestApiClient response but then I realized it makes no sense because it will not cover any real issue. There is a test for account_details response [test](https://github.com/edx/ecommerce/blob/master/ecommerce/core/tests/test_models.py#L94) so I didn't add one.
I tested the fix locally and it works fine. Is this PR good to go?

2017-02-07 07:58 UTC, iivic commented
FYI @mjfrey

2017-02-07 13:48 UTC, clintonb approved these changes
It would be nice to update the test to verify a JWT is sent; but, that is not crucial.

2017-02-07 15:14 UTC, iivic commented
@clintonb I made a test to verify the jwt is sent. Take a quick look to make sure it's done properly.

2017-02-07 15:41 UTC, clintonb approved these changes

2017-02-08 08:07 UTC, merged