[WIP]: ENT:136: Update coupon redemption page to account for the catalog id
openedx-unsupported/ecommerce pull request #1133
Opened 2017-02-07 13:43 UTC by saleem-latif

@mattdrayer , @zubair-arbi , @asadiqbal08 --FYI

2017-02-10 17:58 UTC, mattdrayer commented on ecommerce/coupons/utils.py
> +    Fetch course catalog for the given catalog id.
I think we can just say "catalog" and not "course catalog" here

2017-02-10 18:02 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/vouchers.py
>              logger.error('Could not get course information.')
Does "course information" properly describe what we are retrieving here?

2017-02-10 18:02 UTC, mattdrayer commented on ecommerce/extensions/api/v2/views/vouchers.py
> +            logger.error('Could not get catalog info from catalog-id for voucher code %s.', code)
We are not dealing with "catalogs" here, per se, we are dealing with "offers"

2017-02-10 18:10 UTC, mattdrayer commented
Overall approach LGTM, @saleem-latif -- branch needs a rebase + tests but the implementation makes sense.  I see we are adding some network communications in this PR, so @mjfrey (or someone from his team) is probably going to want to take a look as well.

2017-02-17 15:49 UTC, mattdrayer commented
@haikuginger @bdero here is the change set for ENT-136 -- please let me know if this is blocking anything having to do with ENT-134 / ENT-162

2017-02-17 20:42 UTC, bdero commented
@mattdrayer AFAIK it's not, since the catalog is at no point used in the checks for whether an EnterpriseCustomerUser or EnterpriseCourseEnrollment will be created in https://github.com/edx/edx-enterprise/pull/40 nor https://github.com/edx/ecommerce/pull/1127.

2017-02-21 11:04 UTC, vkaracic requested changes

2017-02-21 11:04 UTC, vkaracic commented on ecommerce/coupons/utils.py
> +    Fetch catalog for the given catalog id.
I don't think you are fetching a [``catalog``](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/catalogue/models.py#L19) here but a ``course catalog``. You should be mindful of the distinction since catalogs are still used for single-course coupons.

2017-02-21 11:04 UTC, vkaracic commented on ecommerce/coupons/utils.py
> +            response = endpoint(catalog_id).get()
You should be able to do this with ``api.catalogs(catalog_id).get()``

2017-02-21 11:04 UTC, vkaracic commented on ecommerce/coupons/utils.py
> +        Timeout: requests exception "Timeout"
This part should describe when and why an exception is raised.

2017-02-21 11:04 UTC, vkaracic commented on ecommerce/utils.py
> +        kay1:value1_key2:value2 ...
``key1``

2017-02-21 11:04 UTC, vkaracic commented on ecommerce/utils.py
> +    key = "_".join(["{}:{}".format(item, value) for item, value in kwargs.iteritems()])
Please import ``six`` and use ``six.iteritems(kwargs)``. This will help transition to Python 3 where ``iteritems`` was replaced by ``items``.

2017-02-21 11:04 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
>      products = voucher_range.all_products()
Will this work for the course catalog case? Since it's not accounted for in [``all_products()``](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/offer/models.py#L294-L301).

2017-02-21 11:04 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/vouchers.py
> +            logger.error('Could not connect to offers service.')
Technically it's ``Could not connect to course catalog service.``

2017-02-21 11:04 UTC, vkaracic commented on ecommerce/coupons/utils.py
> +        site (django.contrib.sites.models.Site): Instance to the current site.
Just ``site (Site)`` will suffice. Also ``Instance of the current site``.

2017-02-23 09:45 UTC, saleem-latif commented on ecommerce/coupons/utils.py
> +            response = endpoint(catalog_id).get()
@vkaracic I did this to adhere to current coding pattern as is done [here](https://github.com/edx/ecommerce/blob/master/ecommerce/coupons/utils.py#L54) and [here](https://github.com/edx/ecommerce/blob/master/ecommerce/courses/utils.py#L54)

2017-02-23 10:05 UTC, saleem-latif commented on ecommerce/extensions/voucher/utils.py
>      products = voucher_range.all_products()
Good catch, I will update it and tests for this.

2017-02-24 11:48 UTC, saleem-latif commented
@vkaracic I have incorporated your feedback changes, however, I still need to add tests for the change set. Feel free to give another pass on the PR and share your thoughts before the tests are added.

2017-02-24 12:22 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/vouchers.py
> +        except HttpNotFoundError:
Pylint reports ``E: 79,15: Bad except clauses order (SlumberBaseException is an ancestor class of HttpNotFoundError) (bad-except-order)`` so you don't need this.

2017-02-27 13:35 UTC, saleem-latif commented
@vkaracic kindly take a look now.

2017-02-27 13:48 UTC, vkaracic approved these changes
One comment, otherwise LGTM.

2017-02-27 13:48 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        self.mock_fetch_course_catalog_with_failure(catalog_id=catalog_id, expected_status=status.HTTP_404_NOT_FOUND)
The lines above this one are almost exactly the same in all tests you've added. Please factor them out into a single method and use that instead, i.e. [don't repeat yourself](http://deviq.com/don-t-repeat-yourself/)

2017-02-27 15:17 UTC, mattdrayer commented
Looks like another rebase is needed -- 👍 assuming all checks pass after doing that.

2017-02-28 11:42 UTC, merged