ECOM-6928 : Revert [SOL-2083] Because it enables student to create multiple orders for same course seat
openedx-unsupported/ecommerce pull request #1137
Opened 2017-02-08 17:37 UTC by Ayub-Khan

Reverts edx/ecommerce#953

**ECOM-6928** :
In SOL-2083 changes enrollment check to work only for coupon baskets, thus enabling other students to place multiple orders for same course(aka Multiple Order Issue). 

**Steps to Reproduce:**
1. Enroll in a verified course on stage.
2. Open Basket page from dashboard in new tab and pay for the course.
3. Open Basket page from same dashboard again and pay for the course.

**Expected** : 
Student should not be able to pay multiple times for single course seat.
**Actual** : 
Student can pay for a course multiple times. 

fyi @mjfrey

2017-02-08 17:48 UTC, clintonb requested changes
This is not doing what you described in the description.

2017-02-08 18:20 UTC, Ayub-Khan commented
@clintonb sorry i did not get your point. Can you explain. There are two checks 
- "product.get_product_class().name != ENROLLMENT_CODE_PRODUCT_CLASS_NAME:"
- "request.user.is_user_already_enrolled(request, product)" (inner if)
First one makes sure that second one does not work for enrollment code orders. While it works for all other baskets. Second check makes sure that if a student is already in verified mode for a course he should not be able to place any other order for that. But adding coupon code condition to first one makes sure that second one only runs when there is a coupon in the basket. Thus enabling students to create multiple orders for the course.

2017-02-08 19:24 UTC, clintonb approved these changes

2017-02-10 11:09 UTC, Ayub-Khan commented
@mjfrey can you review ?

2017-02-10 14:29 UTC, mjfrey approved these changes
I think you will need to add some tests.

2017-02-13 08:29 UTC, Ayub-Khan commented
@mjfrey tests are already there.

2017-02-13 11:15 UTC, Ayub-Khan commented
jenkins run all

2017-02-14 14:11 UTC, merged

2017-02-15 21:28 UTC, clintonb commented
@Ayub-Khan @adampalay this needs to be revisited. The error page seen when a user is already enrolled is a simple line of text on an otherwise empty page. This is poor user experience. I am inclined to revert this until a proper UI is in place.

2017-02-21 08:58 UTC, Ayub-Khan commented
@clintonb I agree this is a bad user experience but as compare to letting user pay multiple times its bearable. Also for user to place multiple orders and payments and than getting refund for those would be worse. In my opinion you should let this be there and create a ticket to create or update response page when this occurs, there is no need to revert this as this blocks 43 average multiple payment attempts every day. 
fyi @adampalay

2017-02-28 16:20 UTC, rlucioni commented
This change appears to be tied to auth-related errors preventing users from enrolling and should be reverted until the issue is better understood. See [Splunk](https://splunk.edx.org/en-US/app/search/search?sid=1488257147.4684184).