Add Backend Validation for Note
openedx-unsupported/ecommerce pull request #1140
Opened 2017-02-10 13:20 UTC by iivic

SOL-2204
The only requirement is that note must be type str or unicode (basestring).
I changed the ValidationError handling in the update method so notice that as well.
@vkaracic @marjev  @mjfrey

2017-02-10 13:21 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1140&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-02-13 08:25 UTC, vkaracic requested changes

2017-02-13 08:25 UTC, vkaracic commented on ecommerce/extensions/catalogue/models.py
> +    def clean(self):
``Product`` already has a [clean](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/catalogue/abstract_models.py#L367) method. This is how it works for ``note`` attribute (or any [text](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/catalogue/migrations/0016_coupon_note_attribute.py#L18) type attributes):
```
p = Product.objects.filter(product_class__name='Coupon').first()
p  # <Product: Test1>
p.attr.note = 123
p.clean()
ValidationError: [u"note attribute [u'Must be str or unicode']"]
```

Try to either re-use the already existing validation, or adjust it to your needs but don't override ``clean`` like this.

2017-02-13 09:17 UTC, marjev requested changes

2017-02-13 09:17 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        details = self.get_response_json('GET', reverse('api:v2:coupons-detail', args=[coupon.id]))
Lines 927 and 928 are called consecutively in almost all test methods for updating coupon fields. It would be a good time to refactor this.

2017-02-13 09:17 UTC, marjev commented on ecommerce/extensions/api/v2/views/coupons.py
> +            raise serializers.ValidationError(error_message)
why not use `log_message_and_raise_validation_error `?

2017-02-13 09:17 UTC, marjev commented on ecommerce/extensions/catalogue/models.py
> +                    'Failed to create Product. Product note value must be type string'
nitpick: `must be of type string`.

2017-02-13 09:17 UTC, marjev commented on ecommerce/extensions/catalogue/tests/test_models.py
> +
remove this space.

2017-02-13 09:17 UTC, marjev commented on ecommerce/extensions/catalogue/tests/test_models.py
> +        )
Don't we have factories for `Product_class` and `Product`? If not, it's time to create those or update existing if, for any reason, you're not able to use those to create test objects.

2017-02-14 11:40 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +            raise serializers.ValidationError(error_message)
This is not the same [ValidationError](http://www.django-rest-framework.org/api-guide/exceptions/#validationerror) as the django ValidationError.

2017-02-14 14:58 UTC, iivic commented
Ready for second review.

2017-02-15 06:48 UTC, marjev approved these changes

2017-02-15 08:28 UTC, vkaracic requested changes

2017-02-15 08:28 UTC, vkaracic commented on ecommerce/extensions/catalogue/models.py
> +                    'Failed to create Product. Product note value must be of type string.'
``clean()`` does a validation of all the product attributes (among other properties, [see table](https://github.com/django-oscar/django-oscar/blob/1.1.1/src/oscar/apps/catalogue/abstract_models.py#L367)). If one of the other than ``note`` fails you will log this.
Lose the attribute check and just do this:
```
try:
    self.clean()
except ValidationError as e:
    log_message_and_raise_validation_error(e.message)
```

2017-02-15 08:28 UTC, vkaracic commented on ecommerce/extensions/catalogue/tests/test_models.py
> +        )
You could re-use this: https://github.com/edx/ecommerce/blob/master/ecommerce/coupons/tests/mixins.py#L146

2017-02-15 08:28 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        details = self._get_coupon_details(self.data['title'])
Nit: the POST call above is above every call of this abstraction, maybe factor it in as well?

2017-02-15 15:00 UTC, iivic commented
Ready for another review.

2017-02-15 15:05 UTC, vkaracic commented on ecommerce/extensions/catalogue/models.py
> +        if hasattr(self.attr, 'note'):
Why would you call ``clean`` only for coupons with ``note``? Shouldn't everything be validated?

2017-02-15 15:07 UTC, vkaracic commented on ecommerce/extensions/catalogue/tests/test_models.py
> +        voucher = factories.VoucherFactory(code='TESTVOUCHER')
Do you need the ``code`` parameter?

2017-02-15 15:08 UTC, vkaracic approved these changes
A couple of nits. Going forward we should definitely consider creating a coupon factory.

2017-02-16 09:06 UTC, iivic commented on ecommerce/extensions/catalogue/models.py
> +        if hasattr(self.attr, 'note'):
Because the validation will fail if the note isn't set for a coupon product. I'm validating the field from the coupon creation/edit form. If you want to make the validation for everything I wish you good luck.

2017-02-16 09:08 UTC, vkaracic commented on ecommerce/extensions/catalogue/models.py
> +        if hasattr(self.attr, 'note'):
Because it isn't set? That's odd since it's set to not be required: https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/catalogue/migrations/0016_coupon_note_attribute.py#L19
What's the error message that you get?

2017-02-16 09:21 UTC, iivic commented on ecommerce/extensions/catalogue/models.py
> +        if hasattr(self.attr, 'note'):
It is not required when not calling clean() on Product but when clean is called it will require all the attributes to be set (title, coupon_vouchers, note). The title and coupon_vouchers will be set on every coupon but the note field can be empty and that's why I first check if the attribute is set.
The message is "note attribute cannot be blank"

2017-02-16 09:24 UTC, iivic commented on ecommerce/extensions/catalogue/tests/test_models.py
> +        voucher = factories.VoucherFactory(code='TESTVOUCHER')
No copy/paste leftovers.

2017-02-16 09:35 UTC, iivic commented
Ditto on the coupon factory. It will make testing easier.

2017-02-16 09:52 UTC, vkaracic commented on ecommerce/extensions/catalogue/models.py
> +        if hasattr(self.attr, 'note'):
I found why that is happening and a couple of ways to fix it, BUT I'm not telling :smiley: 
It's a fun problem to tinker about (at least it was fun for me) and since ``note`` validation is not of crucial importance right now, I'd like to see what you'll come up with. Hopefully by the end of this exercise you'll be a bit more familiar by the inner workings of Django and Oscar.
To be clear, the assignment is to find a way to call ``clean()`` in the ``save()`` method successfully.
Have fun! :)
If necessary, I can give hints in exchange for free candy.

2017-02-22 11:47 UTC, vkaracic commented on ecommerce/extensions/catalogue/utils.py
> +
I would instantiate CouponVouchers separately:
```
coupon_vouchers = CouponVouchers()
...
coupon_vouchers.save()
...
vouchers = create_vouchers(...)
coupon_vouchers.add(*vouchers)
```

2017-02-23 11:56 UTC, iivic commented
I removed the oscar clean method call before save because a lot of tests need to be rewritten (around 520 tests failed). Now just the note type s being tested. I also moved the coupon_vouchers from create_vouchers method since it makes no sense keeping it there.

2017-02-23 13:14 UTC, iivic commented
@marjev  @vkaracic  Please take a quick look before I merge this.

2017-02-27 14:32 UTC, vkaracic requested changes

2017-02-27 14:32 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        return self.get_response_json('GET', reverse('api:v2:coupons-detail', args=[coupon.id]))
Since this returns only details, is it possible to create the coupon directly without sending a POST request to the coupons endpoint and use that to get the details? That will save up some testing time.

2017-02-27 14:32 UTC, vkaracic commented on ecommerce/extensions/catalogue/tests/test_models.py
> +        self._create_coupon_product_with_note_attribute(note)
This method should return the coupon product back, so you can use that one instead of the making another db call below.

2017-02-27 15:03 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        return self.get_response_json('GET', reverse('api:v2:coupons-detail', args=[coupon.id]))
I guess a Product could be created but we want to test if the api endpoint works as expected because of the validation so not calling the api would make the tests useless. If you have a better solution feel free to advice me.

2017-02-28 09:29 UTC, iivic commented
@vkaracic Comment addressed the other needs further explanation.

2017-03-02 12:00 UTC, vkaracic approved these changes

2017-03-03 07:47 UTC, marjev requested changes

2017-03-03 07:47 UTC, marjev commented on ecommerce/extensions/catalogue/models.py
> -# noinspection PyUnresolvedReferences
Why is this being removed?

2017-03-03 07:47 UTC, marjev commented on ecommerce/extensions/catalogue/models.py
> +            pass
Instead of overriding `save`, can you use this:
https://github.com/django-oscar/django-oscar/blob/31ea8dcbcce4ccb6bcbdbb08c3fe9b01103fae2c/src/oscar/apps/catalogue/product_attributes.py#L36

If not, you can use:
https://docs.djangoproject.com/en/1.10/ref/signals/#pre-save

2017-03-03 07:47 UTC, marjev commented on ecommerce/extensions/catalogue/models.py
> -# noinspection PyUnresolvedReferences
Again, why exactly is this being removed?

2017-03-03 07:47 UTC, marjev commented on ecommerce/extensions/voucher/utils.py
> -def _create_new_voucher(code, coupon, end_datetime, name, offer, start_datetime, voucher_type):
Why remove `coupon`?

If you need to remove it, however, change the docstring.

2017-03-03 11:08 UTC, iivic commented on ecommerce/extensions/catalogue/models.py
> -# noinspection PyUnresolvedReferences
As far as I know this is PyCharm specific and I can't see it's use since we are disabling pylint where it's necessary.

2017-03-03 11:08 UTC, iivic commented on ecommerce/extensions/catalogue/models.py
> -# noinspection PyUnresolvedReferences
This statement was [redundant](https://github.com/edx/ecommerce/pull/1140/files/f4e3a67f16162b4dd834f860eb817889c17932a8#diff-115852c6fffaa39425a3d451b1b81285L1).

2017-03-03 11:08 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
> -def _create_new_voucher(code, coupon, end_datetime, name, offer, start_datetime, voucher_type):
I concluded that the coupon is not needed here since the functions name implies that only a voucher is created.  I moved the voucher adding to coupon_voucher into `create_coupon_product` function.
I will remove the docstring.

2017-03-03 11:08 UTC, iivic commented on ecommerce/extensions/catalogue/models.py
> +            pass
`validate_attributes` will make a bunch of tests fail (around 560) so I decided to validate the field directly instead of fixing every test.

Overriding the save method is consistent throughout the code. If you think pre-save is the way to go we should use it in the future as well.

2017-03-03 13:15 UTC, vkaracic requested changes

2017-03-03 13:15 UTC, vkaracic commented on ecommerce/extensions/catalogue/tests/test_models.py
> +from django.core.exceptions import ValidationError
Alphabetize please.

2017-03-06 07:49 UTC, marjev approved these changes

2017-03-06 11:52 UTC, vkaracic approved these changes

2017-03-06 11:54 UTC, merged