Updated to Django Oscar 1.2.2
openedx-unsupported/ecommerce pull request #1156
Opened 2017-02-15 00:14 UTC by clintonb

ECOM-7095

2017-02-16 04:24 UTC, clintonb commented
@edx/ecommerce please review

2017-02-16 04:41 UTC, clintonb commented
FYI @mjfrey note the removal of the custom messages.

2017-02-16 12:22 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> -        for msg in list(messages.get_messages(self.request)):
We need these messages. Why are they removed?

2017-02-16 14:50 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> -        for msg in list(messages.get_messages(self.request)):
* https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/basket/views.py#L302
* https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/basket/views.py#L384

2017-02-16 19:58 UTC, MatthewPiatetsky commented on .travis.yml
> -    firefox: latest
why remove this?

2017-02-16 19:59 UTC, clintonb commented on .travis.yml
> -    firefox: latest
See https://github.com/edx/ecommerce/pull/1146.

2017-02-16 20:13 UTC, MatthewPiatetsky commented on Makefile
> +	# Allow root for Docker
what does this mean?

2017-02-17 17:36 UTC, mjfrey requested changes
Can we also see this in a sandbox or anywhere we can run some tests?

2017-02-17 17:36 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> -class VoucherRemoveMessagesView(VoucherRemoveView):
Unless this is fixed in the latest Oscar we still need this as we will start getting Server errors in the case that triggers this.

2017-02-17 17:38 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> -class VoucherRemoveMessagesView(VoucherRemoveView):
Under what conditions do these errors manifest? Django itself supports string lookups. I've never seen these issues.

2017-02-17 17:40 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> -class VoucherRemoveMessagesView(VoucherRemoveView):
To reproduce:
1: Add item to basket, apply voucher.
2: Open second tab go to basket page.
3: First tab remove voucher.
4: Second tab remove voucher.
Server error will happen in Oscar.

2017-02-17 17:56 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> -class VoucherRemoveMessagesView(VoucherRemoveView):
Was an issue filed at https://github.com/django-oscar/django-oscar/?

2017-02-17 18:07 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> -class VoucherRemoveMessagesView(VoucherRemoveView):
Not that I am aware of.

2017-02-17 18:56 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> -class VoucherRemoveMessagesView(VoucherRemoveView):
https://github.com/django-oscar/django-oscar/pull/2241

2017-02-17 18:56 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> -class VoucherRemoveMessagesView(VoucherRemoveView):
I'll restore this view for now; although, I don't think we should support multi-tab use cases.

2017-02-17 18:57 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> -class VoucherRemoveMessagesView(VoucherRemoveView):
I agree, however we where getting Splunk alerts from this.

2017-02-17 19:58 UTC, clintonb commented
@mjfrey sandbox building. Any other feedback?

2017-02-17 20:05 UTC, mjfrey approved these changes

2017-02-17 20:35 UTC, merged