ENT-183: Update ecommerce enterprise entitlements to account for learner consent
openedx-unsupported/ecommerce pull request #1168
Opened 2017-02-20 09:17 UTC by saleem-latif

Hi @mattdrayer , @asadiqbal08 , @zubair-arbi 

Kindly take a look at this PR, I have added checks for verifying learner has consented to data sharing consent before applying the entitlements.

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +        site (django.contrib.sites.models.Site): Current site learner is facing.
site: (django.contrib.sites.Site) site instance

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +    Fetch learner entitlements.
Update text like:
```
Fetch enterprise learner entitlements according to the eligibility criterion of the related enterprise.
```

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +def fetch_learner_entitlements(site, learner_id):
fetch_enterprise_learner_entitlements(site, learner_id):

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +        >>> fetch_learner_entitlements(site, 2)
I believe one example should be enough as both example are similar.

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +                "requires_consent": True ,
nit: remove extra space before comma `,`

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +        entitlements = getattr(api, resource_url).get()
This APIcall will raise exceptions and since we are not catching it here in this method so we add a `Raises` section in the method docstring.

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +    the eligibility criterion for the provided learners from the Enterprise
nit:  `according to the eligibility criterion for the provided learners` since this method returns all entitlements of an enterprise (does not check the consent or other criterion) so the text should reflect that.

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/tests/mixins.py
> +                base_url=self.ENTERPRISE_LEARNER_URL.rstrip("/"), learner_id=learner_id,
nit: single quotes

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/tests/test_api.py
> +# from ecommerce.courses.tests.factories import CourseFactory
Please remove this commented line

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/tests/test_api.py
> +Catalog = get_model('catalogue', 'Catalog')
nit: add two lines before globals

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/tests/test_api.py
> +        # self.course = CourseFactory(id='edx/Demo_Course/DemoX')
nit: you  may want to remove this commented code

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/tests/test_entitlements.py
> +        self.mock_enterprise_learner_entitlements_api(entitlement_id=coupon.id)
remove this duplicate line

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/utils.py
> +def get_cache_key(**kwargs):
nice 👍

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/utils.py
> +    key = "_".join(["{}:{}".format(item, value) for item, value in kwargs.iteritems()])
nit: use single quote

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/utils.py
> +Utility functions for ecommerce.
I think we should move this utils file content to `ecommerce/core/utils.py`.

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +        learner_id (int): Primary key identifier for the enterprise customer learner.
nit: `enterprise customer learner` -> `enterprise learner`

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +    except (ConnectionError, SlumberBaseException, Timeout, KeyError, TypeError):
I think the above API call won't rise the exceptions `KeyError` and `TypeError`.

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +            user.username
imho, if we are fetching learner entitlements with their id `learner_id` then we should log that id here too instead of username.

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +            'Invalid structure for enterprise learner entitlements API response for the learner [%s]', user.username,
nit: `user.username` -> `learner_id`

2017-02-20 11:07 UTC, zubair-arbi commented on ecommerce/enterprise/entitlements.py
> +    try:
nit: add a new line above before the code de-dents.

2017-02-21 11:59 UTC, saleem-latif commented on ecommerce/enterprise/api.py
> +        entitlements = getattr(api, resource_url).get()
Done

2017-02-21 11:59 UTC, saleem-latif commented
@zubair-arbi I have incorporated your feedback, kindly take a look.

2017-02-21 13:07 UTC, mattdrayer commented
Excellent!  @haikuginger and @mjfrey/@vkaracic can you guys take a look at this one?

2017-02-21 14:10 UTC, vkaracic requested changes
I've done a code review, but I can't comment on the actual implementation as I'm not up to speed with the enterprise part and entitlements.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/entitlements.py
>      for entitlement in entitlements:
Should this be ``in entitlements['results']``?

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/core/utils.py
> +def get_cache_key(**kwargs):
Since this is the same function as here: https://github.com/edx/ecommerce/pull/1133/files/37015cfe8a0c57bd3fc3ff06c1eb4333f50b9c94#diff-35d681f57535c0ab31ab968e0bb486d9 same comments apply.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/api.py
> +        site (django.contrib.sites.Site): site instance.
Just ``site (Site): ..`` will suffice.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/api.py
> +        Timeout: requests exception "Timeout"
This section should describe when/why exceptions are raised.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/api.py
> +        user: (django.contrib.auth.User) django auth user
```
site (Site): ...
user (User): ...
```

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/api.py
> +        Timeout: requests exception "Timeout"
This section should describe when/why exceptions are raised.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/entitlements.py
> +            coupon_product = Product.objects.filter(product_class__name='Coupon').get(id=entitlement)
``id=entitlement['id']`` ?

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/tests/mixins.py
> +            uri='{base_url}/{learner_id}/entitlements/'.format(
You could just remove the slash here and they wouldn't need to call ``rstrip``.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/tests/mixins.py
> +            uri='{base_url}/{learner_id}/entitlements/'.format(
Same here.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/tests/test_api.py
> +@ddt.ddt
You're not using ``ddt`` in the unit tests here.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/tests/test_api.py
> +        self._assert_num_requests(2)
The comment says ``once`` yet the parameter is ``2``, which is confusing.

2017-02-21 14:10 UTC, vkaracic commented on ecommerce/enterprise/tests/test_api.py
> +        self._assert_num_requests(1)
In this, and the test below, you could implement ``expected_request_count`` that you have in ecommerce/enterprise/tests/test_entitlements.py.

2017-02-22 04:33 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
>      for entitlement in entitlements:
@vkaracic [get_course_entitlements_for_learner](https://github.com/edx/ecommerce/pull/1168/files#diff-50449a66b32057163f5619acfe7bc17eR134) is updated in this PR, it now returns a list of entitlement ids.

2017-02-22 04:33 UTC, saleem-latif commented on ecommerce/enterprise/entitlements.py
> +            coupon_product = Product.objects.filter(product_class__name='Coupon').get(id=entitlement)
@vkaracic [get_course_entitlements_for_learner](https://github.com/edx/ecommerce/pull/1168/files#diff-50449a66b32057163f5619acfe7bc17eR134) is updated in this PR, it now returns a list of entitlement ids.

2017-02-22 05:13 UTC, saleem-latif commented on ecommerce/core/utils.py
> +def get_cache_key(**kwargs):
Done

2017-02-22 07:18 UTC, saleem-latif commented
@vkaracic I have incorporated your feedback, kindly take another look

2017-02-22 09:29 UTC, zubair-arbi approved these changes
LGTM 👍

2017-02-22 10:08 UTC, vkaracic commented on ecommerce/enterprise/entitlements.py
> +            coupon_product = Product.objects.filter(product_class__name='Coupon').get(id=entitlement)
Is it of type integer? Because the logger below is expecting a string ``%s``.

2017-02-22 10:12 UTC, vkaracic commented on ecommerce/enterprise/tests/mixins.py
> +                httpretty.Response(body='{}', content_type='application/json', status=500)
You don't need this to return a 500 status response. Just use ``status=500`` as a parameter for ``register_uri``.

2017-02-22 10:15 UTC, vkaracic approved these changes
One nitpick, otherwise looks good.

2017-02-22 13:12 UTC, saleem-latif commented
going ahead with merge now. PR has been verified on sandbox.

2017-02-22 13:13 UTC, merged

2017-02-22 16:07 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        code = FuzzyText().fuzz().upper()
Why were all of these upper-cased? The system should be case-insensitive.

2017-02-23 05:00 UTC, saleem-latif commented on ecommerce/coupons/tests/test_views.py
> +        code = FuzzyText().fuzz().upper()
I had to update this as tests were failing on my system, `code` coming from `FuzzyText().fuzz()` was mixed case and on database it was stored as uppercased. 
Test was failing because, for some reason, database lookup for voucher with mixed case code coming from `FuzzyText().fuzz()` was raising NotFound error.

2017-02-23 09:00 UTC, vkaracic commented on ecommerce/coupons/tests/test_views.py
> +        code = FuzzyText().fuzz().upper()
That shouldn't matter.
```
In [11]: Voucher.objects.get(code='AHCZG3IGQ7HMHSWA')
Out[11]: <Voucher: Test>

In [12]: Voucher.objects.get(code='ahczg3igq7hmhswa')
Out[12]: <Voucher: Test>
```

2017-02-24 10:34 UTC, saleem-latif commented on ecommerce/coupons/tests/test_views.py
> +        code = FuzzyText().fuzz().upper()
@vkaracic , @clintonb Seems like it only happened on my devstack, I am reverting these changes in https://github.com/edx/ecommerce/pull/1133