Option to activate/deactivate enrollment codes
openedx-unsupported/ecommerce pull request #1170
Opened 2017-02-23 13:41 UTC by vkaracic

This is a different version of https://github.com/edx/ecommerce/pull/1151. Here ``Product.expires`` was used to indicate if an enrollment code is active or inactive.

@clintonb is this what you suggested in that other PR? Another thing that needs to be addressed here is when the verification is closed for a seat, i.e. the seat product is set to be expired, the accompanying enrollment code should be disabled as well.

2017-02-23 13:41 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1170&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-02-24 05:56 UTC, clintonb reviewed
Yes, this is more inline with what I was thinking.

2017-02-24 05:56 UTC, clintonb commented on ecommerce/courses/models.py
> +            if enrollment_code.expires is None or (enrollment_code.expires and enrollment_code.expires > now()):
Use the `Selector` and strategy. See https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/api/serializers.py#L192-L194.

2017-02-24 05:56 UTC, clintonb commented on ecommerce/courses/models.py
> +            expires (Datetime): Date when the enrollment code expires.
`datetime` (uncapitalized)

2017-02-24 14:41 UTC, vkaracic commented
In that case I believe this is ready for reviews.

2017-02-27 07:06 UTC, marjev approved these changes

2017-02-27 08:41 UTC, iivic approved these changes
LGTM. Just one question.

2017-02-27 08:41 UTC, iivic commented on ecommerce/templates/courses/course_app.html
> +        window.bulkEnrollmentCodesEnabled = {% if bulk_enrollment_codes_enabled %}true{% else %}false{% endif %};
Why did you include this in the template?

2017-02-27 08:43 UTC, vkaracic commented on ecommerce/templates/courses/course_app.html
> +        window.bulkEnrollmentCodesEnabled = {% if bulk_enrollment_codes_enabled %}true{% else %}false{% endif %};
To know if bulk enrollment codes are enabled or disabled.

2017-02-28 11:17 UTC, vkaracic commented
Guys, can you please review the last commit too?

2017-02-28 11:37 UTC, vkaracic commented
@clintonb regarding the last commit here, you've said that you change the seat's expires date to disable their purchases, I've updated the ``Product.save`` method to deactivate the seat's enrollment code as well in that case. Other than that case, how often and how are seat expires dates changed? So that I can account for any additional cases as well.

2017-02-28 13:49 UTC, clintonb commented
I'm on vacation. See the Course Administration Tool, and its code, for more information on how we handle this with courses.

Clinton Blackburn




On Tue, Feb 28, 2017 at 6:37 AM -0500, "Vedran Karačić" <notifications@github.com> wrote:












@clintonb regarding the last commit here, you've said that you change the seat's expires date to disable their purchases, I've updated the Product.save method to deactivate the seat's enrollment code as well in that case. Other than that case, how often and how are seat expires dates changed? So that I can account for any additional cases as well.



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-03-01 07:48 UTC, marjev requested changes

2017-03-01 07:48 UTC, marjev commented on ecommerce/extensions/catalogue/models.py
> +        if self.get_product_class().name == SEAT_PRODUCT_CLASS_NAME and (self.expires != self.__original_expires):
`if self.is_seat_product`

2017-03-01 07:48 UTC, marjev commented on ecommerce/extensions/catalogue/models.py
> +        self.__original_expires = self.expires
Can we do this using `post_init` signal?
Code example: https://github.com/edx/edx-platform/blob/master/cms/djangoapps/course_creators/models.py#L52

2017-03-01 07:48 UTC, marjev commented on ecommerce/extensions/catalogue/models.py
> +        self.__original_expires = self.expires
This looks to be the same thing that's done `post_init` so perhaps `post_save` should point to the same callback, if you decide to use signals.

2017-03-01 07:48 UTC, marjev commented on ecommerce/extensions/catalogue/models.py
> +                enrollment_code.save()
Again, if you decide to use Django signals, this can be done in the `pre_save` callback.

2017-03-01 09:39 UTC, vkaracic commented
@marjev I've implemented signals, see if that's what you were thinking.

2017-03-01 10:44 UTC, marjev commented
If it works, yeah, that's it. LGTM.

2017-03-01 10:44 UTC, marjev approved these changes

2017-03-02 09:37 UTC, iivic approved these changes

2017-03-02 10:05 UTC, merged