ECOM-7349 Learners cannot get enrollment status on Ecommerce SingleBasketItemView
openedx-unsupported/ecommerce pull request #1178
Opened 2017-03-01 10:08 UTC by Ayub-Khan

**ECOM-7349** 
Learners cannot get enrollment status on Ecommerce SingleBasketItemView because of user oauth token expiration. 
Updated the Oauth access token for enrolment check on basket page from learner Oauth token to Service User Oauth token.

2017-03-01 12:54 UTC, Ayub-Khan commented
jenkins run bokchoy

2017-03-01 13:36 UTC, mjfrey requested changes

2017-03-01 13:36 UTC, mjfrey commented on ecommerce/core/models.py
> +                oauth_access_token=request.site.siteconfiguration.access_token,
While we are at it, we should probably switch this to use JWT.

2017-03-01 13:50 UTC, Ayub-Khan commented on ecommerce/core/models.py
> +                oauth_access_token=request.site.siteconfiguration.access_token,
@mjfrey What about changing in whole class and removing access_token [property](https://github.com/edx/ecommerce/blob/74a41b365adf7b7385d09c8bf325c5b87226d369/ecommerce/core/models.py#L401)?

2017-03-01 13:52 UTC, mjfrey commented on ecommerce/core/models.py
> +                oauth_access_token=request.site.siteconfiguration.access_token,
yes.

2017-03-01 14:47 UTC, mjfrey commented on ecommerce/core/models.py
> +                oauth_access_token=request.site.siteconfiguration.access_token,
actually you might not want to change the property on the User model, but rather just change this method.  Not sure what else relies on getting the User token.

2017-03-01 15:10 UTC, schenedx requested changes
I believe I wrote in the ticket, we should just switch the auth to use JWT

2017-03-01 16:53 UTC, Ayub-Khan commented
@schenedx so we should not catch the possible exception or change the other calls and let them fail?

2017-03-01 17:09 UTC, schenedx commented
@Ayub-Khan That's not what I meant. Your change on catching exception is good.
I meant we should use JWT instead of using oauth token. Rest you should update as you see fit. Sorry about the confusion.

2017-03-01 17:42 UTC, Ayub-Khan commented on ecommerce/core/models.py
> +                oauth_access_token=request.site.siteconfiguration.access_token,
@mjfrey  already changed it .

2017-03-01 17:43 UTC, Ayub-Khan commented
@schenedx still confused. am i doing it the wrong way ?. i used siteconfiguration's jwt tokken .

2017-03-01 17:45 UTC, mjfrey commented on ecommerce/core/models.py
> +                oauth_access_token=request.site.siteconfiguration.access_token,
@Ayub-Khan to use JWT you need.
jwt=request.site.siteconfiguration.access_token
that is still using oauth.

2017-03-01 18:26 UTC, Ayub-Khan commented
@mjfrey @schenedx sorry my bad updated. should i remove other changes or keep them.

2017-03-01 18:35 UTC, schenedx commented
@Ayub-Khan I think you can have other changes to stay. However, I am wondering how you tested this PR? Where you able to run these changes through a sandbox? Or your local machine? And ensure the user sees the basket page no problem?

2017-03-02 15:01 UTC, schenedx approved these changes
👍 Code change here LGTM.
Please make sure it is properly tested

2017-03-02 15:17 UTC, mjfrey approved these changes

2017-03-02 19:03 UTC, schenedx commented
@Ayub-Khan We are merging this PR and let it go to stage. We will test this in stage. The sandbox was too difficult to figure out.

2017-03-02 19:03 UTC, merged

2017-03-02 19:34 UTC, schenedx commented
@Ayub-Khan This PR did not solve the problem in stage. It may have made the issue worse in stage. I will create a PR to revert both this one and the commit in https://github.com/edx/ecommerce/pull/1137