ENT-201 use catalog contains endpoint for varifying the course seats against …
openedx-unsupported/ecommerce pull request #1195
Opened 2017-03-09 08:18 UTC by zubair-arbi

…a course catalog range
@saleem-latif @asadiqbal08 @mattdrayer 

Previously we were using two API calls for checking if a course run exists for a catalog by first retrieving the catalog and then using the course_runs contains endpoint for the provided course run, from discovery service.

Now we are using the updated catalog contains endpoint which tells us if a course run is available in its query.

**Depends on:** [add support for course run key in catalog contains endpoint](https://github.com/edx/course-discovery/pull/721)

2017-03-09 09:22 UTC, saleem-latif requested changes
Overall looks good, however, I have added a couple of comments.

2017-03-09 09:22 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +    def catalog_contains_product(self, product):
I think it would be best to define a helper method in `ecommerce/coupons/utils.py` that makes network calls to discovery API, and use that method here. This way will have all procedures that perform API calls in a single place.
Name of the utility function can be something like `catalog_contains_course(self, course)` or something better.

2017-03-09 09:22 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +    def catalog_contains_product(self, product):
Also, in my opinion I think it would be more readable if `catalog_contains_product ` here returns a boolean if it is possible. and we changes function signature accordingly. thoughts ?

2017-03-09 09:22 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +            site_domain=request.site.domain,
It would be good to also add `resource` key-value pair in cache key to make sure cache key does not collide with any other.

2017-03-09 09:22 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +                response = course_catalog_api_client.catalogs(self.course_catalog).contains.get(
nit: please add a comment here explaining what would be the final URL for the API call, may be something like

```
# GET: /api/v1/catalogs/{catalog_id}/contains?course_run_ids={course_run_id}
```

2017-03-09 10:19 UTC, zubair-arbi commented on ecommerce/extensions/offer/models.py
> +            site_domain=request.site.domain,
added

2017-03-09 10:23 UTC, zubair-arbi commented on ecommerce/extensions/offer/models.py
> +    def catalog_contains_product(self, product):
@saleem-latif @mattdrayer I would recommend a separate story for refactoring/moving the range model API calls to the `ecommerce/coupons/utils.py` file as we have to update both this method and `run_catalog_query` method. Also we have to add separate tests for the utils too. The scope of current story already seems a bit extended and its involves working with 3 repos.

2017-03-09 18:32 UTC, zubair-arbi commented
@mattdrayer @mjfrey please review.

2017-03-10 03:11 UTC, mattdrayer commented on ecommerce/enterprise/entitlements.py
> +    return is_course_in_catalog
Looks like this can be moved to the `try` block:
```
try: 
    return response['courses'][course_id]
except KeyError:
    return False
```

2017-03-10 03:12 UTC, mattdrayer commented
One change, otherwise 👍

2017-03-10 03:14 UTC, mattdrayer commented on ecommerce/extensions/offer/models.py
> +    def catalog_contains_product(self, product):
I'm okay with logging (another) follow-up story -- we've put in a fair amount of effort on this job and we have some higher priorities that we'll need to address next.

2017-03-10 07:37 UTC, zubair-arbi commented on ecommerce/extensions/offer/models.py
> +    def catalog_contains_product(self, product):
I have logged a ticket [ENT-257](https://openedx.atlassian.net/browse/ENT-257) to address this feedback.

2017-03-10 10:09 UTC, saleem-latif approved these changes

2017-03-10 10:09 UTC, saleem-latif commented
@zubair-arbi commits need to be squashed otherwise LGTM 👍

2017-03-13 02:12 UTC, mattdrayer commented
@vkaracic and/or @marjev may want to take a quick look at this one.

2017-03-13 08:24 UTC, marjev commented on ecommerce/courses/tests/mixins.py
> +        course_run_ids = course_run_ids or []
Can you set `[]` as the default value in line 42? That way you won't need this line.

2017-03-13 08:24 UTC, marjev commented on ecommerce/courses/tests/mixins.py
> +            courses.update({course_run_id: True})
You can do this during the initialization like this:
`courses = {course_run_id: True for course_run_id in course_run_ids}`

2017-03-13 08:24 UTC, marjev commented on ecommerce/courses/tests/mixins.py
> +            u'courses': courses
You can import `unicode_literals` like this: https://github.com/edx/ecommerce/blob/master/ecommerce/coupons/views.py#L1

Then, you won't need to mark the string as Unicode.

2017-03-13 10:22 UTC, zubair-arbi commented on ecommerce/courses/tests/mixins.py
> +        course_run_ids = course_run_ids or []
@marjev This would result in pylint error ["dangerous-default-value"](http://stackoverflow.com/questions/26320899/why-is-the-empty-dictionary-a-dangerous-default-value-in-python):
```ecommerce@precise64:~/ecommerce$ make quality
pep8 --config=.pep8 ecommerce e2e
pylint --rcfile=pylintrc ecommerce e2e
************* Module ecommerce.courses.tests.mixins
W: 42, 4: Dangerous default value [] as argument (dangerous-default-value)
```

2017-03-13 10:29 UTC, zubair-arbi commented
@marjev I have addressed your feedback, please have another look.

2017-03-13 10:54 UTC, marjev approved these changes
LGTM

2017-03-13 14:53 UTC, clintonb submitted a review, later dismissed
If this feature relies on the Catalog Service, please add a feature flag to disable it until the Catalog Service is released.

2017-03-14 07:43 UTC, zubair-arbi commented
@clintonb we already have a waffle switch `enable_enterprise_on_runtime` which [enables enterprise functionality in Ecom](https://github.com/edx/ecommerce/blob/master/ecommerce/enterprise/entitlements.py#L42) and we can use this feature flag instead of adding a new one. 
@mattdrayer what is your suggestion?

2017-03-14 13:32 UTC, mattdrayer commented
We're sort of in moot-point territory now because the updated Catalog service has already deployed.  However, for this particular PR, I think I would have recommended that we avoid binding the catalog query logic to the enterprise feature flag.  That flag is for enterprise features, and while they might *use* the updated query logic, the actual code was more of a core ecommerce change.  So a new feature flag probably should have been introduced if we were expecting to merge both PRs to their respective masters and subsequently manage the releases.

TBH I much prefer simply merging+deploying the updated Catalog service, ensuring no rollback was required, and then merging+deploying the updated Ecommerce service at a later point in time (which is what we're doing now).  It's easier to manage and we don't have to worry about juggling feature flags.

2017-03-15 07:46 UTC, merged