ECOM-7410 Update clean_field_value to remove HTML from strings
openedx-unsupported/ecommerce pull request #1203
Opened 2017-03-14 13:39 UTC by Ayub-Khan

**ECOM-7410**

**Description :**
Students were unable to checkout using cybersource when product title had HTML in it. Updated the clean method to remove HTML from those. 

**Testing :**
Unable to test it on local because can not redirect to cybersrouce.
Tested the regex '[\^:"\']?(&\w+;)?(</*\w+>)?' on [online python regex tester](http://pythex.org/)

2017-03-14 13:43 UTC, clintonb requested changes
We should fix this at the source—CAT. Don't allow courses to be created with invalid text.

Also, please include the ticket number on the last line of your commit message.

2017-03-15 05:51 UTC, attiyaIshaque requested changes
Code changes look good. Could you add a regression test for this?

2017-03-15 14:36 UTC, clintonb requested changes
This needs tests.

2017-03-15 14:36 UTC, clintonb commented on ecommerce/static/js/utils/validation_patterns.js
> +            productName: gettext('The product name is invalid.')
Provide helpful text that explains what is considered valid. Also, run `make fake_translations` to update the translations.

2017-03-15 20:24 UTC, Ayub-Khan commented
@clintonb @attiyaIshaque   updated

2017-03-16 00:19 UTC, clintonb approved these changes
Remember to squash your commits, and move the ticket number to the last line of your commit message.

2017-03-16 00:19 UTC, clintonb commented on ecommerce/static/js/utils/validation_patterns.js
> +            productName: gettext('The product name contains HTML in it.')
The product name cannot contain HTML.

2017-03-16 06:08 UTC, attiyaIshaque approved these changes
Once commits squashed 👍

2017-03-16 10:45 UTC, merged