WIP
openedx-unsupported/ecommerce pull request #1205
Opened 2017-03-16 13:42 UTC by vkaracic

2017-03-16 13:43 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1205&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-16 13:43 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/sdn.py
> +        return Response({'hits': 1})
Changed to always return a hit and logout for debugging purposes.

2017-03-16 13:43 UTC, vkaracic commented on ecommerce/static/js/pages/sdn_failure_page.js
> +            function delete_cookie( name, path, domain ) {
Should probably remove this and do this in basket_page.js

2017-03-20 13:24 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/sdn.py
> +                    logout(request)
Not sure if this one is still necessary.

2017-03-20 13:43 UTC, clintonb requested changes
Simplify.

2017-03-20 13:43 UTC, clintonb commented on e2e/mixins.py
> +from e2e.config import (BASIC_AUTH_PASSWORD, BASIC_AUTH_USERNAME, ECOMMERCE_API_URL, ECOMMERCE_URL_ROOT, LMS_AUTO_AUTH,
Looks like you ran `isort` on everything, and we never configured `multi_line_output`. Please set `multi_line_output=3` in `.isort.cfg` and re-run the command to fix these. See https://github.com/timothycrosley/isort#multi-line-output-modes for details.

2017-03-20 13:43 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
> +    def sdn_mock(self, hits):
`mock_sdnclient_search`

2017-03-20 13:43 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
>              with mock.patch.object(User, 'deactivate_account') as deactivate_account_mock:
This code will be cleaner if this is moved to its own mock method.

2017-03-20 13:43 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
>                  deactivate_account_mock.return_value = True
These can be one-liners:

```python
mock.patch.object(User, 'deactivate_account', return_value=True) 
```

2017-03-20 13:43 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> -from paypalrestsdk import WebProfile    # pylint: disable=ungrouped-imports
You're touching *way* more code than you should be. Please revert all changes that are not actually needed for SDN/logout. In the future, if you need to run `isort, run it against the specific directory/files you are editing.

2017-03-20 13:43 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_sdn_view.py
> +    def setUp(self):
Remove. There is no need to have this here if you aren't actually overriding the default.

2017-03-20 13:43 UTC, clintonb commented on ecommerce/static/js/apps/sdn_failure_app.js
> +require([
Yeah...this is overkill.

2017-03-20 13:43 UTC, clintonb commented on ecommerce/templates/oscar/checkout/sdn_logout.html
> +{% extends 'edx/base.html' %}
You've made this a bit more complicated than it needs to be. Keep the existing page. The only change necessary is to load the LMS logout page in an invisible iframe. No need for JS at all since there is no redirection taking place.

2017-03-20 13:43 UTC, clintonb commented on ecommerce/extensions/api/v2/views/sdn.py
> +                    logout(request)
Keep it. If the account is deactivated, you don't want the user believing they can perform actions they cannot.

2017-03-20 13:57 UTC, vkaracic commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> -from paypalrestsdk import WebProfile    # pylint: disable=ungrouped-imports
But technically all these changes are correct.

2017-03-20 14:07 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/sdn.py
> +                    logout(request)
Yes, but shouldn't the iframe take care of logging the user out?

2017-03-20 14:27 UTC, vkaracic commented on ecommerce/templates/oscar/checkout/sdn_logout.html
> +{% extends 'edx/base.html' %}
If you mean adding something like:
```
<div id="iframeContainer" style="visibility: hidden">
  <iframe src="http://localhost:8000/logout"></iframe>
</div>
```
in the SDN failure template - that doesn't work. That code redirects the user the dashboard and if I add ``sandbox="allow-forms allow-same-origin allow-scripts" `` to the iframe it doesn't redirect (it load the iframe just fine) but does not log out the user, at least it doesn't work for me locally.

2017-03-20 16:14 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> -from paypalrestsdk import WebProfile    # pylint: disable=ungrouped-imports
They may be technically correct but they are out-of-scope for this PR. It's unnecessary noise. If you want to clean the entire repo, do it in another PR.

2017-03-28 08:18 UTC, vkaracic commented
@clintonb ready for a second review!

2017-03-28 12:51 UTC, clintonb reviewed
I'd like more info on why a simple iframe doesn't work.

2017-03-28 12:51 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
> +                self.assertTrue(sdn_validator_mock.called)
You're doing far too much in this method. Break this up into two mock methods. If the assertion is really important, it too can be a method.

2017-03-28 12:51 UTC, clintonb commented on ecommerce/templates/oscar/checkout/sdn_logout.html
> +{% extends 'edx/base.html' %}
Have you looked at the logs to determine why the client is redirected to the dashboard rather than logged out?

2017-03-28 15:43 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
> +                self.assertTrue(sdn_validator_mock.called)
Sorry, can you elaborate a bit more? I've done this to somewhat DRY the lower two test cases and if I'm going to create mock methods for each individual mock and call them in both tests it kinda beats that purpose.

2017-03-29 08:48 UTC, vkaracic commented on ecommerce/templates/oscar/checkout/sdn_logout.html
> +{% extends 'edx/base.html' %}
Some update: The redirect to the dashboard happens because of this:
https://github.com/edx/edx-platform/blob/master/lms/templates/main.html#L45-L52
But omitting the ``allow-top-navigation`` from the iframe sandbox flags prevents that redirect, hence the second scenario that I mentioned above.
Still trying to figure out why it's not logging the user out.

2017-03-29 12:31 UTC, clintonb commented on ecommerce/templates/oscar/checkout/sdn_logout.html
> +{% extends 'edx/base.html' %}
Simple solution: update the logout view, setting `allow_iframing` to `True`.

2017-04-06 08:05 UTC, vkaracic commented
@clintonb I believe I have addressed your comments. Also I've verified that this works locally and on a sandbox.

2017-04-07 12:54 UTC, clintonb approved these changes

2017-04-07 12:54 UTC, clintonb commented on ecommerce/templates/oscar/checkout/sdn_failure.html
> +  <div id="iframeContainer" style="visibility: hidden">
This `<div>` is unnecessary. Apply the style to the `<iframe>`.

2017-04-07 12:54 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_sdn_view.py
> +class SDNViewsTests(TestCase):
The filename should be `test_sdn.py`. This class name should be `SDNFailureTests`.

2017-04-07 12:54 UTC, clintonb commented on ecommerce/extensions/payment/tests/views/test_sdn_view.py
> +        logout_url = self.site.siteconfiguration.build_lms_url('/logout')
No need for the slash.

2017-04-07 12:54 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
> -        """Verify the endpoint returns the number of hits SDN check made."""
Why did any of this need to be touched?

2017-04-07 13:14 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_sdn.py
> -        """Verify the endpoint returns the number of hits SDN check made."""
Scoped it in by mistake.

2017-04-10 07:28 UTC, vkaracic commented
@edx/helio somebody else please review.

2017-04-10 07:44 UTC, iivic commented on ecommerce/templates/oscar/checkout/sdn_failure.html
> +  <iframe style="visibility: hidden" sandbox="allow-forms allow-same-origin allow-scripts" src="{{ logout_url }}"></iframe>
Why inline style?

2017-04-10 10:56 UTC, vkaracic commented on ecommerce/templates/oscar/checkout/sdn_failure.html
> +  <iframe style="visibility: hidden" sandbox="allow-forms allow-same-origin allow-scripts" src="{{ logout_url }}"></iframe>
Because it only needs to be hidden from the user, it doesn't and never will require any styling other than that, so there is no need to include id/class and SASS/CSS changes for this.

2017-04-10 10:59 UTC, iivic approved these changes

2017-04-10 13:19 UTC, merged