Fixing a11y issues on new basket page
openedx-unsupported/ecommerce pull request #1206
Opened 2017-03-16 15:18 UTC by iivic

@cptvitamin You can check which ticket is done and for those who are not done properly please leave a comment.
@vkaracic Please review from a more technical point.

The following tickets have been addressed:
- [ ] ECOM-7506
- [ ] ECOM-7515
- [ ] ECOM-7514
- [ ] ECOM-7513
- [ ] ECOM-7521
- [ ] ECOM-7509

2017-03-16 15:18 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1206&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-16 19:33 UTC, cptvitamin requested changes
Some small requests and modifications based on implementation.

2017-03-16 19:33 UTC, cptvitamin commented on ecommerce/templates/edx/partials/_base_navbar.html
> +<header class="navbar navbar-default" aria-label="Account">
@iivic The aria-label for this element doesn't quite make sense anymore. Let's make it "Shopping Cart" since it is the header for the shopping cart page.

2017-03-16 19:33 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                        <a href="#payment-information" id="payment-method-image" aria-label="{% trans "Pay with a Credit Card" %}" role="button"><img aria-hidden="true" src="/static/images/credit_car
Let's convert the aria-label to a title attribute.  title reaches a broader audience and has better implementation support.  Screen readers treat both the same on button elements (or links with role=button)

Let's remove the aria-hidden=true on the image here (its an invalid attr and will cause test failures).  The proper way to hide an image is with an empty alt attribute, which we now have.  Alternatively, you could use role=presentation, but its redundant and not necessary.

2017-03-16 19:33 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                        <button aria-label="{% trans "Pay with PayPal" %}"
let's remove the aria-label all together since we have a title attr on line 119 below.  This will make it consistent with the CreditCard button.

2017-03-16 19:33 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                            <option id=year-label>{% trans "Year" %}</option>
nit, can you quote this id value?

2017-03-17 09:15 UTC, iivic commented on ecommerce/templates/edx/partials/_base_navbar.html
> +<header class="navbar navbar-default" aria-label="Account">
This header is used on other pages as well so "Shopping Cart" will not describe it accurately. There will maybe be more pages in the future so a more generic name or leaving it as is would be better in this case.

2017-03-17 09:26 UTC, vkaracic commented on ecommerce/templates/edx/partials/_base_navbar.html
> +<header class="navbar navbar-default" aria-label="Account">
I think the label is irrelevant on this element. ``Account`` label should be added where the account is displayed, not the whole header.

2017-03-17 09:26 UTC, vkaracic commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                        aria-labelledby="month-label expiration-label">
Is ``aria-labelledby="month-label expiration-label"`` a combination of the two labels?

2017-03-17 09:31 UTC, iivic commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +                        aria-labelledby="month-label expiration-label">
According to [this](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) it is.

2017-03-21 12:41 UTC, iivic commented
@cptvitamin You can review the latest commit
- [ ] ECOM-7508
- [ ] ECOM-7517

2017-03-21 20:33 UTC, cptvitamin commented
I'm not seeing ```<section class="footer-main container">``` converted to a footer element

2017-03-22 11:00 UTC, iivic commented
@cptvitamin  I can't locate the mentioned section. 
For more info look at the comment section https://openedx.atlassian.net/browse/ECOM-7518

2017-03-22 18:15 UTC, cptvitamin requested changes
Just a small change WRT alt and then 👍

2017-03-22 18:15 UTC, cptvitamin commented on ecommerce/templates/coupons/coupon_app.html
> +                    <img class="navbar-brand-logo" alt="Institution logo" src="{% static 'images/default-logo.png' %}"/>
@iivic the alt for the log should be dynamic alt="{{ platform_name }} logo">

2017-03-22 18:15 UTC, cptvitamin commented on ecommerce/templates/courses/course_app.html
> +                    <img class="navbar-brand-logo" alt="Institution logo" src="{% static 'images/default-logo.png' %}"/>
@iivic the alt for the log should be dynamic alt="{{ platform_name }} logo">

2017-03-23 16:13 UTC, closed without merging

2017-03-23 16:15 UTC, iivic commented
Merged into https://github.com/edx/ecommerce/pull/1213.