[WIP] [ECOM-7520] Fix low color contrast
openedx-unsupported/ecommerce pull request #1207
Opened 2017-03-17 12:03 UTC by marjev

### JIRA Ticket:
[[ECOM-7520] Low Color Contrast](https://openedx.atlassian.net/browse/ECOM-7520)
### Screenshots:
Checkout page
![screencapture-localhost-8000-course_modes-choose-course-v1-edx-course-100-1489675121757](https://cloud.githubusercontent.com/assets/6833568/24042192/2fd19712-0b11-11e7-9b7b-3b4d6325e271.png)

### Changes:

1. Background color of both `Apply` and `Place Order` buttons: from [](https://placehold.it/15/000000/000000?text=+) `#000000` to ![](https://placehold.it/15/065683/000000?text=+) `#065683`
2. Hover state background color of both `Apply` and `Place Order` buttons: from [](https://placehold.it/15/337ab7/000000?text=+) `#337ab7` to ![](https://placehold.it/15/0075b4/000000?text=+) `#0075b4`

2017-03-17 12:04 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1207&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-21 19:59 UTC, cptvitamin requested changes
Just one small comment and then this is good to go.

2017-03-21 19:59 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +    <div role="region" aria-labelledby="summary-region">
@marjev can we add the aria-live=polite back to this grouping.  This information is subject to change if the user applies a coupon, and the SR user needs to know what the new values are.  The aria-live will do this.

2017-03-22 07:27 UTC, marjev commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +    <div role="region" aria-labelledby="summary-region">
Comment addressed.

2017-03-22 11:32 UTC, mjfrey approved these changes

2017-03-22 18:02 UTC, cptvitamin approved these changes

2017-03-22 18:02 UTC, cptvitamin commented
👍  nice work. thanks for powering through these.

2017-03-23 07:56 UTC, merged