[ENT-235] Ask for consent on manual code entry
openedx-unsupported/ecommerce pull request #1208
Opened 2017-03-18 00:58 UTC by haikuginger

**Description:** This pull request ensures that when a coupon code linked to an Enterprise Customer is entered manually in the cart, consent is obtained prior to enrollment taking effect.

**JIRA:** [ENT-235](https://openedx.atlassian.net/browse/ENT-235)

**Dependencies:** Full behavior depends on edx/edx-enterprise#68

**Merge deadline:** 27 March 2017

**Installation instructions:** 

Requires a fully-configured E-Commerce installation. Caveats include:

- A commerce configuration must be set up in LMS pointing to the Ecommerce instance
- `ecommerce_worker` must exist be a staff user
- `enterprise_worker` must exist and be a staff user
- In a devstack, the E-commerce config is broken by default. Specifically, in the `JWT_AUTH` key, the `JWT_ISSUERS key must be a list of objects, rather than a list of strings:

    ```yaml
    JWT_AUTH:
        JWT_ISSUERS:
            - AUDIENCE: lms-key
              ISSUER: http://127.0.0.1:8000/oauth2
              SECRET_KEY: lms-secret
            - AUDIENCE: lms-key
              ISSUER: ecommerce_worker
              SECRET_KEY: lms-secret
    ```
- The OAuth client for ecommerce must be assigned one of `ecommerce_worker` and `enterprise_worker` as the linked user.

Additional configuration:

- Use the branch of edx-platform referenced in [this pull request](https://github.com/edx/edx-platform/pull/14708), as it's linked to the proper branch of `edx-enterprise`.
- Enterprise customer with consent enabled and required on enrollment
- Course discovery API populated with course metadata, and pushed to ecommerce
- Premium course mode created in E-commerce for demo course
- Coupon created and linked to that enterprise customer and course
- After the fact, entitlement added to the enterprise customer for that coupon

**Testing instructions:**

1. In ecommerce, download and open the coupon report for the above created coupon
2. Create a new LMS user account and activate it (required)
3. Browse to the course page for the demo course you made a premium mode for in Enterprise
4. Click Enroll.
5. Select the premium course mode
6. Observe that you're at a checkout page
7. Enter the coupon code from the report you downloaded directly.
8. Observe that you're taken to a consent prompt, without the coupon immediately applied.
9. Observe that if you decline consent, you're returned to the checkout page, and an error message appears.
10. Re-enter the code, and this time, consent to data sharing.
11. Observe that you're immediately enrolled in the course in the premium mode and taken to your Dashboard.
12. Log in with a superuser and, in the Manage Learners pane for your Enterprise Customer, observe that the new user you created is now a linked Enterprise Learner.

2017-03-18 00:59 UTC, edx-webhook commented
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1208&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-20 13:17 UTC, e-kolpakov commented
@haikuginger I might need a bit more detailed setup instructions - LMS logs show 

    "GET /enterprise/api/v1/enterprise-customer/ HTTP/1.1" 401 26

and ecommerce coupon creation page does not display any values for Enterprise Customer dropdown.

This probably started happening after I updated JWT_AUTH config in ecommerce.

2017-03-20 13:45 UTC, haikuginger commented
@e-kolpakov, is the ecommerce OAuth client configured to use either the `ecommerce_worker` or `enterprise_worker` user, and is that user marked as staff?

2017-03-20 15:37 UTC, e-kolpakov commented
@haikuginger Yes, with `ecommerce_worker`. It used to be configured to use `staff`, but when it didn't work for  the first time I went there and changed it. Didin't have much effect though.

2017-03-20 15:45 UTC, haikuginger commented
@e-kolpakov, try quitting and relaunching the ecommerce app - I found that it keeps using an old token for a while unless you restart it, so it might still be trying to auth as `staff`.

2017-03-20 15:53 UTC, e-kolpakov commented
@haikuginger I'm not 100% sure, but I believe that was the first thing I've done after updating the setting. I'll check it again tomorrow.

2017-03-21 12:58 UTC, e-kolpakov commented
@haikuginger Still can't verify - probably my devstack is significantly more broken than I expected :). I'll have to debug the configuration issues and it usually takes some time - so most likely I won't be able to finish verification before Thursday evening my timezone.

However, I've read through the code and nothing really strikes my eye, so it might make sense to start upstream review process.

2017-03-21 13:29 UTC, haikuginger commented
Thanks @e-kolpakov! @brittneyexline, @mattdrayer, can you take a look?

2017-03-21 16:15 UTC, haikuginger commented
@e-kolpakov, rebased to pick up a fix from master; this should work for you now.

2017-03-22 10:40 UTC, mattdrayer commented on ecommerce/extensions/basket/views.py
> +                    order_lines = self.request.basket.all_lines()
This item check seems like something that is not specific to the enterprise case -- is it possibly being covered somewhere else?

2017-03-22 10:42 UTC, mattdrayer commented on ecommerce/extensions/basket/views.py
> +                if get_enterprise_customer_from_voucher(
Please include a comment block here that explains what is occurring in this workflow.

2017-03-22 14:54 UTC, haikuginger commented on ecommerce/extensions/basket/views.py
> +                    order_lines = self.request.basket.all_lines()
I took a look and couldn't find anything.

2017-03-22 17:31 UTC, haikuginger commented
@mattdrayer, @brittneyexline, second pass?

2017-03-22 17:37 UTC, mattdrayer commented
LGTM now -- we should have @mjfrey @vkaracic or @marjev take a look since it's the ecommerce project.

2017-03-23 08:13 UTC, vkaracic requested changes
Overall it looks good to me but I'd like to see the commented details addressed.

2017-03-23 08:13 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +                    if not order_lines:
When does this happen? IIRC there should be a ``Your basket is empty`` error triggered prior to getting to this view.

2017-03-23 08:13 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +                            reverse('basket:summary') + '?' + urlencode(
Please use ``str.format()``.
```
'failure_url': self.request.build_absolute_uri('{path}?{params}'.format(
    path=reverse('basket:summary'),
    params=urlencode({CONSENT_FAILED_PARAM: code})
)
```

2017-03-23 08:13 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +                    context = {
This could cause some confusion since ``context`` means something different in a view then what you're using it here for. I suggest either a different variable name or you can do ``params = urlencode({...})`` here directly.

2017-03-23 08:13 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +                    return HttpResponseRedirect(reverse('coupons:redeem') + '?' + params)
Again, please use ``str.format()``, it's the preferred way of formatting strings in this repository.

2017-03-23 08:13 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +    def test_redirects_with_enterprise_customer(self, get_ec):
Please include a brief description of the test in form of a docstring.

2017-03-23 08:13 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +                    sku = order_lines[0].stockrecord.partner_sku
The basket will (should) be changed shortly to support multiple lines so code that assumes only one line will need to be changed. For now please include a TODO comment similar to [this](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/basket/views.py#L209) one so that the poor soul who'll do the conversion to multi-line baskets doesn't skip over it.

2017-03-23 08:13 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.assertIsInstance(resp, HttpResponseRedirect)
If possible could you please add an assertion that makes sure the redirect is to the page that you want it to be and not something else.

2017-03-23 08:13 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +                    order_lines = self.request.basket.all_lines()
Technically these are basket lines. Order lines are something different ([example](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/fulfillment/signals.py#L12))

2017-03-23 09:10 UTC, marjev requested changes

2017-03-23 09:10 UTC, marjev commented on ecommerce/extensions/basket/views.py
> +                _("Could not apply the code '{code}'; it requires data sharing consent.").format(
You should update the translation files.

2017-03-23 11:22 UTC, pomegranited approved these changes
:+1:  If you have the configuration set up (which is a big IF), it works according to the PR instructions.

- [x] I tested this on my devstack, using the PR instructions.
- [x] I read through the code.
- [x] I checked for accessibility issues - there's no new GUI screens to check, but I was able to get around with my keyboard.
- [x] Includes documentation

2017-03-23 21:09 UTC, haikuginger commented on ecommerce/extensions/basket/views.py
> +                    order_lines = self.request.basket.all_lines()
Thanks for the correction!

2017-03-23 21:12 UTC, haikuginger commented on ecommerce/extensions/basket/views.py
> +                    if not order_lines:
Yeah, I took another look, and it seems like we'll never land on the standard basket page if the basket is empty - so this is a no-op.

2017-03-23 21:14 UTC, haikuginger commented on ecommerce/extensions/basket/views.py
> +                    sku = order_lines[0].stockrecord.partner_sku
Noted; thanks!

2017-03-23 21:50 UTC, haikuginger commented
@vkaracic @marjev, care to take another look?

2017-03-24 07:23 UTC, marjev approved these changes

2017-03-24 08:03 UTC, vkaracic approved these changes

2017-03-26 21:31 UTC, haikuginger commented
Rebased and squashed from 6855449.

2017-03-27 01:59 UTC, merged