Add redirect to receipt page after redeeming a free basket.
openedx-unsupported/ecommerce pull request #1210
Opened 2017-03-20 13:52 UTC by vkaracic

When applying an enrollment coupon to a basket and redeeming it, the user would be redirected to the student dashboard. This PR changes that so that the user is redirected to the receipt page or the error page if something went wrong with placing the order (does NOT include fulfillment, this should be it's own ticket).
I've also changed the checkout error page design to be more inline with other error pages:
![screenshot from 2017-03-20 14-28-02](https://cloud.githubusercontent.com/assets/2808092/24101752/c12ac26e-0d79-11e7-9fbe-c93db48ae95e.png)

https://openedx.atlassian.net/browse/SOL-2073

2017-03-20 13:52 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1210"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-20 16:36 UTC, clintonb requested changes

2017-03-20 16:36 UTC, clintonb commented on ecommerce/coupons/views.py
> +                logger.exception('Failed to create an order with message: %s', e.message)
There is no need to log the message when using `log.exception()`. That is already done for you. I would update this to `logger.exception('Failed to create free order for basket [%d].', basket.id)`.

2017-03-20 16:36 UTC, clintonb commented on ecommerce/templates/oscar/checkout/error.html
> +                <p>{% blocktrans %} An error has occurred with your payment. <b>You have not been charged.</b>
Avoid including HTML in strings marked for translation. This should be split: `{% trans "An error has occurred with your payment." %} <b>{% trans "You have not been charged." %}</b>`

2017-03-20 16:36 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        if query_string:
If statements in test methods are a bit of a code smell for me. This would be better off as a separate assertion method, or build `expected_url` outside of this method.

2017-03-20 16:36 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        httpretty.register_uri(httpretty.GET, receipt_page_url, status=status.HTTP_301_MOVED_PERMANENTLY)
This is not necessary. Update your call to `assertRedirects()` to *not* follow the redirect.

2017-03-20 16:36 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        httpretty.register_uri(httpretty.POST, enrollment_api_url, status=status.HTTP_200_OK)
Why do you need to mock the Enrollment API?

2017-03-20 16:36 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +    @ddt.data(
I would update these tests to assume we are using Otto's receipt page since that is what we will be doing long-term. There isn't much value to testing the LMS-based receipt page since it's just a matter of changing the redirect URL.

2017-03-21 09:08 UTC, vkaracic commented on ecommerce/coupons/tests/test_views.py
> +        httpretty.register_uri(httpretty.POST, enrollment_api_url, status=status.HTTP_200_OK)
Because order fulfillment sends a POST request to enroll the user.

2017-03-21 11:31 UTC, vkaracic commented on ecommerce/coupons/tests/test_views.py
> +        httpretty.register_uri(httpretty.POST, enrollment_api_url, status=status.HTTP_200_OK)
Nevermind.

2017-03-22 02:31 UTC, clintonb commented on ecommerce/coupons/views.py
> +            except Exception as e:  # pylint: disable=broad-except
`e` is not used and should be removed.

2017-03-22 02:34 UTC, clintonb reviewed
One last comment about the error message before approving.

2017-03-22 02:34 UTC, clintonb commented on ecommerce/coupons/views.py
> +                # If any error happens when creating an order the user is redirected
This comment adds no value.

2017-03-22 02:34 UTC, clintonb commented on ecommerce/templates/oscar/checkout/error.html
> +                <h3>{{ error }}</h3>
Where is this coming from? Is it translated?

2017-03-22 09:52 UTC, vkaracic commented on ecommerce/templates/oscar/checkout/error.html
> +                <h3>{{ error }}</h3>
It's not used. It's used in the coupon error page and I've must've forgotten to remove it here.

2017-03-22 09:57 UTC, vkaracic commented
@clintonb comments addressed!

2017-03-22 13:12 UTC, marjev approved these changes

2017-03-22 13:20 UTC, clintonb approved these changes

2017-03-22 13:27 UTC, merged

2017-03-22 13:28 UTC, vkaracic commented
Forgot to squash commits... AGAIN! :rage: Sorry!