Coupon view tests update.
openedx-unsupported/ecommerce pull request #1212
Opened 2017-03-21 13:34 UTC by vkaracic

2017-03-21 13:34 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1212"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-21 14:36 UTC, marjev commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        voucher.offers.add(offer)
Can you use https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/test/factories.py#L54 instead?

2017-03-22 10:36 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        voucher.offers.add(offer)
No, that method creates a product and adds it to the voucher range, the test ensures that an exception is raised if there is no product.

2017-03-22 13:12 UTC, marjev approved these changes

2017-03-23 01:37 UTC, clintonb requested changes

2017-03-23 01:37 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_302_FOUND)
Considering this isn't an API module, there shouldn't be any references to DRF here. Even if this were an API module, I see no reason to introduce an unnecessary dependency in our tests.

2017-03-23 01:37 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        self.request = RequestFactory().request()
The base `TestCase` class already includes `self.request`.

2017-03-23 01:37 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        """Used voucher should not be available."""
Verify used vouchers are not valid.

2017-03-23 01:37 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        url = self.path + '?code={}'.format(code)
Use `str.format()` for the entire string.

2017-03-23 01:37 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +            'enterprise_customer': enterprise_customer
Add a trailing comma.

2017-03-23 01:37 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        """User needs be logged in to open offer page with credit seats."""
Verify users need to be logged in to view the offer page.

2017-03-23 01:37 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        self.assertRedirects(response, expected_url, target_status_code=status.HTTP_302_FOUND)
See comments above about unnecessary DRF dependency.

2017-03-23 01:37 UTC, clintonb commented on ecommerce/coupons/views.py
> +        return False, _('Coupon does not exist.')
Update translations.

2017-03-23 07:12 UTC, vkaracic commented on ecommerce/coupons/tests/test_views.py
> +        """Used voucher should not be available."""
The "verify" part is redundant in test docstrings, and I'd like to follow what these guys are doing: https://code.djangoproject.com/ticket/27392

2017-03-24 13:54 UTC, clintonb approved these changes

2017-03-24 15:10 UTC, merged