Fixing a11y issues on new basket page part 2
openedx-unsupported/ecommerce pull request #1213
Opened 2017-03-21 14:52 UTC by iivic

@cptvitamin The following tickets are contained in this PR:

- [ ] ECOM-7516
- [ ] ECOM-7511
- [ ] ECOM-7507
- [ ] ECOM-7505

2017-03-21 14:52 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1213"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-21 20:18 UTC, cptvitamin requested changes

2017-03-21 20:18 UTC, cptvitamin commented on ecommerce/static/sass/partials/views/_basket.scss
> +        text-transform: capitalize;
The intent of https://openedx.atlassian.net/browse/ECOM-7507 was to not use all caps.  While the Text has been changed to all lower-case, That is over-ridden by the CSS.  Ideally, we would "Title Case" all the headings in the base template and remove this text-transform definition.

2017-03-21 20:18 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +        <h2 class="title">{% trans "in your cart" %}</h2>
Title Case

2017-03-21 20:18 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +        <h2>{% trans "summary" %}</h2>
Title Case

2017-03-21 20:18 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +            <h2 class="title">{% trans "order details" %}</h2>
Title Case

2017-03-21 20:18 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +            <h2>{% trans "select payment method" %}</h2>
Title Case

2017-03-21 20:18 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +            <h2 aria-label={% trans "Card holder information" %}>{% trans "card holder information" %}</h2>
Title Case and remove the ```aria-label```

2017-03-21 20:18 UTC, cptvitamin commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +            <h2 aria-label={% trans "Billing information" %}>{% trans "billing information" %}</h2>
Title Case and remove the ```aria-label```

2017-03-21 20:18 UTC, cptvitamin commented on ecommerce/static/sass/base/_base.scss
> +}
I don't see any styles that make the Skip to Content link visible on focus.  Does that already exist in the CSS for this page?  Can you confirm that when you navigate the page with the TAB key the Skip link becomes visible on focus?

2017-03-22 08:34 UTC, iivic commented on ecommerce/static/sass/partials/views/_basket.scss
> +        text-transform: capitalize;
I think that text transformation should be done in css instead of typing it in the html. This practise was indicated to me in one of my PRs.

2017-03-22 08:34 UTC, iivic commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +        <h2 class="title">{% trans "in your cart" %}</h2>
Done in css.

2017-03-22 08:34 UTC, iivic commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +        <h2>{% trans "summary" %}</h2>
Done in css.

2017-03-22 08:34 UTC, iivic commented on ecommerce/templates/oscar/basket/partials/client_side_checkout_basket.html
> +            <h2 class="title">{% trans "order details" %}</h2>
Done in css.

2017-03-22 09:21 UTC, iivic commented on ecommerce/static/sass/base/_base.scss
> +}
The element didn't become visible. Now I included some CSS to make it visible on focus.

2017-03-22 18:00 UTC, cptvitamin approved these changes
@iivic my bad. I read Capitalize, as Uppercase for some reason!  I agree, this is the right approach (CSS) thanks for letting following up.  Everything else looks great!  👍

2017-03-23 12:15 UTC, iivic commented
@cptvitamin I merged the two PRs for basket a11y. Please take a quick look before I merge into master.

2017-03-23 14:19 UTC, cptvitamin commented
👍  merge it!  Some of these features will require manual testing, which I can't do without some sort of test environment.  But I'm so comfortable with the way things look here that I can just open follow-up tickets if there are any issues.

2017-03-23 16:13 UTC, merged