[ENT-236] Check data sharing consent status more thoroughly for coupons
openedx-unsupported/ecommerce pull request #1214
Opened 2017-03-21 18:55 UTC by haikuginger

This pull request adds more thorough checks of user data sharing consent status when redeeming a coupon. At present, users are redirected to the consent flow as long as the attached enterprise has data sharing consent enabled, without regard to whether a user has already provided consent or not. This pull request ensures that users are only directed to the consent flow when they have not already provided consent (for a course or account) and the enterprise enforces consent either at the account level or at the course level.

**JIRA tickets**: Implements [ENT-236](https://openedx.atlassian.net/browse/ENT-236)

**Dependencies**: None

**Merge deadline**: 27 March 2017

**Testing instructions**:

1. Requires a fully-configured course discovery and ecommerce stack.
2. Add a coupon linked to an Enterprise Customer
3. Ensure that the Enterprise Customer has data sharing consent enabled, enforced at enrollment.
3. In the LMS, either log in with an SSO provider linked to the EnterpriseCustomer and provide consent, or manually create a UserDataSharingConsentAudit object via the shell, linked to the user and enterprise in question, with consent enabled.
4. Download the coupon report for the coupon created earlier, and navigate to the "Offers page" URL in that report.
5. Select the course you want to use from the coupon; note that you're taken all the way through the coupon flow and back to the dashboard without being interrupted, rather than being redirected to the consent page.
6. Unlink your user from the Enterprise Customer; set the Enterprise Customer to have data sharing consent enabled, but "optional".
7. De-enroll your user from the course.
8. Again, browse to the Offers page and click through; again, observe that you're not stopped to provide consent.

2017-03-21 18:55 UTC, edx-webhook commented
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1214"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-22 10:48 UTC, mattdrayer commented on ecommerce/enterprise/tests/mixins.py
> +    def mock_specific_enterprise_customer_api(self, uuid, name='TestShib', contact_email='', consent_enabled=True):
are we sure this is the default condition?

2017-03-22 10:52 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +    Determine if consent should be prompted for on this enterprise customer.
Please describe the argument in the docstring -- also why are we passing in a dict here instead of specifying the  arguments we need?

2017-03-22 10:53 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +def enterprise_customer_user_consent_provided(ec_user_data):
As with the above function, why are we being general with the argument specification in this function?

2017-03-22 10:54 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +    api = site.siteconfiguration.enterprise_api_client
Just noting that this will also run into the permissions issue we're seeing in stage+prod right now...

2017-03-22 10:59 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +    if ecu_results:
Can this be combined with the above `if ecu_results:` ?

2017-03-22 11:00 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +    if ecu_results:
Or maybe this was supposed to be `if ec_user:`  ?

2017-03-22 11:03 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +    ec_user_response = ecu_endpoint.get(
It would make things much simpler to follow if we moved the ecu/ece resource getters into their own functions

2017-03-22 11:05 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +    if consent_needed and not account_consent_provided and ecu_results:
I'm not following why we also have to check for `ecu_results` here

2017-03-22 11:08 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +    consent_needed = enterprise_customer_needs_consent(enterprise_customer)
Seems like we should be determining if consent is needed first, and if so, doing all the rest of the work to figure out if the user has provided either account-level consent or course-level consent.

2017-03-22 11:08 UTC, mattdrayer commented on ecommerce/enterprise/utils.py
> +    consent_needed = enterprise_customer_needs_consent(enterprise_customer)
with each of these determinations handled by a separate function/workflow

2017-03-22 11:11 UTC, pomegranited requested changes
@haikuginger I'm pleased with your tests, and how they cover all the cases.

But I don't like how we're duplicating the already complex consent-determination logic that's in the enterprise app.  All of this belongs in the Enterprise API, which shouldn't need to expose all the details of how it works underneath.

2017-03-22 11:11 UTC, pomegranited commented on ecommerce/enterprise/tests/test_utils.py
> +            'cf246b88-d5f6-4908-a522-fc307e0b0c59',
This magic `uuid` is duplicated in several places.  Can it be put into a constant somewhere?

2017-03-22 11:11 UTC, pomegranited commented on ecommerce/enterprise/utils.py
> +    return enterprise_customer_data['enforce_data_sharing_consent'] in ('at_login', 'at_enrollment')
I don't like that this logic lives in both enterprise and ecommerce.

Would rather see an addionional hit to the Enterprise service to check for a user+course than to risk having the logic get out of sync, especially since we know that's quick if the EC doesn't require consent.

2017-03-22 11:11 UTC, pomegranited commented on ecommerce/enterprise/utils.py
> +
Again, the Enterprise API should just return true or false for a user+course.

2017-03-22 11:11 UTC, pomegranited commented on ecommerce/enterprise/utils.py
> +    return consent_needed and not (account_consent_provided or course_consent_provided)
Same argument as above, with knobs on.

2017-03-22 15:24 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    if ecu_results:
Should be `if ec_user:`.

2017-03-22 15:24 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    ec_user_response = ecu_endpoint.get(
Can do!

2017-03-22 15:25 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    if consent_needed and not account_consent_provided and ecu_results:
Should be `ec_user`; you'll note below that we use the EnterpriseCustomerUser's ID to look for related enrollments; we can't do that if we don't have an EnterpriseCustomerUser.

2017-03-22 15:26 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    consent_needed = enterprise_customer_needs_consent(enterprise_customer)
This way allows us to make fewer calls in cases where EnterpriseCustomerUsers already exist - the EnterpriseCustomer comes preloaded on the EnterpriseCustomerUser, so we can use the data we get that way without making a specific call for it.

2017-03-22 15:26 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    api = site.siteconfiguration.enterprise_api_client
Noted.

2017-03-22 15:27 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    Determine if consent should be prompted for on this enterprise customer.
Will do. For both this function and `enterprise_customer_user_consent_provided`, we want to be able to fetch the data independently of parsing it. For example, for this function, it can handle an EnterpriseCustomer either retrieved directly from the API, or one that's a child element on an EnterpriseCustomerUser.

2017-03-22 15:29 UTC, haikuginger commented on ecommerce/enterprise/tests/mixins.py
> +    def mock_specific_enterprise_customer_api(self, uuid, name='TestShib', contact_email='', consent_enabled=True):
I would argue that it is for EnterpriseCustomers in general. It was already the default value; adding it to the method signature just means that we can modify it when testing.

2017-03-22 15:29 UTC, haikuginger commented on ecommerce/enterprise/tests/test_utils.py
> +            'cf246b88-d5f6-4908-a522-fc307e0b0c59',
Sure can!

2017-03-22 15:31 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    return enterprise_customer_data['enforce_data_sharing_consent'] in ('at_login', 'at_enrollment')
I'm not thrilled about it either, but I'm also not sure there's a good home for it in the Enterprise API at the moment - we're talking about an abstract resource that doesn't really exist.

2017-03-22 15:31 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    ec_user_response = ecu_endpoint.get(
Okay; can do!

2017-03-22 15:53 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    return enterprise_customer_data['enforce_data_sharing_consent'] in ('at_login', 'at_enrollment')
@pomegranited, discussed this with Griff. Because we're under a bit of a time crunch at the moment, he'd like to go ahead with the current state, and create a follow-up story to handle the tech debt later on (which he's promised will be prioritized). I've come up with an alternate structure that'll let us handle this even without the API calls, but it's going to be a bit more complex, and we want to have this fixed ASAP for demo purposes. Is that okay with you? I know it's not ideal, but it's what there is.

2017-03-22 21:56 UTC, pomegranited commented on ecommerce/enterprise/utils.py
> +    return enterprise_customer_data['enforce_data_sharing_consent'] in ('at_login', 'at_enrollment')
:+1:

2017-03-23 00:13 UTC, pomegranited requested changes
Ok, I can accept the code duplication if it's going to be cleaned up  soon :)  

Noted the issue that I believe is making the tests fail.  I can't get the tests to run on my devstack, so don't know for sure (they throw Segmentation faults!).

But Steps 1-6 in the PR instructions are working as expected.

However, steps 7-9 aren't resulting in an enrollment in the Coupon course.  I think has to do with the new User I had to create, with `username= settings.ENTERPRISE_SERVICE_WORKER_USERNAME` (`ecommerce_worker`).  Does this user need some special permissions or settings?  I haven't had to have this user before, is it new?

LMS log:
```
[22/Mar/2017 20:04:28] "GET /enterprise/api/v1/enterprise-learner/?username=superego&enterprise_customer=74fa524a-39e4-4db0-819f-608221a13351 HTTP/1.1" 200 93
2017-03-22 20:04:28,448 WARNING 1822 [edx_rest_framework_extensions.authentication] authentication.py:40 - The setting OAUTH2_USER_INFO_URL is invalid!
[22/Mar/2017 20:04:28] "POST /enterprise/api/v1/enterprise-learner/ HTTP/1.1" 403 63
```

ecommerce traceback:
```
2017-03-23 00:04:28,470 ERROR 25646 [ecommerce.extensions.fulfillment.api] /edx/app/ecommerce/ecommerce/ecommerce/extensions/fulfillment/api.py:68 - An unexpected error occurred while fulfilling order [ABC-100017].
Traceback (most recent call last):
  File "/edx/app/ecommerce/ecommerce/ecommerce/extensions/fulfillment/api.py", line 58, in fulfill_order
    module.fulfill_product(order, supported_lines)
  File "/edx/app/ecommerce/ecommerce/ecommerce/extensions/fulfillment/modules.py", line 227, in fulfill_product
    order.user.username
  File "/edx/app/ecommerce/ecommerce/ecommerce/enterprise/utils.py", line 154, in get_or_create_enterprise_customer_user
    response = endpoint.post(data)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/slumber/__init__.py", line 167, in post
    resp = self._request("POST", data=data, files=files, params=kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
HttpClientError: Client Error 403: http://localhost:8000/enterprise/api/v1/enterprise-learner/
```

2017-03-23 00:13 UTC, pomegranited commented on ecommerce/enterprise/utils.py
> +            enterprise_customer_user=ec_user['id']
Your tests have caught an error here:

```diff
--- a/ecommerce/enterprise/utils.py
+++ b/ecommerce/enterprise/utils.py
@@ -273,7 +273,7 @@ def enterprise_customer_user_needs_consent(site, enterprise_customer_uuid, cours
     if consent_needed and not account_consent_provided and ec_user:
         existing_course_enrollment = get_enterprise_course_enrollment(
             course_id=str(course_id),
-            enterprise_customer_user=ec_user['id']
+            username=ec_user['username']
         )
         if existing_course_enrollment:
             course_consent_provided = existing_course_enrollment.get('consent_granted', False)
```

2017-03-23 00:35 UTC, haikuginger commented
@pomegranited, the worker users do need to have `is_staff` set to True in the LMS; is that the case? If not, do that, and then restart ecommerce so that it picks up a new token.

2017-03-23 01:20 UTC, pomegranited commented
@haikuginger Ok, I've given my `enterprise_worker` user staff access, and restarted ecommerce.  But now when I try to redeem a coupon for my logged-in TestShib user, I'm getting a 500 error on /dashboard!

ecommerce says:
```
2017-03-23 01:20:23,010 ERROR 4157 [django.request] /edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/handlers/base.py:284 - Internal Server Error: /api/v2/orders/ABC-100018/
Traceback (most recent call last):
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework/views.py", line 376, in initial
    self.perform_authentication(request)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework/views.py", line 310, in perform_authentication
    request.user
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework/request.py", line 353, in __getattribute__
    return super(Request, self).__getattribute__(attr)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework/request.py", line 193, in user
    self._authenticate()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework/request.py", line 316, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/edx_rest_framework_extensions/authentication.py", line 183, in authenticate
    return super(JwtAuthentication, self).authenticate(request)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/rest_framework_jwt/authentication.py", line 33, in authenticate
    payload = jwt_decode_handler(jwt_value)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/edx_rest_framework_extensions/utils.py", line 74, in jwt_decode_handler
    jwt_issuer['SECRET_KEY'],
TypeError: string indices must be integers, not str
[23/Mar/2017 01:20:23] "GET /api/v2/orders/ABC-100018/ HTTP/1.1" 500 172905
```

LMS Traceback:
```
2017-03-22 21:17:18,568 ERROR 3806 [django.request] base.py:256 - Internal Server Error: /dashboard
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 755, in dashboard
    enrollment.course_id for enrollment in course_enrollments
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 757, in <genexpr>
    user_already_has_certs_for=user_already_has_certs_for
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/models.py", line 1572, in refundable
    refund_cutoff_date = self.refund_cutoff_date()
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/models.py", line 1602, in refund_cutoff_date
    order = ecommerce_api_client(self.user).orders(order_number).get()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/slumber/__init__.py", line 103, in _request
    raise exceptions.HttpServerError("Server Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
HttpServerError: Server Error 500: http://localhost:8002/api/v2/orders/ABC-100018/
```

And I'm able to view http://localhost:8002/api/v2/orders/ABC-100018/ when logged in as a staff user.

Any ideas?

2017-03-23 01:51 UTC, haikuginger commented
Aha! @pomegranited, you've run into my favorite devstack ecommerce bug! Modify the `JWT_AUTH` key in `/edx/etc/ecommerce.yml` as found in the description of [this PR](https://github.com/edx/ecommerce/pull/1208); the devstack config is broken by default.

2017-03-23 04:09 UTC, pomegranited approved these changes
@haikuginger That did the trick!  So many services to hoop through.  Thanks for your help!

:+1: once tests pass.

- [x] I tested this on my devstack using the instructions in the PR.
- [x] I read through the code, and have been assured that the code duplication will be addressed in a subsequent PR.
- [x] I checked for accessibility issues - no new user-facing paths have been introduced, and so a11y levels are maintained.
- [x] Includes documentation - existing functionality is already documented, and there are docstrings to explain this change.

2017-03-23 21:02 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +            enterprise_customer_user=ec_user['id']
Thanks for the pointer! It's the other side that's incorrect, actually - this is the trouble with copy-paste programming!

2017-03-23 21:04 UTC, haikuginger commented
@mattdrayer, can you assign an additional edX reviewer to go over this PR?

2017-03-23 21:08 UTC, mattdrayer commented
Let's tag-in @vkaracic @marjev since they've been so helpful with reviewing our ecommerce changes -- @mjfrey FYI as well.

2017-03-24 08:22 UTC, marjev requested changes

2017-03-24 08:22 UTC, marjev commented on ecommerce/enterprise/utils.py
> +    else:
no need for else

2017-03-24 08:22 UTC, marjev commented on ecommerce/enterprise/utils.py
> +    else:
no need for else

2017-03-24 11:59 UTC, vkaracic approved these changes
A few nitpicks about formatting and tips about DRY'ing your code.

2017-03-24 11:59 UTC, vkaracic commented on ecommerce/coupons/views.py
> +                                        get_enterprise_customer_from_voucher)
The preferred way is [3 - Vertical Hanging Indent](https://github.com/timothycrosley/isort#multi-line-output-modes).

2017-03-24 11:59 UTC, vkaracic commented on ecommerce/enterprise/utils.py
> +        return None
I would make this and the above function shorter, like this:
```
api = site.siteconfiguration.enterprise_api_client
response = api.enterprise_course_enrollment.get(
        enterprise_customer_user=int(enterprise_customer_user),
        course_id=str(course_id),
)
results = response.get('results')
return results[0] if results else None
```
Effectively it's the same thing but with less code, so it's up to you.

2017-03-24 11:59 UTC, vkaracic commented on ecommerce/enterprise/utils.py
> +        site: The site which is handling the current request
``site (Site):`` If the argument should be an instance of a model we add the model name capitalized in parenthesis.

2017-03-24 11:59 UTC, vkaracic commented on ecommerce/enterprise/tests/test_utils.py
> +        self.assertTrue(consent_needed)
These tests can be combined with ``ddt``. For example for this and the above one you could do something like this:
```
@ddt.data(True, False)
def test_ecu_something(self, consent):
        self.mock_access_token_response()
        self.mock_enterprise_learner_api_for_learner_with_no_enterprise()
        uuid = TEST_ENTERPRISE_CUSTOMER_UUID
        self.mock_specific_enterprise_customer_api(uuid, consent_enabled=consent)

        consent_needed = enterprise_customer_user_needs_consent(
            self.site,
            TEST_ENTERPRISE_CUSTOMER_UUID,
            'course-v1:edX+DemoX+Demo_Course',
            'admin'
        )
        self.assertEqual(consent)
```

2017-03-24 11:59 UTC, vkaracic commented on ecommerce/enterprise/tests/mixins.py
> +    def mock_enterprise_course_enrollment_api_no_results(self):
This could be combined with the upper method. Something like this:
```
def mock_enterprise_course_enrollment_api(
        self,
        ec_user_id=1,
        consent_granted=True,
        course_id='course-v1:edX+DemoX+Demo_Course',
        no_results=False
):
    """
    Helper function to register enterprise course enrollment API endpoint for a
    learner with an existing enterprise enrollment in a course.
    """
    enterprise_enrollment_api_response = {
        'count': 0 if no_results else 1,
        'num_pages': 1,
        'current_page': 1,
        'results': [] if no_results else [
            {
                'enterprise_customer_user': ec_user_id,
                'consent_granted': consent_granted,
                'course_id': course_id,
            }
        ],
        'next': None,
        'start': 0,
        'previous': None
    }
    enterprise_enrollment_api_response_json = json.dumps(enterprise_enrollment_api_response)

    httpretty.register_uri(
        method=httpretty.GET,
        uri=self.ENTERPRISE_COURSE_ENROLLMENT_URL,
        body=enterprise_enrollment_api_response_json,
        content_type='application/json'
    )
```

2017-03-24 15:30 UTC, haikuginger commented on ecommerce/coupons/views.py
> +                                        get_enterprise_customer_from_voucher)
Hmm, for some reason I thought it was in the grid style to start with. Regardless, very happy to make the change. :)

2017-03-24 15:36 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +        return None
Aha! I was trying to avoid an IndexError with that last line, but after some testing, I see that the first clause is only evaluated if the conditional is true - nice!

As for the nicer resource stuff... I wish. Unfortunately, the hyphen is a reserved character in Python, so we have to do the `getattr` dance - in which case, I'd rather have those definitions on their own lines, rather than chaining statements.

2017-03-24 16:07 UTC, vkaracic commented on ecommerce/coupons/views.py
> +                                        get_enterprise_customer_from_voucher)
Thanks! I'm guiding myself by this: https://github.com/edx/ecommerce/pull/1205#discussion_r106899790

2017-03-26 21:35 UTC, haikuginger commented
Rebased from 8218696.

2017-03-27 00:12 UTC, haikuginger commented
@marjev, care to give this a final review? Once you've done so, I'll generate translations, squash, and merge.

2017-03-27 01:52 UTC, mattdrayer commented
@haikuginger I think you are good to merge at this point -- two thumbs + you have addressed @marjev's requests.  :shipit:

2017-03-27 02:42 UTC, merged