Change SDN interface address to city.
openedx-unsupported/ecommerce pull request #1223
Opened 2017-03-28 15:37 UTC by vkaracic

Since we are using the city as an address parameter in the SDN check, it makes more sense semantically the parameter ``city`` throughout our code except for when making the call to the Treasury endpoint.

2017-03-28 15:37 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1223"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-28 15:52 UTC, clintonb requested changes

2017-03-28 15:52 UTC, clintonb commented on ecommerce/extensions/payment/migrations/0017_auto_20170328_1445.py
> +        migrations.RemoveField(
You will need to manually call RenameField.

2017-03-28 16:22 UTC, vkaracic commented
@clintonb comment addressed!

2017-03-28 16:24 UTC, vkaracic commented on ecommerce/extensions/payment/migrations/0017_auto_20170328_1445.py
> +        migrations.AlterField(
Not sure if this part is needed though. The ``city`` length on the form is 32.

2017-03-28 16:59 UTC, clintonb approved these changes
Remember to squash your commits.

2017-03-28 17:00 UTC, vkaracic commented
I'll try :smile:

2017-03-30 12:10 UTC, mjfrey approved these changes

2017-03-30 12:24 UTC, davec-edx commented on ecommerce/extensions/payment/utils.py
> +            'address': unicode(city).encode('utf-8'),
add comment to explain why they 'address' key contains the city.  I know we've talked about this, but who will remember in 6 months to fill the next person in on it?

2017-03-30 12:27 UTC, davec-edx commented
I'd like to see a comment in the view to inform a future dev why it's address=city (commented on the exact line) but otherwise, looks good.

2017-03-30 13:36 UTC, merged