[ENT-229] Check for consent on Enterprise-linked entitlements
openedx-unsupported/ecommerce pull request #1224
Opened 2017-03-28 18:10 UTC by haikuginger

Currently, Enterprise entitlements are only processed if they do not require additional consent intervention. However, this is less than ideal, since we now have the ability to get consent in the middle of a coupon flow. This pull request modifies entitlement behavior to ensure that all entitlements are returned, and that we use a flow that will prompt the user for consent if required.

**JIRA tickets**: Fixes [ENT-229](https://openedx.atlassian.net/browse/ENT-229)

**Dependencies**: None

**Merge deadline**: 10 April 2017

**Testing instructions**:

1. Create an Enterprise Customer in LMS
2. Ensure that consent is enabled for that enterprise customer, and that enforcement is "at enrollment".
2. Create a course with a premium mode.
3. Create a coupon that specifies that enterprise customer and gives a discount on the premium course mode.
4. Add that coupon as an entitlement to the enterprise customer.
5. Using the Django admin, manually add a learner to the enterprise customer; ensure that no consent record exists. If the user was previously linked to the enterprise customer, unlink and relink it.
6. Logged in as the learner, browse to the course information page, and click enroll
7. Select the premium course mode.
8. Verify that you're prompted for consent.
9. Declined consent.
10. Verify that you're returned to the single-item cart, with no discount applied.
11. In the LMS, unenroll yourself from the course entirely.
12. Browse to the course and again attempt to enroll in the premium mode.
13. Verify that you're prompted for data sharing consent.
14. Consent to data sharing; verify that, if you created a discount code, the discount appears in the cart. If you created an enrollment code, verify that you are now enrolled in the premium course mode.

2017-03-28 18:10 UTC, edx-webhook commented
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1224"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-28 18:58 UTC, vkaracic requested changes

2017-03-28 18:58 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        stock_record = Selector().strategy().fetch_for_product(product).stockrecord
Why do you need this stock record?

2017-03-28 18:58 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +            self.assertIn(part, resp.url)
Is it possible to construct the expected URL and do ``assertRedirects``?

2017-03-28 18:58 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.mock_enrollment_api_success_enrolled(self.course.id)
There is a problem here. ``mock_enrollment_api_success_enrolled`` returns that a [user is already enrolled](https://github.com/edx/ecommerce/blob/d7fdcce80ec4820c9cf358a478918a30e0bdadbe/ecommerce/extensions/basket/tests/test_views.py#L79) in the passed course, in which case trying to redeem a coupon should result in an error message saying that the user is already enrolled, but here it redirects to the basket summary. Why is that?

2017-03-28 18:58 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +                                    {
Nit: you don't need to new-line these. This format is fine:
```
params=urlencode({
    ...
})
```

2017-03-29 16:56 UTC, mattdrayer commented on ecommerce/extensions/basket/views.py
>              voucher = get_entitlement_voucher(request, product)
Can we enhance the comment here and do a better job explaining that we are overriding the original voucher variable, why we are doing it here, etc.

2017-03-29 17:14 UTC, mattdrayer commented on ecommerce/extensions/basket/views.py
> +                        # In the event of a failure to get consent, redirect the user back to this
So in this case we are preparing for the possible scenario of "failure to get consent", but that is not actually being determined in this function, right?  Can we clarify that in the comment?

2017-03-30 00:31 UTC, e-kolpakov reviewed
@haikuginger Seems reasonable code to me, but still can't verify due to broken ecom <-> LMS config; will try again later today (unless @pomegranited actually manages to verify it by that time)

2017-03-30 11:12 UTC, pomegranited approved these changes
The code works as described.  :+1:  once testing issues resolved.

- [x] I tested this on my devstack using the PR test instructions, with these differences:
    * Step 12 "In the LMS, unenroll yourself from the course entirely." was not necessary, because declining consent did not enrol my user (which is surely the correct behaviour).
    * Step 15: "Consent to data sharing; verify that, if you created a discount code, the discount appears in the cart."  Consenting to data sharing sent me to the Receipt page, with the discount applied (also sounds correct to me).
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> No GUI changes made.
- [x] Includes documentation - bugfix, removes outdated docstring.

2017-03-30 11:12 UTC, pomegranited commented on ecommerce/extensions/basket/tests/test_views.py
> +        sku = self.stockrecord.partner_sku
Test failure here:

```
======================================================================
ERROR: test_with_entitlement_voucher (ecommerce.extensions.basket.tests.test_views.BasketSingleItemViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/edx/app/ecommerce/ecommerce/ecommerce/extensions/basket/tests/test_views.py", line 133, in test_with_entitlement_voucher
    sku = self.stockrecord.partner_sku
AttributeError: 'BasketSingleItemViewTests' object has no attribute 'stockrecord'
-------------------- >> begin captured logging << --------------------
ecommerce.courses.models: DEBUG: Created new parent seat [1071] for [course-v1:test-org+course+xYgJAoWUjEip].
ecommerce.courses.models: INFO: Course seat product with certificate type [verified] for [course-v1:test-org+course+xYgJAoWUjEip] does not exist. Instantiated a new instance.
ecommerce.courses.models: INFO: Course seat product stock record with certificate type [verified] for [course-v1:test-org+course+xYgJAoWUjEip] does not exist. Instantiated a new instance.
ecommerce.courses.models: INFO: Course seat product with certificate type [verified] for [course-v1:test-org+course+xYgJAoWUjEip] does not exist. Instantiated a new instance.
ecommerce.courses.models: INFO: Course seat product stock record with certificate type [verified] for [course-v1:test-org+course+xYgJAoWUjEip] does not exist. Instantiated a new instance.
--------------------- >> end captured logging << ---------------------
```

2017-03-30 11:12 UTC, pomegranited commented on ecommerce/extensions/basket/tests/test_views.py
> +        sku = self.stockrecord.partner_sku
Test failure here:

```
======================================================================
ERROR: test_with_entitlement_voucher_consent_failed (ecommerce.extensions.basket.tests.test_views.BasketSingleItemViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/edx/app/ecommerce/ecommerce/ecommerce/extensions/basket/tests/test_views.py", line 157, in test_with_entitlement_voucher_consent_failed
    sku = self.stockrecord.partner_sku
AttributeError: 'BasketSingleItemViewTests' object has no attribute 'stockrecord'
-------------------- >> begin captured logging << --------------------
ecommerce.courses.models: DEBUG: Created new parent seat [1074] for [course-v1:test-org+course+dOqqhMsFZfIv].
ecommerce.courses.models: INFO: Course seat product with certificate type [verified] for [course-v1:test-org+course+dOqqhMsFZfIv] does not exist. Instantiated a new instance.
ecommerce.courses.models: INFO: Course seat product stock record with certificate type [verified] for [course-v1:test-org+course+dOqqhMsFZfIv] does not exist. Instantiated a new instance.
ecommerce.courses.models: INFO: Course seat product with certificate type [verified] for [course-v1:test-org+course+dOqqhMsFZfIv] does not exist. Instantiated a new instance.
ecommerce.courses.models: INFO: Course seat product stock record with certificate type [verified] for [course-v1:test-org+course+dOqqhMsFZfIv] does not exist. Instantiated a new instance.
--------------------- >> end captured logging << ---------------------
```

2017-03-30 12:36 UTC, haikuginger commented on ecommerce/extensions/basket/tests/test_views.py
> +        stock_record = Selector().strategy().fetch_for_product(product).stockrecord
We don't. Residue - removed.

2017-03-30 12:37 UTC, haikuginger commented on ecommerce/extensions/basket/tests/test_views.py
> +            self.assertIn(part, resp.url)
I rebuilt the method to use OrderedDict, which allows us to have a deterministic order for the URL parameters so we can do that.

2017-03-30 12:45 UTC, haikuginger commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.mock_enrollment_api_success_enrolled(self.course.id)
Well, it's a good thing that this test is already failing for other reasons! I'll make the appropriate change. :)

2017-03-30 13:23 UTC, marjev approved these changes

2017-03-30 14:13 UTC, mattdrayer commented
Thanks for adding the comments -- context is MUCH clearer now!  Code looks cleaner too, nice work!  👍

2017-03-30 20:36 UTC, haikuginger commented
@vkaracic, care to cast a 👍?

2017-03-30 21:42 UTC, vkaracic requested changes
Mostly nitpicks, my only real question is how will the tests behave once you commit the voucher changes to the database.

2017-03-30 21:42 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        voucher.code = 'FAKECODE'
You should call ``save()`` when editing model object attributes to commit the changes to the database:
```
In [1]: from ecommerce.extensions.voucher.models import Voucher

In [2]: v = Voucher.objects.first()

In [3]: v
Out[3]: <Voucher: Demo discount>

In [4]: v.code
Out[4]: u'DEMOD'

In [5]: v.code = 'DEMO'

In [6]: v.code
Out[6]: 'DEMO'

In [7]: v.refresh_from_db()

In [8]: v.code
Out[8]: u'DEMOD'
```

2017-03-30 21:42 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +            'http%3A%2F%2Ftestserver.fake%2Fbasket%2Fsingle-item%2F%3Fconsent_failed%3DTrue%26sku%3D{sku}'.format(
I would change this to:
```
expected_failure_url = '{base}?{params}'.format(
    base=self.get_full_url(path=reverse(basket:single-item)),
    params=urllib.urlencode({
        consent_failed=True,
        sku=sku
    })
)
```

2017-03-30 21:42 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        expected_url = reverse('coupons:redeem') + '?code=FAKECODE&sku={sku}&failure_url={failure_url}'.format(
And this to:
```
expected_url = '{base}?{params}'.format(
    base=reverse('coupons:redeem'),
    params=urllib.urlencode({
        code='FAKECODE',
        sku=sku,
        failure_url=expected_failure_url
    })
)
```

This should make the URL construction more legible. I also don't think you need to manually quote the ``expected_failure_url``, but if I'm wrong, please use ``urllib.quote()``.

2017-03-30 21:42 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        voucher.code = 'FAKECODE'
Same question if the ``model_obj.save()`` is needed?

2017-03-30 21:42 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        url = '{path}?sku={sku}&consent_failed=true'.format(path=self.path, sku=sku)
Nit: I would love it if you could use ``urllib.urlecode`` here for the parameters.

2017-03-30 21:42 UTC, vkaracic commented on ecommerce/extensions/basket/views.py
> +                        ),
Nit: you could make this part a bit more compact:
```
('failure_url', request.build_absolute_uri('{path}?{params}'.format(
    path=reverse('basket:single-item'),
    params=urlencode(OrderedDict([
            (CONSENT_FAILED_PARAM, True),
            ('sku', sku),
        ]))
    )),
),
```

2017-03-30 21:44 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        voucher.code = 'FAKECODE'
And this would true if ``voucher`` here is actually a model object, but if Vedran would read the code a bit more carefully he would see that this is a mocked objects :smile:

2017-03-30 21:44 UTC, vkaracic approved these changes

2017-03-30 21:45 UTC, vkaracic commented
It's up to you if you want to address my nitpicks, otherwise you are good to go :+1:

2017-03-31 14:05 UTC, haikuginger commented on ecommerce/extensions/basket/tests/test_views.py
> +        voucher.code = 'FAKECODE'
Same answer as above. ;)

2017-03-31 14:06 UTC, haikuginger commented on ecommerce/extensions/basket/tests/test_views.py
> +            'http%3A%2F%2Ftestserver.fake%2Fbasket%2Fsingle-item%2F%3Fconsent_failed%3DTrue%26sku%3D{sku}'.format(
I prefer to have the URL more manually constructed; that way I know I'm just not repeating the same errors I made in the real code.

2017-03-31 21:54 UTC, haikuginger commented
Squashed down from 3efa0fa3.

2017-03-31 22:11 UTC, merged