Updated verification URL on receipt page
openedx-unsupported/ecommerce pull request #1225
Opened 2017-03-28 22:13 UTC by clintonb

The receipt page now points to the reverification page, which is not
course-specific. This is one step in making our receipt page more
applicable to orders containing multiple course seats.

LEARNER-278

2017-03-28 22:14 UTC, clintonb commented
@edx/helio please review

2017-03-28 22:38 UTC, vkaracic requested changes

2017-03-28 22:38 UTC, vkaracic commented on ecommerce/extensions/checkout/tests/test_views.py
> +            'verification_url': get_lms_url('verify_student/reverify'),
Perhaps build the LMS URL with the ``site_configuration`` object. 
https://github.com/edx/ecommerce/blob/master/ecommerce/core/url_utils.py#L66
https://github.com/edx/ecommerce/blob/master/ecommerce/core/url_utils.py#L15

2017-03-28 22:38 UTC, vkaracic commented on ecommerce/extensions/checkout/views.py
> +                    'verification_url': get_lms_url('verify_student/reverify'),
Same here.

2017-03-28 22:47 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +            'verification_url': get_lms_url('verify_student/reverify'),
Updated.

2017-03-28 22:47 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                    'verification_url': get_lms_url('verify_student/reverify'),
Updated.

2017-03-28 22:51 UTC, vkaracic commented on ecommerce/extensions/checkout/views.py
> +        request = self.request
Why this change?

2017-03-29 02:38 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +        request = self.request
Simplify access to the `request` object.

2017-03-29 04:53 UTC, vkaracic approved these changes

2017-03-29 11:54 UTC, marjev approved these changes

2017-03-29 16:53 UTC, merged