[WIP] LEARNER-324 New basket endpoint to accept multiple SKUs
openedx-unsupported/ecommerce pull request #1230
Opened 2017-03-31 11:26 UTC by marjev

### JIRA task:
[new basket endpoint to accept a list of SKUs to add to the basket](https://openedx.atlassian.net/browse/LEARNER-324)

### to-do:

- [ ] write tests
- [ ] update translation files

2017-03-31 11:26 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1230&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-03-31 12:03 UTC, mjfrey commented on ecommerce/extensions/basket/app.py
> +            url(r'^multiple-items/$', login_required(self.multiple_items_view.as_view()), name='multiple-items'),
We might want to just call this add-items

2017-04-01 14:34 UTC, clintonb requested changes

2017-04-01 14:34 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +        products = [sr.product for sr in StockRecord.objects.filter(partner=partner, partner_sku__in=skus)]
`products = Product.objects.filter(stockrecords__partner=partner, stockrecords__partner_sku__in=skus)`

2017-04-01 14:34 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +        skus = request.GET.get('skus').split(',')
`skus = request.GET.getlist('sku')`

The URL looks like `http://example.com/basket/add/?sku=8CF08E5&sku=26CD722`

2017-04-01 14:34 UTC, clintonb commented on ecommerce/extensions/basket/app.py
> +            url(r'^multiple-items/$', login_required(self.multiple_items_view.as_view()), name='multiple-items'),
`url(r'^add/$', login_required(self.multiple_items_view.as_view()), name='add-multi'),`

2017-04-03 12:21 UTC, clintonb commented on ecommerce/extensions/basket/app.py
>              url(r'^single-item/$', login_required(self.single_item_view.as_view()), name='single-item'),
Mark this view as deprecated. Either Oscar or Django has a decorator. Alternatively, just log the warning in the post() method.

2017-04-04 13:19 UTC, marjev commented
@clintonb @mjfrey 
Comments addressed. Can you please take another look?

2017-04-04 13:59 UTC, clintonb reviewed
Clean up the tests, and this will be good to go.

2017-04-04 13:59 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.products = []
You do a lot of unnecessary work for every test despite every test not needing all of this data. Move these calls to the tests that need them. `setUp()` should be quite light.

2017-04-04 13:59 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.data.append(('sku', StockRecordFactory(product=product, partner=self.partner).partner_sku))
`StockRecordFactory` creates a product. `ProductFactory` creates a stock record. There is no need to use both. I would use `StockRecordFactory` since you ultimately care about stock records' SKUs.

2017-04-04 13:59 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        response = self.client.get(self.path, data=self.data)
All of the overhead in `create_product_with_stockrecord` can be simplified here.

```python
stock_records = StockRecordFactory.create_batch(3, partner=self.partner)
qs = urllib.urlencode({'sku': [stock_record.partner_sku for stock_record in stock_records]}, True)
url = '{root}?{qs}'.format(root=self.path, qs=qs)
response = self.client.get(url)
```

2017-04-04 13:59 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        basket.strategy = strategy.Default()
Why is this necessary?

2017-04-04 13:59 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +    @ddt.data(Voucher.SINGLE_USE, Voucher.MULTI_USE)
The usage type shouldn't matter. Just use the default of `VoucherFactory`.

2017-04-04 13:59 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +            return HttpResponseBadRequest(_('Products with [{skus}] do not exist.').format(skus=', '.join(skus)))
Products with SKU(s) [] do not exist.

2017-04-04 14:41 UTC, marjev commented on ecommerce/extensions/basket/tests/test_views.py
> +        basket.strategy = strategy.Default()
Basket middleware adds the strategy to the basket, but since this basket did go through the middleware, the strategy is missing. 
Because of that, an exception is thrown when I try to get the total price.
One way is to add the strategy manually.

The end goal was to check if the basket total price is equal to the sum of product prices.

2017-04-05 08:42 UTC, marjev commented on ecommerce/extensions/basket/tests/test_views.py
> +        response = self.client.get(self.path, data=self.data)
I tried create_batch before, but ran into this error:
`IntegrityError: UNIQUE constraint failed: partner_partner.short_code`

I'll leave the method I created, but use some of the things you suggested in this comment.

2017-04-05 11:54 UTC, marjev commented
Comments addressed.

2017-04-05 12:00 UTC, mjfrey approved these changes

2017-04-05 13:00 UTC, clintonb approved these changes

2017-04-05 13:00 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        basket = response.wsgi_request.basket
Interesting.

2017-04-05 13:56 UTC, merged