add enterprise message to offers page
openedx-unsupported/ecommerce pull request #1233
Opened 2017-04-03 09:00 UTC by zubair-arbi

ENT-270
@asadiqbal08 @saleem-latif @mattdrayer 

Add/update the existing offers page heading message from "Select one of the following courses." to "Welcome to edX. Please choose from the courses selected by your organization to start learning." for all users.
<img width="1201" alt="screen shot 2017-04-03 at 1 55 34 pm" src="https://cloud.githubusercontent.com/assets/5072991/24602338/d51fe0fe-1875-11e7-89f7-91e0b5253046.png">

**Previously:** 
<img width="1187" alt="screen shot 2017-03-28 at 3 25 37 pm" src="https://cloud.githubusercontent.com/assets/5072991/24602277/9005b96c-1875-11e7-8975-ff0974b4f089.png">

2017-04-03 12:01 UTC, mattdrayer commented on ecommerce/static/templates/_offer_course_list.html
> +            <%- gettext("Welcome to edX. Please choose from the courses selected by your organization to start learning.") %>
I'd prefer to set this string in the view and pass it via the context.  Then we can write a test to cover the string and easily add conditional logic in the future without cluttering the template code.

2017-04-03 13:04 UTC, zubair-arbi commented
@mattdrayer I have updated the PR to provide offer page heading from offer view and added a js test for it. Please let me know if this is what you were expecting. Also I am waiting for the Griff's suggestion on the layout/design for the message box.

2017-04-03 13:32 UTC, mattdrayer commented
Thanks -- I would also like to see a python test checking for the presence of the parameter in the context -- thus will help to enforce the implicit contract between view and template

2017-04-06 09:36 UTC, asadiqbal08 commented
👍 kindly rebase it

2017-04-06 12:34 UTC, zubair-arbi commented
@mattdrayer I have addressed your feedback, please review again.

2017-04-07 02:53 UTC, mattdrayer commented
Looks like another rebase is in order -- otherwise the PR LGTM -- 👍

@vkaracic and/or @marjev care to take a look?

2017-04-07 05:59 UTC, marjev requested changes

2017-04-07 05:59 UTC, marjev commented on ecommerce/coupons/views.py
> +            })
Can you add this text in the template directly?
You can show it if there wasn't any errors in the context data.

2017-04-07 08:03 UTC, zubair-arbi commented on ecommerce/coupons/views.py
> +            })
@marjev This is intentional. I have made this change as pr suggestion by @mattdrayer, this way we have covered the change in unittest and we can easily add conditional logic in the future without cluttering the template code.

2017-04-07 12:11 UTC, marjev approved these changes

2017-04-07 13:27 UTC, merged