Sort countries alphabetically by their full name.
openedx-unsupported/ecommerce pull request #1242
Opened 2017-04-06 11:40 UTC by vkaracic

After [updating](https://github.com/edx/ecommerce/commit/b78a6cbf60502c2f96d6feb5d53f58f68050d2fd) the ``pycountry`` package the country list wasn't in alphabetical order:
![screenshot from 2017-04-06 13-27-18](https://cloud.githubusercontent.com/assets/2808092/24752509/6c0bd2d4-1ace-11e7-808b-20ebccae19c3.png)

This PR sorts the countries back again:
![screenshot from 2017-04-06 13-35-50](https://cloud.githubusercontent.com/assets/2808092/24752533/8d8e777c-1ace-11e7-8252-91b60dbba4d8.png)

2017-04-06 11:40 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1242&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-04-06 13:44 UTC, clintonb reviewed
Test?

2017-04-07 11:31 UTC, vkaracic commented
@clintonb test added!

2017-04-07 12:46 UTC, clintonb requested changes

2017-04-07 12:46 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_forms.py
> +import copy
This should be separated, since it's part of Python.

2017-04-07 12:46 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_forms.py
>  class CyberSourceSubmitFormTests(TestCase):
There is no class named `CyberSourceSubmitForm`. This should be named `PaymentFormTests`.

2017-04-07 12:46 UTC, clintonb commented on ecommerce/extensions/payment/tests/test_forms.py
> +    def tearDown(self):
This is unnecessarily complicated. Try this:

```python
    def test_countries_sorting(self):
        """ Verify the country choices are sorted by country name. """
        data = self._generate_data()
        form = PaymentForm(user=self.user, data=data)
        expected = sorted([(country.alpha_2, country.name) for country in pycountry.countries], key=lambda x: x[1])
        actual = list(form.fields['country'].choices)
        actual.pop(0)   # Remove the "Choose country" placeholder
        self.assertEqual(actual, expected)

```

2017-04-10 07:33 UTC, vkaracic commented
@clintonb comments addressed!

2017-04-10 12:16 UTC, clintonb approved these changes

2017-04-10 14:37 UTC, merged