[WIP][ENT-303]Allow coupon API to be filtered by EnterpriseCustomer UUID
openedx-unsupported/ecommerce pull request #1247
Opened 2017-04-11 19:13 UTC by haikuginger

this space intentionally left blank. stand by for more.

2017-04-11 19:13 UTC, edx-webhook commented
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1247"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-04-19 07:48 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +        ec_filter = self.request.GET.get('enterprise_customer', None)
You don't need ``None`` here.

2017-04-19 07:48 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if ec_filter is not None:
Can you just say ``if ec_filter:``?

2017-04-19 07:48 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(len(json.loads(response.content)['results']), 2)
You should add a few blank lines to make the code more legible.

2017-04-19 07:48 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(coupon_data['client'], self.data['client'])
If I understand this test correctly you get the same thing with a fake UUID as you do with a valid one?

2017-04-19 08:12 UTC, marjev approved these changes
I would agree with Vedran on adding a few additional blank lines just to increase the readability of the test.

I would suggest separating different cases with a single new line. Otherwise LGTM.

2017-04-19 09:54 UTC, itsjeyd requested changes
@haikuginger Made a first pass over the code. Just needs a little bit of polish; the approach looks good to me.

2017-04-19 09:54 UTC, itsjeyd commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        # And test that without filtering, we get both coupons.
@haikuginger I think we should move this comment above the `GET` in the previous line.

2017-04-19 09:54 UTC, itsjeyd commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(coupon_data['client'], self.data['client'])
@haikuginger Since these assertions are duplicated below it might make sense to move them to a separate method, something like `assert_coupon_data`.

2017-04-19 09:54 UTC, itsjeyd commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> -                });
@haikuginger IIUC, we now want the menu for selecting an enterprise customer to be visible at all times. Would it be worth keeping this test and just changing `.not.toBeVisible()` in L209 to `.toBeVisible()`, to make sure any changes to the current behavior wouldn't go unnoticed?

2017-04-19 09:54 UTC, itsjeyd commented on ecommerce/extensions/api/v2/views/coupons.py
> +
@haikuginger Thanks for adding detailed comments about what's happening to this method :)

2017-04-19 12:28 UTC, clintonb requested changes
Your team needs to finish https://github.com/edx/ecommerce/pull/1218 before you do any additional coupon work. You're building atop an incorrect model.

2017-04-19 16:26 UTC, itsjeyd commented
@haikuginger I tested the changes according to the instructions in the PR description and they are working fine. Couldn't associate a coupon with a catalog because ecommerce is currently failing to retrieve course catalog data from the Course Discovery API, but that's not related to the changes that this PR introduces. The "Enterprise Customer" option is available for any of "Single course", "Multiple courses", "Catalog".

2017-04-19 17:06 UTC, haikuginger commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if ec_filter is not None:
No; that'd match blank strings, which aren't valid filters. To be fair, that'd get caught by checking if it's a valid UUID, but I prefer to be explicit.

2017-04-19 17:06 UTC, haikuginger commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(len(json.loads(response.content)['results']), 2)
Agreed! Legible code is always good.

2017-04-19 17:07 UTC, haikuginger commented on ecommerce/extensions/api/v2/views/coupons.py
> +        ec_filter = self.request.GET.get('enterprise_customer', None)
Right you are!

2017-04-19 17:11 UTC, haikuginger commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(coupon_data['client'], self.data['client'])
No. Initially, we have one coupon, and so calling the list API will return that single coupon. When calling with an invalid UUID, we get that single coupon back, since an invalid UUID can't filter anything. We then add an _additional_ coupon that has a UUID attached, and attempt to filter by that valid UUID, resulting in a single (different) result.

2017-04-19 17:11 UTC, haikuginger commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        # And test that without filtering, we get both coupons.
Sure!

2017-04-19 17:12 UTC, haikuginger commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(coupon_data['client'], self.data['client'])
Sure; that makes sense!

2017-04-19 17:12 UTC, haikuginger commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> -                });
We definitely could; that's a good idea.

2017-04-19 17:18 UTC, clintonb commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if ec_filter is not None:
Filtering should be done in `filters.py` with `django_filters. See https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/api/filters.py.

2017-04-19 17:19 UTC, haikuginger commented
@clintonb, I think you're probably right that we should prioritize that work. However, we'd still like to get this across the line. Would this change be acceptable to you if we moved the actual query to filter by EnterpriseCustomer UUID into the `ecommerce.enterprise` module?

Doing so would isolate where we need to make changes during the refactor to just that module. Otherwise, the needed behavior should remain the same - we need to get a list of the coupons that are associated with a particular EnterpriseCustomer, whether we do that by doing a database lookup to the related Range, or if we locate an Enterprise-linked Offer and get the linked coupons that way.

2017-04-19 18:08 UTC, haikuginger commented
@marjev @vkaracic @itsjeyd, I've addressed your comments. @clintonb, I haven't made any changes to the filtration logic yet, pending a discussion on if and how we should go ahead with implementing this right now, or wait on #1218.

2017-04-19 19:05 UTC, clintonb commented
This cannot be merged until #1218 is addressed. Building atop the incorrect model will only make fixing that model more difficult.

2017-04-19 19:09 UTC, haikuginger commented
@clintonb, okay! I actually just got off a call with Griff, and we've agreed to defer this until later. I'm going to go ahead and close this PR, as it's no longer necessary.

@itsjeyd, @vkaracic, @marjev, thank you for your reviews!

2017-04-19 19:09 UTC, closed without merging