WIP: Add condition offer API endpoint.
openedx-unsupported/ecommerce pull request #1248
Opened 2017-04-12 13:56 UTC by vkaracic

LEARNER-508

@edx/helio FYI.

2017-04-12 13:56 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1248&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-04-12 14:22 UTC, mjfrey requested changes

2017-04-12 14:22 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/offers.py
> +        for course in program['courses']:
We would also need to remove and excluded course_runs.

2017-04-12 14:22 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/offers.py
> +    def create(self, request, *args, **kwargs):
Given a conditional offer does not have an expiration date like Vouchers we need a way to delete / disable these.

2017-04-12 14:22 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/offers.py
> +            program = api.programs(program_uuid).get()
need exception handling

2017-04-12 14:26 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/offers.py
> +    def create(self, request, *args, **kwargs):
Condition offers have expiration dates: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/abstract_models.py#L91

2017-04-12 14:27 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/offers.py
> +        for course in program['courses']:
Those are automatically excluded on the programs API endpoint.

2017-04-12 14:28 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/offers.py
> +    def create(self, request, *args, **kwargs):
perfect.  We would need to just add those to the endpoint like coupons.

2017-04-12 14:29 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +class ConditionalOfferSerialitzer(serializers.ModelSerializer):
`ConditionalOfferSerializer`

2017-04-12 14:30 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/offers.py
> +    def create(self, request, *args, **kwargs):
I'm expecting that they are sent to this endpoint (lines 51 and 52 in this file).

2017-04-14 12:22 UTC, vkaracic commented
@edx/helio ready for reviews!

2017-04-18 17:53 UTC, mjfrey approved these changes
Once tests are fixed.

2017-04-24 10:25 UTC, vkaracic commented
@edx/helio this is ready for a second review.

2017-04-24 15:04 UTC, clintonb requested changes

2017-04-24 15:04 UTC, clintonb commented on ecommerce/extensions/api/v2/urls.py
> +router.register(r'offers', offer_views.OfferViewSet, base_name='offers')
You should not need the `base_name` kwarg.

2017-04-24 15:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/offers.py
> +                stock_records.append(StockRecord.objects.get(product=seat))
This shuould be `.filter()`, since the relationship is 1:m.

2017-04-24 15:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/offers.py
> +        for course in program['courses']:
This can be made more efficient.

```python
partner = self.site.siteconfiguration.partner
currency = settings.OSCAR_DEFAULT_CURRENCY

course_runs = []
for course in program['courses']:
  course_run += course_runs

product_query = reduce(
  lambda x, y: x | y,
  [Q(course__id=course_run['key'], attributes__name='certificate_type', attribute_values__value_text__in=seat_types) for course_run in course_runs]
)

stock_records = StockRecord.objects.filter(Q(partner=partner, price_currency=currency) & product_query)
```

2017-04-24 15:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/offers.py
> +        catalog = Catalog.objects.create(
Why are we copying program information to Otto? What happens if the program courses/course runs change? I would prefer that we read the info from the Catalog Service, and cache it for some period of time.

2017-04-24 15:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/offers.py
> +        for course in program['courses']:
Actually, the SKUs are in the API response. Use them.

2017-04-24 15:05 UTC, clintonb commented
We should avoid storing program details in the E-Commerce Service to avoid issues with data getting out-of-sync. Pull the info, and cache it, rather than storing it.

2017-04-25 07:58 UTC, vkaracic commented on ecommerce/extensions/api/v2/urls.py
> +router.register(r'offers', offer_views.OfferViewSet, base_name='offers')
Without it ``reverse`` can't find the pattern.

2017-04-27 10:13 UTC, vkaracic commented
@clintonb I think I've managed to address your comment with the last commit, so please take a look and let me know if that's the way to go. I'll adjust/add tests once I know I'm on the right track.

2017-05-02 12:11 UTC, mjfrey requested changes

2017-05-02 12:11 UTC, mjfrey commented on ecommerce/extensions/offer/models.py
> +            request = get_current_request()
Do not use this anymore, pass the request in and use it.

2017-05-02 12:11 UTC, mjfrey commented on ecommerce/extensions/offer/models.py
> +        return self.all_products()
why this change?

2017-05-09 07:54 UTC, closed without merging