Ecom 7646
openedx-unsupported/ecommerce pull request #1252
Opened 2017-04-26 11:08 UTC by Ayub-Khan

Test

2017-04-26 12:31 UTC, clintonb submitted a review, later dismissed

2017-04-26 12:31 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +        for order in orders:
You want to filter by RefundLine not Refund. Orders can have multiple items.

2017-04-26 12:31 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +            orders = OrderLine.objects.filter(
These are OrderLine objects not orders. Name your variable accordingly.

2017-04-26 12:31 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +                quantity=1,
Why does quantity matter?

2017-04-26 12:31 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +                line_price_incl_tax__gt=0,
Why does price matter?

2017-04-26 12:31 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +            if not Refund.objects.exists(order=order, status='Complete'):
This can probably be combined with the query above. Remember to account for the other statuses.

2017-04-26 12:31 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +    def user_already_placed_order(user, product):
This should accept an array or products.

2017-04-26 12:31 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +                # if have_already_placed_order(request.user, product):
This needs to work for multi-item view.

2017-04-26 12:40 UTC, Ayub-Khan commented on ecommerce/extensions/order/utils.py
> +                line_price_incl_tax__gt=0,
to avoid orders for audit enrollment

2017-04-26 12:40 UTC, Ayub-Khan commented on ecommerce/extensions/order/utils.py
> +                quantity=1,
to exclude enrollment code orders.

2017-04-26 12:41 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +                quantity=1,
Enrollment codes are a different product class.

2017-04-26 12:41 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
> +                # if have_already_placed_order(request.user, product):
edx allow multi-item purchase against single basket?

2017-04-26 12:42 UTC, clintonb commented on ecommerce/extensions/order/utils.py
> +                line_price_incl_tax__gt=0,
The odds of an audit enrollment coming through here are low. If they did, we really don't care if you buy it twice. If you really want to check for audit, check the product attributes.

2017-04-26 12:43 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +                # if have_already_placed_order(request.user, product):
Yes. Even if we didn't, we should never artificially limit our system.

2017-04-26 12:58 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
> +                # if have_already_placed_order(request.user, product):
ok

2017-04-26 13:08 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
> +                # if have_already_placed_order(request.user, product):
I have divided the work into steps.

- 1. Write code for Order check.
- 2. Write Tests for Order check.
- 3. Remove already existing Enrollment Check and its related code.
- 4. Update single-item view to use the Order Check and write tests.
- 5. Update Order check to work for multiple-item view.
- 6. Update multi-item view to use Order check and write tests.

let me know if you have any suggestions.

2017-04-26 13:08 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
> +                # if have_already_placed_order(request.user, product):
@adampalay @clintonb ^^

2017-04-26 14:10 UTC, mjfrey requested changes

2017-04-26 14:10 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> +                # if have_already_placed_order(request.user, product):
@Ayub-Khan I would move this check to prepare_basket.  Have that throw an exception and check for it in both single-item as well as multi-item views.  This way you have one place where you check for previous order.

2017-04-27 16:46 UTC, Ayub-Khan commented
Sorry just playing around with new git features

2017-05-04 17:20 UTC, mjfrey requested changes

2017-05-04 17:20 UTC, mjfrey commented on ecommerce/extensions/basket/utils.py
> +            logger.warning(
Please use the messaging framework to tell the user that products they already purchased will not be added to the basket. So it is not confusing to them.

2017-05-04 17:20 UTC, mjfrey commented on ecommerce/coupons/views.py
> +            return render(request, template_name, {'error': _('You are already enrolled in the course.')})
The message should be something like:
"You have already purchased these products"

2017-05-04 17:20 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> +            return HttpResponseBadRequest(_('You are already enrolled in courses.'))
Same here.  It is not the enrollment but the purchase that has already happened.

2017-05-05 11:46 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +            logger.warning(
done

2017-05-05 11:50 UTC, Ayub-Khan commented on ecommerce/extensions/order/utils.py
> +    def user_already_placed_order(user, product):
@clintonb as per @mjfrey advice it was implemented in prepare_basket so keeping this to take single input . Because we also log when user tries to purchase course seat again. So i think its batter if we keep logging in prepare_basket. because we might need tp use this in future on checkout view to prevent multiple_payment issue.

2017-05-09 10:34 UTC, Ayub-Khan commented
@clintonb  @mjfrey @noraiz-anwar I have added sandbox link. Kindly review.

2017-05-11 12:11 UTC, Ayub-Khan commented
As @clintonb @mjfrey have not reviewed this for a while adding new code reviewers.

2017-05-11 12:13 UTC, Ayub-Khan commented
@schenedx and @bderusha kindly review.

2017-05-11 14:25 UTC, mjfrey commented
The sandbox is not working for me.  It is not setup to use our e-commerce hosted basket page nor any payment processors.

2017-05-11 17:30 UTC, schenedx requested changes
Commented. Please see if my comments make sense

2017-05-11 17:30 UTC, schenedx commented on ecommerce/extensions/basket/utils.py
> +                product.is_enrollment_code_product:
Can you put the condition `product.is_enrollment_code_product` before the `UserAlreadyPlacedOrder.user_already_placed_order()` call? We want the shortcutting to happen

2017-05-11 17:30 UTC, schenedx commented on ecommerce/extensions/basket/views.py
> +            msg = _('You have already purchased this {course} seat.').format(course=product.course.name)
@Ayub-Khan What if the basket is `None` because of another error or condition that is different from `You already purchased`? Seems to me you are making the assumption that `None` basket means `already ordered`.
I am afraid this assumption is too implicit to understand.
Can we throw an exception in the `prepare_basket` function when the order is already placed, and then handle the exception here? I feel like Exception throwing and catching is the more explicit way of handling

2017-05-11 17:30 UTC, schenedx commented on ecommerce/extensions/basket/views.py
> +        if not basket:
Same comment here about using an exception to signal `already ordered` instead.

2017-05-11 17:30 UTC, schenedx commented on ecommerce/extensions/order/utils.py
> +                if not RefundLine.objects.filter(order_line=order_line).exists():
Can you move this statement into a new utility function? I can think of the function name to be `is_order_line_refunded`

2017-05-11 17:30 UTC, schenedx commented on ecommerce/extensions/order/utils.py
> +                    return True
I don't think we need this line. You can just do `return not is_order_line_refunded(order_line)`

2017-05-12 10:15 UTC, Ayub-Khan commented on ecommerce/extensions/order/utils.py
> +                    return True
@schenedx i did this to counter a edge case where order is multiple product order and there are multiple refund lines so if the first product is refunded in that case this method will return true even if user is trying to buy second product again. In that case that will fail.

2017-05-12 14:16 UTC, schenedx requested changes
I added more comments

2017-05-12 14:16 UTC, schenedx commented on ecommerce/extensions/basket/utils.py
>              )
Shouldn't we raise the `AlreadyPlacedOrderException` here instead of where it is now, out side of the loop?

2017-05-12 14:16 UTC, schenedx commented on ecommerce/extensions/order/utils.py
> +                    return True
You are right. My bad. Thanks for the explanation

2017-05-12 14:16 UTC, schenedx commented on ecommerce/extensions/basket/tests/test_utils.py
> +            self.assertIsNone(basket)
Can you also assert that exception `AlreadyPlacedOrderException` is raised?

2017-05-12 14:16 UTC, schenedx commented on ecommerce/extensions/basket/tests/test_utils.py
> +            self.assertIsNotNone(basket)
Can you also assert that exception `AlreadyPlacedOrderException` is also raised?

2017-05-15 06:37 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
>              )
In case of multiple-item basket we let user move forward for all products which are not paid. But if we place raise here system will break even if first product is already paid and none other.

2017-05-15 06:44 UTC, Ayub-Khan commented on ecommerce/extensions/basket/tests/test_utils.py
> +            self.assertIsNotNone(basket)
We let user purchase enrollment code products as many times as he wants so exception wont be raised.

2017-05-15 09:50 UTC, Ayub-Khan commented
@schenedx should i write extra tests for is_order_line_refunded?

2017-05-15 15:05 UTC, schenedx commented on ecommerce/extensions/basket/tests/test_utils.py
> +            self.assertIsNotNone(basket)
I see. If that's the test case, bad suggestion from me.

2017-05-15 15:08 UTC, schenedx commented
@Ayub-Khan If I were you, I would. You never know if a future iteration of the changes will use the function `is_order_line_refunded` else where.

2017-05-15 15:20 UTC, schenedx commented on ecommerce/extensions/basket/utils.py
> +        raise AlreadyPlacedOrderException
@Ayub-Khan I still have trouble on this logic.
The logic here tells me that, if we get an empty basket, no matter what the reason it is, we always show learner that `the order has been placed before` message. I feel like that's a dangerous assumption.
Why can't we do this:

1. Use a dictionary to store any product we encountered in the basket that was already ordered. After the loop, if we have dictionary to have members, and basket is empty, raise the `AlreadyPlacedOrderException` exception
2. If the dictionary have members, but we still have product in the basket, we can let user proceed with a different warning in the basket page telling user which products he has in the basket has been ordered before.
3. If the dictionary is empty, but basket is still empty, return `None`, and let caller handle an empty basket.
4. If the dictionary is empty, but basket has product, proceed as normal.

For point 2 above, I don't know if that would be a realistic case. @mjfrey @clintonb Can we make the assumption that we only have always 1 seat product in basket in all times?

2017-05-16 09:42 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +        raise AlreadyPlacedOrderException
@schenedx i have updated the prepare basket.

2017-05-22 09:42 UTC, Ayub-Khan commented
@mjfrey @clintonb @schenedx  I have updated the sandbox. You can confirm the changes.
fyi @adampalay

2017-05-22 11:23 UTC, mjfrey commented
The sandbox is still not working for me. I get 500 errors.  The sandbox is also not setup for client-side checkout as well as the otto hosted receipt page.

2017-05-22 13:10 UTC, Ayub-Khan commented
@mjfrey Kindly explain the steps you are taking to create an order and on which steps you get 500 errors, so that I can better reproduce and debug this issue. I'm not sure how to setup a sandbox for client-side checkout and otto hosted receipt page. Is there documentation for how to set this up? I haven't been able to find any. In the past, we've made PRs without checking these things on sandboxes—if you're confident with the code workflow, can we instead wait to test on stage?

2017-05-22 14:00 UTC, schenedx approved these changes
👍  LGTM

2017-05-22 18:43 UTC, schenedx commented
@Ayub-Khan Can you setup your sandbox with the following config values? https://gist.github.com/clintonb/c45f4136c26c03d1f4ed#file-ecom-private-py-L39-L66

2017-05-23 19:46 UTC, Ayub-Khan commented
@mjfrey I have updated the sandbox to use client-side checkout as well as otto hosted receipt page. But sadly i have been able to configure cybersource test account on my sandbox. Its still not working properly. But you can use the paypal to make a payment. 
Kindly use the following steps to confirm the changes on sandbox
1. login to sandbox using email: staff@example.com pass : edx
2. open "Upgrade to Verified" in new tab for course "Test Order Check 2"
3. click paypal for payment 
4. use any paypal sanbox test account to make payment for paypal
5. Notice the receipt page
6. Now from the other tab try to open "Upgrade to Verified" in new tab 
7. Notice the Error Page.
Thanks. 
fyi @schenedx

2017-05-24 15:17 UTC, mjfrey approved these changes
Just a minor comment.

2017-05-24 15:17 UTC, mjfrey commented on ecommerce/coupons/tests/test_views.py
> +            msg = 'You have already purchased this {course} seat.'.format(course=self.course.name)
"You have already purchased", please remove the "this"

2017-05-25 11:05 UTC, merged