Add basket calculate endpoint.
openedx-unsupported/ecommerce pull request #1256
Opened 2017-04-27 15:53 UTC by mjfrey

api/v2/basket/calculate
Creates a temporary basket, adds products and applies an optional voucher.
JSON is returned with the basket totals, including any discounts.

LEARNER-512

2017-04-27 18:44 UTC, mjfrey commented
@edx/helio please review

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +    def test_no_authorization(self):
`test_no_authentication`

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        """ Verify that un-authorized users are rejected """
un-authenticated

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +            'total_excl_discount': Decimal('29.97'),
Where is 29.97 coming from? This should be an explicit variable/constant rather than assumed.

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +            'total_discount': Decimal('10.00'),
`10` should be a variable.

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        """ Verify sucessfull basket calculation when passing a voucher """
successful

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +    """ Calculate basket totals given a list of sku's
What does this look like in Swagger? I suspect this needs to be on `get()`.

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        self.assertEqual(response.data, expected)
You should add a test for flat-rate discounts.

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +    renderer_classes = (JSONRenderer, )
Remove. This is the default renderer. There is no need to specify this.

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +
Remove this unnecessary newline.

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +                if basket.offer_discounts:
Why not both types of discounts? Today, we don't support applying both; however, we should avoid limiting this endpoint to one type.

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +                        discount_type = benefit.type
This assumes that all discounts are the same type, which isn't necessarily the case. Perhaps we should leave out the discount type and amount for now. We are returning the total and the total with discounts. The client can figure out how it wants to display the info.

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +                    'total_excl_discount': basket.total_incl_tax_excl_discounts,
total_incl_tax_excl_discounts

2017-04-27 19:13 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +                    'total_incl_discount': basket.total_incl_tax,
total_incl_tax

2017-04-28 07:46 UTC, marjev requested changes

2017-04-28 07:46 UTC, marjev commented on ecommerce/extensions/api/v2/views/baskets.py
> +        # This is to avaoid merging this temporary basket with a real user bakset.
`avoid`
`basket`

2017-04-28 07:46 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +            self.product_total += product.stockrecords.first().price_excl_tax
`self.product_total = sum(product.stockrecords.first().price_excl_tax for product in self.products)`

2017-04-28 07:46 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        """ Verify a successfull basket calculation with no offers"""
`successful`

2017-04-28 07:46 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +            'total_discount': Decimal('100.00'),
`self.product_total` instead of `Decimal('100.00')`?

2017-04-28 12:33 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +            'total_discount': Decimal('100.00'),
No

2017-04-28 12:35 UTC, mjfrey commented
@edx/helio another look please

2017-04-28 12:56 UTC, marjev approved these changes

2017-04-28 13:23 UTC, clintonb approved these changes
Please address my last comment before squashing and merging.

2017-04-28 13:23 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +                    'total_discount': total_discount,
Without the discount type, I don't see the value of including this field. We can add it later, if needed. For now, we can use a simple cross-out display of pricing.

Also, please include the currency field.

2017-04-28 13:32 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/baskets.py
> +                    'total_discount': total_discount,
@clintonb currency field?  Say more.

2017-04-28 13:56 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +                    'total_discount': total_discount,
Price has a currency (unit) and a value. We should never assume that we solely operate in USD.

Add: `'currency': basket.currency`

2017-04-28 15:18 UTC, merged