[WIP] -- ENT-354: 	Change Enterprise Customer coupon implementation from 'Range' to 'Custom Benefit'
openedx-unsupported/ecommerce pull request #1258
Opened 2017-04-28 11:21 UTC by saleem-latif

@mattdrayer can you take a look at this to see if I am on the right track ?

@brittneyexline , @asadiqbal08 , @zubair-arbi -- FYI

2017-04-28 12:41 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +        return self._description % {
We use `str.format()`.

2017-04-28 12:41 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +    # http://django-oscar.readthedocs.io/en/releases-1.4/howto/how_to_create_a_custom_benefit.html
Not really. The bulk of the class, `apply()`, is copied from `PercentageDiscountBenefit`. Why not simply inherit it?

2017-04-28 12:41 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +class EnterpriseCustomerUserPercentageBenefit(Benefit):
Similar to Oscar's benefit implementations, this class belongs in `benefits.py`. This will probably resolve your circular reference.

2017-04-28 12:41 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +        verbose_name = _("Percentage enterprise entitlement discount benefit")
Single quotes. `'Percentage discount benefit for enterprise customers'`

2017-05-01 13:53 UTC, mattdrayer commented
@saleem-latif this implementation looks a little different from the proto-work done in #1218 -- I'm not seeing a new ConditionalOffer class, which is something that was suggested by @clintonb and @mjfrey.  I'm not sure if we need that versus handling the conditional work inside of the Benefit's `apply()` method -- thoughts?

2017-05-03 12:08 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +        enterprise_learner = enterprise_utils.get_enterprise_learner(request.site, basket.owner.username)
basket.site. Please avoid get_current_request(). I'm not a fan of thread locals.

2017-05-03 12:08 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +        app_label = 'offer'
All you need is proxy. The rest of these will not be used since this isn't a real model.

2017-05-03 12:08 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +__all__ = [
This should not be necessary.

2017-05-03 12:08 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.conditions import *  # noqa isort:skip
We tend to avoid these. Import only what you need.

2017-05-03 12:08 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +        enterprise_learner = enterprise_utils.get_enterprise_learner(request.site, basket.owner.username)
basket.site

2017-05-03 12:08 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    # Get HttpRequest object for the ongoing request
This comment adds not value.

2017-05-03 12:08 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    request = get_current_request()
Pass the site as an argument to this function.

2017-05-03 12:08 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    Examples:
This example doesn't add much value. It's not needed given how simple the function is.

2017-05-04 12:57 UTC, saleem-latif commented
@clintonb In order to resolve pylint error `Old-style class defined. (old-style-class)`. I made [these](https://github.com/edx/ecommerce/pull/1258/files#diff-116bdef327d1558d6d967bafad78ca50R27) changes, Please let me know if I should use `pylint: disable=old-style-class` instead.

Previous: 
```
class Meta:
    proxy = True           
```

New:
```
class Meta(object):
    proxy = True           
```

2017-05-04 13:10 UTC, clintonb commented
@saleem-latif Inheriting from `object` is the proper thing to do in Python 2. What you have is correct.

2017-05-04 13:11 UTC, saleem-latif commented
@mattdrayer I have added offer conditions, please take a look and share your thoughts

2017-05-08 09:40 UTC, saleem-latif commented
@brittneyexline , @douglashall , @clintonb PR is ready for another review, kindly take a llok and share your thoughts.

2017-05-09 13:32 UTC, saleem-latif commented
@mjfrey Can you also take a look at the changes ?

2017-05-09 17:38 UTC, mjfrey requested changes

2017-05-09 17:38 UTC, mjfrey commented on ecommerce/extensions/offer/conditions.py
> +        enterprise_learner = enterprise_utils.get_enterprise_learner(basket.site, basket.owner.username)
you need to catch any exceptions that the API call to enterprise app may throw.  If so return False.

2017-05-09 17:38 UTC, mjfrey commented on ecommerce/extensions/offer/conditions.py
> +        enterprise_learner = enterprise_utils.get_enterprise_learner(basket.site, basket.owner.username)
same here.

2017-05-09 17:38 UTC, mjfrey commented on ecommerce/extensions/offer/benefits.py
> +class EnterpriseCustomerUserAbsoluteDiscountBenefit(benefits.AbsoluteDiscountBenefit):
Where are these new benefits used?

2017-05-09 18:16 UTC, clintonb requested changes
I am concerned that this may not work as expected. Using non-proxy models may cause issues when it comes time to actually apply the offer. I would like to see a test that creates a conditional offer with the custom condition and benefits, and actually applies the offer to a basket.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/benefits.py
> +    # Note that we are adding a new UUID field above -- I am assuming that this cannot be a proxy
That's correct. This comment can go away.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/benefits.py
> +        help_text='UUID for an EnterpriseCustomer from the Enterprise Service.'
This help text doesn't really say anything different from the field's name. It should go away. In the future, remember to mark the help text for translation.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +    _description = _("Enterprise learner has consented to data sharing.")
1. Use single quotes.
2. Move this to the `name` property.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +        return self._description
`return self.name`

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +
This newline is unnecessary.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +
This newline is unnecessary.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +    def is_partially_satisfied(self, offer, basket):  # pylint: disable=unused-argument
We aren't displaying any upsell messages. Neither this method nor `get_upsell_message` is necessary. These should be removed to avoid the unnecessary overhead of calling the Enterprise API for almost every page load.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.benefits import (  # noqa isort:skip pylint: disable=wrong-import-position,unused-import,ungrouped-imports
None of this is necessary.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +        # This means then learner just need to consent to get dispounts. so we show that message to
Typos. Also, we aren't currently displaying upsell messages.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +        username=str(username),
Nit: one line.
`username` is already a string.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    # filtering enterprise learners with empty username will return all learners.
It seems you are using the wrong API endpoint. Why not use `/enterprise-learners/<username>/`?

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +logger = logging.getLogger(__name__)
This is never used. However, you probably should have more logging around your API calls.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    response = endpoint.get(
What happens if this call raises an exception?

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    response = endpoint.get(
The response should be cached for some period of time to avoid performance issues.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/benefits.py
> +class EnterpriseCustomerUserPercentageBenefit(benefits.PercentageDiscountBenefit):
Custom models should almost always be exposed in Django admin.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/benefits.py
> +
This is not necessary.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/benefits.py
> +    enterprise_customer_uuid = models.UUIDField(
Extract this, and your `apply` method to a mixin shared by both classes.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        Common setup operations for each test case.
Docstrings on `setUp` and `tearDown` are unnecessary.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +class TestDataSharingConsentCondition(EnterpriseServiceMockMixin):
`DataSharingConsentConditionTests`

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +    Tests for data sharing consent offer condition.
This docstring doesn't tell us anything we don't already know from the class name. It can go away.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +from decimal import Decimal as D
Nit: I've never understood why folks shorten `Decimal` to `D`. Just use `Decimal`.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        self.range = models.Range.objects.create(
Use factories: `self.range = RangeFactory(includes_all_products=True)`

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        self.basket = factories.create_basket(empty=True)
`self.basket = BasketFactory(owner=self.learner, site=self.site)`

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        self.learner = self.create_user(is_staff=True)
Nit: we generally use `self.user`.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        @return:
Remove.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +    def test_name_and_description(self):
Split this into `test_name` and `test_description`.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        self.assertFalse(self.condition.is_satisfied(self.offer, self.basket))
1. If your condition doesn't rely on the offer parameter, either pass `None` or use `ConditionalOfferFactory`. Don't mock things unnecessarily.
2. Avoid using instance variables unnecessarily. Create an empty basket for this test case with `BasketFactory`.

`self.assertFalse(self.condition.is_satisfied(None, BasketFactory()))`

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +    def test_not_discountable_item_fails_condition(self):
I'm not sure of the value of this test. Your condition should not fail because the basket contains an item that is not discountable. It should only fail because data consent has not been granted. The items in the basket don't matter at all.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        self.basket.owner = None
You don't need `self.basket`. Just use `BasketFactory()`.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        add_product(self.basket, D('26'), product=self.item)
Products don't matter.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +        if basket.is_empty or not all(self.can_apply_condition(line) for line in basket.all_lines()):
Why does this condition care about the basket's contents?

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        add_product(self.basket, D('26'), product=self.item)
`self.basket.add_product(self.item)`

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        self.expensive_item = factories.create_product(price=D('15.00'))
This is never used, and should be removed.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +        self.item = factories.create_product(price=D('5.00'))
1. The price doesn't matter.
2. Use a name that helps describe what the variable represents.

`self.product = factories.create_product()`

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +from oscar.test.basket import add_product
This function isn't necessary. Use `Basket.add_product()`.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_conditions.py
> +    def _update_basket(self):
This method is not needed.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
>  from ecommerce.enterprise.utils import (enterprise_customer_user_needs_consent, get_enterprise_customer,
Drop the contained items to a new line.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +        Switch.objects.get_or_create(
Use `toggle_switch`

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +        self.assertIsNotNone(enterprise_learner)
You should check the returned value. `assertIsNotNone` is not good enough if the non-null value is still invalid.

2017-05-09 18:16 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +    def test_get_enterprise_learner_with_no_learner(self):
This isn't right.

2017-05-10 08:40 UTC, saleem-latif commented on ecommerce/extensions/offer/benefits.py
> +    enterprise_customer_uuid = models.UUIDField(
Function signature for `apply` of `benefits.PercentageDiscountBenefit` and `benefits.AbsoluteDiscountBenefit` is different. If I try to abstract away conflicting arguments using `*args` and `**kwargs` it would reduce readability. I think it would be better to leave apply function in both classes.

2017-05-10 09:28 UTC, saleem-latif commented on ecommerce/enterprise/utils.py
> +    # filtering enterprise learners with empty username will return all learners.
Currently, we have only `/enterprise-learners/<id>/` api endpoint and not `/enterprise-learners/<username>/`, There is a ticket open https://openedx.atlassian.net/browse/ENT-374 which might handle this case going forward. That is why currently we are using filtering to get enterprise learner.

2017-05-10 10:12 UTC, saleem-latif commented on ecommerce/extensions/offer/tests/test_conditions.py
> +from oscar.test.basket import add_product
We need `add_product` for `test_not_discountable_item_fails_condition` otherwise it raises `ValueError: Basket lines must all have stock records.`.
I have removed other occurrences of this

2017-05-10 13:44 UTC, saleem-latif commented on ecommerce/extensions/offer/benefits.py
> +
Done

2017-05-10 13:45 UTC, saleem-latif commented on ecommerce/extensions/offer/benefits.py
> +class EnterpriseCustomerUserPercentageBenefit(benefits.PercentageDiscountBenefit):
Done

2017-05-10 13:45 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.benefits import (  # noqa isort:skip pylint: disable=wrong-import-position,unused-import,ungrouped-imports
removing these causes isort check failure in quality

2017-05-10 13:50 UTC, saleem-latif commented
@clintonb I agree that we need to add an integration test for the newly added benefits and offer conditions, but we have that planned for a later story (https://openedx.atlassian.net/browse/ENT-380).
I tried adding a test but doing that requires some discovery work around conditional offers and their use. So, I am thinking that it would be better to add those tests as part of [ENT-380](https://openedx.atlassian.net/browse/ENT-380).

@mjfrey I hope this also answers your question about where to use these benefits.

2017-05-10 13:50 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.benefits import (  # noqa isort:skip pylint: disable=wrong-import-position,unused-import,ungrouped-imports
I'm referring to the new lines of code. This file does not need to be modified.

2017-05-10 13:53 UTC, clintonb commented
@saleem-latif this can't be merged until there is an integration test. You've created a bunch of code that may not work as you expect. Discovery around conditional offers should have been done before you started work on conditional offers. See https://github.com/edx/ecommerce/commit/e9d66122721424e2fea982389cf4fff0291057cd#diff-3fc00a5e5e9842eaee3b3266d1f0d597 for an example test.

2017-05-10 13:53 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.benefits import (  # noqa isort:skip pylint: disable=wrong-import-position,unused-import,ungrouped-imports
Okay, I will remove these

2017-05-11 09:11 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.benefits import (  # noqa isort:skip pylint: disable=wrong-import-position,unused-import,ungrouped-imports
I looked around removing these but we need benefits imports here for migrations to work properly. Also this style conforms to [django-oscar convention](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/models.py#L63-L64). So, I think we should leave these as is.

2017-05-11 09:12 UTC, saleem-latif commented
@mjfrey @clintonb I have added integration tests, please take a look.

2017-05-11 12:39 UTC, clintonb requested changes

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/migrations/0013_auto_20170511_0838.py
> +        migrations.AlterField(
Why is this field being altered?

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +    name = unicode(_('Enterprise learner has consented to data sharing.'))
Remove the usage of `unicode()`. The translations will never be used since the string will be cast to Unicode (which is the output of `ugettext_lazy`) when the class is loaded.

Also, remove the period.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.benefits import (  # noqa isort:skip pylint: disable=wrong-import-position,unused-import,ungrouped-imports
Please explain how removing these affects migrations. That is a sign of something wrong. I am concerned that this will lead to circular import issues down the road. Given that these models are not used in this code, the imports should not be here.

We don't follow that particular convention of Oscar because we generally avoid `import *`. You're not even following the convention here because you haven't extended `__all__`.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_benefits.py
> +from ecommerce.tests.factories import (EnterpriseCustomerUserAbsoluteDiscountBenefittFactory,
Drop the enclosed items to a new line to avoid long indentations.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/tests/factories.py
> +
Move all of this to `ecommerce/extensts/test/factories.py`.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/tests/factories.py
> +    enterprise_customer_uuid = 'b0990312-c5a3-48c4-b0fe-b8d844249623'
Don't hard-code this. Use `factory.LazyFunction(uuid.uuid4)`

2017-05-11 12:39 UTC, clintonb commented on ecommerce/tests/factories.py
> +    type = get_model('offer', 'Benefit').PERCENTAGE
Set `Benefit = get_model('offer', 'Benefit')` at the top of the file.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/tests/factories.py
> +        model = get_model('offer', 'EnterpriseCustomerUserPercentageBenefit')
Your custom models are not dynamic. Import them as you would any non-Oscar class.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_benefits.py
> +        self.benefit = EnterpriseCustomerUserPercentageBenefitFactory(
Let your factory do the work: `self.benefit = EnterpriseCustomerUserPercentageBenefitFactory()`

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_benefits.py
> +        benefit = EnterpriseCustomerUserPercentageBenefitFactory(
As above, use the values from the factory. Only override what is absolutely necessary.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_benefits.py
> +            start_datetime=datetime.datetime.now(), end_datetime=datetime.datetime.now() + datetime.timedelta(days=1),
Neither the name nor dates need to be overwritten.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_benefits.py
> +        path = reverse('api:v2:baskets:calculate')
Why are you using this endpoint? I provided an example does not involve an API call, and properly validates each line item in the basket. It would be ideal if you followed that model so that we actually test what we want to test: the basket discounts.

2017-05-11 12:39 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_benefits.py
> +        (False, False, 3, Decimal('20.00'), Decimal('24.00')),
Break this into three tests:

1. Consent disabled.
2. Consent enabled, but not provided.
3. Consent enabled, and provided.

Use helper methods to avoid duplication. As written, it is not totally clear what you are testing in each of these cases. Three months from now it won't make any sense.

Do the same for the test below.

Also, since you are testing more than benefits, move this to a new file, `test_offer.py`, similar to what we did for `programs`.

2017-05-11 13:33 UTC, saleem-latif commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.benefits import (  # noqa isort:skip pylint: disable=wrong-import-position,unused-import,ungrouped-imports
If we remove these imports then migrations are not created, and if we remove these at this point then future changes to the benefit models will not be registered, my understanding is that django searches for models in models.py

2017-05-11 13:35 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +from ecommerce.extensions.offer.benefits import (  # noqa isort:skip pylint: disable=wrong-import-position,unused-import,ungrouped-imports
Go it. Thanks for clarifying. Please add that comment in this file to avoid future confusion.

2017-05-12 05:57 UTC, saleem-latif commented on ecommerce/extensions/offer/migrations/0013_auto_20170511_0838.py
> +        migrations.AlterField(
Field was being altered because migration for `offer.Condition` contained `verbose_name='Program UUID'` in the migration ([added here](https://github.com/edx/ecommerce/pull/1262/files#diff-3b5e7b36f57ff6196a43ba289ce6ef12R18)) but the same verbose name was not present in the model definition [added here](https://github.com/edx/ecommerce/pull/1262/files#diff-49b6e1e79e2754be1784cc6dc9a1fe84R321). Not sure what caused this, but my guess would be that migration for `offer.Condition` was created when verbose_name was present in models definition and later removed (but migrations were not updated).
There are two approaches forward here
1. Do not update `offer.Condition`. This way `AlterField` migration will pop up (as is happening currently)
2. Add `verbose_name='Program UUID'` in the `program_uuid` field of `offer.Condition`

Which one do you prefer ?

2017-05-12 11:16 UTC, saleem-latif commented
@clintonb please take a look, I have incorporated your feedback.

2017-05-12 11:36 UTC, clintonb commented on ecommerce/extensions/offer/migrations/0013_auto_20170512_0558.py
> +        migrations.AlterField(
This will be fixed by https://github.com/edx/ecommerce/pull/1272.

2017-05-12 11:40 UTC, clintonb commented on ecommerce/extensions/offer/benefits.py
> +class EnterpriseCustomerUserAbsoluteDiscountBenefit(benefits.AbsoluteDiscountBenefit):
Digging deeper (both in the code and my understanding of Oscar): these should be conditions, not benefits. By the time we get to applying a benefit, we should know if it's going to be applied. A custom condition is what you want to determine if the basket/user meets the conditions for applying an offer.

2017-05-12 13:05 UTC, saleem-latif commented on ecommerce/extensions/offer/migrations/0013_auto_20170512_0558.py
> +        migrations.AlterField(
I have rebased it, migration is fixed

2017-05-15 08:27 UTC, saleem-latif commented
@clintonb can you please take another look.

2017-05-15 13:42 UTC, clintonb requested changes
@saleem-latif the suggestion to re-implement this as a custom benefit was not fully-informed. Given that you want to determine if a user is eligible for an offer, you want to create custom `Condition` models, not `Benefit`. You can use the existing `Benefit` models. If you continue down this route, using data consent as your sole condition, you run the risk of breaking other site-wide offers.

@mattdrayer @douglashall it might help if we get a better understanding of how you intend to use offers now and in the future.

FYI @mjfrey

2017-05-15 13:42 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
>  from ecommerce.enterprise.utils import (enterprise_customer_user_needs_consent, get_enterprise_customer,
Drop the contained items to a new line, and de-indent.

2017-05-15 13:42 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +        except (ConnectionError, SlumberBaseException, Timeout):
What about other exceptions?

2017-05-15 13:42 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +            logger.exception('Failed to retrieve learner data for "%s"', basket.owner.username)
We tend to use square brackets rather than double-quotes. Also, this needs to be a bit more informative:
`Failed to retrieve learner [username] from Enterprise API for site [site.name].`

2017-05-15 13:42 UTC, clintonb commented on ecommerce/extensions/offer/conditions.py
> +from ecommerce.enterprise import utils as enterprise_utils
Add a newline above this one.

2017-05-15 13:42 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    return results[0] if results else None
This is a code smell. Rather than return a special value, you should raise an exception (e.g. `EnterpriseUserNotFound`). Otherwise, you run the risk that someone uses this method and misses the fact that a special value is returned. An exception is hard to miss.

2017-05-15 13:42 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    if not is_enterprise_feature_enabled():
Move this upstream. Keep your utility methods as simple and specific as possible. Utilities should not care about features being enabled. That responsibility belongs at a higher level.

2017-05-15 13:42 UTC, clintonb commented on ecommerce/extensions/offer/admin.py
> +    list_display = ('type', 'value', 'range', 'enterprise_customer_uuid')
`'type'` will always be the same for these instances. It can go away. The same applies to the model below.

2017-05-16 07:26 UTC, saleem-latif commented
@clintonb If we use existing benefits than I do not think we would be able associated a benefit to enterprise customer. For enterprise learners we also want custom analytics events and reports like
1. Total of the enterprise entitlements applied 
2. Time stamps for entitlement application for enterprise learners (This data will be dependent on data sharing consent states of customer and learner)
3. (potential use case) Cost limits applied by enterprise customer (unique for every customer), entitlements should not work after the limit has been exhausted and enterprise customer should be notified accordingly.

There might be other use cases that I am not aware of at this point or that might come up as we move forward with enterprise functionality.

2017-06-01 02:11 UTC, clintonb commented
What's the deal with this? Why isn't it done?

2017-06-01 09:10 UTC, douglashall commented
@clintonb It has been deprioritized for other work at the moment. We will pick this back up soon.

2017-10-11 14:39 UTC, douglashall commented
Closing in favor of https://github.com/edx/ecommerce/pull/1475.

2017-10-11 14:39 UTC, closed without merging