Added program offer administrative views
openedx-unsupported/ecommerce pull request #1262
Opened 2017-05-03 04:02 UTC by clintonb

These views allow staff to create, read, and update conditional offers for programs.

LEARNER-435

2017-05-03 04:06 UTC, clintonb commented
This is intended to replace https://github.com/edx/ecommerce/pull/1254 and https://github.com/edx/ecommerce/pull/1248.

2017-05-03 04:13 UTC, clintonb commented
![screen shot 2017-05-03 at 12 12 54 am](https://cloud.githubusercontent.com/assets/910510/25648018/461c0fc2-2f95-11e7-90cb-ab2f5a2242b6.png)
![screencapture-localhost-18130-program-offers-new-1493784609309](https://cloud.githubusercontent.com/assets/910510/25647999/2c7d45ae-2f95-11e7-8f3d-4441b7e3d2a9.png)
![screencapture-localhost-18130-program-offers-new-1493784659328](https://cloud.githubusercontent.com/assets/910510/25648000/2c807a12-2f95-11e7-8b7e-bb369c97bf14.png)
![screencapture-localhost-18130-program-offers-6-edit-1493784642490](https://cloud.githubusercontent.com/assets/910510/25647998/2c7c21ba-2f95-11e7-8cf7-ae2c0e9ccb35.png)

2017-05-03 04:14 UTC, clintonb commented
FYI @edx/helio

2017-05-03 08:40 UTC, vkaracic commented
Perhaps add a human readable title/name for a program so that someone can more easily search and distinguish programs. Something similar like course name field.

2017-05-05 09:44 UTC, iivic commented on ecommerce/program_offers/views.py
> +                'uuid': self.object.condition.program_uuid,
The uuid is already in the context. Why do we need this?

2017-05-05 10:32 UTC, clintonb commented on ecommerce/program_offers/views.py
> +                'uuid': self.object.condition.program_uuid,
See the TODO above. The goal is to provide more program details. This is merely a placeholder.

2017-05-05 12:40 UTC, clintonb commented on ecommerce/program_offers/conditions.py
> +                raise Exception('Unable to connect to Course Catalog service.')
Don't change the exception type unnecessarily. Instead, log the error and re-raise the exception:

```python
logger.error(...)
raise
```

2017-05-05 12:42 UTC, clintonb commented on ecommerce/program_offers/conditions.py
> +        cache_key = hashlib.md5(
There is no need to hash the key given that we know the characters are all ASCII.

2017-05-05 18:34 UTC, clintonb commented
@edx/helio please review

2017-05-08 09:00 UTC, iivic approved these changes
A few comments left but it's looking good. Good job 👍

2017-05-08 09:00 UTC, iivic commented on ecommerce/program_offers/conditions.py
> +    def _program(self, site_configuration):
We will probably need programs in different places as well. Maybe moving this to an utils module could be helpful in the future?

2017-05-08 09:00 UTC, iivic commented on ecommerce/program_offers/conditions.py
> +            # Remove this course's SKUs the set of basket SKUs under consideration.
This comment is confusing. Please rewrite it or even remove it.

2017-05-08 09:00 UTC, iivic commented on ecommerce/program_offers/views.py
> +from django.utils.translation import ugettext_lazy as _
Use ugettext instead of ugettext_lazy.

2017-05-08 11:42 UTC, iivic requested changes
A migration is still missing.

2017-05-08 17:12 UTC, clintonb commented on ecommerce/program_offers/views.py
> +from django.utils.translation import ugettext_lazy as _
Both functions produce similar output. `ugettext_lazy` is used here because we don't want the value of `ProgramOfferCreateView.success_message` to be evaluated too soon. I have seen issues in the past with `ugettext` breaking on class fields, and I'd like to avoid recreating those issues.

2017-05-08 17:12 UTC, clintonb commented on ecommerce/program_offers/conditions.py
> +            # Remove this course's SKUs the set of basket SKUs under consideration.
Updated.

2017-05-08 17:16 UTC, clintonb commented on ecommerce/program_offers/conditions.py
> +    def _program(self, site_configuration):
I prefer to optimize for that situation when it arises. At the moment I don't fully understand the future use case(s).

2017-05-09 11:20 UTC, vkaracic reviewed
Reviewed ~1/4 of the changes just to realize that this PR is way too large to be effectively reviewed in one sitting.

2017-05-09 11:20 UTC, vkaracic commented on ecommerce/core/models.py
> +        # TODO Use URL from SiteConfiguration model.
Are you going to do this in this PR?

2017-05-09 11:20 UTC, vkaracic commented on ecommerce/extensions/test/factories.py
> +    type = ''
If this is an absolute discount benefit shouldn't the type be ``Benefit.ABSOLUTE`` here and ``Benefit.PERCENTAGE`` down below?

2017-05-09 11:20 UTC, vkaracic commented on ecommerce/programs/api.py
> +            program = self.client.programs(program_uuid).get()
I don't see the usual exceptions (``ConnectionError``, ``Timeout``, ``SlumberException``) getting caught anywhere where this method is used. It might be good to handle those cases.

2017-05-09 12:50 UTC, iivic commented on ecommerce/programs/api.py
> +            program = self.client.programs(program_uuid).get()
We concluded that it's unnecessary. Instead we will let it bubble up since it's not expected to happen often but if it happens the edx staff knows how to report issues.

2017-05-09 12:56 UTC, iivic approved these changes

2017-05-09 13:20 UTC, clintonb commented on ecommerce/extensions/test/factories.py
> +    type = ''
We are using a custom benefit. No type is necessary. See https://django-oscar.readthedocs.io/en/releases-1.4/howto/how_to_create_a_custom_benefit.html.

2017-05-09 13:22 UTC, clintonb commented on ecommerce/core/models.py
> +        # TODO Use URL from SiteConfiguration model.
Probably not. As you pointed out, this PR is already large enough.

2017-05-09 13:27 UTC, clintonb commented on ecommerce/programs/api.py
> +            program = self.client.programs(program_uuid).get()
If consuming code needs that exception handling, it can add it. For the initial version, at least, we aren't going to bother with exception handling. If the  Programs API is not reachable, we have bigger problems than worrying about the admin UX during such an outage.

2017-05-10 00:32 UTC, mjfrey approved these changes

2017-05-10 00:35 UTC, merged

2017-09-17 14:17 UTC, douglashall commented on ecommerce/programs/conditions.py
> +    def get_applicable_lines(self, offer, basket, most_expensive_first=True):
@clintonb Can you remember the reason why you implemented this function here? It looks logically equivalent to the implementation on [AbstractCondition](https://github.com/django-oscar/django-oscar/blob/1.4/src/oscar/apps/offer/abstract_models.py#L749). What am I missing?