[LEARNER-618] Coupon discount should supersede base Program discount
openedx-unsupported/ecommerce pull request #1263
Opened 2017-05-03 11:25 UTC by vkaracic

Since we don't have official program discounts yet, I'm going with the assumption that they are going to be site-wide offers. I've created a 33% off site-wide offer and a 15% voucher offer, the way they behave after applying this PR is shown below:

![out-1](https://cloud.githubusercontent.com/assets/2808092/25658452/3662451a-3003-11e7-8584-d7b14152860c.gif)

FYI: @edx/helio

2017-05-03 11:26 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1263&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-05-03 11:27 UTC, marjev approved these changes

2017-05-03 12:33 UTC, clintonb requested changes

2017-05-03 12:33 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> +        self.request.basket.reset_offer_applications()
Don't do this until after the voucher has been validated; otherwise, you break site-wide offers when the user enters an invalid code. This line should be right above line 420. It should also have a comment explaining why it is necessary.

2017-05-03 12:33 UTC, clintonb commented on ecommerce/extensions/test/factories.py
> +            name='PrepareVoucherOffer',
Drop the name given that the factory will make one for you.

2017-05-03 12:33 UTC, clintonb commented on ecommerce/extensions/test/factories.py
>              name='PrepareVoucherOffer',
Drop the name given that the factory will make one for you.

2017-05-03 12:33 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.view.apply_voucher_to_basket(voucher)
Please call the views via URLs (e.g. `self.client.get(...)`). I recall this sort of testing making the Django/Oscar upgrades unnecessarily difficult. Although these are unit tests, and going through URLs might be considered a functional test, going through URLs is how the user will actually experience the product. We should do our best to mimic actual behaviors in our tests (especially given our poor track record with acceptance tests).

2017-05-03 12:33 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.assertEqual(self.basket.total_discount, voucher_discount)
Use the `Basket.offer_discounts` and `Basket.voucher_discounts` to ensure that your offers are actually applied (or not applied). Otherwise, an offer made by another test could fool this assertion. It's a stretch, I know, but we should be explicit as possible about what we are validating.

2017-05-04 13:39 UTC, vkaracic commented
@clintonb comments addressed!

2017-05-04 14:08 UTC, clintonb reviewed
I'm ready to approve once the final comment is addressed.

2017-05-04 14:08 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.assertEqual(len(basket.voucher_discounts), voucher_discount)
Just as the basket value wasn't really relevant in the first iteration, the number of discounts is not relevant here. We want to assert that the discount we applied is actually applied.

2017-05-04 14:27 UTC, vkaracic commented
@clintonb take another look.

2017-05-04 14:43 UTC, clintonb approved these changes
Please update `assert_basket_discount`.

2017-05-04 14:43 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        for offer in basket.applied_offers().values():
This for-loop seems odd. Consider the following:

```python
def assert_basket_discounts(self, expected_offer_discounts=None, expected_voucher_discounts=None):
  expected_offer_discounts = expected_offer_discounts or []
  expected_voucher_discounts = expected_voucher_discounts or []

  response = self.client.get(reverse('basket:summary'))
  basket = response.context['basket']

  self.assertEqual(basket.offer_discounts, expected_offer_discounts)
  self.assertEqual(basket.voucher_discounts, expected_voucher_discounts)
```

2017-05-05 08:31 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        for offer in basket.applied_offers().values():
The problem with that is that `offer_discounts` and `voucher_discounts` don't return a list of offers, but of dictionaries, example:
```
[{'description': None, 'offer': <ConditionalOffer: esse>, 'name': u'esse', 'discount': Decimal('10.00'), 'voucher': <Voucher: distinctio>, 'freq': 1, 'result': BasketDiscount(Decimal('10.00'))}]
```

2017-05-05 10:37 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        for offer in basket.applied_offers().values():
`actual = [discount['offer'] for discount in basket.offer_discounts]`

2017-05-05 11:04 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_views.py
> +        for offer in basket.applied_offers().values():
D'oh! Thanks.

2017-05-05 11:55 UTC, merged