[WIP] Add Coupon creation for Programs.
openedx-unsupported/ecommerce pull request #1270
Opened 2017-05-11 14:37 UTC by mjfrey

Add support to create Coupons given a Program UUID.

LEARNER-938

2017-05-12 00:53 UTC, mjfrey commented
@edx/helio please review.

2017-05-12 10:30 UTC, vkaracic requested changes
You are missing tests for updating a coupon's program UUID. Also you could add an integration tests where you send the required data to the coupon create API endpoint and assert that everything is created as it's suppose to be.

2017-05-12 10:30 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        program_voucher_offers = program_vouchers.first().offers
You don't seem to be be using ``program_voucher_offers`` anywhere.

2017-05-12 10:30 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +    def create_program_coupon(self, coupon_title, quantity, program_uuid, course_seat_types):
This is unnecessary, you're just renaming ``create_coupon`` to ``create_program_coupon``.

2017-05-12 10:30 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
>              if benefit_value:
What happens if only the ``program_uuid`` is sent for an update?

2017-05-12 10:33 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +    def update_coupon_benefit_value(self, benefit_value, coupon, vouchers, program_uuid=None):
Add program_uuid to the docstring.

2017-05-12 10:33 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
> +            offer_benefit.proxy_class = proxy_class
Can you use the [class](https://github.com/edx/ecommerce/blob/master/ecommerce/programs/benefits.py) directly instead of doing this? I mean replace the `Benefit()` with `PercentageDiscountBenefitWithoutRange()` or `AbsoluteDiscountBenefitWithoutRange()?`

2017-05-12 10:33 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
> +                         email_domains=None, program_uuid=None):
Add `program_uuid` to docstring.

2017-05-12 11:11 UTC, mjfrey commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        program_voucher_offers = program_vouchers.first().offers
I do on the next line.

2017-05-12 11:12 UTC, mjfrey commented on ecommerce/extensions/voucher/utils.py
> +            offer_benefit.proxy_class = proxy_class
This is better.

2017-05-12 11:13 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        program_voucher_offers = program_vouchers.first().offers
What I wanted to say is that you could get away with ``program_voucher_offer = program_vouchers.first().offers.first()``.

2017-05-12 11:14 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/coupons.py
>              if benefit_value:
Right, I think you need both program_uuid and benefit value?  Is that correct @vkaracic

2017-05-12 11:19 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
>              if benefit_value:
That depends on how you wanted your update logic to work. If you want to able to just adjust the program UUID then you don't need the benefit value (which wouldn't be in the request data anyway). Also be careful if you use ``program_uuid and benefit_value`` updating the non-program coupon benefit values won't work.

2017-05-12 11:55 UTC, clintonb commented on ecommerce/extensions/voucher/utils.py
> +            offer_benefit.proxy_class = proxy_class
@iivic this is the Oscar-recommended method to create a custom `Benefit`.

2017-05-12 11:57 UTC, clintonb commented on ecommerce/extensions/voucher/utils.py
> +        if not program_uuid:
Nit: Invert so the positive check comes first `if program_uuid:`

2017-05-16 14:57 UTC, iivic commented
@edx/helio Please take another look.

2017-05-17 12:44 UTC, vkaracic reviewed
Mostly nits left.

2017-05-17 12:44 UTC, vkaracic commented on ecommerce/extensions/api/serializers.py
> +        return retrieve_range(obj).catalog_query if retrieve_range(obj) else None
Perhaps this instead of calling the chain of commands twice:
```
range = retrieve_range(obj)
return range.catalog_query if range else None
```

2017-05-17 12:44 UTC, vkaracic commented on ecommerce/extensions/api/serializers.py
> +        return retrieve_range(obj).course_catalog if retrieve_range(obj) else None
Same here.

2017-05-17 12:44 UTC, vkaracic commented on ecommerce/extensions/api/serializers.py
> +        return retrieve_range(obj).enterprise_customer if retrieve_range(obj) else None
Same here.

2017-05-17 12:44 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(Condition.objects.filter(program_uuid=self.data['program_uuid']).count(), 1)
From this line upwards you have almost the same code that you have in the test above. Either DRY it or don't test same things twice.

2017-05-17 12:44 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +            ).update(program_uuid=program_uuid)
Perhaps you don't need to change this method. Just move the condition update code to the update method directly.
```
program_uuid = request.data.get('program_uuid')

if program_uuid:
  voucher_offer = vouchers.first().offers.first()
  Condition.objects.filter(
      program_uuid=voucher_offer.condition.program_uuid
  ).update(program_uuid=program_uuid)
```

2017-05-17 12:44 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +import uuid
There should be a space between special imports and standard library ones.

2017-05-17 13:13 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(Condition.objects.filter(program_uuid=self.data['program_uuid']).count(), 1)
It's part of what I'm testing. I'm just making sure that the Benefit and Condition count is the same after updating the program_uuid. Relying on another test to check that seems silly.
Regarding the DRY... I don't like coupling tests I think it's smarter to keep every test for itself.

2017-05-17 13:17 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(Condition.objects.filter(program_uuid=self.data['program_uuid']).count(), 1)
Actually in the upper test you are testing that the coupon is created and in this one you're testing that the coupon is created + coupon has been updated. Makes perfect sense to factor our the almost identical piece of code into a custom assert method.

2017-05-17 13:27 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(Condition.objects.filter(program_uuid=self.data['program_uuid']).count(), 1)
Readability is also a factor so people that are looking at the code for the first time can see what is going on instead of switching between lines of code. I don't think the trade that we get with DRY is justified.
If you insist I will make the change but I would like to keep it as is.

2017-05-17 14:52 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +        return retrieve_range(obj).catalog_query if retrieve_range(obj) else None
The pattern in the comment above should be followed to avoid calling `retrieve_range` twice. Use `offer_range` instead of `range` to avoid conflicting with the standard library function.

2017-05-17 14:52 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +        course_seat_types = offer_range.course_seat_types
You run the risk of returning an empty string. This means we have three potential return types: null, empty string, an array. It would be ideal if we returned a single type.

```python
def get_course_seat_types(self, obj):
  seat_types = []
  offer_range = retrieve_range(obj)

  if offer_range:
    course_seat_types = offer_range.course_seat_types or ''
    seat_types = course_seat_types.split(',')

  return seat_types
```

2017-05-17 14:52 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +            return None
See comment above. We should return one data type.

2017-05-18 07:28 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.assertEqual(Condition.objects.filter(program_uuid=self.data['program_uuid']).count(), 1)
Leave it as is, since you're so passionate about it :smile:

2017-05-18 09:36 UTC, iivic commented
One more review.

2017-05-18 13:16 UTC, mjfrey commented
I can not approve since I started this PR.  But LGTM. 👍

2017-05-18 13:46 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +                self.update_coupon_offer(benefit_value=benefit_value, vouchers=vouchers,
Why are you updating this method?

2017-05-18 13:56 UTC, marjev approved these changes

2017-05-19 08:33 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
> +            proxy_class = class_path(BENEFIT_MAP[benefit_type])
Since you're only using this if there is a benefit, I'd move it into the if-block below.

2017-05-19 08:34 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
> +            offer_benefit, __ = Benefit.objects.get_or_create(
What happens if you only update the benefit value of a program coupon, would this create a new benefit for the same coupon?

2017-05-19 08:38 UTC, vkaracic approved these changes
If you want to treat the update as a PATCH (partial) update, you'll still need to account for scenarios where other than the program UUID fields are updated.
If NOT (since our UI sends all the fields on the update now), I guess you're good to go.

2017-05-19 09:30 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
> +            proxy_class = class_path(BENEFIT_MAP[benefit_type])
It's used in the next line.

2017-05-19 09:31 UTC, iivic commented
@vkaracic Nice catch. I will merge it as is so we have something out but we have to take care of it. I will bring it up on standup.

2017-05-19 10:36 UTC, merged