[LEARNER-936] discount name on receipt page
openedx-unsupported/ecommerce pull request #1283
Opened 2017-05-19 12:56 UTC by vkaracic

https://openedx.atlassian.net/browse/LEARNER-936

@edx/helio please review.

2017-05-19 12:56 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1283&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-05-19 12:57 UTC, vkaracic commented
Here are screenshots of the change:
![screenshot from 2017-05-19 14-56-33](https://cloud.githubusercontent.com/assets/2808092/26248634/71d96ebe-3ca3-11e7-891f-6845548bce7f.png)
![screenshot from 2017-05-19 14-56-45](https://cloud.githubusercontent.com/assets/2808092/26248635/71f5e012-3ca3-11e7-8ea7-6da065a68d96.png)

2017-05-19 12:57 UTC, mjfrey commented
@vkaracic screenshot?

2017-05-19 12:59 UTC, marjev approved these changes

2017-05-19 13:01 UTC, mjfrey requested changes

2017-05-19 13:01 UTC, mjfrey commented on ecommerce/extensions/checkout/views.py
> +                program = client.get_program(offer.condition.program_uuid)
Need to catch an error here and if so the receipt page should just say "Discount for Program"

2017-05-19 13:25 UTC, clintonb requested changes
Simplify.

2017-05-19 13:25 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                program_discount_text = 'Discount for the {program_title} {program_type} Program'.format(
We should avoid special use cases for rendering whenever possible. Every if statement poses two new branches that need to be tested. Set the name on the conditional offer instance at https://github.com/edx/ecommerce/blob/master/ecommerce/programs/forms.py#L75. If the program name/type changes in the future, folks can simply re-save the model.

2017-05-22 09:53 UTC, vkaracic commented
@clintonb take a look at the last commit, let me know if this is more appropriate.

2017-05-22 11:14 UTC, mjfrey approved these changes

2017-05-22 12:58 UTC, clintonb requested changes
Please post screenshots for the mobile, tablet, and desktop views of the receipt page.

2017-05-22 12:58 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +ConditionalOffer = get_model('offer', 'ConditionalOffer')
No changes need to be made to this file.

2017-05-22 12:58 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +from ecommerce.programs.tests.mixins import ProgramTestMixin
These changes are not necessary.

2017-05-22 12:58 UTC, clintonb commented on ecommerce/programs/forms.py
> +            offer_name = 'Discount for the {program_title} {program_type} Program'.format(
Mark for translation.

2017-05-22 12:58 UTC, clintonb commented on ecommerce/programs/forms.py
> +        except:  # pylint: disable=bare-except
Don't catch anything here. We don't want an offer with an invalid name in our system. Let the failure escalate to the user.

2017-05-22 12:58 UTC, clintonb commented on ecommerce/static/sass/partials/views/_receipt.scss
> +
Is this needed?

2017-05-22 12:58 UTC, clintonb commented on ecommerce/programs/tests/test_forms.py
> +        self.assertIn(program_title, offer.name)
Check the full name. New challenge for you: only use `assertIn` when checking the contents of a dict, or list.

2017-05-22 12:58 UTC, clintonb commented on ecommerce/programs/tests/mixins.py
> +            'title': program_title,
Nit: either hardcode this or use `Faker`. There isn't a good reason to pass these values as `kwargs`.

2017-05-22 12:58 UTC, clintonb commented on ecommerce/programs/tests/test_forms.py
> -        self.assertEqual(offer.name, 'Discount for program {}'.format(program_uuid))
Restore this, and pass in the program title and type. Alternatively, you can make a new method, `assertOfferName`, that is called separately from this one.

2017-05-22 12:59 UTC, clintonb commented
Never mind. I see the screenshots.

2017-05-22 13:04 UTC, vkaracic commented on ecommerce/programs/forms.py
> +        except:  # pylint: disable=bare-except
Should I at least log the exception?

2017-05-22 13:06 UTC, vkaracic commented on ecommerce/static/sass/partials/views/_receipt.scss
> +
You mean the blank line? It is, before each new selector.
If you mean the `line-height` change, then yes, otherwise the characters overlap.

2017-05-22 13:12 UTC, vkaracic commented on ecommerce/programs/tests/mixins.py
> +            'title': program_title,
I'll hardcode it, no need to introduce another dependency.

2017-05-22 13:26 UTC, clintonb commented on ecommerce/programs/forms.py
> +        except:  # pylint: disable=bare-except
Nope. That will happen when the failure bubbles up to the user level.

2017-05-22 14:07 UTC, vkaracic commented
@clintonb comments addressed!

2017-05-22 15:24 UTC, clintonb approved these changes
Address the latest comments, and squash your commits.

2017-05-22 15:24 UTC, clintonb commented on ecommerce/programs/forms.py
> +logger = logging.getLogger(__name__)
Remove.

2017-05-22 15:24 UTC, clintonb commented on ecommerce/programs/tests/test_forms.py
> +        self.assertEqual(str(offer.name), 'Discount for the Test Program MicroMockers Program')
No need for `str()`.

2017-05-22 15:24 UTC, clintonb commented on ecommerce/programs/tests/test_forms.py
> +        httpretty.enable()
Use the decorator on the appropriate test methods to ensure `httpretty` is disabled when tests finish.

2017-05-22 15:29 UTC, vkaracic commented on ecommerce/programs/tests/test_forms.py
> +        self.assertEqual(str(offer.name), 'Discount for the Test Program MicroMockers Program')
Actually yes there is. Without it the string gets compared with the gettext function representation.

2017-05-22 16:30 UTC, merged