Upgrade ecommerce service to Django 1.10.
openedx-unsupported/ecommerce pull request #1286
Opened 2017-05-22 12:00 UTC by adeelkhan

LEARNER-944
Subtask for LEARNER-480

WIP - Upgrades ecommerce service from 1.9.13 to 1.10.7

2017-05-22 13:10 UTC, clintonb commented
Make sure you review all of the release notes, and run `makemigrations`.

2017-05-24 15:33 UTC, schenedx approved these changes
👍

2017-05-24 15:34 UTC, schenedx commented
@clintonb @mjfrey I think both of you should review this PR

2017-05-24 18:04 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +
Remove this unnecessary newline.

2017-05-24 18:04 UTC, clintonb commented on ecommerce/extensions/catalogue/management/commands/migrate_course.py
> +
Remove this unnecessary newline.

2017-05-24 18:04 UTC, clintonb commented on ecommerce/extensions/catalogue/management/commands/convert_course.py
> +
Remove this unnecessary newline.

2017-05-24 18:04 UTC, clintonb commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        code = FuzzyText().fuzz().upper()
Why does case matter?

2017-05-24 18:04 UTC, clintonb commented on ecommerce/extensions/voucher/tests/test_utils.py
>          voucher = VoucherFactory(code=code)
`VoucherFactory` already generates a code. Use it instead of unnecessary passing another one. (Yes, I know you didn't write this code; however, since you're touching it, you should take a small step to improve it.)

2017-05-24 18:04 UTC, clintonb commented on ecommerce/extensions/payment/management/tests/test_paypal_profile.py
> +        self.call_command_action("list", self.TEST_ID, self. TEST_JSON)
Why are these changes necessary? You have changed how the tests invoke the command in a way that is backwards-incompatible.

2017-05-25 13:55 UTC, adeelkhan commented
@clintonb Made changes, please review.

2017-05-25 14:29 UTC, clintonb requested changes

2017-05-25 14:29 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +        parser.add_argument('vargs', nargs='+', type=str)
I am fine with all of the changes except for those to this file. You've added a new argument, and I'm not sure why. Let's pull these changes, and the updated requirements into a separate PR so that we can discuss them further without blocking your other updates.

2017-05-25 14:44 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +        parser.add_argument('vargs', nargs='+', type=str)
Why are any of these changes necessary? The [Django 1.10 release notes](https://docs.djangoproject.com/en/1.11/releases/1.10/) make no mention of changes to management command arguments/options.

2017-05-25 18:40 UTC, adeelkhan commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +        parser.add_argument('vargs', nargs='+', type=str)
@clintonb I was finding the  [error](https://github.com/miracle2k/django-assets/issues/72) while upgrading. [Here](https://docs.djangoproject.com/en/1.9/releases/1.8/#extending-management-command-arguments-through-command-option-list) its mentioned its deprecated in 1.8, so have to change it to pass command arguments the new way. Now as the tests are executing command with variable no of arguments, so collecting them this way.

2017-05-26 14:38 UTC, adeelkhan commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +        parser.add_argument('vargs', nargs='+', type=str)
@clintonb It seems for 1.9.13, command arguments are successfully passed in args variable, but changing to 1.10.7, no positional arguments are passing to args in handle() function. I have to use vargs to collect positional args and 1.10.7 is populating it into options inside handle. Please guide.

2017-05-26 14:40 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +        parser.add_argument('vargs', nargs='+', type=str)
See https://docs.python.org/2/howto/argparse.html for more info on argparse. At a minimum give these arguments relevant names.

2017-05-26 19:53 UTC, adeelkhan commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +        parser.add_argument('vargs', nargs='+', type=str)
@clintonb Would variable name paypal_profile_arguments is fine?

2017-05-26 20:05 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +        parser.add_argument('vargs', nargs='+', type=str)
Take a look at the `args` class variable. This is not one variable, but two to four variables. I would rather see these listed out as explicit arguments/options, similar to our other commands, than continue doing whatever weirdness is going on here.

Again, let's separate this into a separate sub-task and pull-request. Modifying this management command is worthy of a separate review given the risk and scope of the changes.

2017-06-02 12:14 UTC, adeelkhan commented
@clintonb @simon Please review.

2017-06-02 12:59 UTC, schenedx approved these changes
👍

2017-06-02 12:59 UTC, clintonb approved these changes

2017-06-02 13:25 UTC, merged