Update program coupon: update only benefit value
openedx-unsupported/ecommerce pull request #1287
Opened 2017-05-23 09:36 UTC by iivic

LEARNER-1077

I also included the comments from https://github.com/edx/ecommerce/pull/1285#discussion_r117739230. FYI @clintonb 

@edx/helio Please review.

2017-05-23 09:36 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1287&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-05-23 10:36 UTC, marjev approved these changes

2017-05-23 12:14 UTC, clintonb commented on ecommerce/programs/tests/test_views.py
> -        program_condition = factories.ProgramCourseRunSeatsConditionFactory()
Move this to a separate commit. It is not related to the other change.

2017-05-23 12:14 UTC, clintonb commented on ecommerce/extensions/catalogue/tests/test_models.py
> +from oscar.test import factories as oscar_factories
I believe this module is imported by the factory module below. There should be no need to import this one again.

2017-05-23 13:58 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +        program_uuid = coupon.program_uuid
`program_uuid` is sent as an argument to this method can you use that one?

2017-05-23 14:00 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +        program_uuid = coupon.program_uuid
When only the benefit value gets updated the program uuid will not be sent and thus it will not be possible to use it.

2017-05-24 12:13 UTC, iivic commented
@clintonb comments addressed.

2017-05-24 13:24 UTC, clintonb requested changes
The ticket, LEARNER-1077, is quite vague. I have no idea what the bug is. Can you provide more details, please? What are you trying to accomplish?

2017-05-24 13:24 UTC, clintonb commented on ecommerce/extensions/api/v2/views/coupons.py
> +        program_uuid = coupon.program_uuid
Why not always send the program UUID? Branching of this sort—arguments only sent under overly-specific conditions—is a code smell to me.

2017-05-24 13:24 UTC, clintonb commented on ecommerce/extensions/catalogue/models.py
> +    def program_uuid(self):
This seems to have only been setup for the call in `ecommerce/extensions/api/v2/views/coupons.py`. That doesn't seem right to me.

2017-05-24 13:24 UTC, clintonb commented on ecommerce/extensions/catalogue/tests/test_models.py
> +        """Helper method that creates a product."""
Creates a product for what purpose. Give some more detail here, please.

2017-05-24 13:24 UTC, clintonb commented on ecommerce/extensions/catalogue/tests/test_models.py
> +    def _create_and_assert_product(self, expected_result, offer, product_class_name, short_code):
s/expected_result/expected_program_uuid

2017-05-24 13:45 UTC, iivic commented
@clintonb I don't know what is unclear to you but the ticket goal is simple.
Currently we are not able to update the discount value for a program coupon and this ticket is created in order to enable that.

2017-05-24 13:52 UTC, iivic commented on ecommerce/extensions/api/v2/views/coupons.py
> +        program_uuid = coupon.program_uuid
A PATCH request will be sent if any argument is updated and sending program_uuid every time seems even worse then this solution. Program uuid must be present if the benefit value is updated because that's the current logic of creating/updating program benefits.
I'm open for suggestions.

2017-05-24 13:58 UTC, iivic commented on ecommerce/extensions/catalogue/models.py
> +    def program_uuid(self):
For now that is the only place where it's used but hiding the whole chain of models seems like the right way to expose this data for a coupon. This will be useful in the future as well.

2017-05-24 14:41 UTC, clintonb approved these changes
Please address the remaining comments, update your commit message, and squash your commits.

2017-05-24 14:41 UTC, clintonb commented on ecommerce/extensions/catalogue/models.py
> +    def program_uuid(self):
This doesn't seem right. The `Product` class should not care about program UUIDs. For the time being, remove this.

2017-05-25 08:38 UTC, merged