Added site field to Course model
openedx-unsupported/ecommerce pull request #1291
Opened 2017-05-25 05:45 UTC by clintonb

This commit makes the Course model multi-tenant, ensuring the CAT and API only provide data for a single tenant.

LEARNER-1129

2017-05-26 13:17 UTC, vkaracic commented
@clintonb I have a question about a TODO note that you left.
Does [ ``TODO Update API to set this`` ](https://github.com/edx/ecommerce/pull/1291/files#diff-b8728e7ddc2a7b07a4e6e19255ef1f77R33) mean that I should override the ``create`` method on the courses API endpoint class and set it to manually create a course?

2017-05-26 13:18 UTC, clintonb commented
There is no manual anything. The API should pull the site from the `request`.

2017-05-26 13:47 UTC, clintonb commented on ecommerce/core/migrations/0030_auto_20170526_1259.py
> +# -*- coding: utf-8 -*-
This won't be necessary once https://github.com/edx/ecommerce/pull/1290 is merged.

2017-05-26 13:56 UTC, vkaracic commented
@clintonb is that done automatically? Because there is a test case that sends the name and ID to the API endpoint and it fails because it does not get the site.

2017-05-26 13:59 UTC, clintonb commented
Update the serializer.
-- 
Clinton Blackburn

2017-05-29 20:26 UTC, vkaracic commented on ecommerce/courses/models.py
> +        return None
@clintonb once this is ran https://github.com/edx/ecommerce/pull/1291/files#diff-f137d26c66e1636b8e3cc6a127697be8R9 there would be no need for the if-block here, right?

2017-05-30 12:03 UTC, vkaracic commented
Ready for review @edx/helio

2017-05-30 12:17 UTC, marjev approved these changes

2017-05-31 10:12 UTC, iivic requested changes
Instead of using Course.objects to create courses in test files we should be using CourseFactory. The rest is looking good.

2017-05-31 10:12 UTC, iivic commented on ecommerce/courses/tests/test_models.py
> +        course = Course.objects.create(id='a/b/c', name='Test Course', site=self.site)
Maybe use that CourseFactory you updated?

2017-05-31 10:12 UTC, iivic commented on ecommerce/courses/tests/test_models.py
> +        course = Course.objects.create(id=course_id, site=self.site)
Maybe use that CourseFactory you updated?

2017-05-31 10:12 UTC, iivic commented on ecommerce/courses/tests/test_models.py
> +        course = Course.objects.create(id='a/b/c', name='Test Course', site=self.site)
Maybe use that CourseFactory you updated?

2017-05-31 10:12 UTC, iivic commented on ecommerce/courses/tests/test_models.py
> +        course = Course.objects.create(id='a/b/c', name='Test Course', site=self.site)
Maybe use that CourseFactory you updated?

2017-05-31 10:12 UTC, iivic commented on ecommerce/courses/tests/test_models.py
> +        dotted_course = Course.objects.create(id='a/...course.../id', site=self.site)
Use CourseFactory throughout the file. I will stop writing this comment.

2017-05-31 10:45 UTC, iivic approved these changes

2017-05-31 10:46 UTC, vkaracic commented
@iivic comments addressed, please take another look.

2017-05-31 11:42 UTC, merged

2017-05-31 21:02 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +    site = SiteSerializer(read_only=True)
This is not necessary. Why was it added? The site is implied by the hostname through which the API is accessed.

2017-06-01 07:40 UTC, vkaracic commented on ecommerce/extensions/api/serializers.py
> +    site = SiteSerializer(read_only=True)
So we don't care about this attribute being displayed on the API?

2017-06-01 12:43 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +    site = SiteSerializer(read_only=True)
We don't *need* this attribute to be returned by the API. Why do you think it is needed?

2017-06-01 13:01 UTC, vkaracic commented on ecommerce/extensions/api/serializers.py
> +    site = SiteSerializer(read_only=True)
Ah, correct. I'll remove it.