[WIP] There is no benefit type for program coupons
openedx-unsupported/ecommerce pull request #1294
Opened 2017-05-26 10:05 UTC by iivic

There is no discount/benefit type for program coupons since we use
proxy_class to determine the type. This commit should take care of
displaying the proper benefit type on coupon details/edit page and
basket page.

LEARNER-1087

2017-05-26 10:05 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1294&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-05-26 12:49 UTC, iivic commented
@edx/helio please review.

2017-05-30 08:35 UTC, marjev commented on ecommerce/extensions/offer/utils.py
> +    from ecommerce.programs.constants import BENEFIT_PROXY_CLASS_MAP
For the record: I don't like that we have to resort to this.
https://s-media-cache-ak0.pinimg.com/736x/79/28/2b/79282b550b4bc6d13dfd6ea87e12eb79.jpg

2017-05-30 08:35 UTC, marjev approved these changes

2017-05-30 15:31 UTC, clintonb requested changes

2017-05-30 15:31 UTC, clintonb commented on ecommerce/extensions/offer/utils.py
> +    from ecommerce.programs.constants import BENEFIT_PROXY_CLASS_MAP
Where/how is `format_benefit_value` used? We already have methods of displaying conditional offer details. Why do we need to display the benefit details?

2017-05-30 15:47 UTC, iivic commented on ecommerce/extensions/offer/utils.py
> +    from ecommerce.programs.constants import BENEFIT_PROXY_CLASS_MAP
In this case it is used to display the discount value for basket page. I'm not sure what you are trying to say. Can you elaborate?

2017-05-30 15:50 UTC, clintonb commented on ecommerce/extensions/offer/utils.py
> +    from ecommerce.programs.constants import BENEFIT_PROXY_CLASS_MAP
Oscar already has a mechanism of rendering this value. We use it on the receipt page: https://github.com/edx/ecommerce/blob/39151c18cd187f59fa73efcf8b6ebfd62c10228f/ecommerce/templates/edx/checkout/receipt.html#L100-L119. Replicate that behavior rather than add further customization.

2017-06-02 09:39 UTC, iivic commented on ecommerce/extensions/offer/utils.py
> +    from ecommerce.programs.constants import BENEFIT_PROXY_CLASS_MAP
I can't find that mechanism on oscar and the receipt page filter uses this method that I'm altering. Did I miss something here @clintonb ?

2017-06-02 13:54 UTC, clintonb commented on ecommerce/extensions/offer/utils.py
> +    from ecommerce.programs.constants import BENEFIT_PROXY_CLASS_MAP
Please file a techdebt ticket, and add a comment in the code. I don't have a good solution to this issue at the moment.

2017-06-05 08:34 UTC, iivic commented
@clintonb I created the techdebt ticket and updated the comment. First time doing it so let me know if the info is insufficient.

2017-06-05 13:47 UTC, clintonb approved these changes
Squash your commits, and update your commit title/message to tell me what you did rather than describe the bug.

"There is no benefit type for program coupons" isn't helpful when scrolling through commit messages. The actual fix here is that you, "Fixed basket page rendering of program coupons".

2017-06-05 15:11 UTC, merged