Program coupons download report is broken
openedx-unsupported/ecommerce pull request #1295
Opened 2017-05-29 11:48 UTC by iivic

Should enable downloading coupon reports for program coupons.

LEARNER-1082

@edx/helio Please review.

2017-05-29 11:48 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1295&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-05-29 12:01 UTC, vkaracic requested changes

2017-05-29 12:01 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        """ Verify empty report fields for program coupons. """
``Only program coupon applicable fields should be shown.``

2017-05-29 12:01 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        for field in empty_fields:
Do you need an extra variable to do this?

2017-05-29 12:01 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
> +        # Note (multi-courses): Need to account for multiple seats.
This comment was left for when a catalog has more than one course attach to it (a loong time ago). I don't think it holds true anymore, especially not for catalog query since, if I'm not mistaken, we don't display seat/course information in this case.

2017-05-29 12:01 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
>          field_names.remove('Redeemed For Course ID')
Why is this field removed?

2017-05-29 12:07 UTC, iivic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        for field in empty_fields:
I don't think so. Why do you ask?

2017-05-29 12:10 UTC, vkaracic commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        for field in empty_fields:
Rhetorical question.
``for field in ['Discount Amount', 'Price']:`` works just as fine without introducing unnecessary variables.

2017-05-29 12:25 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
>          field_names.remove('Redeemed For Course ID')
Since I didn't introduce this change I can't be sure but my best guess is that this field is only needed for multi course coupons.

2017-05-29 12:30 UTC, marjev commented on ecommerce/extensions/voucher/utils.py
> +        _('Program UUID'),
Do you need to update translation files?

2017-05-30 05:52 UTC, marjev approved these changes

2017-05-30 07:12 UTC, vkaracic commented on ecommerce/extensions/voucher/utils.py
>              coupon_type = None
How about:
```
coupon_type = _('Discount') if benefit.value < seat_stockrecord.price_excl_tax else _('Enrollment')
```
?

2017-05-30 08:25 UTC, marjev commented on ecommerce/extensions/voucher/utils.py
>              coupon_type = None
for `Benefit.PERCENTAGE`?

2017-05-30 09:58 UTC, iivic commented on ecommerce/extensions/voucher/utils.py
>              coupon_type = None
This will not work.

2017-05-30 11:05 UTC, vkaracic approved these changes

2017-05-30 11:16 UTC, merged