Update paypal command to be compatible for Django 1.9+
openedx-unsupported/ecommerce pull request #1304
Opened 2017-05-31 09:44 UTC by adeelkhan

LEARNER-1245 - Subtask for LEARNER-480
Make Paypal command to be compatible with Django 1.9+

2017-05-31 15:46 UTC, schenedx approved these changes
👍 Good work

2017-05-31 16:43 UTC, clintonb requested changes

2017-05-31 16:43 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +            raise CommandError("Required arguments `partner` and `action` are missing")
Single quotes

2017-05-31 16:43 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +        profile_data = json.loads(self._get_argument([options.get('json')], 'json string', 'create'))
`_get_argument` is not needed. You're literally creating a list to accommodate an unnecessary method. Remove the method, and add proper validation on the arguments to ensure all required parameters are set (depending on the command).

2017-06-01 12:29 UTC, adeelkhan commented
@clintonb Made required changes, please review.

2017-06-01 12:37 UTC, clintonb approved these changes
Please address the comments before merging.

2017-06-01 12:37 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +                                                                                   'profile_id'))
`'profile_id'` is a constant. It should not be a `kwarg`.

2017-06-01 12:37 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +                                                                                   'profile_id'))
`'profile_id'` is a constant. It should not be a `kwarg`.

2017-06-01 12:37 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +                                                                                   'profile_id'))
`'profile_id'` is a constant. It should not be a `kwarg`.

2017-06-01 12:37 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +                                                                                   'profile_id'))
`'profile_id'` is a constant. It should not be a `kwarg`.

2017-06-01 12:37 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +                                                                                   'json string'))
`'json string'` is a constant. It should not be a `kwarg`. It should also be, `'JSON string'`.

2017-06-01 12:37 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +                                                                                   'profile_id'))
`'profile_id'` is a constant. It should not be a `kwarg`.

2017-06-01 12:37 UTC, clintonb commented on ecommerce/extensions/payment/management/commands/paypal_profile.py
> +                                                                                   'json string'))
`'json string'` is a constant. It should not be a `kwarg`. It should also be, `'JSON string'`.

2017-06-01 13:51 UTC, merged