[ENT-357] Display course run price with entitlement on Landing page & course description modal
openedx-unsupported/ecommerce pull request #1307
Opened 2017-06-02 05:58 UTC by replaceafill

2017-06-02 05:59 UTC, edx-webhook commented
Thanks for the pull request, @replaceafill! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1307"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-06-02 10:28 UTC, itsjeyd requested changes
@replaceafill This is looking pretty good already. Most of my suggestions are about making cosmetic changes. I also had a question about URL patterns, and about extending the tests a bit.

2017-06-02 10:28 UTC, itsjeyd commented on ecommerce/extensions/api/v2/urls.py
> +        r'^sku_price_details_for_user/{sku},{username}/$'.format(
@replaceafill Any specific reason for using a comma to separate `{sku}` and `{username}` (instead of a slash)?

In general, I'm wondering if we should make the URL pattern more generic, to make extending it more straightforward. For example, we might want to introduce additional endpoints for retrieving information related to a specific user in the future. So how about something like:

```python
r'^users/{username}/products/{sku}/price/$'.format(...)
```

2017-06-02 10:28 UTC, itsjeyd commented on ecommerce/enterprise/entitlements.py
> +    Return price information for a product for enterprise customer user.
@replaceafill How about:

```
Return price information for a product for a user who is associated with an enterprise customer.
```

(The current wording sounds like we're dealing with a user who is an enterprise customer.)

If you make that change, I think you can shorten the name of the function to `get_product_price_details_for_user`.

2017-06-02 10:28 UTC, itsjeyd commented on ecommerce/enterprise/entitlements.py
> +        voucher (Voucher): voucher for getting the benift's type and value
@replaceafill Typo: `benift`

2017-06-02 10:28 UTC, itsjeyd commented on ecommerce/enterprise/tests/test_entitlements.py
> +        Verify that method "get_discounted_price" returns the substraction of
@replaceafill Typo: `substraction`

Nit: The following wording would be more precise:

> Verify that for a fixed benefit, "get_discounted_price" returns the result of subtracting the benefit value from the original price.

2017-06-02 10:28 UTC, itsjeyd commented on ecommerce/enterprise/tests/test_entitlements.py
> +        to the benefit value for a percentage benefit type.
@replaceafill The method should return the result of subtracting a fraction equivalent to the benefit value from the original price (not the fraction itself):

> Verify that for a percentage benefit, "get_discounted_price" returns the result of subtracting a fraction equivalent to the benefit value from the original price.

2017-06-02 10:28 UTC, itsjeyd commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +    def test_get_price_details(self, voucher_for_product_mock, vouchers_for_learner_mock):
@replaceafill Nit: Add docstring

2017-06-02 10:28 UTC, itsjeyd commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        )
@replaceafill This test looks good, but it only covers one of two happy paths (the other happy path is when we're dealing with a non-staff user who is requesting price details for themselves), and none of the sad paths (non-staff user requesting price details for another user; non-existing user). Could you add tests for these paths as well?

2017-06-02 13:08 UTC, clintonb requested changes
Let's have a chat about APIs. We should avoid making Enterprise-specific endpoints when they may benefit all of OpenEdX. The ability to get a price for a user opens up many possibilities on marketing sites. Also @mjfrey has already written a similar endpoint: /baskets/calculate/.

2017-06-02 13:48 UTC, itsjeyd commented
@brittneyexline @douglashall Pinging you on this as discussed at standup.

2017-06-05 22:52 UTC, replaceafill commented on ecommerce/extensions/api/v2/urls.py
> +        r'^sku_price_details_for_user/{sku},{username}/$'.format(
@itsjeyd No specific reason. I've just been working with the enrollment API lately and it uses that approach. I changed this to use your suggestion.

2017-06-06 03:13 UTC, clintonb commented on ecommerce/extensions/api/v2/urls.py
> +        r'^sku_price_details_for_user/{sku},{username}/$'.format(
Please don't follow any examples from the Enrollment API. It's an example of what not to do.

2017-06-06 03:15 UTC, clintonb commented
Are you progressing with an Enterprise-specific API? If so, why? What about the existing API is lacking?

2017-06-06 03:41 UTC, replaceafill commented
@clintonb I wanted to ask you a couple of questions today, but I decided to address @itsjeyd comments first.

Thank you for pointing me to the calculate endpoint. It seems to do part of what we need. I even tried extracting and reusing [this part](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/api/v2/views/baskets.py#L369-L392), but couldn't get the discount to work in my current tests. I decided to extract that part because calling the "whole" endpoint from a new endpoint didn't seem right.

My plan was to [get the entitlement voucher](https://github.com/edx/ecommerce/blob/master/ecommerce/enterprise/entitlements.py#L30-L49) and use it with the calculate endpoint code. But the way I've implemented the current endpoint [allows a user to query other user's data](https://github.com/replaceafill/ecommerce/blob/replaceafill/ENT-357/ecommerce/extensions/api/v2/views/enterprise.py#L30-L34) (I recently asked @haikuginger if this is even needed) and I'm not sure if the Applicator in Oscar's offers relies on request.user instead.

This is my first interaction with Ecommerce so any recommendation is highly appreciated.

2017-06-06 04:31 UTC, clintonb commented
@replaceafill, would you please describe the problem you are trying to solve?

2017-06-06 04:50 UTC, replaceafill commented
@clintonb Sure. The JIRA ticket is [ENT-357](https://openedx.atlassian.net/browse/ENT-357). The goal of the task is that when an Enterprise learner enrolls in a course of an Enterprise, they see a discounted price on the premium (paid) track based on the entitlements (coupons) associated with the Enterprise.

The enterprise code in Ecommerce is already able to [get the voucher](https://github.com/edx/ecommerce/blob/master/ecommerce/enterprise/entitlements.py#L30-L49) based on a product, so all I need to do is to get the Product from the SKU of the paid mode. Then I was thinking of (somehow) sending `voucher code + [product]` to the calculate  endpoint you mentioned.

2017-06-06 05:12 UTC, clintonb commented
1. (Not necessarily for you to answer) Why are entitlements implemented as vouchers instead of site-wide conditional offers?
2. Why not update the existing endpoint, `/api/v2/baskets/calculate/`, to account for *all* context, including entitlements?

2017-06-06 05:30 UTC, replaceafill commented
@clintonb Correct. The decision on 1. predates my involvement on Enterprise coding :)

Regarding 2. do you think we could make the `/api/v2/baskets/calculate` endpoint to accept an optional username and try to get the voucher code from it if an explicit code is not supplied?

2017-06-06 10:03 UTC, itsjeyd requested changes
@replaceafill Thanks for the updates. This is getting close, but the tests are not quite there yet (see inline comments). Since a final decision on the overall approach is still pending it might make sense to hold off on making further adjustments to the tests (although the feedback that I had should be fairly quick to incorporate).

This also needs a rebase, and (note to self) testing is blocked on the issue that I reported on [OC-2619](https://tasks.opencraft.com/browse/OC-2619).

2017-06-06 10:03 UTC, itsjeyd commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        # Create staff user
@replaceafill After the recent updates, this should be just "Create user", or "Create (non-)staff user".

2017-06-06 10:03 UTC, itsjeyd commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        )
@replaceafill Thanks for adding these tests! They look good, but contain a good amount of duplication.

Please merge `test_get_price_details_staff_checks_other_user` and `test_get_price_details_non_staff_checks_other_user` using `ddt`. You could name the resulting test `test_get_price_details_other_user`. For the parts that verify the response you can vary behavior based on whether the current user `is_staff`.

It would be fine to have separate tests for "user checks own information" vs. "user checks information for other user", I think, but maybe you can extract some of the common parts from `test_get_price_details_user_checks_own_information` and the new `test_get_price_details_other_user` into (private) helper methods on the `TestEnterpriseSkuPriceDetailsForUserView` class.

Finally, it would be great if you could add docstrings to the tests :)

2017-06-06 14:12 UTC, clintonb commented
@replaceafill what is the use case for passing a username as opposed to using the authenticated user? Yes, looking up the entitlements is exactly what I am proposing.

2017-06-06 14:20 UTC, haikuginger commented
@clintonb, re: your question about conditional offers, I believe we actually have some stuff in flight to switch over to those.

2017-06-07 17:34 UTC, replaceafill commented
@clintonb I'm going to modify the `/api/v2/baskets/calculate` endpoint to also be aware of Enterprise entitlements.

2017-06-08 09:06 UTC, itsjeyd requested changes
@replaceafill Thanks for changing the approach! This looks good aside from a few small things that you'll need to clean up. I also had a [question](https://github.com/edx/ecommerce/pull/1307#discussion_r120832216) about applying voucher codes vs. Enterprise entitlements, but we can resolve that during upstream review.

2017-06-08 09:06 UTC, itsjeyd commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        """ Verufy successful basket calculation for a fixed price voucher """
@replaceafill Typo: Verufy (please fix for docstring of `test_basket_calculate_fixed_coupon` as well).

Also, can you please update/extend this docstring to explain how the test differs from `test_basket_calculate_fixed_coupon`?

2017-06-08 09:06 UTC, itsjeyd commented on ecommerce/extensions/api/v2/views/baskets.py
> +        vouchers = []
@replaceafill Please update the following part of the docstring of this method to take into account Enterprise entitlements:

> Create a temporary basket add the sku's and apply an optional voucher code. Then calculate the total proce less discounts.

There's also a typo in there: "proce"

2017-06-08 09:06 UTC, itsjeyd commented on ecommerce/extensions/api/v2/views/baskets.py
> +        else:
@replaceafill IIUC, passing a `code` to this view will cause this code to skip applying any Enterprise entitlements. Is this what we want? Or is there are use case where we'd pass a code *and* would want the view to apply Enterprise entitlements? Genuine question, CC @clintonb @brittneyexline @douglashall @haikuginger

2017-06-08 09:06 UTC, itsjeyd commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +
@replaceafill I think you can revert the changes in this file.

2017-06-08 09:06 UTC, itsjeyd commented on ecommerce/enterprise/tests/test_entitlements.py
> +Benefit = get_model('offer', 'Benefit')
@replaceafill I think you can revert the changes in this file.

2017-06-08 09:06 UTC, itsjeyd commented on ecommerce/extensions/api/v2/views/enterprise.py
> +
@replaceafill I think you can revert the changes in this file.

2017-06-08 12:45 UTC, itsjeyd commented
@replaceafill One more thing I forgot to mention earlier: Now that the approach has changed it would be worth updating the PR description to reflect that.

2017-06-08 21:28 UTC, replaceafill commented on ecommerce/extensions/api/v2/views/baskets.py
> +        else:
@itsjeyd I have the same question.

2017-06-09 10:20 UTC, itsjeyd reviewed
@replaceafill One more nit and another rebase, then this should be good to go (manual testing pending).

2017-06-09 10:20 UTC, itsjeyd commented on ecommerce/extensions/api/v2/views/baskets.py
> +        provided look for vouchers in the Enterprise entitlements available
@replaceafill Nit: Replace "look for" (which is pretty generic) with "apply":

> If a voucher code is not provided, apply vouchers from the Enterprise entitlements for the current user instead.

2017-06-09 12:39 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +        if voucher is not None:
`if voucher`

2017-06-09 12:39 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +        else:
Look at how the basket page determines priority, and replicate that/extract it to a method you can use here. Generally, user-specified vouchers take precedence over other offers. We will let you shoot yourself in the foot if you choose to use an offer that gives you a worse discount than the one we've selected for you.

2017-06-10 06:06 UTC, replaceafill commented
@itsjeyd Rebased/squashed from 3fc7270

2017-06-12 15:07 UTC, replaceafill commented on ecommerce/extensions/api/v2/views/baskets.py
> +        else:
@clintonb I reviewed how the basket page determines voucher priority and I found that only the [BasketSingleItemView](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/basket/views.py#L43) uses Enterprise entitlements after failing to get a voucher from the request.

What I'm wondering now is how much sense does it make to apply multiple entitlement vouchers to the calculate endpoint (one for each sku). Maybe just adding this in [this part](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/api/v2/views/baskets.py#L364) of the endpoint would be enough:

```python
        # If it's a single product try to apply an Enterprise entitlement voucher                                               
        if not voucher and len(products) ==  1:
            voucher = get_entitlement_voucher(request, products[0])
```

What do you think?

2017-06-13 14:16 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/baskets.py
> +        else:
hey @clintonb, when you get a chance can you reply to the above implementation question in this thread? thanks!

2017-06-13 14:26 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +        else:
> What I'm wondering now is how much sense does it make to apply multiple entitlement vouchers to the calculate endpoint (one for each sku).

That's a question for the product owner. However, if we only use one entitlement voucher today, I see no reason to change that.

2017-06-14 04:56 UTC, replaceafill commented
@itsjeyd I just rebased this from c557da4

2017-06-14 14:32 UTC, replaceafill commented on ecommerce/extensions/api/v2/views/baskets.py
> +        else:
Thanks @clintonb. I changed the implementation to use this approach. Could you please take a look and let me know if it's good to be merged?

2017-06-14 19:04 UTC, clintonb approved these changes
Squash your commits, and update your commit message to follow the guidelines at https://openedx.atlassian.net/wiki/display/ECOM/Developer+Onboarding.

2017-06-14 19:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +        if not voucher and len(products) == 1:
I clearly misunderstood your initial question. Who is the product owner? Has he/she been notified of this limitation? What you are doing here is probably okay for now, but will be limiting in the future as Enterprise embraces multi-item baskets (which may be sooner, rather than later, for programs). The alternative to this approach is to retrieve multiple vouchers. Ultimately, the Enterprise Team will need to update entitlements to be conditional offers rather than vouchers.

2017-06-14 19:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +        # This is to match the logic of the '/basket/single-item' view
I would not mention the old view since it will eventually be deleted. The justification for this logic should stand on its own merit.

2017-06-14 20:21 UTC, replaceafill commented
Thanks for your help @clintonb. I just rebased/squashed this from 3f91f6d

2017-06-15 09:35 UTC, douglashall approved these changes
Can you rebase this again?

2017-06-15 17:09 UTC, replaceafill commented
@douglashall Rebased from 02bb022

2017-06-15 17:40 UTC, merged