WIP: switches added for disable/enable order and user table change/list view
openedx-unsupported/ecommerce pull request #1309
Opened 2017-06-06 10:22 UTC by tasawernawaz

[LEARNER-864](https://openedx.atlassian.net/browse/LEARNER-864)

2017-06-06 12:39 UTC, tasawernawaz commented
@clintonb Please review this.

2017-06-06 14:04 UTC, clintonb requested changes

2017-06-06 14:04 UTC, clintonb commented on ecommerce/core/admin.py
> +        if waffle.switch_is_active(USER_LIST_VIEW_SWITCH):
Add a comment explaining why this is necessary.

2017-06-06 14:04 UTC, clintonb commented on ecommerce/core/admin.py
> +from ecommerce.core.constants import USER_LIST_VIEW_SWITCH
Fix your import groupings.

https://github.com/timothycrosley/isort

2017-06-06 14:04 UTC, clintonb commented on ecommerce/core/constants.py
> +# User constants
This comment is not helpful. Actually explain what the switch is for.

2017-06-06 14:04 UTC, clintonb commented on ecommerce/extensions/order/admin.py
> +from ecommerce.extensions.order.constants import ORDER_LIST_VIEW_SWITCH
Fix.

2017-06-06 14:04 UTC, clintonb commented on ecommerce/extensions/order/constants.py
> +# Order Constants
Again, this comment is not helpful.

2017-06-06 14:04 UTC, clintonb commented on ecommerce/extensions/order/admin.py
> +        if waffle.switch_is_active(ORDER_LIST_VIEW_SWITCH):
Add a comment explaining what is going on here.

2017-06-06 14:04 UTC, clintonb commented on ecommerce/extensions/order/migrations/0014_auto_20170606_0535.py
> +    Switch.objects.get_or_create(name=ORDER_LIST_VIEW_SWITCH, defaults={'active': True})
`update_or_create`

2017-06-06 14:04 UTC, clintonb commented on ecommerce/core/migrations/0033_auto_20170606_0539.py
> +    Switch.objects.get_or_create(name=USER_LIST_VIEW_SWITCH, defaults={'active': True})
`update_or_create`

2017-06-06 14:04 UTC, clintonb commented on ecommerce/extensions/order/tests/test_admin.py
> +from ecommerce.core.tests import toggle_switch
Alphabetize.

2017-06-06 14:04 UTC, clintonb commented on ecommerce/extensions/order/tests/test_admin.py
> +        self.order_page_url = '/admin/order/order/'
Use `reverse()`: https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#reversing-admin-urls

2017-06-06 14:04 UTC, clintonb commented on ecommerce/extensions/order/tests/test_admin.py
> +    """ Tests Admin page."""
Remove this docstring. It adds no value.

2017-06-06 14:04 UTC, clintonb commented on ecommerce/extensions/order/tests/test_admin.py
> +        self.order_page_url = '/admin/order/order/'
Move this outside of setup. It should be fine to put this at the same level as `password`.

2017-06-06 14:04 UTC, clintonb commented on ecommerce/core/admin.py
> +from ecommerce.core.constants import USER_LIST_VIEW_SWITCH
Also, where are the tests for this one?

2017-06-07 11:47 UTC, tasawernawaz commented
@clintonb Please take another look.

2017-06-07 12:59 UTC, clintonb commented on ecommerce/extensions/order/tests/test_admin.py
> +    def test_with_enable_order_list_view(self):
Merge these into a single test with ddt.

2017-06-07 12:59 UTC, clintonb commented on ecommerce/core/tests/test_admin.py
> +    def test_with_enable_order_list_view(self):
Merge these into a single test with ddt.

2017-06-07 13:10 UTC, tasawernawaz commented on ecommerce/extensions/order/tests/test_admin.py
> +    def test_with_enable_order_list_view(self):
Merging both tests needs a conditional statement in test before assertion, which I believe is not a better solution.

2017-06-07 13:10 UTC, tasawernawaz commented on ecommerce/core/tests/test_admin.py
> +    def test_with_enable_order_list_view(self):
same here.

2017-06-07 13:13 UTC, clintonb commented on ecommerce/extensions/order/tests/test_admin.py
> +    def test_with_enable_order_list_view(self):
```python
@ddt.data(True, False)
def test_has_change_permission(self, switch_value):
  """ The method should only return True if the switch is enabled. """
  toggle_switch(ORDER_LIST_VIEW_SWITCH, switch_value)
  self.assertEqual(self.order_admin.has_change_permission(self.request), switch_value)
```

2017-06-07 13:47 UTC, tasawernawaz commented
@clintonb Made suggested changes.

2017-06-07 14:11 UTC, clintonb reviewed
I just realized that this disables the change view. We only want to disable the list view.

2017-06-07 14:11 UTC, clintonb commented on ecommerce/core/admin.py
> +        return True if waffle.switch_is_active(USER_LIST_VIEW_SWITCH) else False
`return waffle.switch_is_active(USER_LIST_VIEW_SWITCH)`

2017-06-07 14:11 UTC, clintonb commented on ecommerce/extensions/order/admin.py
> +        return True if waffle.switch_is_active(ORDER_LIST_VIEW_SWITCH) else False
`waffle.switch_is_active(ORDER_LIST_VIEW_SWITCH)`

2017-06-08 09:59 UTC, tasawernawaz commented
@clintonb Good catch. There isn't any permission related to list view. We can override `get_queryset`  and return empty set or we can override `changelist_view` and raise `PermissionDenied` exception. Your thoughts will be appreciated here.

2017-06-08 17:07 UTC, schenedx commented on ecommerce/core/tests/test_admin.py
> +    def test_has_change_permission(self, switch_value):
We want to restrict view permission right?. So this should be renamed to`test_has_view_permission`?

2017-06-08 17:12 UTC, schenedx requested changes
I like the idea to override `changelist_view`. I don't know if `permission_denied` is the right exception to raise. Do we need to raise exception? Shouldn't we override the view template in the view? We should tell our users who try to access this view that they are not going to get the list of orders? The message should also include that list of orders are too many and to expansive to render.

2017-06-08 17:12 UTC, schenedx commented on ecommerce/extensions/order/tests/test_admin.py
> +    def test_has_change_permission(self, switch_value):
Same comment as above.  Should this be renamed to `test_has_view_permission`?

2017-06-12 11:46 UTC, tasawernawaz commented
@schenedx Implemented your suggestion. Please review.

2017-06-12 19:30 UTC, schenedx approved these changes
👍 Nice work

2017-06-13 08:46 UTC, tasawernawaz commented
@clintonb Needs your review.

2017-06-13 14:37 UTC, clintonb approved these changes

2017-06-13 14:46 UTC, merged

2017-06-13 15:02 UTC, schenedx commented
@tasawernawaz Can you please verify this change on stage now?
Looks like the ecom stage deployment will be done 10min or less from now.

2017-06-14 06:38 UTC, tasawernawaz commented
@schenedx Verified.