[WIP] -- ENT-367: Show Enterprise Logistration for coupon users
openedx-unsupported/ecommerce pull request #1320
Opened 2017-06-12 12:01 UTC by saleem-latif

Hi @douglashall , @zubair-arbi , @asadiqbal08 

Please take a look, This PR adds branding for enterprise learners coming from coupon redemption page.

__Jira Ticket:__ [ENT-367](https://openedx.atlassian.net/browse/ENT-367)

__Description:__
When the user comes into the offers page and is then redirected to login or register, and go through data sharing consent, the user should see the cobranded version of the logistration page and DSC page, then return to the existing flow.

2017-06-13 11:45 UTC, zubair-arbi commented on ecommerce/enterprise/tests/test_utils.py
> +        voucher, _ = prepare_voucher(enterprise_customer=enterprise_customer_uuid)
nit: double underscore `__`

2017-06-13 11:50 UTC, asadiqbal08 commented on ecommerce/enterprise/utils.py
> +        settings.ENTERPRISE_CUSTOMER_COOKIE_NAME, enterprise_customer_uuid, domain=settings.BASE_SESSION_COOKIE_DOMAIN,
what would be the maximum age in that case ?

2017-06-13 11:52 UTC, asadiqbal08 commented on ecommerce/enterprise/utils.py
> +    Set cookie for the enterprise customer with enterprise customer uuid.
suggestion: Setting enterprise customer cookie with enterprise customer uuid ?

2017-06-13 11:52 UTC, zubair-arbi approved these changes
Functionality looks good 👍

2017-06-13 11:55 UTC, asadiqbal08 commented on ecommerce/enterprise/utils.py
> +        return None
@saleem-latif  which option would be better - one try with multiple except blocks ? or the separate one like above ?

2017-06-13 11:57 UTC, asadiqbal08 commented on ecommerce/enterprise/utils.py
> +        return None
@saleem-latif which option would be best ? one try with multiple exceptions blocks or the same as above ? 

```
try:
   voucher = Voucher.objects.get(code=coupon_code)
   offer = voucher.offers.get(benefit__range__enterprise_customer__isnull=False)
except (Voucher.DoesNotExist, ConditionalOffer.DoesNotExist) :
        return None

```

2017-06-13 12:00 UTC, saleem-latif commented on ecommerce/enterprise/utils.py
> +        settings.ENTERPRISE_CUSTOMER_COOKIE_NAME, enterprise_customer_uuid, domain=settings.BASE_SESSION_COOKIE_DOMAIN,
Cookie will last for the session length.

2017-06-13 12:01 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_utils.py
> +        # does not with given code does not exist.
nit : Can we rephrase that sentence?

2017-06-13 12:01 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_utils.py
> +        # assert that None is returned when voucher exists but conditional offer
nit: move that comment where you are actually asserting the condition.

2017-06-13 12:03 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_utils.py
> +        Verify that enterprise cookies are set properly.
nit: Verifying that enterprise cookies are **setting** properly.

2017-06-13 12:03 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_utils.py
> +        # does not with given code does not exist.
nit: rephrase it

2017-06-13 12:05 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_utils.py
> +        self.assertEqual(
may I ask, where `None` is returning in the assert ?

2017-06-13 12:05 UTC, saleem-latif commented on ecommerce/enterprise/utils.py
> +        return None
I think it is better to use multiple exception blocks, this way we will know the exact cause for each exception and avoid accidental/invalid exception catch.

2017-06-13 12:09 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_decorators.py
> +        associated with the voucher of given code.
I could not understand this test docstring with `test_set_enterprise_cookie` line - `35-36` both looking same.

2017-06-13 12:12 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_decorators.py
> +        Validate that no cookie is set if no enterprise customer is
change it

2017-06-13 12:15 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_utils.py
> +        Verify correct value of enterprise customer uuid is returned.
with the given docstring, It seems me we are testing multiple values of enterprise customer uuid, However, in this test we are only testing the `None` state.

2017-06-13 12:17 UTC, asadiqbal08 commented on ecommerce/enterprise/tests/test_utils.py
> +        self.assertIsNone(
add any other none assert test in it or update the docstring.

2017-06-13 12:23 UTC, asadiqbal08 commented on ecommerce/enterprise/utils.py
> +        return None
actually, in both cases we are only returning `None` or should we `log` some info in those catches above ?

2017-06-13 12:24 UTC, asadiqbal08 commented on ecommerce/enterprise/decorators.py
> +
nit: remove extra lines

2017-06-13 12:24 UTC, asadiqbal08 commented on ecommerce/enterprise/decorators.py
> +
nit: remove extra lines

2017-06-13 13:27 UTC, clintonb requested changes

2017-06-13 13:27 UTC, clintonb commented on ecommerce/settings/base.py
> +BASE_SESSION_COOKIE_DOMAIN = '.edx.org'
Do not hardcode "edx.org" in settings. Move this to the SiteConfiguration model since it is site-specific. Also, update the management command to allow this to be set.

2017-06-13 13:27 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +        Verify that enterprise cookies are set properly.
This statement is correct as written. No changes are needed.

2017-06-13 13:27 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +        # does not with given code does not exist.
Remove it. This statement is already reflected in the docstring.

2017-06-13 13:27 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +            get_enterprise_customer_uuid(voucher.code)
One line.

2017-06-13 13:27 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
>  from ecommerce.enterprise.utils import (enterprise_customer_user_needs_consent, get_enterprise_customer,
Put these on a new line and properly indent.

2017-06-13 13:27 UTC, clintonb commented on ecommerce/enterprise/decorators.py
> +
This is correct as written. Please see the PEP 8 style guide at https://www.python.org/dev/peps/pep-0008/#imports.

2017-06-13 13:27 UTC, clintonb commented on ecommerce/coupons/views.py
> +from ecommerce.enterprise.utils import (enterprise_customer_user_needs_consent, get_enterprise_course_consent_url,
Revert. The imports were correct as they were before. Avoid large indented blocks.

2017-06-13 13:27 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    Set cookie for the enterprise customer with enterprise customer uuid.
This statement is also correct as written. The only change is to capitalize UUID. It is an acronym, not a word.

2017-06-13 13:55 UTC, asadiqbal08 commented on ecommerce/enterprise/decorators.py
> +
sorry, I was talking about the extra line. Is it ok to have it @saleem-latif ?

2017-06-14 05:30 UTC, saleem-latif commented on ecommerce/enterprise/decorators.py
> +
@asadiqbal08 ref: https://www.python.org/dev/peps/pep-0008/#imports
```
Imports should be grouped in the following order:

standard library imports
related third party imports
local application/library specific imports
You should put a blank line between each group of imports.
```

2017-06-14 05:46 UTC, saleem-latif commented on ecommerce/enterprise/utils.py
> +        return None
@asadiqbal08 No, we do not need to log the exception as this exception will be raised for all cases except when an enterprise customer is associated with the voucher and we do not want to pollute the logs.

> for all try/except clauses, limit the try clause to the absolute minimum amount of code necessary. Again, this avoids masking bugs.
ref: http://legacy.python.org/dev/peps/pep-0008/#programming-recommendations
> 
> Yes:
>  ```
> try:
>     value = collection[key]
> except KeyError:
>     return key_not_found(key)
> else:
>     return handle_value(value)
> ```
> No:
> ```
> try:
>     # Too broad!
>     return handle_value(collection[key])
> except KeyError:
>     # Will also catch KeyError raised by handle_value()
>     return key_not_found(key)
> ```

2017-06-14 07:20 UTC, saleem-latif commented on ecommerce/enterprise/tests/test_utils.py
>  from ecommerce.enterprise.utils import (enterprise_customer_user_needs_consent, get_enterprise_customer,
In order to avoid future problems with import indents, I have added a [new rule in isort config file](https://github.com/edx/ecommerce/pull/1320/files#diff-170b3556059bb1e212db57e7c98d02b6R3) 
```
multi_line_output=3
```
ref: [isort Vertical Hanging Indent https://github.com/timothycrosley/isort](https://github.com/timothycrosley/isort)

2017-06-14 08:36 UTC, saleem-latif commented
@asadiqbal08 , @clintonb I have incorporated your feedback, please take a look.

2017-06-14 10:36 UTC, asadiqbal08 commented
LGTM 👍

2017-06-14 13:44 UTC, clintonb reviewed
Update translations and squash your commits.

2017-06-14 13:44 UTC, clintonb commented on ecommerce/core/management/commands/create_or_update_site.py
> +        if base_session_cookie_domain:
Ditch the if statement. It's perfectly fine to store an empty string.

2017-06-14 13:44 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    Cookie is set with the base domain so that it is available in both lms and ecommerce.
The cookie is set to the base domain so that it is accessible to all services on the same domain.

2017-06-14 13:44 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +        site (Site): django site object.
Django

2017-06-14 13:44 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +        response (HttpResponse): django http response object.
Django

2017-06-14 13:44 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +        enterprise_customer_uuid (UUID): enterprise customer uuid
Enterprise customer UUID

2017-06-14 13:44 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +         response (HttpResponse): django http response object.
Django HTTP

2017-06-14 13:44 UTC, clintonb commented on ecommerce/settings/base.py
> +ENTERPRISE_CUSTOMER_COOKIE_NAME = 'enterprise_customer'
enterprise_customer_uuid

2017-06-14 13:44 UTC, clintonb commented on ecommerce/extensions/test/factories.py
> +class RangeFactory(BaseRangeFactory):  # pylint: disable=function-redefined
There is no need to override this class given that you are passing in the `enterprise_customer` field value.

2017-06-14 13:44 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +    if site.siteconfiguration.base_session_cookie_domain:
What if no value is set? Do you need to log a warning?

2017-06-14 13:44 UTC, clintonb commented on ecommerce/enterprise/utils.py
> +        coupon_code (str|unicode): Code for the enterprise coupon.
str

2017-06-14 13:44 UTC, clintonb commented on ecommerce/core/tests/test_commands.py
> +            from_email=self.from_email,
Revert.

2017-06-14 13:44 UTC, clintonb commented on ecommerce/core/models.py
> +        default='',
No need for a trailing comma here.

2017-06-14 13:44 UTC, clintonb commented on ecommerce/core/models.py
> +        help_text=_('Base Cookie Domain to share cookies across IDAs.'),
Base cookie domain used to share cookies across services

2017-06-14 13:44 UTC, clintonb commented on ecommerce/core/models.py
> +    base_session_cookie_domain = models.CharField(
base_cookie_domain

2017-06-14 13:44 UTC, clintonb commented on ecommerce/core/models.py
> +        verbose_name=_('Base Session Cookie Domain'),
Base Cookie Domain

2017-06-14 13:44 UTC, clintonb commented on ecommerce/core/models.py
> +    base_session_cookie_domain = models.CharField(
Update the parameters for the management command as well.

2017-06-15 06:17 UTC, saleem-latif commented on ecommerce/core/management/commands/create_or_update_site.py
> +        if base_session_cookie_domain:
`base_session_cookie_domain` is not a required argument, If we remove if condition then `base_session_cookie_domain` will be set to empty string even if it is not provided in the arguments.

2017-06-15 08:05 UTC, saleem-latif commented
@clintonb I am getting this error when I run `make update_translations`

```
Exception: No user credentials found for host https://www.transifex.com. Edit ~/.transifexrc and add the appropriate info in there.
Makefile:116: recipe for target 'pull_translations' failed
```
Thoughts on what is the problem here ?

2017-06-15 12:45 UTC, clintonb commented
You probably need a Transifex account.

2017-06-15 12:46 UTC, clintonb requested changes

2017-06-15 12:46 UTC, clintonb commented on ecommerce/core/management/commands/create_or_update_site.py
> +        if base_cookie_domain:
Again, you don't need an if statement. The default empty string is fine. Get rid of the if statement.

2017-06-15 12:48 UTC, asadiqbal08 commented
@saleem-latif why do you need to pull/update the translations ?

2017-06-16 06:02 UTC, saleem-latif commented
@asadiqbal08 `validate_translations` fail if I update translations and not pull them.
@clintonb I have updated the command as per your suggestion, please take a look.

2017-06-16 12:06 UTC, clintonb reviewed
Although you may not have made it, you are consuming `EnterpriseServiceMockMixin` which should *not* be inheriting from *TestCase*. Please correct this in a separate commit.

Your actual work is correct, but the PR title and commit message need to be updated to reflect the changes you're actually making. Here is an ideal commit message:

```
Updated CouponView to store enterprise customer UUID in cookie

Users arriving at this view, who are associated with an enterprise customer, will have this cookie set on the base domain (e.g. .edx.org instead of ecommerce.edx.org). This cookie will be used by the LMS, in the event of a redirect for login, to properly style the page based on the associated enterprise.

ENT-367
```

2017-06-16 12:06 UTC, clintonb commented on ecommerce/enterprise/tests/test_decorators.py
> +class EnterpriseDecoratorsTests(EnterpriseServiceMockMixin):
`EnterpriseServiceMockMixin` isn't a mixin. It's an actual `TestCase`. It should be made a mixin, however, to avoid future confusion.

2017-06-16 12:06 UTC, clintonb commented on ecommerce/enterprise/tests/test_decorators.py
> +        self.request_factory = RequestFactory()
This isn't necessary. Just call `RequestFactory()` where needed.

2017-06-16 12:06 UTC, clintonb commented on ecommerce/enterprise/tests/test_decorators.py
> +        self.assertIn(settings.ENTERPRISE_CUSTOMER_COOKIE_NAME, response.cookies)
This is not necessary given the call below.

2017-06-16 12:06 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +        self.assertIn(settings.ENTERPRISE_CUSTOMER_COOKIE_NAME, result.cookies)
This is not needed.

2017-06-16 12:06 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +        # Validate that cookie was not set.
This comment is not needed.

2017-06-16 12:06 UTC, clintonb commented on ecommerce/enterprise/tests/test_utils.py
> +        # Validate value of the cookie is correct.
This comment is not needed.

2017-06-16 12:06 UTC, clintonb commented on ecommerce/enterprise/tests/test_decorators.py
> +        # Validate value of the cookie is correct.
This comment is not needed.

2017-06-16 12:27 UTC, saleem-latif commented
@clintonb Done, Please take a look

2017-06-20 01:30 UTC, douglashall approved these changes

2017-06-20 01:50 UTC, douglashall commented
@clintonb I believe all of your feedback has been addressed. I am going to merge this in.

2017-06-20 01:51 UTC, merged