Allow localization of Paypal checkout experience
openedx-unsupported/ecommerce pull request #1321
Opened 2017-06-12 14:32 UTC by stevenzheng3791

Allow locale setting for Paypal checkout. Currently set to "US", but should be set to whatever language is detected as chosen by the user (with default to "US").

LEARNER-1270

2017-06-12 14:38 UTC, schenedx requested changes
Have both questions and comments. Is this PR ready for review?

2017-06-12 14:38 UTC, schenedx commented on ecommerce/extensions/payment/processors/paypal.py
> +from paypalrestsdk import WebProfile, Payment
Please make a decision whether you want to import `paypalrestsdk` or the sub modules individually here.
Basically, either delete the line before this line, or remove this line

2017-06-12 14:38 UTC, schenedx commented on ecommerce/extensions/payment/processors/paypal.py
> +                    "locale_code": locale_code
How is this value transitioned to `ES` when needed?

2017-06-12 14:38 UTC, schenedx commented on ecommerce/extensions/payment/processors/paypal.py
> +        available_attempts = 2
Why do we need to make multiple attempts? Are you trying to address a bug? Is 2 attempts going to be enough?

2017-06-12 14:38 UTC, BenjiLee commented on ecommerce/extensions/payment/processors/paypal.py
> +        locale_code = "US" # TODO, set the locale code according to user settings, use "US" as default
Let's include the ticket number for this comment https://openedx.atlassian.net/browse/LEARNER-1278

2017-06-12 14:39 UTC, stevenzheng3791 commented
It is possible to create permanent payment experience profiles beforehand, perhaps one for each language, and grab the correct one when the user presses checkout with paypal. I think that would be better, but it would require unknown changes outside of this one file.

2017-06-12 14:45 UTC, stevenzheng3791 commented on ecommerce/extensions/payment/processors/paypal.py
> +                    "locale_code": locale_code
Right now it can't, until language detection is supported (LEARNER 1278). Transitioning to "ES" will be a combination of language detection and then setting that language.

2017-06-12 15:11 UTC, stevenzheng3791 commented on ecommerce/extensions/payment/processors/paypal.py
> +        available_attempts = 2
Removed the multiple attempts logic, it was unnecessary. 
Right now, we create a temporary paypal web profile that lasts 3 hours each time a user clicks checkout with paypal. To create a profile, we need to generate a unique name. In the (highly unlikely I think) event that the generated name is already taken by an existing temporary profile, then it would fail and default to english. I am exploring a solution to avoid temporary profiles altogether.

2017-06-12 15:11 UTC, stevenzheng3791 commented on ecommerce/extensions/payment/processors/paypal.py
> +from paypalrestsdk import WebProfile, Payment
Done

2017-06-12 19:01 UTC, BenjiLee commented on ecommerce/extensions/payment/processors/paypal.py
> +        # US - english
The US and ES comments could be removed. The link is sufficient

2017-06-12 19:21 UTC, BenjiLee commented on ecommerce/extensions/payment/processors/paypal.py
> +        name = ''.join(random.choice(string.ascii_uppercase) for i in range(12)) # Name needs to be unique so just generating a random one
nit: If `name` is not being used anywhere else you could move it right into the WebProfile

2017-06-12 21:13 UTC, bderusha commented on ecommerce/extensions/payment/processors/paypal.py
> -            web_profile = PaypalWebProfile.objects.get(name=self.DEFAULT_PROFILE_NAME)
@stevenzheng3791 @BenjiLee I missed this before.  We already have a database table for these profiles.

What if we did something where we look up the profile like `PaypalWebProfile.objects.get(name=locale)` and if it exists then we use it, otherwise we create a permanent one on-the-fly and then store it.

2017-06-14 16:04 UTC, stevenzheng3791 commented on ecommerce/extensions/payment/processors/paypal.py
> -            web_profile = PaypalWebProfile.objects.get(name=self.DEFAULT_PROFILE_NAME)
Maintaining the mapping turned out to be rather complicated after accounting for potential errors, as opposed to creating one on the fly, which is logically self-contained whether the API call succeeds or not. If the extra API call does turn out to be too slow, then we can look at mapping as a faster solution.

2017-06-15 21:41 UTC, BenjiLee commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> -    @ddt.data(None, Paypal.DEFAULT_PROFILE_NAME, 'some-other-name')
I think you forgot to revert the changes made to this test.

2017-06-15 21:44 UTC, BenjiLee commented on ecommerce/extensions/payment/processors/paypal.py
> +                        "name": str(uuid.uuid1()),
The comment about paypal requiring a 12 char unique name would be helpful here.

2017-06-15 21:45 UTC, BenjiLee commented on ecommerce/extensions/payment/processors/paypal.py
> +                        "temporary": True
A comment that says temporary == 3 hours would be helpful here.

2017-06-16 12:59 UTC, stevenzheng3791 commented on ecommerce/extensions/payment/processors/paypal.py
> +                        "name": str(uuid.uuid1()),
It actually doesn't, 12 char was just an example. I figured it'd be more straightforward to use the unique identifier library for the unique name.

2017-06-16 19:07 UTC, schenedx reviewed
This makes more sense. Please see if my comments make sense to you

2017-06-16 19:07 UTC, schenedx commented on ecommerce/extensions/payment/processors/paypal.py
> +                        logger.info("Web Profile[%s] created successfully", (web_profile.id))
We should log down the locale/language that prompted for this profile creation

2017-06-16 19:07 UTC, schenedx commented on ecommerce/extensions/payment/processors/paypal.py
> +                            "Error [%s]. Web Profile could not be created. Will continue without one.",
I think it's better to have the log message as `Web profile creation encountered error [%s]. Will continue without one.`

2017-06-16 19:07 UTC, schenedx commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +        self.assertNotIn('experience_profile_id', payment_creation_payload)
You should also make sure logging messages are done as part of this test

2017-06-16 19:07 UTC, schenedx commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +        self.assertNotIn('experience_profile_id', payment_creation_payload)
You should test that exception is raised and an error message is logged

2017-06-16 19:07 UTC, schenedx commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +        self.assertNotIn('experience_profile_id', payment_creation_payload)
Maybe you should also assert that the `paypalrestsdk.WebProfile` is not called with the flag toggled false?

2017-06-20 01:06 UTC, stevenzheng3791 commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +        self.assertNotIn('experience_profile_id', payment_creation_payload)
I've gotten rid of this test since it was testing the original functionality, and the existing test for it was already more thorough. I modified the original test to set the waffle flag to false.

2017-06-20 01:10 UTC, stevenzheng3791 commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +        self.assertNotIn('experience_profile_id', payment_creation_payload)
I've updated all logger messages, and now verified them and/or exceptions in all my tests

2017-06-20 13:27 UTC, schenedx commented on ecommerce/extensions/payment/processors/paypal.py
> +                web_profile_id = self.create_web_profile(locale_code)
#Minor I think the function name is better as `create_temporary_web_profile`

2017-06-20 13:29 UTC, schenedx approved these changes
Just a minor comment, rest LGTM

2017-06-20 19:30 UTC, BenjiLee approved these changes

2017-06-20 20:15 UTC, merged