ENT-242 Updated the payment page UI with Enterprise msg.
openedx-unsupported/ecommerce pull request #1333
Opened 2017-06-21 10:29 UTC by asadiqbal08

JIRA - [ENT-242](https://openedx.atlassian.net/browse/ENT-242)

@zubair-arbi @saleem-latif your initial thoughts on it ?

2017-06-21 11:14 UTC, zubair-arbi approved these changes
Once build is green 👍

2017-06-21 11:48 UTC, clintonb reviewed
Please post a screenshot.

2017-06-21 11:48 UTC, clintonb commented on ecommerce/coupons/views.py
> +                _('{html_start} A discount has been applied, courtesy of {enterprise_customer_name}. {html_end}').
There is no need to have the HTML in your translation string.

2017-06-21 11:48 UTC, clintonb commented on ecommerce/coupons/views.py
> +from django.contrib import messages
Sort.

2017-06-21 11:54 UTC, asadiqbal08 commented on ecommerce/coupons/views.py
> +                _('{html_start} A discount has been applied, courtesy of {enterprise_customer_name}. {html_end}').
so no need for `fa-info-circle` ?

2017-06-21 12:31 UTC, clintonb commented on ecommerce/coupons/views.py
> +            message = '{html_start}'.format(html_start='<i class="fa fa-info-circle"> ',) + \
Why is the icon necessary? Do we display an icon for any other messages? Will this conflict with that? Should we display the same icon for all info messages? If so, that should be a template, not here.

If you do need the icon here, stop using format unnecessarily and stop italicizing the entire string:
```python
message = _('A discount has been applied, courtesy of {enterprise_customer_name}.').format(enterprise_customer_name=enterprise_customer.get('name'))
message = '<i class="fa fa-info-circle"></i> {}'.format(message)
```

2017-06-21 20:41 UTC, brittneyexline reviewed
Code looks good! I will also approve once the build is green.
Is there a sandbox available for this? If it is too burdensome to spin that up yourself, we should try to get this onto the business sandbox for testing.

2017-06-21 20:45 UTC, clintonb requested changes
You need tests. Also, your commit message has a typo in the ticket number.

2017-06-21 20:45 UTC, clintonb commented on ecommerce/coupons/views.py
> +                self.request,
This can go on one line.

2017-06-22 12:05 UTC, asadiqbal08 commented
added test

2017-06-22 12:39 UTC, clintonb requested changes

2017-06-22 12:39 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        self.request.user = self.user
This line does nothing because self.request will never be used in this test.

2017-06-22 12:39 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        expected_url = self.get_full_url(path=reverse('basket:summary'))
There is no need to use get_full_url because the test client knows the domain. Also, the variable name doesn't correspond to its usage. 

`path = reverse('basket:summary')`

2017-06-22 12:39 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        code = self.prepare_enterprise_data(benefit_value=5, consent_enabled=False)
The benefit value doesn't matter, so don't override the default. Overriding a default signals to other developers that your test cares about the value. This test doesn't, so why bother overriding?

2017-06-22 12:39 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +            response, expected_url, status_code=302, target_status_code=200, fetch_redirect_response=False
target_status_code is not needed given that you aren't fetching a response.

2017-06-22 12:39 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        response_messages = messages.storage.cookie.CookieStorage(response)._decode(response.cookies['messages'].value)
There's no need to decode cookies. Pull messages from context. See https://github.com/edx/ecommerce/blob/8fde125db17565c28cdf182fd35416c5c05b9dee/ecommerce/extensions/dashboard/tests.py#L8.

2017-06-22 12:44 UTC, asadiqbal08 commented on ecommerce/coupons/tests/test_views.py
> +        response_messages = messages.storage.cookie.CookieStorage(response)._decode(response.cookies['messages'].value)
@zubair-arbi fyi

2017-06-22 12:46 UTC, asadiqbal08 commented on ecommerce/coupons/tests/test_views.py
> +        code = self.prepare_enterprise_data(benefit_value=5, consent_enabled=False)
sorry with `benefit_value=100`, I am getting [redirection](https://github.com/edx/ecommerce/blob/master/ecommerce/coupons/views.py#L240)

2017-06-22 12:59 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        code = self.prepare_enterprise_data(benefit_value=5, consent_enabled=False)
Add a comment with that explanation. Try not leave others guessing about your changes. That's easy to do with comments. 

Setting benefit value to a low amount to ensure the basket is not free, and calls to the checkout page do not redirect away from the checkout page.

2017-06-23 09:21 UTC, asadiqbal08 commented
@brittneyexline build is green.

2017-06-23 11:17 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        for context in response.context:
Why is this a loop? There is only one context.

2017-06-23 12:03 UTC, clintonb requested changes

2017-06-23 12:03 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        messages += response.context[0].get('messages', [])
You still haven't answered my question: Is there more than one context? 

The answer is no, there is only one context. `response.context` is a `dict`, not a `list`. See https://docs.djangoproject.com/en/1.11/topics/testing/tools/#django.test.Response.context for additional details.

Here is the corrected code: 
```python
messages = response.context['messages']
self.assertEqual(len(messages), 1)
```

2017-06-23 12:15 UTC, asadiqbal08 commented on ecommerce/coupons/tests/test_views.py
> +        messages += response.context[0].get('messages', [])
@clintonb there are more than one context in response that's why I use the loop. However I have eliminate the loop logic. Kindly approve the PR.

2017-06-23 12:33 UTC, clintonb commented on ecommerce/coupons/tests/test_views.py
> +        messages = []
`messages = response.context['messages']`

2017-06-23 12:41 UTC, clintonb approved these changes
Please address the last comment.

Note that I am not intentionally trying to be a roadblock. Out jobs as engineers is to not simply solve the problem, but to effectively communicate anything that might trip someone up later (including our future selves).

While the test may have seemed simple, it differed significantly from every test in our codebase. Differences are okay *if* they are properly explained via comments. Otherwise, seemingly simple solutions end up with a lot of questions.

2017-06-23 12:54 UTC, asadiqbal08 commented on ecommerce/coupons/tests/test_views.py
> +        messages = []
`response.context['messages']` gives me a `FallbackStorage` object but in list it is a `storage.base.Message` object that is what I get from [storage beckends](https://hdknr.github.io/docs/django/django.contrib.messages.storage.html)

2017-06-23 13:15 UTC, asadiqbal08 commented
@clintonb Thanks for the feedback on the PR. I agree with you but if I look around the other existing tests in same file then sure there are many places that need to be documented and named properly. 
As an example, If you look around the method that is basically returning a `code` but its name is  something confusing --- [prepare_enterprise_data](https://github.com/edx/ecommerce/blob/master/ecommerce/coupons/tests/test_views.py#L454)  and it is used many other places.
As an other example, I could not understand the reason why this [value is coded `100`](https://github.com/edx/ecommerce/blob/master/ecommerce/coupons/tests/test_views.py#L457) here, while I was writing the test. 

So I agree, we should effectively communicate anything that might trip someone up later.

2017-06-23 13:17 UTC, clintonb commented
If you see a problem with the code, fix it! No one else will maintain our codebase for us.

2017-06-23 21:04 UTC, douglashall commented
@asadiqbal08  I have cherry-picked this commit onto a sprint branch (edx/ecommerce:mighty_mouse) and deployed that branch to https://business.sandbox.edx.org.

2017-06-28 15:26 UTC, brittneyexline commented
rebased from https://github.com/edx/ecommerce/pull/1333/commits/1a7be4707ebcc3bd744aab97d5869eaee12d2927

2017-06-29 20:10 UTC, merged