[WIP] -- ENT-243: Update Receipt page to display Enterprise sponsorship
openedx-unsupported/ecommerce pull request #1335
Opened 2017-06-22 09:52 UTC by saleem-latif

@douglashall , @asadiqbal08 , @zubair-arbi -- FYI

I will add more info once implementation is finalized.

2017-06-23 14:29 UTC, brittneyexline reviewed
Is there a sandbox for this? This might be another good candidate to deploy onto the business sandbox @douglashall

2017-06-23 14:29 UTC, brittneyexline commented on ecommerce/enterprise/tests/test_templatetags.py
> +class EnterpriseTempateTagsTests(EnterpriseServiceMockMixin, CouponMixin, TestCase):
There is a missing "l" in Template here

2017-06-23 14:32 UTC, clintonb requested changes

2017-06-23 14:32 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt.html
> +                            {% trans "Courtesty of " %}
Use blocktrans.

2017-06-23 14:32 UTC, clintonb commented on ecommerce/enterprise/templatetags/enterprise.py
> +    request = get_current_request()
We should minimize, and eventually eliminate, our use of `threadlocals`. Please update your template tag to use the view's context. See https://stackoverflow.com/a/2160298/592820.

2017-06-23 21:05 UTC, douglashall commented
@saleem-latif  I have cherry-picked this commit onto a sprint branch (edx/ecommerce:mighty_mouse) and deployed that branch to https://business.sandbox.edx.org.

2017-06-29 19:03 UTC, douglashall requested changes
I think we need to get clarification from Griff on whether we should be displaying the sponsorship message in the product description section of the page.

2017-06-29 19:03 UTC, douglashall commented on ecommerce/templates/edx/checkout/receipt.html
> +                            {% blocktrans with enterprise_name=enterprise_customer.name %}
This looks like it will blow up if there is no `EnterpriseCustomer` in play here.

2017-06-29 19:03 UTC, douglashall commented on ecommerce/templates/edx/checkout/receipt.html
> +                          <div class="enterprise-customer">
We probably should not render this element at all if there is no `EnterpriseCustomer` in play for a receipt.

2017-06-30 08:34 UTC, itsjeyd reviewed
@brittneyexline Had a look at the code, it looks good to me aside from a couple formatting nits.

@douglashall Could you deploy the new commits on the business sandbox? I think it would be worth verifying the updated changeset there before merging.

2017-06-30 08:34 UTC, itsjeyd commented on ecommerce/enterprise/tests/test_templatetags.py
> +
@brittneyexline Remove empty line.

2017-06-30 08:34 UTC, itsjeyd commented on ecommerce/enterprise/tests/test_templatetags.py
> +        mock_utils.side_effect = EnterpriseDoesNotExist()
@brittneyexline Formatting nit: Switch L55 and L56.

2017-06-30 09:45 UTC, douglashall commented
@itsjeyd The newest commit is now deployed to the business sandbox.

2017-06-30 12:23 UTC, clintonb requested changes
1. Generate translations. 
2. Post screenshots of the desktop, tablet, and phone views with the longest supported partner name. 
3. Squash your commits.

2017-06-30 12:23 UTC, clintonb commented on ecommerce/enterprise/templatetags/enterprise.py
> +        return utils.get_enterprise_customer_from_voucher(request and request.site, voucher)
What if there is no request? You're simultaneously writing risky and defensive code. Make it all defensive.

2017-06-30 12:23 UTC, clintonb commented on ecommerce/enterprise/tests/test_templatetags.py
> +        request.site = self.site
Use `self.request`. It's already setup for you.

2017-06-30 12:23 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt.html
> +                        {% blocktrans with enterprise_name=enterprise_customer.name %}
Add the trimmed argument to get rid of white space.

2017-06-30 12:23 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt.html
> +            {% trans "View Course on Your Dashabord" %}
No. We sell products that happen to be courses. Never assume that (a) an order only contains course products or that (b) an order only contains one item.

2017-06-30 15:50 UTC, brittneyexline commented on ecommerce/templates/edx/checkout/receipt.html
> +            {% trans "View Course on Your Dashabord" %}
You bring up a good point - this was done according to the mock ups for this ticket, however I think the context of when to show this wasn't clearly defined, so I'm going to revert this part.

2017-06-30 15:56 UTC, brittneyexline commented
Here are a few screenshots @clintonb. One thing that your request brought to mind is that our character limit is quite long for the enterprise name, and we should probably make it shorter:

<img width="1343" alt="screen shot 2017-06-30 at 11 01 23 am" src="https://user-images.githubusercontent.com/524809/27743602-897a4e1e-5d8a-11e7-94c9-bd61f83d4487.png">
<img width="389" alt="screen shot 2017-06-30 at 11 02 11 am" src="https://user-images.githubusercontent.com/524809/27743606-8cdb18a4-5d8a-11e7-8375-6192ba2ede9d.png">
<img width="803" alt="screen shot 2017-06-30 at 11 02 44 am" src="https://user-images.githubusercontent.com/524809/27743614-91a45f6c-5d8a-11e7-9faa-2dc8c4675d60.png">

Here's a screenshot with a more expected enterprise name:
<img width="1326" alt="screen shot 2017-06-30 at 11 55 24 am" src="https://user-images.githubusercontent.com/524809/27743750-090dabf8-5d8b-11e7-9aed-4d20ab1e5e79.png">

2017-07-01 09:41 UTC, douglashall approved these changes
Looks good to me. Just need to fix the translations one more time.

2017-07-01 13:51 UTC, clintonb approved these changes

2017-07-05 17:22 UTC, merged