WIP Move edx.org theme into ecommerce repo
openedx-unsupported/ecommerce pull request #1340
Opened 2017-06-23 09:31 UTC by amangano-edx

Moves the edx.org theme from https://github.com/edx/edx-themes into this repo so that we can translate the footer more easily.

Corresponding edx-themes PR: https://github.com/edx/edx-themes/pull/521

JIRA: https://openedx.atlassian.net/browse/LEARNER-1576 (subtask of https://openedx.atlassian.net/browse/LEARNER-1271)

WIP because this hasn't been fully tested, and I'm not sure if any configuration changes are necessary.

2017-06-23 11:14 UTC, clintonb requested changes
We should setup some time to chat about theming. Moving any theme back into this repository is not ideal. I would much rather move toward adopting a model similar to what we do with credentials, where the theme is its own app, and setup those repos to translations.

2017-06-23 11:17 UTC, amangano-edx commented
@clintonb Our team is aware that this is not an ideal solution, but we decided to go with this approach for now so that we can meet our deadline by the end of this week. I talked with @douglashall yesterday about a better approach that we can apply when we have more time. We will definitely be doing that as we will need it for credentials, which also uses a separate themes repo. Please see the comments in https://openedx.atlassian.net/browse/LEARNER-1271 for more context on what was discussed and our decision making process.

2017-06-23 14:10 UTC, douglashall approved these changes
Do you want to also run makemessages or will you do that in a separate PR?

2017-06-23 14:10 UTC, douglashall commented on ecommerce/themes/edx.org/static/sass/base/overrides.scss
> +}
Add an extra line.

2017-06-26 18:48 UTC, BenjiLee commented
closing in favor of https://github.com/edx/ecommerce/pull/1350

2017-06-26 18:48 UTC, closed without merging