Check for embargo course access.
openedx-unsupported/ecommerce pull request #1352
Opened 2017-06-28 00:08 UTC by mjfrey

LEARNER-1525

Check for course access via the LMS embargo API.

2017-06-28 13:24 UTC, mjfrey commented
@edx/helio Please review.

2017-06-28 13:47 UTC, iivic commented on ecommerce/core/models.py
> +    @property
I noticed that we use @cached_property when jwt is set.

2017-06-28 13:47 UTC, iivic commented on ecommerce/extensions/basket/tests/test_utils.py
> +        """ Verify embargo check passes when API call thorws an exception. """
Nit: thorws

2017-06-28 13:47 UTC, iivic commented on ecommerce/extensions/payment/utils.py
> +        courses (list): A list of courses to check access against
Nit: your parameter is called `products` while here you state `courses`

2017-06-28 13:47 UTC, iivic commented on ecommerce/extensions/payment/utils.py
> +        # We are going to allow purchase if the API is un-reachable.
We usually catch three types of exceptions ConnectionError, SlumberBaseException and Timeout. Do you want to allow any kind of error or just those for connection issues?

2017-06-28 13:47 UTC, iivic commented on ecommerce/extensions/payment/utils.py
> +        if not response.get('access'):
Why not just return response.get('access')?

2017-06-28 13:52 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +        if not response.get('access'):
EdxRestAPI just returns a response

2017-06-28 13:52 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +        # We are going to allow purchase if the API is un-reachable.
I really want to catch all exceptions.

2017-06-28 13:58 UTC, vkaracic requested changes

2017-06-28 13:58 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_utils.py
> +            re.compile(self.site_configuration.build_lms_url('/api/embargo/v1')),
Why are you using regex here for the URL?

2017-06-28 13:58 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_utils.py
> +        self.assertEqual(basket.lines.count(), 0)
The docstring states that you verify if the `embargo_check` is called yet I don't see that assertion here.

2017-06-28 13:58 UTC, vkaracic commented on ecommerce/extensions/payment/tests/test_utils.py
> +            re.compile(self.site_configuration.build_lms_url('/api/embargo/v1')),
Same question for regex here.

2017-06-28 13:58 UTC, vkaracic commented on ecommerce/extensions/payment/utils.py
> +        courses.append(product.course.id)
What happens if you try and purchase enrollment codes?

2017-06-28 13:58 UTC, vkaracic commented on ecommerce/extensions/payment/tests/test_utils.py
> +        self.assertEqual(response, embargo_response)
I think you should be testing how `embargo_check()` works here. I think you're just testing here if you'll get the response from going directly to the endpoint that you previously mocked.

2017-06-28 14:15 UTC, mjfrey commented on ecommerce/extensions/payment/tests/test_utils.py
> +            re.compile(self.site_configuration.build_lms_url('/api/embargo/v1')),
This is the way to match on the API with kwargs

2017-06-28 14:15 UTC, mjfrey commented on ecommerce/extensions/basket/tests/test_utils.py
> +            re.compile(self.site_configuration.build_lms_url('/api/embargo/v1')),
The only way to match the API with kwargs

2017-06-28 14:16 UTC, mjfrey commented on ecommerce/extensions/payment/utils.py
> +        courses.append(product.course.id)
Good catch, we only are checking against seats.  I will add the check.

2017-06-28 14:16 UTC, mjfrey commented on ecommerce/extensions/basket/tests/test_utils.py
> +        self.assertEqual(basket.lines.count(), 0)
comment fixed.

2017-06-28 14:17 UTC, mjfrey commented on ecommerce/extensions/payment/tests/test_utils.py
> +        self.assertEqual(response, embargo_response)
I am testing this also in prepare_basket.

2017-06-28 14:27 UTC, vkaracic commented on ecommerce/extensions/payment/tests/test_utils.py
> +            re.compile(self.site_configuration.build_lms_url('/api/embargo/v1')),
Can you give me an example of what URL is not working for you? Because a URL with any kwargs/string-queries should work just fine.
```
In [1]: import requests

In [2]: import httpretty

In [3]: httpretty.enable()

In [4]: httpretty.register_uri(httpretty.GET, 'http://test-me.com', body="HIT!!")

In [5]: print requests.get('http://test-me.com')
<Response [200]>

In [6]: print requests.get('http://test-me.com').content
HIT!!

In [7]: print requests.get('http://test-me.com/').content
HIT!!

In [8]: print requests.get('http://test-me.com/?a=b').content
HIT!!
```

2017-06-28 14:28 UTC, mjfrey commented on ecommerce/extensions/payment/tests/test_utils.py
> +            re.compile(self.site_configuration.build_lms_url('/api/embargo/v1')),
I am not sure what your problem is with the regex?  Why does it bother you?

2017-06-28 14:29 UTC, vkaracic commented on ecommerce/extensions/payment/tests/test_utils.py
> +        self.assertEqual(response, embargo_response)
I was referring that this test doesn't make much sense. You're basically testing if mocking works here.

2017-06-28 14:36 UTC, mjfrey commented on ecommerce/extensions/payment/tests/test_utils.py
> +        self.assertEqual(response, embargo_response)
you are right, it is a bit extraneous, but the more tests the better :)

2017-06-28 14:37 UTC, vkaracic commented on ecommerce/extensions/payment/tests/test_utils.py
> +            re.compile(self.site_configuration.build_lms_url('/api/embargo/v1')),
I don't have problems with regex. I think it's not necessary to use it, since we never needed it before to register a URL.

2017-06-28 15:22 UTC, schenedx commented on ecommerce/extensions/basket/tests/test_utils.py
> +            re.compile(self.site_configuration.build_lms_url('/api/embargo/v1')),
@mjfrey can you add a comment here for using the regex?

2017-06-28 15:23 UTC, schenedx commented on ecommerce/extensions/basket/utils.py
> +                _('Due to export controls, we cannot allow you to access this course at this time.')
@mjfrey Is the word `access` what you wrote? Or it's part of the message agreed with copy writers and legal?

2017-06-28 16:00 UTC, mjfrey commented on ecommerce/extensions/basket/utils.py
> +                _('Due to export controls, we cannot allow you to access this course at this time.')
@schenedx This is virtual the copy we have in the LMS today.

2017-06-28 16:08 UTC, schenedx approved these changes
👍

2017-06-28 16:29 UTC, mjfrey commented
@clintonb can you take a look

2017-06-29 01:09 UTC, clintonb approved these changes

2017-06-29 01:09 UTC, clintonb commented on ecommerce/core/models.py
> +    @property
`@cached_property`

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +        self.site_configuration.enable_embargo_check = True
You can avoid future confusion by putting this line in your tests rather than the mock method.

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +            body=body,
Nit: Do your JSON conversion here.

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +        """ Verify embargo check passes when API call thorws an exception. """
throws

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +        """ Verify an basket is returned after adding enrollment code. """
a basket

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +        self.assertEqual(basket.lines.count(), 1)
Nit: You should ensure the correct product is in the basket.

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +        self.mock_embargo_api(body=timeoutException, status=400)
Nit: replace `timeoutException` with `lambda: raise requests.Timeout`.
Also, there is no need for the status kwarg since it won't be used.

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +def embargo_check(request, products):
Avoid passing request objects as this constricts this method to usage solely within the request cycle. Instead pass the user and site separately since they are the only parts of the request you need.

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +            if not response.get('access'):
`return response.get('access', True)`

2017-06-29 01:09 UTC, clintonb commented on ecommerce/extensions/payment/utils.py
> +        True or False
bool

2017-06-29 11:47 UTC, mjfrey commented on ecommerce/extensions/basket/tests/test_utils.py
> +        self.mock_embargo_api(body=timeoutException, status=400)
That syntax does not seem to work.

2017-06-29 11:54 UTC, vkaracic commented on ecommerce/extensions/basket/tests/test_utils.py
> +        self.mock_embargo_api(body=timeoutException, status=400)
Try with `lambda: requests.Timeout`.

2017-06-29 11:58 UTC, vkaracic approved these changes

2017-06-29 13:40 UTC, merged