Escaped string for translation
openedx-unsupported/ecommerce pull request #1361
Opened 2017-06-29 20:24 UTC by BenjiLee

2017-06-29 20:40 UTC, clintonb requested changes

2017-06-29 20:40 UTC, clintonb commented on ecommerce/extensions/payment/forms.py
> +    countries.insert(0, ('', _('&lt;Choose country&gt;')))
The symbols do not need to be translated. Move them outside of the call to `gettext`. Also, why are they HTML instead of the existing characters?

2017-06-29 21:03 UTC, BenjiLee commented on ecommerce/extensions/payment/forms.py
> +    countries.insert(0, ('', _('&lt;Choose country&gt;')))
Transifex was trying to treat the <> as an HTML tag so I replaced them. Your suggestion to not wrap the tags is a better idea.

2017-06-30 00:01 UTC, BenjiLee commented
@clintonb Updated PR. Ready for another pass.

2017-06-30 00:03 UTC, clintonb approved these changes

2017-06-30 00:53 UTC, clintonb commented
Generate updated translation files (skip djangojs.*).

2017-06-30 15:03 UTC, merged