Updated E-Commerce Service to use a site-specific URL for Catalog Service
openedx-unsupported/ecommerce pull request #1368
Opened 2017-07-03 09:09 UTC by iivic

LEARNER-1135

TODO:

- [ ] Check for program caching and enable multitenancy support for caching

2017-07-03 09:09 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1368"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-07-03 11:55 UTC, marjev approved these changes
Just a few nitpicks, otherwise LGTM

2017-07-03 11:55 UTC, marjev commented on ecommerce/core/models.py
> +        if waffle.switch_is_active("multi-site-course-catalog-url") and self.course_catalog_api_url:
Use single quotes

2017-07-03 11:55 UTC, marjev commented on ecommerce/core/tests/test_models.py
> +        toggle_switch("multi-site-course-catalog-url", switch_enabled)
Use single quotes.

2017-07-03 11:55 UTC, marjev commented on ecommerce/core/tests/test_models.py
> +    def test_course_catalog_api_client(self, switch_enabled, api_url_model_value, expected_api_url):
I suggest renaming `api_url_model_value` to `site_course_catalog_api_url`.

2017-07-04 12:44 UTC, afzaledx commented
@iivic, the '@cached_property' decorator will probably keep on returning the first fetched value in all subsequent calls, so the per-site configuration will not work as desired.

2017-07-05 11:34 UTC, iivic commented
@clintonb  please review.

2017-07-05 12:30 UTC, clintonb requested changes

2017-07-05 12:30 UTC, clintonb commented on ecommerce/core/models.py
> +    course_catalog_api_url = models.URLField(
Replace references to course catalog with discovery. That's the name we'll be using from now on.

2017-07-05 12:30 UTC, clintonb commented on ecommerce/programs/api.py
> +    def get_program(self, uuid, site_domain):
Pass this on the constructor, just as we do for the client.

2017-07-05 12:30 UTC, clintonb commented on ecommerce/core/models.py
> +        if waffle.switch_is_active('multi-site-course-catalog-url') and self.course_catalog_api_url:
Update the switch name to better reflect what will happen if it is activated: use_multi_tenant_discovery_api_urls

2017-07-05 12:30 UTC, clintonb commented on ecommerce/core/tests/test_models.py
> +    def test_course_catalog_api_client(self, switch_enabled, site_course_catalog_api_url, expected_api_url):
Split this into two tests:

- test_course_catalog_api_client
- test_course_catalog_api_client_without_multitenancy

When cleanup time comes, all you'll need to do is delete the second test.

2017-07-05 12:30 UTC, clintonb commented on ecommerce/core/models.py
> +    course_catalog_api_url = models.URLField(
Also, generate translations.

2017-07-05 12:30 UTC, clintonb commented on ecommerce/core/models.py
> +    course_catalog_api_url = models.URLField(
Also, add this field to the management command that creates sites, and update the provisioning script in edx/devstack to set this field's value.

2017-07-06 11:01 UTC, iivic commented
@clintonb comments addressed please take another look.

2017-07-06 13:00 UTC, clintonb requested changes

2017-07-06 13:00 UTC, clintonb commented on ecommerce/conf/locale/en/LC_MESSAGES/djangojs.po
> +"POT-Creation-Date: 2017-07-06 10:35+0000\n"
Unless you make JS changes, there is no need to commit djangojs translation files.

2017-07-06 13:00 UTC, clintonb commented on ecommerce/core/models.py
> +        help_text=_('URL for discovery API.'),
This help text adds no additional value over the field name. Get rid of it.

2017-07-06 13:00 UTC, clintonb commented on ecommerce/enterprise/tests/test_entitlements.py
> +DISCOVERY_API_URL = 'https://catalog.example.com/api/v1/'
Where is this used?

2017-07-06 13:00 UTC, clintonb commented on ecommerce/core/tests/decorators.py
> +def mock_discovery_api_client(test):
Get rid of this decorator. All it does is prevent a call to the access token endpoint. Given that we already have a mock method for that, this decorator is unnecessary. The same goes for `mock_enterprise_api_client` below. This file can go away, and the tests updated with calls to `mock_access_token`.

2017-07-06 13:00 UTC, clintonb commented on ecommerce/core/tests/test_models.py
> +        self.site.siteconfiguration.discovery_api_url = DISCOVERY_API_URL
Update `SiteConfigurationFactory` to generate this URL. Ultimately, it will become a required field.

2017-07-06 13:00 UTC, clintonb commented on ecommerce/courses/tests/mixins.py
> +        settings.DISCOVERY_API_URL,
Update this class to use the multi-tenant URL. Also, update the name of the class.

2017-07-06 13:00 UTC, clintonb commented on ecommerce/coupons/tests/mixins.py
> +            settings.DISCOVERY_API_URL,
Updated this class to use the multi-tenant URL, and the class name.

Ideally, after a bit of time in production, we should be able to simply ditch the switch and setting, and be permanently multi-tenant. This means we need to get rid of many of these references to the setting.

2017-07-06 13:00 UTC, clintonb commented on ecommerce/settings/base.py
> +DISCOVERY_API_URL = 'http://localhost:8008/api/v1/'
This name is overwritten in secure configuration, and should not be changed.

2017-07-07 08:49 UTC, iivic commented on ecommerce/enterprise/tests/test_entitlements.py
> +DISCOVERY_API_URL = 'https://catalog.example.com/api/v1/'
Couldn't find where it's used. Removing the line.

2017-07-10 15:35 UTC, iivic commented
@clintonb please take another look.

2017-07-10 16:22 UTC, clintonb reviewed
There's a lot of renaming/refactoring happening here. It might be best to split this into a few PRs:

1. Refactor, moving/merging code, etc.
2. Renaming
3. Add multi-tenancy.

2017-07-10 16:22 UTC, clintonb commented on ecommerce/core/management/commands/create_or_update_site.py
> +                            help='URL for Discovery service API calls (e.g. http://localhost:8008/api/v1/).')
Drop the example URL. It's no longer valid given that we should be using Docker Devstack.

2017-07-10 16:22 UTC, clintonb commented on ecommerce/core/management/commands/create_or_update_site.py
> +            'discovery_api_url': discovery_api_url
Add a trailing comma.

2017-07-10 16:22 UTC, clintonb commented on ecommerce/coupons/tests/mixins.py
> +    def mock_dynamic_discovery_single_course_runs_api(
`mock_course_run_detail_endpoint`

2017-07-10 16:22 UTC, clintonb commented on ecommerce/coupons/tests/mixins.py
> +        """ Helper function to register a dynamic discovery API endpoint for the course run information. """
Mocks the course run detail endpoint on the Discovery API.

2017-07-10 16:22 UTC, clintonb commented on ecommerce/coupons/tests/mixins.py
> +    def mock_fetch_course_catalog(
`mock_catalog_detail_endpoint`

2017-07-10 16:22 UTC, clintonb commented on ecommerce/coupons/tests/mixins.py
> +    def mock_discovery_api_for_catalog_voucher(
This seems to be used in precisely one location. It doesn't need a method.

2017-07-10 16:22 UTC, clintonb commented on ecommerce/coupons/tests/mixins.py
> +    def mock_dynamic_catalog_course_runs_api(
`mock_course_runs_endpoint`

2017-07-10 16:22 UTC, clintonb commented on ecommerce/coupons/tests/mixins.py
> +    def mock_dynamic_catalog_contains_api(self, course_run_ids, query, discovery_api_url=DEFAULT_DISCOVERY_API_URL):
`mock_course_runs_contains_endpoint`

2017-07-10 16:22 UTC, clintonb commented on ecommerce/courses/tests/mixins.py
> +class DiscoveryServiceMockMixin(object):
Merge this with `DiscoveryMockMixin` above. There seems to be some overlap.

2017-08-02 13:36 UTC, iivic commented
This work is merged in three separate PRs.

2017-08-02 13:36 UTC, closed without merging