Fire Product Added event when item added to basket
openedx-unsupported/ecommerce pull request #1369
Opened 2017-07-03 14:22 UTC by McKenzieW

Updated Basket model add_product method to include a call to the Google Analytics "Product Added" event.

LEARNER-1566

2017-07-03 14:46 UTC, clintonb requested changes
I think your IDE may be doing more than it should.

Git pro-tips:

1. Squash your commits before requesting a review. As you gain experience you will only need one round of reviews. Get everything in order so you can simply press the merge button without having to debase and wait for the build to pass again. 
2. Rebate on master instead of merging it into your branch to avoid merge bubbles.

2017-07-03 14:46 UTC, clintonb commented on ecommerce.yml
> +---
This shouldn't b here.

2017-07-03 14:46 UTC, clintonb commented on ecommerce/extensions/analytics/tests/test_utils.py
> +
Remove. mock is a third-party lib.

2017-07-03 14:46 UTC, clintonb commented on ecommerce/extensions/basket/models.py
> -from oscar.apps.basket.models import *  # noqa isort:skip pylint: disable=wildcard-import,unused-wildcard-import,wrong-import-position
Restore this block.

2017-07-03 14:46 UTC, clintonb commented on ecommerce/extensions/basket/utils.py
> -
Revert.

2017-07-03 15:09 UTC, marjev reviewed
I see Clinton already left valuable comments. I only noticed two smaller things that might be changed.

2017-07-03 15:09 UTC, marjev commented on ecommerce/extensions/basket/models.py
> +    def add_product(self, product, quantity=1, options=None):
Please add a docstring for this method. We're trying to write a Google style Python docstring for each method.
See the example here: https://gist.github.com/dsaiztc/9b4c15c6dfef08a957c1
Basic idea is to have a short description, a list of parameters and return values available in a docstring.

2017-07-03 15:09 UTC, marjev commented on ecommerce/extensions/basket/tests/test_models.py
> +            is added to the basket """
I think this docstring can fit in a single line. I think we allow 120 characters per line.

2017-07-03 15:16 UTC, McKenzieW commented on ecommerce/extensions/basket/models.py
> -from oscar.apps.basket.models import *  # noqa isort:skip pylint: disable=wildcard-import,unused-wildcard-import,wrong-import-position
This causes issues with the quality check. Should it not be at the top of of the file?

2017-07-03 15:34 UTC, clintonb commented on ecommerce/extensions/basket/models.py
> -from oscar.apps.basket.models import *  # noqa isort:skip pylint: disable=wildcard-import,unused-wildcard-import,wrong-import-position
Nope. It belongs here. We want our definition of the Basket model to take precedence. Quality checks haven't failed in the months this has been here. It's fine.

2017-07-10 20:34 UTC, McKenzieW commented
https://github.com/edx/ecommerce/pull/1382

2017-07-10 20:34 UTC, closed without merging