Multi-Tenant Support for E-Commerce Service API endpoints
openedx-unsupported/ecommerce pull request #1372
Opened 2017-07-04 11:54 UTC by vkaracic

LEARNER-1130

@edx/helio please review.

2017-07-04 11:54 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1372"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-07-05 12:39 UTC, vkaracic commented
@clintonb please review.

2017-07-05 15:41 UTC, clintonb requested changes
Every viewset needs at least one test on the list endpoint validating these changes.

2017-07-05 15:41 UTC, clintonb commented on ecommerce/extensions/api/v2/views/catalog.py
> +        return super(CatalogViewSet, self).get_queryset().filter(
Nit: Ditch `super` and the `queryset` field above.

`return Catalog.objects.filter(partner=self.request.site.siteconfiguration.partner)`

2017-07-05 15:41 UTC, clintonb commented on ecommerce/extensions/api/v2/views/courses.py
> +        ).all()
Drop `.all()`

2017-07-05 15:41 UTC, clintonb commented on ecommerce/extensions/api/v2/views/products.py
> +    queryset = Product.objects.all()
Move this into the method below.

2017-07-05 15:41 UTC, clintonb commented on ecommerce/extensions/api/v2/views/products.py
> +            Q(course__site=self.request.site)
Don't assume products are associated with courses. Remove this. The stock record filtering is sufficient.

2017-07-06 08:04 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/products.py
> +            Q(course__site=self.request.site)
Parent course products don't have stock records associated with them.

2017-07-06 08:07 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/catalog.py
> +        return super(CatalogViewSet, self).get_queryset().filter(
This won't work with nested catalogs. `NestedViewSetMixin` should first do the filtering based on the parent ID and then filter those results by partner. Filtering directly here will render the nesting useless since it would return all the catalogs (filtered by partner) regardless of the parent ID.

2017-07-06 12:22 UTC, clintonb commented on ecommerce/extensions/api/v2/views/catalog.py
> +        return super(CatalogViewSet, self).get_queryset().filter(
Add a comment explaining this.

2017-07-06 12:22 UTC, clintonb commented on ecommerce/extensions/api/v2/views/products.py
> +            Q(course__site=self.request.site)
Add a comment explaining this.

2017-07-06 12:23 UTC, clintonb approved these changes

2017-07-06 12:23 UTC, clintonb commented
Remember to add comments for the last two items, and squash your commits.

2017-07-06 13:09 UTC, vkaracic commented
@clintonb I've added tests for each viewset. Please take another look.

2017-07-06 13:13 UTC, clintonb requested changes
You did a bit too much work for these tests. Simplify:

```python
def test_list(self):
  # TODO Create data for multiple partners
  # TODO Verify data is returned for a single partner
```
For the existing tests, you should only need to create some data for another partner. The existing tests are sufficient.

2017-07-06 14:27 UTC, vkaracic commented
@clintonb take another look please.

2017-07-11 10:15 UTC, vkaracic commented
@clintonb ping.

2017-07-11 11:12 UTC, marjev requested changes

2017-07-11 11:12 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_catalog.py
> +        """Assert that the catalog list endpoint response content is as expected."""
I think you're missing the body of the method.

2017-07-11 11:12 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_catalog.py
> +        Catalog.objects.create(name='New catalog', partner=new_partner)
Can you send `PartnerFactory()` directly? I don't see `new_partner` being used again.

2017-07-11 11:12 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        self.create_coupon(partner=new_partner)
Can these two lines be one? Is `new_partner` ever reused?

2017-07-11 11:12 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +        ProductFactory(stockrecords__partner=new_partner)
Same comment as before.

2017-07-11 11:12 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_stockrecords.py
> +        StockRecordFactory(partner=new_partner)
Same comment as before.

2017-07-11 11:12 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        self.create_vouchers(partner=new_partner)
Same comment as before.

2017-07-11 11:12 UTC, marjev commented on ecommerce/extensions/basket/tests/test_views.py
> +            'failure_url=http%3A%2F%2Ftestserver.fake%2Fbasket%2F%3Fconsent_failed%3D{code}'.format(code=COUPON_CODE)
Shouldn't this be part of the format parameters as well? I think `testserver.fake` comes from either a Factory instance or settings.

2017-07-11 13:05 UTC, vkaracic commented
@marjev comments addressed.

2017-07-11 13:18 UTC, clintonb reviewed
You're still doing way too much with these tests. I'm not a fan of the mixin because it's a bit too generic.

Literally all you need to do for the existing tests is create some for the non-default partner and add a comment informing future developers the data should not be returned. There is no need for any of these other changes to test code

```python
def test_list(self):
  # This data won't be returned because it's associated with the wrong site/partner.
  ProductFactory.create_batch(3, partner=PartnerFactory())

  # <Existing Test>
```

2017-07-11 13:18 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/mixins.py
> +        self.assertEqual(response_data['count'], count)
Nit: If the results match, checking the count doesn't really matter.

2017-07-11 13:18 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/mixins.py
> +        response_data = json.loads(response.content)
Use `response.data` to get Python instead of JSON, and you can ditch all of the conversion.

2017-07-11 13:18 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/mixins.py
> +        expected_data = json.dumps(serializer(obj, context={'request': self.request}).data)
Nit: Use the `many` kwarg: `expected = serializer([obj], context={'request': self.request}, many=True).data`

2017-07-12 13:11 UTC, vkaracic commented
@clintonb comments addressed!

2017-07-12 13:22 UTC, clintonb approved these changes

2017-07-12 13:22 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_courses.py
> +        CourseFactory(id='new/test/course', site=new_site)
All you need is `CourseFactory()`. It will do all the work for you.

2017-07-12 13:22 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_stockrecords.py
> +        StockRecordFactory(partner=PartnerFactory())
Just use `StockRecordFactory()`.

2017-07-12 13:35 UTC, vkaracic commented
@marjev please re-review.

2017-07-13 05:22 UTC, marjev approved these changes

2017-07-13 05:23 UTC, merged