Updated E-Commerce Service to use a site-specific URL for Discovery Service
openedx-unsupported/ecommerce pull request #1385
Opened 2017-07-11 14:38 UTC by iivic

LEARNER-1135

Splitting https://github.com/edx/ecommerce/pull/1368/files into three pieces this one should be merged first.

- [ ] Add references to the remaining PRs once they are created.

@clintonb FYI.

2017-07-11 14:38 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1385"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-07-11 15:34 UTC, clintonb requested changes
There is a lot of unnecessary duplication of the `toggle_switch()` call. I suggest moving it to `setUp()` of the base `TestCase` class. That way there is very little code to remove to roll this out permanently.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/tests/factories.py
> +    discovery_api_url = factory.LazyAttribute(lambda obj: 'http://{domain}/api/v1/'.format(domain=obj.site.domain))
Use faker: http://faker.readthedocs.io/en/master/providers/faker.providers.internet.html?highlight=url#faker-providers-internet

2017-07-11 15:34 UTC, clintonb commented on ecommerce/programs/tests/test_forms.py
> +        toggle_switch('use_multi_tenant_discovery_api_urls', True)
Why duplicate? Move to `setUp()`.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/programs/tests/test_conditions.py
> +        toggle_switch('use_multi_tenant_discovery_api_urls', True)
Move to `setUp()`.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/programs/tests/mixins.py
> +    DEFAULT_DISCOVERY_API_URL = 'http://testserver.fake/api/v1'
No more hardcoding. This should come from `self.site_configuration`.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        toggle_switch("use_multi_tenant_discovery_api_urls", True)
Move to `setUp()`. Also, use single quotes.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_models.py
> +        toggle_switch('use_multi_tenant_discovery_api_urls', True)
Move to `setUp()`.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        toggle_switch("use_multi_tenant_discovery_api_urls", True)
Move to `setUp()`.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +        toggle_switch('use_multi_tenant_discovery_api_urls', True)
Move to `setUp()`.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/extensions/api/v2/tests/views/test_catalog.py
> +        toggle_switch("use_multi_tenant_discovery_api_urls", True)
Move to `setUp()`.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/enterprise/tests/test_entitlements.py
> +        toggle_switch('use_multi_tenant_discovery_api_urls', True)
Move to `setUp()`.

2017-07-11 15:34 UTC, clintonb commented on ecommerce/coupons/tests/mixins.py
> +    DEFAULT_DISCOVERY_API_URL = 'http://testserver.fake/api/v1/'
Create from `self.site_configuration`.

2017-07-12 08:05 UTC, iivic commented on ecommerce/tests/factories.py
> +    discovery_api_url = factory.LazyAttribute(lambda obj: 'http://{domain}/api/v1/'.format(domain=obj.site.domain))
The idea was to activate the switch for tests that really need it instead of running it for every test. Since it will get removed anyway your suggestion makes more sense.

2017-07-12 08:07 UTC, iivic commented on ecommerce/programs/tests/test_forms.py
> +        toggle_switch('use_multi_tenant_discovery_api_urls', True)
The idea was to activate the switch for tests that really need it. Since it will get removed anyway your suggestion makes more sense.

2017-07-12 10:37 UTC, iivic commented on ecommerce/tests/factories.py
> +    discovery_api_url = factory.LazyAttribute(lambda obj: 'http://{domain}/api/v1/'.format(domain=obj.site.domain))
In order to add the fake url the `@mock_course_catalog_api_client` decorator must be removed. I was planing to do so in the refactor PR. I will include this comment there.

2017-07-12 11:45 UTC, clintonb commented on ecommerce/tests/factories.py
> +    discovery_api_url = factory.LazyAttribute(lambda obj: 'http://{domain}/api/v1/'.format(domain=obj.site.domain))
The factory is not dependent on decorators. You can modify the factory with faker instead of using the lambda with no issue.

2017-07-12 12:15 UTC, iivic commented on ecommerce/tests/factories.py
> +    discovery_api_url = factory.LazyAttribute(lambda obj: 'http://{domain}/api/v1/'.format(domain=obj.site.domain))
Decorator mocks the SiteConfiguration.discovery_api_client while mocks like mock_dynamic_catalog_single_course_runs_api use the factory discovery_api_url to create the discovery client and if we add the faker without removing the decorator the urls will not match.

2017-07-12 12:17 UTC, clintonb commented on ecommerce/tests/factories.py
> +    discovery_api_url = factory.LazyAttribute(lambda obj: 'http://{domain}/api/v1/'.format(domain=obj.site.domain))
Perhaps the decorator should have been removed first. Add the comment, and remember to switch to `Faker` after the decorator is removed.

2017-07-12 12:51 UTC, iivic commented
@clintonb please verify everything is in place. I would like to squash and merge.

2017-07-12 12:55 UTC, clintonb approved these changes

2017-07-12 12:55 UTC, clintonb commented on ecommerce/tests/testcases.py
> +        toggle_switch('use_multi_tenant_discovery_api_urls', True)
Add a comment explaining that this is temporary, and linking to the ticket to remove this.

2017-07-12 13:43 UTC, iivic commented
@clintonb strange I covered my changes but codecov is complaining. What is the procedure in this case?

2017-07-12 13:46 UTC, clintonb commented
You touched files that previously had less than 100% coverage. Our overall coverage dropped after https://github.com/edx/ecommerce/pull/1384 was merged because not all JS files are covered. I'll merge and update Codecov's threshold.

2017-07-12 13:46 UTC, merged