Fire Product Removed event when item removed from basket
openedx-unsupported/ecommerce pull request #1386
Opened 2017-07-11 21:07 UTC by McKenzieW

Before flushing a basket, fire 'Product Removed' Segment event for each product that was in the basket.

[LEARNER-1567]

2017-07-12 13:59 UTC, mjfrey requested changes

2017-07-12 13:59 UTC, mjfrey commented on ecommerce/extensions/basket/utils.py
> +    for line in basket.all_lines():
Rather than doing this here.  Override the flush method in the Basket model.  Then call Super.

2017-07-12 16:17 UTC, mjfrey commented on ecommerce/extensions/basket/models.py
> +    def flush(self):
you need to call the Super method so the default behavior still happens.

2017-07-12 16:22 UTC, McKenzieW commented on ecommerce/extensions/basket/models.py
> +    def flush(self):
yes, so silly of me to forget. Thank you!

2017-07-12 16:34 UTC, clintonb requested changes

2017-07-12 16:34 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +    def _prepare_basket_segment_event(self, isEmpty):
Use snake_casing for Python (e.g. `is_empty`). That said, `empty` is sufficient.

2017-07-12 16:34 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +        basket = BasketFactory(owner=self.request.user, site=self.site_configuration.site)
Avoid relying on `self.request`. We should not depend on requests outside of views. Use `self.create_user()`.

2017-07-12 16:34 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +            if isEmpty:
If statements in tests are a code smell. Your test methods should do one thing well. Move these assertions to the test methods. This method should only be concerned with creating the basket.

2017-07-12 18:15 UTC, mjfrey commented on ecommerce/extensions/basket/models.py
> +        super(Basket, self).flush()  # pylint: disable=bad-super-call
This will need to go after the track calls otherwise there will be no lines.

2017-07-13 18:05 UTC, McKenzieW commented
@mjfrey @clintonb can I get a confirmation from y'all on the changes you requested? Otherwise, ready to merge.

2017-07-13 18:48 UTC, clintonb requested changes
Ditch `_flush_segment_event`. Convenience methods that are too convenient end up doing us a disservice because the branching logic hides potential issues and/or makes them difficult to process mentally. Since there is little commonality amongst your two test cases, there is little need for a convenience method.

2017-07-13 18:48 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +        basket = self._create_basket(user, site)
Can you pass the empty flag here? It seems strange to flush the basket on the line below only to create another product and add it to the basket.

2017-07-13 18:48 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +            if empty:
An if statement in the test means you're doing too much for one test, or for one helper method in this case. This should be split appropriately. De-duplication is nice, but not the extent that it makes your tests unreadable.

Compare what you have to this below.

```python
    def test_flush_events(self):
        """ Flushing the basket should fire the "Product Removed" event for all lines in the basket. """
        user = factories.UserFactory()
        basket = Basket.create_basket(self.site, user)

        properties = translate_basket_line_for_segment(basket.lines.first())
        user_tracking_id, lms_client_id, lms_ip = parse_tracking_context(basket.owner)
        context = {
            'ip': lms_ip,
            'Google Analytics': {
                'clientId': lms_client_id
            }
        }

        with mock.patch.object(Client, 'track') as mock_track:
            basket.flush()
            mock_track.assert_called_once_with(user_tracking_id, 'Product Removed', properties, context=context)

    def test_flush_events_for_empty_basket(self):
        """ Flush an empty basket should NOT fire any events. """
        user = factories.UserFactory()
        basket = Basket.create_basket(self.site, user)

        with mock.patch.object(Client, 'track') as mock_track:
            basket.flush()
            self.assertEqual(mock_track.call_count, 0)
```

2017-07-13 18:48 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +    def test_flush_with_product(self):
Add docstrings explaining what these tests do.

2017-07-13 18:50 UTC, mjfrey commented on ecommerce/extensions/basket/tests/test_models.py
> +        basket.flush()
I don't think you need this as new baskets are empty.

2017-07-13 18:50 UTC, mjfrey commented on ecommerce/extensions/basket/tests/test_models.py
> +        site = SiteConfigurationFactory().site
you could use self.site1 rather than creating a new one.

2017-07-13 19:58 UTC, McKenzieW commented
@clintonb @mjfrey your requests have been addressed

2017-07-13 19:58 UTC, mjfrey approved these changes

2017-07-13 20:05 UTC, clintonb approved these changes
* Address the remaining comments
* Add the ticket number to your commit message. See the guidelines at https://openedx.atlassian.net/wiki/display/ECOM/Developer+Onboarding.

2017-07-13 20:05 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +        self.site1.siteconfiguration = SiteConfigurationFactory()
Do you need to make a new instance? `self.site` already exists. If you aren't doing anything special with Site or SiteConfiguration, there's no need to make more of them.

2017-07-13 20:05 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +        basket.save()
This call should not be needed.

2017-07-13 20:05 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +        self.site1.siteconfiguration = SiteConfigurationFactory()
Same comment as above.

2017-07-13 20:10 UTC, McKenzieW commented on ecommerce/extensions/basket/tests/test_models.py
> +        basket.save()
sorry, which part of this should not be needed?

2017-07-13 20:12 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +        basket.save()
This line to save the basket. The call to `add_product()` updates the m2m relations. There is no need to save after this.

2017-07-13 20:14 UTC, McKenzieW commented on ecommerce/extensions/basket/tests/test_models.py
> +        basket.save()
Ah ok, I didn't realize. Thank you

2017-07-13 20:14 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +        basket.save()
You're welcome.

2017-07-13 20:24 UTC, McKenzieW commented on ecommerce/extensions/basket/tests/test_models.py
> +        self.site1.siteconfiguration = SiteConfigurationFactory()
There needs to be a site configuration for the segment event to work, and there doesn't already exist one for any of the site objects, so I need to add it.

2017-07-13 20:57 UTC, merged

2017-07-13 21:16 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_models.py
> +        self.site1.siteconfiguration = SiteConfigurationFactory()
`self.site` is created by `SiteMixin`. It is already configured appropriately. See https://github.com/edx/ecommerce/blob/ac971e8b72c3f4fd4aca1a438d268286c85e507b/ecommerce/tests/mixins.py#L253.

2017-07-14 13:00 UTC, McKenzieW commented on ecommerce/extensions/basket/tests/test_models.py
> +        self.site1.siteconfiguration = SiteConfigurationFactory()
That is crazy because when I tried to use self.site I got an error saying that it had no siteconfiguration attribute