Add management command to create a set of courses from json
openedx-unsupported/ecommerce pull request #1392
Opened 2017-07-14 13:10 UTC by stevenzheng3791

LEARNER-1817
https://openedx.atlassian.net/browse/LEARNER-1817

This management command allows you to create a set of courses from properly-formatted json. Eventually, a provisioning script from docker devstack should be used to call this command, as opposed to using this command directly (It would be cumbersome to specify json directly on the command line)

2017-07-14 13:32 UTC, schenedx requested changes
Please see my feedback inline.

Also, how would this management command be used? I see all the courses are passed in as a large string of json format. How is that being passed in?

2017-07-14 13:32 UTC, schenedx commented on ecommerce/core/management/commands/generate_courses.py
> +        # verification_deadline = timezone.now() + datetime.timedelta(days=366)
#nitpick This commented out line should be removed?

2017-07-14 13:32 UTC, schenedx commented on ecommerce/core/management/commands/generate_courses.py
> +                store = course_settings["store"]
Can we be explicit for the variable? Just say `module_store` instead of `store`?

2017-07-14 13:32 UTC, schenedx commented on ecommerce/core/management/commands/generate_courses.py
> +                raise CommandError("Course JSON object is missing required id fields")
Wouldn't this stop the command? Should we do that? Should we continue the command so we can consume other courses specified in the json?

2017-07-14 13:32 UTC, schenedx commented on ecommerce/core/tests/test_generate_courses.py
> +        error_msg = "Modulestore invalid_store is invalid"
This is a very confusing error message. Can we make this message better?

2017-07-14 13:32 UTC, schenedx commented on ecommerce/core/tests/test_generate_courses.py
> +    def test_create_audit_seat(self):
From this point in the file, the test cases pattern is quite repetitive. Can we refactor so we can use ddt to make this a single test with different test inputs?

2017-07-14 13:32 UTC, schenedx commented on ecommerce/core/management/commands/generate_courses.py
> +    help = 'Generate courses on ecommerce from a json list of courses. Should only be run in development environments!'
Should we implement this command so if this is run in the production environment, throws an exception? You should be able to determine whether this is in production environment through settings. I don't know exactly which setting tho. Can you find out?

2017-07-14 13:51 UTC, stevenzheng3791 commented
The way I have it planned is to have a provisioning script in docker devstack load a json file containing a list of courses and pass that json to this management command (as well as analogous commands on mktg and studio so that courses are linked across services). Eventually, users should be able to auto-populate this json file based on what course settings they'd like to permute on (e.g. certificate types), rather than specify course json manually.

2017-07-18 01:48 UTC, stevenzheng3791 commented on ecommerce/core/management/commands/generate_courses.py
> +                raise CommandError("Course JSON object is missing required id fields")
Yes, thank you for point this out. I've updated it to only raise exception if the preliminary checks fail.

2017-07-18 16:57 UTC, BenjiLee commented on ecommerce/core/management/commands/generate_courses.py
> +                    course_id = "course-v1:{org}/{num}/{run}".format(org=org, num=num, run=run)
Mongo course_id's do not have `course-v1:` prepended. They look like `{org}/{num}/{run}`

2017-07-18 17:00 UTC, BenjiLee commented on ecommerce/core/management/commands/generate_courses.py
> +            logger.info(msg)
nit: You could probably fit this all in one line.

logger.info("Created course with id {}".format(course.id))

2017-07-18 17:07 UTC, BenjiLee commented on ecommerce/core/management/commands/generate_courses.py
> +            if not set(seat_types).issubset(self.valid_seat_types):
It might be better to do this verification before even attempting to create a course. That way, we won't have to worry about the clean up.

2017-07-18 17:11 UTC, BenjiLee commented on ecommerce/core/management/commands/generate_courses.py
> +            # Requires manually creating TestCreditProvider in the LMS django admin
Should this raise an Exception if TestCreditProvider is not set?

2017-07-18 17:12 UTC, schenedx reviewed
Looks better. I agree with comments made by @BenjiLee

2017-07-18 17:15 UTC, BenjiLee commented on ecommerce/core/management/commands/generate_courses.py
> +        partner = Partner.objects.get(short_code='edx')
Do these have to be hardcoded?

2017-07-18 17:17 UTC, BenjiLee commented on ecommerce/core/management/commands/generate_courses.py
> +        if not settings.DEBUG:
Could you describe whats settings.DEBUG is in a github comment?

2017-07-18 17:34 UTC, BenjiLee commented
@stevenzheng3791 Done with first pass

2017-07-19 02:25 UTC, stevenzheng3791 commented on ecommerce/core/management/commands/generate_courses.py
> +            # Requires manually creating TestCreditProvider in the LMS django admin
I've decided to get rid of this case for now. It isn't very functional right now without provisioning a credit provider before hand. In the future, if we find out we need credit courses, then we can figure out the best way to go about handling it.

2017-07-19 02:29 UTC, stevenzheng3791 commented on ecommerce/core/management/commands/generate_courses.py
> +        partner = Partner.objects.get(short_code='edx')
It is because partner and site for 'edx' are already provisioned in docker devstack. Unless it turns out developers want to set it (would require manually provisioning a partner/site right now), I think this is the simplest way to allow course creation

2017-07-19 14:32 UTC, BenjiLee commented on ecommerce/core/management/commands/generate_courses.py
> +        return True
Nit: We could log all the missing fields in one run. If a user is missing all of the fields, they will only get the error message for one.

2017-07-20 19:47 UTC, BenjiLee approved these changes

2017-07-21 14:09 UTC, schenedx approved these changes
Just one place I believe we should update.
rest LGTM

2017-07-21 14:09 UTC, schenedx commented on ecommerce/core/management/commands/generate_courses.py
> +            print options["courses"]
Should we use `print` or use `logger` here?

2017-07-25 14:04 UTC, merged