Fixed coupon redemption report for programs only lists one course id
openedx-unsupported/ecommerce pull request #1397
Opened 2017-07-18 13:37 UTC by iivic

LEARNER-1823

2017-07-18 13:37 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1397"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-07-18 13:40 UTC, iivic commented
<img width="880" alt="screen shot 2017-07-18 at 15 38 49" src="https://user-images.githubusercontent.com/16685686/28319903-6fc97550-6bcf-11e7-976b-fe119bb0b304.png">

2017-07-18 14:32 UTC, iivic commented
@edx/helio please review.

2017-07-18 19:48 UTC, mjfrey approved these changes

2017-07-19 07:01 UTC, marjev requested changes

2017-07-19 07:01 UTC, marjev commented on ecommerce/extensions/voucher/utils.py
> +    if set(['Catalog Query', 'Program UUID']).intersection(set(header_row)):
why not `if 'Catalog Query' in header_row or 'Program UUID' in header_row:`?

2017-07-20 08:55 UTC, marjev approved these changes

2017-07-20 10:46 UTC, merged