Updated Order Completed segment event to include Coupon data
openedx-unsupported/ecommerce pull request #1400
Opened 2017-07-19 15:07 UTC by Mjloturco

Segment events were not tracking coupon or discount values, events fired now have include a coupon field containing the name of the coupon and a discount field containing the value of the discount they have received.

 [LEARNER-1918] cloned from [LEARNER-1568]

2017-07-19 19:06 UTC, mjfrey commented on ecommerce/extensions/checkout/signals.py
> +        coupon_name = discount.voucher.name
A few things here.  There may be a discount that does not have a voucher.
For example, we have program offers which are discounts that the learner does not have to enter a code at checkout time.  

You can get those via:
discount.offer

I would suggest we send a list of vouchers, offers and total all the discounts together.

2017-07-20 13:30 UTC, clintonb requested changes
These are not valid properties. See the documentation at https://segment.com/docs/spec/ecommerce/v2/#order-completed.

2017-07-20 13:30 UTC, clintonb commented on e2e/test_auth.py
> +import pytest  # isort:skip
Revert. General rule of thumb: if merged code has a quality issue, the issue probably lies with your machine, not the merged code. In this case, you probably haven't installed Pytest. Run `make requirements` to install the e2e test requirements.

2017-07-20 13:30 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +    # coupon_name = None
No dead code in the repo.

2017-07-20 13:30 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +        'discount_names': discount_names,
Where did these field names come from? They are not listed at https://segment.com/docs/spec/ecommerce/v2/#order-completed.

2017-07-20 13:39 UTC, Mjloturco commented on e2e/test_auth.py
> +import pytest  # isort:skip
Got it, will revert.

2017-07-20 13:41 UTC, clintonb commented
@Mjloturco I'm going to let you do the digging, instead of telling you exactly what to change, to help you learn more about Otto and Oscar. Here are a few hints, however.

1. We only allow one coupon/voucher per order.
2. We may have multiple offers per order (but only one will be voucher-based).
3. The `Order` model has everything you need.

2017-07-20 14:06 UTC, Mjloturco commented
@clintonb thanks for the hints, I'll make sure to stick with actual segment event properties. Are we interested in tracking the names of applied offers in some way as well?  The docs specify the "discount" property is a total discount, are we worried this may appear as if the entire discount is due to the one voucher?

Example case: order pre-offer total is $100, a voucher "examplevoucher" discounts $10, and a separate offer discounts $10 as well. Discount would be 20, despite the coupon only accounting for half of that.

2017-07-20 17:50 UTC, Mjloturco commented
@clintonb I made the changes you requested.

2017-07-20 18:07 UTC, clintonb requested changes

2017-07-20 18:07 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +        'discount': str(discount_value),
See https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/order/abstract_models.py#L201.

```python
str(order. total_discount_incl_tax)
```

2017-07-20 18:07 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +    for discount in order.discounts.all():
There is no need to iterate over all discounts. You can filter in the database.

```python
voucher = order.basket_discounts.filter(voucher_id__isnull=False).first()
coupon = voucher.voucher_code if voucher else None
```

2017-07-21 15:28 UTC, Mjloturco commented on ecommerce/extensions/checkout/signals.py
> +    for discount in order.discounts.all():
Fixed

2017-07-21 15:28 UTC, Mjloturco commented on ecommerce/extensions/checkout/signals.py
> +        'discount': str(discount_value),
Fixed

2017-07-21 15:56 UTC, clintonb approved these changes
Fix the tests, and you're good to go.

2017-07-21 15:56 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +        voucher = order.basket_discounts.filter(voucher_id__isnull=False).first()
Pass the voucher in as an argument. You want to avoid using the code being tested in your test in case that code is wrong.

2017-07-21 15:56 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +    def test_track_completed_fixed_discounted_order(self):
The voucher type shouldn't matter. I see no need for a separate test case.

2017-07-21 15:56 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +    def test_track_completed_fixed_discounted_order(self):
I would convert this to a test with both a voucher and another offer (without a voucher).

2017-07-21 16:13 UTC, merged

2017-07-21 16:16 UTC, Mjloturco commented
Just realized it was approved only with changes, making a new pr right now to fix.