Updated Program Conditional Offer logic to allow for partial programs
openedx-unsupported/ecommerce pull request #1401
Opened 2017-07-19 20:04 UTC by McKenzieW

is_satisfied method checks items in basket and for condition satisfaction, and continues on to user's enrollments if condition is not satisfied, allowing for discount application on the remaining courses in a program when a user adds them to their basket.

LEARNER-1901

2017-07-19 20:42 UTC, mjfrey commented on ecommerce/programs/conditions.py
> +        verified_enrollments = set()
Take a look below.  You will need to check if any of the modes are in the applicable_seat_types.  Not just verified.

2017-07-24 20:49 UTC, McKenzieW commented
@edx/helio

2017-07-25 06:40 UTC, marjev requested changes
Mostly suggestions. Let me know if you need any help or clarification of some of my comments.

2017-07-25 06:40 UTC, marjev commented on ecommerce/programs/conditions.py
> +        """ Retrieve the enrollments for the specified User """
Can you add args and return value to the docstring the same way it's done in e. g. `get_program` method found above?

2017-07-25 06:40 UTC, marjev commented on ecommerce/programs/conditions.py
> +            logger.exception(u'An unexpected error occurred while retrieving enrollments for [%s].', username)
You can import `from __future__ import unicode_literals` at the beginning of the file to avoid having explicit unicode string literals.

2017-07-25 06:40 UTC, marjev commented on ecommerce/programs/conditions.py
> +        """ Determine whether or not the user is enrolled in a given course """
Please extend the docstring with descriptions of args and return value.

2017-07-25 06:40 UTC, marjev commented on ecommerce/programs/conditions.py
> +    def enrolled(self, enrollments, course, applicable_seat_types):
Can you please rename this and give it a more descriptive name? I suggest `determine_user_enrollment` since it's a method and I like to name methods as actions. It's only a suggestion and perhaps you can think of a more descriptive name.

2017-07-25 06:40 UTC, marjev commented on ecommerce/programs/conditions.py
> +        return False
If you want, you can use Python's any built-in function like this:
```
return any(
    course['uuid'] == enrollment['course_details']['course_id'] and enrollment['mode'] in applicable_seat_types 
    for enrollment in enrollments
)
```

2017-07-25 06:40 UTC, marjev commented on ecommerce/programs/tests/mixins.py
> +            course_id = i
I'm not sure I understand why this is needed. Why's the counter value assigned as the seat ID?

2017-07-25 13:18 UTC, clintonb requested changes

2017-07-25 13:18 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> -
Revert.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/conditions.py
> +            url = '{}?user={}'.format(get_lms_enrollment_api_url(), username)
Create an `enrollment_api_client` property on the `SiteConfiguration` model and use it, similar to how we call other APIs. Also, use JWT authentication.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/conditions.py
> +                return json.loads(response.json())
`response.json()` will give you a Python object. There is no need to call `json.loads()`. In fact, this line will fail. (Make sure you've manually tested this locally.)

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/conditions.py
> +            if course['uuid'] == enrollment['course_details']['course_id']:
The course's UUID will never be equivalent to a course ID. The simplest check is to determine if `enrollment['course_details']['course_id'].startswith(course['key'])`.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/conditions.py
> +                if enrollment['mode'] in applicable_seat_types:
Combine with the above if statement.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/conditions.py
> +            url = '{}?user={}'.format(get_lms_enrollment_api_url(), username)
Is this endpoint paginated? You may need to account for that.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/mixins.py
> +                course_run.create_or_update_seat('audit', False, Decimal(0), self.partner)
This change is unnecessary. Revert.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/mixins.py
> +                        'id': seat_id,
Our code doesn't care about seat IDs. The API doesn't even expose them. This needs to go away.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/mixins.py
> +            courses.append({'uuid': course_id, 'course_runs': course_runs, })
I'm not sure what's going on here in this file. The only change needed to the data is the addition of a `'key'` field on this line. The rest is unnecessary.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/mixins.py
> +            courses.append({'uuid': course_id, 'course_runs': course_runs, })
See the API for the exposed fields: https://prod-edx-discovery.edx.org/api/v1/programs/3fa369a7-4055-4f6d-8e31-b5b50c19ac73/.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/test_conditions.py
> +        self.test_product = ProductFactory(categories=[])
This is not necessary. If your tests are dependent on product categories something is wrong.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/test_conditions.py
> +        """ The method should return an empty list if their is an error when trying to retrieve enrollments """
s/their/there

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/test_conditions.py
> +            method=httpretty.GET,
Nit: these are the first two arguments. There is no need for the `method=` and `uri=` components.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/test_conditions.py
> +        with mock.patch('ecommerce.programs.conditions.ProgramCourseRunSeatsCondition.get_enrollments',
Nit: Make this a decorator over the entire method.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/test_conditions.py
> +        basket or the user's enrolled courses """
Add a period at the end of the sentence.

2017-07-25 13:18 UTC, clintonb commented on ecommerce/programs/tests/test_conditions.py
> +        enrollments = [{'mode': 'verified', 'course_details': {'course_id': 1}},
These are not valid course keys. See `CourseFactory` for an example generator.

2017-07-26 15:40 UTC, McKenzieW commented on ecommerce/programs/tests/test_conditions.py
> +            method=httpretty.GET,
Sorry, I'm not sure what you mean by this.

2017-07-26 15:45 UTC, clintonb commented on ecommerce/programs/tests/test_conditions.py
> +            method=httpretty.GET,
```python
uri = '{}?user={}'.format(get_lms_enrollment_api_url(), user.username)
httpretty.register_uri(httpretty.GET, uri, status=404)
```

You don't need to specify `method=` or `uri=` because they are positional arguments. See https://docs.python.org/3/glossary.html#term-argument for an example of the difference between positional and keyword arguments.

2017-07-26 16:04 UTC, McKenzieW commented on ecommerce/programs/tests/test_conditions.py
> +            method=httpretty.GET,
Oh ok I see. I didn't realize that you were mentioning that they were positional arguments.

2017-08-01 19:45 UTC, McKenzieW commented
@edx/helio please review

2017-08-01 19:54 UTC, clintonb commented on ecommerce/courses/utils.py
> +            'X-Edx-Api-Key': settings.EDX_API_KEY
This endpoint now supports using JWT for authentication, and staff users can now read all enrollments. Please update this code to use the JWT. In general, if you find yourself needing the API key header, you should update the API to use proper authentication and authorization schemes.

2017-08-02 12:37 UTC, staubina commented on ecommerce/courses/utils.py
> +            'X-Edx-Api-Key': settings.EDX_API_KEY
@clintonb Can you please provide a link to documentation or an example of how to upgrade the authentication method.  Thank you.

2017-08-02 13:10 UTC, McKenzieW commented on ecommerce/courses/utils.py
> +            'X-Edx-Api-Key': settings.EDX_API_KEY
I think I've gotten it mostly sorted, just can't find information on a JWT key that would allow us to access returned data (all the examples I found in the code base were for payment processing)

2017-08-02 13:20 UTC, staubina requested changes
Some minor changes requested. Otherwise looks good.

2017-08-02 13:20 UTC, staubina commented on ecommerce/courses/utils.py
> +    except Exception:  # pylint: disable=broad-except
nit: You do not need to changes this I know it was a code move. Just as a general note I am not a fan of using general Exception catching.  It can be risky and hide/mask real errors.  There is logging in this case so we should be ok, but it should be avoided.

2017-08-02 13:20 UTC, staubina commented on ecommerce/extensions/dashboard/users/tests/test_views.py
> +        with mock.patch('ecommerce.courses.utils.get_enrollments', mock_get_enrollments):
I am glad we were able to work out this Mocking issue 👍

2017-08-02 13:20 UTC, staubina commented on ecommerce/programs/conditions.py
> +            # If the user is alread enrolled in a course, we do not need to check their basket for it
Small issue, Typo in the comment

2017-08-02 13:23 UTC, clintonb commented on ecommerce/courses/utils.py
> +            'X-Edx-Api-Key': settings.EDX_API_KEY
See https://github.com/edx/ecommerce/blob/06dcd6566c07517088ce9a71ce22fe335f2a156c/ecommerce/core/models.py#L422-L424, and mimic that behavior for the Enrollment API.

2017-08-03 07:52 UTC, marjev approved these changes

2017-08-03 07:53 UTC, marjev commented
You should fix quality, otherwise looks good.

2017-08-04 13:05 UTC, staubina approved these changes
Good work.  Changes are working in the basket as expected.  Remember to wait on merging this.

👍

2017-08-07 16:44 UTC, McKenzieW commented
Changes from this PR are included in https://github.com/edx/ecommerce/pull/1434

2017-08-07 16:44 UTC, closed without merging