[ENT-493] New data sharing consent API
openedx-unsupported/ecommerce pull request #1426
Opened 2017-08-01 06:11 UTC by haikuginger

This pull request updates ecommerce to use the new generic data sharing consent API, as well as adopt a different format for communicating the linked enterprise to the LMS for use in consent creation.

WIP.

2017-08-01 06:11 UTC, edx-webhook commented
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1426"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-08-01 15:45 UTC, brittneyexline commented on ecommerce/enterprise/utils.py
> +    from slumber.exceptions import HttpNotFoundError
is there a reason this line is here if it's getting imported above?

2017-08-01 15:45 UTC, brittneyexline commented on ecommerce/extensions/fulfillment/modules.py
> +                data['linked_enterprise_customer'] = str(enterprise_customer_uuid)
i don't understand the purpose or effect of this change, can you explain?

2017-08-01 18:06 UTC, itsjeyd requested changes
@haikuginger This looks good to me in general. I had a few comments about functions that no longer seem to be referenced anywhere, though, and would also like to know the answers to the questions that @brittneyexline raised.

> There is a a concern that we are not able to use the new endpoint to determine whether or not consent is required in ecommerce at the time of enrollment

Does the implementation address this?

2017-08-01 18:06 UTC, itsjeyd commented on ecommerce/enterprise/utils.py
> -    ec_user = get_enterprise_customer_user(site, username, enterprise_customer_uuid)
@haikuginger `get_enterprise_customer_user` seems to be unused now.

2017-08-01 18:06 UTC, itsjeyd commented on ecommerce/enterprise/utils.py
> -        account_consent_provided = enterprise_customer_user_consent_provided(ec_user)
@haikuginger `enterprise_customer_user_consent_provided` seems to be unused now.

2017-08-01 18:06 UTC, itsjeyd commented on ecommerce/enterprise/utils.py
> -    consent_needed = enterprise_customer_needs_consent(enterprise_customer)
@haikuginger `enterprise_customer_needs_consent` seems to be unused now.

2017-08-01 20:46 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +    from slumber.exceptions import HttpNotFoundError
Ah, no. Code cruft that I need to remove.

2017-08-01 20:47 UTC, haikuginger commented on ecommerce/extensions/fulfillment/modules.py
> +                data['linked_enterprise_customer'] = str(enterprise_customer_uuid)
Basically, previously, when this POST hit the enrollment API, we were implicitly getting the linked EnterpriseCustomer by looking for an EnterpriseCustomerUser, and then adding a consent record for the enrolled course with that user. The new consent API expects us to be more explicit, so now, the actual EnterpriseCustomer that was linked to the coupon is being transmitted across so that we can use it in an explicit call to the consent API.

2017-08-01 20:47 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> -    consent_needed = enterprise_customer_needs_consent(enterprise_customer)
👍

2017-08-01 20:48 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> -        account_consent_provided = enterprise_customer_user_consent_provided(ec_user)
👍

2017-08-01 20:48 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> -    ec_user = get_enterprise_customer_user(site, username, enterprise_customer_uuid)
👍

2017-08-14 06:54 UTC, haikuginger commented
Rebased from fa852e4f.

2017-08-14 08:04 UTC, haikuginger commented
@itsjeyd @brittneyexline, tests are set to go and comments are addressed.

2017-08-14 08:06 UTC, haikuginger commented
Squashed from 9ab32b25.

2017-08-14 09:24 UTC, itsjeyd reviewed
@haikuginger Recent updates to the code look good to me. I tried testing this on the sandbox, and found that I wasn't able to create a coupon (for Pied Piper and the VNC course); got

> Error! An error occurred while saving the data.

when trying to submit coupon data.

2017-08-14 15:07 UTC, haikuginger commented
@itsjeyd I'm guessing there's a migration in the Pink Panther branch that I'm missing here. Stand by.

2017-08-14 15:09 UTC, haikuginger commented
@itsjeyd Yeah, just needed to run migrations. This should be set for you to run through on the sandbox now.

2017-08-14 15:41 UTC, itsjeyd approved these changes
@haikuginger Yup, was able to complete the steps from the test instructions now :+1:

- [x] I tested this: Works as advertised in PR description
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ N/A (no new flows)
- [x] ~~Includes documentation~~ N/A

2017-08-14 20:00 UTC, douglashall commented on ecommerce/enterprise/utils.py
> +        return endpoint._try_to_serialize_response(e.response)['consent_required']  # pylint: disable=protected-access
What is the purpose of this code? Why are we calling this protected function?

2017-08-14 20:22 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +        return endpoint._try_to_serialize_response(e.response)['consent_required']  # pylint: disable=protected-access
Slumber doesn't have a native way for us to get a deserialized response body when the server returned an error code. So we can either access Slumber's "private" functions to do it for us in a way that matches the way it behaves when it receives a non-error response, or we can just naively use the `json` module to do it ourselves - which is more Pylint-compliant, but also more brittle.

2017-08-14 20:51 UTC, douglashall commented on ecommerce/enterprise/utils.py
> +        return endpoint._try_to_serialize_response(e.response)['consent_required']  # pylint: disable=protected-access
Why are we returning a 404 status from the consent API if we are actually returning consent data?

2017-08-15 16:52 UTC, douglashall requested changes
@haikuginger One last question to address here.

2017-08-15 17:25 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +        return endpoint._try_to_serialize_response(e.response)['consent_required']  # pylint: disable=protected-access
We return a 404 as an early distinguisher about whether a relevant record exists. There's no reason we can't also return a response body on a 404 with additional details, and the 404 status code conceptually maps to "entity does not exist" in the HTTP lexicon.

2017-08-15 17:51 UTC, douglashall commented on ecommerce/enterprise/utils.py
> +        return endpoint._try_to_serialize_response(e.response)['consent_required']  # pylint: disable=protected-access
I think 200 is the more appropriate status code here if you are returning a non-error response body from the API endpoint. If we need to a way to identify that the a data sharing consent record did not exist then let's add that to the data returned from the API endpoint.

2017-08-16 11:11 UTC, haikuginger commented on ecommerce/enterprise/utils.py
> +        return endpoint._try_to_serialize_response(e.response)['consent_required']  # pylint: disable=protected-access
Okay, making that change!

2017-08-16 12:15 UTC, haikuginger commented
@douglashall, addressed.

2017-08-16 12:56 UTC, haikuginger commented
Looks like we've got unrelated ESLint tests that are failing on multiple branches. I'll try rebasing on master to see if that resolves it.

2017-08-16 14:08 UTC, douglashall commented
@haikuginger Looks like the build failure here is not related to ESLint, but instead:

```
pep8 --config=.pep8 ecommerce e2e
ecommerce/enterprise/utils.py:269:1: E302 expected 2 blank lines, found 1
Makefile:60: recipe for target 'quality' failed
make: *** [quality] Error 1
```

2017-08-16 14:16 UTC, haikuginger commented
@douglashall I don't see those lines in the Travis log at all. Here's what I see:

```
Message:

    Failed with 2 errors

Makefile:65: recipe for target 'validate_js' failed

make: *** [validate_js] Error 1
```

2017-08-17 02:45 UTC, haikuginger commented
Rebased from c69bc7d0.

2017-08-17 03:06 UTC, haikuginger commented
@douglashall, we've got a green check here, so once you sign off, we're set to merge. No rush, though, since we want to delay the rollout on this somewhat.

2017-08-17 09:32 UTC, douglashall approved these changes

2017-08-18 16:47 UTC, haikuginger commented
Squashed from 8ada68da.

2017-08-18 17:25 UTC, merged