[WIP] Refactor ecommerce course generator command
openedx-unsupported/ecommerce pull request #1432
Opened 2017-08-01 19:54 UTC by stevenzheng3791

LEARNER-2102
https://openedx.atlassian.net/browse/LEARNER-2102

Refactored generate_courses command and associated tests.
Updated the course seat handling logic.

2017-08-01 21:27 UTC, bderusha requested changes

2017-08-01 21:27 UTC, bderusha commented on ecommerce/core/management/commands/generate_courses.py
> +                if "display_name" not in course["fields"]:
`if setting not in course["fields"]`

2017-08-03 19:34 UTC, bderusha approved these changes

2017-08-03 19:54 UTC, BenjiLee approved these changes

2017-08-07 18:16 UTC, merged