Add Site fk to ConditionalOffer model
openedx-unsupported/ecommerce pull request #1435
Opened 2017-08-04 22:25 UTC by bill-filler

This will make Program Offers multi-site aware by adding a foreign key
to the Sites table. Null values are accepted for this phase, and
django-admin has been modified to expose Site to manaully change the
data.

WL-1152

2017-08-10 13:39 UTC, clintonb requested changes
Tests?

2017-08-10 13:39 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +        'sites.Site', verbose_name=_("Site"), null=True, blank=True, default=None, on_delete=models.SET_NULL
Ditch the on_delete. If a site goes away, we don't want to keep a bunch of unassociatrd data.

2017-08-10 13:40 UTC, clintonb commented
Drop the merge bubble. Rebase on master instead of merging it into your branch.

2017-08-10 13:47 UTC, bill-filler commented on ecommerce/extensions/offer/models.py
> +        'sites.Site', verbose_name=_("Site"), null=True, blank=True, default=None, on_delete=models.SET_NULL
ok

2017-08-10 20:12 UTC, bill-filler commented
@clintonb addressed issues. tests written, removed on_delete and rebased my branch on master. Let me know if anything else.

2017-08-11 13:40 UTC, clintonb commented on ecommerce/extensions/offer/models.py
> +        'sites.Site', verbose_name=_("Site"), null=True, blank=True, default=None
nit: single quotes

2017-08-11 13:40 UTC, clintonb commented on ecommerce/extensions/offer/tests/test_admin.py
> +    def test_site_displayed(self):
This test isn't useful. Unless you actually check the HTML to determine if the site field is present, you're just testing the frameworks—Django and Oscar. This file can be removed.

2017-08-11 13:40 UTC, clintonb commented on ecommerce/programs/forms.py
> +        self.instance.site = site
This is really what I was looking for tests around. We need to ensure the form associates a `Site` with the offer. See https://github.com/edx/ecommerce/blob/master/ecommerce/programs/tests/test_forms.py. You should be able to get away with adding a line to `test_save_create` and `test_save_edit`.

2017-08-11 14:33 UTC, bill-filler commented on ecommerce/programs/forms.py
> +        self.instance.site = site
fixed. actually added the check to assert_program_offer_conditions as that gets called from both functions as well as test_save_offer_name

2017-08-11 15:03 UTC, clintonb approved these changes

2017-08-11 15:03 UTC, clintonb commented
Remember to update the [Hawthorn release notes](https://openedx.atlassian.net/wiki/display/COMM/Hawthorn).

2017-08-11 15:22 UTC, bill-filler commented
Hawthorn release notes updated

2017-08-11 15:25 UTC, merged