(WIP) LEARNER-1184 Disable enrollment code product revocation in refund process
openedx-unsupported/ecommerce pull request #1439
Opened 2017-08-08 10:49 UTC by Ayub-Khan

[Learner-1184](https://openedx.atlassian.net/browse/LEARNER-1184)

Description:
Refund revocataion process was breaking for enrollment codes because of no enrollment for user. Currently do not have proper rules for implementation so bypassing it. People were able to get multiple refunds for single orders. This pr will disable that functionality.

2017-08-08 12:35 UTC, Ayub-Khan commented
@mjfrey @clintonb  Thoughts?

2017-08-08 12:42 UTC, clintonb requested changes

2017-08-08 12:42 UTC, clintonb commented on ecommerce/extensions/fulfillment/api.py
> +            if not order_line.product.is_enrollment_code_product:
There should be no product-specific code here. Take a look at https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/fulfillment/modules.py#L482. There is no revocation function for enrollment codes.

The simpler solution is to update the code that creates refunds to never create refund lines for enrollment code lines.

2017-08-08 18:59 UTC, clintonb requested changes

2017-08-08 18:59 UTC, clintonb commented on ecommerce/extensions/refund/models.py
> +                if not line.product.is_enrollment_code_product:
Add a comment, and ticket number, explaining why we do not allow enrollment code products to be refunded.

2017-08-08 18:59 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +        coe order line
code

2017-08-08 18:59 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +        Test Refund.create_with_lines should not create RefundLines for enrollment
Nit: No need for the word "Test" here.

2017-08-08 18:59 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +            self.assert_refund_creation_logged(l, refund, order)
Checking logs is nice, but you really need to verify that no `RefundLine` is associated with `line`.

2017-08-08 18:59 UTC, clintonb commented on ecommerce/extensions/refund/tests/mixins.py
> +        toggle_switch(ENROLLMENT_CODE_SWITCH, True)
Move all of this to the test case that needs it. We don't need to do all of this work for every single test case.

2017-08-08 19:07 UTC, schenedx commented
@Ayub-Khan I agree this is the better approach than your first attempt.

2017-08-09 16:41 UTC, schenedx commented on ecommerce/extensions/refund/models.py
> +                if not line.product.is_enrollment_code_product:
Question: If a refund on the order is created without any refund lines, what happens? Is that a realistic case?

2017-08-09 16:54 UTC, clintonb commented on ecommerce/extensions/refund/models.py
> +                if not line.product.is_enrollment_code_product:
Good question. This check should be moved up to the declaration of `unrefunded_lines`. If that array is empty no `Refund` will be created.

2017-08-10 10:20 UTC, Ayub-Khan commented on ecommerce/extensions/refund/models.py
> +                if not line.product.is_enrollment_code_product:
I think if no refund is generated, we wont be even able to refund the money. we will totally disable the refund option for enrollment codes.

2017-08-10 12:03 UTC, clintonb commented on ecommerce/extensions/refund/models.py
> +                if not line.product.is_enrollment_code_product:
That's the point. No one should be buying enrollment codes with real money.

2017-08-10 12:06 UTC, mjfrey commented on ecommerce/extensions/refund/models.py
> +                if not line.product.is_enrollment_code_product:
Actually on WL sites, enrollment codes are purchased with money.  When a quantity greater than 1 for the seat is entered, enrollment codes are generated and sent to the purchaser.

2017-08-10 12:10 UTC, clintonb commented on ecommerce/extensions/refund/models.py
> +                if not line.product.is_enrollment_code_product:
Bah! Who said you could go on vacation! @Ayub-Khan please work with Product (Deen and Mike Martin) to determine the correct behavior. Once that is determined, please document that behavior in `/docs` and implement it.

2017-08-10 13:01 UTC, Ayub-Khan commented on ecommerce/extensions/refund/models.py
> +                if not line.product.is_enrollment_code_product:
@clintonb I will create a hipchat room including all the related people to find a resolution fast.

2017-08-10 19:07 UTC, schenedx commented
@Ayub-Khan Close this PR? Let the user story do this work.

2017-08-11 11:23 UTC, closed without merging