[WIP] BasketCalculateView supports username parameter.
openedx-unsupported/ecommerce pull request #1442
Opened 2017-08-08 14:12 UTC by Mjloturco

In order for basket calculate view to correctly return discounts to marketing site, and optional parameter of username is included in the BasketCalculateView instead of always relying on request.user.

2017-08-08 17:36 UTC, Mjloturco commented
@edx/helio Hey all, feel free to give this a look over

2017-08-08 20:10 UTC, clintonb requested changes
Follow the [commit message guidelines](https://openedx.atlassian.net/wiki/spaces/OpenDev/pages/161880915/Git+Best+Practices#GitBestPractices-CommitMessages).

2017-08-08 20:10 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +            raise api_exceptions.BadRequestException('User "{}" does not exist.'.format(username))
We generally use square brackets (e.g. `[username]`) rather than quotes.

2017-08-08 20:10 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +            user = User.objects.get(username=username) if username else request.user
What happens if I pass in the username of someone else? There should be permissions on this endpoint to avoid exposing details about one user to another.

2017-08-08 20:10 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +            user = User.objects.get(username=username) if username else request.user
Drop the `else` and add `user = request.user` above the `try` block.

2017-08-08 20:10 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +            #raise api_exceptions.BadRequestException('User "{}" does not exist.'.format(username))
Dead code should be removed.

2017-08-08 20:10 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +            user = request.user
Add a debug logging statement to aid local development but avoid spamming production logs.

2017-08-08 20:46 UTC, Mjloturco commented on ecommerce/extensions/api/v2/views/baskets.py
> +            user = User.objects.get(username=username) if username else request.user
Looping in @mjfrey on this, he'd mentioned that since only pricing info is being returned no user details are really exposed.

2017-08-08 21:04 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +            user = User.objects.get(username=username) if username else request.user
You are exposing the fact that a learner may, or may not, be enrolled in certain course runs. It may seem minor, but it's a potential breach of learner trust.

2017-08-09 07:28 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        self.assertEqual(response.status_code, 200)
How can you be sure that the response is not the same in these two tests? I suggest asserting that the response data is the one that you expect for a particular case.

2017-08-09 11:44 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/baskets.py
> +            user = User.objects.get(username=username) if username else request.user
I understand that a user could after some real digging determine that another user has already purchased a verified / professional seat based on a list of skus.  All this endpoint returns is price.  If we are really concerned with this, how would we ensure that only a privileged user or the actual learner can call this?

2017-08-09 12:09 UTC, clintonb commented on ecommerce/extensions/api/v2/views/baskets.py
> +            user = User.objects.get(username=username) if username else request.user
If `request.user` is a staff member, allow all calls. Otherwise, if `request.user.username` does not match the passed in username (remember to account for cAsE), return HTTP 403 (Forbidden) with an error message stating that users can only view their own data.

2017-08-11 18:49 UTC, closed without merging