[WIP] BasketCalculateView supports username parameter
openedx-unsupported/ecommerce pull request #1447
Opened 2017-08-11 18:50 UTC by Mjloturco

BasketCalculateView supports username parameter

In order to support Drupal site accessing user data the
BasketCalculateView must take a username as a parameter.
Additionally, protections are put in place to make sure
that unpriviledged users are not allowed to access other
user's data by passing in a different username.

LEARNER-1875

2017-08-14 15:30 UTC, mjfrey requested changes

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/baskets.py
> +                return HttpResponseForbidden('Users can only access their own pricing details')
I would change this error message to 
"Unauthorized user credentials"

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/baskets.py
> +        # If a username is passed in, validate that the user is priviledged or the same as username.
validate the user has staff access or is the same user.

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        unpriviledgeduser = self.create_user(is_staff=False)
non_staff_user

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        unpriviledgeduser = self.create_user(is_staff=False)
non_staff_user

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        """Verify that a priviledged user passing an invalid username gets a response but about themselves
Verify that a staff user

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        """Verify that a priviledged user passing a valid username gets a response about the other user"""
Verify a staff user

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +    def test_basket_calculate_by_priviledged_user_invalid_username(self, mocked_logger):
s/priviledged/staff

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        """Verify that an unpriviledged user passing their own username gets a valid response"""
s/unpriviledged/non-staff

2017-08-14 15:30 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +    def test_basket_calculate_by_unpriviledged_user_other_username(self):
s/unpriviledged/non_staff

2017-08-14 17:20 UTC, mjfrey requested changes

2017-08-14 17:20 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        for course in program['courses']:
Move this into a helper method, you are doing the same thing in more than 1 test.

2017-08-14 17:42 UTC, Mjloturco commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        for course in program['courses']:
Will do, should helper functions be moved into a mixin file somewhere else? or just left in the test file as _<helpername>

2017-08-14 17:55 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        for course in program['courses']:
If you think more tests would need it, mixin.  Otherwise just in the test itself.

2017-08-15 11:56 UTC, mjfrey approved these changes

2017-08-23 14:03 UTC, merged