McKenzieW/learner-1721
openedx-unsupported/ecommerce pull request #1448
Opened 2017-08-11 19:19 UTC by McKenzieW

Track programs or other bundles associated with a completed order

prepare_basket creates a 'bundle' basket attribute if the request includes a bundle, and this is tracked along with the basket's products in the 'Order Completed' analytic event

[LEARNER-1721]

2017-08-14 15:30 UTC, McKenzieW commented
@edx/helio please review

2017-08-14 15:48 UTC, clintonb requested changes
Grenade coming...you can't rely on baskets for reporting. Baskets aren't intended for longterm storage. If you want to store this info, it should be associated with an order since we will never delete orders.

2017-08-14 15:48 UTC, clintonb commented on ecommerce/extensions/basket/models.py
> +    bundle = models.CharField(
This table has 15,785,356 rows. Adding a field will lock the table, and break enrollments for the duration of the lock. We have a management command, `delete_ordered_baskets`, that should remove many of the baskets, but that might not remove enough of them.

2017-08-14 15:48 UTC, clintonb commented on ecommerce/extensions/basket/models.py
> +    bundle = models.CharField(
Actually...where is this field used?

2017-08-14 15:48 UTC, clintonb commented on ecommerce/sailthru/migrations/0002_add_basket_attribute_type.py
> +    BasketAttributeType.objects.create(name=BUNDLE)
This migration will not be run again in production. If you want this created, make a new migration. Even if this migration had not been run, you should avoid cross-pollinating app migrations in this manner. Your changes have nothing to do with Sailthru, thus your changes should not rely on Sailthru's migrations.

2017-08-14 15:54 UTC, McKenzieW commented on ecommerce/extensions/basket/models.py
> +    bundle = models.CharField(
Wow that was a dumb mistake on my part. This is from an old approach and I must've just forgotten to delete that code.

2017-08-14 18:31 UTC, clintonb commented
@McKenzieW this PR cannot be merged. See my note about baskets.

2017-08-14 18:35 UTC, mjfrey commented
Why can't the basket be used here for firing events?  There is no order when items are added to the basket.  Do we need persistence here or is it just fine to fire the event?  A basket would not be gone before the order complete event happens?

2017-08-14 18:38 UTC, clintonb commented
I see. I missed the fact that you are firing an event. As long as everyone understands that the basket may go away after the order is placed, all is well.

2017-08-14 18:39 UTC, McKenzieW commented
Yupp the reason we're associating the attribute with the basket as opposed to the offer is that we only need it for the event

2017-08-14 18:55 UTC, clintonb requested changes
Biggest cause of concern are the event properties. We shouldn't be putting non-products in the products array.

2017-08-14 18:55 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +        bundle_id = BasketAttribute.objects.get(basket=order.basket,
You don't need `BasketAttributeType` here:
```python
BasketAttribute.objects.get(basket=order.basket, attribute_type__name=BUNDLE).value_text
```

2017-08-14 18:55 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +BUNDLE = 'bundle_identifier'
Nit: separate your constants from the class names.

2017-08-14 18:55 UTC, clintonb commented on ecommerce/programs/migrations/0002_add_basket_attribute_type.py
> +    BasketAttributeType.objects.get(name=BUNDLE).delete()
Catch the `DoesNotExist` exception, and do nothing, just in case something goes awry.

2017-08-14 18:55 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +            # If the order is a bundle purchase, we should track the associated bundle in the properties
Nit: make this a separate test case.

2017-08-14 18:55 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +    def prepare_order(self, seat_type, credit_provider_id=None, bundle_id=None):
You're relying on the bundle in exactly one test case. Move this code to that test case.

2017-08-14 18:55 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +        properties['products'].append({'bundle': bundle_id})
Why is this nested under `'products'`? That array follows semantics set by Google and Segment. I fear adding a product that does not follow the semantics will cause issues.

2017-08-14 18:55 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +    if bundle_id:
It might be cleaner to always include the bundle ID, even if it is `null`.

2017-08-14 18:58 UTC, mjfrey commented on ecommerce/extensions/checkout/signals.py
> +        properties['products'].append({'bundle': bundle_id})
Peaking to Adley her suggested sending the UUID as a label

'label': uuid,

2017-08-14 19:08 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +        properties['products'].append({'bundle': bundle_id})
That is cleaner and shouldn't conflict with existing properties.

2017-08-14 19:17 UTC, McKenzieW commented on ecommerce/extensions/checkout/signals.py
> +        properties['products'].append({'bundle': bundle_id})
Do you know if it is possible to add another property to the event that is not listed in its spec? If not, would 'affiliation' be a better property to set the the program identifier?

2017-08-14 19:27 UTC, McKenzieW commented on ecommerce/extensions/checkout/signals.py
> +        bundle_id = BasketAttribute.objects.get(basket=order.basket,
but isn't it possible that the query would return the sailthru attribute otherwise?

2017-08-14 19:53 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +        bundle_id = BasketAttribute.objects.get(basket=order.basket,
If the Sailthru attributes have the name set to the value of `BUNDLE`, that's going to be returned regardless of implementation.

2017-08-14 20:01 UTC, McKenzieW commented on ecommerce/extensions/checkout/signals.py
> +        bundle_id = BasketAttribute.objects.get(basket=order.basket,
Oh sorry right, I didn't read carefully. I thought at first you were suggesting that I leave out the parameter entirely.

2017-08-14 20:27 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +            BasketAttribute.objects.get(basket=basket, attribute_type=BasketAttributeType.objects.get(name=BUNDLE))
`BasketAttribute.objects.get(basket=basket, attribute_type__name=BUNDLE)`

2017-08-14 20:27 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_utils.py
> +        bundle_id = BasketAttribute.objects.get(basket=basket,
`BasketAttribute.objects.get(basket=basket, attribute_type__name=BUNDLE)`

2017-08-18 14:47 UTC, mjfrey requested changes

2017-08-18 14:47 UTC, mjfrey commented on ecommerce/extensions/checkout/signals.py
> +def get_program_data(program_uuid, site_configuration):
I feel like we have this implemented somewhere else.  We should make this a utility and not repeat.

2017-08-18 14:47 UTC, mjfrey commented on ecommerce/extensions/checkout/tests/test_signals.py
> +    def test_get_program_data(self):
Same for this test.  I think we already have a test exactly like this.

2017-08-18 15:16 UTC, McKenzieW commented on ecommerce/extensions/checkout/signals.py
> +def get_program_data(program_uuid, site_configuration):
So there are two other methods:
https://github.com/edx/ecommerce/blob/master/ecommerce/programs/conditions.py#L29-L44
https://github.com/edx/ecommerce/blob/master/ecommerce/programs/views.py#L26-L38

that also essentially just call the api method:
https://github.com/edx/ecommerce/blob/master/ecommerce/programs/api.py


Do you want me to remove those methods as well?

2017-08-18 15:18 UTC, mjfrey commented on ecommerce/extensions/checkout/signals.py
> +def get_program_data(program_uuid, site_configuration):
Yes, I would consolidate all of those methods into one utility.

2017-08-18 16:40 UTC, mjfrey commented on ecommerce/extensions/checkout/utils.py
> +def get_program(program_uuid, siteconfiguration):
Good, but please move this to:
extensions/programs/utils.py

2017-08-18 18:56 UTC, McKenzieW commented
@mjfrey good to go?

2017-08-18 18:58 UTC, mjfrey approved these changes
looks good.  Please squash commits.

2017-08-18 19:19 UTC, merged