exception handling for get_program
openedx-unsupported/ecommerce pull request #1452
Opened 2017-08-21 13:21 UTC by McKenzieW

Update to Tracking Completed Program Purchase Orders to handle timeout, connection, not found, and slumber errors

[LEARNER-2226] (https://openedx.atlassian.net/browse/LEARNER-2226)

2017-08-21 17:26 UTC, McKenzieW commented
@edx/helio take a look

2017-08-21 17:33 UTC, staubina commented on ecommerce/programs/utils.py
>          dict
Update this to reflect that a None can be returned.  Also take a quick look at the user of this method to ensure that a return of None will not cause an issue.

2017-08-21 17:34 UTC, staubina commented on ecommerce/programs/utils.py
>          dict
Or return an empty Dictionary.

2017-08-21 17:34 UTC, mjfrey commented on ecommerce/programs/utils.py
> +    response = None
might be better:
response = []

2017-08-21 17:35 UTC, staubina commented on ecommerce/programs/tests/test_utils.py
> +    @mock.patch('ecommerce.programs.utils.log.warning')
Big :+1: for adding tests

2017-08-21 17:36 UTC, staubina commented on ecommerce/programs/utils.py
> +    response = None
@mjfrey I think you meant response = {}

2017-08-23 23:46 UTC, mjfrey requested changes

2017-08-23 23:46 UTC, mjfrey commented on ecommerce/programs/tests/mixins.py
> +    def mock_empty_program_detail_endpoint(self, program_uuid, siteconfiguration):
You could just add this to the already mock_program_data above by passing in a return_data kwarg.

2017-08-24 11:20 UTC, staubina commented on ecommerce/programs/conditions.py
> +                for course_run in course['course_runs']:
Our python code style guide ask us to have the parenthesis match vertically when using a new line.

http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python_guidelines.html#breaking-long-lines

```
program_course_run_skus.update(
    set([seat['sku'] for seat in course_run['seats'] if seat['type'] in applicable_seat_types])
)
```

2017-08-24 11:25 UTC, staubina commented on ecommerce/programs/tests/mixins.py
> +            uri='{base}/programs/{uuid}/'.format(base=siteconfiguration.discovery_api_url.strip('/'),
Consider moving 

```
'{base}/programs/{uuid}/'.format(base=siteconfiguration.discovery_api_url.strip('/'),
uuid=program_uuid)
```

out into a variable for clarity and code style guide requirements. 

Or

``` 
            method=httpretty.GET,
            uri='{base}/programs/{uuid}/'.format(
                  base=siteconfiguration.discovery_api_url.strip('/'),
                  uuid=program_uuid
            ),
            body=None,
```

2017-08-24 11:27 UTC, staubina requested changes
A few minor style updates to meet the Python Style Guide.

Also please wait to squash commits until we have finished reviewing if possible in the future.  It will make it easier to look at the updates between reviews.

2017-08-24 11:30 UTC, staubina commented on ecommerce/programs/tests/test_utils.py
> +                l.check((LOGGER_NAME, 'DEBUG',
Like my previous comments please update this line to match the style guide.

2017-08-24 14:04 UTC, mjfrey approved these changes

2017-08-24 14:10 UTC, McKenzieW commented
@staubina what do you think, good to go?

2017-08-24 14:17 UTC, staubina approved these changes

2017-08-24 14:17 UTC, staubina commented
:shipit:

2017-08-24 14:48 UTC, merged