Filter Program Offers to only show offers for the current site
openedx-unsupported/ecommerce pull request #1456
Opened 2017-08-22 15:16 UTC by bill-filler

Program Offers are now site-aware and the view is filtered to only show
offers for the current site. Site field also added to dashboard/offers
UI when creating/displaying offers from the dashboard.

WL-1152

2017-08-22 16:40 UTC, bill-filler commented
I think the codecov is failing because of the oscar templates (which are large html files) I had to include to add Site to the summary and details page:
https://github.com/edx/ecommerce/pull/1456/files#diff-bd70d183ff3ef2312b933085571eb273
https://github.com/edx/ecommerce/pull/1456/files#diff-89356728367e81c60819b61474c73c72
Not sure what to do about that.

2017-08-22 18:33 UTC, mjfrey commented
I would add a view test that submits a form so the new code that stores the site in the kwargs gets tested.

2017-08-22 19:43 UTC, clintonb requested changes
You need tests. Codecov doesn't look at HTML templates. You've added Python code that is not tested.

2017-08-22 19:43 UTC, clintonb commented on ecommerce/extensions/dashboard/offers/forms.py
> +    class Meta:  # pylint: disable=C1001
Don't disable this. Fix it: `class Meta(object)`.

2017-08-22 19:43 UTC, clintonb commented on ecommerce/programs/views.py
> +        site = self.request.site
Nit: Merge this with the line below. The `site` variable isn't necessary.

2017-08-22 19:43 UTC, clintonb commented on ecommerce/templates/oscar/dashboard/offers/offer_detail.html
> +{% extends 'dashboard/layout.html' %} {% load currency_filters %} {% load i18n %} {% block title %} {% blocktrans with name=offer.name %} {{ name }} | Offers {% endblocktrans %} | {{ block.super }} {
Break this up into multiple lines. Each `extends` and `load` call is on its own line. Each `block` is its own block.

2017-08-22 19:43 UTC, clintonb commented on ecommerce/templates/oscar/dashboard/offers/summary.html
> +</div>
Add a new line.

2017-08-22 19:43 UTC, clintonb commented on ecommerce/templates/oscar/dashboard/offers/offer_detail.html
> +{% include 'dashboard/partials/pagination.html' %} {% endif %} {% endblock dashboard_content %}
Add a new line.

2017-08-25 16:19 UTC, clintonb approved these changes
Remember to squash commits.

2017-08-26 12:28 UTC, merged