ignore for now
openedx-unsupported/ecommerce pull request #1457
Opened 2017-08-22 15:33 UTC by MatthewPiatetsky

Do not tell sailthru about bundles

2017-08-24 19:36 UTC, mjfrey commented
You can probably do something like this:
https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/checkout/signals.py#L37

2017-08-24 19:47 UTC, schenedx commented
@MatthewPiatetsky I agree with @mjfrey.
I think the assumption that multiple products in basket is always a bundle is too risky.
I have seen bundles sold with just 1 item. Or orders with multiple items in it that's not a bundle.

2017-08-24 19:53 UTC, schenedx requested changes
Let's use to Bundle ID to determine whether the basket is a bundled basket or not.

2017-08-24 19:55 UTC, MatthewPiatetsky commented
@schenedx what is an example of orders that are not a bundle but have multiple items?
I can check with product, but I think the requirement at the moment might just be that we wanted to do a single item email first and a multi item email later?
If the only multi item carts we have are bundles then using this bundle check makes sense, although if not, perhaps not

also @mjfrey you said this was using the wrong api?

2017-08-24 19:58 UTC, mjfrey commented
This is the API that gets called when purchasing bundles.
https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/basket/views.py#L95

2017-08-24 20:01 UTC, MatthewPiatetsky commented
@mjfrey I think the function you linked to eventually calls the code I modified.
BasketMultipleItemsView calls prepare_basket
https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/basket/views.py#L130
prepare_basket calls basket_addition
https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/basket/utils.py#L91

2017-08-24 20:12 UTC, schenedx commented
@MatthewPiatetsky Yes. I have an example. See 19858657

2017-08-28 19:58 UTC, MatthewPiatetsky commented
@schenedx @mjfrey if we have orders that are not bundles with multiple lines, i think the product requirement here would be to check the number of lines (not whether something is a bundle) because the emails would not be correct for the non-bundle multi line orders either

2017-08-29 12:53 UTC, schenedx requested changes
@MatthewPiatetsky If you are not specifically checking for bundles, and instead want to stop Sailthru basket update for all multi-product baskets, we should update the variables and comments accordingly to this requirement

2017-08-29 12:53 UTC, schenedx commented on ecommerce/extensions/api/v2/views/baskets.py
> +                is_bundle = True if len(requested_products) > 1 else False
I think calling this variable `is_bundle` is going to confuse others. 
What about calling this `is_multi_product_basket`?

2017-08-29 12:53 UTC, schenedx commented on ecommerce/sailthru/signals.py
> +    if is_bundle:
Why do we need 3 lines while just 2 lines can achieve the same?
```
if len(lines) > 1:
    return
```

2017-08-29 12:53 UTC, schenedx commented on ecommerce/sailthru/signals.py
> +        if price and not is_bundle:
Again, the variable name is not accurate in my opinion

2017-08-29 12:53 UTC, schenedx commented on ecommerce/sailthru/tests/test_signals.py
> +    def test_unsupported_bundles(self, mock_log_error, mock_update_course_enrollment):
I think a more accurate name for this test case is `test_stop_sailthru_update_on_multi_product_baskets`

2017-08-29 13:38 UTC, MatthewPiatetsky commented
@schenedx  did i address your comments?

2017-08-29 15:00 UTC, schenedx reviewed
See my inline comments

2017-08-29 15:00 UTC, schenedx commented on ecommerce/extensions/basket/utils.py
> +    is_bundle = True if len(products) > 1 else False
`is_multi_product_basket`

2017-08-29 15:00 UTC, schenedx commented on ecommerce/extensions/basket/utils.py
> +                                 basket=basket, is_bundle=is_bundle)
You'll want to update this variable as well to `is_multi_product_basket`

2017-08-29 15:00 UTC, schenedx commented on ecommerce/sailthru/signals.py
> +        return
Add some comments about multiple product basket case, and why we choose to skip sending to Sailthru

2017-08-29 15:00 UTC, schenedx commented on ecommerce/sailthru/tests/test_signals.py
> +        process_basket_addition(None, request=self.request, user=self.user, product=seat, is_bundle=True)
Should we update the variable here from `is_bundle` to `is_multi_product_basket`?

2017-08-29 16:05 UTC, mjfrey commented
It really seems to me that we are doing to much work to not send notifications to bundle purchase users.  Why do we not just teach sailthru about multi-line item basket/orders?

2017-08-29 19:02 UTC, MatthewPiatetsky commented
@mjfrey sounds like we decided to go ahead with this after talking
@schenedx further comments?

2017-08-29 19:11 UTC, schenedx approved these changes
👍

2017-08-29 19:34 UTC, merged