Mloturco/learner 2196
openedx-unsupported/ecommerce pull request #1460
Opened 2017-08-25 17:21 UTC by Mjloturco

2017-08-25 20:41 UTC, McKenzieW approved these changes

2017-08-28 11:32 UTC, mjfrey requested changes

2017-08-28 11:32 UTC, mjfrey commented on ecommerce/programs/tests/mixins.py
> +    def mock_program_detail_endpoint(self, program_uuid, discovery_api_url, empty=False, international_title=False):
Just add an optional title kwarg instead of a conditional.

2017-08-28 11:32 UTC, mjfrey commented on ecommerce/programs/tests/mixins.py
> +                'title': u'Sp\xe1nish Program' if international_title else 'Test Program',
Use the default or the custom title sent in as a param.

2017-08-28 11:32 UTC, mjfrey commented on ecommerce/programs/tests/test_forms.py
> +                                        expected_name='Discount for the Test Program MicroMockers Program'):
always send expected_name and remove the default value.

2017-08-28 11:32 UTC, mjfrey commented on ecommerce/programs/tests/test_forms.py
> +                                          international_title=True)
just call this kwarg program_title

2017-08-28 15:45 UTC, mjfrey approved these changes

2017-08-28 16:04 UTC, merged