[ENT-587] [WIP] More gracefully handle errors when hitting APIs
openedx-unsupported/ecommerce pull request #1468
Opened 2017-09-05 12:57 UTC by UmanShahzad

This PR is meant to handle errors more gracefully in the codebase -- specifically those places where `edx/edx-enterprise` requires it.

**JIRA tickets**: [ENT-587](https://openedx.atlassian.net/browse/ENT-587)

**Merge deadline**: By the end of the week.

**Testing instructions**:

It's hard to test this because you'd need to force an error somehow. In many cases you can force the errors through over-throttling. But other than that, the tests should build the confidence you need.

**Reviewers**
- [ ] @haikuginger 
- [ ] @douglashall @brittneyexline

2017-09-05 12:57 UTC, edx-webhook commented
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1468"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-09-06 10:11 UTC, UmanShahzad commented
I've covered the case that was written in the ticket, but there may be more places that the basket calculation logic takes us where API calls are being made without an outer try-catch block. I'll have to investigate more to be sure.

2017-09-06 13:09 UTC, UmanShahzad commented
@haikuginger @brittneyexline @douglashall I did more testing to see if there's any more weak spots that aren't handling errors gracefully, but I can't find them. I think at this point instead of investing more effort into trying to magically run into a new pain point, we can review / merge this change and continue to do something similar for more ungracefully-handled errors in the future as they pop up in logs.

2017-09-06 14:15 UTC, douglashall commented on ecommerce/programs/conditions.py
>              enrollments = []
Could we do this instead to simplify a bit:
```
enrollments = []
if basket.site.siteconfiguration.enable_partial_program:
    api_resource = 'enrollments'
    cache_key = get_cache_key(
        site_domain=basket.site.domain,
        resource=api_resource,
        username=basket.owner.username,
    )
    enrollments = cache.get(cache_key)
    if not enrollments:
        api = basket.site.siteconfiguration.enrollment_api_client
        user = basket.owner.username
        enrollments = api.enrollment.get(user=user)
        cache.set(cache_key, enrollments, settings.ENROLLMENT_API_CACHE_TIMEOUT)
        try:
            enrollments = api.enrollment.get(user=user)
        except (ConnectionError, SlumberBaseException, Timeout):
            logger.exception('Failed to retrieve enrollments from enrollment API:')
        else:
            cache.set(cache_key, enrollments, settings.ENROLLMENT_API_CACHE_TIMEOUT)
```

2017-09-06 14:29 UTC, UmanShahzad commented on ecommerce/programs/conditions.py
>              enrollments = []
That's much better, yep!

2017-09-06 14:41 UTC, douglashall approved these changes

2017-09-06 14:42 UTC, douglashall approved these changes

2017-09-06 14:42 UTC, douglashall commented
@UmanShahzad Reminder to rebase/squash before merging.

2017-09-06 14:43 UTC, UmanShahzad commented
@douglashall Will do :+1:

2017-09-06 15:05 UTC, haikuginger requested changes
One change request to the testing harness; I'm going to test this manually now.

2017-09-06 15:05 UTC, haikuginger commented on ecommerce/programs/tests/mixins.py
> +            body=json.dumps(enrollments) if enrollments else self.throw_exception,
I don't think this'll do what you want it to do. What you want to do is set the status code to an error code; HTTP requests to the given URL will then receive a response with that code, and Slumber (the HTTP client itself) will interpret that as an error and raise an exception.

I also think you probably want to do `if enrollments is None` rather than just checking for truthiness so that an empty list can be explicitly passed if desired.

2017-09-06 15:11 UTC, haikuginger commented on ecommerce/settings/base.py
> +        'user': '500/minute',
I'm unclear on how this is relevant to the other changes.

2017-09-06 15:11 UTC, UmanShahzad commented on ecommerce/settings/base.py
> +        'user': '500/minute',
Oh my, sorry this slipped through, that was for testing.

2017-09-06 15:13 UTC, UmanShahzad commented on ecommerce/programs/tests/mixins.py
> +            body=json.dumps(enrollments) if enrollments else self.throw_exception,
I think you're right, although I do thing it throws the error as I hoped because (apparently) I have test coverage? Either way, that's a way simpler solution that I just didn't know about.

2017-09-06 15:25 UTC, haikuginger requested changes

2017-09-06 15:25 UTC, haikuginger commented on ecommerce/programs/tests/mixins.py
> +    def mock_enrollment_api(self, username, enrollments=None):
Looks like we've got several tests throughout the testing suite that use the default parameter here, so now they're testing something else - instead of testing an explicitly returned empty set of enrollments, they're testing the exception behavior.

Can you modify this method to have an extra optional parameter `response_code` that accepts a numeric response code, defaulting to 200, and then add explicit tests of the error case? Something like this:

```python
def mock_enrollment_api(self, username, enrollments=None, response_code=200):
    enrollments = enrollments or []
    self.mock_access_token_response()
    httpretty.register_uri(
        method=httpretty.GET,
        uri='{}?user={}'.format(get_lms_enrollment_api_url(), username),
        body=json.dumps(enrollments),
        status=response_code,
    )
    return enrollments

2017-09-06 15:32 UTC, UmanShahzad commented on ecommerce/programs/conditions.py
> +                    enrollments = []
@douglashall Turns out I still had to have this, because it's being gotten from the cache above, which may give `None`, and then it gets used below as a list, causing errors.

2017-09-06 15:43 UTC, douglashall commented on ecommerce/programs/conditions.py
> +                    enrollments = []
You could do `cache.get(cache_key, [])`.

2017-09-06 15:45 UTC, UmanShahzad commented on ecommerce/programs/conditions.py
> +                    enrollments = []
/facepalm. Yeah, I need a rest. :P Thanks.

2017-09-06 16:48 UTC, UmanShahzad commented on ecommerce/programs/tests/mixins.py
> +            body=json.dumps([] if enrollments is None else enrollments),
I do this to avoid the pylint suppression above.

2017-09-06 16:49 UTC, UmanShahzad commented on ecommerce/programs/tests/test_conditions.py
> +from requests import ConnectionError, Timeout
Sorry, this is unused.

2017-09-06 16:49 UTC, UmanShahzad commented
@haikuginger Ok, attempted to apply the test suggestion.

2017-09-07 15:34 UTC, douglashall commented
@haikuginger Is this ready for merge now?

2017-09-07 16:05 UTC, haikuginger approved these changes
:+1:

- [x] I tested this: Verified the cleaner behavior when receiving an error code from the enrollment API
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ N/A
- [x] Includes documentation

2017-09-07 17:04 UTC, UmanShahzad commented
@douglashall Am I good to squash, rebase, and merge? Do we need any other reviews for ecommerce PRs?

2017-09-07 17:37 UTC, douglashall commented
@UmanShahzad I think you are good to merge once tests pass. Thanks.

2017-09-08 05:57 UTC, merged

2017-09-12 12:32 UTC, clintonb commented on ecommerce/programs/conditions.py
> +                    cache.set(cache_key, enrollments, settings.ENROLLMENT_API_CACHE_TIMEOUT)
You're potentially caching invalid data for an hour. This is not good.

2017-09-12 12:35 UTC, UmanShahzad commented on ecommerce/programs/conditions.py
> +                    cache.set(cache_key, enrollments, settings.ENROLLMENT_API_CACHE_TIMEOUT)
Sorry -- we can change this to skip the caching step if it's invalid.