Call isort on codebase
openedx-unsupported/ecommerce pull request #1469
Opened 2017-09-05 13:03 UTC by UmanShahzad

We seem to do an isort check on the codebase as part of quality, but there are files that haven't actually been sorted.

This just calls it in a separate PR to make the diff easier to read.

P.S. This also adds an `isort` make target for future ease.

2017-09-05 13:03 UTC, edx-webhook commented
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1469"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-09-06 10:12 UTC, UmanShahzad commented
@clintonb This is not a significant change -- can you give a :+1: if it looks fine?

2017-09-06 11:47 UTC, clintonb requested changes
The make target is not necessary. I am generally in favor of better documentation rather than more make targets to obfuscate the commands. 

Update your commit message better describe what actually occurred: Ran isort on entire codebase

2017-09-06 11:47 UTC, clintonb commented on Makefile
> +isort:
The quality target already exists. Remove this

2017-09-06 11:49 UTC, UmanShahzad commented on Makefile
> +isort:
The quality target applies `--check-only`. This doesn't. It's a fast way to run isort on the entire codebase, instead of having to type out everything.

2017-09-06 12:17 UTC, clintonb commented on Makefile
> +isort:
I understand. Again, documentation over convenience. This is not an issue for other repos. The only reason you found isort issues here is due to the manner in which the tests are run.

2017-09-06 12:24 UTC, clintonb commented on Makefile
> +isort:
Correction: I fixed the issues with test runs a while ago. All of the changes you've made are purely cosmetic; `isort` isn't failing.

I stand by my statement that devs should understand exactly what they are running rather than rely on Make targets for everything. I'll approve the cosmetic changes. I have yet to hear a convincing argument to add another Make target.

2017-09-06 12:30 UTC, UmanShahzad commented on Makefile
> +isort:
As part of #1468, I added/removed some imports and I knew that caused `isort` to fail in one of the test runs. I then called `isort --recursive e2e ecommerce` assuming it'd solve my problem, but it instead generated this much larger changeset. So I figured it'd be good to not slow developers down by `isort` issues by allowing a convenience command to solve it automatically.

I'm OK with removing this as a make target, but we should consider a weekly/monthly bot that runs `isort` on the codebase. It's not important, but it allows individual developers to fix their PR-local `isort` quality issues without much effort. Just a recommendation.

2017-09-06 12:34 UTC, UmanShahzad commented
@clintonb The make target is removed & commits squashed to your recommended commit message.

2017-09-06 12:35 UTC, clintonb approved these changes

2017-09-06 13:26 UTC, merged