Pre Django 1.11 updates
openedx-unsupported/ecommerce pull request #1470
Opened 2017-09-06 11:43 UTC by ahsan-ul-haq

This includes the work involve in upgrading the libraries to support django 1.11
[LEARNER-1306](https://openedx.atlassian.net/browse/LEARNER-1306)

2017-09-06 12:27 UTC, clintonb commented on requirements/base.txt
>  django-rest-swagger[reST]==0.3.10
This needs to be updated. Breaking Swagger for edx/course-discovery affected some users. Let's make sure we don't repeat that .

2017-09-15 14:49 UTC, schenedx approved these changes
👍  LGTM
After you merge, could you do some manual testing on stage?
Remember to squash your commits!

2017-09-18 12:28 UTC, ahsan-ul-haq commented
@clintonb please review

2017-09-18 13:14 UTC, clintonb requested changes
You've changed some of the functionality that should have been changed. Also, some of your migrations may touch large tables and result in downtime. Please work with @edx/devops to test the effects of these migrations.

For the sake of time and simplicity, it may be better to split this PR into two parts:

1. Upgrade everything except Oscar
2. Upgrade Oscar

2017-09-18 13:14 UTC, clintonb commented on requirements/test.txt
> +django-webtest==1.9.2
What is this, and why is it necessary?

2017-09-18 13:14 UTC, clintonb commented on ecommerce/settings/base.py
> -# END MIDDLEWARE CONFIGURATION
Restore this.

2017-09-18 13:14 UTC, clintonb commented on ecommerce/settings/base.py
> +# END MIDDLEWARE CONFIGURATION
Remove this.

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/order/migrations/0016_auto_20170907_1306.py
> +            model_name='historicalorder',
How big is this table?

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/basket/views.py
> -            messages.warning(
Why was this removed?

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        with self.assertRaises(ValidationError):
Revert. The desired functionality is to display an error message, not raise an exception message that is not helpful to the user.

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        expected = "No voucher found with id '{}'".format(pk)
Revert. This is probably an issue with translations.

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        voucher, product = prepare_voucher(code=COUPON_CODE, benefit_value=10)
Why was this changed?

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/api/tests/test_views.py
> +    def setUp(self):
Ditch the `setUp` method. There is nothing special about any of the variables you're making here. Make them in the test cases. We tend to do too much in `setUp`, making tests difficult to debug later.

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/api/tests/test_views.py
> +        user = UserFactory()
This doesn't need to be a separate variable.

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/api/tests/test_views.py
> +        """ Verify the view raises `PermissionDenied` if the request is authenticated. """
Permission denied errors should be raised if the user lacks the appropriate permissions, not if the user is authenticated. This docstring is more confusing than helpful. Please update it to reflect what is actually going on.

2017-09-18 13:14 UTC, clintonb commented on ecommerce/extensions/api/views.py
> +        generator = SchemaGenerator(title='Discovery API')
This is E-Commerce.

2017-09-18 14:20 UTC, ahsan-ul-haq commented on ecommerce/extensions/basket/tests/test_views.py
> +        voucher, product = prepare_voucher(code=COUPON_CODE, benefit_value=10)
Because having this value as 0 will cause validation error in Oscar 1.5

2017-09-18 14:22 UTC, ahsan-ul-haq commented on ecommerce/extensions/basket/views.py
> -            messages.warning(
this is now being handled in the oscar that will generate validation error. If we want to have this I can override that behavior to not raise the error.

2017-09-18 14:24 UTC, ahsan-ul-haq commented on ecommerce/extensions/order/migrations/0016_auto_20170907_1306.py
> +            model_name='historicalorder',
Are you refering to number of record in this table?

2017-09-18 14:25 UTC, clintonb commented on ecommerce/extensions/order/migrations/0016_auto_20170907_1306.py
> +            model_name='historicalorder',
Yes.

2017-09-18 14:25 UTC, ahsan-ul-haq commented on requirements/test.txt
> +django-webtest==1.9.2
Its a required package for testing in Oscar 1.5

2018-02-02 09:43 UTC, closed without merging