Added loggings to track Missing Orders
openedx-unsupported/ecommerce pull request #1471
Opened 2017-09-08 11:28 UTC by Ayub-Khan

**[LEARNER-2456](https://openedx.atlassian.net/browse/LEARNER-2456)**

Added loggings so that if there is missing order issue we can track it using the splunk alerts.

2017-09-08 11:31 UTC, mjfrey commented on ecommerce/extensions/payment/views/cybersource.py
> +                order = Order.objects.get(number=order_number)
This will throw an exception if no order exists.

2017-09-08 13:54 UTC, schenedx requested changes
You would also need to exclude the case where there already exists of a paymentprocessorresponse row with a valid transaction_id

2017-09-08 13:54 UTC, schenedx commented on ecommerce/extensions/payment/views/cybersource.py
> +                    Order.objects.get(number=order_number)
@Ayub-Khan Why not do
`if Order.objects.filter(number=order_number).exists():`? This way, you don't need to do try catch

2017-09-11 16:53 UTC, schenedx requested changes
Question on the logic

2017-09-11 16:53 UTC, schenedx commented on ecommerce/extensions/payment/views/cybersource.py
> +                if Order.objects.filter(number=order_number).exists() and \
Should be `or` in the if condition?

2017-09-11 16:53 UTC, schenedx commented on ecommerce/extensions/payment/views/cybersource.py
> +                        'Received CyberSource payment notification for basket [%d] which is not associated '
`Received duplicate Cybersource payment notification for basket...`

2017-09-11 17:13 UTC, schenedx approved these changes
👍

2017-09-11 17:13 UTC, schenedx commented on ecommerce/extensions/payment/views/cybersource.py
> +                        ).exclude(transaction_id__isnull=True).exclude(transaction_id=""):
#Nitpick please use single quote to keep the file consistent.

2017-09-11 17:13 UTC, schenedx commented on ecommerce/extensions/payment/views/cybersource.py
> +                        'Received CyberSource payment notification for basket [%d] which is associated '
This log message is no longer accurate with the `OR` condition above. Can you update the message?

2017-09-11 17:35 UTC, schenedx commented on ecommerce/extensions/payment/views/cybersource.py
> +                        'Received CyberSource payment notification for basket [%d] which is associated '
`Received CyberSource duplicate payment notification for basket....or had an existing valid payment notification.`

2017-09-11 18:45 UTC, mjfrey approved these changes

2017-09-15 10:38 UTC, ahsan-ul-haq approved these changes
:+1:

2017-09-15 10:39 UTC, merged