ignore for now
openedx-unsupported/ecommerce pull request #1477
Opened 2017-09-15 15:00 UTC by MatthewPiatetsky

Make address, suite, state and zip optional

2017-09-18 19:31 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/forms.py
> -            try:
this is the same below just inside the if statement

2017-09-18 22:25 UTC, mikedikan reviewed
Just a cup'l questions

2017-09-18 22:25 UTC, mikedikan commented on ecommerce/extensions/payment/forms.py
> +            # I could require it client side, but am not because it is not currently marked as required for the user
Do I understand this to mean that we don't CURRENTLY have code to validate zip client-side?

2017-09-18 22:25 UTC, mikedikan commented on ecommerce/extensions/payment/views/cybersource.py
> +            line1=cybersource_response.get('req_bill_to_address_line1', ''),
Worth leaving a comment here about the test?

2017-09-19 12:45 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/forms.py
> +            # I could require it client side, but am not because it is not currently marked as required for the user
correct

2017-09-19 12:53 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/views/cybersource.py
> +            line1=cybersource_response.get('req_bill_to_address_line1', ''),
added comment

2017-09-19 16:38 UTC, mjfrey requested changes

2017-09-19 16:38 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
Rather than commenting this out, can we add a siteconfig option like "enable minimal payment fields: bool"?  This way we can turn it on / off for all the different sites. 

Once we feel it is good globally we can remove the siteconfig flag.

2017-09-19 16:40 UTC, mikedikan commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
I think this makes sense once this goes to implementation, but right now it's just an A/B test and is more likely to be reverted completely than anything else.  @mjfrey  Can we save this feedback for when we have a successful A/B test and are moving towards productizing?

2017-09-19 16:48 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
But doing it this way will force the test and behavior on all sites including the WL ones.  This could be an issue.

2017-09-19 17:07 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
i don't mind adding siteconfig flag but wondering if that's the best fix here.
optimizely test won't trigger on white label sites so if we wanted to preserve identical behavior from a user perspective we could add zip code to the list of required fields client side, and all the current required fields would remain required and behave the same.

If the actual reason we wanted to add a flag is because we were concerned about this change breaking something, i'm wondering if a feature flag makes more sense.
in both cases we'd have to several additional tests to pass codecov, but then we would not need to write a migration to add the field, remove the field, and squash migrations

2017-09-19 17:09 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
Only issue with a feature flag, it is global.  A siteconfig flag is per site.

2017-09-19 17:16 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
but what case wouldn't be covered by globally identical client-side behavior and a global feature flag?

2017-09-19 17:20 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
I guess I do not understand the proposal.  I am suggesting that we support the current behavior on some sites and the test on others.  Can the be done with a feature flag being global?

2017-09-19 17:29 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
my proposal would be to keep all the fields required client side on all sites other than edx.org to preserve their current behavior.
If we were concerned that someone would commit something breaking the client side code during the test, we could use a feature flag as a fallback safety measure to turn off the test changes until we can fix the bug.
then all the code would be reverted after the test is over

2017-09-19 17:30 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
so you would modify the client side JS?  Isn't adding a siteconfig flag easier?  I did not mean for this to be a big deal, just that is needs to be configurable per site.

2017-09-19 17:49 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
this pr already modifies the client side js to preserve current behavior unless a flag an optimizely flag is triggered, which would only happen on edx.org
the one exception is that unlike the other fields which are required both client side and server side, zip code is only required server side.
so as part of my proposal, also requiring it client side would mean that users would mean that users won't be able to submit without any of the fields now optional server side
i think this would work unless white label sites use different javascript, in which case a siteconfiguration would be necessary
do white label sites use different javascript client side?

2017-09-19 17:50 UTC, mjfrey commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
okay I understand.  I am not sure about WL sites modifying the JS.  I do not think they do but you should check the themes to see.

2017-09-19 20:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/forms.py
> +            # Temporarily comment out below code that requires state while running this test
i looked through themes and some of the actual sites, and the payment pages look the same to me. i've gone ahead and ensured that all fields including zip continue to be required client side. just in case, the server side changes are now also controlled by a waffle switch

2017-09-20 13:21 UTC, mjfrey approved these changes

2017-09-20 16:42 UTC, merged