[WIP] history cleanup command
openedx-unsupported/ecommerce pull request #1496
Opened 2017-10-02 15:05 UTC by ahsan-ul-haq

LEARNER-2697

2017-10-02 15:47 UTC, clintonb requested changes
This is unnecessarily complicated. Zero dollar orders. Fiscal year. None of that really matters. See https://gist.github.com/clintonb/9c13b56da1368186bc65edebced709c4 for a simplified version. Feel free to use it as a base. It needs to be updated to support setting the date via command line, and batching deletes.

2017-10-03 13:19 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                            default=None,
Ditch the default so that you guarantee a value is always supplied.

2017-10-03 13:19 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                cutoff_date.split("-")
Use [`dateutil.parser.parse`](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parse).

2017-10-03 13:19 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                except Exception:  # pylint: disable=broad-except
Why is this necessary? What is the specific exception that errors?

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +from dateutil.parser import parse
This is a third-party library. Group it accordingly. Run `make quality` before committing to avoid these issues.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +        if not cutoff_date:
This should never be hit given that the input is required.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +        cutoff_date = options.get('cutoff_date')
Use `[]` for both of these instead of `get()`. There will always be values for both keys.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                logger.error('Invalid date provided in cutoff date.')
`logger.exception('Failed to parse cutoff date.')`

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/tests/test_clean_history.py
> +        """Create history data for all history models."""
If your methods have descriptive names and concise bodies, you don’t need doc strings. You don’t need docstrings for any of these methods.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +        if not cutoff_date:
Make the field required. https://docs.python.org/3/library/argparse.html#required

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/tests/test_clean_history.py
> +    def test_invavlid_cutoff_date(self):
You misspelled invalid.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/tests/test_clean_history.py
> +    def create_history_record(self, batch_size=3):
`create_history_records`. You’re making more than one.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +"""Clean the history data for one or all historical tables."""
Get rid of this docstring. It offers no additional value over the commands help text.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/tests/test_clean_history.py
> +    models = (Order, OrderLine, Refund, RefundLine, ProductAttributeValue, Product, StockRecord, Course,)
This is only used in one method. There is no need for it to be a class variable. Move it to the method.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/tests/test_clean_history.py
> +        call_command('clean_history', cutoff_date=cutoff_date.strftime('%Y-%m-%d'), batch_limit=2)
1. Set the batch size to 1 to keep the math simple.
2. You need to verify the number of DB calls, ideally in a non-flaky manner. 
3. Add a test case verifying that no data is deleted if the cutoff date is before the creation date of the data.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +        parser.add_argument('--batch_limit',
Nit: we’ve always called this batch size, not limit.

2017-10-04 13:17 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                            help='Limit of the batch data to be removed at one time.')
Maximum number of database rows to delete per query. This helps avoid locking the database when deleting large amounts of data.

2017-10-04 13:44 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +            return
Use [CommandError](https://docs.djangoproject.com/en/1.11/howto/custom-management-commands/#django.core.management.CommandError) to indicate an issue.

```python
msg = 'Failed to parse cutoff date: {}'.format(cutoff_date)
logger.exception(msg)
raise CommandError(msg)
```

2017-10-05 12:54 UTC, ahsan-ul-haq commented
@clintonb can you please review this

2017-10-05 13:04 UTC, clintonb requested changes

2017-10-05 13:04 UTC, clintonb commented on ecommerce/core/tests/test_clean_history.py
> +        """Test error on invalid date."""
Again, these docstrings add no value. Get rid of them.

2017-10-05 13:04 UTC, clintonb commented on ecommerce/core/tests/test_clean_history.py
> +        call_command('clean_history', '--cutoff_date={}'.format(cutoff_date.strftime('%Y-%m-%d')), batch_limit=2)
Test the query count. You’ll see that the kwarg is misnamed and you are deleting all of the data in a single query.

2017-10-05 13:41 UTC, ahsan-ul-haq commented
@clintonb add query count. Here is the list of queries being executed 
```
SELECT COUNT(*) AS "__count" FROM "order_historicalorder" WHERE "order_historicalorder"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "order_historicalorder" WHERE "order_historicalorder"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SAVEPOINT "s140145555691264_x94"
SELECT "order_historicalorder"."id" FROM "order_historicalorder" WHERE "order_historicalorder"."history_date" <= '2017-10-06 04:00:00' ORDER BY "order_historicalorder"."history_date" DESC, "order_historicalorder"."history_id" DESC LIMIT 2
DELETE FROM "order_historicalorder" WHERE "order_historicalorder"."history_id" IN (4, 5)
RELEASE SAVEPOINT "s140145555691264_x94"
SELECT (1) AS "a" FROM "order_historicalorder" WHERE "order_historicalorder"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SAVEPOINT "s140145555691264_x95"
SELECT "order_historicalorder"."id" FROM "order_historicalorder" WHERE "order_historicalorder"."history_date" <= '2017-10-06 04:00:00' ORDER BY "order_historicalorder"."history_date" DESC, "order_historicalorder"."history_id" DESC LIMIT 2
DELETE FROM "order_historicalorder" WHERE "order_historicalorder"."history_id" IN (2, 3)
RELEASE SAVEPOINT "s140145555691264_x95"
SELECT (1) AS "a" FROM "order_historicalorder" WHERE "order_historicalorder"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SAVEPOINT "s140145555691264_x96"
SELECT "order_historicalorder"."id" FROM "order_historicalorder" WHERE "order_historicalorder"."history_date" <= '2017-10-06 04:00:00' ORDER BY "order_historicalorder"."history_date" DESC, "order_historicalorder"."history_id" DESC LIMIT 2
DELETE FROM "order_historicalorder" WHERE "order_historicalorder"."history_id" IN (1)
RELEASE SAVEPOINT "s140145555691264_x96"
SELECT (1) AS "a" FROM "order_historicalorder" WHERE "order_historicalorder"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SELECT COUNT(*) AS "__count" FROM "order_historicalline" WHERE "order_historicalline"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "order_historicalline" WHERE "order_historicalline"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SELECT COUNT(*) AS "__count" FROM "refund_historicalrefund" WHERE "refund_historicalrefund"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "refund_historicalrefund" WHERE "refund_historicalrefund"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SELECT COUNT(*) AS "__count" FROM "refund_historicalrefundline" WHERE "refund_historicalrefundline"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "refund_historicalrefundline" WHERE "refund_historicalrefundline"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SELECT COUNT(*) AS "__count" FROM "catalogue_historicalproductattributevalue" WHERE "catalogue_historicalproductattributevalue"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "catalogue_historicalproductattributevalue" WHERE "catalogue_historicalproductattributevalue"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SELECT COUNT(*) AS "__count" FROM "catalogue_historicalproduct" WHERE "catalogue_historicalproduct"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "catalogue_historicalproduct" WHERE "catalogue_historicalproduct"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SELECT COUNT(*) AS "__count" FROM "partner_historicalstockrecord" WHERE "partner_historicalstockrecord"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "partner_historicalstockrecord" WHERE "partner_historicalstockrecord"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SELECT COUNT(*) AS "__count" FROM "courses_historicalcourse" WHERE "courses_historicalcourse"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "courses_historicalcourse" WHERE "courses_historicalcourse"."history_date" <= '2017-10-06 04:00:00' LIMIT 1
SELECT COUNT(*) AS "__count" FROM "invoice_historicalinvoice" WHERE "invoice_historicalinvoice"."history_date" <= '2017-10-06 04:00:00'
SELECT (1) AS "a" FROM "invoice_historicalinvoice" WHERE "invoice_historicalinvoice"."history_date" <= '2017-10-06 04:00:00' LIMIT 1

```

2017-10-05 15:51 UTC, clintonb commented on ecommerce/core/management/commands/tests/test_clean_history.py
> +        QuerySet.delete = counter(QuerySet.delete)
I added this so that we can track the explicit calls to `QuerySet.delete()`. I find that `assertNumQueries` leads to either flaky tests or making tedious changes in the future (e.g. incrementing the count). This change limits the likelihood of those events occurring because it is rare that we call `QuerySet.delete()` so the likelihood of it being invoked outside of the management command is also rare.

2017-10-05 15:51 UTC, clintonb commented on ecommerce/core/management/commands/tests/test_clean_history.py
> +import datetime
I have moved this test to the appropriate subdirectory.

2017-10-05 15:51 UTC, clintonb approved these changes

2017-10-06 11:56 UTC, merged