[WIP] jbradley/learner 2413 Add Geolocation-Based Local Currency To Basket
openedx-unsupported/ecommerce pull request #1498
Opened 2017-10-04 13:17 UTC by jaebradley

## Purpose

[JIRA](https://openedx.atlassian.net/browse/LEARNER-2413)

Translate basket prices into local currency. Local currency is defined by information stored in the `edx-price-l10n` cookie, which should be set beforehand.

cc: @MatthewPiatetsky @AlasdairSwan @mikedikan 

## Example

### Before
![image](https://user-images.githubusercontent.com/8136030/31177374-d7841a0a-a8e3-11e7-954c-d392a3a0d3c1.png)

### After
![image](https://user-images.githubusercontent.com/8136030/31177422-f8f9bb5e-a8e3-11e7-86a9-48f7bfd21457.png)

## To Do
- [ ] Check about warning text on conversion accuracy
- [ ] Squash commits

2017-10-04 13:32 UTC, MatthewPiatetsky commented
good to dos, also we put the ticket number on the third line of the squashed commit message
you can create a coupon here http://localhost:18130/coupons/new/ and apply that

2017-10-04 13:34 UTC, AlasdairSwan requested changes

2017-10-04 13:34 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                return '$' + priceInUSD;
It may be cleaner to just set countryData.symbol to '$' and countryData.rate = 1 so the formatting of the number is consistent.

2017-10-04 13:34 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                        rawPriceValue.length
You don't need to include this, if omitted it defaults to the length of the string.

2017-10-04 13:34 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                $(this).text(calculateLocalizedPrice(priceInUSD));
I think it would be worth doing a check to ensure the new value is different than the current value before updating the DOM.

2017-10-04 20:59 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                var priceText = $(this).text();
This is repeated code from above - I can move to it's own function if necessary.

2017-10-04 21:02 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                    .toLocaleString(undefined, {maximumFractionDigits: 0});
This is slightly different than the implementation [here](https://github.com/edx/edx-mktg/pull/1612/files#diff-873ba66872fcc5d2e711a09db7daddc2R194) and provides additional numerical formatting (`1000` => `1,000` - you can see the Yen screenshot in the PR description for a live example).

2017-10-04 21:03 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                $('<span>').attr('class', 'price-disclaimer')
There's got to be a better way to do this...open to suggestions!

2017-10-04 21:12 UTC, MatthewPiatetsky commented
We might want to wrap this (and the platform work) in a feature gate
we can decide during standup tomorrow

2017-10-04 21:13 UTC, MatthewPiatetsky reviewed
We might want to wrap this (and the platform work) in a feature gate
we can decide during standup tomorrow

left some comments

2017-10-04 21:13 UTC, MatthewPiatetsky commented on ecommerce/static/js/pages/basket_page.js
> +            var countryData = Cookies.getJSON('edx-price-l10n');
define all var variables on first line like this

```
var x=1,
    y=2;
```

2017-10-04 21:13 UTC, MatthewPiatetsky commented on ecommerce/static/js/pages/basket_page.js
> +                return '$' + priceInUsd;
we can double check if we need USD after, if we don't want to change the current behavior, perhaps we can just do nothing in that case?

2017-10-04 21:13 UTC, MatthewPiatetsky commented on ecommerce/static/js/pages/basket_page.js
> +                currencyValue = Math.round(priceInUsd * countryData.rate)
maybe lets do ceiling here?

2017-10-04 21:13 UTC, MatthewPiatetsky commented on ecommerce/static/js/pages/basket_page.js
> +            var price = $('#basket-total').find('> .price').text();
what is the > in the selector?

2017-10-04 21:13 UTC, MatthewPiatetsky commented on ecommerce/static/js/pages/basket_page.js
> +                    .appendTo('div[aria-labelledby="order-details-region"]');
defer to @AlasdairSwan on whether this is accessible

2017-10-04 21:13 UTC, MatthewPiatetsky commented on package-lock.json
> +{
i think you didn't mean to commit this file?

2017-10-04 21:13 UTC, MatthewPiatetsky commented on ecommerce/static/js/pages/basket_page.js
> +            usdPriceText.match(/\$[0-9]+\.[0-9]+/g).forEach(function(value) {
perhaps add a comment showing what this regex does with input/output?

2017-10-05 20:30 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +        var BasketPage = {};
The reason I'm creating (and returning) this object is because the current structure is not conducive to tests (particularly spies).

## Example Time

Consider this `foobar.js`

```javascript
// foobar.js

define([],
    function() {
        'use strict';

        function bar() {
            console.log('bar has been called');
        }

        function foo() {
            console.log('foo has been called');
            bar();
        }

        return {
            foo: foo,
            bar: bar
        };
    }
);
```

The previous implementation of `foobar.js` fails this spec

```javascript
// foobar_spec.js

define([
    'pages/foobar'
],
    function(Foobar) {
        'use strict';

        describe('Testing foo', function() {
            it('should call bar', function() {
                console.log(Foobar);
                spyOn(Foobar, 'bar');
                Foobar.foo();
                expect(Foobar.bar).toHaveBeenCalled();
            });
        });
    }
);
```

while this `foobar.js` passes

```javascript
define([],
    function() {
        'use strict';

        var obj = {};

        obj.bar = function() {
            console.log('bar has been called');
        };

        obj.foo = function() {
            console.log('foo has been called');
            obj.bar();
        };

        return obj;
    }
);
```

The first `foobar.js` fails (I think) because the `Foobar.bar` property (which Jasmine puts a spy on) is different than the `bar` method that the method `foo` (which `Foobar.foo` has a reference to) calls. Thus, while the method `bar` is called by `Foobar.foo`, the property `Foobar.bar` is never called, and thus, `expect(Foobar.bar).toHaveBeenCalled()` will fail.

The second `foobar.js` succeeds for the same reason that the first `foobar.js` fails.

The implication is that in order to write sane Jasmine tests for `BasketPage` the returned object needs to follow the pattern established in the second `foobar.js` instead of the current pattern, which is identical to the first `foobar.js`.

2017-10-05 20:46 UTC, jaebradley commented on package-lock.json
> +{
From [the `package-lock.json` documentation](https://docs.npmjs.com/files/package-lock.json)
> This file is intended to be committed into source repositories

I've deleted it for now and added `package-lock.json` to the `.gitignore`.

2017-10-05 20:49 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +            var price = $('#basket-total').find('> .price').text();
A [child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_selectors)!
> It matches only those elements matched by the second selector that are the children of elements matched by the first.

I initially had
![image](https://user-images.githubusercontent.com/8136030/31251737-07365be6-a9ed-11e7-87f7-c6c287ac8b12.png)

2017-10-05 20:49 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                    .appendTo('div[aria-labelledby="order-details-region"]');
I tested the updated Basket Page using `axe` and I didn't see any warnings over the added `span`.

2017-10-05 20:51 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                currencyValue = Math.round(priceInUsd * countryData.rate)
I was just copying from [here](https://github.com/edx/edx-mktg/pull/1612/files#diff-873ba66872fcc5d2e711a09db7daddc2R200)

![image](https://user-images.githubusercontent.com/8136030/31251891-6ff5439a-a9ed-11e7-950f-18b4b430cba5.png)

2017-10-05 20:52 UTC, MatthewPiatetsky commented on ecommerce/static/js/pages/basket_page.js
> +                currencyValue = Math.round(priceInUsd * countryData.rate)
ok i guess i'll just my code to round :(

2017-10-05 20:56 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                return '$' + priceInUsd;
I see what you mean.

I do like the modularity of this method and how it encapsulates the implementation details around the `edx-price-l10n` cookie.

I did include [checks](https://github.com/edx/ecommerce/pull/1498/files#diff-a77e90eb28521ce0645b1b9831b34192R277) that don't update the DOM element if the text value is the same as the formatted local price value.

2017-10-05 21:08 UTC, MatthewPiatetsky approved these changes
once Alasdair approves and you've tested locally that you can still successfully checkout, good from my end.
this can also be released before the platform work, since no user should currently have the cookie (so this should do nothing when it is released)

2017-10-06 15:25 UTC, jaebradley commented
@AlasdairSwan mind taking another look? Thanks!

2017-10-06 15:53 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +        var BasketPage = {};
Why not just do this;
```
var BasketPage = {
    onFail: function() {....}
};
```

2017-10-06 16:06 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                    .appendTo('div[aria-labelledby="order-details-region"]');
@jaebradley where is the element with this id?

2017-10-06 16:12 UTC, AlasdairSwan requested changes
Just some minor changes and a few comments.

2017-10-06 16:12 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                    .css('font-style', 'italic')
Please update to use a CSS class for styling, we shouldn't be styling with JS.

2017-10-06 16:12 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                var localPriceText = BasketPage.generateLocalPriceText($(this).text());
There should only be 1 var declaration at the top of the function, comma separating the variable names.

2017-10-06 16:12 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                var localPriceText = BasketPage.generateLocalPriceText($(this).text());
Also, you should just pass ```priceText``` to the function on line 276 instead of getting it again.

2017-10-06 16:12 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                var priceText = $(this).text();
Yeah, please move the function called in the each loop to its own named function so it can be called for each loop instead of duplicating it.

2017-10-06 16:12 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +            $('#card-cvn-help').hover(BasketPage.showCvvTooltip, BasketPage.hideCvvTooltip);
The jQuery object ```$('#card-cvn-help')``` is being created 3 times, please assign it to a variable so it only needs to be created once. Also, remember you can chain jQuery methods.

2017-10-06 17:30 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                    .appendTo('div[aria-labelledby="order-details-region"]');
![image](https://user-images.githubusercontent.com/8136030/31290443-7a934fc4-aa9a-11e7-922d-a7a23ffa9508.png)

2017-10-06 17:35 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +            $('#card-cvn-help').hover(BasketPage.showCvvTooltip, BasketPage.hideCvvTooltip);
This was existing code that I edited to deal with the Jasmine test issues. Would you still like me to make these changes (I know they're quite small) in this PR?

2017-10-06 17:35 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +        var BasketPage = {};
@AlasdairSwan ha - good point!

2017-10-06 18:35 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +            $('#card-cvn-help').hover(BasketPage.showCvvTooltip, BasketPage.hideCvvTooltip);
Yes please, if you're in there already I think any code clean up that can be done should be.

2017-10-10 14:29 UTC, jaebradley commented
@AlasdairSwan mind taking another pass here?

2017-10-10 15:16 UTC, AlasdairSwan requested changes

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                var message = gettext('Problem occurred during checkout. Please contact support');
Missing ```.```

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                    if (['US', 'CA'].indexOf($('select[name=country]').val()) > -1) {
It would be clearer what is going on if you moved the array to a variable.

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                event.preventDefault();
This should be called at the start of the function.

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                $('#card-cvn-help').attr('aria-expanded', 'true');
You can chain jQuery methods instead of instantiating the same jQuery object twice, but here it would make sense to just set both attributes at the same time http://api.jquery.com/attr/#setting-several-attrs.

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                $('#card-cvn-help').attr('aria-expanded', 'false');
You can chain jQuery methods instead of instantiating the same jQuery object twice, but here it would make sense to just set both attributes at the same time http://api.jquery.com/attr/#setting-several-attrs.

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                );
You can chain jQuery methods, but here it would make sense to just set both attributes at the same time http://api.jquery.com/attr/#setting-several-attrs.

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                        .toLocaleString(undefined, {maximumFractionDigits: 0});
Why no decimals? In edx-mktg it rounds to 2 decimal places following a standard already set by the program bundling work.

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                $('#card-cvn-help').hover(BasketPage.showCvvTooltip, BasketPage.hideCvvTooltip);
You can chain jQuery methods instead of instantiating the same jQuery object twice.

2017-10-10 15:16 UTC, AlasdairSwan commented on ecommerce/static/js/test/specs/pages/basket_page_spec.js
> +                var COOKIE_VALUES = {countryCode: 'FOO', rate: 2, code: 'BAR', symbol: 'BAZ'};
There should only be 1 var declaration at the top of the function, comma separating the variable names.

2017-10-10 15:35 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                        .toLocaleString(undefined, {maximumFractionDigits: 0});
[Learner-2012](https://openedx.atlassian.net/browse/LEARNER-2012) seemed to suggest that when currency converting we should not have decimals
> Verify that format for prices without a label is $213 USD

2017-10-10 17:11 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                        .toLocaleString(undefined, {maximumFractionDigits: 0});
@jaebradley can you please confirm with @stroilova the desired format?

2017-10-11 14:37 UTC, jaebradley commented on ecommerce/static/js/pages/basket_page.js
> +                        .toLocaleString(undefined, {maximumFractionDigits: 0});
Based on the conversation in the Learner - Growth HipChat, it seems like no decimals is the desired format for converted values?

2017-10-12 12:42 UTC, AlasdairSwan commented on ecommerce/static/js/pages/basket_page.js
> +                        .toLocaleString(undefined, {maximumFractionDigits: 0});
👍

2017-10-12 12:42 UTC, AlasdairSwan approved these changes
:shipit:

2017-10-13 14:28 UTC, merged