LEARNER-2714 Fix for cat not saving credit hours.
openedx-unsupported/ecommerce pull request #1502
Opened 2017-10-10 10:51 UTC by Ayub-Khan

[LEARNER-2714](https://openedx.atlassian.net/browse/LEARNER-2714):

**Current behavior**
When I attempt to edit the 'credit hours' field in the CAT/Ecomm instance for course run course run ASUx+CHM114x+2184C, the page won't save the change.

**Steps to reproduce**
Navigate to the CAT/Ecomm instance for course run ASUx+CHM114x+2184C (https://ecommerce.edx.org/courses/course-v1:ASUx+CHM114x+2184C).
Edit the page
Set the 'credit hours' field for course as '4' (currently has a value of '3')
Save the page

**Scope & Impact**
The current value of '3' misleads learners who are paying to convert this course to university credit.
Screenshots attached.

2017-10-10 16:23 UTC, clintonb requested changes
Write a test proving you've fixed the problem.

2017-10-11 13:11 UTC, clintonb requested changes
1. Why haven't we seen this problem until now?
2. Update your commit message to follow the best practices at https://openedx.atlassian.net/wiki/spaces/OpenDev/pages/161880915/Git+Best+Practices.

2017-10-11 13:11 UTC, clintonb commented on ecommerce/courses/models.py
> +        seat.save()
Nit: add a newline after this line for legibility.

2017-10-11 13:11 UTC, clintonb commented on ecommerce/courses/tests/test_models.py
> +        course = CourseFactory(id='a/test/c', name='Test Course', site=self.site)
None of these arguments are relevant to your test. Get rid of them. Don't waste time, or add confusion to later readers, by adding unnecessary factory arguments.

2017-10-11 13:11 UTC, clintonb commented on ecommerce/courses/tests/test_models.py
> +        Verify that model's seat updation method updates the seat
This docstring doesn't tell the reader anything that isn't obvious from the name of the test. It can go. Docstrings should go further than tell us what the test does. They should explain _why_ it's being done. There isn't much explanation needed, so this can go.

2017-10-11 13:11 UTC, clintonb commented on ecommerce/courses/tests/test_models.py
> +        credit_data = ['MIT', 2]
There is no reason for this to be an array. Break this into two variables: `credit_provider` and `credit_hours`.

2017-10-11 14:07 UTC, Ayub-Khan commented
@clintonb Im not sure about the question why we discovered this so late or why it did not occur before. Could be that we do not update credit seats once they have been created.

2017-10-11 14:12 UTC, clintonb commented on ecommerce/courses/tests/test_models.py
> +            credit_provider=credit_data[0],
Make sure you run your tests locally _before_ pushing. Doing so helps decreases the latency between push and merge.

2017-10-12 17:51 UTC, clintonb approved these changes

2017-10-12 20:13 UTC, schenedx approved these changes
👍

2017-10-13 07:26 UTC, merged