add logs in clean history command
openedx-unsupported/ecommerce pull request #1506
Opened 2017-10-11 19:29 UTC by ahsan-ul-haq

2017-10-11 19:39 UTC, feanil approved these changes
This is an improvement, not sure if this will fix the issue that caused it to hang but will hopefully give us some more info and reduce the number of things inside the atomic block.

2017-10-11 19:41 UTC, clintonb requested changes

2017-10-11 19:41 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                message = 'Deleted {}s from pk: {} to pk: {}'.format(model.__name__, batch_list[-1], batch_list[0])
Ditch `str.format()` and use the logger's built-in interpolation.

```python
logger.info('Deleted instances of %s with PKs %d and %d', model.__name__, batch_list[0], batch_list[-1])
```

2017-10-11 19:41 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                batch_list = list(history_batch)
There is no need for a new variable: `history_batch = list(qs.values_list('id', flat=True))`

2017-10-11 19:41 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                message = 'Deleted {}s from pk: {} to pk: {}'.format(model.__name__, batch_list[-1], batch_list[0])
Move the log message into the transaction block.

2017-10-11 20:00 UTC, clintonb approved these changes
Update the commit message to follow our best practices: https://openedx.atlassian.net/wiki/spaces/OpenDev/pages/161880915/Git+Best+Practices. Use the previous ticket number.

2017-10-11 20:00 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +                        'Deleted instances of %s with PKs %d and %d',
with PKs between

2017-10-11 20:02 UTC, ahsan-ul-haq commented
@clintonb made the suggested changes

2017-10-12 04:52 UTC, clintonb approved these changes

2017-10-12 11:58 UTC, merged