Fulfillment module for Course Entitlement Products.
openedx-unsupported/ecommerce pull request #1507
Opened 2017-10-12 01:02 UTC by mjfrey

Fulfilment module to fulfill and revoke course entitlement products.

Utils to create or update course entitlement products.

LEARNER-1741

2017-10-13 23:28 UTC, staubina commented on ecommerce/entitlements/utils.py
> +    ProductCategory.objects.get_or_create(category=Category.objects.get(name='Course Entitlements'), product=parent)
Do we can weather or not this was created?  Should we include the data below in the context of the get_or_create using the defaults parameter? If we get an entitlement to we want to update it? 

Would update_or_create work better?

2017-10-13 23:35 UTC, staubina reviewed
Early review comments I will take a deeper look on Monday.

2017-10-16 12:19 UTC, McKenzieW commented on ecommerce/extensions/fulfillment/modules.py
> +        except Exception:  # pylint: disable=broad-except
What kind of exception(s) can we expect to be raised here? Should they possible be handled / logged differently?

2017-10-17 12:15 UTC, staubina commented on ecommerce/entitlements/utils.py
> +    course_entitlement.structure = Product.CHILD
Could you also use update_or_create here for course_entitlement?

2017-10-17 12:15 UTC, staubina commented on ecommerce/entitlements/utils.py
> +    except StockRecord.DoesNotExist:
Should we use get_or_create here instead of relying on the exception?

2017-10-17 12:17 UTC, staubina commented on ecommerce/entitlements/utils.py
> +    stock_record.save()
Looking at this area, we might want to consider an update_or_create.

2017-10-17 12:23 UTC, staubina commented on ecommerce/extensions/fulfillment/modules.py
> +                course_key = line.product.attr.course_key
Note from yesterday's conversation.  Will we get UUID here as well?

2017-10-17 12:23 UTC, staubina commented on ecommerce/extensions/fulfillment/modules.py
> +                    'course_id': course_key
Note from yesterday's conversation: Changing to UUID

2017-10-17 12:23 UTC, staubina commented on ecommerce/extensions/fulfillment/modules.py
> +                    'course_id': course_key,
Note from yesterday's conversation: UUID here also I assume

2017-10-17 12:25 UTC, staubina commented on ecommerce/extensions/fulfillment/tests/test_modules.py
> +class EntitlementFulfillmentModuleTests(FulfillmentTestMixin, TestCase):
Note from yesterday's conversation: Add tests for the UUID as well please.

2017-10-17 12:26 UTC, staubina requested changes
Some requested changes, no major logic issues from what I can see. Let me know if you have any questions.

2017-10-17 14:57 UTC, bderusha requested changes
This is 1/2 a review.  I wanted you to get the comments now.  I will review the 2nd half of this PR after lunch 🍔 🍟

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/tests/test_utils.py
> +            'verfied', 100, self.partner, 'foo-bar', 'Foo Bar Entitlement')
`verfied` spelling

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/tests/test_utils.py
> +        self.assertEqual(product.title, 'Seat in Foo Bar Entitlement')
Why does the title of this use the word "seat".  Seems confusing to me since these are outside of seats, yes?

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/tests/test_utils.py
> +        product = create_or_update_course_entitlement('verfied', 100, self.partner, 'foo-bar', 'Foo Bar Entitlement')
`verfied`

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/tests/test_utils.py
> +        product = create_or_update_course_entitlement('verfied', 200, partner, 'foo-bar', 'Foo Bar Entitlement')
`verfied`

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +def create_parent_course_entitlement(name, course_id):
Consistent use of `course_entitlement` VS `parent_course_entitlement` would be nice.  My preference is to drop the word parent, but my only request is consistency.

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +    parent.title = 'Seat in {}'.format(name)
Reiterating comment in tests. "Seat in" seems like the wrong way to describe these products.

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +    ProductCategory.objects.get_or_create(category=Category.objects.get(name='Course Entitlements'), product=parent)
Can we move 'Course Entitlements' to a constant like `COURSE_ENTITLEMENT_PRODUCT_CATEGORY_NAME`?

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +    parent.attr.course_key = course_id
We discussed this offline, but wanted to come back to it.  Can we refactor this to use `uuid` instead?

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +        logger.debug('Parent course_entitlement [%d] already exists for [%s].', parent.id, course_id)
NIT: move these lines to right after the `get_or_create` so they still log even if something goes wrong re-saving the parent

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +    return course_entitlement
Would be nice if this had the same API contract as django `update_or_create`, a tuple of `(course_entitlement_obj, boolean_created)`

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +        title='Seat in {}'.format(name),
Noting the use of `Seat in`  here as well for cleanup

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +def create_or_update_course_entitlement(certificate_type, price, partner, course_id, name):
Is this only used by tests?  If so maybe we can move it to a test_utils file instead of the main application code

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +    except StockRecord.DoesNotExist:
Agreed.  `get_or_create` is a little cleaner here.

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +def create_or_update_course_entitlement(certificate_type, price, partner, course_id, name):
Also the use of `course_id` where it has been called `course_key` should be updated for consistency.  Obviously if we refactor to use UUID this would also change.

2017-10-17 14:57 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +def create_parent_course_entitlement(name, course_id):
inconsistent use of `course_id` and `course_key`.  Let's pick one and use it everywhere.

2017-10-17 15:18 UTC, mjfrey commented on ecommerce/entitlements/utils.py
> +def create_or_update_course_entitlement(certificate_type, price, partner, course_id, name):
This will eventually be used by the product API endpoint to create new products.  That is why it is in a util and not just the test.

2017-10-17 15:18 UTC, mjfrey commented on ecommerce/entitlements/tests/test_utils.py
> +        self.assertEqual(product.title, 'Seat in Foo Bar Entitlement')
I am looking for a better word.  Any suggestions?

2017-10-17 15:22 UTC, mjfrey commented on ecommerce/entitlements/utils.py
> +    parent.attr.course_key = course_id
Yes, I will add the migration change to this PR and replace the use of the course_key with UUID.

2017-10-17 15:27 UTC, mjfrey commented on ecommerce/entitlements/utils.py
> +def create_parent_course_entitlement(name, course_id):
What specifically is not consistent with parent vs not?  I think the use is correct.

2017-10-17 16:07 UTC, mjfrey commented on ecommerce/entitlements/utils.py
> +        title='Seat in {}'.format(name),
I originally had 'Course Entitlement in', what do you think about that?

2017-10-18 17:08 UTC, staubina commented on ecommerce/extensions/fulfillment/modules.py
> +            except AttributeError:
If for some reason you get all Attribute errors it looks like you will never create a data object.  Then on line 584 when you post_to_entitlement_api you will send a non existent data object.  Should we initialize data as an empty object just in case?

2017-10-18 17:09 UTC, staubina commented on ecommerce/extensions/fulfillment/modules.py
> +        except Exception:  # pylint: disable=broad-except
Did you get a chance to look at this one @mjfrey ?

2017-10-18 17:11 UTC, staubina reviewed
One open question from @McKenzieW about an open exception, otherwise 👍

2017-10-18 18:34 UTC, mjfrey commented on ecommerce/extensions/fulfillment/modules.py
> +        except Exception:  # pylint: disable=broad-except
We generally catch all Exceptions here rather than enumerating all possible exceptions.  Take a look at the Seat revoke.  If anything goes wrong, we just do  not revoke.

2017-10-18 19:21 UTC, McKenzieW commented on ecommerce/extensions/fulfillment/modules.py
> +        except Exception:  # pylint: disable=broad-except
👍 works for me

2017-10-19 10:10 UTC, staubina approved these changes

2017-10-19 16:43 UTC, bderusha requested changes

2017-10-19 16:43 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +                mode = mode_for_seat(line.product)
Mode for seat is not really the correct name for this method.  Can we update the method to be more accurately named `mode_for_product`?

2017-10-19 16:43 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +    parent.title = 'Course Entitlement for {}'.format(name)
Should we have different names for the parent/child products?

2017-10-19 16:43 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +                'expiration_date': '{}'.format(now() + timedelta(days=365)),
Talking with Deen and finance, etc.  It seems like `expiration_date` may be too naive for the use cases we need to support.  Let's talk about this.

2017-10-19 16:44 UTC, bderusha commented
Looks good code-wise.  Biggest question is actually more LMS side model design.

2017-10-19 16:46 UTC, mjfrey commented on ecommerce/entitlements/utils.py
> +    parent.title = 'Course Entitlement for {}'.format(name)
We currently do not for Seats.  We could, but the parent is never actually purchased.

2017-10-19 16:46 UTC, mjfrey commented on ecommerce/extensions/fulfillment/modules.py
> +                mode = mode_for_seat(line.product)
I can rename

2017-10-19 16:47 UTC, mjfrey commented on ecommerce/extensions/fulfillment/modules.py
> +                'expiration_date': '{}'.format(now() + timedelta(days=365)),
say more.  Make this configurable?

2017-10-20 17:05 UTC, mjfrey commented
@bderusha @staubina Removed expiration.  Should be good to go. Take another look.

2017-10-20 17:11 UTC, staubina commented on ecommerce/extensions/fulfillment/modules.py
> +                'is_active': True,
Should we remove is_active from the data as well?

2017-10-20 17:12 UTC, staubina commented on ecommerce/extensions/fulfillment/modules.py
> +                'is_active': False,
As mentioned above.

2017-10-20 17:13 UTC, mjfrey commented on ecommerce/extensions/fulfillment/modules.py
> +                'is_active': True,
oops
Yes, forgot.

2017-10-20 17:14 UTC, staubina approved these changes

2017-10-23 20:14 UTC, bderusha reviewed
My only question is around the revocation API.  1 question about the revoke attribute.  Another not embedded in the code is whether or not it would make sense for the fulfillment API to return a primary key we could look up rather than looking up by username, uuid, mode, etc.

2017-10-23 20:14 UTC, bderusha commented on ecommerce/courses/utils.py
> +def mode_for_product(product):
🎸 🔥 ✊

2017-10-23 20:14 UTC, bderusha commented on ecommerce/entitlements/utils.py
> +    parent.title = 'Course Entitlement for {}'.format(name)
More for administration,  if we don't really use the parent product it would be great to have an easy way to distinguish between them when looking at names in django admin

2017-10-23 20:14 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +                'revoke': True,
What is this? How is it used?  I have questions

2017-10-23 22:06 UTC, mjfrey commented on ecommerce/extensions/fulfillment/modules.py
> +                'revoke': True,
@staubina  and I where thinking that an explicit revoke would be sent to LMS.  This would tell LMS that in fact it is final. 

Not sure I understand the above question.  Can you explain?

2017-10-23 22:15 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +                'revoke': True,
If revoke isn't actually part of the entitlement model this breaks a lot of standards and expectations.  I don't understand what telling the LMS that this is final is meant to prevent or ensure.  Can you explain more?

If we do need some kind of assurance I would prefer to have a separate endpoint or argument  and not pass this as part of the payload.  But ideally I want to know why we need it at all

2017-10-23 22:20 UTC, mjfrey commented on ecommerce/extensions/fulfillment/modules.py
> +                'revoke': True,
I was trying to mimic the entitlement API, there is the explicit active attribute.  The other thing is that revoke is just calling the same entitlement API put endpoint.  
Do you suggest we just fill out the expired_at data?

2017-10-26 15:26 UTC, mjfrey commented
@bderusha @staubina ready for a second round.  Now calling the new Entitlement API.

2017-10-27 00:59 UTC, staubina approved these changes
:shipit: 👍

2017-10-27 13:56 UTC, bderusha requested changes

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/catalogue/migrations/0027_catalogue_entitlement_option.py
> +def remove_catalog_option(apps, schema_editor):
rename to `remove_entitlement_option`

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/catalogue/migrations/0027_catalogue_entitlement_option.py
> +
Can we add the rollback functionality

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/catalogue/migrations/0026_course_entitlement_attr_change.py
> +    """ Remove product attr """
Can we add the rollback functionality

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +                entitlement_option = Option.objects.get(name='Course Entitlement')
we should get by `code` as a practice since that should never change.

Might also be worth updating the migration to differentiate the two values like `course_entitlement` or something

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +                results = response['results']
I'm assuming we don't need to do any response code checks at this level, but wanted to double check that it's being handled by the client

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +                logger.error(
`logger.exception` so we also get the stack trace in case it's something other than a network error

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +                    'Unable to fulfill line [%d] of order [%s] due to a network problem', line.id, order.number
with the generic exception we do not know that it was a network error.

Might be worth keeping the original exceptions with this error and then add the broad exception with a different message

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +            entitlement_option = Option.objects.get(name='Course Entitlement')
same comment.  get by `code`

2017-10-27 13:56 UTC, bderusha commented on ecommerce/extensions/fulfillment/modules.py
> +            entitlement_api_client.entitlements(course_entitlement_uuid).delete()
do we need to check the response code here to ensure that it was revoked?

2017-10-27 14:23 UTC, mjfrey commented on ecommerce/extensions/catalogue/migrations/0026_course_entitlement_attr_change.py
> +    """ Remove product attr """
do we need it?  There will be FK to things we do not want to delete.

2017-10-27 14:23 UTC, mjfrey commented on ecommerce/extensions/catalogue/migrations/0027_catalogue_entitlement_option.py
> +
Same comment as above.

2017-10-27 14:24 UTC, mjfrey commented on ecommerce/extensions/fulfillment/modules.py
> +                results = response['results']
Yes, we rely on the client.  If it is a bad response we will get an exception.

2017-10-27 14:25 UTC, mjfrey commented on ecommerce/extensions/fulfillment/modules.py
> +            entitlement_api_client.entitlements(course_entitlement_uuid).delete()
No.  If it did not work we would get an exception.

2017-10-27 15:55 UTC, bderusha approved these changes

2017-10-27 15:55 UTC, bderusha commented on ecommerce/extensions/catalogue/migrations/0026_course_entitlement_attr_change.py
> +    """ Remove product attr """
If something goes wrong for some reason and we do a rollback to older code the code will break because it expects `course_key` but the database only has `UUID` since we didnt actually reverse the change

2017-10-27 15:55 UTC, bderusha commented on ecommerce/extensions/catalogue/migrations/0027_catalogue_entitlement_option.py
> +    """ Remove course entitlement option """
This code is better since there is no older code referencing anything.  I don't see why we can't just call `course_entitlement_option.delete()` for completeness though.

2017-10-27 15:56 UTC, bderusha commented
2 comments on the migration rollback.  I don't feel like I need to review the changes since they are pretty straightforward so I gave it a preemptive thumb

2017-10-27 16:48 UTC, merged