[ENT-720] Fix error when trying to apply a voucher.
openedx-unsupported/ecommerce pull request #1521
Opened 2017-10-22 15:13 UTC by UmanShahzad

Without this, there are cases where people try to apply a coupon on the basket page and because there are no lines in the basket, they get an error since some code assumes there's always at least one line. So we just ensure lines exist in the basket before accessing them.

**JIRA tickets**: [ENT-720](https://openedx.atlassian.net/browse/ENT-720)

**Merge deadline**: End of sprint.

**Testing instructions**:

I don't know how to get into a situation where the basket has no lines when trying to apply the coupon -- sorry, just lack of eCommerce knowledge here :\ Tried looking but couldn't figure it out. @douglashall ?

2017-10-22 15:13 UTC, edx-webhook commented
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1521&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-10-23 09:36 UTC, douglashall reviewed
Looks like we need a new test case.

2017-10-23 10:57 UTC, UmanShahzad commented
@douglashall Yep, will be doing that today or tomorrow. Would maybe shed some light on how this happens in practice.

2017-10-23 11:13 UTC, mjfrey commented
I do not know what causes this state.  I think just protecting against it is fine.

2017-10-23 11:22 UTC, UmanShahzad commented
@mjfrey Alright, no problem.

2017-10-23 11:32 UTC, mjfrey requested changes

2017-10-23 11:32 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> +                if self.request.basket.num_lines:
I would just at the top of this block check to see if the basket is empty and if so -- re-direct to the summary page.

2017-10-23 11:34 UTC, UmanShahzad commented on ecommerce/extensions/basket/views.py
> +                if self.request.basket.num_lines:
:+1:

2017-10-23 11:44 UTC, UmanShahzad commented on ecommerce/extensions/basket/views.py
> +                if self.request.basket.num_lines:
The basket is empty if `id is None and num_lines == 0`, so I'll just change the check for the ID above to check for emptiness instead. In that case, we won't even need this new check here.

2017-10-23 11:50 UTC, UmanShahzad commented
@douglashall @mjfrey One last look? This time I don't think we'll need any new test.

2017-10-23 12:00 UTC, mjfrey approved these changes

2017-10-23 13:13 UTC, UmanShahzad commented
Had to fix a tiny test.

2017-10-23 15:06 UTC, douglashall commented on ecommerce/extensions/basket/views.py
> +        if self.request.basket.is_empty:
We are okay making the assumption here that if a basket is not empty, then it has an id?

2017-10-23 15:08 UTC, mjfrey commented on ecommerce/extensions/basket/views.py
> +        if self.request.basket.is_empty:
if you look at oscar, they check for that in the is_empty method.

2017-10-23 15:08 UTC, douglashall commented on ecommerce/extensions/basket/views.py
> +        if self.request.basket.is_empty:
Do we have a test for this condition?

2017-10-23 15:09 UTC, douglashall commented on ecommerce/extensions/basket/views.py
> +        if self.request.basket.is_empty:
@mjfrey Awesome. Thanks.

2017-10-23 15:09 UTC, douglashall approved these changes

2017-10-23 15:15 UTC, UmanShahzad commented on ecommerce/extensions/basket/views.py
> +        if self.request.basket.is_empty:
Yep, tests already exist. I'm surprised this wasn't set to `is_empty` in the first place. We should search through the codebase for other similar scenarios. Might make an OSPR for that.

2017-10-23 15:17 UTC, merged

2017-10-24 07:59 UTC, itsjeyd reviewed
@UmanShahzad :+1:

- [x] ~~I tested this:~~ [N/A](https://github.com/edx/ecommerce/pull/1521#issuecomment-338626152)
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ N/A
- [x] ~~Includes documentation~~ N/A