Add ability to apply a voucher to a basket with an Enterprise Offer.
openedx-unsupported/ecommerce pull request #1532
Opened 2017-10-27 16:22 UTC by douglashall

Voucher-based offers should take precedence over any other offers
that may be valid for a given basket. This change will set the
priority on new ConditionalOffers higher than Enterprise offers
or Program offers.

ENT-734

2017-10-27 16:40 UTC, mjfrey requested changes

2017-10-27 16:40 UTC, mjfrey commented on ecommerce/extensions/voucher/utils.py
> +        priority=20,
Can we create priority constants so they can be more descriptive.
VOUCHER_PRIORITY = 20
ENTERPRISE_OFFER_PRIORITY = 10
...

2017-10-27 16:40 UTC, mjfrey commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        self.assertEqual(voucher_offer.priority, 20)
Add a couple more tests to prove that a voucher wins over offers.

2017-10-27 17:44 UTC, douglashall commented on ecommerce/extensions/voucher/utils.py
> +        priority=20,
Done.

2017-10-27 17:47 UTC, douglashall commented on ecommerce/extensions/voucher/tests/test_utils.py
> +        self.assertEqual(voucher_offer.priority, 20)
I'm not sure it's worth adding a test like that. It would only be testing the Otto code which sorts the offers [here](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/applicator.py#L59). The tests we already have ensure that the offer/coupon creation forms will create offers with the appropriate priority.

2017-10-30 09:31 UTC, douglashall commented
@mjfrey Can you give this another look when you get a chance? Thanks.

2017-10-30 15:05 UTC, douglashall commented
@mjfrey Anything else to address here?

2017-10-30 16:11 UTC, mjfrey commented
Looks fine, I just still would love a couple tests to make sure Oscar is acting the way we think it should.

2017-10-30 16:35 UTC, douglashall commented
@mjfrey Where would you add such a test?

2017-10-30 16:39 UTC, mjfrey commented
In either the ProgramOffers Tests or the Condition tests.  Would just be nice to know when we update oscar that our assumptions are still valid and do not break our coupons / offers.

I would create the scenario that this PR assumes and just test it is true.

2017-10-30 17:13 UTC, douglashall commented
@mjfrey How does this look?

2017-10-30 18:21 UTC, mjfrey commented on ecommerce/extensions/test/factories.py
> +            priority=20
OFFER_PRIORITY_VOUCHER

2017-10-30 18:22 UTC, mjfrey approved these changes
Yes thanks.  Just 2 small Nits.

2017-10-30 19:24 UTC, merged