Management command for creating bulk orders
openedx-unsupported/ecommerce pull request #1550
Opened 2017-11-02 11:44 UTC by ahsan-ul-haq

Bulk orders are needed to create for testing migrations on
huge date
LEARNER-3075

2017-11-02 13:40 UTC, clintonb requested changes

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +from __future__ import unicode_literals
Move this to ecommerce/extentions/order/management/commands/create_fake_orders.py.

We want to keep order-related code together. Also, we want to make it clear that this data is fake and should not be used in production.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +        parser.add_argument('--orders',
Let's call this count so that its purpose is obvious.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +                            help='Number of orders to be generated as bulk order.')
The term "bulk order" implies something different for me. I would rephrase this to: Number of orders to create.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +        parser.add_argument('--product_id',
Use SKU as that is how we generally present products to end users/API clients. Also, the corresponding `StockRecord` will keep track of the price and currency being used.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +            if not product.is_seat_product:
Why does the product class matter? I see no reason to limit this to seat products.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +        if product_id:
Make this required and avoid the extra work.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +            products = Product.objects.all()
This should go away but, in the future, just filter by product class if you only care about a single class of product.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +        for _ in range(orders):
Use double underscore, `__`. A single underscore, `_`, is typically reserved as an alias to `ugettext()`.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +            if not basket.id:
Given that you wrote `create_basket`, you should guarantee the basket has an ID. This should go away.

2017-11-02 13:40 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +        user = User.objects.order_by('id').first()
I would either create a new user, making this a great way to also populate the user table, or allow the user to pass in the username. I'm kinda leaning toward making a new one.

2017-11-02 13:58 UTC, ahsan-ul-haq commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +        parser.add_argument('--product_id',
Are you referring to partner_sku?

2017-11-02 14:02 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +        parser.add_argument('--product_id',
Correct.

2017-11-02 14:03 UTC, clintonb commented on ecommerce/core/management/commands/generate_bulk_orders.py
> +        parser.add_argument('--product_id',
Also, note that you should probably use the partner from that SKU to get the `Site` that should be associated with the basket/order.

2017-11-03 09:56 UTC, ahsan-ul-haq commented
@clintonb made the suggested changes.
FYI: @edx/learner-spartans

2017-11-03 13:20 UTC, clintonb requested changes

2017-11-03 13:20 UTC, clintonb commented on ecommerce/extensions/order/management/commands/create_fake_orders.py
> +        parser.add_argument('--partner_sku',
Nit: "sku" is sufficient.

2017-11-03 13:20 UTC, clintonb commented on ecommerce/extensions/order/management/commands/create_fake_orders.py
> +                            help='Partner SKU for which orders are to be generated.')
SKU corresponding to the product for which orders will be created.

2017-11-03 13:20 UTC, clintonb commented on ecommerce/extensions/order/management/commands/create_fake_orders.py
> +            site = SiteConfiguration.objects.get(partner=partner).site
`site = partner.siteconfiguration.site`

2017-11-03 13:20 UTC, clintonb commented on ecommerce/extensions/order/management/commands/create_fake_orders.py
> +            product = Product.objects.get(stockrecords__partner_sku=partner_sku)
Minor, but you can decrease the number of queries:

```python
stock_record = StockRecord.objects.get(partner_sku=partner_sku)
product = stock_record.product
partner = stock_record.partner
```

2017-11-03 13:20 UTC, clintonb commented on ecommerce/extensions/order/management/commands/create_fake_orders.py
> +            msg = 'Site configuration for partner_sku {} does not exists.'.format(partner_sku)
Site configuration is linked to partners, not SKUs.

`No Site Configuration exists for partner {}!'.format(partner.id)`

2017-11-03 13:20 UTC, clintonb commented on ecommerce/extensions/order/management/commands/create_fake_orders.py
> +        user = User.objects.create(username='fake_user', email='fake_user@example.com')
This will fail the second time this command is run. Use `user = UserFactory()`

2017-11-03 13:20 UTC, clintonb commented on ecommerce/extensions/order/management/commands/tests/test_create_fake_orders.py
> +    def test_product_not_exist(self):
`test_product_does_not_exist`

2017-11-03 13:20 UTC, clintonb commented on ecommerce/extensions/order/management/commands/tests/test_create_fake_orders.py
> +    def test_site_config_not_exist(self):
`test_site_configuration_does_not_exist`

2017-11-03 13:25 UTC, ahsan-ul-haq commented on ecommerce/extensions/order/management/commands/create_fake_orders.py
> +        user = User.objects.create(username='fake_user', email='fake_user@example.com')
May be we can use get_or_create I am bit uncomfortable with using factories here.

2017-11-03 13:47 UTC, clintonb commented on ecommerce/extensions/order/management/commands/create_fake_orders.py
> +        user = User.objects.create(username='fake_user', email='fake_user@example.com')
Write your own, non-test, factory then. The advantage of using the factory is that we get to create a large set of users. This is advantageous for times when we want to run tests on large user tables.

2017-11-03 14:04 UTC, ahsan-ul-haq commented
@clintonb made the suggested changes

2017-11-03 14:21 UTC, clintonb approved these changes

2017-11-03 18:52 UTC, merged