Update program offer logic to account for entitlements
openedx-unsupported/ecommerce pull request #1564
Opened 2017-11-13 20:11 UTC by McKenzieW

Take existing user entitlements into account for partial program offers and calculate offers for programs with course entitlement products.

[LEARNER-2659](https://openedx.atlassian.net/browse/LEARNER-2659)

2017-11-13 20:12 UTC, McKenzieW commented
@edx/helio I'm still having some issues with the updates I made for tests, but here's the PR so you can start getting a look at my code.

2017-11-13 20:19 UTC, mjfrey requested changes

2017-11-13 20:19 UTC, mjfrey commented on ecommerce/programs/conditions.py
> +    def get_user_ownership_data(self, basket, retrieve_entitlements):
default should be False for retrieve_entitlements

2017-11-13 20:19 UTC, mjfrey commented on ecommerce/programs/conditions.py
> +        api_resources = ['enrollments']
I would create a tuple set to have the api that corresponds to the resource.

2017-11-13 20:19 UTC, mjfrey commented on ecommerce/programs/conditions.py
> +                        if api_resource == 'enrollments':
use the tuple above to just write this once and eliminate the if clauses.

2017-11-13 20:19 UTC, mjfrey commented on ecommerce/programs/conditions.py
> +            for entitlement in course['entitlements']:
Will the element 'entitlements' always exists in the JSON?

2017-11-13 21:23 UTC, McKenzieW commented on ecommerce/programs/conditions.py
> +            for entitlement in course['entitlements']:
Yes, it will just be an empty list if there aren't any entitlements

2017-11-14 12:14 UTC, staubina commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        print expected
Are these just here for debugging the tests you are currently working on?

2017-11-14 12:17 UTC, staubina commented on ecommerce/programs/conditions.py
> +                    if entitlement['mode'].lower() in applicable_seat_types:
Is the lower() needed here?  The expectation elsewhere seems to be that the mode slugs will match the seat type slugs.

2017-11-14 12:20 UTC, McKenzieW commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        print expected
Yes

2017-11-14 12:38 UTC, staubina commented on ecommerce/programs/conditions.py
> +            for api_resource in api_resources:
It seems like this should not be a loop and instead should just be two code paths, one for enrollments and one for entitlements. 

The loop seems unnecessary.

2017-11-14 12:40 UTC, staubina commented on ecommerce/programs/conditions.py
> +                if entitlement['mode'].lower() in applicable_seat_types:
Same as earlier comment, is the lower() necessary?

2017-11-14 12:57 UTC, staubina requested changes
Some comments on the code per our discussion.

Keep up the great work.

2017-11-15 15:44 UTC, mjfrey requested changes

2017-11-15 15:44 UTC, mjfrey commented on ecommerce/programs/conditions.py
> +        data_list = cache.get(cache_key, [])
No need for the empty list.

2017-11-15 15:44 UTC, mjfrey commented on ecommerce/programs/conditions.py
> +    def get_from_cache_or_endpoint(self, basket, resource_name, endpoint):
get_entitlements_and_enrollments

2017-11-15 15:44 UTC, mjfrey commented on ecommerce/programs/tests/mixins.py
> +                entitlement_class, created = ProductClass.objects.get_or_create(  # pylint: disable=unused-variable
you can just use the existing util class:
create_or_update_course_entitlement
https://github.com/edx/ecommerce/blob/master/ecommerce/entitlements/utils.py#L41

2017-11-15 15:47 UTC, McKenzieW commented on ecommerce/programs/conditions.py
> +    def get_from_cache_or_endpoint(self, basket, resource_name, endpoint):
This method only retrieves one resource at a time, and can in theory be used to retrieve any data from LMS.  How about, `get_lms_resource`?

2017-11-15 16:30 UTC, staubina commented on ecommerce/programs/tests/mixins.py
> +                entitlement_class, created = ProductClass.objects.get_or_create(  # pylint: disable=unused-variable
Why is the # pylint: disable=unused-variable needed?  Can we remove the unused variable?

2017-11-15 16:30 UTC, McKenzieW commented on ecommerce/programs/tests/mixins.py
> +                entitlement_class, created = ProductClass.objects.get_or_create(  # pylint: disable=unused-variable
it's just that the method returns two variables and we only need one of them, but I'm refactoring this code to use a util method anyway.

2017-11-15 16:37 UTC, staubina commented on ecommerce/programs/tests/mixins.py
> +                entitlement_class, created = ProductClass.objects.get_or_create(  # pylint: disable=unused-variable
If you only need one of the values you can do something like

`
def foo():
   return 'Hello', 'World'

one = foo()[0]
two = foo()[1]
`

2017-11-15 16:42 UTC, McKenzieW commented on ecommerce/programs/tests/mixins.py
> +                entitlement_class, created = ProductClass.objects.get_or_create(  # pylint: disable=unused-variable
Probably, yes. I will keep that in mind for the future. But in this case I won't need to do that because the util method I'll be using just returns one thing

2017-11-15 16:43 UTC, staubina commented on ecommerce/programs/tests/mixins.py
> +                entitlement_class, created = ProductClass.objects.get_or_create(  # pylint: disable=unused-variable
Just keep the following as an FYI then.

2017-11-15 17:08 UTC, McKenzieW commented on ecommerce/programs/conditions.py
> +        data_list = cache.get(cache_key, [])
I do need the empty list somewhere because otherwise the method will return a NoneType object instead of a list if there aren't any enrollments or entitlements, but I'm adding it to the return statement instead of here

2017-11-15 23:07 UTC, mjfrey commented on ecommerce/entitlements/utils.py
> +    course_entitlement.product_class = entitlement_class
Thanks for catching this.

2017-11-15 23:16 UTC, mjfrey commented on ecommerce/programs/tests/mixins.py
> +Product = get_model('catalogue', 'Product')
Are these used anymore?

2017-11-15 23:17 UTC, mjfrey commented on ecommerce/programs/tests/mixins.py
> +                sku = entitlement.stockrecords.first().partner_sku
no need to assign the variable if only using it once.

2017-11-16 12:34 UTC, McKenzieW commented on ecommerce/programs/tests/mixins.py
> +Product = get_model('catalogue', 'Product')
The partner factory is because partner has to be passed to the util for creating course entitlement products, but the Product model is not

2017-11-16 12:37 UTC, McKenzieW commented on ecommerce/programs/tests/mixins.py
> +                sku = entitlement.stockrecords.first().partner_sku
I used uuid twice, as the uuid for the course and in the name of the entitlement to indicate which course it is for.

2017-11-16 12:44 UTC, mjfrey approved these changes
Remember to squash.

2017-11-16 12:45 UTC, McKenzieW commented
@mjfrey I just want to do a bit more testing locally with the new pagination handling before I merge

2017-11-16 14:57 UTC, McKenzieW commented
Tested locally and all the different combinations of basket lines and existing enrollments and entitlements are working as expected.

@staubina do you have any further comments before I merge?

2017-11-16 16:32 UTC, staubina approved these changes

2017-11-16 16:34 UTC, merged