Add support for refunding course entitlements.
openedx-unsupported/ecommerce pull request #1582
Opened 2017-12-03 20:53 UTC by mjfrey

Add to the refund API the ability to refund orders that have course entitlements.

LEARNER-3414

2017-12-03 23:12 UTC, mjfrey commented
@amangano-edx FYI

2017-12-04 01:14 UTC, mjfrey commented
@edx/helio Please take a look.

2017-12-04 12:27 UTC, McKenzieW commented on ecommerce/extensions/api/v2/views/refunds.py
> +            order = user.orders.filter(number=order_number).first()
since there should only be one order with the given number, could you not just use `get(number=order_number)` rather than `filter(number=order_number).first()`?

2017-12-04 12:28 UTC, McKenzieW commented on ecommerce/extensions/api/v2/views/refunds.py
> +            order = user.orders.filter(number=order_number).first()
which then I suppose you'd have to wrap in a get except rather than using the if else block below

2017-12-04 12:36 UTC, McKenzieW commented on ecommerce/extensions/refund/api.py
> +    line = order.lines.filter(refund_lines__id__isnull=True,
I believe the same logic should apply here as above, where there would only be one line in a given order with the given entitlement UUID, so `get` rather than `filter(...).first()` should be appropriate with a try..except rather than if..else block

2017-12-04 20:18 UTC, staubina requested changes
Some open questions and comments.

2017-12-04 20:18 UTC, staubina commented on ecommerce/extensions/api/v2/views/refunds.py
> +        user = request.user
This will move the User from the username in the data to the user making the request, is this expected? It seems to be a change that could cause problems for the existing code.

2017-12-04 20:18 UTC, staubina commented on ecommerce/extensions/api/v2/views/refunds.py
> +        user = request.user
Is it possible that the user making the request is say a Staff/Admin user while the refund is for a different username?

2017-12-04 20:18 UTC, staubina commented on ecommerce/extensions/api/v2/views/refunds.py
> +        user = request.user
Looking later in the code I might be missing something, but I do not see the reason to set user here to the requesting user.

2017-12-04 20:18 UTC, staubina commented on ecommerce/extensions/refund/api.py
> +            refunds.append(refund)
Should we log something if there is an attempt to refund that is None here? Or is it handled with Exception logs?

2017-12-04 20:18 UTC, staubina commented on ecommerce/extensions/refund/api.py
> +        pass
Do we need to be concerned here?  Should we log before passing with exception?

2017-12-04 20:50 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/refunds.py
> +        user = request.user
You are right.  This is left over.  I will remove and only use the username param.

2017-12-04 20:50 UTC, mjfrey commented on ecommerce/extensions/refund/api.py
> +        pass
I should log something here.

2017-12-05 15:00 UTC, amangano-edx commented on ecommerce/extensions/api/v2/views/refunds.py
>          if not username:  # pragma: no cover
This seems to indicate that username is required for entitlement refunds. We should clarify that in the docstring.

2017-12-05 15:05 UTC, amangano-edx commented on ecommerce/extensions/api/v2/views/refunds.py
> +        if order_number:
I think it would be better to check for `entitlement_uuid` as that's more specific to entitlements.

2017-12-05 15:05 UTC, amangano-edx commented on ecommerce/extensions/api/v2/views/refunds.py
> +                refunds = create_refunds(orders, course_id)
Could we move this code to two separate methods, `refund_entitlement` and `refund_courserun`?

2017-12-05 15:06 UTC, amangano-edx commented on ecommerce/extensions/api/v2/views/refunds.py
> +                refunds = create_refund_for_entitlement(order, entitlement_uuid)
We should make sure both `order_number` and `entitlement_uuid` exist before making these calls.

2017-12-05 15:07 UTC, amangano-edx commented on ecommerce/extensions/api/v2/views/refunds.py
> +            if user.orders.exists():
Why do we need to do this for the course_run case but not for entitlements?

2017-12-05 15:09 UTC, amangano-edx commented on ecommerce/extensions/refund/api.py
> +def create_refund_for_entitlement(order, entitlement_uuid):
Nit: this returns a list, but the method name is singular. Giving this a plural name would make things clearer.

2017-12-05 15:17 UTC, amangano-edx commented on ecommerce/extensions/api/v2/tests/views/test_refunds.py
> +        data = self._get_data(username=self.user.username, order_number=order.number, entitlement_uuid='111')
Nit: it would be good if we could avoid hardcoding the skus.

2017-12-05 15:18 UTC, amangano-edx commented on ecommerce/extensions/api/v2/tests/views/test_refunds.py
> +    def _get_data(self, username=None, course_id=None, order_number=None, entitlement_uuid=None):
What API endpoint does this hit?

2017-12-05 15:18 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/refunds.py
> +        if order_number:
not really.  An order_number is the key here.

2017-12-05 15:19 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/refunds.py
> +                refunds = create_refunds(orders, course_id)
Do not see the need.  They both create refunds.  No need to break out and create new methods.

2017-12-05 15:19 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/refunds.py
> +            if user.orders.exists():
Since no order_number is sent this has been here as a check to make sure the user has orders before attempting.

2017-12-05 15:26 UTC, mjfrey commented on ecommerce/extensions/api/v2/tests/views/test_refunds.py
> +    def _get_data(self, username=None, course_id=None, order_number=None, entitlement_uuid=None):
no API it is a method

2017-12-05 15:28 UTC, amangano-edx commented on ecommerce/extensions/api/v2/tests/views/test_refunds.py
> +    def _get_data(self, username=None, course_id=None, order_number=None, entitlement_uuid=None):
ohh, oops. the diff made it look like it was making a post.

2017-12-05 15:30 UTC, amangano-edx commented on ecommerce/extensions/api/v2/tests/views/test_refunds.py
> +        View should not create a refund if an entitlement order/lineis invalid.
Nit: 'order/line is'

2017-12-05 15:33 UTC, amangano-edx commented on ecommerce/extensions/api/v2/views/refunds.py
> +                refunds = create_refunds(orders, course_id)
Methods that handle one isolated piece of functionality are easier to read/maintain than long, monothic methods that do many things and contain many if/else blocks.

2017-12-05 16:30 UTC, staubina approved these changes

2017-12-06 19:38 UTC, merged