Remove usage of simple history
openedx-unsupported/ecommerce pull request #1583
Opened 2017-12-04 12:04 UTC by ahsan-ul-haq

LEARNER-3348

2017-12-04 14:50 UTC, clintonb requested changes

2017-12-04 14:50 UTC, clintonb commented on ecommerce/courses/models.py
> +    created = models.DateTimeField(
Don't manually make these fields. Use `from django_extensions.db.models import TimeStampedModel`. Also, make sure these fields are populated with the data from the first and last historical record.

2017-12-04 15:45 UTC, ahsan-ul-haq commented on ecommerce/courses/models.py
> +    created = models.DateTimeField(
I tried using that but it requires a default value as, I believe, it does not allow null=True.

2017-12-04 15:58 UTC, clintonb commented on ecommerce/courses/models.py
> +    created = models.DateTimeField(
Drop the fields.

2017-12-04 16:00 UTC, ahsan-ul-haq commented on ecommerce/courses/models.py
> +    created = models.DateTimeField(
So we are not going to need that as well?

2017-12-04 16:03 UTC, clintonb commented on ecommerce/courses/models.py
> +    created = models.DateTimeField(
Sorry. Keep your customizations, and populate with the historical records.

2017-12-05 09:47 UTC, ahsan-ul-haq commented
@clintonb madee the change

2017-12-05 20:28 UTC, ahsan-ul-haq commented
@clintonb please take a look.

2017-12-05 20:39 UTC, clintonb reviewed
Fix the migration, and update the translations.

2017-12-05 20:39 UTC, clintonb commented on ecommerce/courses/migrations/0007_auto_20171205_0800.py
> +# -*- coding: utf-8 -*-
Merge this with the migration above.

2017-12-05 20:39 UTC, clintonb commented on ecommerce/courses/migrations/0007_auto_20171205_0800.py
> +from ecommerce.courses.models import Course
This is not the proper way to access models in migrations. Use `apps.get_models()`. See https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations.

2017-12-05 20:39 UTC, clintonb commented on ecommerce/courses/migrations/0007_auto_20171205_0800.py
> +        migrations.RunPython(add_created_date, remove_created_date),
Merge these into a single method, and avoid iterating over the data twice.

2017-12-05 20:39 UTC, clintonb commented on ecommerce/courses/migrations/0007_auto_20171205_0800.py
> +            created_date = course.history.earliest().history_date.strftime(ISO_8601_FORMAT)
Why are you converting the `datetime` object to a string? That is not necessary.

2017-12-05 20:39 UTC, clintonb commented on ecommerce/courses/migrations/0007_auto_20171205_0800.py
> +        migrations.RunPython(add_created_date, remove_created_date),
Also, don't bother with a revert. If we revert the merged migration, the column will be deleted. Use [`RunPython.noop`](https://docs.djangoproject.com/en/1.11/ref/migration-operations/#django.db.migrations.operations.RunPython.noop).

2017-12-05 20:39 UTC, clintonb commented on ecommerce/courses/models.py
> +    created = models.DateTimeField(
Nit: Both of these declarations can be on one line.

2017-12-05 20:39 UTC, clintonb commented on ecommerce/courses/models.py
> +    history = HistoricalRecords()
Nit: put this back where it was.

2017-12-05 20:39 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +        return obj.modified.strftime(ISO_8601_FORMAT)
What happens if the value is `None`?

2017-12-05 20:39 UTC, clintonb commented on ecommerce/courses/models.py
> +        null=True,
Make these fields non-nullable in a follow-on PR.

2017-12-06 10:45 UTC, ahsan-ul-haq commented
@clintonb made the suggested changes.

2017-12-06 13:14 UTC, waheedahmed approved these changes
Just one comment otherwise :+1:

2017-12-06 13:14 UTC, waheedahmed commented on ecommerce/courses/migrations/0006_auto_20171204_1036.py
> +            created_date = course.history.earliest().history_date
No need to create variables, just directly assign the value to model fields.

2017-12-06 14:08 UTC, ahsan-ul-haq commented
@waheedahmed made the change. @clintonb please review

2017-12-06 14:12 UTC, clintonb approved these changes
Please ensure the [Hawthorn release notes](https://openedx.atlassian.net/wiki/spaces/COMM/pages/158045104/Hawthorn) are updated to inform maintainers that django-simple-history is being removed from this service.

2017-12-06 14:12 UTC, clintonb commented
FYI @edx/learner @edx/devops @edx/open-source-team

2017-12-07 13:15 UTC, ahsan-ul-haq commented
Closing this and creating a new PR https://github.com/edx/ecommerce/pull/1587

2017-12-07 13:15 UTC, closed without merging