Added course migration
openedx-unsupported/ecommerce pull request #1592
Opened 2017-12-08 12:16 UTC by ahsan-ul-haq

Added the modified and created date in course model. That was removed as it was causing some issues in the stage which have been dealt with.

2017-12-11 11:14 UTC, waheedahmed approved these changes
Just one comment, otherwise looks good

2017-12-11 11:14 UTC, waheedahmed commented on ecommerce/extensions/api/v2/tests/views/test_courses.py
>          except ObjectDoesNotExist:
Remove this try except statements.

2017-12-11 14:17 UTC, ahsan-ul-haq commented
@waheedahmed  made the suggested change. @clintonb please take a look.

2017-12-11 14:21 UTC, clintonb requested changes
Why are you adding so much code back to the repo? You only need to modify the `Course` model.

2017-12-11 14:21 UTC, clintonb commented on ecommerce/core/management/commands/clean_history.py
> +from __future__ import unicode_literals
Why is this file here?

2017-12-11 14:21 UTC, clintonb commented on ecommerce/extensions/catalogue/models.py
> +class ProductAttributeValue(AbstractProductAttributeValue):
Why are these being added back?

2017-12-11 14:25 UTC, ahsan-ul-haq commented on ecommerce/core/management/commands/clean_history.py
> +from __future__ import unicode_literals
because as per @feanil suggested history tables need to be emptied before we remove them otherwise, when we drop the table, it will take down the database because it will use up all of our disk IO.

2017-12-12 08:55 UTC, ahsan-ul-haq commented on ecommerce/extensions/catalogue/models.py
> +class ProductAttributeValue(AbstractProductAttributeValue):
because [here](https://github.com/edx/ecommerce/pull/1592/files#diff-612c9c2724929804eb68ea7d3f14a15bR62) we want to remove ProductAttributeValue data as well.

2017-12-12 14:04 UTC, ahsan-ul-haq commented
@clintonb please review.

2017-12-12 14:12 UTC, clintonb approved these changes
Squash your commits and update your commit message to follow our guidelines: https://openedx.atlassian.net/wiki/spaces/OpenDev/pages/161880915/Git+Best+Practices#GitBestPractices-CommitMessages.

2017-12-13 17:21 UTC, clintonb commented
@ahsan-ul-haq why do you keep opening/closing this PR?

2017-12-13 17:23 UTC, ahsan-ul-haq commented
Apparently the codecov is not working on this last time mike suggest closing and then opening it trigger that so I was trying that.

2017-12-13 17:24 UTC, clintonb commented
Given that your branch is out of date, rebase it and push. Alternatively, work with IT to ensure the webooks still work.

2017-12-21 11:48 UTC, ahsan-ul-haq commented
Closing this as this is being done in https://github.com/edx/ecommerce/pull/1612

2017-12-21 11:48 UTC, closed without merging