WIP: Clee/learner 2986
openedx-unsupported/ecommerce pull request #1621
Opened 2018-01-03 21:38 UTC by BenjiLee

2018-01-09 16:31 UTC, mikix requested changes

2018-01-09 16:31 UTC, mikix commented on docs/internationalization.rst
> +source users may choose to use another language. Marking content for translation ensures our users have this choice.
This section reads oddly.  "Even if this application is only run in English" -- "this application" means ecommerce at edx.org I guess?  And by open source users you mean server admins running an instance of openedx rather than users of the site?  It all makes it sound like you're talking to other edX employees rather than the community.

Maybe something like "An installation of ecommerce can choose to support any number of non-English languages" or something nicer.

2018-01-09 16:31 UTC, mikix commented on docs/internationalization.rst
> +  LANGUAGE_COOKIE_NAME = 'ecommerce_language'
That seems like a misleading "suggested" name.  Since right above you say this name should be shared between platform and ecommerce.  Maybe...  'openedx-language' (dashes or underscores?)

2018-01-09 16:31 UTC, mikix commented on docs/internationalization.rst
> +.. _Django's Locale Middleware: https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#how-django-discovers-language-preference
This link feels like it's in the wrong section (original link was in previous one).

2018-01-09 16:31 UTC, mikix commented on docs/internationalization.rst
> +To enable localization for Paypal, enable the waffle switch "create_and_set_webprofile" in the admin. Waffle switches
Hah.  Reading this for the first time, without any context, I have no idea why that switch would control this. Not sure it's worth having a parenthetical here or not, though.

2018-01-09 16:31 UTC, mikix commented on docs/internationalization.rst
> +cookie When the language code is fetched from the cookie (as described in Ecommerce Language Negotiation), only the base
Missing a period after cookie.

2018-01-09 16:31 UTC, mikix commented on docs/internationalization.rst
> +set in PAYPAL_LOCALES in ecommerce/extensions/payment/constants.py will be used.
Is that for realz? We didn't have en first before this PR. Were we defaulting to Chinese?

2018-01-09 16:31 UTC, mikix commented on docs/internationalization.rst
> +can be enabled at http://YOUR_HOST_NAME/admin/waffle/switch/
Is there a way to mark that as not-a-link so that it doesn't get rendered as clickable?

2018-01-09 16:31 UTC, mikix commented on docs/internationalization.rst
> +Language negotiation for the ecommerce site will be handled by `Django's Locale Middleware`_. Languages are enabled in
This left me wanting somehow.  I can read that doc, but like...  which parts of the normal django negotiation do we actually rely on? (do we take advantage of i18n_patterns?, do we set LANGUAGE_SESSION_KEY ourselves?, or do we just jump to the LANGUAGE_COOKIE_NAME part of it?)

2018-01-09 18:41 UTC, BenjiLee commented
@catong

2018-01-09 20:31 UTC, BenjiLee commented on docs/internationalization.rst
> +.. _Django's Locale Middleware: https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#how-django-discovers-language-preference
Moved.

2018-01-09 20:31 UTC, BenjiLee commented on docs/internationalization.rst
> +set in PAYPAL_LOCALES in ecommerce/extensions/payment/constants.py will be used.
Updating code in https://github.com/edx/ecommerce/pull/1630

2018-01-09 20:31 UTC, BenjiLee commented on docs/internationalization.rst
> +cookie When the language code is fetched from the cookie (as described in Ecommerce Language Negotiation), only the base
Perioded.

2018-01-09 20:31 UTC, BenjiLee commented on docs/internationalization.rst
> +can be enabled at http://YOUR_HOST_NAME/admin/waffle/switch/
I heard it's impossible.

2018-01-09 20:31 UTC, BenjiLee commented on docs/internationalization.rst
> +To enable localization for Paypal, enable the waffle switch "create_and_set_webprofile" in the admin. Waffle switches
Added.

2018-01-09 20:31 UTC, BenjiLee commented on docs/internationalization.rst
> +  LANGUAGE_COOKIE_NAME = 'ecommerce_language'
Changed to openedx's actual cookie name.

2018-01-09 20:46 UTC, amangano-edx commented on docs/internationalization.rst
> +already.
Is this relevant for the open source community? They could choose to use a different provider if they wanted right?

2018-01-10 20:41 UTC, BenjiLee commented
@mikix Ready for another pass

2018-01-11 14:32 UTC, mikix requested changes
Looks real good.  Couple comments.

2018-01-11 14:32 UTC, mikix commented on docs/internationalization.rst
> +3. LANGUAGE_COOKIE_NAME is used to negotiate language. A user's language is set in their account settings in
The indentation of point 3 is wrong...  Not sure why looking at this, but maybe the code block below is messing it up?

2018-01-11 14:32 UTC, mikix commented on docs/internationalization.rst
> +'es'. Paypal takes a country code and then resolves a language from this code so 'es' will map to 'MX' when it is sent
This sentence is confusing.  You talk about country -> language, but then use an example of language -> country.

Maybe the following is clearer?  "then resolves a language from this code so 'es' on the ecommerce side will map to 'MX' which is sent to Paypal who then resolves 'MX' back to 'es'"

2018-01-11 14:33 UTC, mikix commented on docs/internationalization.rst
> +.. code-block:: bash
bash not python? (used two places here)

2018-01-11 14:36 UTC, mikix commented on docs/internationalization.rst
> +'es'. Paypal takes a country code and then resolves a language from this code so 'es' will map to 'MX' when it is sent
Or "then resolves a language from this code.  For example, ...."

2018-01-11 14:43 UTC, BenjiLee commented on docs/internationalization.rst
> +.. code-block:: bash
updated

2018-01-11 14:44 UTC, BenjiLee commented on docs/internationalization.rst
> +3. LANGUAGE_COOKIE_NAME is used to negotiate language. A user's language is set in their account settings in
I was artificially newlining the text. I took all the new lines out. I believe readthedocs and github wiki should handle that for us.

2018-01-11 16:16 UTC, catong requested changes
@BenjiLee Did a first pass and left comments inline.

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +.. _internationalization coding guidelines: http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/conventions/internationalization/i18n.html
Suggest either moving all links down to bottom of the file, or move to a separate links.rst document so that common links used in multiple files don't need to be duplicated and can be maintained in one place. If you use a separate links.rst file, then you will need to add an "include" in the files that refer to links.rst, e.g. ```.. include:: ../../links.rst```

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +Language negotiation for the ecommerce site will be handled by `Django's Locale Middleware`_. Below is the list of Django's Language Negotiation rule in priority order.
"will be handled" -> "is handled"

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +Language negotiation for the ecommerce site will be handled by `Django's Locale Middleware`_. Below is the list of Django's Language Negotiation rule in priority order.
"Django's Language Negotiation rules, in priority order, are as follows."

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +1. Language prefix is not enabled by default for the ecommerce application.
Use ```#.``` for automatic list numbering.

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +3. LANGUAGE_COOKIE_NAME is used to negotiate language. A user's language is set in their account settings in edx-platform which sets the language cookie. The language cookie name should be the same c
For filename/monospace formatting use double ` (``) instead of single straight quote.

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +Paypal Language Negotiation
Two uppercase "P"s in "PayPal"

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +To enable localization for Paypal, enable the waffle switch "create_and_set_webprofile" (The language request is sent to Paypal in a "WebProfile") in the admin. Waffle switches can be enabled at http
"Paypal" -> "PayPal" throughout

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +.. _internationalization coding guidelines: http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/conventions/internationalization/i18n.html
Throughout, apply line wrapping to make it easier to comment on specific lines. Can be done using Cmd+option+Q with your cursor somewhere in the paragraph.

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +To enable localization for Paypal, enable the waffle switch "create_and_set_webprofile" (The language request is sent to Paypal in a "WebProfile") in the admin. Waffle switches can be enabled at http
"in the admin" seems a bit unclear - do you mean in Django Admin? Suggest following a consistent pattern for referring to Django Admin, as in: 

Also, http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/ecommerce/enable_receipt_page.html

Remove the parenthetical statement and make it the following sentence, rather than breaking up the first sentence.

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +.. code-block:: python
This code block is not showing up in the generated HTML.

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +A language code for the ecommerce IDA will be taken from a cookie as described in Ecommerce Language Negotation. When the language code is fetched from the cookie, only the base language will be used
Missing "i" in "Negotation"
"base language will be used" -> "base language is used"
"will resolve to" -> "resolves to"

Use double backquotes (``) for monospace formatting rather than single straight quote/

2018-01-11 16:16 UTC, catong commented on docs/internationalization.rst
> +If a language fetched from the cookie cannot be found in PAYPAL_LOCALES, the LANGUAGE_CODE is used. If the LANGUAGE_CODE does not exist in PAYPAL_LOCALES, Paypal will use its own language negotiation
"Paypal" -> "PayPal"

2018-01-11 16:45 UTC, BenjiLee commented on docs/internationalization.rst
> +.. _internationalization coding guidelines: http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/conventions/internationalization/i18n.html
I ended up force quitting :(

2018-01-12 15:58 UTC, BenjiLee commented
Closed in favor of https://github.com/edx/edx-documentation/pull/1641

2018-01-12 15:58 UTC, closed without merging