WIP:  ENT-803:  Added management command to create enrollment codes for courses.
openedx-unsupported/ecommerce pull request #1653
Opened 2018-02-15 09:23 UTC by saleem-latif

2018-02-20 11:13 UTC, zubair-arbi requested changes
Overall functionality looks good.

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +    pass
Please add some docstring for this exception, e.g. `""" Raised when we fail to generate enrollment code for a course. """`
Also since this is generic exception which we will raise when we fail to generate enrollment codes for a course so maybe we could name it something like `CourseEnrollmentCodeGenerationError`.

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +    ch.setLevel(logging.DEBUG)
nit: remove this code for debugging,

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            help='Path to file to read courses from.',
`Path of the file to read courses id from.'`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            '--limit',
for consistency with `batch-sleep-time` argument we can rename it to `batch-limit`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +        failed = []
nit `failed_courses`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            while courses.count() > 0:
Use len(courses)
> Note that if you want the number of items in a QuerySet and are also retrieving model instances from it (for example, by iterating over it), it’s probably more efficient to use len(queryset) which won’t cause an extra database query like count() would.
https://docs.djangoproject.com/en/dev/ref/models/querysets/#count

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            logger.error('Completed enrollment codes generation. %d of %d failed.', len(failed), total_courses)
`'Completed processing for {total_courses_count} total courses for enrollment codes generation out of which {failed_courses_count} courses failed.'`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            logger.info('Enrollment codes created for %d courses.', total_courses)
`Successfully generated enrollment codes for all {total_courses_count} courses.`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +    def course_is_eligible_for_enrollment_code(course):
nit `course_is_eligible_for_enrollment_code` -> `is_course_eligible_for_enrollment_code`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            1. Course have a type that supports enrollment codes AND
Course have course modes that supports enrollment codes

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +                'Enrollment code generation skipped for "%s" course. Because it already has enrollment codes.',
`'Skipping enrollment code generation for "%s" course due to existing enrollment codes.'`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +                'Enrollment code generation skipped for "%s" course. '
`'Skipping enrollment code generation for "%s" course.`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/tests/test_create_enrollment_codes_command.py
> +        self.professional_course2 = self.create_course(seat_type=str('professional'))
`self.professional_course_1` and `self.professional_course_2`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/tests/test_create_enrollment_codes_command.py
> +            call_command('create_enrollment_codes', course_ids_file="fake/path", batch_sleep_time=0)
`fake/path` -> `invalid/courses_id/file/path`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/tests/test_create_enrollment_codes_command.py
> +        with LogCapture(LOGGER_NAME) as lc:
nit `lc` -> `log_capture`

2018-02-20 11:13 UTC, zubair-arbi commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            if not os.path.exists(course_ids_file):
I think we can create 2 sub method for generating enrollment codes from file or from db which can return, counts for total processed courses and total failed courses, like:
`_generate_enrollment_code_from_file`
`_generate_enrollment_code_from_db`

2018-02-20 12:49 UTC, saleem-latif commented
@georgebabey can you please take a look at the PR and share your thoughts?

2018-02-20 15:34 UTC, brittneyexline requested changes
great start!

2018-02-20 15:34 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +        offset = options['offset'] or 0
is this redundant with the defaults provided from the parser?

2018-02-20 15:34 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            if not os.path.exists(course_ids_file):
i agree.

2018-02-20 15:34 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +                time.sleep(batch_sleep_time * 60)
can you explain why we need this sleep statement?

2018-02-20 15:34 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            1. Course have a type that supports enrollment codes AND
The course has a course mode that supports enrollment codes

2018-02-20 15:34 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            2. Course does not already has an enrollment code
The course does not already have an enrollment code for that course mode

2018-02-20 15:34 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +        for seat_typ in seat_types:
seat_type

2018-02-20 15:34 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +        else:
it probably shouldn't happen, but what if len(seats) > 1?

2018-02-20 15:34 UTC, brittneyexline commented on ecommerce/courses/tests/test_create_enrollment_codes_command.py
> +        expected = (
seems like this is copied in each test, and you have the ddt decorator above, is the intention here to refactor to use ddt?
i also think you should fetch the created enrollment code product from the database and check that instead of just checking log messages.

2018-02-21 10:03 UTC, saleem-latif commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +                time.sleep(batch_sleep_time * 60)
I added this in case we want to add sleep time before processing each batch of courses to reduce strain on database.

2018-02-21 10:34 UTC, saleem-latif commented on ecommerce/courses/tests/test_create_enrollment_codes_command.py
> +        expected = (
I tried converting the tests to use ddt but setup for each test case is very different. I have remove the ddt import and class decorator.
I have also updated the tests to verify enrollment codes are actually created in the database.

2018-02-21 10:35 UTC, saleem-latif commented
@zubair-arbi , @brittneyexline I have made the changes you suggested, please take another look.

2018-02-21 12:14 UTC, zubair-arbi approved these changes
Changes looks good 👍 

@georgebabey @brittneyexline @saleem-latif  We need to decide how we will use this management command, e.g. running it against all courses at a time or manually providing the file with specific courses ids.

2018-02-22 18:26 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +        courses = Course.objects.all()[batch_offset:batch_offset + batch_limit]
I think we should be filtering this at least on verification_deadline not in the past. it also seems weird to me that we're calling for all the Course objects then taking a slice at two separate points - I am not sure we're getting the intended benefits of batching.

2018-02-22 18:26 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            time.sleep(batch_sleep_time * 60)
what evidence do you have that this is necessary, and if it is, that it should be a parameter that is passed in by the caller?

2018-02-22 18:26 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +    def _generate_enrollment_codes_from_db(self, batch_limit, batch_offset, batch_sleep_time):
i would prefer we remove batch_offset as an option to be passed into the script. as a caller, i'm not sure why it would be useful, but i see why it is needed to keep track of batches below.

2018-02-22 18:26 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            batch_offset += courses.count()
does this mean that total_courses and batch_offset are always the same if we're starting from 0? if we get rid of batch_offset as a parameter then we could simplify this and have one variable.

2018-02-23 08:02 UTC, saleem-latif commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +        courses = Course.objects.all()[batch_offset:batch_offset + batch_limit]
Verification deadline is not a required field and can be null, so we might miss some courses if we filter on verification_deadline. 
>it also seems weird to me that we're calling for all the Course objects then taking a slice at two separate points - I am not sure we're getting the intended benefits of batching.

https://docs.djangoproject.com/en/2.0/topics/db/queries/#limiting-querysets
Django handles slicing on queryset by creating a corresponding query with limit and offset so all courses will not fetched.

2018-02-23 08:06 UTC, saleem-latif commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +            time.sleep(batch_sleep_time * 60)
My thinking is that if the command runs for say 5 minutes than it will make a lot of queries to database (i.e. to fetch courses, to create enrollment code products, to check if enrollment code product exists etc.) that may cause strain on database. I am not sure if it will. I wanted add this just in case.
I can update the default `batch_sleep_time` to 0 so that there is no sleep time in normal runs of the management command?

2018-02-23 08:10 UTC, saleem-latif commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +    def _generate_enrollment_codes_from_db(self, batch_limit, batch_offset, batch_sleep_time):
Let's say we run the management command and it processes say 20% of the courses and then we terminate the command or it errors out for some reason. In this case we can pass in the appropriate `batch_offset` and start processing only the courses that need to be updated.

2018-02-23 18:45 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +        courses = Course.objects.all()[batch_offset:batch_offset + batch_limit]
i feel like there has got to be a way to more intelligently filter "all" courses. there are almost 6000 courses in that table on prod, and at least 2/3 of these can't possibly be active courses that you can buy a seat in. it may be that the best answer to the filtering question is we pull the list of courses and use the file option when running this command (in which case this branch isn't necessary), but i think that is something you should consider.

2018-02-23 18:52 UTC, brittneyexline commented on ecommerce/courses/management/commands/create_enrollment_codes.py
> +    def _generate_enrollment_codes_from_db(self, batch_limit, batch_offset, batch_sleep_time):
we should be able to avoid "erroring out for some reason" short of a hardware failure. we could also send in the list of unprocessed courses, which at this point seems like the safer option.

i think ultimately, if you feel like you have to code defensively for unknown failures or performance issues for processing all courses, maybe it is better to force the caller to specify courses and remove the logic for running with all courses. i will leave this up to you.

2018-02-26 09:02 UTC, saleem-latif commented
@brittneyexline I have removed `batch_offset` and `batch_sleep_time` from the command please take another look.

2018-02-26 15:48 UTC, brittneyexline approved these changes
considering we will likely run this with the course id file, this looks good to go. also, we don't have to wait on merging this because of WL-1457, since we decide when to run the command.

2018-02-27 07:38 UTC, merged