WIP- [ENT-860]Update Basket and Receipt Page UI to include Bulk Enrollment Information
openedx-unsupported/ecommerce pull request #1655
Opened 2018-02-16 13:33 UTC by asadiqbal08

[ENT-860](https://openedx.atlassian.net/browse/ENT-860)

#### NOTE: The PR is in progress.

2018-02-19 11:39 UTC, zubair-arbi requested changes

2018-02-19 11:39 UTC, zubair-arbi commented on ecommerce/templates/oscar/basket/messages/new_total.html
> +{% load currency_filters %}
nit: remove this templatetag as we are not using it.

2018-02-19 11:39 UTC, zubair-arbi commented on ecommerce/templates/oscar/basket/messages/new_total.html
> +            <b>We’ve updated your quantity.</b>
move html tags outside the block `blocktrans` or use some substitute for it.
```html
{% blocktrans with link_start='<a href="https://www.edx.org/gfa">' link_end='</a>' %}
    Please read {{ link_start }}our FAQs to view common questions about our certificates.{{ link_end }}
{% endblocktrans %}
```

2018-02-19 11:39 UTC, zubair-arbi commented on ecommerce/extensions/payment/forms.py
> +                    self.fields['organization'] = forms.CharField(max_length=60, label=_('Organization'))
In actual `BusinessClient` model the name field has limit of 255 characters:
https://github.com/edx/ecommerce/blob/master/ecommerce/core/models.py#L591-L594
```python
class BusinessClient(models.Model):
    """The model for the business client."""
    name = models.CharField(_('Name'), unique=True, max_length=255)
```

2018-02-19 11:39 UTC, zubair-arbi commented on ecommerce/extensions/payment/forms.py
> +                    self.fields['organization'] = forms.CharField(max_length=60, label=_('Organization'))
Also please add validation (empty organization field in case of enrollment code) of organization (business client) field in the form's `clean` method [here](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/payment/forms.py#L131-L182).

2018-02-19 12:09 UTC, asadiqbal08 commented on ecommerce/extensions/payment/forms.py
> +                    self.fields['organization'] = forms.CharField(max_length=60, label=_('Organization'))
I did not see the validation on first_name, last_name in clean method. currently, There are two levels of validation. 
1- Client side 
2- backend
on backend side, The following code marking the `required` attribute fields as [HERE](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/payment/forms.py#L101). The payment form method form_invalid will raise the error if client side validation failed to handle.

2018-02-20 19:35 UTC, asadiqbal08 commented
@zubair-arbi kindly take another look.

2018-02-22 11:15 UTC, asadiqbal08 commented on ecommerce/templates/oscar/basket/messages/new_total.html
> +{% load currency_filters %}
we are using it now.

2018-02-23 06:12 UTC, asadiqbal08 commented
@rrakhshan fyi
<img width="816" alt="screen shot 2018-02-23 at 11 11 24 am" src="https://user-images.githubusercontent.com/7334669/36580512-629fe284-188a-11e8-9bac-cc90c656aace.png">

2018-02-23 14:34 UTC, brittneyexline commented
@asadiqbal08 can you provide testing instructions for the business sandbox?

2018-02-26 13:47 UTC, asadiqbal08 commented
@brittneyexline added.

2018-02-27 15:53 UTC, brittneyexline reviewed
I also have looked on the sandbox, and i noticed that on the receipt page that the "Verify your Identity" box comes up, which seems odd to me, because the person didn't buy a verified seat for themselves.

I also did not receive the email with the codes, which I would have expected to happen because it is existing functionality, but that is something we can debug outside the scope of this.

2018-02-27 15:53 UTC, brittneyexline commented on ecommerce/core/url_utils.py
> +def get_lms_explore_courses():
to be consistent, rename to get_lms_explore_courses_url

2018-02-27 15:53 UTC, brittneyexline commented on ecommerce/extensions/payment/tests/test_forms.py
> +        """ Verify the field 'organization' is present in form when basket have enrollment code product. """
"Verify the field 'organization' is present in the form when the basket has an enrollment code product."

2018-02-27 15:53 UTC, brittneyexline commented on ecommerce/extensions/payment/tests/test_forms.py
> +        """ Verify the field 'organization' is not present in form when basket has not any enrollment code product. """
"Verify the field 'organization' is not present in the form when the basket does not have an enrollment code product."

2018-02-27 15:53 UTC, brittneyexline commented on ecommerce/templates/edx/checkout/receipt.html
> +          <a class="find-more-courses-link nav-link" href="{{ explore_courses_url }}" target="_blank">
is this meant to open in a new tab?

2018-02-28 10:55 UTC, asadiqbal08 commented on ecommerce/templates/edx/checkout/receipt.html
> +          <a class="find-more-courses-link nav-link" href="{{ explore_courses_url }}" target="_blank">
yes

2018-02-28 10:58 UTC, asadiqbal08 commented
@brittneyexline I have addressed some of your suggestions. I saw your comment about "Verify your Identity" box. The changes in the PR are not related to that box. Can we open a new ticket for any changes related to that particular box?

2018-02-28 13:18 UTC, asadiqbal08 commented
@zubair-arbi @brittneyexline @georgebabey are we good with the current change set ? If yes, then please let me know so I could merge it.

2018-03-01 16:36 UTC, brittneyexline approved these changes

2018-03-02 04:31 UTC, georgebabey approved these changes

2018-03-05 12:09 UTC, zubair-arbi approved these changes
I have verified these changes with the [changes for backend support](https://github.com/edx/ecommerce/pull/1657). 👍

2018-03-14 08:30 UTC, merged