ENT-804 Link order with enrollment code to the provided business client
openedx-unsupported/ecommerce pull request #1657
Opened 2018-02-19 12:28 UTC by zubair-arbi

@asadiqbal08 @saleem-latif @georgebabey 
**Description:** Store `Company` Field data from Basket Page in `BusinessClient` model for bulk enrollment code purchases and link the order with the that Business Client.

**JIRA:** [ENT-804](https://openedx.atlassian.net/browse/ENT-804)

**Implemented Tasks:**
* Added  a new field `client` in the `Order` model and also added the related migration.
* Added a method `link_order_with_business_client` in common order mixin .`EdxOrderPlacementMixin` which is used by all payment processor (`cybersource`, `paypal`,  `stripe`).
* Called this method `link_order_with_business_client` immediately after an order is created to link the current order with the provided business client for bulk enrollment purchase.

**Remaining Tasks:**
* Add unittests.

**Dependencies:** https://github.com/edx/ecommerce/pull/1655

**Merge deadline:** N/A

**Installation instructions:** Checkout ecommerce on this branch `zub/ENT-804-link-enrollment-code-order-with-client` and run order model migrations like `./manage.py migrate order`.

**Testing instructions:**

1. Create a course with in **LMS** and create its related modes in **ECOM** for single seat `SKU` and bulk purchase `Bulk SKU`
<img width="1397" alt="screen shot 2018-02-19 at 5 04 37 pm" src="https://user-images.githubusercontent.com/5072991/36376985-176fab8c-1597-11e8-86f0-6d9825d48370.png">
2. In Ecom add bulk purchase product in the baseket by going to a url like: `http://localhost:8002/basket/single-item/?sku=4040F39`
<img width="883" alt="screen shot 2018-02-19 at 5 06 17 pm" src="https://user-images.githubusercontent.com/5072991/36377084-7cda0580-1597-11e8-9b0c-f94e6ba390af.png">
3. Provide the value for organization field (not present currently), e.g. `TEST CLIENT 1`. This field will be available once the related PR https://github.com/edx/ecommerce/pull/1655 is merged.
4. Click on "Place Order" button after providing the payment form values.
5. Now go to Ecom django admin for `core/businessclient` and verify that a new Business Client with the name `TEST CLIENT 1` has been added.
<img width="835" alt="screen shot 2018-02-19 at 5 11 39 pm" src="https://user-images.githubusercontent.com/5072991/36377392-dd576e56-1598-11e8-9deb-357c91ab4bbf.png">
6. Now go to Ecom django admin for `order/order` and verify that a new order has been placed with the provided payment values.
<img width="1398" alt="screen shot 2018-02-19 at 5 19 31 pm" src="https://user-images.githubusercontent.com/5072991/36377468-15b73de4-1599-11e8-85c3-ddac6c486b57.png">

7. Verify that on django detail page of the order `order/order` the new client field `Business Client:` is now linked with the business client `TEST CLIENT 1`.
<img width="836" alt="screen shot 2018-02-19 at 5 14 29 pm" src="https://user-images.githubusercontent.com/5072991/36377368-c2a54d58-1598-11e8-80e9-2ced7504f83e.png">

8. Repeat the process for single seat purchase and verify that the new client field `Business Client:`  remains empty (order not linked with business client).

2018-02-22 10:51 UTC, zubair-arbi commented
@mjfrey @brittneyexline @georgebabey Please have look on these changes for linking orders with the business client provided from the basket page as field `organization`.

2018-02-23 18:25 UTC, brittneyexline commented on ecommerce/extensions/order/models.py
> +    client = models.ForeignKey(
i'm sorry to change this on you, but i don't  think we can add this to order. there are currently ~28.5 million rows in the order table in prod ecommerce, so altering this table is not really feasible.
unfortunately, i think it would be better to create a new model that foreign keys to both order and business client.

2018-02-23 18:25 UTC, brittneyexline commented on ecommerce/extensions/payment/views/cybersource.py
> +            self.link_order_with_business_client(request.POST, order)
i would rename this method to something like handle_post_order because we're not necessarily linking all orders to a business client, and other post order handling might happen down the line that should probably be in one place.

2018-02-26 12:23 UTC, zubair-arbi commented on ecommerce/extensions/order/models.py
> +    client = models.ForeignKey(
@brittneyexline According to my understanding there are 2 ways to avoid downtime while running migrations:
1. Adding a (nullable) field 
2. Adding a new table

I have used the management command `create_fake_orders` to create 100000 dummy orders on **business sandbox** for testing these changes _(It took ~40 min to create 100000 fake orders)_.
```bash
./manage.py create_fake_orders --count=5 --sku=319955C
```
* On business sandbox running this migration took only 1 sec to run as we are adding a nullable field.
```
./manage.py migrate order
```
* Reverting this migrations took 3 sec
```
./manage.py migrate order 0016
```
You can verify migration time on the business sandbox.

I believe this is clean solution instead of adding a new m2m table.

2018-02-26 15:26 UTC, brittneyexline approved these changes
thanks for doing the research on the migration - let's move forward with your solution.

2018-02-27 15:52 UTC, mjfrey commented on ecommerce/extensions/order/models.py
> +        BusinessClient, verbose_name=_('Business Client'), null=True, blank=True
We certainly do not want to do this.  Do not change the built in Order model from Oscar.  Please add a key to the Invoice model.  That is a cleaner way as to not add a custom column to the generic Order model.

2018-02-27 15:53 UTC, mjfrey requested changes
We do not want to modify the generic Order model that comes with Oscar.

2018-02-28 13:34 UTC, zubair-arbi commented
@mjfrey @brittneyexline @georgebabey I have updated the PR to use `Invoice` model for linking the bulk purchase orders with business clients. Please have another look.
Currently there are `1926` records in `Invoice` model (prod-replice) so the running the new `Invoice` migration won't have any problems.

2018-03-02 13:43 UTC, zubair-arbi commented
@asadiqbal08 @brittneyexline I have add the changes to store `organization` value from basket page as `BasketAttribute` and use it later to link order with the business client on CyberSource Silent Order POST.
Task Remaining: Tests update

2018-03-05 12:05 UTC, zubair-arbi commented
@mjfrey @brittneyexline @georgebabey @asadiqbal08 I have verified these changes on business sandbox.

2018-03-05 15:50 UTC, brittneyexline commented on ecommerce/extensions/payment/views/paypal.py
> +            basket_add_organization_attribute(basket, self.request.GET)
it seems odd to me to put this in each implementation of specific payment processors when this has nothing to do with individual payment processors. is there any way to put this somewhere common? where do other basket attributes get attached to the basket?

2018-03-06 14:48 UTC, zubair-arbi commented on ecommerce/extensions/payment/views/paypal.py
> +            basket_add_organization_attribute(basket, self.request.GET)
@brittneyexline I have made this change in order to have a consistent flow for each payment processor, e.g. saving the business client name as organization attribute on the basket immediately after we create a basket and retrieve it later when we have done creating order for linking the order with business client.
Also Cybersource and Stripe triggers order creation on POST request but PayPal triggers order creation on GET request, that's why I am manually providing request data to method `basket_add_organization_attribute`.

I am not sure if there is common place where we can put this maybe someone from @edx/ecommerce can give us suggestion.

There are few other places where we set basket attributes, e.g. `prepare_basket` but that method is called when basket is initialized to render a basket page, before providing the payment details on that basket page by the user.

2018-03-06 21:35 UTC, brittneyexline approved these changes

2018-03-07 10:12 UTC, asadiqbal08 approved these changes

2018-03-14 09:58 UTC, merged