check for entitlement products in addition to course run products
openedx-unsupported/ecommerce pull request #1664
Opened 2018-02-28 21:06 UTC by McKenzieW

Allow courses in addition to course runs to be included in Coupon Ranges' catalog queries

[LEARNER-4166](https://openedx.atlassian.net/browse/LEARNER-4166)

2018-02-28 21:09 UTC, McKenzieW commented
@edx/helio

2018-03-01 18:42 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +        if self.range:
is this supposed to be different from the ranger param passed into this function?

2018-03-01 18:46 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +        if self.range:
Yes you can pass a range to the base function if you want to use that instead of the benefit's range. I suppose if the passed in range is what is being used to determine applicable lines, though, we should be using that for the logic that follows. Good catch

2018-03-01 19:15 UTC, Mjloturco requested changes
Logic seems good, I think it could be broken into some more readable functions, would be happy to identify possible functionization in person if you'd like (thats a new word).

2018-03-01 19:15 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +            applicable_lines = [line for line in basket.all_lines()
Is this you filtering for entitlement products? do products have a more explicit way of identifying type? i.e. just like line.product.type == 'Course Entitlement' or something?

2018-03-01 19:15 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +                return len(self.benefit.get_applicable_lines(self, basket)) == basket.all_lines().count()
This line is pretty hard to read and make sense of, if it could be wrapped in a helpfully named function that might be useful, otherwise atleast a comment would help.

2018-03-01 19:15 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +                    if product.course:
This also seems like an implicit way of determining product type, may break heavily if we have products in the future that have similar attributes but different types.

2018-03-01 19:15 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +            for identifier, cache_key, line in course_run_ids + course_uuids:
should this be under the if conditional on line 78? or does this always need to be executed.

2018-03-01 19:15 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +        else:
This whole else statement is really big, is there any chance pieces of it could be broken into a seperate function?

2018-03-01 20:34 UTC, staubina requested changes
Please take a look at the comments I posted.  I have not dug into the tests, I need to wrap a few things up before I leave today.  I will take a look first thing when I get back.

2018-03-01 20:34 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +                line.product.attr.certificate_type.lower() in applicable_range.course_seat_types]
Slight code style thing here for this you might want to adjust the spacing to something more like 

```
return [
        line for line in lines 
        if line.product.is_seat_product or 
           line.product.is_course_entitlement_product and 
           hasattr(line.product.attr, 'certificate_type') and
           line.product.attr.certificate_type.lower() in applicable_range.course_seat_types
    ]
```

2018-03-01 20:34 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +                line.product.attr.certificate_type.lower() in applicable_range.course_seat_types]
More in line with come of the topics here: http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#breaking-long-lines

2018-03-01 20:34 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +    def get_applicable_lines(self, offer, basket, range=None):  # pylint: disable=redefined-builtin
Can we avoid adding the pylint disable?  I need to look into what triggers it.

2018-03-01 20:34 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +            return super(Benefit, self).get_applicable_lines(offer, basket, range=range)  # pylint: disable=bad-super-call
Please look at why this disable is required and see if it can be removed.

2018-03-01 20:34 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +        else:
The else if also probably not required because you are returning in the if, so you will not get to the code that is currently in the else.

2018-03-01 20:34 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +                except:  # pylint: disable=bare-except
Please avoid bare exceptions if we can.  Are there certain exceptions we can catch here and interpret.

2018-03-01 20:34 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +        if self.benefit.range:
I think you can combine these two if statements 

```
if self.benefit.range and self.benefit.range.catalog_query:
```

2018-03-01 20:40 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +        if self.benefit.range:
unfortunately python doesn't seem to break at the first false in boolean `and` calculations

2018-03-01 20:41 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +                except:  # pylint: disable=bare-except
This code is moved from it's previous location in the Range model

2018-03-01 20:54 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +        if self.benefit.range:
I think python does short circuit evaluate, is there something else going on ? https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not

2018-03-02 10:48 UTC, jaebradley commented on ecommerce/extensions/catalogue/tests/mixins.py
> +        course_uuid = course_uuid if course_uuid else uuid4()
Nit: unnecessary variable assignment? Looks like this is solely used on [line 85](https://github.com/edx/ecommerce/pull/1664/files#diff-439a8341d45fbef63fb11f0da08d17cbR85)? 

Maybe

```python
entitlement.attr.UUID = course_uuid if course_uuid else uuid4()
```

is more terse?

2018-03-02 10:50 UTC, jaebradley commented on ecommerce/extensions/catalogue/tests/mixins.py
> +        partner = PartnerFactory()
Same thing here?

```python
entitlement = factories.ProductFactory(
  product_class=self.entitlement_product_class, 
  stockrecords__partner=PartnerFactory(),
  stockrecords__price_currency='USD'
)
```

2018-03-02 11:28 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +        query = None
It looks like query is `None` when `applicable_range` is `None` 

**or** if `applicable_range` is `not None` but `applicable_range.catalog_query` is `None`.

So maybe this could be simplified to

```python
applicable_range = range if range else self.range
# if applicable_range is None, this will return
# if applicable_range.catalog_query is None, this will return
# ...right?
if not applicable_range or not applicable_range.catalog_query
  return super(..etc)
query = applicable_range.catalog_query
```

2018-03-02 11:40 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +    def _try_cache_for_contains_data(self, lines, domain, partner_code, query):
`_try_cache_for_contains_data` seems a little vague...maybe `identify_uncached_product_identifiers`?

![alt-text](https://memegenerator.net/img/instances/66865576/naming-things-is-too-damn-hard.jpg)

2018-03-02 11:48 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +                lines.remove(line)
Manipulating the underlying `lines` array might not be an obvious side-effect to the method caller. You could consider creating a `cached_lines` (there must exist a better name) array that you push to when `response is True` and then returning that instead of `lines`.

2018-03-02 11:52 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +                in_range = response[str(identifier)]
It's probably just my lack of context, but it's not terribly obvious what `in_range` is supposed to represent?

If it is, and I'm just being ignorant, plz ign0r3.

2018-03-02 11:58 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +                raise Exception('Could not contact Discovery Service.')
Would it be useful to log / monitor anything about the Discovery Service error?

2018-03-02 17:28 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +                in_range = response[str(identifier)]
would `in_catalog_range` be clearer?

2018-03-05 12:09 UTC, McKenzieW commented
@jaebradley @staubina @Mjloturco Could you take another look and share any other comments you have?

2018-03-05 12:57 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +                        course_run_ids=','.join([course_run_id for (course_run_id, cache_key, line) in course_run_ids]),
Nit: The verbosity here is valuable but if you were looking for something more terse you could also do

```python
','.join([course_run_metadata[0] for course_run_metadata in course_run_ids])
```

![image](https://user-images.githubusercontent.com/8136030/36976121-75ef5118-204a-11e8-88b7-d45592b4d408.png)

If you used `dict`s instead of `tuple`s you could use the key instead of the index

```python
','.join([metadata['id'] for metadata in course_run_ids])
```

Not a big deal either way.

2018-03-05 13:17 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +                        course_run_ids=','.join([course_run_id for (course_run_id, cache_key, line) in course_run_ids]),
I definitely like the idea of using a dict to preserve the detail from the verbosity while also being a bit more terse

2018-03-05 13:22 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +                    raise Exception('Could not contact Discovery Service.')
I know this is copied code and I know this error message is only used in one place across all edX repos

![image](https://user-images.githubusercontent.com/8136030/36976518-ef5ab3f2-204b-11e8-9c31-881489eb0fb5.png)

but should there be a slightly more descriptive error message like `Failed to fetch course information from the Discovery Service when calculating applicable lines`? 

Also, I think it would be helpful to at least log the Discovery exception since I think it's going to get lost in the stack trace when you raise the blank `Exception`.

[Example](https://repl.it/repls/RottenWateryCylinders)

2018-03-05 13:22 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +                    course_run_ids.append((product.course.id, cache_key, line))
This needs to be a `dict` as well?

2018-03-05 13:25 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +                    course_run_ids.append((product.course.id, cache_key, line))
it sure does. Thanks for catching that

2018-03-05 13:26 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +                    raise Exception('Could not contact Discovery Service.')
Yeah that makes sense. I'll add a bit more details to the error message and log the failure.

2018-03-05 13:29 UTC, jaebradley commented on ecommerce/extensions/offer/models.py
> +                    raise Exception('Could not contact Discovery Service.')
I don't know why that blank `Exception` exists but another thing to consider is whether or not a more specific `Exception` class is more useful.

[This is a good explanation of various error-handling strategies](https://stackoverflow.com/a/24065533/5225575).

2018-03-05 16:55 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +        if self.benefit.range:
Per our conversation @McKenzieW Please take another look here.

2018-03-05 16:58 UTC, staubina requested changes
The change to the conditional should do the trick for me. Along with the changes recommended by others.

2018-03-05 17:24 UTC, staubina approved these changes
:shipit:

2018-03-05 17:24 UTC, staubina commented
Just a quick reminder to please squash commits before merging.

2018-03-05 17:31 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +                    response = site.siteconfiguration.discovery_api_client.catalog_query.contains.get(
Sorry I didn't think of this earlier, does discovery_api_client.catalog_query not do some smart looking up of results against the cache? it seems like '_identify_uncached_product_identifiers' might be something that the catalog query should be handling internally. thoughts?

2018-03-05 17:32 UTC, Mjloturco reviewed
Just one last comment, Also I believe merging this is blocked until the discovery side is in place, is that correct?

2018-03-05 17:37 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +                    response = site.siteconfiguration.discovery_api_client.catalog_query.contains.get(
As far as I know the rest of our API hits (in ecommerce at least) are preceded by an explicit cache check, suggesting that the client doesn't have a smart lookup. For this endpoint in particular it would be even less safe to assume that the smart lookup happens, because it would be dependent, I believe, on the request body being the same (i.e the catalog_query as well as the list of run ids and course uuids). Because we want to be able to cache data about the individual courses and runs so that future requests are more likely to hit the cache rather than pinging discovery, I don't believe relying on a smart lookup would be sufficient in this case.

2018-03-05 17:38 UTC, McKenzieW commented
@Mjloturco that is definitely right. We absolutely don't want to make our coupon logic dependent on an API endpoint that does not yet exist.

2018-03-05 17:45 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +                    response = site.siteconfiguration.discovery_api_client.catalog_query.contains.get(
Cool if thats our general practice for now I say lets :shipit: (when unblocked). Might be worth an architecture chat at somepoint, It seems like in general dealing with caching should be handled in the api_client, which would help us ensure we are always using caching on endpoints when available and would abstract a lot of this work out of the individual views.

2018-03-05 17:49 UTC, McKenzieW commented on ecommerce/extensions/offer/models.py
> +                    response = site.siteconfiguration.discovery_api_client.catalog_query.contains.get(
Yeah, very good point. Moving the caching work into the API client would be incredible.

2018-03-05 18:04 UTC, Mjloturco approved these changes

2018-03-05 18:04 UTC, Mjloturco commented on ecommerce/extensions/offer/models.py
> +                    response = site.siteconfiguration.discovery_api_client.catalog_query.contains.get(
Could we make a ticket for that as a techdebt/ecommerce improvement?

2018-03-08 16:00 UTC, staubina requested changes
Some minor comments and a requested change, overall looks good.

2018-03-08 16:00 UTC, staubina commented on ecommerce/extensions/offer/tests/test_models.py
> +        _range = factories.RangeFactory()
Small nit, Why are we naming range starting with an underscore?

2018-03-08 16:00 UTC, staubina commented on ecommerce/extensions/offer/models.py
> +                lines.remove(line)
Modifying an array in a method can be a dangerous habit as the caller of the method might not be expecting it to change in size.  I second @jaebradley here. We should make a copy and return the copy.

2018-03-08 16:03 UTC, McKenzieW commented on ecommerce/extensions/offer/tests/test_models.py
> +        _range = factories.RangeFactory()
mostly just because range is an existing keyword, but I can change it

2018-03-08 16:07 UTC, McKenzieW commented on ecommerce/extensions/offer/tests/test_models.py
> +        _range = factories.RangeFactory()
It does, however, follow the convention that already existed for the other tests in the file, so for consistency I'd either like to remove the underscore from all instances of the variable `_range` or keep them on my newly added instances.

2018-03-08 16:09 UTC, staubina commented on ecommerce/extensions/offer/tests/test_models.py
> +        _range = factories.RangeFactory()
Ok, if it is consistent that is fine with me.

2018-03-08 16:10 UTC, staubina commented on ecommerce/extensions/offer/tests/test_models.py
> +        _range = factories.RangeFactory()
I do not think it is hurting anything.

2018-03-08 16:14 UTC, staubina approved these changes
Squash and :shipit:

2018-03-08 16:35 UTC, merged