stop using deprecated basket single item view
openedx-unsupported/ecommerce pull request #1671
Opened 2018-03-09 06:41 UTC by tasawernawaz

[LEARNER-4428](https://openedx.atlassian.net/browse/LEARNER-4428)

The [`BasketSingleItemView`](https://github.com/edx/ecommerce/blob/4cfb8c902b84af23584f7a535a421781fb5decd7/ecommerce/extensions/basket/views.py#L46) is deprecated and causing database deadlock in ecommerce.

2018-03-14 18:05 UTC, tasawernawaz commented
@McKenzieW Please review this PR as well, this is for removing usage of deprecated view from ecommerce.

2018-03-14 18:11 UTC, McKenzieW approved these changes

2018-03-14 18:15 UTC, tasawernawaz commented
@McKenzieW Do you know why codcov is failing on the PR ?

2018-03-14 18:38 UTC, McKenzieW commented
@tasawernawaz it looks like because the line you updated was in close vicinity to / acted upon by a couple of other lines of code that were already uncovered it's identifying those uncovered lines in the diff
https://codecov.io/gh/edx/ecommerce/compare/bb6f52ac1879fa3027509f259228dd5ce7fe02aa...8c79e6f6100952ce96ea4c5f39bbcdf99ecd3e1f/diff

2018-03-15 11:19 UTC, tasawernawaz commented
@McKenzieW Could you please review this again, I have rmeoved the unused class [`BasketSingleItemView`](https://github.com/edx/ecommerce/blob/4cfb8c902b84af23584f7a535a421781fb5decd7/ecommerce/extensions/basket/views.py#L46).

2018-03-15 13:29 UTC, McKenzieW approved these changes

2018-03-16 04:21 UTC, tasawernawaz commented
@edx/learner-spartans Please review it.

2018-03-16 12:54 UTC, Ayub-Khan commented
I have some concerns that why all we removing all code in this pull request should not we follow a strategy of adding a waffle flag or config model to stop using the single-item basket. and then if its working file remove all the related code. If we move this kinda change to prod and it fails it will cause a lot of problems for learners. Plus It will be a lot to revert if it causes problems. second. with waffle flag or config model aproch we can simply turn the change off if its not working.

2018-03-19 10:46 UTC, Ayub-Khan commented
As we have already removed the usage from platform i think we no longer have any need to use the waffle flag.

2018-03-19 11:20 UTC, Ayub-Khan requested changes

2018-03-19 11:20 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
> -        purchase_info = request.strategy.fetch_for_product(product)
We want to include this check for all products in multiple item basket.

2018-03-19 11:32 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
> -        purchase_info = request.strategy.fetch_for_product(product)
You will need to check all the products availability. if some product is not available drop that product and start payment process for remaining. if all products are not available log error and return HttpResponseBadRequest(error message). 
Possible Cases could be:
1 unavailable product (Log error and return bad request)
1 available product (No action needed)
many available and many unavailable procucts (Log warnings for unavailable products and move forward with available products)
all available products  (no action needed)
all unavailable products (log error and return bad request)

2018-03-19 11:42 UTC, Ayub-Khan commented
also have a look at prepare_basket method you might have to update that too .

2018-03-20 12:44 UTC, tasawernawaz commented on ecommerce/extensions/basket/views.py
> -        purchase_info = request.strategy.fetch_for_product(product)
Updated

2018-03-20 14:03 UTC, staubina commented
I think we can ignore this codecov failure.  Once you get approval @tasawernawaz from @Ayub-Khan I think we can merge this PR.

2018-03-20 14:03 UTC, staubina commented
It looks like the Codecov is reporting an overall decrease in the % of covered code because you are deleting code, but your changes are 100% covered.

2018-03-20 14:09 UTC, McKenzieW commented
Although it is not a newly uncovered line of code, it might be useful to add a test for [this line](https://codecov.io/gh/edx/ecommerce/compare/5ff8e61795627e2f1700a2aad24f4b4281364273...74ded71bafa5099fdc8e739fd2387cbfc726d256/diff#D7-21) so as to increase coverage and simplify the process of merging this PR.

2018-03-20 14:25 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
>  class BasketMultipleItemsView(View):
As this class not handles single items baskets too we need to update its name and description.

2018-03-20 14:29 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
> +        # check availability of products
*Optional* double check this functionality using sandbox as we have recently seen some students placing orders for expired course seats.
If you think it is out of the scope just ignore this we can come back to it after this is done.

2018-03-21 09:22 UTC, tasawernawaz commented on ecommerce/extensions/basket/views.py
> +        # check availability of products
@Ayub-Khan Do we have ticket to investigate "orders for expired course seats." ? If not please create one, after this got merged. I will look into that.

2018-03-21 09:23 UTC, tasawernawaz commented
@Ayub-Khan I have added jasmine test to fix code coverage issue. Also refactored as you requested. Please review again when you have time.

2018-03-21 09:35 UTC, Ayub-Khan commented on ecommerce/extensions/basket/views.py
> +        # check availability of products
ok

2018-03-21 11:08 UTC, Ayub-Khan approved these changes

2018-03-21 11:08 UTC, Ayub-Khan commented
:+1:

2018-03-21 11:09 UTC, merged