WIP- Update Email Templates for Bulk Enrollment Purchases
openedx-unsupported/ecommerce pull request #1675
Opened 2018-03-13 17:31 UTC by asadiqbal08

**Work in progress**

I will update the sandbox tomorrow to verify the actual email.

<img width="587" alt="screen shot 2018-03-13 at 6 30 53 pm" src="https://user-images.githubusercontent.com/7334669/37358879-05a8f948-270e-11e8-9463-7b58e86bb819.png">

@rrakhshan @georgebabey @zubair-arbi  FYI
##### NOTE : Need to update the message related to coupon expiration

2018-03-14 11:25 UTC, zubair-arbi requested changes
Generally changes looks good.

2018-03-14 11:25 UTC, zubair-arbi commented on ecommerce/templates/customer/emails/commtype_order_with_csv_body.html
> +                        <li>{% blocktrans %}Download and save the <a href="{{download_csv_link}}">enrollment code file.</a>{% endblocktrans %}</li>
Please move the complete anchor tag `<a href="{{download_csv_link}}">` to translation placeholder.

2018-03-16 07:36 UTC, asadiqbal08 commented
@zubair-arbi take another look. 
@georgebabey your thoughts on it ? It is ready for review.

2018-03-16 07:48 UTC, saleem-latif reviewed
Please deploy this to sandbox and add testing instructions.

2018-03-16 07:48 UTC, saleem-latif commented on ecommerce/templates/customer/emails/commtype_order_with_csv_body.html
> +                        <li>{% blocktrans with link_start='<a href="' link_middle='">' link_end='</a>'%}Download and save the {{ link_start }}{{ download_csv_link }}{{ link_middle }} enrollment code
I think you combine these three placeholders into one.
```
{{ link_start }}{{ download_csv_link }}{{ link_middle }}
```
into 
```
{{link_start}}
```

2018-03-16 07:48 UTC, saleem-latif commented on ecommerce/templates/customer/emails/commtype_order_with_csv_body.html
> +                    <p>{% blocktrans with link_start='<a href="' link_middle='">' link_end='</a>' %}To view your payment information, log in to see your Order History, under {{ link_start }}{{order_h
same as above `{{ link_start }}{{order_history_url}}{{ link_middle }}` can be combined into one

2018-03-16 07:51 UTC, asadiqbal08 commented on ecommerce/templates/customer/emails/commtype_order_with_csv_body.html
> +                        <li>{% blocktrans with link_start='<a href="' link_middle='">' link_end='</a>'%}Download and save the {{ link_start }}{{ download_csv_link }}{{ link_middle }} enrollment code
I tried it before but it was not making the href URL correctly.

2018-03-16 08:04 UTC, saleem-latif commented on ecommerce/templates/customer/emails/commtype_order_with_csv_body.html
> +                        <li>{% blocktrans with link_start='<a href="' link_middle='">' link_end='</a>'%}Download and save the {{ link_start }}{{ download_csv_link }}{{ link_middle }} enrollment code
you can use `add` filter to concatenate strings.

ref: https://stackoverflow.com/questions/4386168/how-to-concatenate-strings-in-django-templates
```
{% with "shop/"|add:shop_name|add:"/base.html" as template %}
```

2018-03-16 08:10 UTC, asadiqbal08 commented
@saleem-latif It is deploying on sandbox but due to some configurations issue as discussed on [ENT-913](https://openedx.atlassian.net/browse/ENT-913) Emails are not sending properly.

2018-03-16 08:12 UTC, asadiqbal08 commented on ecommerce/templates/customer/emails/commtype_order_with_csv_body.html
> +                        <li>{% blocktrans with link_start='<a href="' link_middle='">' link_end='</a>'%}Download and save the {{ link_start }}{{ download_csv_link }}{{ link_middle }} enrollment code
any particular advantage to use it over the mine ?

2018-03-16 09:17 UTC, saleem-latif commented on ecommerce/templates/customer/emails/commtype_order_with_csv_body.html
> +                        <li>{% blocktrans with link_start='<a href="' link_middle='">' link_end='</a>'%}Download and save the {{ link_start }}{{ download_csv_link }}{{ link_middle }} enrollment code
It will reduce the probability of translation related mistakes made by the translaters.

2018-03-16 10:47 UTC, saleem-latif approved these changes

2018-03-20 18:12 UTC, brittneyexline reviewed
looks like a good start from looking at the code. however, I noticed there aren't any changes to the actual csv file - part of the requirements for the ticket were to add some additional blank columns to the csv to make it more usable. will those changes happen in this PR or another one?

2018-03-21 08:37 UTC, asadiqbal08 commented on ecommerce/coupons/views.py
> +        voucher_field_names = ('Code', 'Redemption URL', 'Name Of Employee', 'Date Of Distribution', 'Employee Email')
@brittneyexline Do you mean that blank columns ? I added up.

2018-03-21 15:50 UTC, brittneyexline approved these changes

2018-03-26 10:06 UTC, asadiqbal08 commented
@georgebabey please review it.

2018-03-26 13:45 UTC, merged