disable refund admin page
openedx-unsupported/ecommerce pull request #1701
Opened 2018-04-03 11:48 UTC by ahsan-ul-haq

LEARNER-4681

2018-04-04 14:48 UTC, staubina approved these changes
The changes seem straightforward to me.

2018-04-04 14:48 UTC, staubina commented
We should have at least one more reviewer on this PR.

2018-04-04 16:07 UTC, Ayub-Khan approved these changes
LGTM

2018-04-05 09:28 UTC, Ayub-Khan requested changes

2018-04-05 09:28 UTC, Ayub-Khan commented on ecommerce/conf/locale/en/LC_MESSAGES/django.po
> -"Report-Msgid-Bugs-To: openedx-translation@googlegroups.com\n"
Im not sure why those are being removed, but put them back. 'Report-Msgid-Bugs-To: openedx-translation@googlegroups.com\n'

2018-04-05 09:28 UTC, Ayub-Khan commented on ecommerce/conf/locale/en/LC_MESSAGES/djangojs.po
> -"Report-Msgid-Bugs-To: openedx-translation@googlegroups.com\n"
Im not sure why those are being removed, but put them back. 'Report-Msgid-Bugs-To: openedx-translation@googlegroups.com\n'

2018-04-05 11:24 UTC, Ayub-Khan approved these changes

2018-04-05 11:49 UTC, merged