LEARNER-4968: Do not call any segment events when Calculating the basket
openedx-unsupported/ecommerce pull request #1715
Opened 2018-04-13 16:33 UTC by jlajoie

2018-04-13 19:18 UTC, robrap commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
This all looks great.  However, I had discussed with @BenjiLee adding a required field to `track_segment_event` for skipping the event tracking.  He had that code started locally.  What happened to it?

Also, what about the rest of the calls to `track_segment_event`?

2018-04-13 19:20 UTC, staubina commented on ecommerce/extensions/basket/models.py
> +        if line.stockrecord.price_excl_tax > 0 and not temporary_basket:
👍

2018-04-13 19:21 UTC, staubina approved these changes
I like this approach a lot better. Thanks for taking another swing at this.

2018-04-13 19:39 UTC, jlajoie commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
I'm not sure I like that approach, it seems a bit on the code smell side of things and we could just not call it if we don't want it, instead of adding the line and then saying "no"?

2018-04-13 20:50 UTC, robrap commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
@jlajoie: Agreed that this isn't ideal, but I think it solves the following problem.

I add some code and I want to add an event so I copy the line:
```
track_segment_event(self.site, self.owner, 'Product Added', properties)
```
Then I update the event, and I never realize that there are certain odd circumstances in which I don't want to track the event and I have introduced difficult to find bugs.

Or, I copy a line like:
```
track_segment_event(self.site, self.owner, 'Product Added', properties, is_temporary_basket)
```
And my new code doesn't yet have `is_temporary_basket` so I need to read up on what it is and how it gets used and I don't introduce a difficult to find bug.

If you have another proposal that solves this problem, that would be great.  Note that is why I wanted to revive the code that @BenjiLee and I wrote together, because we added `is_temporary_basked` (or something like that) as a required parameter with a doc string that explained the reasoning above.

2018-04-17 13:09 UTC, staubina commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
@robrap I believe that the above change would mix concerns. track_segment_event is a clear method that should be left as it is.  

The approach here seems cleaner because it does not cross concerns.

2018-04-17 13:11 UTC, staubina commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
We should potentially talk about this in person.

2018-04-17 13:12 UTC, staubina commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
@robrap Also `is_temporary_basket` is added to the options within this PR when the method add_product is called.

https://github.com/edx/ecommerce/pull/1715/files#diff-ae237e82e578ba8c25c0917a33381619R355

2018-04-17 13:31 UTC, robrap commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
@staubina @jlajoie: I don't love my solution, but I haven't heard an alternate solution to the problem I stated.

The main problem is that it is and will be way too easy to introduce a bug.

It is also possible to rename `is_temporary_basket` to `skip_event_tracking` or `mute_event_tracking`.  In either case, the docs will need to clear up why that parameter exists and how it should be used.

I am open to an alternate solution...since as I said...I don't love this one.

2018-04-17 16:20 UTC, jlajoie commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
@robrap I guess maybe I'm missing what problem we're trying to solve here? Following the example above, we'd add the line, pass in false for `is_temporary_basket` because we want to get events persisted, and then we'd be in the same boat as today. The developer would have to ask themselves "Do I want to add an event here", but instead of deciding whether or not to add the call at all, you now need to decide whether or not to set a boolean.

My understanding is that we ran into this issue with the segment events because we were always emitting these events in add_products when we actually didn't want to be. So this isn't really a problem with the event_tracking, but rather us calling a method when we shouldn't have, and us missing that case. 

I just have a hard time advocating for explicitly calling a method, but then passing in a parameter for that method to both return nothing and do nothing.

I think before you mentioned potentially using the request cache to mute events. If it would be something to suppress ALL events, despite feeling a bit of a hack, I think that approach of setting a context global makes more sense than specifying whether they're muted at the method call level, if that's the route we'd want to go.

2018-04-17 17:42 UTC, BenjiLee commented on ecommerce/extensions/basket/models.py
>              track_segment_event(self.site, self.owner, 'Product Added', properties)
So, it looks like I forgot to also handle flush() which also sends a tracking event that we dont want to be sending in basket calculate. https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/basket/models.py#L50

Unfortunately, we will not be able to use this approach.

2018-04-17 19:54 UTC, BenjiLee commented
Attempting to implement request caching in a separate PR which should make handling the flush call easier.

2018-04-18 14:03 UTC, BenjiLee requested changes
Blocked on self

2018-05-04 12:34 UTC, robrap commented
@BenjiLee: I'm going to close this.  We can reopen or create a new one when we have something that will work.

2018-06-04 14:56 UTC, BenjiLee commented
Closed in favor of https://github.com/edx/ecommerce/pull/1786

2018-06-04 14:56 UTC, closed without merging