(WIP) WL-1541 | Test cases for whitelabel journal.
openedx-unsupported/ecommerce pull request #1718
Opened 2018-04-17 09:54 UTC by hasnain-naveed

2018-05-15 13:56 UTC, hasnain-naveed commented
@ziafazal

2018-05-16 09:06 UTC, ziafazal requested changes
@hasnain-naveed completed first round of review. See inline comments.

2018-05-16 09:06 UTC, ziafazal commented on ecommerce/journal/api/tests/test_views.py
> +    path = None
nit:Do need these variables here assuming they are initialized in `setUp` of test class.?

2018-05-16 09:06 UTC, ziafazal commented on ecommerce/journal/api/tests/test_views.py
> +    def test_update_journal_product(self):
I think we should have a test case for product create with valid and invalid data.

2018-05-16 09:06 UTC, ziafazal commented on ecommerce/journal/api/tests/test_views.py
> +        product_class = ProductClassFactory(name="Journal")
I think instead of using these Factory classes for product, productclass, StockRecord and productattribute we should use `journal:api:v1` endpoint to create journal.

2018-05-16 09:06 UTC, ziafazal commented on ecommerce/journal/api/tests/test_serializers.py
> +class AttributesSerializerTest(TestCase):
I'm wondering do we really need test cases for `Serializers`?. i think those should be covered with test cases written for views.

2018-05-16 09:06 UTC, ziafazal commented on ecommerce/journal/tests/test_views.py
> +    def test_get(self, mock_journal_endpoint):
Should have get test with a scenario where we don't have any offers.

2018-05-16 09:06 UTC, ziafazal commented on ecommerce/journal/tests/test_views.py
> +class JournalOfferListViewTests(ViewTestMixin, TestCase):
Why we don't have offer create/update related test cases?

2018-05-16 10:27 UTC, hasnain-naveed commented on ecommerce/journal/api/tests/test_views.py
> +    path = None
removed.

2018-05-16 10:33 UTC, hasnain-naveed commented on ecommerce/journal/api/tests/test_views.py
> +    def test_update_journal_product(self):
added

2018-05-16 10:33 UTC, hasnain-naveed commented on ecommerce/journal/tests/test_views.py
> +    def test_get(self, mock_journal_endpoint):
added

2018-05-16 10:37 UTC, hasnain-naveed commented on ecommerce/journal/api/tests/test_serializers.py
> +class AttributesSerializerTest(TestCase):
I think, the main purpose of unit tests is to test each module of code separately. If you still think, that's not the case then I can remove these test cases.

2018-05-17 09:00 UTC, hasnain-naveed commented on ecommerce/journal/tests/test_views.py
> +class JournalOfferListViewTests(ViewTestMixin, TestCase):
added

2018-05-17 09:00 UTC, hasnain-naveed commented on ecommerce/journal/api/tests/test_views.py
> +        product_class = ProductClassFactory(name="Journal")
used the endpoint

2018-05-17 09:42 UTC, ziafazal requested changes
@hasnain-naveed thanks for the update there is still some room for improvement.

2018-05-17 09:42 UTC, ziafazal commented on ecommerce/journal/api/tests/test_views.py
> +        self._login_staff_user()
It appears you need a user session in all of these test cases. I think we should add these 
```
user = self.create_user(is_staff=True)
self.client.login(username=user.username, password=self.password)
```
in `setUp` and remove this method `_login_staff_user `

2018-05-17 09:42 UTC, ziafazal commented on ecommerce/journal/api/tests/test_views.py
> +        product = Product.objects.get(id=self.product.id)
I think you should use journal list view to get journal products instead of getting them directly from database

2018-05-17 09:42 UTC, ziafazal commented on ecommerce/journal/api/tests/test_views.py
> +        self.assertEqual(Product.objects.get(id=self.product.id).title, product_title)
I think we should assert an HTTP invalid request status 400 instead of comparing product titles

2018-05-17 11:23 UTC, ziafazal approved these changes
👍

2018-05-17 13:27 UTC, bill-filler approved these changes
nice work @hasnain-naveed

2018-05-17 13:27 UTC, merged