Added is_anonymous parameter to the calculate URL
openedx-unsupported/ecommerce pull request #1720
Opened 2018-04-18 14:04 UTC by staubina

[LEARNER-4913]

Add in check for the is_anonymous URL parameter.  If it is not present we will treat the request as if there were a username.

2018-04-19 14:41 UTC, robrap requested changes
Thanks @staubina.  Some of my requests assume a 2 phase roll-out:
1. Add new functionality for parameter.
2. In a future PR, clean-up old code for MARKETING_USER.

We can discuss if you don't agree or have questions.  Thanks.

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        self._login_as_user(MARKETING_USER, is_staff=True)
I'd no longer include the MARKETING_USER for this test.  We want this to work for any user passing the is_anonymous param.

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        mock_calculate_basket.return_value = expected
Oops.  Nice.  :)

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
>          # Check that a being logged in as a different user doesn't hit the cache
Instead of updating this, I'd delete this whole case.  I don't think it applies any more.  It used to be checking that the caching only worked for marketing_site_worker, but not other users.  However, that is no longer the case.  Now it should work for any user with the is_anonymous flag.

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +    def test_no_user_anonymous_params_log(self, mock_calculate_basket, mocked_logger):
Rename to `test_no_query_params_log`

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        response is not invalid.
Can you add something like the following:
```
NOTE: This is temporary until we no longer have these calls and can ultimately return a 400 error.
Due to backward incompatibility, we should make the switch to a 400 error once we need a version change.
```

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        self._login_as_user(MARKETING_USER, is_staff=True)
I think we want something different in the following two cases:
- For marketing_site_worker, the code should continue to work as-is, i.e., acting as if you sent is_anonymous.
- For all other users, the code should continue to work as-is, i.e., acting as if you sent  username=user.username? 

Given this, I think we still temporarily want to support the `MARKETING_USER` special case in the code for now.

Once everything is working as planned, we can remove this code.

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        Verify that when the request contains both a username parameter and a is_anonymous a Bad Request response
I made some minor tweaks:
```
Verify that when the request contains both a username and an is_anonymous parameter, a Bad Request response
is returned.
```

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
> -    MARKETING_USER = 'marketing_site_worker'
I think we may still want this.  See my test related comment.

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
> +        elif is_anonymous:
May want this to be something like:
```
elif is_anonymous OR user.username == self.MARKETING_USER:
    if not is_anonymous:
        logger.warning('Request to Basket Calculate by marketing_site_worker without any parameter.')
    ...
```

2018-04-19 14:41 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
> +                'Request to Basket Calculate must supply either username or is_anonymous query param [%s]',
`Request` => `Requests`.  Also, I'd fix the message a little like:
```
        logger.warning(
                'Request to Basket Calculate must supply either username or is_anonymous query param. Requesting user=[%s]',
                user.username
        )
```

2018-04-19 18:16 UTC, staubina commented
@robrap Please take another look when you have a moment.

2018-04-20 05:04 UTC, robrap requested changes
Thanks @staubina.

2018-04-20 05:04 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +            Logs in the Marketing User, required along with the is_anonymous parameter for anonymous
Fix message.  No longer logs in the marketing user.

2018-04-20 05:04 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        # Note: This and the following checks related to is should be removed once we remove
Typo: `related to is should`
Can we change this to a `TODO: LEARNER-XXXX: ..." comment after creating a new ticket for this clean-up?

2018-04-20 05:04 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        response is not invalid.
`response is valid`

2018-04-20 05:04 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        url_with_one_sku = self._generate_sku_url(self.products, number_of_products=1)
This is where we have two cases, right?
- No parameters and Marketing user => anonymous
- No parameters and a different user => username=user.username

2018-04-20 05:04 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
> +            # the marketing user. The check for the marketing user is being left until usage
Delete `the marketing user.`.
Maybe add `TODO: LEARNER-XXXX: ...` for clean-up story.

2018-04-20 05:04 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
> -            is_anonymous = True
This line should have been left alone.  This whole case is about making it anonymous.

2018-04-20 05:04 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
> +                logger.warning('Request to Basket Calculate by marketing_site_worker without any parameter.')
FYI: We _might_ need logger.error.  Let's see what we determine based on the PR we are trying to get to Prod.  I wasn't able to see log messages, and not sure why yet.

2018-04-20 12:12 UTC, staubina commented on ecommerce/extensions/api/v2/views/baskets.py
> -            is_anonymous = True
It is more explicit the way it is now.  I set is_anonymous to True if it is not already true on line 448 right above here. Right after logging that we are checking for the marketing_site_worker.

2018-04-20 12:23 UTC, staubina commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        url_with_one_sku = self._generate_sku_url(self.products, number_of_products=1)
This was added to trigger this code path explicitly

```
        if not username and not is_anonymous:
            logger.warning(
                ('Request to Basket Calculate must supply either username or '
                 'is_anonymous query param. Requesting user=[%s]'),
                user.username
            )
```

2018-04-20 12:43 UTC, staubina commented
@robrap Please take another look.

2018-04-21 00:26 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
>              is_anonymous = True
@staubina: I understand your earlier comment now about this.  I made this its own if statement to make it even more clear.

Also, I removed the log message here, because this case will already have a log message from one of the cases above.

2018-04-23 14:37 UTC, robrap approved these changes

2018-04-23 15:06 UTC, merged