Fix for https://openedx.atlassian.net/browse/LEARNER-4765
openedx-unsupported/ecommerce pull request #1725
Opened 2018-04-20 10:42 UTC by raeeschachar

2018-04-21 13:53 UTC, raeeschachar commented
@robrap @staubina 
Please review. This fixes the Credit Card payment issue. Will be pushing another PR for Paypal fix later. Idea here is to merge this in as soon for payment coverage, as discussed. 
results: https://tools-edx-jenkins.edx.org/job/e2e/job/stage-ecommerce/395/console

2018-04-21 14:22 UTC, robrap requested changes
Thanks Raees. Don’t forget to take a break as well. 🙂

2018-04-21 14:22 UTC, robrap commented on ecommerce/extensions/order/migrations/0015_create_disable_repeat_order_check_switch.py
> +    Switch.objects.get_or_create(name=DISABLE_REPEAT_ORDER_CHECK_SWITCH_NAME, defaults={'active': True})
Migrations should be considered semi-permanent. Assume many environments have already run an existing migration. I think you want to add a new migration. You can use a similar name, but call it “update” instead of “create”. 

A couple of other thoughts about this:
1. We need to ensure we won’t break any environments by turning this on, especially prod, and including open source. If this flag is still required, we may need to first check that someone didn’t set it to False in an environment before changing its default. I don’t think we can get this from the model. Changing defaults is complex.
2. Is it possible that this was meant to be a temporary flag for rollout? I do not know its history. If it was meant to be temporary, the much simpler and better solution would be cleaning up this flag and all of its code.

2018-04-21 14:26 UTC, robrap commented on ecommerce/extensions/order/migrations/0015_create_disable_repeat_order_check_switch.py
> +    Switch.objects.get_or_create(name=DISABLE_REPEAT_ORDER_CHECK_SWITCH_NAME, defaults={'active': True})
Actually, we should leave this decision and code to a separate PR. Since you manually turned this on in Stage, I don’t think you need this for Stage e2e. We will want to figure this out, but I’d separate it out to a separate PR and/or story.

2018-04-21 14:43 UTC, raeeschachar commented on ecommerce/extensions/order/migrations/0015_create_disable_repeat_order_check_switch.py
> +    Switch.objects.get_or_create(name=DISABLE_REPEAT_ORDER_CHECK_SWITCH_NAME, defaults={'active': True})
@robrap 
Makes sense. I will remove the flag part from this PR and keep the flag active for stage. 
Resting too after this :smile:

2018-04-21 14:54 UTC, raeeschachar commented
@robrap Done. 
https://tools-edx-jenkins.edx.org/job/e2e/job/stage-ecommerce/396/console
Feel free to review on Monday. Happy weekend :)

2018-04-21 15:33 UTC, robrap approved these changes
When you have a green build AND the Jenkins run against this branch passes, feel free to merge.

2018-04-21 15:33 UTC, robrap commented on e2e/test_payment.py
> -    def checkout_with_paypal(self, selenium):
Is this a function we should have deleted earlier with the initial delete?

2018-04-21 15:33 UTC, robrap commented on e2e/test_payment.py
> +            self.refund_orders_for_course_run(course_run_key)
Does refund need an assertion.

2018-04-22 02:27 UTC, robrap commented on e2e/test_payment.py
> +    def test_verified_seat_payment_with_credit_card(self, selenium):
One last thing. It may make sense to add a comment that states that this test requires that flag to be turned on.

2018-04-23 07:28 UTC, raeeschachar commented on e2e/test_payment.py
> -    def checkout_with_paypal(self, selenium):
Yes, I was trying to fix this so both tests can be merged together that is why it is here.

2018-04-23 08:49 UTC, raeeschachar commented on e2e/test_payment.py
> +    def test_verified_seat_payment_with_credit_card(self, selenium):
Done

2018-04-23 09:01 UTC, Ayub-Khan requested changes
As this run through the jenkins job and jenkins job creates a new ecommerce environment and after that injects the stage credentials and variable to configure it with stage. Its not actual copy of stage. Which means the switches have the default value set by the code. This will fail. To correct the behavior we will have to set the default value of 'disable_repeat_order_check' True.

2018-04-23 09:18 UTC, Ayub-Khan commented on ecommerce/extensions/order/migrations/0015_create_disable_repeat_order_check_switch.py
> +    Switch.objects.get_or_create(name=DISABLE_REPEAT_ORDER_CHECK_SWITCH_NAME, defaults={'active': True})
@robrap this flag was created for the e2e tests. To enable e2e buy a single item multiple times.

2018-04-23 09:19 UTC, Ayub-Khan approved these changes
It seems my assumption was not correct. Activating the stage switch passing the test.

2018-04-23 09:28 UTC, merged

2018-04-24 17:31 UTC, BenjiLee commented
https://tools-edx-jenkins.edx.org/job/e2e/job/stage-ecommerce/407
Build is still failing