(WIP) WL-1541 | Coverage PR
openedx-unsupported/ecommerce pull request #1768
Opened 2018-05-18 09:36 UTC by hasnain-naveed

2018-05-18 18:50 UTC, robrap commented
@hasnain-naveed @bill-filler: FYI: As we move forward with the Ecommerce Guild, it would be great if you could point to documentation around decisions made regarding this work.  If that documentation doesn't exist, please expect to do some work to help with knowledge sharing around this.  Thank you!

2018-05-18 19:42 UTC, bill-filler commented
@robrap 
I can be the point person on this. Basically we are introducing a new product type in ecommerce for Journals, which is a Whitelabel project (for now). I will share the spec with you. We'll need to work wiith the Guild (and become members) to get the following feature branch merged after we write sufficient tests. The feature branch is here: https://github.com/edx/ecommerce/tree/whitelabel/journal

2018-05-23 07:31 UTC, ziafazal requested changes
@hasnain-naveed completed first round of review.

2018-05-23 07:31 UTC, ziafazal commented on ecommerce/journal/tests/mixins.py
> +    def _get_mocked_discovery_journal_endpoint(
can we rename this method to `get_mocked_discovery_journal`?

2018-05-23 07:31 UTC, ziafazal commented on ecommerce/journal/tests/mixins.py
> +    def _create_product(self, data=None):
method names in this Mixin start with underscore whereas they are called from outside i think we should remove underscore prefix for these methods.

2018-05-23 07:31 UTC, ziafazal commented on ecommerce/journal/tests/mixins.py
> +class JournalMixin(TestCase):
I think this mixin suppose to provide additional methods to journal test cases it should inherit from `object` and use it in multiple inheritance way.
`class JournalProductViewTests(JournalMixin, TestCase)`

2018-05-23 07:31 UTC, ziafazal commented on ecommerce/journal/fulfillment/tests/test_modules.py
> +    def test_fulfill_product(self, mocked_post_journal_access):     # pylint: disable=unused-argument
why `mocked_post_journal_access ` has been mocked and never used in this test?

2018-05-23 07:31 UTC, ziafazal commented on ecommerce/journal/fulfillment/tests/test_modules.py
> +    def test_fulfill_product_without_attribute(self, mocked_post_journal_access):  # pylint: disable=unused-argument
why `mocked_post_journal_access ` has been mocked and never used in this test?

2018-05-23 07:31 UTC, ziafazal commented on ecommerce/journal/tests/test_benefits.py
> +class EnterpriseAbsoluteDiscountBenefitTests(mixins.BenefitTestMixin, TestCase):
Need to change the name of this test class to `JournalAbsoluteDiscountBenefitTests`.

2018-05-23 07:31 UTC, ziafazal commented on ecommerce/journal/tests/test_benefits.py
> +class EnterprisePercentageDiscountBenefitTests(mixins.BenefitTestMixin, TestCase):
Need to change the name of this test class to `JournalPercentageDiscountBenefitTests`

2018-05-23 09:14 UTC, hasnain-naveed commented on ecommerce/journal/fulfillment/tests/test_modules.py
> +    def test_fulfill_product_without_attribute(self, mocked_post_journal_access):  # pylint: disable=unused-argument
removed.

2018-05-23 09:15 UTC, hasnain-naveed commented on ecommerce/journal/fulfillment/tests/test_modules.py
> +    def test_fulfill_product(self, mocked_post_journal_access):     # pylint: disable=unused-argument
Because `fulfill_product` function is calling the `post_journal_access` function which is responsible for posting data in discovery. Although I have changed it.

2018-05-23 09:16 UTC, hasnain-naveed commented on ecommerce/journal/tests/mixins.py
> +class JournalMixin(TestCase):
I have refactored the `JournalMixin` class.

2018-05-23 10:11 UTC, ziafazal approved these changes
👍

2018-05-23 11:37 UTC, bill-filler approved these changes
looks great!

2018-05-23 11:37 UTC, merged