Journal Integration For Ecommerce
openedx-unsupported/ecommerce pull request #1790
Opened 2018-06-04 17:16 UTC by BessieSteinberg

NOT READY FOR REVIEW

Journal Service Integration for Ecommerce:

2018-06-04 18:10 UTC, robrap commented
@BessieSteinberg: I understand this isn't ready fro review yet.  I want to preemptively ask that documentation in the form of .rst files (as needed) are added as part of this PR.  Thank you.

2018-06-21 17:24 UTC, nedbat commented on ecommerce/journal/forms.py
> +                                                     empty_permitted, instance)
If you don't indent to the opening paren, then lines like this don't have to move when you change the names of things:
```
super(JournalBundleOfferForm, self).__init__(
    data, files, auto_id, prefix, initial, error_class, label_suffix,
    empty_permitted, instance,
)
```

2018-06-21 18:27 UTC, bessiesteinberg commented on ecommerce/journal/forms.py
> +                                                     empty_permitted, instance)
I'll clean that up - Thanks!

2018-06-25 21:32 UTC, jmyatt requested changes

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/core/management/commands/create_or_update_site.py
> +        journals_api_url = options.get('journals_api_url', '')
it might make sense to leave out the default empty string value here, to keep consistent with how discovery_api_url and lms_url_root are handled

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/core/migrations/0046_merge_20180525_1418.py
> +        ('core', '0045_siteconfiguration_journals_api_url'),
Instead of having two # 45 migrations, I think siteconfiguration_journals_api_url should be 0046 and merge_20180525_1418 should be 0047

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/core/tests/test_models.py
> +            urljoin(self.site.siteconfiguration.discovery_api_url, '/journal/api/v1/')
better to import this api path from ecommerce.journal.constants

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/extensions/catalogue/migrations/0031_journal_product_class.py
> +# -*- coding: utf-8 -*-
it looks like there's another 0031 now, so after rebasing from master you'll need to regenerate or rename this one

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/extensions/catalogue/migrations/0031_journal_product_class.py
> +        ('catalogue', '0024_fix_enrollment_code_slug')
for dependencies from this same app, you should just need the one (the migration prior to this one)

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/extensions/catalogue/migrations/0032_merge_20180321_2215.py
> +        ('catalogue', '0030_auto_20180124_1131'),
same as above - 0030 is not needed here since you have 0031 listed

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/extensions/catalogue/migrations/0033_merge_20180620_1551.py
> +        ('catalogue', '0031_course_entitlement_idverifyreq_attr'),
same comment

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/extensions/catalogue/tests/test_models.py
> +        self.assertNotEqual(coupon.is_journal_product, JOURNAL_PRODUCT_CLASS_NAME)
looks like this is comparing a bool to a string.  Did you mean to say:
    
    self.assertNotEqual(coupon.get_product_class().name, JOURNAL_PRODUCT_CLASS_NAME)

or
    
    self.assertFalse(coupon.is_journal_product)

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/extensions/payment/migrations/0019_auto_20180326_1545.py
> +        ),
These 2 changes look like no-ops judging from [django-extensions](https://github.com/django-extensions/django-extensions/blob/3410f6a819a2ac9373d0387ca62c3255260a5e18/django_extensions/db/fields/__init__.py#L339-L371) - is this needed?  There are more instances of these same AlterField statements in your some of your other migrations.  

I do see other instances of similar changes in migrations in ecommerce, so maybe this is fine as is:
* [invoice 0006](https://github.com/edx/ecommerce/blob/master/ecommerce/invoice/migrations/0006_auto_20180228_1057.py#L19-L24)
* [payment 0013](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/payment/migrations/0013_sdncheckfailure.py#L21-L22)

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/extensions/refund/migrations/0005_merge_20180418_1605.py
> +        ('refund', '0004_auto_20180326_1545'),
looks like you just need the second one here

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/api/serializers.py
> +        return instance.attribute.code
I *think* that instead of using SerializerMethodField() for these, you can simply declare them like this:

    name = serializers.CharField(source='attribute.name')
    code = serializers.CharField(source='attribute.code')

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/api/serializers.py
> +        product_class = ProductClass.objects.get(id=product.product_class_id)
doesn't look like you actually need to fetch the ProductClass object - you can just use `product.product_class_id` where you need it in the ProductAttribute query below

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/api/serializers.py
> +        product_attribute = ProductAttribute.objects.get(product_class__id=product_class.id)
this assumes you'll get exactly one item for the filter terms.   Also, you can use `product_class_id` instead of `product_class__id` to avoid a join in the resulting query (since product_class_id exists as a field on the ProductAttribute model). So to avoid that join and to avoid hitting `MultipleObjectsReturned` or `DoesNotExist` exceptions, you should instead use something like:

    product_attributes = ProductAttribute.objects.filter(product_class_id=product.product_class_id)

then you'll need to handle that resulting list in the ProductAttributeValue.objects.create logic below

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/api/v1/views.py
> +    queryset = Product.objects.filter(product_class__name='Journal')
you should import 

    from ecommerce.journal.constants import JOURNAL_PRODUCT_CLASS_NAME

and use the constant here, like you do where you create the ProductClass in migrations/0031_journal_product_class.py

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/client.py
> +        site
pls include data type and description

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/conditions.py
> +class JournalBundleCondition(SingleItemConsumptionConditionMixin, Condition):
pls add class docstring

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/conditions.py
> +        return True
nice job inline-commenting this logic.  Instead of using a class attribute for `self.basket_skus`, it might be clearer to scope that set locally in `is_satisfied`, then pass it to each of `basket_contains_all_required_courses` and `basket_contains_all_journals`, with those methods returning the altered set. So is_satisfied would have something like:

    basket_skus = set([line.stockrecord.partner_sku for line in basket.all_lines()])
    basket_skus, condition1 = self._basket_contains_all_required_courses(basket_skus)
    if not condition1:
        return False
    basket_skus, condition2 = self._basket_contains_all_journals(basket_skus)
    if not condition2:
        return False

but I dunno - that's kind of clunky.  Maybe simply marking the 2 'contains' functions private (with a leading underscore in the name) and adding a comment in each one (and/or at the top of this class where basket_skus is defined) to note that it is populated within `is_satisfied` would be best.

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/conditions.py
> +        self.basket_skus = set([line.stockrecord.partner_sku for line in basket.all_lines()])
this can be moved to line 134 below, since it's not used until then

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/forms.py
> +            site=self.request.site,
this can just be

    site=site

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/fulfillment/modules.py
> +        """ Return a list of lines that can be fulfilled.
use an empty first line since it's a multi-line docstring

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/fulfillment/modules.py
> +        """ Fulfills the purchase of a 'Journal'
empty first docstring line

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/fulfillment/modules.py
> +    def revoke_line(self, line):
docstring please

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/tests/test_client.py
> +        """ Test 'fetch_journal_bundle'
use an empty first docstring line

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/journal/tests/test_views.py
> +         to apply them """
docstring format

2018-06-25 21:32 UTC, jmyatt commented on ecommerce/referrals/migrations/0005_auto_20180326_1545.py
> +            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
same question from elsewhere on whether this migration is necessary or is a no-op

2018-06-26 14:12 UTC, BessieSteinberg commented on ecommerce/core/management/commands/create_or_update_site.py
> +        journals_api_url = options.get('journals_api_url', '')
Yeah that is a good point - I'll make that change

2018-06-26 15:58 UTC, BenjiLee commented on ecommerce/core/migrations/0046_merge_20180525_1418.py
> +        ('core', '0045_siteconfiguration_journals_api_url'),
I believe these numbers are automatically generated by manage.py makemigrations and are numbered by django app

2018-06-26 16:09 UTC, BenjiLee commented on ecommerce/extensions/test/factories.py
> +from ecommerce.journal.conditions import JournalBundleCondition
I'm confused by the mix of the singular/plural use of Journal/s. I think JournalBundle makes sense, but I see `journals` referenced as plural, but the app name is `journal`.

2018-06-26 16:11 UTC, BenjiLee commented on ecommerce/journal/admin.py
> +# Register your models here.
Do we want any Django Admin entries for Journal/s?

2018-06-26 17:35 UTC, BenjiLee commented on ecommerce/journal/api/serializers.py
> +        fields = ('partner', 'partner_sku', 'price_currency', 'price_excl_tax',)
I noticed in extensions/api/serializers.py we use the same subclassed name for this serializer.

```
class StockRecordSerializer(serializers.ModelSerializer):
    """ Serializer for stock record objects. """

    class Meta(object):
        model = StockRecord
        fields = ('id', 'product', 'partner', 'partner_sku', 'price_currency', 'price_excl_tax',)
```

We should either...
a. Separate journal/s from the main code and keep this serializer if we cannot use the other one. Additionally, we should rename this serializer to be Journal specific
b. Use the already existing serializer

2018-06-26 17:37 UTC, BenjiLee commented on ecommerce/journal/api/serializers.py
> +class StockRecordSerializerForUpdate(StockRecordSerializer):
Same comment as StockRecordSerializer above

2018-06-27 15:59 UTC, BessieSteinberg commented on ecommerce/core/migrations/0046_merge_20180525_1418.py
> +        ('core', '0045_siteconfiguration_journals_api_url'),
With the exception of the `0031_journal_product_class.py`, all of the migrations are auto generated by django.  Would you like me to squash the migrations within each app?

2018-06-27 17:42 UTC, BessieSteinberg commented on ecommerce/journal/api/serializers.py
> +        fields = ('partner', 'partner_sku', 'price_currency', 'price_excl_tax',)
The `StockRecordSerializer` in extensions expects different fields and expects the `partner` field to be in a different format. So I will rename the one for journals

2018-06-27 17:42 UTC, BessieSteinberg commented on ecommerce/journal/api/serializers.py
> +class StockRecordSerializerForUpdate(StockRecordSerializer):
I'll rename it (see comment about `StockRecordSerializer`

2018-06-27 18:13 UTC, jmyatt commented on ecommerce/core/migrations/0046_merge_20180525_1418.py
> +        ('core', '0045_siteconfiguration_journals_api_url'),
Hmm I think the only app's migrations you could safely squash would be `journal` since that's the only new app on this feature branch, but there's not much value in doing that since that app has just the 2 migrations.  I suspect that these issues I'm noticing are due to multiple rebases against master that you've probably done over the life of this branch.  

So although django has created these migrations, we may still have issues like redundant dependencies and (more importantly) incorrect/out-of-order dependencies, which I believe could create migration breakages as soon as this branch is merged.

I think one course to take on this would be:
* remove all migrations from this branch
  * on a clean environment representing master (with the db in the state represnted by master's migrations), switch to this branch and run makemigrations
  * also drop in the 00##_journal_product_class.py migration (at the appropriate number), and make sure its dependency is correct
  * run migrate to apply the new migrations
  * ensure everything looks right runtime, in terms of schema / data
  * then the branch is ready to merge once the rest of the code review is done (assuming there are no new migrations added master in the interim)

Another option would be to manually fix some subset of these issues I've raised to make sure the resulting dependency chain is correct.

I'd welcome input from others on my comments here and existing best practices with migration conflicts (@robrap?)

2018-06-27 18:32 UTC, BessieSteinberg commented on ecommerce/core/migrations/0046_merge_20180525_1418.py
> +        ('core', '0045_siteconfiguration_journals_api_url'),
Thank you for explaining that process!  I'm happy to do that.  I'll deal with these migration inconsistencies last then incase more come up as I'm working on this PR.

2018-06-27 20:55 UTC, BessieSteinberg commented on ecommerce/journal/admin.py
> +# Register your models here.
There aren't any for 'programs' or 'entitlements' so I took that to assume that we haven't really found a need for Django Admin entries for products.  We can add them later if we need them.

Would you like me to delete this file?  It was autogenerated when we created a new Django app, but I can delete it if that would be cleaner.

2018-06-28 13:53 UTC, BessieSteinberg commented on ecommerce/journal/conditions.py
> +        return True
Yeah this is a good point, I opted for the second option because I felt it was more readable.  It's still a little clunky but at least it won't be confusing now :)

2018-06-28 14:12 UTC, BenjiLee commented on ecommerce/journal/admin.py
> +# Register your models here.
I think the custom interface that's been created for Enterprise Offers and Programs Offers replaces the need for the admin interface. This is fine the way it is.

2018-06-29 13:48 UTC, BenjiLee commented
@BessieSteinberg , Just a heads up Jason and I are on PTO for 7/4-7/6

2018-06-29 13:52 UTC, robrap commented on ecommerce/journal/admin.py
> +# Register your models here.
I'd delete the file if it isn't serving any purpose.

2018-06-29 17:24 UTC, jmyatt approved these changes

2018-07-02 20:11 UTC, BenjiLee commented on ecommerce/journals/api/tests/test_serializers.py
> +                categories=""
@BessieSteinberg This is completely up to you whether you want to do this or not.

Looks like we are setting `categories=""` in quite a few places. Should we be subclassing `ProductFactory()` and add `categoriers=""` as a default?

2018-07-02 20:14 UTC, BenjiLee commented on ecommerce/journals/api/tests/test_views.py
> +from ecommerce.journals.tests.mixins import JournalMixin     # pylint: disable=no-name-in-module
Why is this pylint violation occuring? 
Are there ways to resolve this?

2018-07-02 20:38 UTC, BessieSteinberg commented on ecommerce/journals/api/tests/test_views.py
> +from ecommerce.journals.tests.mixins import JournalMixin     # pylint: disable=no-name-in-module
For some reason pylint fails with this error, even though there is a class JournalMixin defined in mixins.py - I am not really sure why but i am looking into it

2018-07-03 18:00 UTC, BenjiLee approved these changes

2018-07-03 18:41 UTC, BenjiLee commented
Note: @BessieSteinberg @jmyatt  and I verified the forwards and backwards migrations offline.  We also set up a journals product locally to confirm this feature's behaviour.

2018-07-03 19:20 UTC, BenjiLee requested changes
@robrap Mentioned we should have asynchronous calls from e-commerce to LMS. This means calls such as the fulfillment call after purchased should be pushed on to a ecom worker. 

Synchronous calls have been a boon to the ecommerce service and we want to stop introducing more of these into ecommerce. Although the merging of this code won't immediately create synchronous calls, we will need to pass these calls to the ecom_worker before enabling journals. To ensure that we have no synchronous calls to other services from ecommerce, the action item here is to create a commited JIRA ticket to pass the synchronous calls (such as fulfillment) to the ecom_worker before turning Journals on.

2018-07-09 17:24 UTC, bill-filler approved these changes
looks good

2018-07-09 17:25 UTC, merged

2018-07-09 19:17 UTC, robrap commented
@BessieSteinberg: I know you were working hard with everyone to get this merged.  I don't think we should get in the habit of merging PRs when a reviewer has a red X "requested changes" outstanding on a PR.  Sounds like it was nearly there, but not sure why the preemptive merge.
FYI: @BenjiLee

2018-07-09 19:46 UTC, BessieSteinberg commented
@robrap My understanding was that the only reason for the X was because I needed to comment everywhere an async call is currently being made and create an associated JIRA task.  Every where that there is an asyc call I have included a comment in the code: ```# TODO: WL-1680: All calls from ecommerce to other services should be async``` 
I was under the impression that it would be fine to merge once that had been done and everything else was passing.

2018-07-09 19:58 UTC, bill-filler commented
I was under the same impression as @BessieSteinberg based on our guild meeting last week. Sorry if we jumped the gun, but thought we'd met the requirements and were hesitant to wait any longer with this huge PR.

2018-07-09 21:40 UTC, robrap commented
@BessieSteinberg @bill-filler: I think as a general rule it is good to get a thumb from someone who requests changes.  If someones gives an Approval with a final comment saying just do X...then I would do what you did.

Also, note that I don't think WL-1680 is what you think it is.
https://openedx.atlassian.net/browse/WL-1680