WIP: Initial fix work for missing id_verification_required attr
openedx-unsupported/ecommerce pull request #1796
Opened 2018-06-08 17:51 UTC by staubina

This is an early stage WIP PR for context and discussion.

2018-06-08 20:20 UTC, BenjiLee requested changes

2018-06-08 20:20 UTC, BenjiLee commented on ecommerce/extensions/catalogue/migrations/0031_course_entitlement_idverifyreq_attr.py
> +
Include the reverse migration.

https://github.com/edx/ecommerce/blob/2d2760cd94118e18529306b5cb08933d3c2b3821/ecommerce/extensions/catalogue/migrations/0019_enrollment_code_idverifyreq_attribute.py#L25-L28

2018-06-08 20:20 UTC, BenjiLee commented on ecommerce/extensions/catalogue/migrations/0031_course_entitlement_idverifyreq_attr.py
> +        migrations.RunPython(create_idverifyreq_attribute)
Add the reverse migration function here.
https://github.com/edx/ecommerce/blob/2d2760cd94118e18529306b5cb08933d3c2b3821/ecommerce/extensions/catalogue/migrations/0019_enrollment_code_idverifyreq_attribute.py#L38

2018-06-08 20:55 UTC, BenjiLee commented on ecommerce/extensions/checkout/views.py
>      def get_order_verification_context(self, order):
@robrap  and I have a suggested refactor.
```
    def get_order_verification_context(self, order):
        context = {}
        request = self.request
        site = request.site

        # NOTE: Only display verification and credit completion details to the user who actually placed the order.
        if request.user != order.user:
            return context
    
        for line in order.lines.all():
            product = line.product

            user_verification_required = \
                getattr(product.attr, 'id_verification_required', False) and \
                (getattr(product.attr, 'course_key', False) or getattr(product.attr, 'UUID', False))
            
            if user_verification_required:
                context.update({
                    'verification_url': site.siteconfiguration.build_lms_url('verify_student/reverify'),
                    'user_verified': request.user.is_verified(site),
                })
                break

        return context
```

2018-06-08 20:59 UTC, BenjiLee commented on ecommerce/extensions/checkout/views.py
>      def get_order_verification_context(self, order):
We renamed `get_and_maybe_update_order_verification_context`

2018-06-11 11:58 UTC, staubina commented on ecommerce/extensions/checkout/views.py
>      def get_order_verification_context(self, order):
I am not a fan of this method name change.  I prefer what it currently is named.

2018-06-11 13:05 UTC, BenjiLee commented on ecommerce/extensions/checkout/views.py
>      def get_order_verification_context(self, order):
`get_order_verification_context` is misleading as there is an update. Do you have a better suggestion to more closely reflect what this method is doing?

2018-06-11 15:44 UTC, staubina commented on ecommerce/extensions/checkout/views.py
>      def get_order_verification_context(self, order):
This is more or an update than a get so does one of the following work for you?

get_updated_order_verification_context

update_order_verification_context

2018-06-11 16:06 UTC, BenjiLee commented on ecommerce/extensions/checkout/views.py
>      def get_order_verification_context(self, order):
Talked offline with @staubina. This method is ONLY doing a get for a context.

2018-06-14 19:07 UTC, bessiesteinberg approved these changes

2018-06-15 20:52 UTC, BenjiLee approved these changes

2018-06-20 12:12 UTC, merged