Added update order line partner management command.
openedx-unsupported/ecommerce pull request #1824
Opened 2018-06-25 12:34 UTC by waheedahmed

LEARNER-5608

2018-06-25 12:35 UTC, waheedahmed commented
@edx/learner-spartans, @staubina Please review.

2018-06-25 17:27 UTC, staubina commented on ecommerce/extensions/order/management/commands/update_order_lines_partner.py
> +        OrderLine.objects.filter(partner_sku__in=skus).update(partner=partner, partner_name=partner.name)
Can you add to this filter to exclude order lines that already have the correct partner?

2018-06-25 17:29 UTC, staubina requested changes
Can we also add a step that will output how many lines will be updated and ask the user to confirm the operation?  

I could imagine the user running this command without realizing the impact and potential performance implications.

2018-06-26 14:10 UTC, waheedahmed commented
@staubina I have added the request changes kindly take another look.

2018-06-27 11:54 UTC, raeeschachar approved these changes

2018-06-27 13:58 UTC, staubina commented on ecommerce/extensions/order/management/commands/prompt.py
> +    if default is None:
I feel like this conditional block could be reduced to something like 

```
if default is None or default in valid.keys():
  prompt = " [y/n] "
else:
  raise ValueError("invalid default answer: '%s'" % default)
```

2018-06-27 14:01 UTC, staubina commented on ecommerce/extensions/order/management/commands/prompt.py
> +            sys.stdout.write("Please respond with 'yes' or 'no' (or 'y' or 'n').\n")
I would consider using the valid.keys() here to set the valid answers to protect against copy and paste errors.

2018-06-27 14:01 UTC, staubina commented on ecommerce/extensions/order/management/commands/prompt.py
> +        "ye": True,
Is ye a typo?

2018-06-27 14:02 UTC, staubina requested changes
Some recommendations on the new code.

Thank you for taking my requested changes into account.

2018-06-27 16:13 UTC, robrap commented on ecommerce/extensions/order/management/commands/tests/test_update_order_lines_partner.py
> +    def test_update_order_lines_partner(self):
You could use ddt and pass in `yes_no_value` as True/False to remove duplicate code with test above.

Not a blocker, but please clean up while here.  Thanks.

2018-06-28 09:57 UTC, waheedahmed commented on ecommerce/extensions/order/management/commands/prompt.py
> +    if default is None:
@staubina We this conditional block is setting capital Y or N based on default value so that user can know the default value and respond accordingly.

2018-06-28 10:25 UTC, waheedahmed commented on ecommerce/extensions/order/management/commands/tests/test_update_order_lines_partner.py
> +    def test_update_order_lines_partner(self):
Done.

2018-06-28 10:43 UTC, waheedahmed commented
@staubina @robrap I have addressed your comments, kindly take another look.

2018-06-29 12:59 UTC, staubina commented on ecommerce/extensions/order/management/commands/prompt.py
> +    if default is None:
I would consider adjusting this then and only having the defaulted value in the brackets rather than the capitalized letter.

2018-06-29 13:00 UTC, staubina approved these changes
One minor comment that is not a blocker.  This PR is ready to merge.

2018-06-29 13:35 UTC, robrap commented
FYI: I don't plan on doing a full review.  Don't wait on me. :)

2018-06-29 13:40 UTC, raeeschachar commented
Thanks for the heads up. A fyi, Waheed will be out till Monday, I wouldn't expect a reply back till Tuesday.

2018-07-03 09:50 UTC, waheedahmed commented
@staubina I have updated the PR, please merge it.

2018-07-05 14:27 UTC, merged