Added backoff decorator
openedx-unsupported/ecommerce pull request #1827
Opened 2018-06-26 11:46 UTC by irfanuddinahmad

Description: 
There were 8876 errors in the logs due to 
File "/edx/app/ecommerce/ecommerce/ecommerce/enterprise/conditions.py", line 44, in is_satisfied
The exponential backoff and retry for exceptions in this function should reduce the connection failures

Test instructions:
Monitor the splunk logs and verify reduction in monthly error rate

2018-06-26 12:18 UTC, zubair-arbi commented on ecommerce/enterprise/conditions.py
> +    @backoff.on_exception(backoff.expo,
use this decorator specifically on line 
```python
learner_data = fetch_enterprise_learner_data(basket.site, basket.owner)['results'][0] 
```
as this method catches the exceptions `except (ConnectionError, KeyError, SlumberHttpBaseException, Timeout):` also this will avoid use logging exception each time when error occurs. We have to log just once for after using all retries.

Also I think 60 sec time is too much, maybe we can set it to 30 sec as this method is called on basket page to determines if a user is eligible for an enterprise customer offer based on their association with the enterprise customer. @georgebabey what is your suggestion.

Also if possible we can specify the number of calls made during this `max_time` by using `max_retires` decorator argument.

2018-06-27 14:57 UTC, muhammad-ammar reviewed
@irfanuddinahmad don't we need to add the tests?

2018-06-27 15:52 UTC, robrap commented on ecommerce/enterprise/api.py
> +                      RequestException,
1. Why is RequestException not mentioned in the docstring?  Which does this apply to?
2. We should consider what it might look like to add more features into the api client to get this behavior by default.
3. At this time, these calls are happening inside an atomic transaction.  Anything that we do to increase time to failure will increase the likelihood of lock wait timeouts.  We may need to consider precomputing/caching external calls early in the transaction, outside of the atomic transaction.

FYI: @georgebabey

2018-06-28 11:21 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +                      max_tries=4)
please set `max_tries=3` and `max_time=30`

2018-06-28 11:51 UTC, zubair-arbi approved these changes
Good effort 👍

2018-06-29 10:13 UTC, georgebabey commented on ecommerce/enterprise/api.py
> +                      RequestException,
@robrap 
2. Agreed - it would be good to get some intelligent defaults for backoff into edx-rest-api-client, however I'm not sure what that would look like as it is likely use-case dependent.
3. Hmm... Good call - I'd hate to increase lock timeouts when trying to fix other exceptions

2018-06-29 10:22 UTC, georgebabey commented on ecommerce/enterprise/api.py
> +                      RequestException,
@robrap Any prior art for (3) - prefetching the data outside of the atomic transaction?

2018-06-29 11:14 UTC, zubair-arbi commented on ecommerce/enterprise/api.py
> +        Resilient helper function for fetch_enterprise_learner_data(site, user)
nit: dedent this docsting

2018-06-29 12:38 UTC, robrap commented on ecommerce/enterprise/api.py
> +                      RequestException,
2. Agreed that this may take some thought. I do want this thinking to happen, but not a blocker for this PR.
3. Only discussion And a ticket so far. This may be simple, but there are some details that may mess up the idea.
General idea:
a. Use decorator to remove atomic transaction from the view, and manually add back the transaction via code.
b. Make the same call that you know you’ll make in the transaction using the same TieredCache.
c. The second time you go to process, the result will simply be pulled from the Request Cache in the TieredCache.
Here’s the tricky caveat: Oscar recommends protecting all transactions as atomic by default, as we’ve done, with little detail about what matters most. We have middleware that messes with the basket that I am guessing is part of the overall atomic transaction as-is, and I presume would no longer be if the decorator is used to disable it for the view. We need some way to determine if this is safe.
I’ve got other alternative hack ideas as well.
There’s also the idea of redundant data to keep from having to make external calls.
Food for thought. I’m not sure if this makes sense without some solution to that problem. Or, we might need load testing where we force the issue and track the lock wait timeouts.

Lastly, an additional thought is that I’ve discussed using Circuit Breakers with Feanil. We found some libraries that showed promise. It would need to play nice with the backoff library, but I could see backoff without a Circuit Breaker creating a new problem for us of lots of threads waiting the full timeout.

I’m not certain what the recommendation should be. One possibility is to have two methods, one with and one without backoff, and use a waffle flag to choose which to call so we can turn this feature on and off temporarily. That way, whether we experiment in load test or prod we can try either without a redeploy.

2018-07-02 18:20 UTC, georgebabey commented
I like @robrap idea of using a waffle flag as circuit breaker to turn this on/off as mentioned here: https://github.com/edx/ecommerce/pull/1827#discussion_r199145150. I worry we'll see an increase in deadlocks which can be tricky to reproduce

2018-07-03 12:30 UTC, georgebabey approved these changes
A few small comments but overall looks good!

2018-07-03 12:30 UTC, georgebabey commented on ecommerce/core/constants.py
> +BACKOFF_FOR_API_CALLS_SWITCH = u'enable_backoff_for_api_calls'
Can we update the name to `enable_backoff_for_enterprise_api_calls` just to avoid confusion if someone thinks the backoff applies to all api calls.

2018-07-03 12:30 UTC, georgebabey commented on ecommerce/enterprise/api.py
> +    Resilient helper function for fetch_enterprise_learner_data(site, user)
Would be good to mention the backoff in the comments in case someone is just looking at the docstrings/documentation

2018-07-03 12:30 UTC, georgebabey commented on ecommerce/enterprise/api.py
> +def _get_response(endpoint, **querystring):
could rename this as `get_with_backoff` to be more explicit on what this method is doing

2018-07-03 13:35 UTC, irfanuddinahmad commented
@georgebabey I have incorporated your suggestions. Kindly review and merge. Thanks.

2018-07-03 14:31 UTC, robrap commented on ecommerce/enterprise/api.py
> +                      max_time=30)
@georgebabey: I'm having second thoughts about us putting this through. I'm not convinced that this isn't trading off one problem for a different and worse problem. The problem with the Lock Wait Timeouts is that they are so hard to solve and/or know which transactions/situations are the root cause, and they affect the entire system due to the locking.

For this, and all of our back-end synchronous calls, we need a better solution. 30 seconds is just asking for locking issues any time the LMS is having trouble, which happens every LMS deployment (as well as other times).  Let's chat in person.

Sorry about this...but it feels wrong to introduce this at the same time that Chris and Jason are working so hard to shrink these kinds of problems.

2018-07-03 14:37 UTC, georgebabey commented on ecommerce/enterprise/api.py
> +                      max_time=30)
@robrap No problem and totally understand the concern. 👍  Lets circle back and come up with a good game plan. I think we do need some resiliency for external calls and exponential backoff is likely the right way, but we need to do so without introducing additional lock waits.

2018-07-03 14:40 UTC, georgebabey requested changes
Requesting changes until we have a better strategy for the locking

2018-08-10 15:50 UTC, robrap commented
@georgebabey: Does it make sense to close this PR and just refer to it from some ticket related to the ongoing research?

2018-11-08 19:31 UTC, closed without merging