[WIP] Add coupon categories
openedx-unsupported/ecommerce pull request #1834
Opened 2018-06-28 13:49 UTC by mushtaqak

2018-07-02 15:11 UTC, robrap commented on ecommerce/extensions/catalogue/migrations/0032_add_coupon_categories.py
> +    'Bulk Enrollment - Prepay', 'Bulk Enrollment - Upon Redemption',
FYI: I'm not planning on doing a full review, but could you please put each option on its own line. :)

2018-07-02 15:17 UTC, robrap commented
@georgebabey: I don't have any experience with the coupon code or coupon categories.
Based on the new names of the categories, they now include a sort-of category and subcategory in the name.  I don't know if there needs to be a relationship for these?  Do we need to know what is an Enrollment coupon of any variety?
I just have high-level questions because I don't have experience here.  Can you help turn up anyone that does in the guild, or are we starting from scratch from the guild perspective?  Thanks.

2018-07-02 15:20 UTC, muhammad-ammar commented
@mushtaqak I think we should do the filtering on backend because

- changes would be robust, and
- all the consumers of api will get consistent result  

[CouponCategoriesListView](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/api/v2/views/coupons.py#L503:7) returns all the coupon categories and we can exclude the `Bulk Enrollment` in `get_queryset` like below. 

```python
DEPRECATED_COUPON_CATEGORIES = ['Bulk Enrollment']

def get_queryset(self):
    parent_category = Category.objects.get(slug='coupons')
    return parent_category.get_children().exclude(name__in=DEPRECATED_COUPON_CATEGORIES)

```

2018-07-02 15:20 UTC, muhammad-ammar requested changes
@mushtaqak we need to move the filtering logic from frontend to backend. Please see me comment.

2018-07-03 09:16 UTC, mushtaqak commented
@zubair-arbi @muhammad-ammar @georgebabey @robrap Feedback addressed.

2018-07-03 09:36 UTC, muhammad-ammar approved these changes
👍 once build is green

2018-07-03 10:29 UTC, mushtaqak commented
Squashed commits, once build is green again this will be ready for merge.

2018-07-03 12:24 UTC, georgebabey reviewed
One question regarding the migration..

2018-07-03 12:24 UTC, georgebabey commented on ecommerce/extensions/catalogue/migrations/0032_add_coupon_categories.py
> +Category = get_model("catalogue", "Category")
single-quotes for consistency, probably a nit since its in a migration

2018-07-03 12:24 UTC, georgebabey commented on ecommerce/extensions/catalogue/migrations/0032_add_coupon_categories.py
> +    Category.objects.get(name=COUPON_CATEGORY_NAME).get_children().filter(
Won't this remove the deprecated `Bulk Enrollment` category?

2018-07-03 12:27 UTC, mushtaqak commented
Sandbox: https://ecommerce-couponcategories.sandbox.edx.org/coupons/new/

2018-07-03 12:30 UTC, mushtaqak commented on ecommerce/extensions/catalogue/migrations/0032_add_coupon_categories.py
> +    Category.objects.get(name=COUPON_CATEGORY_NAME).get_children().filter(
This is the reverse migration method.

By the way, I copied the migration logic from previous migration [default migration file](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/catalogue/migrations/0015_default_categories.py#L8)

2018-07-03 12:32 UTC, georgebabey commented on ecommerce/extensions/catalogue/migrations/0032_add_coupon_categories.py
> +    Category.objects.get(name=COUPON_CATEGORY_NAME).get_children().filter(
Whoops. yes I misread that, thanks! 👍

2018-07-03 12:33 UTC, georgebabey approved these changes

2018-07-03 12:52 UTC, mushtaqak commented on ecommerce/extensions/catalogue/migrations/0032_add_coupon_categories.py
> +Category = get_model("catalogue", "Category")
@georgebabey Do you want me to change this or this is ok to merge? since this is already done a lot of migration files in ecommerce.

2018-07-03 12:54 UTC, georgebabey commented on ecommerce/extensions/catalogue/migrations/0032_add_coupon_categories.py
> +Category = get_model("catalogue", "Category")
Like I said, I consider it a nit since its just in a migration, not a python file that will require ongoing support.

2018-07-03 16:07 UTC, mushtaqak commented on ecommerce/extensions/catalogue/migrations/0032_add_coupon_categories.py
> +Category = get_model("catalogue", "Category")
Addressed.

2018-07-03 16:08 UTC, mushtaqak commented
@georgebabey Since I don't have merge right, can you get this merged. Thanks

2018-07-09 17:49 UTC, georgebabey commented
@mushtaqak This just needs a rebase before it can be merged

2018-07-10 07:26 UTC, zubair-arbi approved these changes
:shipit:

2018-07-10 09:31 UTC, mushtaqak commented
@georgebabey Rebased :)

2018-07-10 09:49 UTC, mushtaqak commented
It looks like there is a merge conflict - I will push it again.

2018-07-10 12:13 UTC, mushtaqak commented
@georgebabey This is ready for merging.

2018-07-10 12:19 UTC, merged