LEARNER-5603 Hot Fix
openedx-unsupported/ecommerce pull request #1843
Opened 2018-07-02 16:56 UTC by Ayub-Khan

[LEARNER-5603](https://openedx.atlassian.net/browse/LEARNER-5603)
Students are skipping the basket views which have all the voucher checks if its valid or not. Students are able to submit payments but after payments oscar checks if voucher is valid or not and breaks the system as vouchers used for those baskets is not valid. On average we are receiving around 20 such cases every day which is causing a lot of problem for support. Also we have to fix all the previous paid baskets which have expired vouchers. 
This will prevent students from paying using a expired coupon. I do know this is not a good solution. We will be reverting this after we figure out how students are able to bypass basket views and direct submit payment using submit payment view.

2018-07-02 17:10 UTC, staubina commented on ecommerce/extensions/payment/views/__init__.py
> +        """LEARNER-5603 Hot fix"""
Add more detail here as the ticket ID could potentially change.

2018-07-02 17:25 UTC, jmyatt commented on ecommerce/extensions/payment/views/__init__.py
> +        """LEARNER-5603 Hot fix"""
yes, please point to the code in place_order() that you're copying here and briefly explain why we need that

2018-07-02 17:27 UTC, jmyatt commented
LGTM as a temporary fix

2018-07-02 18:13 UTC, robrap reviewed
If we think this change is risky, because we aren't sure about it, some ways to mitigate risk:
1. Add a unit test to at least ensure we aren't introducing any issues.  Codecov says we are never going into this code.
2. Add appropriate logging to potentially help us track down when this is happening?
3. Could add a temporary waffle switch so you could turn this on/off if it doesn't do what you want it to do.

2018-07-03 19:00 UTC, jmyatt commented on ecommerce/extensions/payment/migrations/0019_create_voucher_validation_switch.py
> +# -*- coding: utf-8 -*-
hmm not sure a migration is the best way to add a waffle switch, esp since it would require a future migration to remove the switch, which we expect to do in a future, more comprehensive fix for this issue.  Is there a compelling reason to do this instead of simply creating the switch in django admin?

2018-07-03 20:15 UTC, robrap requested changes
Minor changes requested.  Thank you!

2018-07-03 20:15 UTC, robrap commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        toggle_switch(VOUCHER_VALIDATION_BEFORE_PAYMENT, True)
Use the following decorator:
```
@override_switch(VOUCHER_VALIDATION_BEFORE_PAYMENT, active=True)
```

2018-07-03 20:15 UTC, robrap commented on ecommerce/extensions/payment/migrations/0019_create_voucher_validation_switch.py
> +# -*- coding: utf-8 -*-
Agreed.  Let's drop this migration.

2018-07-03 20:15 UTC, robrap commented on ecommerce/extensions/payment/views/__init__.py
> +        if waffle.switch_is_active(VOUCHER_VALIDATION_BEFORE_PAYMENT):
Please add a JIRA ticket for removing this switch in the future and add a comment like the following above this line:
```
# TODO: LEARNER-XXXX: Clean-up validation code as needed after further investigation.
```
Note: I imagine that LEARNER-5603 will be closed.  If it will remain open, then maybe this is just LEARNER-5603.  It just needs to be linked to an open ticket.  Thanks!

2018-07-03 20:20 UTC, robrap commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +    def test_submit_view_fails_for_invalid_voucher(self, end_time, status_code):
Also, can you add one more test (or manually verify) that if the switch is False then it succeeds without an error.  Basically, I want to make sure that this test proves that the bug exists with the switch disabled, and is fixed with it enabled.  Thank you!

2018-07-03 20:21 UTC, robrap commented
@Ayub-Khan: Thank you for adding both the switch and the test. :)

2018-07-04 06:11 UTC, Ayub-Khan commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        toggle_switch(VOUCHER_VALIDATION_BEFORE_PAYMENT, True)
@robrap In ecommerce we have been using toggle_switch, decorator override_switch was only used once before. I have updated the test tho decorator is a better choice. May be create a ticket to remove toggle_switch altogether and only use decorator only.

2018-07-04 06:19 UTC, Ayub-Khan commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +    def test_submit_view_fails_for_invalid_voucher(self, end_time, status_code):
done.

2018-07-04 16:18 UTC, robrap approved these changes
Minor comment if you don’t mind updating as part of squashing. We can merge and deploy tomorrow morning when back from our holiday. Thank you!

2018-07-04 16:18 UTC, robrap commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +        Verify SubmitPaymentView call is successful if voucher waffle switch disabled
Great. Thank you.
Some minor updates.
1. Could you update this docstring as follows:
```
“””
Temporary test to confirm the problem with SubmitPaymentView
Accepting an invalid voucher when the waffle switch is False.
This will be cleaned up in LEARNER-5719.
“””
```
2. Nit: these tests would be a little cleaner to have both `start_time` and `end_time` as variables. I’m this test, you could name it `expired_end_time’.

2018-07-04 16:32 UTC, Ayub-Khan commented
sure

2018-07-05 12:11 UTC, staubina approved these changes

2018-07-05 12:11 UTC, staubina commented
@jmyatt Do you mind finalizing your review?

2018-07-05 12:36 UTC, robrap commented
@staubina: This is ready for you to merge/deploy.  @jmyatt made one comment that I already had the team see through.  Note: after deployment, you'll want to turn on the switch and monitor for issues.

2018-07-05 16:19 UTC, merged