WIP- Fixed the Enterprise Offer Name Issues
openedx-unsupported/ecommerce pull request #1850
Opened 2018-07-06 10:08 UTC by asadiqbal08

@georgebabey can you look into the change set?

2018-07-06 10:12 UTC, asadiqbal08 commented on ecommerce/enterprise/forms.py
> +        offer_name = (offer_name[:125] + '...') if len(offer_name) > 128 else offer_name  # pylint: disable=unsubscriptable-object
@georgebabey I can see, in programs form, A [similar approach](https://github.com/edx/ecommerce/blob/master/ecommerce/programs/forms.py#L92) is adopted to fix that issue. Thoughts ?

2018-07-10 10:15 UTC, georgebabey requested changes
We still need the catalog_uuid in the name, as there is a unique constraint on the offer name. That is what caused this issue in the first place.

I'd recommend

2018-07-10 10:15 UTC, georgebabey commented on ecommerce/enterprise/forms.py
> +        self.instance.name = offer_name
The instance name still needs to be unique - so we need the catalog_uuid in the name. Thats also why I recommend truncating just the enterprise_name down, otherwise we risk the catalog_uuid getting cut off and it failing to save because of the unique constraint.

Note when we do change the name to include the UUID, we need to update the receipt to not show the offer name directly, but instead show 'offer provided by {company}' since the offer name would then show the catalog uuid, which doesn't make sense to present to an end user.

2018-07-11 13:42 UTC, asadiqbal08 commented
@georgebabey can you review the change set ?

2018-07-11 14:21 UTC, georgebabey approved these changes
This looks good, just one minor question for my own understanding

2018-07-11 14:21 UTC, georgebabey commented on ecommerce/enterprise/forms.py
> +        # Truncate enterprise_customer_name down to 68 characters, as Oscar's AbstractConditionalOffer name is
Looks like you used 48 characters, which is fine, just comment needs updating

2018-07-11 14:21 UTC, georgebabey commented on ecommerce/enterprise/forms.py
> +                self.instance.condition.enterprise_customer_name = enterprise_customer['name']
Why did enterprise_customer_name not work here if its what we're using on line 103? Doesn't look like you're modifying it...

2018-07-11 14:22 UTC, georgebabey commented on ecommerce/enterprise/forms.py
> +        # Truncate enterprise_customer_name down to 68 characters, as Oscar's AbstractConditionalOffer name is
Nevermind, you fixed this before I submitted 👍

2018-07-11 14:25 UTC, asadiqbal08 commented on ecommerce/enterprise/forms.py
> +                self.instance.condition.enterprise_customer_name = enterprise_customer['name']
ah yes. It is just for testing. I am going to revert these lines.

2018-07-12 07:51 UTC, zubair-arbi requested changes

2018-07-12 07:51 UTC, zubair-arbi commented on ecommerce/enterprise/forms.py
> +        # Truncate enterprise_customer_name down to 48 characters, as Oscar's AbstractConditionalOffer name is
```
Truncate `enterprise_customer_name` to 48 characters so that our complete name with 
format `Discount of type {site} provided by {enterprise_name} for {catalog_uuid}.` does
not exceed the limit of 128 characters for Oscar's `AbstractConditionalOffer` name.
```

2018-07-12 07:51 UTC, zubair-arbi commented on ecommerce/enterprise/forms.py
> +            enterprise_customer_name[:48] if len(enterprise_customer_name) > 48 else enterprise_customer_name,  # pylint: disable=unsubscriptable-object,
We can just do:
```python
enterprise_customer_name[:48]
```

2018-07-12 07:51 UTC, zubair-arbi commented on ecommerce/templates/edx/checkout/receipt.html
> +                        <span class="discount">
nit: It looks like we can move `<span>` tag outside of `if-else` condition.

2018-07-12 09:23 UTC, zubair-arbi approved these changes
LGTM 👍 🚢

2018-07-12 10:07 UTC, merged