Add partner in course model.
openedx-unsupported/ecommerce pull request #1853
Opened 2018-07-09 07:27 UTC by waheedahmed

LEARNER-5052

2018-07-23 14:06 UTC, waheedahmed commented
@feanil @robrap Please review, I have tried to remove all the usages of `Course.site` I don't think we need to wrap this in a function.

2018-07-26 13:52 UTC, robrap reviewed
@feanil: Please don't take this as a fully comprehensive review.  I didn't look at migrations or other things, and used search to check certain specific questions.

Thanks @waheedahmed.  Sorry about the delay.  I had to keep coming back to this.

2018-07-26 13:52 UTC, robrap commented on ecommerce/extensions/api/v2/views/products.py
>          #   - course site: for products that don't have a stockrecord (parent course)
course site => course partner

2018-07-26 13:52 UTC, robrap commented on ecommerce/courses/tests/test_create_enrollment_codes_command.py
> +        course = CourseFactory(partner=self.site.siteconfiguration.partner)
Can this just be `self.partner`?

2018-07-26 13:52 UTC, robrap commented on ecommerce/courses/management/commands/publish_to_lms.py
> +                    publishing_error = course.publish_to_lms(course.partner.default_site)
1. I thought `partner.default_site` was something we were considering dropping.  I need to better understand it.
2. I'm not clear on what the proper relationships should be between a course and its partner, and a course publish to lms, and the site that is used for publishing.
a. Will all sites represent a single lms, and does it not matter which is used?
b. Should `publish_to_lms` just use the course.partner.default_site internally, if that is something that will always exist?
c. Below, we call `publish_to_lms(request.site)`? Do we care if the request.site has no relationship with the course partner's sites?  Would we need an assertion somewhere?

2018-07-26 17:34 UTC, feanil requested changes
Generaly looks good, just a few questions and some changes needed in the migrations.

2018-07-26 17:34 UTC, feanil commented on ecommerce/courses/migrations/0008_course_partner.py
> +# -*- coding: utf-8 -*-
- Separate the 3 migraitons here to be separate.
  - One for the addition of the field,
  - One for making the site optional
  - One for making doing the data migration.
- The data migration should have a reverse that updates the course.site.siteconfiguration.partner with the current value of the course.partner

2018-07-26 17:34 UTC, feanil commented on ecommerce/courses/publishers.py
> +            commerce_api_client = site.siteconfiguration.commerce_api_client
Why not just use course.partner.default_site?  Then you don't need to pass the extra parameter.

2018-07-26 17:37 UTC, robrap commented on ecommerce/courses/publishers.py
> +            commerce_api_client = site.siteconfiguration.commerce_api_client
@feanil: Does this mean `partner.default_site` is here to stay?  Also, does it need to be a specific site, or is that equivalent to something like `partner.any_one_of_my_sites`?

2018-07-26 18:23 UTC, feanil commented on ecommerce/courses/publishers.py
> +            commerce_api_client = site.siteconfiguration.commerce_api_client
I don't remember if we came to any decision on that.  I could see arguments for just removing it and always being explicit as well.

2018-07-27 07:50 UTC, waheedahmed commented on ecommerce/courses/management/commands/publish_to_lms.py
> +                    publishing_error = course.publish_to_lms(course.partner.default_site)
@robrap Yes we are, I'm just trying to use the current logic here. We will think about it later with a better resolution.

2018-07-27 10:42 UTC, waheedahmed commented
@robrap @feanil Addressed all comments, kindly take another look.

2018-07-27 10:43 UTC, waheedahmed commented on ecommerce/courses/publishers.py
> +            commerce_api_client = site.siteconfiguration.commerce_api_client
@robrap No, I'm just using the available logic for now, it will be cleaned up in follow up ticket with a better logic.

2018-07-27 13:06 UTC, robrap commented on ecommerce/courses/management/commands/publish_to_lms.py
> +                    publishing_error = course.publish_to_lms(course.partner.default_site)
Sounds good @waheedahmed.  When we get to that ticket, let's ensure we agree on a design/plan before you implement.  It's not clear to me what is the right thing to do you on this front.  Thanks!

2018-07-27 21:03 UTC, feanil reviewed
Two file renames and then I think this is good to go.  Don't forget to update the dependencies when you rename the auto migrations.

2018-07-27 21:03 UTC, feanil commented on ecommerce/courses/migrations/0009_auto_20180727_0751.py
> +# -*- coding: utf-8 -*-
give this migration a better name, maybe `0009_allow_site_to_be_nullable.py`

2018-07-27 21:03 UTC, feanil commented on ecommerce/courses/migrations/0010_auto_20180727_0757.py
> +# -*- coding: utf-8 -*-
Give this migration a better name, maybe `0010_migrate_partner_data_to_courses.py`

2018-07-30 10:09 UTC, ahsan-ul-haq approved these changes
LGTM

2018-07-30 11:05 UTC, waheedahmed commented
@feanil Renamed the migrations also tested locally with multiple site objects against same partner and course api returning same data for both sites. Kindly take another look.

2018-07-30 13:44 UTC, feanil approved these changes

2018-07-30 13:46 UTC, merged