Fix for LEARNER-5603, LEARNER-5630
openedx-unsupported/ecommerce pull request #1862
Opened 2018-07-18 10:51 UTC by Ayub-Khan

[LEARNER-5603](https://openedx.atlassian.net/browse/LEARNER-5603)
[LEARNER-5630](https://openedx.atlassian.net/browse/LEARNER-5630)

Steps to Reproduce:
Add a voucher to a basket
Close the basket page
Reopen the basket page
Notice the coupon already added to basket without any discount.
Also works even if you open basket page after the coupon expiration. 

When preparing the basket for checkout we flush the basket to remove lines and add again. I added a call to remove all the existing vouchers in basket too.

2018-07-18 10:56 UTC, tasawernawaz commented
Change make sense to me. It would be great if you can add tests too, also if it is feasible please create sandbox to test this.

2018-07-18 15:46 UTC, robrap commented on ecommerce/extensions/basket/models.py
> +        self.clear_vouchers()
This doesn't feel right.  Some questions:
1. From your description, it sounds like prepare_basket calls the flush and could also clear the vouchers.
2. I'm unclear if this temporarily clears the vouchers (just like the basket being emptied), and then it adds it back with the proper discount?  Or, does the user have to add the voucher again?  What would Product prefer?
3. Agreed.  Please add a test for whatever we decide.
Thank you!

2018-07-18 18:12 UTC, jmyatt commented on ecommerce/extensions/basket/models.py
> +        self.clear_vouchers()
Adding to @robrap 's comments, I agree that this should live in prepare_basket along with the other code there that does the following:
  * flushes products via this Basket.flush method and conditionally adds them back
  * conditionally clears / adds vouchers

Specifically, maybe [this code block](https://github.com/edx/ecommerce/blob/d7f5586b9b3c1ece5d7423563be37a1a5f41e4ef/ecommerce/extensions/basket/utils.py#L105-L111) could be augmented to something like:

    if len(products) == 1 and products[0].is_enrollment_code_product:
        basket.clear_vouchers()
    elif voucher:
        basket.clear_vouchers()
        basket.vouchers.add(voucher)
        Applicator().apply(basket, request.user, request)
        logger.info('Applied Voucher [%s] to basket [%s].', voucher.code, basket.id)
    elif basket.vouchers.exists():
        for voucher in basket.vouchers.all():
            if not voucher.is_active():
                basket.vouchers.remove(voucher)

(the last 4 lines being the new logic).  But if we do that it probably makes sense to include all the logic you recently added to check_valid_voucher

2018-07-19 05:39 UTC, Ayub-Khan commented on ecommerce/extensions/basket/models.py
> +        self.clear_vouchers()
@robrap 
2. This does not clear the vouchers added by user. It clears the vouchers already existing in the basket obj. 
3. @jmyatt  Agree but we will need to reapply the voucher too if we want to keep the valid voucher added in the basket.

2018-07-19 07:26 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +        is_valid, message = validate_voucher(voucher, request.user, basket, request.site)
Fixes the issue LEARNER-5876

2018-07-19 07:27 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +        valid_vouchers = []
Just in case if we start using Multiple voucher functionality for single basket.

2018-07-19 07:29 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +    elif basket.vouchers.exists():
Checks if there is a existing voucher which was added before in the basket. Validate it and apply again if its valid now and active now and can be used for new products. LEARNER-5603, LEARNER-5630

2018-07-19 07:32 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +def validate_voucher(voucher_code, user, basket, request_site):
Moved Voucher validate for basket code to this new method to avoid code duplication in VoucherAddView and prepare_basket.

2018-07-19 07:33 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +def _apply_voucher_on_basket(voucher, request, basket):
Created this to avoid code duplication in prepare basket method.

2018-07-19 13:31 UTC, robrap commented
This is probably already planned, but can you add at least one test per ticket that confirms that the issue is fixed.  All new tests should fail against master and pass for this PR.

2018-07-23 13:02 UTC, robrap requested changes
It will be great to have these fixes.  I've got a lot of comments, but they are mostly minor.  Let me know if you think otherwise and we can discuss.  Thanks.

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/tests/test_utils.py
> +        not applies it if invalid.
Should be “does not apply it if invalid.”

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/tests/test_utils.py
> +        voucher, __ = prepare_voucher(start_datetime=voucher_start_time, end_datetime=voucher_end_time)
Can you rename `voucher` to `expired_voucher` for clarity?

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/tests/test_utils.py
> +        voucher, voucher_product = prepare_voucher(start_datetime=voucher_start_time, end_datetime=voucher_end_time)
expired_voucher, _ = ...

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/tests/test_utils.py
> +        if its valid for new product.
What does new or old mean here? Is this a test that a voucher made for two products is valid for either one?  Can you better explain this test?

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +    elif basket.vouchers.exists():
The doc string for this method states that we will only allow up to one voucher, but this code is not written as such.  Is the docstring accurate?  

Also, these two `elif` sections are extremely similar and not DRY.  Could we have a single `elif voucher or basket.vouchers.exists():`.  In this new `elif`, I would create a list with the first element as the passed in voucher, and the rest of the list being the basket vouchers.  Once you have this list, you can clear the basket vouchers. Then loop over the list in order until you find a valid voucher (or reach the end), and break after the first valid voucher (if we only want a max of one voucher list the docstring says).  Note: If we are not sure about the business rule, we can ask.

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +            message = _("Coupon code '{code}' has already been redeemed.").format(code=voucher.code)
Does this custom message belong in `voucher.is_available_to_user()`?

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +        message = _("Coupon code '{code}' is not valid for this basket.").format(code=voucher.code)
If `voucher_site` exists, are we ok if `request_site` is None, or would that still be invalid? Note: I know that this code did not originate in this PR, so this isn't a blocker.  But, I would like to get this answered.

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +
@georgebabey @BessieSteinberg @bill-filler: FYI: I'm not sure how Journal and Enterprise vouchers are handling this case, and whether it is handled elsewhere, or if we need more expanded logic around this here, since it is only looking at programs?

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +        message = _("Coupon code '{code}' is not valid for this basket.").format(code=voucher.code)
Please update the message to provide more detail about the problem.

2018-07-23 13:02 UTC, robrap commented on ecommerce/extensions/basket/tests/test_utils.py
> +        voucher2, __ = prepare_voucher(code='TEST2', _range=new_range, benefit_value=20)
1. Why does `_range` have an underscore prefix? (If that code is outside the PR, I'll leave it to you to update.)
2. Can you explain why the range and benefit value need to be added for some of these tests?

I may recommend wrapping this in a helper with a name that clarifies what kind of voucher this is, but that depends on the answer to the second question.

2018-07-24 10:09 UTC, Ayub-Khan commented on ecommerce/extensions/basket/tests/test_utils.py
> +        voucher2, __ = prepare_voucher(code='TEST2', _range=new_range, benefit_value=20)
1. its the % by default its 100% so in case of valid coupons tests we check if the basket price is updated or not.

2018-07-24 10:27 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +    elif basket.vouchers.exists():
yes we do only allow one voucher. I wrote it bcz of forward compatibility. To be more specific we only count the last added voucher. We have a test for that too. i have updated the code too.

2018-07-24 10:42 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +            message = _("Coupon code '{code}' has already been redeemed.").format(code=voucher.code)
Im not sure if i understand what you mean. But we can move this there. Here its also kinda replacing the error msg returned by is_available_to_user.

2018-07-24 10:45 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +        message = _("Coupon code '{code}' is not valid for this basket.").format(code=voucher.code)
Im not sure if we will reach this point if request.site is none.

2018-07-24 10:49 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +        message = _("Coupon code '{code}' is not valid for this basket.").format(code=voucher.code)
I think we should get opinion from bundling people if its ok for us to update those error messages. Also this message appears to students too.

2018-07-24 15:35 UTC, robrap commented on ecommerce/extensions/basket/tests/test_utils.py
> +        """
I'm not sure if it is the name of this test that is incorrect, or the docstring, or the code.  It depends what we wish to test.  

The test before this is named `test_prepare_basket_removes_old_basket_invalid_voucher` and it uses `basket.vouchers.add(expired_voucher)`.  I imagine that `old_basket_invalid_voucher` means `existing_basket_invalid_voucher`.  In this test, we use the name `test_prepare_basket_applies_old_basket_valid_voucher`, but we don't have the line `basket.vouchers.add(voucher)`, and we probably should, rather than sending it into `prepare_basket`.  If we need a separate test for sending it in to `prepare_basket`, we could also have that.

In the docstring, I think `old voucher` just means `existing basket voucher`, right?  Also, I don't think `new` in `new product` signifies anything, unless I am missing something.  It looks like the following would be a better docstring:
```
Tests that prepare_basket applies an existing basket voucher that is valid
for multiple products when used to purchase any of those products.
```
NOTE: The phrase `existing basket voucher` only applies if you add the line `basket.vouchers.add(voucher)`.  If we don't, or we need an additional test for passing the voucher, we could use something like:
```
Tests that prepare_basket applies that passed voucher that is valid
for multiple products when used to purchase any of those products.
```

Let me know if this all makes sense.  Thanks.

2018-07-24 15:35 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +        voucher = voucher or basket.vouchers.last()
If voucher exists, but is expired, wouldn't we want the basket voucher?  Or, do we only want the voucher that was passed in if it was passed in?  Also, if the basket had 2 vouchers (not sure if it could), and the last one is expired, but the other one is not, wouldn't we want the unexpired one?

Your code may or may not be ok depending on the answers to the above question.  

If we do need to handle more complicated rules, we could have something like:
```
voucher_list = []
voucher_list.append(voucher)
voucher_list.extend(basket.vouchers)
voucher_list = filter(None, voucher_list)
basket.clear_vouchers()
for voucher in voucher_list:
    is_valid, message = validate_voucher(voucher, request.user, basket, request.site)
    if is_valid:
        _apply_voucher_on_basket(voucher, request, basket)
        break
    else:
        logger.info(message)
```
NOTE: Do not update your code unless we need to support the more complicated behavior.  Your code is simpler to write and test. :)

2018-07-24 15:35 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +            message = _("Coupon code '{code}' has already been redeemed.").format(code=voucher.code)
You do not have to do this.  I feel like it belongs in an overridden method somewhere so that anyone calling this would get the more complete message, but you were just moving this code.  You can leave this as-is.

2018-07-24 15:36 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +        message = _("Coupon code '{code}' is not valid for this basket.").format(code=voucher.code)
Not a blocker.  You can leave as-is for now.

2018-07-24 15:37 UTC, robrap commented on ecommerce/extensions/basket/tests/test_utils.py
> +        voucher2, __ = prepare_voucher(code='TEST2', _range=new_range, benefit_value=20)
I still don't see where the added `benefit_value` is used in this particular test.  But, if it is necessary for some reason, you can leave it.

2018-07-24 15:38 UTC, robrap reviewed
I wrote a lot of text, but I'm not asking for much.  This is close.  Thank you!

2018-07-24 15:44 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +        message = _("Coupon code '{code}' is not valid for this basket.").format(code=voucher.code)
ok

2018-07-26 07:20 UTC, Ayub-Khan commented on ecommerce/extensions/basket/tests/test_utils.py
> +        voucher2, __ = prepare_voucher(code='TEST2', _range=new_range, benefit_value=20)
its in the last assert to check the discount value.

2018-07-26 07:40 UTC, Ayub-Khan commented on ecommerce/extensions/basket/tests/test_utils.py
> +        """
Updated.

2018-07-26 08:00 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +        voucher = voucher or basket.vouchers.last()
@robrap we prefer the last added voucher over already existing voucher. Also we do not usually pass voucher code directly into baskets. So it will be a rare case. i think we pass voucher directly to basket add page from coupon redeem pages so there is a more less chance its going to be invalid. I do think we will need to use the above mentioned code when we start using multiple vouchers for same basket.

2018-07-26 13:10 UTC, robrap commented on ecommerce/extensions/basket/utils.py
> +        voucher = voucher or basket.vouchers.last()
@Ayub-Khan: Please change from `vouchers.last` to `vouchers.first` for consistency with the rest of the code.  I'm not sure which is more accurate, or if there could only be 1 so it doesn't matter, so I'd like to retain consistency.

FYI: I'll follow-up with Product around the current and future status of handling multiple vouchers.  I want to document in ecommerce if we are committed to always handling a max of 1 voucher, or if we should handle multiple.  We can always add another PR if needed, but don't want to block this one.

Note: In the future, if we wanted to handle multiple here, a simpler version of what I wrote would be: `vouchers = [voucher] or basket.vouchers`, which is a mix of yours and mine.

2018-07-26 13:18 UTC, robrap submitted a review, later dismissed
Very close.  Just a missing test and a very minor change.

2018-07-26 13:18 UTC, robrap commented on ecommerce/extensions/basket/tests/test_utils.py
> +    def test_prepare_basket_applies_existing_basket_valid_voucher(self):
I think we are missing a test, but let me know if I am wrong.  Here would be the new test:
```
def test_prepare_basket_applies_valid_voucher_argument(self):
    """
    Tests that prepare_basket applies a valid voucher passed as an
    an argument, even when there is also a valid voucher already on
    the basket.
    """
```
Note: You would need to create two different valid vouchers, add one to the basket and pass one to `prepare_basket`, and ensure it was the `prepare_basket` one that gets used.
However, I'm basing this on you stating that this is what should happen.  I don't really know. :)

2018-07-26 15:13 UTC, robrap reviewed
@Ayub-Khan: This is approved if you add the missing test as asked and make the other minor change from `last` to `first`.  Just squash and rebase and you can get @waheedahmed to merge and you can test on Stage and then deploy.  I don't want you to have to wait another day for me.
Thanks!

2018-07-27 08:11 UTC, Ayub-Khan commented on ecommerce/extensions/basket/utils.py
> +        voucher = voucher or basket.vouchers.last()
Agree

2018-07-27 11:30 UTC, Ayub-Khan commented on ecommerce/extensions/basket/tests/test_utils.py
> +    def test_prepare_basket_applies_existing_basket_valid_voucher(self):
done.

2018-07-27 11:51 UTC, waheedahmed approved these changes

2018-07-27 12:06 UTC, merged