Fix UnicodeError when getting enrolment codes - ENT-1079
openedx-unsupported/ecommerce pull request #1863
Opened 2018-07-18 13:05 UTC by mushtaqak

This PR fixes unicode error when user tries to get enrolment codes through order completion email.

[ENT-1079](https://openedx.atlassian.net/browse/ENT-1079)

2018-07-18 14:21 UTC, mushtaqak commented
@zubair-arbi @muhammad-ammar This is ready for review.

2018-07-19 07:16 UTC, Qubad786 reviewed
Minor concerns otherwise LGTM 👍

2018-07-19 07:16 UTC, Qubad786 commented on ecommerce/coupons/views.py
> +            writer.writerow([order_line_voucher.line.product.title.encode('utf-8')])
We should use [unicodecsv](https://github.com/jdunck/python-unicodecsv):

At L316, `writer` would be:
```bash
import unicodecsv as csv
writer = csv.writer(response, encoding='utf-8')
```

Also, make sure that `order_line_voucher.line.product.title` is never `None`.

2018-07-19 12:31 UTC, muhammad-ammar approved these changes

2018-07-19 12:34 UTC, mushtaqak commented on ecommerce/coupons/views.py
> +            writer.writerow([order_line_voucher.line.product.title.encode('utf-8')])
We aren't using `unicodecsv` in ecommerce, so I guess I am not inclined to add it for now at-least.

2018-07-19 12:35 UTC, zubair-arbi approved these changes
Nice 👍

2018-07-19 13:18 UTC, robrap commented on ecommerce/coupons/views.py
> +            writer.writerow([order_line_voucher.line.product.title.encode('utf-8')])
Good call @Qubad786.  Based on [usage across the platform](https://github.com/search?p=3&q=org%3Aedx+unicodecsv&type=Code), it seems like this is the way to go.  Can you add `unicodecsv` to avoid future issues?

2018-07-19 13:47 UTC, mushtaqak commented
@georgebabey Can you review and merge this (if all is good :P) ?

2018-07-19 14:48 UTC, georgebabey requested changes

2018-07-19 14:48 UTC, georgebabey commented on ecommerce/coupons/views.py
> +            writer.writerow([order_line_voucher.line.product.title.encode('utf-8')])
Agreed, we should switch to using the unicodecsv as @Qubad786 indicates. This seems like a small lift to bring this repo in line with the other edx projects.  Also seems more robust in that this just fixes encoding for the product title, but if another field was added we'd have to remember to encode there as well.

2018-07-20 09:54 UTC, georgebabey approved these changes

2018-07-20 11:53 UTC, merged

2018-07-20 12:59 UTC, robrap commented
Great.  Thanks @mushtaqak!