LEARNER-5864
openedx-unsupported/ecommerce pull request #1864
Opened 2018-07-19 09:58 UTC by Ayub-Khan

[LEARNER-5864](https://openedx.atlassian.net/browse/LEARNER-5864)
Fixed missing order issue in case of duplicate reference number exception.
Check ticket description for more details.

2018-07-19 11:18 UTC, staubina approved these changes
This seems like a nice way to tie up a loose end.

Please clear up testing issues also.

2018-07-19 12:23 UTC, robrap reviewed
Agreed this looks good, but please add a test or assertions for this case. Thank you.

2018-07-23 16:09 UTC, jmyatt requested changes

2018-07-23 16:09 UTC, jmyatt commented on ecommerce/extensions/payment/views/cybersource.py
> +                    'with existing order [%s] or had an existing valid payment notification. '
please remove the text 'or had an existing valid payment notification' - since with the PR we will be (correctly IMO) raising DuplicateReferenceNumber only when an order matching this basket id exists.

2018-07-24 14:02 UTC, jmyatt approved these changes

2018-07-26 08:00 UTC, merged