log duplicate order attempts accurately
openedx-unsupported/ecommerce pull request #1865
Opened 2018-07-19 14:34 UTC by jmyatt

There are some problems with the way we log order placement failures after payment has been successfully processed:

1. in some cases an order for the basket id / order number in question already exists
2. in other cases an inactive voucher was somehow in place on the basket up through this post-payment pre-order point
3. there may be other cases where some other problem caused this condition

Other work is in progress to handle item 2 (PR #1862).  This change addresses item 1 by logging duplicate order cases separately from any other (item 3) cases that may occur.  This will enable us to make the alerting for the duplicate order case more precise and establish a straightforward runbook for Support to manually address those cases.

https://openedx.atlassian.net/browse/LEARNER-5466LEARNER-5466

2018-07-20 04:30 UTC, Ayub-Khan commented on ecommerce/extensions/checkout/mixins.py
>                                    'could not be placed because of exception [%s].'
We can remove the exception part from both logs. As both are logged using logger.exception it includes traceback too in logs.

2018-07-20 16:07 UTC, jmyatt commented on ecommerce/extensions/checkout/mixins.py
>                                    'could not be placed because of exception [%s].'
thanks, all set now

2018-07-20 18:45 UTC, robrap reviewed
Thanks.  Next steps will be based on your responses.

2018-07-20 18:45 UTC, robrap commented on ecommerce/extensions/payment/views/paypal.py
> +                logger.exception(
1. Do we understand why and when this happens, and whether or not it is a problem?  Did we mistakenly place the order at some point?  Did we get a second payment call?  Other?  
2. Based on answer above, do we have a different problem that someone should be looking into?  Or, do we think this is not a problem, and should  just be a warning?  Note: if we need the exception info for some reason, you could add `exc_info=True` as a parameter.
NOTE: Based on the above, we might want to add a relevant comment to the code, like:
```
# We do not understand why this happens and further investigation is needed.  See EG-XXX.
```
Or whatever is appropriate. :)

2018-07-20 18:45 UTC, robrap commented on ecommerce/extensions/payment/views/paypal.py
> +                    self.duplicate_order_number_msg, self.payment_processor.NAME.title(), order_number, basket.id)
I think `self.duplicate_order_attempt_msg`, which reuses "attempt" from the actual message, is more accurate.

2018-07-20 18:45 UTC, robrap commented on ecommerce/extensions/payment/views/paypal.py
> +            if Order.objects.filter(number=order_number).exists():
Did you consider a shared `log_order_placement_exception` method?

2018-07-20 18:45 UTC, robrap commented on ecommerce/extensions/payment/tests/mixins.py
> +                    payment_processor='Cybersource', basket_id=self.basket.id)
Please move closing paren to the next line.  It should line up with the start of the line that contains the open paren.

2018-07-20 19:45 UTC, jmyatt commented on ecommerce/extensions/payment/views/paypal.py
> +            if Order.objects.filter(number=order_number).exists():
ah yes much DRYer - I'll do that

2018-07-20 19:46 UTC, jmyatt commented on ecommerce/extensions/payment/views/paypal.py
> +                    self.duplicate_order_number_msg, self.payment_processor.NAME.title(), order_number, basket.id)
sounds good

2018-07-20 20:00 UTC, jmyatt commented on ecommerce/extensions/payment/views/paypal.py
> +                logger.exception(
1. It's still unclear whether the blame for the duplicate order case is on us for "mistakenly placing the order at some point" or on the payment gateway for accepting payment twice when our end user re-submits quickly.  So more investigation is necessary.  This happens infrequently (3 times in the past 30 days) but when it does we need to alert on it and the user needs to be refunded.  I'll add the further investigation ticket and add a comment here about that

2018-07-21 00:32 UTC, robrap commented on ecommerce/extensions/payment/views/paypal.py
> +                logger.exception(
Thanks. It sounds like they might need to be refunded, but only if we charged them twice. Is there a way for us to know this up front? Is there a way to autorefund when this happens and two payments were found for the order?

2018-07-23 06:51 UTC, Ayub-Khan commented on ecommerce/extensions/payment/views/paypal.py
> +                logger.exception(
@jmyatt  I would like to add some thing here. Multiple payment issue does not happen if user re submits quickly. We have a cybersource setting enabled which do not accept payments and sends a notification with error code '104'. 
https://support.cybersource.com/s/article/What-does-this-response-code-mean
Which mean in every multiple payment issue second request was made after 15 min of first payment. 
@robrap A simple suggestion could be that we create a zendesk ticket through splunk and support refunds the payment from cybersource whenever this issue occurs. (As we do for fulfillment issues).

2018-07-23 06:53 UTC, Ayub-Khan commented on ecommerce/extensions/payment/views/paypal.py
> +            if Order.objects.filter(number=order_number).exists():
+1

2018-07-23 13:58 UTC, jmyatt commented on ecommerce/extensions/payment/views/paypal.py
> +                logger.exception(
I agree that an actionable ticket to manually handle the refund after confirming that the original payment was received, the the original order is valid, and that the user's status on the course run is 'verified' is the right action here, as oppose to coding something to auto-refund the user.  This is infrequent and delicate enough that it justifies the manual steps.

2018-07-25 14:40 UTC, robrap requested changes
Hopefully minor refactors.  Let me know.  Thanks.

2018-07-25 14:40 UTC, robrap commented on ecommerce/extensions/payment/tests/views/test_paypal.py
> +            error_message = \
Couldn't the message be moved to `_assert_order_placement_failure` so it appears in only one place?

2018-07-25 14:40 UTC, robrap commented on ecommerce/extensions/payment/tests/views/test_paypal.py
> +    def test_duplicate_order_attempt_logging(self):
Couldn't most of this been moved to the mixin as well?

2018-07-25 17:55 UTC, robrap approved these changes
I was originally thinking the whole LogCapture context code could be a helper method, but looking more closely, I see they are just different enough.  Not sure why one processing method raises an exception and the other does not, but that is a separate question.

Looking more closely, I made one minor comment.  Feel free to fix locally when you squash, or you could leave it.

2018-07-25 17:55 UTC, robrap commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +            try:
If an exception isn't raised, this test would also pass, and I am guessing it shouldn't. This should probably be:
```
with LogCapture(self.DUPLICATE_ORDER_LOGGER_NAME) as lc:
    with self.assertRaises(ValueError):
        dummy_mixin.create_order(dummy_request, prior_order.basket, None)
    lc.check( ... )
```

2018-07-25 18:03 UTC, jmyatt commented on ecommerce/extensions/payment/tests/views/test_cybersource.py
> +            try:
good point - I'll fix that

2018-07-25 18:22 UTC, merged