Added verify transactions management command to ensure orders and pay…
openedx-unsupported/ecommerce pull request #1881
Opened 2018-08-17 19:11 UTC by calistenson

…ments match.

2018-08-20 16:06 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +        exit_errors = {}
Add a docstring.

2018-08-20 16:06 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +Django management command to verify ecommerce transactions.
Add more details about the management command as a whole.

2018-08-20 16:07 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +    help = 'Management command to verify ecommerce transactions and trigger alerts if there is any imbalance.'
Since we are not explicitly triggering alerts, we should clarify that we are just outputting logs.

2018-08-20 16:08 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +                exit_errors["multi_payment"] = "Multiple payments on order."
Add more details to this log message such as which orders and what payments.

2018-08-20 16:13 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +            order_sum += order.total_incl_tax
I think every order after the first erroneous order will fail because we are not resetting the sums.

2018-08-20 16:17 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +            pays = PaymentEvent.objects.filter(order_id=order.id)
We should use a better variable name here such as `payment_events`

2018-08-20 16:19 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +            pays = PaymentEvent.objects.filter(order_id=order.id)
This filters against the full database. I think you were trying to further filter against your queryset that you filtered in the previous lines. (`payments`)

2018-08-20 16:25 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +            if pays.count() == 0 and order.total_incl_tax > 0:
if an order == 0, do we want to verify that there is no payment event?

2018-08-20 16:31 UTC, BenjiLee requested changes

2018-08-20 16:31 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +            exit_errors["totals_mismatch"] = "Order totals mismatch with payments received." \
When there is a mismatch, how can we identify which orders/paymentevents are wrong if  all orders have payments.

2018-08-20 16:32 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +    def tearDown(self):
We should be able to get rid of this. All changes are rolled back after the test.

https://docs.djangoproject.com/en/1.9/topics/testing/tools/#transactiontestcase

2018-08-20 16:33 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +        order = OrderFactory()
I believe we can shorten this to...

`OrderFactory(total_incl_tax = 100, date_placed = self.timestamp)`
```
order = OrderFactory()
order.total_incl_tax = 100
order.date_placed = self.timestamp
```

2018-08-20 16:34 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +        payment = PaymentEventFactory(order=order, amount=100, event_type_id=self.payevent[0].id)
Same shortening comment as Order() above.

2018-08-20 16:36 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +        order = OrderFactory()
Looks like we are using a lot of the same code for the OrderFactory(). We can put this code in setUp().

2018-08-21 14:38 UTC, BenjiLee commented
Git suggests using present-tense and imperative language. https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n133
`Added verify transactions management command to ensure orders and payments match.` -> `Add verify_transactions management command to ensure orders and payments match.`

Shorten the first line of the commit message. If it need more details, begin the paragraph on the 3rd line.
```
Add verify_transactions management command

The verify_transactions management command ensures that
orders amounts and paymentevent amounts match.

LEARNER-5763
LEARNER-6012
```

2018-08-21 14:42 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +For each order in the time window the command verifies exactly one payment of the expected value exists in the database.
https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#id4

Docstrings should be 80 chars in width.

2018-08-21 14:45 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +If a PaymentEvent does not exist, multiple payments exist, or the payment amount is different from the order amount
`If a PaymentEvent does not exist, multiple PaymentEvents exist, or the PaymentEvent amount is different from the order amount, then the order id and relevant payment information is logged in a list associated with each of these scenarios.`

2018-08-21 14:50 UTC, BenjiLee commented
@calistenson Could you output an example of this management command where all 3 scenarios fail?

2018-08-21 14:52 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +        self.payevent = PaymentEventType.objects.get_or_create(name=PaymentEventTypeName.PAID)
nit: a `payevent` is not a `paymenteventtype`.`self.payevent` -> `self.payment_event_type`

2018-08-21 14:59 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +        self.timestamp = datetime.datetime.now(pytz.utc) - datetime.timedelta(hours=1, minutes=30)
nit: self.timestamp is not a random timestamp. This might be easier to code when we have parser arguments being passed in for the management command.

2018-08-21 15:03 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +        payment.date_created = self.timestamp
Should be able to shove this into the factory initialization.
`payment = PaymentEventFactory(order=self.order, amount=90, event_type_id=self.payevent[0].id, date_created = self.timestamp)`

2018-08-21 15:17 UTC, BenjiLee commented
@calistenson  Is the same process going to be followed for a refund?

2018-08-22 14:25 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +Command is run by Jenkins job each hour on the previous hour and 10 minutes of orders in ecommerce.
This is no longer true. We can make this more resistant to changes.

`Command will be run as a cron job in Jenkins that looks at a time window for Order/Payment discrepancies.`

2018-08-22 20:26 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +            if payment_events.count() == 0 and order.total_incl_tax > 0:
Add a comment to why this conditional is here. 
`# If a coupon is used to purchase a product for the full price, there will be no PaymentEvent`

2018-08-22 20:47 UTC, calistenson commented on ecommerce/core/management/commands/verify_transactions.py
> +            if payment_events.count() == 0 and order.total_incl_tax > 0:
Done

2018-08-22 20:52 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +            for event in payment_events:
nit: I believe we should be guaranteed only 1 payment event here. We are using this for loop to extract a single item from a list and rename it.

2018-08-22 20:57 UTC, BenjiLee commented on ecommerce/core/management/commands/verify_transactions.py
> +        if len(order_payment_totals_mismatch):
fun python! empty lists are falsy

2018-08-23 12:34 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +        self.assertIn(str(payment1.id), exception.message)
There's a potential for order.id == payment.id since they are not unique with each other. A way to resolve this is to customize the id generation field in the PaymentFactory. Example: https://github.com/edx/ecommerce/blob/af0190314929a482421f52162ccad3eaf296e982/ecommerce/courses/tests/factories.py#L14

2018-08-23 13:06 UTC, calistenson commented on ecommerce/core/management/commands/verify_transactions.py
> +            for event in payment_events:
We still want to catch mismatched totals in the cases where there are multiple payments. So I will leave the loop here.

2018-08-23 13:35 UTC, calistenson commented on ecommerce/core/management/commands/tests/test_verify_transactions.py
> +        self.assertIn(str(payment1.id), exception.message)
Fixed this issue in the test by setting the order id manually to "1000". Should I add a comment in the test about why I did this?

2018-08-23 14:36 UTC, BenjiLee commented on ecommerce/core/management/commands/tests/factories.py
> +
`id = random.randint(1000,9999)`

2018-08-23 15:50 UTC, BenjiLee approved these changes

2018-08-23 15:51 UTC, BenjiLee commented
![shipit](https://user-images.githubusercontent.com/7101723/44536582-d01d8400-a6ca-11e8-8408-8c6d366b51ed.jpeg)

2018-08-23 17:12 UTC, merged