LEARNER-6347-fix
openedx-unsupported/ecommerce pull request #1901
Opened 2018-09-12 10:27 UTC by Ayub-Khan

LEARNER-6347

2018-09-12 11:07 UTC, hamzamunir7300 approved these changes
:+1: LGTM

2018-09-12 11:13 UTC, Ayub-Khan commented
Some tests are failing 
ERROR: /edx/app/ecommerce/ecommerce/ecommerce/static/build/bower_components/bootstrapaccessibilityplugin/_site/bs3/test-infra/s3_cache.py Imports are incorrectly sorted.
Those files do not exist on my local.

2018-09-12 12:39 UTC, robrap requested changes
Please let me know if you have questions. The main requests are:
1. Refactor cache key code so we know we are setting/getting with the same key, and we are naming whatever is getting cached. I’m still not clear what the cached value is.
2. Add the test as I described.
Thank you.

2018-09-12 12:39 UTC, robrap commented on ecommerce/extensions/offer/models.py
> +            elif not cached_response.value:
This may be correct (I can’t tell yet), but it seems like there is a larger issue that makes this code brittle.

Note: I’m reviewing from a phone, so if I misread the code and my comments below don’t make sense, just let me know. Also, I know you didn’t write the code that I will be commenting on, but I believe these suggestions will make bugs less likely in the future.

Typically, caching code looks as follows:
```
def get_thing(self, stuff):
     # making the key doesn’t need to be a separate method if it is only used in one method
    thing_cache_key = make_thing_cache_key(stuff)
    thing_cached_response = cache.get_cached_response(thing_cache_key)
    if thing_cached_response.is_found:
        return thing_cached_response.value

    # calculate_thing may not be a separate method if it is only needed here
    thing = calculate_thing(stuff)
    cache.set(thing_cache_key, thing)
    return thing
```

The main differences between my example and the code as I’ve Read it are as follows:
1. The cache key is computed in one place only so you know the same key is used to set and get from the cache. In this code, I don’t see the set, so I presume that is happening elsewhere.
2. In the example above, the name ‘thing’ is used all over to let you know what is being retrieved (and set) from the cache.
3. Even if ‘thing’ wasn’t used in the names, because the calculation of the value and setting it in the cache is all in a single function, you can see what is added to the cache and how a cached value should be used.

If in this case you really only need to know if something is in the cache, you might need the following 3 types of methods:
- get_thing (like the pseudo code I wrote)
- _is_thing_in_cache (returns cached_response.is_found. Do not use the result of get_thing to determine if something was cached.)
- _make_thing_cache_key (used by the above two methods to ensure the same key is used for gets and sets.

I would imagine that some type of refactor would be possible to make this code more clear and less likely to have a bug.

Also, please add a test that fails before any changes were added and passes once you have your fix. This will help ensure we avoid regressions.

Thank you!

2018-09-12 13:22 UTC, robrap commented
Now that I saw the new comments in the ticket, here are two additional things that it would be great to see:
1. The value set in the cache should be consistent if possible.  If this is meant to be a boolean (what is a name for what is being cached), then can it always be a boolean?  Or is the cached value used differently in different places?  Needs some discovery and then probably clean-up.
2. The ticket states this values is getting set with `metadata['cache_key']`.  Do we have access to `metadata['cache_key']` when we are reading from the cache?  If so, that could be the consistent cache key.  If not, then `metadata['cache_key']` would need to be set with the shared `make_XXX_cache_key` method to ensure we always are using the same cache key.

Thank you.

2018-09-12 17:28 UTC, robrap commented on package-lock.json
> +      "integrity": "sha512-L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg==",
I don't think these changes should be needed as part of this PR.

2018-09-13 13:39 UTC, robrap reviewed
Thanks again for the find.

2018-09-13 13:39 UTC, robrap commented on ecommerce/extensions/offer/models.py
> +                    uncached_course_run_ids.append({'id': product_id, 'cache_key': cache_key, 'line': line})
Thanks for the name change.

2018-09-13 13:39 UTC, robrap commented on ecommerce/extensions/offer/models.py
> +            is_found, contains = self._check_catalog_query_contains(cache_key=cache_key)
I think it would be cleaner to do the following:

1. Can you add the following lines before the TieredCache.set() line in the other method:
```
# Convert to int, because this is what memcached will return, and the request cache should return the same value.
# Note: once the TieredCache is fixed to handle this case, we could remove this line.
in_range = int(in_range)
```
This way, get_cached_response() will return the same value every time.

2. I'd go back to the previous TieredCache.get_cache_response call directly from this method, but I'd rename `cached_response` to `in_catalog_range_cached_response`.

2018-09-13 18:42 UTC, Ayub-Khan commented
Done.

2018-09-13 19:13 UTC, robrap approved these changes

2018-09-13 19:25 UTC, merged