[WIP] Add option to use cybersource email for notifications
openedx-unsupported/ecommerce pull request #1914
Opened 2018-09-21 09:30 UTC by kaizoku

This PR will use the email address returned from the CyberSource checkout process to send ecommerce notifications, rather than the user's email address from edx-platform.

**Sandbox URL**: TBD - sandbox is being provisioned.

**Testing instructions**:

1. Complete the purchase of a seat in the sandbox providing a different email address from the one configured in edX during the CyberSource checkout sequence.
2. Check to see that the seat fulfillment notification is sent to the address used on CyberSource.

**Author notes and concerns**:

1. Should this be behind a waffle flag?
2. Is this the right place to store the user email?

**Reviewers**
- [ ] (@UmanShahzad)
- [ ] edX reviewer[s] TBD

2018-09-21 09:30 UTC, edx-webhook commented
Thanks for the pull request, @kaizoku! I've created [OSPR-2627](https://openedx.atlassian.net/browse/OSPR-2627) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2018-09-21 18:47 UTC, natabene commented
Let me know when this is ready for review, @kaizoku .

2018-09-22 03:24 UTC, kaizoku commented
@natabene I can fix the migration issues if we're going to use this approach, but we're wondering if this approach is likely to be upstreamed, or if another method would be preferrable.

Currently this code stores the email provided from CyberSource as a `CharField` on the `ecommerce.core.models.User` model, but we're unsure if edX would want us to extend that model, or perhaps create another table elsewhere. Could you or someone at edX advise on our approach and what would be suitable for upstreaming?

2018-09-24 19:25 UTC, natabene commented
@marcotuts Can you have a look at this?

2018-10-04 02:41 UTC, UmanShahzad commented
@marcotuts @natabene Anyone able to look at this? Note we're mostly trying to see what edX would consider acceptable for what this PR is trying to achieve. If that means the approach needs to change a bit, we can talk about it.

2018-10-10 14:52 UTC, marcotuts commented
I'm not clear on the intent here, so I had a few questions - 
1.) Today we send this notification / email through edx-platform and the proposal is to use some details within cybersource to send this instead? Was cybersource a "channel" / email delivery mechanism already or is this introducing that? 

2.) @nasthagiri may be able to chime in here in case I'm misrepresenting this architectural direction but I believe we'd like to shift to having ACE be aware of all notifications from the platform, regardless of which "channel" (aka Sailthru, Amazon SES, Firebase Cloud Messaging, etc) sends the notification. This will let us eventually provide notification settings and controls for learners. How can we help move closer to this edx-ace usage as part of this PR?

2018-10-10 14:58 UTC, robrap commented
@marcotuts: I think the issue is that the CyberSource account that someone uses to pay (this applies to Paypal and other providers as well), might be a very different account with a different email address.  It might even be a different user, if a parent or someone else's account is used to pay.

I did not look at this PR deeply, but I imagine it is trying to determine where and when we could send notifications to the payer email address that is returned back to us, rather than the email address of the Open edX account being payed for.  I don't know if there are any legal questions as well about usage of this other email address?

Hope this helps.

2018-10-10 15:00 UTC, UmanShahzad commented
@robrap Your interpretation is correct - we have a use case to send an email to the address used on the payment gateway side (in this case, specifically Cybersource, but we'd want to make it generic if possible), not the Open edX side.

cc @kaizoku to expand if necessary.

2018-10-10 18:53 UTC, kaizoku commented
That's correct @robrap and @UmanShahzad, this will sent the receipt email to the email address returned from cybersource instead of the one associated to the user's edX account.

Cybersource itself isn't used to deliver messages, from edX, but this makes it a source for the address used to deliver, in case a different address is provided there, than the one from the user's account.

2018-10-18 06:06 UTC, UmanShahzad commented
With that said, is there any idea how to approach this problem in a way edX would accept?

2018-10-18 17:22 UTC, natabene commented
@edx/arch-review Team, can you have a look at this?

2018-10-18 20:55 UTC, robrap commented
@UmanShahzad @kaizoku: Product needs to weigh-in, but this idea would require extra review because of the legal territory with consequences on PII (Personally Identifiable Information) and GDPR.  It also gets into questions around our permissions to use that email.

2018-10-19 15:57 UTC, macdiesel commented
@stroilova FYI.

2018-11-02 10:23 UTC, UmanShahzad commented
@robrap Makes sense. Just let us know what the result of the legal investigation turns out to be, if it's not too difficult.

2018-11-02 15:27 UTC, natabene commented
@stroilova  Do you want to have a look at this?

2018-11-26 16:30 UTC, marcotuts commented
@macdiesel - Would you mind giving this a review and suggest next steps in terms of approach? This seems related to student privacy and general PII. Initial review can be conceptual and not a code level review. Thanks!

2018-11-28 19:34 UTC, macdiesel commented on ecommerce/core/models.py
> +    cybersource_email = models.CharField(_('Cybersource Email'), max_length=255, blank=True, null=True)
I would prefer this be named something more vendor neutral. Perhaps purchaser email? Also thinking about this, I'm not sure that this email address should be attached to the user object. 

Couldn't this email address change per transaction? It would be better to store this with the transaction I would think.

2018-11-28 19:35 UTC, macdiesel commented on ecommerce/extensions/customer/utils.py
> +        if not user.email or user.cybersource_email:
I would prefer to see the refactor on this pass the email address to this method. The caller of this method should own the logic of which email address to user, not this function.

2018-11-28 19:39 UTC, macdiesel requested changes
In light of GDPR my overall suggestion here would be that we should not store this data if we can avoid doing so. In addition I think there is some re-work that should be done here, please see my comments. 

One suggestion I do have is this: If you want to send the email to the cybersource email address, why store it at all? Would it be possible to take the email address cybersource returns, fire the email (perhaps log or fire an event that the email was sent) and then just not save the information? 

I would prefer a route here that would not store this users email address in the system at all if we can avoid it.

2018-12-03 16:37 UTC, natabene commented
@kaizoku  Please let us know once you have addressed our comments.

2019-02-11 07:07 UTC, kaizoku commented
Thanks @macdiesel, It does make more sense not to store this email.
I've pushed up a WIP new approach which adds a `recipient` argument to the message dispatching methods, and only uses the email returned from cybersource to send off the email, not storing it in the database.

I haven't fully tested this yet, since I wanted to check that this approach was acceptable before making sure it's fully fleshed out. Does this method seem alright?

One current oddity is that the email is extracted from the request in the signal handler, which is not cybersource specific, as it's in ` ecommerce/extensions/checkout/signals.py`.

Instead we could change the `post_checkout` signal to also send an email address to be used for the receipt, and then choose the email in the cybersource views instead. Is that preferrable to checking the `request.POST` from the signal handler?

2019-02-22 18:15 UTC, marcotuts commented
@macdiesel, @kaizoku  - I'm going to push this past product review and leave this in your hands to find a path that makes this configurable and eliminates PII concerns. It sounds like we are making progress toward this, nothing else on my side from a product standpoint. If @macdiesel you'd like to bring me back into this conversation for whatever reason lmk. Thanks!

2019-04-08 15:57 UTC, kaizoku commented
@macdiesel any chance you've been able to look at this WIP? Just wanted to make sure it's on the right track before I finalize and make sure it's all tested and working well.

2019-04-08 16:44 UTC, macdiesel commented
@kaizoku I'm ok with this. I however am unable to merge in to the ecommerce repo. @cpennington can the rev team take over this PR?

2019-04-08 17:32 UTC, cpennington commented
Yup, we'll take it.

2019-04-08 17:39 UTC, cpennington approved these changes
Except for the currently unused changes in `checkout/signals.py`, this looks good to me.

2019-04-08 17:39 UTC, cpennington commented on ecommerce/extensions/checkout/signals.py
> +                recipient = request.POST.get('req_bill_to_email', order.user.email)
This isn't being used. Is it left over from a previous version of the code?

2019-04-08 17:47 UTC, macdiesel approved these changes

2019-04-12 16:26 UTC, cpennington commented on ecommerce/extensions/checkout/signals.py
> +                recipient = request.POST.get('req_bill_to_email', order.user.email)
It looks like this needs to be passed to `send_notification` below.

2019-04-12 16:33 UTC, cpennington requested changes
Reading this PR again more closely, I noticed that currently, the *only* notification being affected is purchase receipt for a *credit* purchase. Was this the intention?

2019-04-24 07:30 UTC, kaizoku commented on ecommerce/extensions/checkout/signals.py
> +                recipient = request.POST.get('req_bill_to_email', order.user.email)
Ah yep, thanks. This was still WIP so I hadn't tested everything yet.

2019-04-24 07:54 UTC, kaizoku commented
@cpennington, right, we're not intending to change notifications for enrollment coupons for instance, if that's what you mean.

I addressed the test issues and this is ready for another review.

2019-04-24 18:17 UTC, cpennington approved these changes

2019-04-25 14:35 UTC, merged

2019-04-25 14:35 UTC, edx-webhook commented
@kaizoku 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/1914&entry.1484655318=https://github.com/kaizoku&entry.752974735=2018-09-21+09:30&entry.1917517419=2019-04-25+14:35&entry.2133058324=Yes) so we can improve your experience in the future.