Learner 6478
openedx-unsupported/ecommerce pull request #1931
Opened 2018-10-05 11:16 UTC by Ayub-Khan

Coming soon.

2018-10-05 14:09 UTC, robrap commented
@Ayub-Khan: I added more notes on the ticket about potential approach for this issue.  Thank you for your work on this.

2018-10-15 13:13 UTC, robrap commented
@jmyatt: Can you review this?

2018-10-15 16:36 UTC, jmyatt requested changes

2018-10-15 16:36 UTC, jmyatt commented on ecommerce/management/utils.py
> +                return False
why not log a warning here, noting the order id that we attempted to fulfill?

2018-10-15 16:36 UTC, jmyatt commented on ecommerce/management/utils.py
> +            successful_transaction = basket.paymentprocessorresponse_set.filer(
filer --> filter

2018-10-15 16:36 UTC, jmyatt commented on ecommerce/management/utils.py
> +                basket.clear_vouchers()
so will this result in the payment amount and order amount being out of sync?  I agree that is the best way to handle the issue, so that the order still goes through, just want to understand the expected outcome.  Also the prod-edx-verify_transactions will flag these so we may need to manually ignore those instances after running this job

2018-10-15 16:36 UTC, jmyatt commented on ecommerce/management/utils.py
> +                logger.info('Basket %d do not have any successful payment response', basket_id)
"do" --> "does"

2018-10-15 16:36 UTC, jmyatt commented on ecommerce/management/utils.py
> +            successful_payment_notification = successful_transaction[0]
I think continuing with the fulfillment in the case where there are multiple successful transactions logged is the right thing to do (as opposed to short-circuiting as the prior code did).  I'm just not sure about arbitrarily selecting the first transaction.  Maybe leave this as is (selecting the 0-index transaction), but log a warning if we have more than one transaction id among the successful transactions found?  Borrowing from the prior code, this would be something like:

```
unique_transaction_ids = set([response.transaction_id for response in successful_transaction])
if len(unique_transaction_ids) > 1:
    logger.warning('Basket %d has more than one successful transaction id, using the first one', basket_id)
```

2018-10-15 16:36 UTC, jmyatt commented on ecommerce/management/utils.py
> +                card_type=successful_payment_notification.response.get('req_card_type', 'Paypal Account'),
for Cybersource, I think the value we want is not the raw `req_card_type` but rather `CYBERSOURCE_CARD_TYPE_MAP.get(req_card_type)`

2018-10-15 16:36 UTC, jmyatt commented on ecommerce/management/utils.py
> +                logger.info('Successfully create order for basket %d'. basket.id)
'create' --> 'created'

2018-10-17 06:27 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +                basket.clear_vouchers()
Yes. Payment amount and order amount will be out of sync.

2018-10-17 06:27 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +            successful_transaction = basket.paymentprocessorresponse_set.filer(
done

2018-10-17 06:27 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +                logger.info('Basket %d do not have any successful payment response', basket_id)
done

2018-10-17 06:33 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +            successful_payment_notification = successful_transaction[0]
done

2018-10-17 06:58 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +                return False
@jmyatt above line runs the following code which have extensive logging 
https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/fulfillment/api.py#L21
thats why i did not log any thing here. should i add a log here too.

2018-10-17 07:00 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +                card_type=successful_payment_notification.response.get('req_card_type', 'Paypal Account'),
done

2018-10-17 07:01 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +                logger.info('Successfully create order for basket %d'. basket.id)
done

2018-10-17 14:59 UTC, jmyatt commented on ecommerce/management/utils.py
> +                return False
ah right - no, you're right, the existing logging should be enough

2018-10-17 15:00 UTC, jmyatt commented on ecommerce/management/utils.py
> +                basket.clear_vouchers()
ok makes sense

2018-10-18 12:41 UTC, Ayub-Khan commented
kindly ignore the i18n changes i will remove them.

2018-10-18 13:10 UTC, jmyatt commented on ecommerce/management/utils.py
> +            order = None
ah good catch

2018-10-18 13:12 UTC, jmyatt commented on ecommerce/management/utils.py
> +            successful_payment_notification = successful_transaction[0]
I think you still want to de-dup these on `response.transaction_id` - that's actually the case we want to warn about.

2018-10-18 13:19 UTC, jmyatt commented on ecommerce/management/utils.py
> +                    'Paypal Account')
looking at this again, it seems you have the Paypal values for card_number and card_type swapped - the existing code uses 'Paypal Account' for card_number and None for card_type.  So I think these lines should be:

```
    card_number=successful_payment_notification.response.get('req_card_number', 'Paypal Account'),
    card_type=CYBERSOURCE_CARD_TYPE_MAP.get(
        successful_payment_notification.response.get('req_card_type'), None)
```

2018-10-23 12:49 UTC, jmyatt approved these changes

2018-10-30 10:17 UTC, merged