Learner 6478 basket api
openedx-unsupported/ecommerce pull request #1938
Opened 2018-10-17 06:11 UTC by Ayub-Khan

Added basket api.
Will write tests after first review.
for more details check ticket. 

Review @robrap @waheedahmed

2018-10-17 06:12 UTC, Ayub-Khan commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^basket-edit/', include(BASKET_URLS, namespace='baskets')),
@robrap Im not sure if this is the right thing to do. Do we use those api views.

2018-10-18 14:37 UTC, robrap commented
@Ayub-Khan: Ultimately, can you provide more details/screenshots on how you expect Customer Support to use this?  
Also, let us know when this is ready and we'll find a reviewer.  Thanks.

2018-10-29 10:31 UTC, Ayub-Khan commented
@robrap  The idea is to give this api to support team so that they could check what went wrong against a basket. In case if we are not able to create an order for a basket we will redirect the alert to support team. They will use this to check if we received payment for the order other related information to upate the student in right track and use the management view to create the order for user.

2018-10-29 13:23 UTC, robrap commented
@jmyatt: This PR is a continuation of the work for [LEARNER-6478](https://openedx.atlassian.net/browse/LEARNER-6478).

2018-11-12 11:45 UTC, waheedahmed requested changes

2018-11-12 11:45 UTC, waheedahmed commented on ecommerce/extensions/api/v2/urls.py
> +router.register(r'basket-details', basket_views.BasketViewSet, base_name='basket')
This API endpoint suggests that we are viewing a single basket details but I believe it's not the case, right? I believe we should update it more precise name, `basket-list` maybe?

2018-11-12 11:52 UTC, Ayub-Khan commented on ecommerce/extensions/api/v2/urls.py
> +router.register(r'basket-details', basket_views.BasketViewSet, base_name='basket')
yes. i agree as this shows basket list it would be appropriate. But as the basket includes some other details. and we want to use it for single baskets. basket-details will be more appropriate.

2018-11-12 11:57 UTC, waheedahmed approved these changes

2018-11-12 12:30 UTC, merged