WIP: Pass email_opt_in through fulfillment flow
openedx-unsupported/ecommerce pull request #1942
Opened 2018-10-23 14:04 UTC by bbaker6225

2018-10-23 14:32 UTC, bbaker6225 commented on ecommerce/extensions/fulfillment/modules.py
> +            A supported list of unmodified lines associated with "Course Entitlement" products.
"ENtitlement" was annoying me

2018-10-24 15:43 UTC, bbaker6225 commented
I'm consistently getting the error message "WebDriverException: Message: newSession", but it definitely does not seem related to any of my changes. Not sure how to get these to pass

2018-10-24 18:17 UTC, jmyatt commented on ecommerce/extensions/fulfillment/modules.py
> +            A supported list of unmodified lines associated with "Course Entitlement" products.
👍 good call

2018-10-24 18:39 UTC, jmyatt requested changes

2018-10-24 18:39 UTC, jmyatt commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +        basket_attribute, _ = BasketAttributeType.objects.get_or_create(name=EMAIL_OPT_IN_ATTRIBUTE)
nit: this variable should be named basket_attribute_type

2018-10-24 18:39 UTC, jmyatt commented on ecommerce/extensions/checkout/mixins.py
> +                email_opt_in=email_opt_in
with the current (v0.6.0) version of ecommerce-worker in requirements, does this call throw an `unexpected keyword argument` exception?

2018-10-24 18:39 UTC, jmyatt commented on ecommerce/extensions/fulfillment/api.py
> +        email_opt_in (Bool): Whether the user should be opted in to emails as
this should be `bool` (lowercase).  Same for the other implementations of `fulfill_product`

2018-10-24 18:39 UTC, jmyatt commented on ecommerce/extensions/fulfillment/modules.py
> +    def fulfill_product(self, order, lines, email_opt_in=False):  # pylint: disable=arguments-differ
do you need this pylint directive, since the abstract method and all concrete implementations name this argument?

2018-10-25 21:46 UTC, jmyatt commented
version 0.7.0 of ecommerce-worker is now available on Pypi (and deployed to stage).  So the remaining steps with this PR are:
 - update worker version in requirements
 - rebase against master after https://github.com/edx/ecommerce/pull/1945 is merged

then we'll figure out the best flow for testing this on stage in light of the other ecommerce PRs that need to go out.  We may need to merge this, test on stage, then revert in order to wait for the ecom worker deployment to Prod to be done by DevOps.

2018-10-26 13:16 UTC, bbaker6225 commented
Updated requirements and rebased

2018-10-26 18:00 UTC, jmyatt approved these changes

2018-10-26 18:01 UTC, merged