Skip broken selenium tests
openedx-unsupported/ecommerce pull request #1945
Opened 2018-10-24 20:33 UTC by jmyatt

2018-10-24 21:53 UTC, robrap commented
Is there an associated ticket? What are the implications of this? Is it temporary? Why not just delete them like in the Flaky Yest Process?

2018-10-25 14:12 UTC, jmyatt commented
@robrap yes I think we need to follow the Flaky Test process here to avoid these broken tests blocking deployment of time sensitive work, since a fix for this will take some digging

2018-10-25 15:14 UTC, robrap requested changes
If I understand correctly, you are removing some older skipIf calls + the 4 new failing tests?

2018-10-25 15:14 UTC, robrap commented on ecommerce/extensions/dashboard/refunds/tests/test_acceptance.py
> +from unittest import skip, skipIf
Do you need to remove this skipIf?

2018-10-25 15:24 UTC, jmyatt commented
@robrap this commit removed the 4 test classes that inherit the failing call to WebDriver() - those are in the base classes `RefundAcceptanceTestMixin` and `OrderViewBrowserTestBase`.  not sure this change is the right thing to do, just wanted to confirm that it would avoid the travis failure.  Will remove the unused import to avoid the pylint failure now, just to get this to green but I'm thinking it might also be worth trying a version upgrade on selenium or pytest-selenium.  But that's just a guess as I don't see any info on this in the wild

2018-10-25 15:30 UTC, robrap commented
@jmyatt: This also removes `test_retry_fulfillment` which was never really running anyway, right?
1. I think it is ok to remove these while we figure out the real fix, if we first learn what these tests are doing, whether or not we have e2e coverage, and/or what the steps are for someone to manually test these.
2. Ultimately, the real fix is probably to get these working, and if that is faster than #1, we can do that instead.  But, I'm guessing not.

2018-10-25 15:43 UTC, jmyatt commented
@robrap by my count, this removes:
6 Order tests, 2 of which were being skipped
8 Refund tests, 4 of which were being skipped

2018-10-25 15:56 UTC, robrap commented
Are 2 of these unnecessarily getting removed?
In this PR: https://github.com/edx/ecommerce/pull/1941
In Travis: https://travis-ci.org/edx/ecommerce/jobs/446169438
I see: "FAILED (SKIP=2, errors=4)"

2018-10-25 16:13 UTC, jmyatt commented
I think that error count is inaccurate (it's counting classes as opposed to tests) because there a class level block that's failing for 4 different classes - 2 each extending from the 2 problem base classes.  I also don't understand the skip count of 2 - there are 2 affected tests with the `skip` decorator and 2 with `skipIf` (travis)

2018-10-25 16:18 UTC, robrap approved these changes
This is ready to merge as soon as we have recommendations for manual testing required.

I can merge with the codecov issue if you can't merge.

2018-10-25 16:20 UTC, jmyatt commented
Codecov is upset for a non browser test related loss of coverage.  I'll try to rework these tests so that we leave the non browser related tests alone.  Then I'll try to assess the impact of removing these tests as you described @robrap

2018-10-25 17:35 UTC, jmyatt commented
@robrap this passed tests and checks - I just re-pushed in order to squash.  Updating the Jira ticket now with manual testing steps in the absence of these tests

2018-10-25 20:49 UTC, jmyatt commented
@robrap let's go with this approach.  TestEng has not seen this issue but has supplied some ideas on digging deeper to try to fix it.  I added those notes plus detail on how we can manually test these aspects (if we think that's necessary) in the Jira ticket.  I also attempted switching to chrome, safari, and ie webdrivers, all of which had their own OS related complications (probably why we were using Firefox in the first place).

2018-10-26 13:15 UTC, merged