LEARNER-6478 fixed bug
openedx-unsupported/ecommerce pull request #1953
Opened 2018-10-31 08:31 UTC by Ayub-Khan

Fix the following bug.
Traceback (most recent call last):
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
    return wrapped(*args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/contrib/auth/mixins.py", line 116, in dispatch
    return super(UserPassesTestMixin, self).dispatch(request, *args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/newrelic/hooks/framework_django.py", line 940, in wrapper
    return wrapped(*args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/edx/app/ecommerce/ecommerce/ecommerce/management/views.py", line 44, in post
    fulfilled = FulfillFrozenBaskets().fulfill_basket(basket_id=basket_id, site=request.site)
  File "/edx/app/ecommerce/ecommerce/ecommerce/management/utils.py", line 136, in fulfill_basket
    card_number=json.loads(successful_payment_notification.response).get(
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

2018-11-05 15:25 UTC, jmyatt requested changes

2018-11-05 15:25 UTC, jmyatt commented on ecommerce/management/utils.py
> +    def get_payment_notification(basket):
good call on organizing this logic (and the valid basket stuff) into discrete functions

2018-11-05 15:25 UTC, jmyatt commented on ecommerce/management/utils.py
> +    def is_valid_basket(basket_id):
maybe this should be name `get_valid_basket` since it returns either a valid basket or None

2018-11-05 15:25 UTC, jmyatt commented on ecommerce/management/utils.py
> +        :return: first successful payment notification
would be good to mention that None could be returned

2018-11-06 09:47 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +    def is_valid_basket(basket_id):
done

2018-11-06 09:47 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> +        :return: first successful payment notification
done

2018-11-07 10:54 UTC, waheedahmed commented on ecommerce/management/utils.py
> -                card_number=json.loads(successful_payment_notification.response).get(
If response was already a `JSONField`, why we were calling `json.loads()` here? Just curious.

2018-11-07 10:56 UTC, waheedahmed approved these changes
LGTM, just one question out of curiosity.

2018-11-07 11:15 UTC, Ayub-Khan commented on ecommerce/management/utils.py
> -                card_number=json.loads(successful_payment_notification.response).get(
my mistake.

2018-11-07 11:26 UTC, merged