Adds Middlewares to debug Request/Session objects
openedx-unsupported/ecommerce pull request #1967
Opened 2018-11-05 09:23 UTC by adeelkhan

These are temporary middlewares used to debug
issue of no state available inside session by
inspecting & logging request/session loaded
during authentication on ecommerce via lms.

[LEARNER-6226](https://openedx.atlassian.net/browse/LEARNER-6226)

2018-11-05 13:49 UTC, robrap commented
Before adding additional logging, I just want to make sure you are aware of what was added to NewRelic.

See:

- [Authentication Related Metrics](https://openedx.atlassian.net/wiki/spaces/AC/pages/807371420/Authentication+Related+Metrics)
  - Note the info about `tripId` which can be useful to follow a transaction across services.
- [More on all Custom Metrics (including other Authentication Metrics)](https://openedx.atlassian.net/wiki/spaces/PERF/pages/54362736/Custom+Metrics+in+New+Relic)

2018-11-08 11:13 UTC, adeelkhan commented
@robrap Going through the above documentation i couldn't find anything related to sso that is done via openid. The authentication section in the doc is related to DOT/DOP based access. As per my understanding DOT/DOP are used for api request and not for sso and the existing metrics isn't logging anything related to it. I want to log the flow when user is redirected to ecommerce via lms during authentication.

2018-11-08 14:53 UTC, robrap commented
Thanks @adeelkhan.  I don't want you to have to over-invest if this is just temporary debugging help.  Here's what I'd like to see:
1. Please add a waffle switch to turn on/off logging.  This will be useful if we find that you get way too many logs.
2. Add try blocks to protect again any coding issues you may have missed.
3. Manually test on stage once this is ready.  (This may require coordination, because I may need to merge it due to the codecov issue.)

2018-11-13 12:30 UTC, adeelkhan commented
@robrap I have made changes for pt#1 and pt#2. Please review it when possible. thanks

2018-11-13 23:32 UTC, robrap reviewed
Is the session_key code printing the session id? Is this a security concern? Do you have sample output?

Also, the NewRelic request metrics added were for all requests, so you may have some data available already, unless possibly it is for errors.

Again, because this is temporary, I’d do whatever you need as long as there isn’t a security concern.

2018-11-15 19:43 UTC, robrap requested changes
Note the security concern.  Thanks.

2018-11-15 19:43 UTC, robrap commented on ecommerce/social_auth/middleware.py
> +            session_key = str(request.session.session_key)
I confirmed the security concern here, and we definitely don't want to log anything that could enable someone to steal a session.  If this info is absolutely needed, you could use a one-way hash to encrypt this info, and someone couldn't reverse it.

2018-11-15 19:47 UTC, robrap commented on ecommerce/social_auth/middleware.py
> +    log.info('-----------------Inspecting Request:-------------')
FYI: I'll leave it to you to determine what is useful, but I would imagine you would want a single log message containing everything you want to output, otherwise these messages could get intermingled with other calls. Maybe Splunk makes it simple for you and you plan on using IP or something to correlate?

2018-11-16 07:30 UTC, adeelkhan commented on ecommerce/social_auth/middleware.py
> +            session_key = str(request.session.session_key)
Yes that was a concern in my mind too, that is why i am logging just a part of session key.  I think hashing is good idea, that would remove possibility of exposing session key info all together.

2018-11-16 09:59 UTC, adeelkhan commented on ecommerce/social_auth/middleware.py
> +    log.info('-----------------Inspecting Request:-------------')
thanks for raising this. Ideally i think a single log message is the right solution and yes there must be a way to correlate request/response logs with IP.  I'll implement that too.

2018-11-16 10:01 UTC, robrap reviewed
Feel free to complete the review process locally and have Waheed merge when ready. Thanks.

2018-11-16 10:01 UTC, robrap commented on ecommerce/social_auth/middleware.py
> +            session_key = str(request.session.session_key)
Yes. Please either hash this if you think it is necessary, or remove it. It was also pointed out that the IP might be a good enough proxy for the user. So, you could try landing this more quickly without hashed session ID and try using the IP and see if you have enough info that way, and if not, you can add more.

In all cases, I think you have enough info to review and land this without further review from Cambridge. 

Good luck getting to the bottom of things.

2018-12-20 19:41 UTC, robrap commented
@adeelkhan: Are you still pursuing this or should it be closed?

2018-12-20 20:10 UTC, adeelkhan commented
@robrap Yup. Was stuck in some other more important tickets so had to switch my attentions to them, but now have time to look into this. Secondly exploring a possibility of not using this merge at all as some one was facing the same problem and thought about first knowing their resolutions and fixing things at social-auth package level as the person is claiming. For now i am not able to reproduce above issue by any configuration of package. I have no intention to merge this or next week, until i am dead sure that we really need to merge to know more.

2018-12-20 20:48 UTC, robrap commented
Thanks.  We were trying to do some PR clean-up.  Feel free to close and reopen when and if you need this if you want.  Good luck.

2019-01-25 10:00 UTC, closed without merging