Enterprise coupons overview
openedx-unsupported/ecommerce pull request #1974
Opened 2018-11-09 11:56 UTC by mushtaqak

The purpose of this PR is to add backend support for listing coupons for an enterprise needed for edx-portal.

[Backend API for Coupon Overview - ENT-1260](https://openedx.atlassian.net/browse/ENT-1260)

2018-11-13 10:32 UTC, mushtaqak commented
@brittneyexline Can you have a very quick look at the following sample API response and see if are going in correct direction.
```python
{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "end_date": "2019-03-08T00:00:00Z",
            "id": 2,
            "max_uses": null,
            "num_uses": 0,
            "quantity": 1,
            "start_date": "2018-11-12T00:00:00Z",
            "title": "TESt2",
            "voucher_type": "Single use"
        },
        {
            "end_date": "2019-02-01T00:00:00Z",
            "id": 1,
            "max_uses": null,
            "num_uses": 0,
            "quantity": 100,
            "start_date": "2018-11-12T00:00:00Z",
            "title": "TEST_COUPON",
            "voucher_type": "Multi-use"
        }
    ]
}
```
Esp. about `% of available Code redemptions available that have been redeemed.` part mentioned in the PR description. I mean, we don't need to calculate percentage here, we just need to send the the data to front-end, right?

2018-11-13 16:34 UTC, adamstankiewicz commented
> Esp. about `% of available Code redemptions available that have been redeemed.` part mentioned in the PR description. I mean, we don't need to calculate percentage here, we just need to send the the data to front-end, right?

Yeah, the front-end will calculate the percentage of redemptions used/available.

2018-11-13 16:36 UTC, adamstankiewicz commented
@mushtaqak @brittneyexline Will we be able to know through this API whether any of the codes have an error (e.g., undeliverable email)? The front-end has an assumption that the API response for the coupons will contain a boolean field like `has_error` to determine whether we should show an error state for a coupon.

2018-11-13 16:44 UTC, adamstankiewicz commented
@mushtaqak In the above example API response, do any of those fields align with the number of unassigned codes remaining? Is it the `quantity` field?

See the below screenshot (i.e., "Unassigned Codes") where this data will be used:

![image](https://user-images.githubusercontent.com/2828721/48428394-ecb0e180-e738-11e8-8c0b-c5d126283cf9.png)

2018-11-13 16:48 UTC, brittneyexline commented
@adamstankiewicz i think including the error at this level is a question of what the ui needs. however, it probably won't be implemented with this change since we haven't implemented notifying or assigning users yet.

2018-11-13 16:49 UTC, robrap commented
@adamstankiewicz @mushtaqak: It would be great if names can be updated to be more readily understandable.  So if it is `quantity`, could we rename to `num_unassigned` (or something like that)?

2018-11-13 16:49 UTC, adamstankiewicz commented
> @adamstankiewicz i think including the error at this level is a question of what the ui needs. however, it probably won't be implemented with this change since we haven't implemented notifying or assigning users yet.

Yeah, that makes sense. Just making sure it can eventually be supported in this API 😄

2018-11-13 16:51 UTC, adamstankiewicz commented
> @adamstankiewicz @mushtaqak: It would be great if names can be updated to be more readily understandable. So if it is `quantity`, could we rename to `num_unassigned` (or something like that)?

Agreed 👍

2018-11-13 17:36 UTC, mushtaqak commented
@adamstankiewicz `quantity` is `# of codes` mentioned in the ticket. However, I think the mockups has changed, so we can either remove it or UI won't use it (atleast not in the overview screen) 

About, `Unassigned Codes`, it's functionality part is not implemented yet (scoped in some other JIRA story). So, I will add just the placeholder in this PR.

Regarding error status, can you explain the a bit more, what info front end would need? copoun status? Sorry, I don't have much of info on coupon/code terms.

2018-11-13 18:06 UTC, adamstankiewicz commented
@mushtaqak Sounds good about the placeholder for number of unassigned codes. If we do keep the `quantity` field, can we rename it to be more explicit about what it's referring to?

As for the error status, the UI needs to know whether a code(s) within a coupon contains an error to properly prompt the user that an error exists. The coupon doesn't need to know what the actual error is; just that one exists. It could just be a boolean field in the API response, like `has_error: true`. 

For reference, this is the coupon error state in the UI:

![image](https://user-images.githubusercontent.com/2828721/48433138-5da9c680-e744-11e8-87de-79505e8654e4.png)

2018-11-14 14:52 UTC, mushtaqak commented
@brittneyexline @adamstankiewicz Can you guys review this?

2018-11-14 22:44 UTC, brittneyexline reviewed
On the right track!

2018-11-14 22:44 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        if enterprise_id:
nit: more readable if this is an if/else statement

2018-11-14 22:44 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            - Copoun ID
nit: typo (Coupon)

2018-11-14 22:44 UTC, brittneyexline commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +    def setUp(self):
you'll have to rebase on my branch again - i have just added a bunch of tests so some of this is redundant

2018-11-14 22:44 UTC, brittneyexline commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        self.coupon3 = self.create_get_coupon(data3)
i'd prefer if we move these coupon creations to the test method that needs them.

2018-11-14 22:44 UTC, brittneyexline commented on ecommerce/extensions/api/serializers.py
> +        offer = retrieve_offer(obj)
we will need to revisit this because many vouchers will have two offers, and we'll probably want to add together the num_applications on each offer to get the actual total number of applications.

2018-11-15 14:04 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +        offer = retrieve_offer(obj)
@brittneyexline Do you think, this will be covered in this PR? What do we have to do? I looked at a couple of places in codebase, do you think something like this would be needed?

```python
def redemptions(self, obj):
        voucher = getattr(obj, 'voucher', obj)
        offer = voucher.best_offer
        redemption_count = offer.num_applications

        if voucher.usage == Voucher.SINGLE_USE:
            max_coupon_usage = 1
            redemption_count = voucher.num_orders
        elif voucher.usage != Voucher.SINGLE_USE and offer.max_global_applications is None:
            max_coupon_usage = 10000
        else:
            max_coupon_usage = offer.max_global_applications

        return {
            'used': redemption_count,
            'available': max_coupon_usage,
        }
```

2018-11-16 11:02 UTC, mushtaqak commented
@brittneyexline I have addressed all of your feedback except the `num_uses` where I have asked the question. Rest this is ready for your review again.

2018-11-16 14:32 UTC, mushtaqak commented
@georgebabey Can you review this as well ?

2018-11-16 16:16 UTC, brittneyexline reviewed
looking good! the next thing i would like to see is if you could deploy this on the business sandbox and write out some test instructions with different test cases.

2018-11-16 16:16 UTC, brittneyexline commented on ecommerce/extensions/api/serializers.py
> +        offer = retrieve_offer(obj)
for now let's leave it as is... i haven't quite figured out how we're going to manage these things when we have to switch which offer we use

2018-11-20 10:28 UTC, mushtaqak commented
@brittneyexline [Sandbox](https://ecommerce-entcoupon.sandbox.edx.org/api/v2/coupons/enterprise/cf246b88d5f64908a522fc307e0b0c60/overview/) is ready

2018-11-20 15:31 UTC, adamstankiewicz commented
@mushtaqak @brittneyexline Just taking a look at the API response, and all the data the frontend needs seems to be there! Nice 👍

2018-11-20 16:09 UTC, adamstankiewicz commented
It looks like the API response is paginated (e.g., has `prev` and `next` fields), but it doesn't have a `num_pages` field like API responses in our other services. Is this expected?

2018-11-22 09:39 UTC, mushtaqak commented
@adamstankiewicz I guess REST APIs have a `count` field (not the`num_pages`). Below is the response containing fields returned ...
```python
{
    "count": ...,
    "next": ...,
    "previous": ...,
    "results": [...]
}

2018-11-29 16:21 UTC, brittneyexline approved these changes
i think this looks good overall! i have a couple of small suggestions, and in particular the num_uses field should be updated before merging. this is also blocked on merge/release by https://github.com/edx/ecommerce/pull/1969 getting merged/released, so i will try to work with @georgebabey to get that released soon.

2018-11-29 16:21 UTC, brittneyexline commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        Test if we get correct enterprise coupoun overview data.
nit: coupoun should be coupon

2018-11-29 16:21 UTC, brittneyexline commented on ecommerce/extensions/api/v2/urls.py
> +router.register(r'coupons/enterprise/(?P<enterprise_id>.+)', enterprise_views.EnterpriseCouponViewSet,
should we add /overview to the pattern so that we match exactly?

2018-11-29 16:21 UTC, brittneyexline commented on ecommerce/extensions/api/serializers.py
> +        offer = retrieve_offer(obj)
after pulling some data for an audit of the coupons yesterday, i remembered that there is a `num_orders` field on the voucher - i think using this value will give us the best value for num_uses without having to account for the multiple conditional offers.

2018-11-29 21:31 UTC, brittneyexline commented on ecommerce/extensions/api/v2/urls.py
> +router.register(r'coupons/enterprise/(?P<enterprise_id>.+)', enterprise_views.EnterpriseCouponViewSet,
i noticed that the paths are slightly different between yours and Ammar's PR - here it is `coupons/enterprise` and on his and for the other endpoints it is `enterprise/coupons`. i think you should make sure the path is consistent with the other endpoints.

2018-12-07 20:41 UTC, georgebabey commented
@mushtaqak Looks like this is ready to go but theres some conflicts to resolve. Can you update this and I'll get it merged in.

2018-12-07 20:49 UTC, georgebabey requested changes

2018-12-07 20:49 UTC, georgebabey commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +            reverse('api:v2:enterprise-coupons-(?P<enterprise-id>.+)/overview-list',
Are you sure this is correct? It looks like it should be `/overview` instead of `/overview-list` https://github.com/edx/ecommerce/pull/1974/commits/91fcfa83978643ebb6d3dd20bf87016f2746750b#diff-141fa9c110c00aba0d7f70839c4a77bbR179

2018-12-10 10:27 UTC, mushtaqak commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +            reverse('api:v2:enterprise-coupons-(?P<enterprise-id>.+)/overview-list',
Yes, actually ViewSet creates url route for the endpoint. While the URL pattern name is `api:v2:enterprise-coupons-(?P<enterprise-id>.+)/overview-list`, the actual url pattern is `api/v2/enterprise/coupons/<enterprise-id>/overview/`

2018-12-10 11:47 UTC, mushtaqak commented
@georgebabey This is ready to merge!

2018-12-11 13:35 UTC, georgebabey approved these changes

2018-12-11 13:36 UTC, merged