Cache catalog query contains call
openedx-unsupported/ecommerce pull request #1990
Opened 2018-11-26 16:16 UTC by BenjiLee

2018-11-26 17:34 UTC, robrap requested changes

2018-11-26 17:34 UTC, robrap commented on ecommerce/enterprise/migrations/0004_add_enterprise_offers_for_coupons.py
> +
Why are you messing with migrations?  Was this isort?

2018-11-26 17:34 UTC, robrap commented on ecommerce/extensions/offer/models.py
> +        if not applicable_range and applicable_range.catalog_query is None:
`NOT (X AND Y) => NOT X OR NOT Y`
Should this be?:
```
if not applicable_range or (applicable_range and applicable_range.catalog_query is None):
```
Were tests failing?  If not, do we have a coverage issue?

2018-11-26 17:34 UTC, robrap commented on ecommerce/extensions/offer/models.py
> +            cache_key = get_cache_key(course_run_ids=','.join([metadata['id'] for metadata in sorted(course_run_ids)]),
1. Could this be a separate method with a docstring?
2. You dropped the comment (which wasn't really great anyway).  I'm not clear what this is really doing, and what these course run ids and course uuids would be.  Maybe I need to review more of this code?
3. Consider using local variable like `course_run_id_list=','.join([metadata['id'] for metadata in sorted(course_run_ids)]` in the two calls below.

2018-11-26 17:34 UTC, robrap commented on ecommerce/settings/base.py
> +CATALOG_QUERY_CONTAINS_TIMEOUT = 3600  # Value is in seconds.
Can you rename to `CATALOG_QUERY_CONTAINS_CACHE_TIMEOUT`?

2018-11-26 17:36 UTC, BenjiLee commented on ecommerce/enterprise/migrations/0004_add_enterprise_offers_for_coupons.py
> +
This was isort :/

2018-11-26 17:36 UTC, BenjiLee commented on ecommerce/extensions/offer/models.py
> +        if not applicable_range and applicable_range.catalog_query is None:
Not sure. I think this changed the behaviour. currently looking into this now.

2018-11-26 17:38 UTC, BenjiLee commented on ecommerce/extensions/offer/models.py
> +            cache_key = get_cache_key(course_run_ids=','.join([metadata['id'] for metadata in sorted(course_run_ids)]),
1. I consider that as well. I think it will be helpful to get context of what the api is doing
2. #1 should clear this up. 
3. will do

2018-11-26 17:39 UTC, BenjiLee commented on ecommerce/settings/base.py
> +CATALOG_QUERY_CONTAINS_TIMEOUT = 3600  # Value is in seconds.
will do

2018-11-26 17:46 UTC, robrap commented on ecommerce/extensions/offer/models.py
> +        if not applicable_range and applicable_range.catalog_query is None:
It changed it because you had an `and` instead of an `or`.

2018-11-26 19:33 UTC, BenjiLee commented on ecommerce/extensions/offer/models.py
> +        if not applicable_range and applicable_range.catalog_query is None:
Tests were failing which is why I wasn't sure if my change was correct.

2018-11-27 13:53 UTC, BenjiLee commented
Closing PR. Looks like my cache isn't working because there is a different cache thats working correctly.

2018-11-28 16:02 UTC, BenjiLee commented
@robrap This PR might still be relevant. I think there's something weird with the current way this caching works today.

2024-11-04 16:02 UTC, closed without merging