WIP: added assignment email api
openedx-unsupported/ecommerce pull request #1998
Opened 2018-11-29 15:48 UTC by irfanuddinahmad

2018-11-29 15:54 UTC, robrap commented
1. Please update names and/or comments to make it more clear what this is for.  What is an "assignment email"?
2. Please ensure to get this reviewed by @macdiesel or someone regarding GDPR and handling of PII data (e.g. email).

2018-12-19 21:22 UTC, brittneyexline reviewed
looking good so far!

2018-12-19 21:22 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        *offer_id*
i would call this offer_assignment_id to avoid confusion with potentially referring to the offer object itself

2018-12-19 21:22 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        update_status.update(extra_status)
what is `extra_status` if `email_status != 'success'`?

2018-12-19 21:22 UTC, brittneyexline commented on ecommerce/extensions/offer/models.py
> +class OfferAssignmentEmail(models.Model):
i would call this `OfferAssignmentEmailAttempt` to be a little clearer. also not sure if we should attempt to think about other email mechanisms besides sailthru and make this an abstract model that is inherited by a Sailthru specific model? could be overkill right now though...

2018-12-19 21:22 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Sends assignment email(s) to Learners."""
might be useful to explain for each of these Views who is expected to call these apis

2018-12-19 21:22 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    permission_classes = (IsAuthenticated,)
should this also include `IsAdminUser`?

2018-12-19 21:22 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Receive Sailthru bounce-api POST"""
if this is going to be received through Sailthru, will we need to do anything special to make sure this endpoint is accessible from outside our usual services?

2018-12-20 07:01 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        *offer_id*
@georgebabey This would require changes to the ecommerce-worker. Please advise.

2018-12-20 07:06 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        update_status.update(extra_status)
The API is only called when email is a success, otherwise the status in offer_assignment model remains EMAIL_PENDING. Should we add an EMAIL_FAILED status to the offer_assignment model?

2018-12-20 07:08 UTC, irfanuddinahmad commented on ecommerce/extensions/offer/models.py
> +class OfferAssignmentEmail(models.Model):
The plan is to enhance edx-ace https://github.com/edx/edx-ace 
We could not use it here since it does not have any bounce functions at this time.

2018-12-20 07:12 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    permission_classes = (IsAuthenticated,)
Not sure. @georgebabey Please advise.
ecommerce-worker uses the following user:
'''
service_username = get_configuration('ECOMMERCE_SERVICE_USERNAME', site_code=site_code)
'''

2018-12-20 07:14 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Receive Sailthru bounce-api POST"""
@georgebabey You mentioned that the Amazon API Gateway will proxy this url. Should I add a DevOps ticket for that?

2018-12-20 09:25 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        update_status.update(extra_status)
Fixed! ... good catch!

2018-12-20 09:25 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Sends assignment email(s) to Learners."""
Done

2018-12-21 21:44 UTC, georgebabey requested changes

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^updatestatus$', assignment_email.AssignmentEmailStatus.as_view(), name='update_status'),
I think this should just be `status`, including the verb doesn't make it feel very REST

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^receivebounce$', assignment_email.AssignmentEmailBounce.as_view(), name='receive_bounce')
This could also just be `bounce`

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^assignmentemail/', include(ASSIGNMENT_EMAIL_URLS, namespace='assignmentemail')),
I think `assignment-email` would be more readable. hyphens for urls

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    permission_classes = (IsAuthenticated,)
I dont know if we need `IsAdminUser` but I do think adding `IsStaffOrOwner` would protect this endpoint from abuse

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        email_template = ('Your learning manager has provided you with a new access code to take a course at edX.'
Thinking we may want to pull this into config so we could potentially have a different email for stage vs prod. Also would allow Open edX installs to more easily configure this default

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        *offer_id*
Agree with @brittneyexline here. Given the similarity of model names and likely confusion let's update this and ecomm-worker. You even call it `offer_assignment_id` on the first line below

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Receive Sailthru bounce-api POST"""
We don't need to go through the API Gateway, we have many examples where we do not and it has not been widely adopted yet.  This should be accessible as our frontends are also hitting the backend APIs, Sailthru should be able to.

We should think through what would happen if a bad actor hit this endpoint. I think they'd be able to muck with the data since the IDs are auto-incrementing.  Therefore we should think how we can limit the access. Does Sailthru publish IP blocks we could whitelist? Lets chat about this with devops before this lands.

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    # Note: Will use a proxy api to secure this endpoint
We need to figure out how to secure this - whether through a proxy or some other way.

2018-12-21 21:44 UTC, georgebabey commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    permission_classes = ()
Lets make sure we we add a big comment here why we're removing base permission class.

2018-12-21 21:44 UTC, georgebabey commented on requirements/test.txt
> +-e git+https://github.com/edx/ecommerce-worker.git@master#egg=ecommerce-worker==master
Need to publish a version of the worker so we don't pull from master.

2018-12-24 13:04 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        email_template = ('Your learning manager has provided you with a new access code to take a course at edX.'
@georgebabey Are you referring to the edx-configuration repo?

https://github.com/edx/configuration/blob/0a413f7ba6a8b61e9d170f9fa9892aff3967f08e/playbooks/roles/ecommerce/defaults/main.yml#L121

2018-12-24 13:17 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        *offer_id*
Done. The companion PR in ecommerce-worker is at:
https://github.com/edx/ecommerce-worker/pull/39

2018-12-24 13:18 UTC, irfanuddinahmad commented on ecommerce/extensions/offer/models.py
> +class OfferAssignmentEmail(models.Model):
Name changed.

2018-12-24 13:19 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    permission_classes = (IsAuthenticated,)
IsStaffOrOwner permission added.

2018-12-24 13:24 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Receive Sailthru bounce-api POST"""
Unfortunately, I could not find any IP white-list in the docs. The endpoint receives an already created send_id which identifies the message to be updated. The auto increment ID is already created by the ecommerce-worker's call to /api/v2/assignment-email/status

2018-12-24 13:25 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^updatestatus$', assignment_email.AssignmentEmailStatus.as_view(), name='update_status'),
Done.

2018-12-24 13:25 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^receivebounce$', assignment_email.AssignmentEmailBounce.as_view(), name='receive_bounce')
Done.

2018-12-24 13:25 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/urls.py
> +    url(r'^assignmentemail/', include(ASSIGNMENT_EMAIL_URLS, namespace='assignmentemail')),
Done.

2018-12-24 13:26 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    permission_classes = ()
Added.

2018-12-24 13:26 UTC, irfanuddinahmad commented on requirements/test.txt
> +-e git+https://github.com/edx/ecommerce-worker.git@master#egg=ecommerce-worker==master
Waiting for https://github.com/edx/ecommerce-worker/pull/39 to be pulled into master.

2018-12-26 17:03 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        if email_status == 'success':
should we consider logging a warning if email status is not success? it seems like you are expecting only this value to come back

2018-12-27 07:49 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        if email_status == 'success':
You are right ... the ecommerce-worker only calls the api when the Sailthru call is successful, otherwise it logs an error. Since our default status in the offer_assignment model is 'EMAIL_PENDING', we can do away with the status check altogether. The only reason for keeping it would be if we were to introduce another status in offer_assignment e.g. EMAIL_FAILED ...  ... what do you think?

2018-12-28 15:28 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        if email_status == 'success':
if something changes, we'll have to update this anyway, so if it makes sense to assume this only gets called upon success, then we can just log a warning if the format of the payload is unexpected.

2019-01-08 16:28 UTC, brittneyexline approved these changes
from a code perspective, i think this is ready to go. the only small thing i'd like to see is more clarity on the AssignmentEmailStatus view when email_status is not 'success' (add a test?).
so, once you get the tests resolved, which i assume is due to ecommerce-worker, i think we can merge this.

2019-01-09 10:54 UTC, georgebabey commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        email_template = ('Your learning manager has provided you with a new access code to take a course at edX.'
Local project django settings would be fine

2019-01-09 13:39 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        email_template = ('Your learning manager has provided you with a new access code to take a course at edX.'
Done

2019-01-09 13:40 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        if email_status == 'success':
Done

2019-01-09 13:42 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        if email_status == 'success':
Done

2019-01-11 11:40 UTC, muhammad-ammar requested changes
@irfanuddinahmad Done with first pass of the review. Let me know once it is ready for next review.

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        *status*
`send_id` needs to be added to docstring

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Coupon code assignment email related functions"""
This view only has one endpoint to get the template so can update the docstring according to the endpoint?

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    in offer_assignment and offer_assignment_email model.
Can we update the model names in docstring like  `offer_assignment` -> `OfferAssignment`?

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        POST /ecommerce/api/v2/assignment-email/status
Can we add bit more explanation about what this endpoint does?

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +            similar_offers.update(status=OFFER_ASSIGNED)
this can be re-written as 
```python
OfferAssignment.objects.select_for_update().filter(
    user_email=assigned_offer.user_email,
    code=assigned_offer.code
).update(status=OFFER_ASSIGNED)
```

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        offer_assignment_id = int(request.data.get('offer_assignment_id'))
`offer_assignment_id` is an integer, so why we need to convert it to `int`?

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        if email_status == 'success':
Ideally we should have enum for these('success', `updated`) constants something like

```python
class OfferAssignmentEmailStatus(object):
    SUCCESS = 'success'
    UPDATED = 'updated'
```
And then we should use this enum everywhere we need the statuses. 
```python
if email_status == OfferAssignmentEmailStatus.SUCCESS:
```

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        return Response(update_status, status=status.HTTP_200_OK)
We are always sending the `200` even in case of error, this means that endpoint consumer always need to check the response to see if there is an error or not. Ideally endpoint should send 4XX in case of an error.

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +            similar_offers.update(status=OFFER_ASSIGNMENT_EMAIL_BOUNCED)
the above can be re-written as 
```python
OfferAssignment.objects.select_for_update().filter(
    user_email=assigned_offer.user_email,
    code=assigned_offer.code
).update(status= OFFER_ASSIGNMENT_EMAIL_BOUNCED)
```

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/offer/utils.py
> +        return False
I think we should log the exception, this will help in case of an error.

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/offer/utils.py
> +    email_subject = 'New edX course assignment'
Should we make this configurable?

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/offer/models.py
> +class OfferAssignmentEmailAttempt(models.Model):
Can we add a comment to explain why we need this model?

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    permission_classes = ()
Currently this endpoint has no authentication and verification so anyone can make a hit to this endpoint and try to update the database.

It would be great if we can add post verification as mentioned [here](https://getstarted.sailthru.com/developers/api-basics/postbacks/). We don't need to do this now as a part of this PR but we should definitely look this in future.

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/tests/views/test_assignmentemail.py
> +class AssignmentEmailTests(TestCase):
`AssignmentEmailTests` -> `AssignmentEmailTemplateTests`

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +class AssignmentEmail(APIView):
`AssignmentEmail` -> `AssignmentEmailTemplate` because this endpoint only handles template thing.

2019-01-11 11:40 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/tests/views/test_assignmentemail.py
> +    """ Tests for AssignmentEmail API view. """
`Tests for AssignmentEmail API view.` -> `Tests for AssignmentEmailTemplate API view.`

2019-01-11 16:08 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        POST /ecommerce/api/v2/assignment-email/status
Done

2019-01-11 16:08 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        *status*
Done

2019-01-11 16:09 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        return Response(update_status, status=status.HTTP_200_OK)
Done

2019-01-11 16:09 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    permission_classes = ()
Done

2019-01-11 16:09 UTC, irfanuddinahmad commented on ecommerce/extensions/offer/models.py
> +class OfferAssignmentEmailAttempt(models.Model):
Done

2019-01-11 16:09 UTC, irfanuddinahmad commented on ecommerce/extensions/offer/utils.py
> +        return False
Done

2019-01-11 16:11 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Receive Sailthru bounce-api POST"""
Added message md5 hash verification with sailthru key and secret

2019-01-11 16:11 UTC, irfanuddinahmad commented on requirements/test.txt
> +-e git+https://github.com/edx/ecommerce-worker.git@master#egg=ecommerce-worker==master
Done

2019-01-11 16:13 UTC, irfanuddinahmad commented
@muhammad-ammar I have incorporated most of your suggestions. Please review.

2019-01-11 16:35 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +        if email_status == 'success':
Done

2019-01-11 16:56 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    """Coupon code assignment email related functions"""
Done

2019-01-11 16:56 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    in offer_assignment and offer_assignment_email model.
Done

2019-01-11 16:57 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +            similar_offers.update(status=OFFER_ASSIGNED)
Done

2019-01-11 16:57 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/tests/views/test_assignmentemail.py
> +class AssignmentEmailTests(TestCase):
Done

2019-01-11 16:57 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +class AssignmentEmail(APIView):
Done

2019-01-11 16:57 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/tests/views/test_assignmentemail.py
> +    """ Tests for AssignmentEmail API view. """
Done

2019-01-14 10:20 UTC, muhammad-ammar approved these changes
@irfanuddinahmad Looks good to me.

Currently AWS SES does not work on sandbox so we can't test changes in this PR. My only concern is that it would be nice if we can test the changes on sandbox before merging.

2019-01-14 10:20 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +class OfferAssignmentStatus(object):
`OfferAssignmentStatus` -> `OfferAssignmentEmailStatus `

2019-01-15 18:05 UTC, feanil commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +            hash_string = sailthru_secret + sailthru_key + 'json' + json.dumps(received_data)
If the sailthru keys need to get rotated, all the hashes will mismatch, so signatures won't match for anything that is being sent to sailthru during the time when the rotation is occuring.  It seems like we wouldn't want that.  Should you be using a different token to salt the hash?  Like a new sailthru salt setting?

2019-01-15 18:06 UTC, feanil commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +            computed_hash = hashlib.md5(hash_string).hexdigest()
There are lots of places that use openEdx which have stringent security requirements about not using MD5 for anything.  I think you should use sha256 instead as this makes the hash more secure.

2019-01-15 18:08 UTC, feanil commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    def post(self, request):
Can we make this endpoint rate limited?  Do we know the rate at which we expect sailthru to hit this endpoint?

2019-01-16 07:04 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    def post(self, request):
@feanil Assuming that we send out ~100000 emails in 24 hours and again assuming that 1% bounce, that would entail approx. 1000 calls to this api in those 24 hours. However, we should get the exact stats by monitoring the api in AWS for a month.

2019-01-16 07:10 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +            hash_string = sailthru_secret + sailthru_key + 'json' + json.dumps(received_data)
@feanil This api handles postbacks 'from' Sailthru. Messages are 'sent' via edx-ecommerce-worker which already has the following two settings:
ECOMMERCE_WORKER_SAILTHRU_KEY
ECOMMERCE_WORKER_SAILTHRU_SECRET

Our ask is to setup edx-ecommerce in a similar way. Thanks

2019-01-16 07:13 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +            computed_hash = hashlib.md5(hash_string).hexdigest()
@feanil You are correct, however, Sailthru is sending us the postback message hash in MD5 format

2019-01-16 12:05 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    def post(self, request):
Added UserRateThrottle whose default rate in edx-ecommerce is 50 requests per minute ... which should be more than enough for this endpoint

2019-01-16 14:26 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +            hash_string = sailthru_secret + sailthru_key + 'json' + json.dumps(received_data)
Keys added as part of https://openedx.atlassian.net/servicedesk/customer/portal/3/DEVOPS-8165 ...

2019-01-17 16:19 UTC, coryleeio commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +    def post(self, request):
Marking as resolved since endpoint is rate limited globally on a per endpoint basis.

2019-01-17 16:22 UTC, coryleeio approved these changes

2019-01-17 16:42 UTC, merged