Coupon codes CSV
openedx-unsupported/ecommerce pull request #2084
Opened 2018-12-24 13:58 UTC by mushtaqak

2018-12-26 07:15 UTC, mushtaqak commented
@irfanuddinahmad Can you have a look at this?

2018-12-26 15:42 UTC, brittneyexline approved these changes
looks good! just need the quality checks to pass

2019-01-02 09:11 UTC, muhammad-ammar requested changes
@mushtaqak According to the changes it is mandatory that `no_page` param must be present in query params and appending the format alone is not enough. As per my understanding this is unintuitive.

`https://ecommerce-business.sandbox.edx.org/api/v2/enterprise/coupons/124/codes.csv/` is more intuitive than
`https://ecommerce-business.sandbox.edx.org/api/v2/enterprise/coupons/124/codes.csv/?no_page`

As per my understanding we can make the decision on `format` keyword argument in codes view. If format is other than `None` than do not paginate else paginate.

2019-01-02 09:11 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
This will add format suffix support for all the urls, is this expected?

2019-01-03 06:11 UTC, muhammad-ammar approved these changes
@mushtaqak Looks good to me.

2019-01-07 11:24 UTC, mushtaqak commented on ecommerce/extensions/api/v2/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
I guess this is OK, since this is used across many edX repositories.

2019-01-07 12:41 UTC, mushtaqak commented
>As per my understanding we can make the decision on format keyword argument in codes view. If format is other than None than do not paginate else paginate.

@muhammad-ammar I have removed `no_page` query param as per above feedback :)

2019-01-08 13:47 UTC, mushtaqak commented
@georgebabey Can do a quick review and merge - I don't merge rights :P ?

2019-01-15 22:12 UTC, robrap commented
FYI: I'm merging on behalf of @georgebabey due to codecov issues.

2019-01-15 22:12 UTC, merged