[WIP]: ENT-1172 Added notify_email field and updated POST handler
openedx-unsupported/ecommerce pull request #2085
Opened 2018-12-31 13:08 UTC by irfanuddinahmad

Description: This PR adds a notification email field to http://site_root/enterprise/coupons/new and updates the POST handler for EnterpriseCouponViewSet to send a notification to the supplied email address

Test Instructions:
1: Open http://site_root/enterprise/coupons/new in a browser
2: Create a new coupon and supply a notification email
3: Verify that the notification email is received on the supplied email address

2019-01-09 21:54 UTC, brittneyexline approved these changes
looks good, nice work!

2019-01-10 08:19 UTC, mushtaqak requested changes
Great work 👍 , just one miner change for removing a notification email.

2019-01-10 08:19 UTC, mushtaqak commented on ecommerce/extensions/api/v2/views/coupons.py
> +        pass
This is the case for old Coupon screen (https://ecommerce-business.sandbox.edx.org/coupons/new/) ? we just want to do nothing in this case. right ?

2019-01-10 08:19 UTC, mushtaqak commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if notify_email is not None:
I think this should be just `if notify_email:` otherwise we are getting an error when we add a notification email and then remove it ... thus form will make it "" - empty string and this will be bypassed here and model save does not handle empty string notification email ... and it gives error, making us unable to remove a notification email.

```suggestion
        if notify_email:
```
<img width="1069" alt="screen shot 2019-01-10 at 1 11 12 pm" src="https://user-images.githubusercontent.com/6991154/50954807-42a3ca80-14d9-11e9-9162-22c87bb2244e.png">

2019-01-10 08:19 UTC, mushtaqak commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        self.send_mail_patcher = patcher.start()
Nice :)

2019-01-10 14:35 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/coupons.py
> +        if notify_email is not None:
@mushtaqak I have fixed the issue. Can you please test it again?

2019-01-11 07:45 UTC, mushtaqak approved these changes
👍

2019-01-11 19:25 UTC, merged