ENT-1384 Add Enterprise Coupon Code Revoke API
openedx-unsupported/ecommerce pull request #2087
Opened 2019-01-03 19:39 UTC by brittneyexline

Depends on https://github.com/edx/ecommerce-worker/pull/40

2019-01-09 12:08 UTC, muhammad-ammar reviewed
@brittneyexline Looks good to me. Any way to test these changes on sandbox?

2019-01-09 12:08 UTC, muhammad-ammar commented on ecommerce/extensions/offer/utils.py
> +        *offer_assignment_id*
`offer_assignment_id` is not in the function parameters list?

2019-01-09 12:08 UTC, muhammad-ammar commented on ecommerce/extensions/api/serializers.py
> +class CouponCodeRevokeBulkSerializer(serializers.ListSerializer):  # pylint: disable=abstract-method
To me these customizations are complex to understand :smile: Any way to test this PR on sandbox?

2019-01-09 12:08 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +                    {'template': 'Test template', 'email': 'test3@example.com', 'code': 'RANDOMCODE'},
do we need to test a scenario where all bulk revokes completed successfully?

2019-01-09 21:56 UTC, brittneyexline commented on ecommerce/extensions/api/serializers.py
> +class CouponCodeRevokeBulkSerializer(serializers.ListSerializer):  # pylint: disable=abstract-method
you are right, i need to add testing instructions :-)
i'll also add a comment about what these do - i took it from some previous work with the enterprise enrollment api where we needed to process multiple rows of request data independently, meaning failures wouldn't prevent other rows from being processed.

2019-01-10 15:53 UTC, nedbat requested changes

2019-01-10 15:53 UTC, nedbat commented on ecommerce/extensions/offer/utils.py
> +         True when successful or False in case of any exception
This seems like an unusual choice for a function like this: why not let the exception raise up to the caller, and have them deal with it?

2019-01-10 15:53 UTC, nedbat commented on ecommerce/extensions/api/v2/views/enterprise.py
> +                status_keys.update({'status': 'email_dispatch_failed'})
Wouldn't it be useful to include some of the reason why it failed?

2019-01-10 15:53 UTC, nedbat commented on ecommerce/extensions/offer/utils.py
> +        return False
We don't even log the exception? This completely discards all information about the failure.

2019-01-15 20:21 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +                status_keys.update({'status': 'email_dispatch_failed'})
this is actually part of another PR that my work is based on: https://github.com/edx/ecommerce/pull/2082
fyi @irfanuddinahmad - might not be applicable anymore for you though

2019-01-15 20:22 UTC, brittneyexline commented on ecommerce/extensions/offer/utils.py
> +         True when successful or False in case of any exception
also part of the PR mentioned above - but i added a similar function below so note taken :-)

2019-01-15 21:30 UTC, brittneyexline commented on ecommerce/extensions/offer/utils.py
> +        return False
this is also part of the PR mentioned above, but i added a similar function so note taken there!

2019-01-24 16:41 UTC, irfanuddinahmad approved these changes
LGTM! ... highlighted some small changes

2019-01-24 16:41 UTC, irfanuddinahmad commented on ecommerce/extensions/api/serializers.py
> +        Validate that the code is part of the Coupon the code and email provided have an active OfferAssignment.
nit: Validate that the code is part of the Coupon and the provided code and email have an active OfferAssignment.

2019-01-24 16:41 UTC, irfanuddinahmad commented on ecommerce/extensions/offer/utils.py
> +    email_subject = 'edX Course Assignment Revoked'
nit: Could be made a configuration setting.

2019-01-24 16:41 UTC, irfanuddinahmad commented on ecommerce/extensions/offer/utils.py
> +         True when successful or False in case of any exception
Update docstring: The function does not return anything

2019-01-24 21:29 UTC, merged