[WIP] ENT-1385 Offer assignment reminder email api
openedx-unsupported/ecommerce pull request #2098
Opened 2019-01-21 15:14 UTC by irfanuddinahmad

Description: This PR provides api for sending reminder emails to learners regarding their un-redeemed offers.

JIRA: https://openedx.atlassian.net/browse/ENT-1385

2019-01-22 15:19 UTC, irfanuddinahmad commented
Reviewers: Please review the last commit since the earlier commits contain work from ENT-1384 and ENT-1417

2019-01-28 11:39 UTC, mushtaqak commented
I did end-to-end testing on my local docker machine with `CELERY_ALWAYS_EAGER` set `True` in `devstack.py`. Things are looking good 👍  (although we might need to think over the response message in case of some of the reminders failed)

2019-01-28 12:34 UTC, muhammad-ammar requested changes
@irfanuddinahmad I am done with first pass of the review.

2019-01-28 12:34 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        email_template = request.data.pop('template', None)
shouldn't the template always present in the request data? as per my understanding template is mandatory so we should raise error if template is not present.

2019-01-28 12:34 UTC, muhammad-ammar commented on ecommerce/extensions/api/serializers.py
> +        email = validated_data.get('total_offer_count')
looks like the above two lines are left by mistake?

2019-01-28 12:34 UTC, muhammad-ammar commented on ecommerce/extensions/api/serializers.py
> +            if template and offer_assignments:
I think we don't need this `if condition` because if `template` is not present than control should not get here, we should validate the template in the view and raise error. Also we don't need to check for `offer_assignments` because if there are no `offer_assignments` than `validate` method will raise error and control will not get here.

2019-01-28 12:34 UTC, muhammad-ammar commented on ecommerce/settings/base.py
> +OFFER_ASSIGNMENT_EMAIL_REMINDER_DEFAULT_SUBJECT = 'Reminder on edX course assignment'
email subject is not clear enough to convey the message? What about `Reminder to redeem your course coupon` or something better?

2019-01-28 12:34 UTC, muhammad-ammar commented on ecommerce/settings/base.py
> +    Enrollment url: {ENROLLMENT_URL}
nit: `url` -> `URL`

2019-01-28 12:34 UTC, muhammad-ammar commented on ecommerce/settings/base.py
> +    or you can insert the access code at check out under "coupon code" for applicable courses.
Is this expected that a leaner knows the flow mention in `you can insert the access code at check out under "coupon code" for applicable courses`?

2019-01-28 12:34 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            return Response(serializer.data, status=status.HTTP_200_OK)
we are always sending `200` even if there are errors. Is this OK?

2019-01-28 12:34 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +            {'non_field_errors': ['Code RANDOMCODE is not associated with this Coupon']},
Though not needed but it would be nice if response format for success and failure is same, instead of `non_field_errors` what about 
```python
{'email': offer_assignment.user_email, 'code': offer_assignment.code, 'detail': 'failure', 'error_message': 'Code RANDOMCODE is not associated with this Coupon'}
```
we need to do something like below in `to_internal_value` method in `CouponCodeRevokeRemindBulkSerializer` 

```python
ret = []
for item in data:
    try:
        validated = self.child.run_validation(item)
    except serializers.ValidationError as exc:
        ret.append(dict(item, **{'detail': 'failure', 'message': exc.detail['non_field_errors'][0]}))
    else:
        ret.append(validated)
```
This will help us on frontend side to attach the error with correct row if we ever want to show the individual errors.

2019-01-28 13:20 UTC, irfanuddinahmad commented on ecommerce/settings/base.py
> +    or you can insert the access code at check out under "coupon code" for applicable courses.
@georgebabey This was provided by @jshin-edx

2019-01-28 13:20 UTC, irfanuddinahmad commented on ecommerce/settings/base.py
> +OFFER_ASSIGNMENT_EMAIL_REMINDER_DEFAULT_SUBJECT = 'Reminder on edX course assignment'
@georgebabey This was provided by @jshin-edx

2019-01-28 13:20 UTC, irfanuddinahmad commented on ecommerce/extensions/api/serializers.py
> +        email = validated_data.get('total_offer_count')
the perils of copy-paste!

2019-01-28 13:21 UTC, irfanuddinahmad commented on ecommerce/settings/base.py
> +    Enrollment url: {ENROLLMENT_URL}
@georgebabey This was provided by @jshin-edx

2019-01-28 13:22 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            return Response(serializer.data, status=status.HTTP_200_OK)
@georgebabey We are sending a per record status ... what should be the overall status?

2019-01-28 13:27 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        email_template = request.data.pop('template', None)
Done

2019-01-28 13:28 UTC, irfanuddinahmad commented on ecommerce/extensions/api/serializers.py
> +            if template and offer_assignments:
Done

2019-01-28 13:28 UTC, irfanuddinahmad commented on ecommerce/extensions/api/serializers.py
> +        email = validated_data.get('total_offer_count')
Removed

2019-01-29 09:31 UTC, muhammad-ammar approved these changes

2019-01-30 15:54 UTC, brittneyexline approved these changes
let me know what you think about consolidating the serializer validation code, and then i think we're good to merge/release this!

2019-01-30 15:54 UTC, brittneyexline commented on ecommerce/extensions/api/serializers.py
> +        if not coupon.attr.coupon_vouchers.vouchers.filter(code=code).exists():
i wonder if there is an opportunity to DRY out some of this validation logic, since it is quite similar to the revoke serializer's logic?

2019-01-30 15:54 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            return Response(serializer.data, status=status.HTTP_200_OK)
given i'm the one who introduced this pattern with revoke, i think it's ok that the status is 200 even if individual requests within the larger request fail - the overall request still succeeded by going through each individual one. if the overall request format is one that we cannot process, then it is a bad request.

2019-01-31 10:15 UTC, irfanuddinahmad commented on ecommerce/extensions/api/serializers.py
> +        if not coupon.attr.coupon_vouchers.vouchers.filter(code=code).exists():
Done. Still a bit WET though! :)

2019-01-31 15:26 UTC, brittneyexline commented on ecommerce/extensions/api/serializers.py
> +        validate_coupon_has_code(coupon, code)
i think it would be better to create a serializer class or mixin that had this method as well as one that checks if there are active offer assignments that exist (since both validate methods perform this as well). then both serializers could inherit from it, and possibly the list serializer could be specified at this level too.

2019-02-01 10:34 UTC, irfanuddinahmad commented on ecommerce/extensions/api/serializers.py
> +        validate_coupon_has_code(coupon, code)
Done!

2019-02-01 14:07 UTC, merged