Filter coupon details - Unassigned vouchers
openedx-unsupported/ecommerce pull request #2099
Opened 2019-01-22 10:47 UTC by mushtaqak

Filter coupon details - [ENT-1345](https://openedx.atlassian.net/browse/ENT-1345)

2019-01-30 13:28 UTC, muhammad-ammar requested changes
@mushtaqak I am done with review. Please see my suggestions.

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            MULTI_USE, 3 quantiy, 10 max_uses, no assignment, no redemption --> 3 slots available.
I think in this scenario we will have `10 slots available` per code

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        Returns vouchers that are fully redeemed, these vouchers do not have any assignment or redemption left.
nit: `Return vouchers ...`

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        assigne_codes = self.get_assigned_codes()
`assigne_codes` -> `assigned_codes `

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return coupon_vouchers.filter(num_orders_gte=1, offers__max_global_applications__gt=F('num_orders'))
I think empty queryset in case of `SINGLE_USE` make sense but I am not sure? `max_global_applications` 
 is set to `None` for `SINGLE_USE` so we need to add a test with `SINGLE_USE` type to specifically check the above filter condition.

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        assigned_codes = self.get_assigned_codes()
`assigned_codes` -> `assigned_and_unredeemed_codes`

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return unredeemed_vouchers
I think we don't need to call `self.get_redeemable_vouchers` in this method. We just need to filter the `coupon_vouchers` with `assigned_and_unredeemed_codes` like below

```python
def get_unredeemed_coupon_vouchers(self, coupon_vouchers):
    assigned_and_unredeemed_codes = self.get_assigned_codes()
    return coupon_vouchers.filter(code__in= assigned_and_unredeemed_codes)
```

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        Returns only those vouchers which have free slots available.
nit:`Return only ...`

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/serializers.py
> +            'available': voucher.slots_available_for_assignment,
`available` should be set to `max_coupon_usage`. It would be great if we can rename `available` to `total` on both the backend and frontend side

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return unassigned_vouchers
```python
from django.db.models import OuterRef, Subquery
from django.db.models.functions import Coalesce

# subquery to count number of unredeemed offer assignments of a code
# the way this subquery is written is suggested in [django docs](https://docs.djangoproject.com/en/1.11/ref/models/expressions/#using-aggregates-within-a-subquery-expression)  
offerassignments = OfferAssignment.objects.filter(
    code=OuterRef('code')
).exclude(
    status__in=[OFFER_REDEEMED, OFFER_ASSIGNMENT_REVOKED]
).values('code').annotate(assignment_count=Count('pk', distinct=True)).values('assignment_count')

# Coalesce is used so that if there are no assigments than return 0
offerassignments_subquery = Coalesce(Subquery(offerassignments, output_field=IntegerField()), 0)

if SINGLE_USE:
    qs_may_have_free_slots = coupon_vouchers.filter(num_orders=0)
    vouchers_with_free_slots = qs_may_have_free_slots.annotate(
        assignment_count=offerassignments_subquery
    ).filter(
        assignment_count=0,
        num_orders=0
    )
else:
    qs_may_have_free_slots = coupon_vouchers.filter(offers__max_global_applications__gt=F('num_orders'))
    vouchers_with_free_slots = qs_may_have_free_slots.annotate(
        assignment_count=offerassignments_subquery
    ).filter(
        offers__max_global_applications__gt=F(assignment_count) + F('num_orders')
    )
```

  max = 10
  redeemed = 2
  assigned = 3
  redeemed and assigned are different 
  free slots = 5
  
  max = 10
  redeemed = 2
  assigned = 3
  redeemed and assigned are same 
  free slots = 7

2019-01-30 13:28 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return coupon_vouchers.filter(num_orders_gte=1, offers__max_global_applications__gt=F('num_orders'))
[This](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#none) is how we can return an empty queryset.

2019-02-04 17:00 UTC, adamstankiewicz commented on ecommerce/extensions/api/v2/views/enterprise.py
> +    def get_assigned_uredeemed_codes(self):
typo: `get_assigned_unredeemed_codes`

2019-02-04 17:07 UTC, adamstankiewicz commented on ecommerce/extensions/api/serializers.py
> +            'total': max_coupon_usage,
I agree that we should change this field name to `total` as it's a little more descriptive than `available`. However, we'll have to change the frontend code to reflect this API change, just FYI as a note.

2019-02-04 17:07 UTC, adamstankiewicz commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        assigned_uredeemed_codes = self.get_assigned_uredeemed_codes()
typo: `assigned_unredeemed_codes`

2019-02-06 10:44 UTC, mushtaqak commented
@muhammad-ammar This is finally ready for your review :P

2019-02-06 11:30 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +            'total': max_coupon_usage,
Yep, addressed in https://github.com/edx/edx-portal/pull/164 :)

2019-02-06 17:03 UTC, brittneyexline reviewed
the biggest difference between what you've done here and what i've done in my PR is the conceptual model of the type of data we are returning. this implementation focuses on the status of an individual code (which is the way we originally thought it would work). my implementation focuses on the status of unique user/code pairs. this happens to be the same for SINGLE_USE and MULTI_USE_PER_CUSTOMER codes where only one user is assigned to one code, but it starts to get weird with MULTI_USE and ONCE_PER_CUSTOMER.

based on my conversation with Adam, we shifted to thinking about the status of the code and user together. consider the following scenario:

code A is a MULTI_USE code that has 4 usages. one usage has been redeemed by user 1, one usage is assigned to user 1 but not redeemed, one usage is assigned to user 2, the last usage is not assigned.

your implementation might show something like this (although you are not dealing with assigned to in the PR):
not-assigned - Redemptions: 3 of 4 | Code: A
not-redeemed - Assigned to: user 2 | Redemptions: 3 of 4 | Code: A
partial-redeemed - Assigned to: user 1 | Redemptions: 3 of 4 | Code: A
redeemed: nothing

my implementation would show this:
not-assigned - Redemptions: 1 of 4 | Code: A
not-redeemed - Assigned to: user 2 | Redemptions: 0 of 1 | Code: A
partial-redeemed - Assigned to: user 1 | Redemptions: 1 of 2 | Code: A
redeemed: nothing

when user 1 redeems their second assignment, my implementation would show a row in redeemed with redemptions: 2 of 2, while yours would remain the same in partial-redeemed.

i think we have to consider the user in order for the rows returned to make sense, which is why redemptions ends up scoped to the user (except for the not-assigned filter). as such, i don't think we can reconcile our PRs. i would encourage you to review mine closely to make sure i haven't missed anything that you are covering here.

2019-02-06 17:03 UTC, brittneyexline commented on ecommerce/extensions/api/serializers.py
> +            'used': redemption_count + num_unredeemed_offerassignments,
i thought that assignments that have not redeemed would not go towards used, as used is for the number of redemptions. however, i do feel that we need a way to represent the number of assignments that have not been redeemed.

2019-02-06 17:03 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        """
i have to admit, i find this function hard to understand, so it's hard for me to know if it does the same thing as i did. this was my implementation: https://github.com/edx/ecommerce/pull/2109/files#diff-141fa9c110c00aba0d7f70839c4a77bbR260

2019-02-08 11:14 UTC, closed without merging

2019-02-08 11:15 UTC, mushtaqak commented
Closed in favour of https://github.com/edx/ecommerce/pull/2109