Adding in create entitlement API
openedx-unsupported/ecommerce pull request #2103
Opened 2019-01-28 16:32 UTC by Dillon-Dumesnil

2019-01-28 20:00 UTC, Dillon-Dumesnil commented
Related PR: https://github.com/edx/course-discovery/pull/1755

2019-01-28 21:27 UTC, mikix commented on ecommerce/extensions/api/v2/views/products.py
> +        if product_class == COURSE_ENTITLEMENT_PRODUCT_CLASS_NAME:
nit: I would use `data` instead of `entitlement_data` -- you don't know what class it is yet, and makes more sense in case we ever add support for other products to this method.

Likewise for the docstring, I'd make it a little more generic.

2019-01-28 21:27 UTC, mikix commented on ecommerce/extensions/api/v2/views/products.py
> +            )
You can just do:
```
entitlement = create_or_update_course_entitlement(**product_creation_fields)
```

2019-01-28 21:27 UTC, mikix commented on ecommerce/extensions/api/v2/views/products.py
> +                bad_request_message = 'Missing or bad value(s) for: {}. '.format(', '.join(missing_values)) + \
I don't love the `(s)` - red flag for me, who is used to translating and being careful with plurals. It's also inconsistent with the phrase "These fields" just a moment later. is there a way to rephrase? Or always use the plural? I dunno. Your call.

Additionally, I think it's an interesting question of whether this error (and the one later in this file) should be translated? I understand the argument that these should basically never be seen. But that's more an argument for not writing them at all. If we expect a human to ever look at these, might be nice to translate. But just a nit. These are rare enough that I don't really care. If they are translated, the correct thing would probably be using ngettext to handle the plural correctly.

2019-01-28 21:27 UTC, mikix commented on ecommerce/extensions/api/v2/views/products.py
> +                    missing_values.append(attribute_name)
Could do:
```
missing_values = [k for k, v in product_creation_fields.items() if v is not None]
```

2019-01-28 21:27 UTC, mikix commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +        self.assertEqual(response.status_code, 201)
Might also want to test that the database object got created correctly? Or at least mock create_or_update_course_entitlement and confirm it got called correctly.

2019-01-28 21:27 UTC, mikix commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +        """ Verify the view allows individual Course Entitlement products to be made via post"""
docstring

2019-01-28 21:27 UTC, mikix commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +        """ Verify the view allows individual Course Entitlement products to be made via post"""
docstring

2019-01-28 21:27 UTC, mikix commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +        self.assertEqual(response.status_code, 400)
Might be worth testing message here. For all you know, it's complaining about missing price & name like the test above, rather than class type.

2019-02-04 19:18 UTC, Dillon-Dumesnil commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +        """ Verify the view allows individual Course Entitlement products to be made via post"""
Disagree here. This docstring is under the class of tests called `ProductViewSetCourseEntitlementTests`. I feel comfortable specifying that it is a Course Entitlement in the docstring.

2019-02-04 19:18 UTC, Dillon-Dumesnil commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +        """ Verify the view allows individual Course Entitlement products to be made via post"""
Disagree here. This docstring is under the class of tests called `ProductViewSetCourseEntitlementTests`. I feel comfortable specifying that it is a Course Entitlement in the docstring.

2019-02-05 15:28 UTC, mikix approved these changes
Thank you :pray: for doing the partial update stuff for me.

2019-02-05 15:28 UTC, mikix commented on ecommerce/courses/tests/test_utils.py
> +            product, __ = create_or_update_course_entitlement(
Two underscores? That's fine too, but I usually see one. Do not change, super not worth it. Another style would be "_sku" to label what you're tossing away so the reader isn't wondering. But again, not worth changing.

2019-02-05 15:28 UTC, mikix commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +            'price': price or self.entitlement_data['price'],
Why the `or` here - we probably want to test passing in partial data, no?

2019-02-05 15:28 UTC, mikix commented on ecommerce/programs/tests/mixins.py
> +                __, sku = create_or_update_course_entitlement('verified', 10, partner, uuid, uuid)
Heh nice

2019-02-06 21:26 UTC, mikix approved these changes
Nice title/name cleanup

2019-02-08 14:26 UTC, jmyatt requested changes

2019-02-08 14:26 UTC, jmyatt commented on ecommerce/extensions/api/v2/tests/views/test_products.py
> +            'uuid': 'f9044e15-133f-4a4f-b587-99530e8a8e88',
why not generate a fresh uuid instead of hard coding it?  More importantly, you could reference this value where it's used in the test code (`put_data` and `patch_data`) using `self.entitlement_data['uuid']` instead of also hard coding it there

2019-02-08 16:37 UTC, jmyatt approved these changes

2019-02-12 15:02 UTC, merged