ENT-1511 | Allowing for CORS for this service
openedx-unsupported/ecommerce pull request #2110
Opened 2019-02-05 15:00 UTC by christopappas

2019-02-05 16:30 UTC, georgebabey approved these changes
Just one question but this looks good!

2019-02-05 16:30 UTC, georgebabey commented on ecommerce/settings/production.py
> +CORS_ORIGIN_ALLOW_ALL = environ.get('CORS_ORIGIN_ALLOW_ALL', False)
Is this and `CORS_ALLOW_INSECURE ` needed at all? I can't imagine a scenario where we'd be using production.py and want to allow any origin.

2019-02-05 18:27 UTC, christopappas commented on ecommerce/settings/production.py
> +CORS_ORIGIN_ALLOW_ALL = environ.get('CORS_ORIGIN_ALLOW_ALL', False)
can remove, np

2019-02-06 09:57 UTC, mushtaqak requested changes
@christopappas Looks good, one thing, we need to import `corsheaders_default_headers`

2019-02-06 09:57 UTC, mushtaqak commented on ecommerce/settings/production.py
> +CORS_ALLOW_HEADERS = corsheaders_default_headers + (
We need to import this as well.
```python
from corsheaders.defaults import default_headers as corsheaders_default_headers
```

2019-02-06 15:48 UTC, christopappas commented on ecommerce/settings/production.py
> +CORS_ALLOW_HEADERS = corsheaders_default_headers + (
goood catch. thank you mushtaq

2019-02-07 07:29 UTC, mushtaqak approved these changes
Looks good :shipit:

2019-02-07 14:42 UTC, merged