move ecommerce task to thier own queue
openedx-unsupported/ecommerce pull request #2129
Opened 2019-02-12 14:10 UTC by syed-awais-ali

2019-02-14 20:57 UTC, coryleeio commented on ecommerce/settings/base.py
> +    Queue('ecommerce', Exchange('ecommerce'), routing_key='ecommerce'),
Instead of just setting this to ecommerce, I would default it to celery(I think this is what it is now), and load it from an environment variable.  That away people running this code already dont have their queue changed out from underneath them, because if the old queue is not empty that work wont be completed.

I would read in a config in production.py, default that value to celery deploy that to production, then make the config change in internal.

When we roll the config change out you will need to make sure the old default queue is clear before we allow the ecommerce service to terminate.

2019-02-25 17:32 UTC, coryleeio requested changes
load from env, similar to notifier PR

2019-03-06 22:32 UTC, coryleeio submitted a review, later dismissed

2019-03-06 22:32 UTC, coryleeio commented on ecommerce/settings/base.py
> +    Queue('ecommerce', Exchange('ecommerce'), routing_key='ecommerce'),
You have a routing key variable below, but ROUTING_KEY = environ.get('ECOMMERCE_ROUTING_KEY')


but it is still hardcoded here to 'ecommerce'

2019-03-18 15:31 UTC, coryleeio commented
I've removed my review since you appear to be redoing this

2019-03-18 15:31 UTC, coryleeio commented
Please file a new review ticket once this is ready to go

2019-04-10 20:23 UTC, coryleeio requested changes

2019-04-10 20:23 UTC, coryleeio commented on ecommerce/settings/production.py
> +ROUTING_KEY = environ.get('ECOMMERCE_ROUTING_KEY')
same pattern here as https://github.com/edx/ecommerce-worker/pull/52#pullrequestreview-225196290

2019-04-11 13:02 UTC, syed-awais-ali commented on ecommerce/settings/production.py
> +ROUTING_KEY = environ.get('ECOMMERCE_ROUTING_KEY')
@coryleeio should this be moved to base.py ?
i am moving it to base.py

2019-04-11 20:20 UTC, coryleeio approved these changes

2019-04-22 10:23 UTC, merged