WL-1881 | Added a management command to sync the ecommerce data to hubspot.
openedx-unsupported/ecommerce pull request #2146
Opened 2019-02-19 12:13 UTC by hasnain-naveed

2019-02-19 12:34 UTC, hasnain-naveed commented
@HammadAhmadWaqas this is final PR.

2019-02-19 13:37 UTC, ziafazal approved these changes
@hasnain-naveed overall looks good just few nits.

2019-02-19 13:37 UTC, ziafazal commented on ecommerce/core/management/commands/sync_hubspot.py
> +    def _hubspot_endpoint(self, api, api_url, api_type, body=None, **kwargs):
Can we make signature of this method a little more readable.
i.e `def _hubspot_endpoint(self, hubspot_object, api_url, method, body=None, **kwargs):`

2019-02-19 13:37 UTC, ziafazal commented on ecommerce/core/management/commands/sync_hubspot.py
> +                'It is first syncing call, it will pull all the orders for syncing for site {site}'.format(
May be we can change the wording `No last synced order found...`

2019-02-20 13:47 UTC, georgebabey requested changes
Looks great overall but I believe there is one issue with null vs empty_string on the configuration

2019-02-20 13:47 UTC, georgebabey commented on ecommerce/core/management/commands/sync_hubspot.py
> +
nit: space

2019-02-20 13:47 UTC, georgebabey commented on ecommerce/core/management/commands/sync_hubspot.py
> +    help = 'Sync Product, Orders and Lines to partners Hubspot server.'
I would take `partner` out of here as that is an edx specific term. Maybe `Sync Products, Orders and Line Items to a Hubspot server.`

2019-02-20 13:47 UTC, georgebabey commented on ecommerce/core/migrations/0048_siteconfiguration_hubspot_secret_key.py
> +            field=models.CharField(blank=True, help_text='Secret key for Hubspot portal authentication', max_length=255, null=True, verbose_name='Hubspot Portal Secret Key'),
General django best practice is to not allow null for CharField (see https://docs.djangoproject.com/en/dev/ref/models/fields/#null) 

Right now you are checking for non-`null` to determine if hubspot is enabled, but new configurations will have this set to empty string.  https://github.com/edx/ecommerce/pull/2146/files#diff-344c0546bfd4c3a65a58efc931f82f3aR147

I'd recommend changing this to `null=False`

2019-02-21 10:18 UTC, hasnain-naveed commented on ecommerce/core/migrations/0048_siteconfiguration_hubspot_secret_key.py
> +            field=models.CharField(blank=True, help_text='Secret key for Hubspot portal authentication', max_length=255, null=True, verbose_name='Hubspot Portal Secret Key'),
@georgebabey WL-1880 is pre-requisite of WL-1881. WL-1880 covers this model change. I have updated my [PR](https://github.com/edx/ecommerce/pull/2118) according to your suggestion. Waiting for your +1. Thanks.

2019-02-25 20:03 UTC, georgebabey commented on ecommerce/core/migrations/0048_siteconfiguration_hubspot_secret_key.py
> +            field=models.CharField(blank=True, help_text='Secret key for Hubspot portal authentication', max_length=255, null=True, verbose_name='Hubspot Portal Secret Key'),
Merged WL-1880 in, so this will need to be rebased now

2019-02-25 20:03 UTC, georgebabey approved these changes

2019-02-26 13:26 UTC, georgebabey approved these changes

2019-02-26 13:28 UTC, merged