ENT-1566 Updated logging for offer assignment when send_id is not found in model
openedx-unsupported/ecommerce pull request #2147
Opened 2019-02-20 17:20 UTC by irfanuddinahmad

Description: This PR updates the bounce endpoint (POST /ecommerce/api/v2/assignment-email/bounce).
It removes logging for the case when the Sailthru send_id is not found in the OfferAssignmentEmailAttempt model. This log was generating a lot of splunk entries since Sailthru sends a bounce callback for all bounces, irrespective of the origin email template. Consequently, most of the send_ids were expected to be not present in the OfferAssignmentEmailAttempt model and hence should not generate a log entry.

2019-02-20 18:00 UTC, georgebabey requested changes

2019-02-20 18:00 UTC, georgebabey commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +                    pass
Can you add a comment here indicating why we're passing. Something like: Marketing email bounces also come through this code path and its expected they would not have a corresponding OfferAssignment

2019-02-20 18:10 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/assignmentemail.py
> +                    pass
Done

2019-02-20 18:23 UTC, georgebabey approved these changes

2019-02-21 07:00 UTC, muhammad-ammar approved these changes
LGTM 👍

2019-02-21 07:28 UTC, merged