[WIP] ENT-1606 New permission -  IsStaffOrEnterpriseUser
openedx-unsupported/ecommerce pull request #2160
Opened 2019-02-27 14:31 UTC by irfanuddinahmad

Description: This PR adds a new permission IsStaffOrEnterpriseUser which will be applied on the enterprise api endpoints.

2019-03-01 17:57 UTC, brittneyexline reviewed
you're on the right track, but there are some things that will need to be adjusted. i'm also wondering if you are going to add the permission check to the endpoints in this PR or in a separate PR?

2019-03-01 17:57 UTC, brittneyexline commented on ecommerce/enterprise/clients.py
> +class EnterpriseApiClient(EdxRestApiClient):
I'm pretty sure we already have an api client for hitting enterprise apis: https://github.com/edx/ecommerce/blob/master/ecommerce/enterprise/api.py
you should probably add the with_access_to call to this file.

2019-03-01 17:57 UTC, brittneyexline commented on ecommerce/enterprise/clients.py
> +            resource='enterprise-customer',
maybe 'enterprise-customer-access' would reflect the resource better?

2019-03-01 17:57 UTC, brittneyexline commented on ecommerce/extensions/api/permissions.py
> +    ENTERPRISE_DATA_API_GROUP = 'enterprise_data_api_access'
seems weird that we are defining the same constant twice?

2019-03-01 17:57 UTC, brittneyexline commented on ecommerce/extensions/api/permissions.py
> +class IsStaffOrEnterpriseUser(permissions.BasePermission):
so, i think i may have pointed you to the wrong permission class to use in the data api code. we should be mimicking HasDataAPIDjangoGroupAccess (https://github.com/edx/edx-enterprise-data/blob/master/enterprise_data/permissions.py#L70).
staff users will also need to go through the with_access_to check.

2019-03-04 21:39 UTC, brittneyexline commented on ecommerce/extensions/api/permissions.py
> +        enterprise_in_url = request.parser_context.get('kwargs', {}).get('enterprise_id', '')
not all of the urls to our views will have the enterprise_id in it - you will have to add logic to derive it from the coupon product if that is what is available instead

2019-03-04 21:39 UTC, brittneyexline commented on ecommerce/extensions/api/permissions.py
> +        permitted = self.get_enterprise_with_access_to(request.site, request.user, enterprise_in_url)
just calling out that you are planning on relying on the cache instead of the user's session to prevent further redundant calls to the endpoint?

2019-03-04 21:39 UTC, brittneyexline commented on ecommerce/enterprise/api.py
> +        resource=api_resource_name,
can we add a little more detail to this cache key name to differentiate it from other calls to the enterprise-customer set of endpoints? see https://github.com/edx/ecommerce/blob/410496eee46e6b3c4b80a54ed32f12168d12e70c/ecommerce/enterprise/api.py#L185

2019-03-06 16:12 UTC, irfanuddinahmad commented on ecommerce/enterprise/clients.py
> +class EnterpriseApiClient(EdxRestApiClient):
api client updated.

2019-03-06 16:14 UTC, irfanuddinahmad commented on ecommerce/enterprise/clients.py
> +            resource='enterprise-customer',
Updated key

2019-03-06 16:14 UTC, irfanuddinahmad commented on ecommerce/extensions/api/permissions.py
> +    ENTERPRISE_DATA_API_GROUP = 'enterprise_data_api_access'
added settings value

2019-03-06 16:15 UTC, irfanuddinahmad commented on ecommerce/extensions/api/permissions.py
> +class IsStaffOrEnterpriseUser(permissions.BasePermission):
added the new permission

2019-03-06 16:16 UTC, irfanuddinahmad commented on ecommerce/extensions/api/permissions.py
> +        enterprise_in_url = request.parser_context.get('kwargs', {}).get('enterprise_id', '')
added coupon based logic

2019-03-06 16:16 UTC, irfanuddinahmad commented on ecommerce/extensions/api/permissions.py
> +        permitted = self.get_enterprise_with_access_to(request.site, request.user, enterprise_in_url)
Yes.

2019-03-06 16:17 UTC, irfanuddinahmad commented on ecommerce/enterprise/api.py
> +        resource=api_resource_name,
Done

2019-03-06 16:34 UTC, brittneyexline approved these changes

2019-03-06 16:34 UTC, brittneyexline commented on ecommerce/extensions/api/permissions.py
> +                coupon.attr.coupon_vouchers.vouchers.first().enterprise_offer.condition.enterprise_customer_uuid)
nit: end parentheses should be on the next line

2019-03-06 16:34 UTC, brittneyexline commented on ecommerce/enterprise/api.py
> +    TieredCache.set_all_tiers(cache_key, response['results'][0], settings.ENTERPRISE_API_CACHE_TIMEOUT)
this setting is 300s, which is only 5 min. i don't have a very strong feeling about this, but i think this points towards using the user session as a better point of storing this data to avoid an api call. since we'll be ripping this out at some point soon, i don't think you need to change it, unless the number of calls to this endpoint become problematic before the other authz stuff is ready.

2019-03-07 15:34 UTC, brittneyexline requested changes
we'll need to adjust how the permission_class gets applied by moving the code management endpoints into their own viewset. also, it appears that you are also just below the coverage threshold

2019-03-07 15:34 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +    permission_classes = (IsAuthenticated, HasDataAPIDjangoGroupAccess,)
we need to separate the code management endpoints into their own view set class so that we don't apply this permission check to the endpoints used by the coupon admin pages.

2019-03-08 14:10 UTC, irfanuddinahmad commented on ecommerce/extensions/api/permissions.py
> +                coupon.attr.coupon_vouchers.vouchers.first().enterprise_offer.condition.enterprise_customer_uuid)
Changed the method for getting the enterprise_id

2019-03-08 14:11 UTC, irfanuddinahmad commented on ecommerce/enterprise/api.py
> +    TieredCache.set_all_tiers(cache_key, response['results'][0], settings.ENTERPRISE_API_CACHE_TIMEOUT)
Noted.

2019-03-08 14:12 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +    permission_classes = (IsAuthenticated, HasDataAPIDjangoGroupAccess,)
I have added the permission in the detail_route decorator. Please review.

2019-03-08 16:54 UTC, brittneyexline approved these changes

2019-03-08 17:35 UTC, merged