ENT-1627: Bounced codes do not have remind/revoke buttons.
openedx-unsupported/ecommerce pull request #2164
Opened 2019-03-05 11:05 UTC by saleem-latif

**JIRA Ticket:** (ENT-1627)[https://openedx.atlassian.net/browse/ENT-1627]

**Description:**
Unredeemed codes do not have a "Remind / Revoke" option next. This PR adds `OFFER_ASSIGNMENT_EMAIL_BOUNCED` status to the filter so that bounced codes are included in the API response and are handled accordingly on the edx-portal side.

2019-03-06 08:59 UTC, irfanuddinahmad approved these changes
LGTM!

2019-03-07 06:30 UTC, mushtaqak requested changes

2019-03-07 06:30 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +                status__in=[OFFER_ASSIGNED, OFFER_ASSIGNMENT_EMAIL_PENDING, OFFER_ASSIGNMENT_EMAIL_BOUNCED],
I don't think bounced codes would ever appear in partial-redeemed since there would not be any email sent in the first place to redeem the code, hence no partial-redemption.

2019-03-08 11:01 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +                status__in=[OFFER_ASSIGNED, OFFER_ASSIGNMENT_EMAIL_PENDING, OFFER_ASSIGNMENT_EMAIL_BOUNCED],
@brittneyexline what do you think?

2019-03-08 13:29 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +                status__in=[OFFER_ASSIGNED, OFFER_ASSIGNMENT_EMAIL_PENDING, OFFER_ASSIGNMENT_EMAIL_BOUNCED],
@adamstankiewicz Can you have a look at this? I will get this merged if this needs fix.

2019-03-08 16:56 UTC, brittneyexline commented on ecommerce/extensions/api/serializers.py
> +                status__in=[OFFER_ASSIGNED, OFFER_ASSIGNMENT_EMAIL_PENDING, OFFER_ASSIGNMENT_EMAIL_BOUNCED],
i think you are right @mushtaqak, but there is really no impact from this change if we merge it.

2019-03-08 16:56 UTC, brittneyexline approved these changes

2019-03-08 17:17 UTC, adamstankiewicz approved these changes

2019-03-08 18:00 UTC, merged