[WIP] ENT-1698 django rules based permission checks for enterprise api endpoints
openedx-unsupported/ecommerce pull request #2182
Opened 2019-03-21 07:23 UTC by irfanuddinahmad

Description: Updates authorization checks on all API endpoints, that are currently performing custom authorization logic related to enterprise, to use the django-rules based permission checks.

2019-03-22 21:04 UTC, brittneyexline reviewed
good start! i would take a look at the data api PR to see how the predicates should be set up. the comment about checking enterprise id applies here as well. also, please add testing instructions :-)

2019-03-22 21:04 UTC, brittneyexline commented on ecommerce/enterprise/rules.py
> +def is_enterprise_coupon_admin(user, obj):  # pylint: disable=unused-argument
i think we will need two predicates, similar to what is in the data api PR: https://github.com/edx/edx-enterprise-data/pull/112/files#diff-6c49a377b4da1d1d150c51be9f4afffeR19

2019-03-26 14:17 UTC, brittneyexline commented
@irfanuddinahmad @mushtaqak - based on our discussion and a quick look at the code, here are a few options:
1. make the enabled flag passed into the decorator take a function instead. as you said, it's not pretty, but there is already a lot going on in the decorator arguments.
2. try mocking the waffle call. this might be tricky to get right considering there are other places we call waffle.
3. move the waffle switch check to the predicate function directly. also not pretty, but considering this is being used as a implementation detail of how we're rolling it out, and we would want to remove the conditional logic anyway, this might be the best option in terms of both clarity and simplicity. i think it might require changing the decorator to allow a return value from the predicates that says skip this check, so that it doesn't return true or throw PermissionDenied.

my vote is for option 3, but i will leave it to you.

2019-03-26 18:14 UTC, christopappas commented on ecommerce/enterprise/rules.py
> +def request_user_has_explicit_access(*args, **kwargs):  # pylint: disable=unused-argument
This is a nitpicky thing, but if we're only using `user` from the args, should the function definition just accept `user` and not `*args` and `**kwargs`?

2019-03-26 18:18 UTC, christopappas commented on ecommerce/enterprise/rules.py
> +def request_user_has_explicit_access(*args, **kwargs):  # pylint: disable=unused-argument
You can ignore the above

2019-03-26 18:47 UTC, christopappas commented on ecommerce/extensions/api/v2/utils.py
> +    except:
Nitpick-ish, but, I'm always a fan of specifying the exact Exceptions that could be raised, instead of a bare `except`

2019-03-26 18:57 UTC, christopappas commented on ecommerce/extensions/api/permissions.py
> +        if waffle.switch_is_active(USE_ROLE_BASED_ACCESS_CONTROL):
So if our switch is active, then we are letting the user simply pass this permission check, eh?

I think my personal preference would be to not even have this check happen at all (kind of what we're doing in the data api); however, this seems to be functionally equivalent, so I'm cool with it. 👍  (Especially where it's likely we'll be dropping this code altogether soon enough)

2019-03-26 19:19 UTC, christopappas commented
Overall this looks good to me! Just gotta make codecov happy :)

2019-03-27 17:35 UTC, brittneyexline reviewed
i think as you are nearing the end of this implementation, it's time to write out test instructions for devstack for both the waffle switch on and off. at a high level, we need to test:
with the switch off:
* staff users with the enterprise_data_api_access group who are may or may not be linked to an enterprise get access.
* non-staff users linked to the same enterprise as the request object who have the enterprise_data_api_access group get access.
* all other users are denied (staff without the group, matching enterprise users without the group, non matching enterprise users with the group)

with the waffle switch on:
* users with the system wide role in their jwt and a matching enterprise get access.
* users with a feature specific role assignment with a matching enterprise get access.
* all other users are denied (this includes staff, for now, since we are relying on a future story to implement this)

2019-03-27 17:35 UTC, brittneyexline commented on ecommerce/enterprise/rules.py
> +    decoded_jwt = get_decoded_jwt_from_request(request)
we are going to need to take into account the context (enterprise id) and make sure it matches the request object, both here and below. for the explicit access check, we should add a nullable field to capture the enterprise id on the role assignment.

2019-03-27 17:35 UTC, brittneyexline commented on ecommerce/extensions/api/permissions.py
> +        if waffle.switch_is_active(USE_ROLE_BASED_ACCESS_CONTROL):
my concern with returning true here and in the predicates is that we will unintentionally give access all the time when the switch is on or off. we should consider what return value will result in skipping the check and relying on the correct one to evaluate - i don't know if returning true will result in that behavior.

2019-03-28 14:22 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    decoded_jwt = get_decoded_jwt_from_request(request)
@brittneyexline ... just wanted to know if this was what you had in mind?

2019-03-28 14:26 UTC, irfanuddinahmad commented on ecommerce/extensions/api/permissions.py
> +        if waffle.switch_is_active(USE_ROLE_BASED_ACCESS_CONTROL):
... the return true here is using an opposite condition as compared to the one in the predicates

2019-03-28 15:23 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +def is_enterprise_coupon_admin(user, obj):  # pylint: disable=unused-argument
Added

2019-03-28 15:23 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/utils.py
> +    except:
Changed

2019-03-29 15:35 UTC, christopappas commented on ecommerce/enterprise/rules.py
> +    if isinstance(obj, unicode):
do we want to use six.string_types here? 1 less thing to change for the impending py3 upgrade

2019-03-29 15:43 UTC, christopappas commented on ecommerce/enterprise/rules.py
> +            if isinstance(obj, unicode):
same question here about six.string_types

2019-04-01 15:50 UTC, brittneyexline commented on ecommerce/enterprise/rules.py
> +            if isinstance(obj, six.string_types):
i think it would be cleaner to either separate out this string or Product check into a separate function and just return a related enterprise id and pass it in for comparison. it looks kind of messy here and below - feels like it could by DRYer.

2019-04-01 15:50 UTC, brittneyexline commented on ecommerce/enterprise/rules.py
> +    return has_correct_context_for_implicit_access(obj, decoded_jwt, SYSTEM_ENTERPRISE_ADMIN_ROLE)
maybe once i merge https://github.com/edx/edx-rbac/pull/14/files we can refactor this to one call to the util function.

2019-04-01 15:50 UTC, brittneyexline commented on ecommerce/extensions/api/permissions.py
> +        if waffle.switch_is_active(USE_ROLE_BASED_ACCESS_CONTROL):
i think you are right @irfanuddinahmad - this should work.

2019-04-01 15:50 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        'enterprise.can_view_coupon', fn=lambda request, pk, format=None: Product.objects.filter(pk=pk).first(),
another option here would be to create a function that handles grabbing the enterprise id from a given product id and call it in this lambda function. that way the predicates are only concerned with enterprise ids being passed in.

2019-04-01 15:50 UTC, brittneyexline commented on ecommerce/settings/base.py
> +    'edx_rest_framework_extensions.auth.jwt.middleware.JwtAuthCookieMiddleware',
can you explain why we had to reorder this middleware setting for my own understanding?

2019-04-01 15:50 UTC, brittneyexline commented on ecommerce/enterprise/rules.py
> +    return has_correct_context_for_explicit_access(user, obj)
here also, we can consolidate to one call after the edx-rbac PR is merged.

2019-04-01 15:50 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        enabled=True)
do you think we should remove this enabled flag functionality?

2019-04-01 16:05 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    if isinstance(obj, unicode):
Done

2019-04-01 16:05 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +            if isinstance(obj, unicode):
Done

2019-04-01 16:08 UTC, irfanuddinahmad commented on ecommerce/settings/base.py
> +    'edx_rest_framework_extensions.auth.jwt.middleware.JwtAuthCookieMiddleware',
This was updated in master and I merely fixed a conflict. :)

2019-04-01 16:10 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        enabled=True)
Yes. This was added to support rollout with waffle ... however, it seems we cannot pass anything which uses the database ... some nose issue. Hence, it is quite redundant as far as ecommerce is concerned.

2019-04-03 10:21 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +            if isinstance(obj, six.string_types):
Done

2019-04-03 10:21 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    return has_correct_context_for_implicit_access(obj, decoded_jwt, SYSTEM_ENTERPRISE_ADMIN_ROLE)
Done

2019-04-03 10:21 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        'enterprise.can_view_coupon', fn=lambda request, pk, format=None: Product.objects.filter(pk=pk).first(),
Done

2019-04-03 10:21 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    return has_correct_context_for_explicit_access(user, obj)
Done

2019-04-03 13:46 UTC, mushtaqak requested changes
This is looking almost ready. I had a couple comments regarding rbac ...

2019-04-03 13:46 UTC, mushtaqak commented on ecommerce/enterprise/rules.py
> +    if not context:
I think we should add a comment why this is neccessary or this should be done in rbac [here](https://github.com/edx/edx-rbac/blob/daade8dd8711f30087e5ed1ead9a562fbe275bea/edx_rbac/utils.py#L88)

2019-04-03 13:46 UTC, mushtaqak commented on ecommerce/enterprise/rules.py
> +        return False
same as above.

2019-04-03 13:46 UTC, mushtaqak commented on ecommerce/enterprise/rules.py
> +    if not waffle.switch_is_active(USE_ROLE_BASED_ACCESS_CONTROL):
it would be great if we could add a new predicate for this switch  that can be placed in all rules?

2019-04-03 13:46 UTC, mushtaqak commented on ecommerce/enterprise/rules.py
> +    ) if decoded_jwt else False
Should this be handled in rbac ?

2019-04-03 13:46 UTC, mushtaqak commented on ecommerce/enterprise/constants.py
> +USE_ROLE_BASED_ACCESS_CONTROL = 'use_role_based_access_control'
This can be renamed to `ENTERPRISE_ROLE_BASED_ACCESS_CONTROL_SWITCH` for consistency.

2019-04-03 13:46 UTC, mushtaqak commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> -
unintentional ?

2019-04-03 13:46 UTC, mushtaqak commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        if self.role:
I don't think we need to add if statement here, since we are using `.get` which will throw `DoesNotExist` if not found.

2019-04-03 13:46 UTC, mushtaqak commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        EcommerceFeatureRoleAssignment.objects.all().delete()
Why are we deleting this almost in every second test ?

2019-04-03 14:30 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    if not context:
Agreed. I would suggest a separate ticket for the rbac work.

2019-04-03 14:35 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    ) if decoded_jwt else False
Agreed. This could be added to the rbac refactoring.

2019-04-03 14:38 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> +        EcommerceFeatureRoleAssignment.objects.all().delete()
This will disable the explicit permission so that we can effectively test the implicit ones.

2019-04-03 14:40 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/tests/views/test_enterprise.py
> -
This should be fine.

2019-04-03 14:41 UTC, irfanuddinahmad commented on ecommerce/enterprise/constants.py
> +USE_ROLE_BASED_ACCESS_CONTROL = 'use_role_based_access_control'
That seems too long. Also, this code will be removed pretty soon.

2019-04-03 14:42 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    ) if decoded_jwt else False
Since we are fetching it in this function, we should not pass on the validation to rbac.

2019-04-03 14:43 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    if not waffle.switch_is_active(USE_ROLE_BASED_ACCESS_CONTROL):
This is temporary code that will be removed very soon.

2019-04-03 14:46 UTC, irfanuddinahmad commented on ecommerce/enterprise/rules.py
> +    if not context:
@christopappas @brittneyexline your thoughts on returning False when context is absent ... as would be the case if the enterprise_id cannot be found in Invoice.business_client

2019-04-03 19:37 UTC, brittneyexline approved these changes

2019-04-04 14:16 UTC, mushtaqak approved these changes

2019-04-04 16:06 UTC, merged