add enterprise-openedx-operator permission checks
openedx-unsupported/ecommerce pull request #2200
Opened 2019-04-02 14:23 UTC by mushtaqak

https://openedx.atlassian.net/browse/ENT-1737

2019-04-05 10:41 UTC, mushtaqak commented
build is not being triggered, closing and re-opening ...

2019-04-05 16:25 UTC, brittneyexline commented on ecommerce/enterprise/rules.py
> +def request_user_is_edx_operator(user, context):    # pylint: disable=unused-argument
i think as long as the system wide role gets mapped to the coupon admin role in the settings, this check won't be needed. the context for the system wide role will be `*`, which is now supported to mean access to all enterprises based on Ammar's PR. so the existing check for the single feature specific role of enterprise_coupon_admin should be sufficient.

2019-04-05 21:44 UTC, christopappas approved these changes
Waffle switch refactor stuff looks good. I think we can remove the new predicate here because the same logic is covered in ammar's edx-rbac PR, other than that we're 👍

2019-04-09 09:11 UTC, muhammad-ammar requested changes
LGTM There is one minor comment.

2019-04-09 09:11 UTC, muhammad-ammar commented on ecommerce/core/models.py
> +            enterprise_id = self.enterprise_id and str(self.enterprise_id)
I think we only need `enterprise_id = str(self.enterprise_id)`

2019-04-09 09:25 UTC, muhammad-ammar approved these changes

2019-04-09 10:46 UTC, mushtaqak commented
@brittneyexline Can you please merge this? :shipit:

2019-04-09 15:27 UTC, merged