Enable Browser Back Button On Receipt Page
openedx-unsupported/ecommerce pull request #2440
Opened 2019-07-04 09:11 UTC by zainab-amir

#### Steps to reproduce current behavior:
* Go to https://ecommerce.edx.org/checkout/receipt/?order_number=EDX-29479306#jwudxzwa
* Press back button
* You will get a pop-up saying "Caution! Using the back button on this page may cause you to be charged again."

#### Expected Behavior:
* If a user is viewing order receipt from order history, don't disable the back button. 
* Disable only if the user has landed on receipt page after completing a payment, in which case user might be charged again if he goes back.

[PROD-376](https://openedx.atlassian.net/browse/PROD-376)

2019-07-04 10:32 UTC, waheedahmed commented
Seems like back button isn't disabled if we pay with credit card method instead of Paypal.

2019-07-04 10:33 UTC, waheedahmed reviewed
Seems like back button isn't disabled if we pay with credit card method instead of Paypal.

2019-07-16 09:13 UTC, waheedahmed requested changes

2019-07-16 09:13 UTC, waheedahmed commented on ecommerce/extensions/checkout/utils.py
> +        url = url + '&back_button=disable' if params else '?back_button=disable'
Use same functionality to add params like used at L50.

2019-07-16 09:13 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +                    disable_button=True
Why we need to disable it for free checkouts?

2019-07-16 09:13 UTC, waheedahmed commented on ecommerce/extensions/payment/processors/cybersource.py
> +                disable_button=True
Isn't it required in other payment processors?

2019-07-16 09:13 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +            'back_button': self.request.GET.get('back_button', "")
If we are passing it in context then I believe we should remove it from URL afterwards so that the user does not of it's existence.

2019-07-16 09:33 UTC, zainab-amir commented on ecommerce/extensions/payment/processors/cybersource.py
> +                disable_button=True
Other payment processors use default receipt page but cybersource overrides the receipt_page 
https://github.com/edx/ecommerce/blob/ff004d501dad10a3687c3cdab0210768e46f0442/ecommerce/extensions/payment/processors/cybersource.py#L183-L190
This step is redundant in cybersource ^ because the override page is same as default page 
https://github.com/edx/ecommerce/blob/ff004d501dad10a3687c3cdab0210768e46f0442/ecommerce/extensions/checkout/utils.py#L49

2019-07-16 09:36 UTC, zainab-amir commented on ecommerce/extensions/checkout/views.py
> +                    disable_button=True
I just disabled because it comes from the same payment page. I was thinking of a scenario where user uses a coupon that can only be used once and if he goes back he might be charged again. I might be wrong here. Let me know if I should continue to disable the button or remove it for free checkouts

2019-07-16 09:44 UTC, zainab-amir commented on ecommerce/extensions/payment/processors/cybersource.py
> +                disable_button=True
I think we can remove the disable_button option from here because this will return from here
https://github.com/edx/ecommerce/blob/ff004d501dad10a3687c3cdab0210768e46f0442/ecommerce/extensions/checkout/utils.py#L47
and goes to receipt page from here
https://github.com/edx/ecommerce/blob/ff004d501dad10a3687c3cdab0210768e46f0442/ecommerce/extensions/payment/views/cybersource.py#L363-L366

2019-07-19 12:56 UTC, waheedahmed approved these changes

2019-07-25 12:57 UTC, cpennington reviewed
It looks like having the back button disabled is the common/expected case? Should the default be `True`, and then have the few cases where we have an exception do disabling be the case that gets called out in the code?

2019-07-25 12:57 UTC, cpennington commented on ecommerce/coupons/tests/test_views.py
> +            params['back_button'] = 'disable'
If `params` isn't set, but `disable_button` is, shouldn't this still add `back_button` to the url (and thus need to create a new params object)?

2019-07-25 13:02 UTC, zainab-amir commented on ecommerce/coupons/tests/test_views.py
> +            params['back_button'] = 'disable'
In params, we add the order number, without order number the page is not rendered and gives and error. I don't see a scenario where order number is not sent and we want to view an empty receipt (it does not show empty receipt but throws an exception)
The right thing would be to ensure that order number is present, but that changes the scope of this ticket.

2019-07-25 13:04 UTC, robrap reviewed
@cpennington @mulby @sstack22: The Arch Squad had asked that:
1. That there would be a freeze on changes to the basket flow, and
2. If a high-priority item came up that we had to implement, then the Arch Squad would be informed.
I'm not sure if this got communicated to @fysheets @sethmccann.
Note: I do not think this will make it to the new Payment MFE the Arch Squad is working on without additional work, and that should be rolling out in the next week or two.  This change will still be required for the existing basket page (used for white label), but it would need to be duplicated in the Payment MFE config in terms of passing on this parameter.
FYI: @marcotuts

2019-07-25 13:04 UTC, robrap commented on ecommerce/extensions/checkout/utils.py
> +        params = six.moves.urllib.parse.urlencode(url_params) if order_number else ''
I don't like the use of `if order_number` in this line.  It wouldn't send the back_button disable if the order_number wasn't included.

I think something like the following would be cleaner:
```
        url_params = {}
        if order_number:
            url_params['order_number'] = order_number
        if disable_button:
            url_params['back_button'] = 'disable'

         base_url = site_configuration.build_ecommerce_url(reverse('checkout:receipt'))
         params = six.moves.urllib.parse.urlencode(url_params)
```

2019-07-25 13:04 UTC, robrap commented on ecommerce/coupons/tests/test_views.py
> +            params['back_button'] = 'disable'
Nit: I think `disable_back_button=1` would be more explicit than a special value of `disable`, because it would be clear it only has 2 values (i.e. on/off).

2019-07-25 13:12 UTC, zainab-amir commented
@cpennington 
> It looks like having the back button disabled is the common/expected case? Should the default be True, and then have the few cases where we have an exception do disabling be the case that gets called out in the code?

It should not be the default behavior to disable back button. Receipt page is referenced in emails and can be accessed via order page. To me it makes sense to enable back button by default and disable only if the flow hits payment page

2019-07-25 13:22 UTC, robrap commented
IMPORTANT: This cannot merge until the new Payment MFE is sending the same parameter to the receipt page.

2019-07-25 13:28 UTC, robrap commented
Note: My "DO NOT MERGE" change to the subject was to clarify that this should not merge before the new Payment MFE has a solution that will keep the back button working.

2019-07-25 20:02 UTC, robrap commented
@zainab-amir @cpennington: An alternative is to determine this based on referrer, which has its own advantages and disadvantages.  Not sure if this would be cybersource, paypal, applepay?, etc., so that may get too complicated.  Anyway, just a thought.  Also, at the very least, this is a reminder to ensure that cybersource and paypal and applepay all work for disabling properly.

2019-07-29 22:19 UTC, fysheets commented
Thanks for reaching out here @robrap. I know that I wasn't aware of any code freezes on changes or communications that needed to occur in areas of our code. Should we hand off this change to Arch with the PR + ticket so that the team can ensure that it does not get merged in prior to when the team is ready?

2019-07-29 23:32 UTC, robrap commented
I'm going to temporarily close this PR so it doesn't accidentally get merged.  It can be reopened when it is unblocked.

2019-07-29 23:32 UTC, closed without merging

2019-07-29 23:49 UTC, robrap commented
@fysheets: Let's loop back with @sstack22 and @mulby (when he returns) about the freeze.  The freeze should thaw soon though.

I don't think this should become an Arch Squad ticket, but you can discuss that with @nasthagiri.  I think this is independent of the scope of our work.  However, I do think it makes it clear that there is going to be a cost to bug fixes where both the microfrontend and legacy versions are being maintained.  Whatever we can do to resolve that issue will reduce scope of this kind.  Also, the escalations team is going to ultimately need experience working in the microfrontend world, because that is where are apps are headed.  So, even if we don't take the ticket, I'd be happy to provide help and guidance.  We can discuss more in person if necessary.

2019-08-02 18:52 UTC, robrap commented on ecommerce/coupons/tests/test_views.py
> +            params['back_button'] = 'disable'
@emma-green: This is the rename I requested that would affect the Payment MFE. ^