ENT-2035 | Adding new endpoint to return data about remaining code re…
openedx-unsupported/ecommerce pull request #2474
Opened 2019-07-16 21:17 UTC by christopappas

…pdemptions for a user

2019-07-18 19:27 UTC, brittneyexline reviewed
so i have an idea to make this "fight the framework" less potentially... though we'll have to think it through.
what if we made a vanilla model serializer for offer assignment, which should work for every field except redemptions remaining. we can implement a custom field for that and just do a filter by user, code and count those rows.
this leaves us with a problem of duplicate rows in the result set... either we try to pass a queryset of offer assignments that have a unique user and code selected (not sure if it's possible) or we filter out duplicate rows in the view afterward (which could mess with pagination).
just some food for thought... especially since the only wonky field stopping us from a vanilla model serializer is redemptions_remaining.

2019-07-18 19:27 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +                # objects that each of thse offerAssignments share (e.g. the benefit)
nit: thse -> these

2019-07-18 19:27 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            user_email=user_email
we'll also have to filter on the status at some point i think, or do you imagine that being the frontend's job? there could be a use case for showing what had been redeemed i guess...

2019-07-18 19:27 UTC, brittneyexline commented on ecommerce/extensions/api/v2/views/enterprise.py
> +    # permission_classes = (IsAuthenticated, IsAdminUser,)
we might actually need a new permission rule for this view. i imagine it would be enterprise learner where the request user matches the user_email provided at the very least, but i would say for now it might be out of scope. we can ask jennifer and then file a follow up ticket

2019-07-18 20:08 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +                # objects that each of thse offerAssignments share (e.g. the benefit)
👍

2019-07-18 20:11 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +    # permission_classes = (IsAuthenticated, IsAdminUser,)
reasonable to leave as admin user for now then? (depending on what jenn says of course)

2019-07-18 20:15 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            user_email=user_email
with this endpoint the way it's written, the frontend would not have anything to filter out, because we are sending a rolled up summary type response (irrespective of status). I think it's probably not a big deal to add filtering on status via query params here if we need it, but probably a think we can wait and see about

2019-07-18 20:16 UTC, christopappas commented
yeah @brittneyexline there is a OfferAssignmentSerializer already :D -- potentially an option to use this for whatever we need too

2019-07-19 15:02 UTC, christopappas commented
@brittneyexline -- after walking away from this for a bit, my feeling is that if we're cool with doing the counting/de-duping on the frontend, then we should scrap this and use the vanilla offerAssignment serializer for our needs. If we prefer to do all the counting/de-duping on the backend, for now I think this meets our needs

It sounded like we preferred the backend handling this logic though, so, I'm good with proceeding if you are!

Ready for re-review :)

2019-07-22 15:14 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
This is an interesting return for get_queryset ... quite unorthodox! ...
https://www.django-rest-framework.org/api-guide/filtering/

2019-07-22 16:50 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
Agreed that it's a bit unorthodox! Needed a place to "roll up" the results and the `get_queryset` method seemed like the best place to do it. A list of dictionaries isn't terrible to serialize though, so it is my hope that the code is approachable.

Another potential solution for this issue was to use a `Count('code')` in my queryset in conjunction with a `.values()` `.order_by()` and `.distinct('code')` which I believe would effectively rollup the query_set to single unique entries (per code), while including the total count per each code (which is what we want); however, use of `.distinct('code')` maps to `DISTINCT ON` which is a postgres only operation, so I avoided exploring this solution

2019-07-23 13:24 UTC, muhammad-ammar requested changes

2019-07-23 13:24 UTC, muhammad-ammar commented on ecommerce/extensions/api/serializers.py
> +class OfferAssignmentSummarySerializer(serializers.Serializer):
I think we don't need `create` and `update` and we can create a read-only serializer like https://www.django-rest-framework.org/api-guide/serializers/#read-only-baseserializer-classes.

2019-07-23 13:28 UTC, mushtaqak requested changes
Nice start. I left some suggestions regarding serializer, viewset and queryset.

2019-07-23 13:28 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +class OfferAssignmentSummarySerializer(serializers.Serializer):
Suggestion:

I think we can create a model serializer keeping assignements data (however it would need to have an extra field that would come through methodfield)

Also, once that serializer is created, we can use that in the serializer which has count and offer assignment object. So we will be creating 2 serializers in short.

2019-07-23 13:28 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +    def create(self, validated_data):
I think we don't need to override these methods.

2019-07-23 13:28 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +    def update(self, instance, validated_data):
I think we don't need to override these methods.

2019-07-23 13:28 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +    def to_representation(self, instance):
A lot of this logic could be easily implemented when we create 2 serializers.

2019-07-23 13:28 UTC, mushtaqak commented on ecommerce/extensions/api/v2/urls.py
> +    r'enterprise/offer-assignment-summary',
I would have made url part in underscores (this is standard followed in most of the edx code) ... `r'enterprise/offer_assignment_summary`

2019-07-23 13:28 UTC, mushtaqak commented on ecommerce/extensions/api/v2/views/enterprise.py
> +class OfferAssignmentSummaryViewSet(ModelViewSet):
May be we don't need `ModelViewSet` here, a simple ViewSet would suffice I guess. Also if this is view is just read-only, I would either disallow other methods except `GET` or just implement an `APIView` with get method.

2019-07-23 13:28 UTC, mushtaqak commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        offer_assignments_with_counts = {}
I think this can be done using `Count`. A lot of this logic could be skipped in this way.

```
from django.db.models import Count
queryset  = OfferAssignment.objects.filter(
    user_email=user_email,
    status__in=[OFFER_ASSIGNED, OFFER_ASSIGNMENT_EMAIL_PENDING]
).values().order_by('code').annotate(count=Count('code'))
```

2019-07-23 17:14 UTC, christopappas commented on ecommerce/extensions/api/serializers.py
> +class OfferAssignmentSummarySerializer(serializers.Serializer):
Linter was complaining about this. Changing to BasedSerializer did the trick, so I can remove them now. Thanks!

2019-07-23 17:14 UTC, christopappas commented on ecommerce/extensions/api/serializers.py
> +    def create(self, validated_data):
Linter was complaining about this. Changing to BasedSerializer did the trick, so I can remove them now. Thanks!

2019-07-23 17:26 UTC, christopappas commented on ecommerce/extensions/api/v2/urls.py
> +    r'enterprise/offer-assignment-summary',
okay, i can change this

2019-07-23 17:37 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        offer_assignments_with_counts = {}
So the tough thing with this PR is, we want our response only to have a few unique objects serialized and returned. Serializing this queryset would return a number of offerAssignments with duplicate codes in the response

Say code, "AAAA" can be used 3 times, there would be 3 offerAssignment objects (or dictionaries) in the queryset handed to the serializer with the same code, when we would only want to serialize it once, but add "redemptions_remaining": 3 in that one unique objects/dict.

Additionally, serializers don't know anything about other objects in the queryset that is being serialized. So once I've hit serialization, I can no longer remove duplicates entries from my final API response.

I know you had a few recommendations around serialization above, and I will continue to think about it, but I'm not sure yet how I can achieve what I've done in a different way

2019-07-23 17:50 UTC, christopappas commented on ecommerce/extensions/api/serializers.py
> +class OfferAssignmentSummarySerializer(serializers.Serializer):
How do we handle not having duplicate entries in our API response? Even if you have an embedded serializer, you are going to be processing some larger queryset to begin with, right? Once you're in serializer code, I don't think there's a way to know if you've processed certain objects already (for, in our case, avoiding returning duplicate objects)

2019-07-23 18:32 UTC, christopappas commented on ecommerce/extensions/api/serializers.py
> +    def create(self, validated_data):
actually, I lied! the linter still complains even if I use BaseSerializer. I have to override these functions :(

2019-07-23 18:32 UTC, christopappas commented on ecommerce/extensions/api/serializers.py
> +class OfferAssignmentSummarySerializer(serializers.Serializer):
actually, I lied! the linter still complains even if I use BaseSerializer. I have to override these functions :(

2019-07-23 18:35 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +class OfferAssignmentSummaryViewSet(ModelViewSet):
In an upcoming commit, I have made only GET and HEAD acceptable methods for the view set, effectively making this read-only 👍 

Leaving as a ModelViewSet though, as it abstracts away some of things I don't think we need to worry about right now (specific response ERROR codes, pagination, etc)

2019-07-23 20:28 UTC, christopappas commented
Ready to be reviewed again after feedback

Also, I added a `select_related` to my query_set to cut down on the number of DB queries made (also made the endpoint more performant at least with the number of codes my test user had).

2019-07-24 15:04 UTC, mushtaqak commented on ecommerce/extensions/api/serializers.py
> +class OfferAssignmentSummarySerializer(serializers.Serializer):
You are right, these methods are abstract, which means we need to override if we want to use them. 

However, I see that we have creates some serializers who had inherited from `serializers.Serializer` but they do not override the `update` and `create` methods because they don't use them which makes them read only serializers ...

So to fix linter issue we can disable it by adding `# pylint: disable=abstract-method`.
```
class OfferAssignmentSummarySerializer(serializers.Serializer):    # pylint: disable=abstract-method
```

2019-07-24 15:05 UTC, christopappas commented on ecommerce/extensions/api/serializers.py
> +class OfferAssignmentSummarySerializer(serializers.Serializer):
Okay, I will do this 👍

2019-07-24 15:08 UTC, mushtaqak approved these changes

2019-07-24 15:16 UTC, muhammad-ammar approved these changes

2019-07-24 19:14 UTC, cpennington commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
I don't think you need a `distinct`, in this case... If you were doing this with straight sql, a `GROUP BY` would be sufficient, right? You want something equivalent to:

```
SELECT
code, 
benefit.*,
condition.*,
COUNT(*)
FROM
offerassignment
WHERE user_email=:user_email
AND status IN ('assigned', 'pending')
GROUP BY code, benefit.*, condition.*
```

I think just doing the `.values(... a bunch of fields that are the same here ...).annotate(count=Count('code')` will get you the right answer?

2019-07-24 20:25 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
So I did try different combinations of the above, but what I found is that a test fails around the count for a MULTI_USE_PER_CUSTOMER coupon. I assert 7 is the right value for offer assignments for our user (this coupon in question has a max use of 78), but the count returned in the API response is 35 (interestingly, there are 5 of these MULTI_USE_PER_CUSTOMER coupon created).

Here is the query:

```
queryset  = OfferAssignment.objects.filter(
            user_email=user_email,
            status__in=[OFFER_ASSIGNED, OFFER_ASSIGNMENT_EMAIL_PENDING]
        ).select_related(
            'offer__benefit',
            'offer__condition',
        ).values(
            'status',
            'code',
            'user_email',
            'offer__condition__enterprise_customer_catalog_uuid',
            'offer__vouchers__start_datetime',
            'offer__vouchers__end_datetime',
            'offer__benefit__id'
        ).annotate(count=Count('code'))
```

Here is the SQL from that query returns:

```
SELECT "offer_offerassignment"."status", "offer_offerassignment"."code", "offer_offerassignment"."user_email", "offer_condition"."enterprise_customer_catalog_uuid", "voucher_voucher"."start_datetime", "voucher_voucher"."end_datetime", "offer_conditionaloffer"."benefit_id", COUNT("offer_offerassignment"."code") AS "count" FROM "offer_offerassignment" INNER JOIN "offer_conditionaloffer" ON ("offer_offerassignment"."offer_id" = "offer_conditionaloffer"."id") INNER JOIN "offer_condition" ON ("offer_conditionaloffer"."condition_id" = "offer_condition"."id") LEFT OUTER JOIN "voucher_voucher_offers" ON ("offer_conditionaloffer"."id" = "voucher_voucher_offers"."conditionaloffer_id") LEFT OUTER JOIN "voucher_voucher" ON ("voucher_voucher_offers"."voucher_id" = "voucher_voucher"."id") WHERE ("offer_offerassignment"."user_email" = test@example.com AND "offer_offerassignment"."status" IN (ASSIGNED, EMAIL_PENDING)) GROUP BY "offer_offerassignment"."status", "offer_offerassignment"."code", "offer_offerassignment"."user_email", "offer_condition"."enterprise_customer_catalog_uuid", "voucher_voucher"."start_datetime", "voucher_voucher"."end_datetime", "offer_conditionaloffer"."benefit_id", "offer_offerassignment"."modified", "offer_offerassignment"."created" ORDER BY "offer_offerassignment"."modified" DESC, "offer_offerassignment"."created" DESC
```

Not quite sure how else to "phrase" the django filters to get what I'm after 🤔

2019-07-24 21:02 UTC, mushtaqak commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
@christopappas Django has a weird behavior in this case.  To apply group_by you would need to add a `.order_by('code')` after the `.values(...)` ... not sure if this would solve the issue but worth trying.
```
queryset  = OfferAssignment.objects.filter(
            user_email=user_email,
            status__in=[OFFER_ASSIGNED, OFFER_ASSIGNMENT_EMAIL_PENDING]
        ).select_related(
            'offer__benefit',
            'offer__condition',
        ).values(
            'status',
            'code',
            'user_email',
            'offer__condition__enterprise_customer_catalog_uuid',
            'offer__vouchers__start_datetime',
            'offer__vouchers__end_datetime',
            'offer__benefit__id'
        ).order_by('code').annotate(count=Count('code'))
```

2019-07-24 21:14 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
thanks @mushtaqak ! unfortunately, i get the same result 😞

2019-07-25 15:50 UTC, cpennington commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
This sounds a bit like https://docs.djangoproject.com/en/1.11/topics/db/aggregation/#combining-multiple-aggregations. If you're game for trying that, great, otherwise I think it's fine to merge as-is.

2019-07-25 15:58 UTC, cpennington commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
I dug in a little bit, and one thing I noticed is that the query is adding a groupby and order by on `offer_assignment.modified` and `.created`, even those aren't being selected. In my test query on staging, that resulted in getting multiple rows with the same values, rather than correctly grouping them. Not sure how to get rid of that problem via the django query, though.

2019-07-25 16:14 UTC, christopappas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        return offer_assignments_with_counts.values()
Noodled around with the `distinct=True` on Count, and trying to see if i can finagle a count on other fields to achieve what i'm after. no dice yet, but if you're okay with merging this, i'm happy too

2019-07-25 19:06 UTC, merged