set benefit_type and benefit_value for dynamic_conditional_offer
openedx-unsupported/ecommerce pull request #2530
Opened 2019-08-08 21:00 UTC by MatthewPiatetsky

2019-08-09 18:51 UTC, emma-green requested changes

2019-08-09 18:51 UTC, emma-green commented on ecommerce/extensions/basket/views.py
> +                benefit_value = get_percentage_from_request()
this function is unique to the dynamic discount offer, so if you are going to use it, I think you should check for that specific offer in the condition.

2019-08-09 19:03 UTC, MatthewPiatetsky commented on ecommerce/extensions/basket/views.py
> +                benefit_value = get_percentage_from_request()
that's a fair point, that if this function is only intended to work for this offer it would make sense to check the offer directly
@robrap i know you were recommending not to check the offer
do you have thoughts about what approach might be sufficiently extensible?
i had been thinking i could directly override benefit.value in the code for this benefit, but that didn't seem to work

2019-08-09 20:33 UTC, MatthewPiatetsky commented on ecommerce/extensions/offer/dynamic_conditional_offer.py
> +class DynamicPercentageDiscountBenefit(BenefitWithoutRangeMixin, PercentageDiscountBenefit, PercentageBenefitMixin):
this mixin will make the type of this offer in the payment api response 'Percentage'

2019-08-09 20:34 UTC, MatthewPiatetsky commented on ecommerce/extensions/offer/utils.py
> +    value = getattr(benefit.proxy(), 'benefit_class_value', benefit.value)
we could use this pattern which is similar to the one used above for benefit_type, to have a dynamic value set for this benefit

2019-08-09 20:35 UTC, MatthewPiatetsky commented on ecommerce/extensions/basket/views.py
> +                benefit_value = get_percentage_from_request()
i've updated the code with a new pattern that i think will allow us to not check for the specific offer

2019-08-12 14:24 UTC, cpennington approved these changes

2019-08-13 13:46 UTC, merged