WIP: Added management command to populate history as of 06/29.
openedx-unsupported/ecommerce pull request #2642
Opened 2019-10-24 14:09 UTC by HassanJaveed84

2019-10-28 16:14 UTC, pwnage101 requested changes

2019-10-28 16:14 UTC, pwnage101 commented on ecommerce/core/management/commands/backfill_history.py
> +                        raise Exception(u"Database count: %s does not match input count: %s" % (count, len(ids)))
ids is just a string, in think.  You probably want row_ids or rows:

```suggestion
                        raise Exception(u"Database count: %s does not match input count: %s" % (count, len(rows)))
```

2019-10-28 16:14 UTC, pwnage101 commented on ecommerce/core/management/commands/backfill_history.py
> +                    values = [tuple(value) for value in values]
Nit:
```suggestion
                    values = [tuple(row) for row in values]
```

2019-10-29 19:00 UTC, pwnage101 approved these changes

2019-10-29 19:57 UTC, bmedx approved these changes
Seems ok to me, what are the commented out tables?

2019-10-29 20:48 UTC, HassanJaveed84 commented
I commented out the ones with no missing historical records. I'll remove them.

2019-10-30 12:51 UTC, HassanJaveed84 commented
@cpennington please review and merge.

2019-10-30 14:43 UTC, cpennington commented
I'm having some deja vu. Didn't I already review this command?

2019-10-30 14:46 UTC, cpennington approved these changes

2019-10-30 14:56 UTC, merged

2019-10-30 16:52 UTC, HassanJaveed84 commented
That was the Step 1 out of 2 of history population. This is the second step.
I had created a PR to remove it, please merge(I just rebased it): 
https://github.com/edx/ecommerce/pull/2615