WIP: Send course purchase email
openedx-unsupported/ecommerce pull request #2645
Opened 2019-10-25 12:34 UTC by zainab-amir

Send verified course purchase email to learners. 
Previously we sent these emails for cybersource payment processor but we should send these to any user who goes through the checkout process.

2019-10-31 07:51 UTC, waheedahmed reviewed
Generally looks good, just one question.

2019-10-31 07:51 UTC, waheedahmed commented on ecommerce/extensions/checkout/signals.py
> +        if product.is_seat_product:
What about entitlement product? Do we also need to send receipts for them or there is already an email going for them from somewhere else?

2019-10-31 09:13 UTC, zainab-amir commented on ecommerce/extensions/checkout/signals.py
> +        if product.is_seat_product:
It's sent from `EnrollmentCodeFulfillmentModule` 
https://github.com/edx/ecommerce/blob/2c3af49eeb9f1f15b4391b2583c1692b6fe29d98/ecommerce/extensions/fulfillment/modules.py#L573

2019-10-31 09:37 UTC, waheedahmed commented on ecommerce/extensions/checkout/signals.py
> +        if product.is_seat_product:
`EnrollmentCode` is a separate product, I'm talking about `Entitlement` product.

2019-10-31 09:54 UTC, zainab-amir commented on ecommerce/extensions/checkout/signals.py
> +        if product.is_seat_product:
Ah no. We don't send any email for those.

2019-11-05 11:57 UTC, waheedahmed requested changes

2019-11-05 11:57 UTC, waheedahmed commented on ecommerce/extensions/checkout/tests/test_signals.py
> +        credit_provider_id = 'HGW'
Remove this unnecessary variable.

2019-11-05 11:57 UTC, waheedahmed commented on ecommerce/extensions/checkout/tests/test_signals.py
> +        self.assertEqual(mail.outbox[0].subject, 'Order Placed')
Can we somehow verify that the email is actually sent for the correct product here and in product type seat test case?

2019-11-05 11:57 UTC, waheedahmed commented on ecommerce/extensions/checkout/signals.py
> -                logger.error(
Can we keep this log under a check if the mode is `credit` but there is no credit provider information? It can help investigating credit config related issues.

2019-11-05 12:05 UTC, zainab-amir commented on ecommerce/extensions/checkout/tests/test_signals.py
> +        credit_provider_id = 'HGW'
we need this, this is for when `credit_provider_id` is present but no `credit_provider_data` exists

2019-11-05 12:07 UTC, waheedahmed commented on ecommerce/extensions/checkout/tests/test_signals.py
> +        credit_provider_id = 'HGW'
I mean use the value directly because there is only one place where we are using this.

2019-11-06 07:35 UTC, waheedahmed approved these changes

2019-11-08 07:24 UTC, adeelkhan approved these changes

2019-11-13 09:13 UTC, merged