ENT-2263 Added Search By Code Functionality
openedx-unsupported/ecommerce pull request #2717
Opened 2019-12-04 12:36 UTC by sameenfatima78

**ENT 2263**: customers need to be able to search for codes in batches.

This pull request is an enhancement of search functionality in **Code Management Portal**. As requested in the ticket (**ENT-2263**), enterprise admins can now make a search by code as well. The search results would help them figure out which voucher code belongs to which coupon batch and will also give them useful information about the assignment of the _searched_ voucher.

**STEPS TO TEST IT:**
- Open Code Management Portal
- Pick out any voucher from any of the coupons shown below
- Copy/Paste the code in the search bar at the top
- See results

2019-12-12 07:33 UTC, irfanuddinahmad requested changes

2019-12-12 07:33 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        search_parameter = self.request.query_params.get('search_parameter', None)
You could add code as an additional parameter.

2019-12-12 13:22 UTC, sameenfatima78 commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        search_parameter = self.request.query_params.get('search_parameter', None)
Fixed.

2019-12-13 10:16 UTC, irfanuddinahmad requested changes

2019-12-13 10:16 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        user_code = self.request.query_params.get('user_code', None)
nit: user_code -> voucher_code

2019-12-13 10:16 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +                'status__in': [OFFER_ASSIGNED, OFFER_ASSIGNMENT_EMAIL_PENDING],
Should we have these filters for searching by code?

2019-12-13 10:39 UTC, irfanuddinahmad requested changes

2019-12-13 10:39 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +                    redemption_data = dict(coupon_data)
DRY: Can we create an inner function to handle this code repetition?

2019-12-13 13:06 UTC, irfanuddinahmad requested changes

2019-12-13 13:06 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        redemption_data = dict(coupon_data)
nit: docstring

2019-12-13 13:06 UTC, irfanuddinahmad commented on ecommerce/extensions/api/v2/views/enterprise.py
> +                    redemptions_and_assignments.append(redemption_data)
You can take this inside the  _prepare_redemption_data and make that an inner function of _form_search_response_data_from_vouchers

2019-12-16 12:06 UTC, georgebabey approved these changes

2019-12-16 13:35 UTC, merged