Add Custom Applicator to calculate view
openedx-unsupported/ecommerce pull request #2770
Opened 2020-02-03 11:56 UTC by zainab-amir

Right now the about pages and basket add view are using different mechanisms to calculate price of programs, which is causing confusion for leaners. 
For Program `IBM Data Science`, https://www.edx.org/es/professional-certificate/ibm-data-science ,the about page shows,
<img width="560" alt="Screenshot 2020-02-03 at 4 51 11 PM" src="https://user-images.githubusercontent.com/40633976/73651108-8b5e9080-46a5-11ea-9cb6-2cebb8fbbbda.png">
and the basket calculates the total as
<img width="548" alt="Screenshot 2020-02-03 at 4 51 33 PM" src="https://user-images.githubusercontent.com/40633976/73651116-93b6cb80-46a5-11ea-8c23-d455ae45398a.png">

The Applicator used on about page is applying offer of another program (`Python Data Science`) when it shouldn't be doing that. Using CustomApplicator on CalculateView will solve this issue

2020-02-03 12:49 UTC, waheedahmed requested changes
Why can't we simply create a bundle attribute for this temporary basket which will be deleted eventually when transaction is rolled back on raising `TemporaryBasketException` at the end of basket calculate view?

2020-02-03 12:49 UTC, waheedahmed commented on ecommerce/extensions/offer/applicator.py
> +        if self.bundle_id:
I believe we can simplify it like following or some other way:
```
bundle_attributes = BasketAttribute.objects.filter(
    basket=basket,
    attribute_type=BasketAttributeType.objects.get(name=BUNDLE)
)
if self.bundle_id or bundle_attributes.count() > 0:
    bundele_id = self.bundle_id or bundle_attributes.first().value_text
    program_offers = self.get_program_offers(bundele_id)
```

2020-02-03 13:21 UTC, zainab-amir commented
Because this temporary basket is not commited to db, creating a BundleAttribute against it raises ValueError
```
ValueError: save() prohibited to prevent data loss due to unsaved related object 'basket'.
```

2020-02-04 06:47 UTC, zainab-amir commented on ecommerce/extensions/offer/applicator.py
> +        if self.bundle_id:
This will make an extra query to db if `self.bundle_id` is present, I was trying to avoid that

2020-02-04 07:14 UTC, waheedahmed commented on ecommerce/extensions/offer/applicator.py
> +        if self.bundle_id:
I don't think it will. If `self.bundle` is present, it won't check for or condition and until an operation is performed on the filter it won't hit the database.

2020-02-04 10:26 UTC, waheedahmed approved these changes

2020-02-04 13:55 UTC, robrap commented
Could there be similar bugs in other parts of Ecommerce still using the old Applicator, or do we think this is specific to this code?

2020-02-06 06:58 UTC, zainab-amir commented
@robrap I just did a quick review of code and saw that old applicator is used in ~5 places without CUSTOM_APPLICATOR_USE_FLAG. Should I create a ticket to investigate old applicator's usage and impact ?

2020-02-06 15:59 UTC, robrap commented
@zainab-amir: I personally would add/update the ADR for the Custom Applicator describing that it should be the only one in use, or we will potentially run into bugs and will certainly run into performance issues.

* There is already a PR that was in progress for updating all of ecommerce to use the Custom Applicator.  
* There is also a PR for the start of an ADR that I think never landed that @cpennington had last worked on.
* Here is a search for these PRs: https://github.com/edx/ecommerce/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+custom+applicator

Given that, @emma-green is the ecommerce owner, and needs to work with you to determine how this gets ticketed/prioritized.

2020-02-07 06:29 UTC, zainab-amir commented
@robrap I will work with Emma on it. 
Is this okay to merge? Can you review it kindly ?

2020-02-07 06:40 UTC, zainab-amir commented
There already is a ticket which is in grooming to change the Applicator 
https://openedx.atlassian.net/browse/EG-42

2020-02-07 19:00 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
> +                    CustomApplicator(bundle_id).apply(basket, user=user, request=request)
Sorry - this is my first time actually looking at this.  This doesn't feel right.  What would be the typical situation where `bundle_id` gets added such that later `bundle_attributes.count() > 0`?  Can we make that happen so that the `bundle_id` doesn't need to be passed in specially here?

2020-02-10 06:12 UTC, zainab-amir commented on ecommerce/extensions/api/v2/views/baskets.py
> +                    CustomApplicator(bundle_id).apply(basket, user=user, request=request)
Normally we create a BasketAttribute with `attribute_type` set to `BUNDLE`.
```
BasketAttribute.objects.update_or_create(
    basket=basket,
    attribute_type=BasketAttributeType.objects.get(name=BUNDLE),
    defaults={'value_text': bundle}
)
```
This makes the `bundle_attributes.count() > 0` but in our case we are not actually making a basket in db, we are just using a temporary basket (not committed to db), to calculate the price of program and show it on about page. Creating a BasketAttribute object for it raises ValueError
```
ValueError: save() prohibited to prevent data loss due to unsaved related object 'basket'.
```

The other solution is to override the `apply` function and pass bundle_id as a parameter.

2020-02-10 15:16 UTC, robrap commented on ecommerce/extensions/offer/applicator.py
> +    def get_program_offers(self, bundle_id):
Not a blocker to landing this, but if this is truly not called from anywhere outside, can we use the `_` prefix convention (e.g. `_get_program_offers`) to show that this, and any other private methods, are only meant to be used for internal processing?

2020-02-10 15:16 UTC, robrap commented on ecommerce/extensions/api/v2/views/baskets.py
> +                    CustomApplicator(bundle_id).apply(basket, user=user, request=request)
Thanks for explaining this again.  I forgot you had explained this.
My thoughts would be:
1. The apply function seems like a better place for this.  This seems like a function of applying this to the basket.
2. I would put your explanation in the comment to the new argument for bundle_id.  Something like:
```
    bundle_id (int): (Optional) The bundle_id of the basket.  This should only be used in the case of a temporary
        basket which is not saved to the db, because we get an error when trying to create the bundle_id
        BasketAttribute.
```
3. Possibly you could add an assertion that this `basket_id` parameter is only used if the basket is marked as temporary (I think there is a flag or something on the basket).  I'm just concerned that this is going to lead to other difficult to find bugs if it is used in places where it isn't meant to be used.

2020-02-10 15:19 UTC, robrap commented
@zainab-amir @waheedahmed: I added some comments.  Hopefully you can handle both the updates and review on your side without waiting on another review from Cambridge.  Feel free to put out a fix for the issue,  and if we want to improve comments (or something like that) in a quick follow-up PR, we can do that separately.  Thank you!

2020-02-11 19:08 UTC, robrap approved these changes
I don't think any of the changes below are required in this PR, but it would be nice to follow-up.

2020-02-11 19:08 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +    @override_flag(CUSTOM_APPLICATOR_USE_FLAG, active=False)
You can wait for a follow-up PR if you want, but I think this flag was just for rolling out/testing the custom applicator when it was first written.  I think this flag can probably be removed altogether, but at least in this new code, you don't need tests like this and you don't need to use the flag.  Just use the updated applicator that works.

2020-02-11 19:08 UTC, robrap commented on ecommerce/extensions/api/v2/tests/views/test_baskets.py
> +    def create_program_with_courses_and_offer(self):
If this is used only in this class, can you rename to `_create_program_with_courses_and_offer` to make it more clear it is private (like the next method, `_setup_anonymous_basket_calculate`).

2020-02-11 19:08 UTC, robrap commented on ecommerce/extensions/offer/applicator.py
> +            get an error when trying to create the bundle_id BasketAttribute.
Nit: Add extra indent to these two lines.

2020-02-11 19:08 UTC, robrap commented on ecommerce/extensions/offer/applicator.py
> +        are dependent on the user (eg session-based offers).
This new comment isn't clear to me. We should either clarify it or remove it.  Also, if possible, adding these details below to `user` or `request` might be one way to help clarify.

2020-02-11 19:08 UTC, robrap commented on ecommerce/extensions/offer/applicator.py
> +
For future PR, maybe do something like the following (untested):
```
# use the bundle attribute if it exists.  otherwise, try the passed in bundle_id.
program_uuid = bundle_id if bundle_attributes.count() == 0 else bundle_attributes.first().value_text
if program_uuid:
    ...
```
This has two advantages:
1. It doesn't repeat `bundle_id or ...` and puts that logic into one place.
2. It gives precedence to the bundle attribute, and doesn't allow you to override the bundle_id if you have a bundle attribute.

2020-02-11 19:08 UTC, robrap commented on ecommerce/extensions/offer/applicator.py
> +    def get_offers(self, basket, user=None, request=None, bundle_id=None):  # pylint: disable=arguments-differ
Is this public or private?  Use the prefix `_` if private.

2020-02-12 07:02 UTC, waheedahmed approved these changes

2020-02-12 07:40 UTC, merged