WIP --- ENT-2523
openedx-unsupported/ecommerce pull request #2771
Opened 2020-02-03 13:11 UTC by muhammad-ammar

2020-02-03 15:21 UTC, ziafazal requested changes
@muhammad-ammar completed first round of review.

2020-02-03 15:21 UTC, ziafazal commented on ecommerce/extensions/offer/models.py
> +    email_type = models.CharField(
should be indexed

2020-02-03 15:21 UTC, ziafazal commented on ecommerce/extensions/offer/models.py
> +    active = models.BooleanField(
do we need `active` field what if pull last modified as active?

2020-02-03 15:21 UTC, ziafazal commented on ecommerce/extensions/offer/models.py
> +    enterprise_customer = models.UUIDField(help_text=_('UUID for an EnterpriseCustomer from the Enterprise Service.'))
should be indexed

2020-02-03 15:21 UTC, ziafazal commented on ecommerce/extensions/offer/models.py
> +from jsonfield import JSONField
not used anymore

2020-02-03 15:21 UTC, ziafazal commented on ecommerce/extensions/api/serializers.py
> +    def create(self, validated_data):
I'm not able to understand the reason for overriding this `create` method.

2020-02-07 06:53 UTC, muhammad-ammar commented on ecommerce/extensions/offer/models.py
> +    active = models.BooleanField(
I added `active` field to explicitly mark the active template. When we have template version manager, It may be possible that admin modified couple of old templates but wants to active a different template.

2020-02-07 06:53 UTC, muhammad-ammar commented on ecommerce/extensions/api/serializers.py
> +    def create(self, validated_data):
There are 2 reason:
1. We need to `bleach` the incoming `greeting` and `closing` texts to avoid XSS.
2. We need to deactivate(`active=False`) the old templates.

2020-02-10 10:33 UTC, muhammad-ammar commented
@ziafazal This is ready for 2nd review.

2020-02-11 06:21 UTC, ziafazal approved these changes
@muhammad-ammar overall looks good. Could you please create indexes in `active` and `email_type` fields?
👍

2020-02-11 11:54 UTC, muhammad-ammar commented
@ziafazal I have added a multi-column index on `enterprise_customer` and `email_type`.

2020-02-11 17:39 UTC, moconnell1453 approved these changes

2020-02-14 10:13 UTC, merged