ENT-2763: Fail gracefully if enterprise of learner is not found
openedx-unsupported/ecommerce pull request #2898
Opened 2020-04-13 07:31 UTC by ziafazal

Fail gracefully if enterprise of learner is not found
ENT-2763

2020-04-13 08:11 UTC, zamanafzal approved these changes

2020-04-13 13:50 UTC, moconnell1453 commented on ecommerce/enterprise/utils.py
> +        log.info('Unable to retrieve enterprise learner data for User: %s, Exception: %s', user, exc)
While we're modifying this method, and the similar usage in checkout/views.py in this same PR, it seems that we are no longer interested in reporting this exception as an exception. In that case, I would prefer to see a modification in fetch_enterprise_learner_data() to handle these exceptions when making the call to the Enterprise API, and return None. Methods that call fetch_enterprise_learner_data() should expect None as a potential outcome and handle it accordingly.

2020-04-13 13:54 UTC, moconnell1453 requested changes
With fetch_enterprise_learner_data() as a common point of failure if enterprise endpoints are not available, I would prefer to see changes made there to eliminate unnecessary exception handling for components using that method.

2020-04-14 13:26 UTC, moconnell1453 approved these changes

2020-04-15 08:12 UTC, merged