[WIP][REV-1170] Redirect to payment mfe when static page submits an invalid coupon
openedx-unsupported/ecommerce pull request #2932
Opened 2020-04-29 15:21 UTC by MatthewPiatetsky

applying an invalid coupon from the static page was throwing an uncaught exception
modifying this behavior to direct to the regular payment page instead

2020-04-30 14:04 UTC, julianajlk approved these changes

2020-04-30 14:13 UTC, dianekaplan approved these changes

2020-04-30 14:29 UTC, emma-green requested changes
This seems like it would have implications for the other uses of the add endpoint

2020-04-30 14:29 UTC, emma-green commented on ecommerce/extensions/basket/views.py
> +                # applying an invalid coupon from the static page was throwing an uncaught exception
We want to make sure this flow works from everything besides the static page. I think the correct thing to do here is not skip the rest of the flow.

2020-04-30 14:42 UTC, MatthewPiatetsky commented on ecommerce/extensions/basket/views.py
> +                # applying an invalid coupon from the static page was throwing an uncaught exception
currently that exception is not caught so the current behavior without this is it throws a regular server error when the voucher does not exist. but also i'm checking the referrer so the code should only activate for the static page anyway. (most links to basket/add are coming from the lms, and the payment mfe interacts with ecommerce through the api, i don't think it sends anything to the basket/add view)

2020-04-30 14:51 UTC, emma-green commented on ecommerce/extensions/basket/views.py
> +                # applying an invalid coupon from the static page was throwing an uncaught exception
Regardless of where it's coming from, if an invalid coupon is sent, we probably want the payment mfe to display with the error message that the coupon was invalid. Therefore, rather than just doing this on a one-off basis for our test (and needing to think about removing it), how about writing it so that it works for all flows? Basically, this would mean letting it run through the rest of the flow, and at the end adding the error param.

2020-04-30 14:55 UTC, MatthewPiatetsky commented on ecommerce/extensions/basket/views.py
> +                # applying an invalid coupon from the static page was throwing an uncaught exception
the payment mfe already displays an error message when an invalid coupon is sent, i don't think this code affects it

2020-04-30 15:04 UTC, emma-green commented on ecommerce/extensions/basket/views.py
> +                # applying an invalid coupon from the static page was throwing an uncaught exception
how does that work different from this?

2020-04-30 15:49 UTC, MatthewPiatetsky commented on ecommerce/extensions/basket/views.py
> +                # applying an invalid coupon from the static page was throwing an uncaught exception
it gets errors as a message added to the response of an ajax request, it doesn't actually reload the page so a redirect wouldn't work there, but it shouldn't be using this code i think

2020-05-05 20:17 UTC, emma-green requested changes
A couple of small things.

2020-05-05 20:17 UTC, emma-green commented on ecommerce/extensions/basket/views.py
> +    def _redirect_response_to_basket_or_payment(self, request, skus, invalid_code):
this is picky, but I would make this a kwarg instead of an arg, as most of the time, it will be none.

2020-05-05 20:17 UTC, emma-green commented on ecommerce/extensions/basket/views.py
> +                code = request.GET.get('code', None)
why not set this directly to invalid_code?

2020-05-08 15:43 UTC, emma-green approved these changes

2020-05-11 14:29 UTC, merged