update url but not update url root
openedx-unsupported/ecommerce pull request #2968
Opened 2020-05-27 21:25 UTC by kellmarie

2020-05-29 15:34 UTC, bbaker6225 commented on ecommerce/settings/production.py
> +ENTERPRISE_CATALOG_SERVICE_URL = 'http://enterprise.catalog.app:18160'
I think you'll want to use values from remote config like https://github.com/edx/edx-internal/blob/a4e3c355dbe1bcf2bc3f2fb1a561048727fae803/edx-remote-config/prod/ecommerce.yml#L72

2020-05-29 15:45 UTC, iloveagent57 reviewed
Looking pretty good so far, couple of suggestions.

2020-05-29 15:45 UTC, iloveagent57 commented on ecommerce/extensions/api/serializers.py
> +        return settings.ENTERPRISE_CATALOG_API_URL + 'enterprise-catalogs/'
Minor suggestion: you could use `urljoin()` here, too.

2020-05-29 15:45 UTC, iloveagent57 commented on ecommerce/settings/production.py
> +ENTERPRISE_CATALOG_SERVICE_URL = 'http://enterprise.catalog.app:18160'
More background on this: https://openedx.atlassian.net/wiki/spaces/SRE/pages/987202032/How-To+Use+Remote+Config

2020-05-29 16:09 UTC, kellmarie commented on ecommerce/settings/production.py
> +ENTERPRISE_CATALOG_SERVICE_URL = 'http://enterprise.catalog.app:18160'
Why is it that the url in the remote config for production is: `https://enterprise-catalog.edx.org`
while the one in the [API client](https://github.com/edx/edx-enterprise/blob/master/enterprise/api_client/enterprise_catalog.py#L28) for production is `http://enterprise.catalog.app:18160?`

2020-05-29 16:11 UTC, kellmarie commented on ecommerce/settings/production.py
> +ENTERPRISE_CATALOG_SERVICE_URL = 'http://enterprise.catalog.app:18160'
Should I also be updating the link that's in my edx-enterprise PR?
https://github.com/edx/edx-enterprise/pull/776

2020-05-29 18:39 UTC, chavesj commented on ecommerce/extensions/api/serializers.py
> +    def get_enterprise_catalog_url(self, obj):
quality check is failing here - removing the 'obj' argument should fix it

2020-05-29 18:39 UTC, chavesj commented on ecommerce/extensions/api/serializers.py
> +        return settings.ENTERPRISE_CATALOG_API_URL + 'enterprise-catalogs/'
+1

2020-05-29 18:39 UTC, chavesj commented on ecommerce/settings/production.py
> +ENTERPRISE_CATALOG_SERVICE_URL = 'http://enterprise.catalog.app:18160'
> Why is it that the url in the remote config for production is: `https://enterprise-catalog.edx.org`
> while the one in the [API client](https://github.com/edx/edx-enterprise/blob/master/enterprise/api_client/enterprise_catalog.py#L28) for production is `http://enterprise.catalog.app:18160?`

If you [search](https://github.com/edx/edx-internal/search?q=ENTERPRISE_CATALOG_INTERNAL_ROOT_URL&unscoped_q=ENTERPRISE_CATALOG_INTERNAL_ROOT_URL) in edx-internal for ENTERPRISE_CATALOG_INTERNAL_ROOT_URL you'll find the values that actually get used in prod/stage. The URL you see when testing edx-enterprise locally is obtained from the edx-platform settings (edx-enterprise is installed into edx-platform). If you [search](https://github.com/edx/edx-platform/search?q=ENTERPRISE_CATALOG_INTERNAL_ROOT_URL&unscoped_q=ENTERPRISE_CATALOG_INTERNAL_ROOT_URL) for the variable in edx-platform you'll find the URL that gets used for devstack in lms/envs/common.py and the value from remote-config gets brought into the settings in lms/envs/production.py.

2020-05-29 19:03 UTC, kellmarie commented on ecommerce/extensions/api/serializers.py
> +    def get_enterprise_catalog_url(self, obj):
But then I get an internal server error and the page fails to load. Maybe instead of making this get_enterprise_catalog_url function I just directly set `enterprise_catalog_url` to `settings.ENTERPRISE_CATALOG_API_URL + 'enterprise-catalogs/'` instead of calling the serializer function.

2020-05-29 19:06 UTC, kellmarie commented on ecommerce/extensions/api/serializers.py
> +    def get_enterprise_catalog_url(self, obj):
oh nevermind, directly setting it also causes an internal server error

2020-05-29 19:06 UTC, bbaker6225 commented on ecommerce/extensions/api/serializers.py
> +    def get_enterprise_catalog_url(self, obj):
You're doing it right in general with a serializer method field. What's the stack trace on the 500?

2020-05-29 19:08 UTC, bbaker6225 commented on ecommerce/static/js/models/enterprise_coupon_model.js
> +                enterprise_catalog_url: '',
We might want this to default to a similar `/api/v1/enterprise-catalogs/` url, but I'm not sure about that

2020-05-29 19:31 UTC, kellmarie commented on ecommerce/extensions/api/serializers.py
> +    def get_enterprise_catalog_url(self, obj):
```
TypeError at /api/v2/enterprise/coupons/5/
get_enterprise_catalog_url() takes 1 positional argument but 2 were given

Request Method: GET
Request URL: http://localhost:18130/api/v2/enterprise/coupons/5/
Django Version: 2.2.12
Python Executable: /edx/app/ecommerce/venvs/ecommerce/bin/python
Python Version: 3.5.2
Python Path: ['/edx/app/ecommerce/ecommerce', '/edx/app/ecommerce/venvs/ecommerce/lib/python35.zip', '/edx/app/ecommerce/venvs/ecommerce/lib/python3.5', '/edx/app/ecommerce/venvs/ecommerce/lib/python3.5/plat-x86_64-linux-gnu', '/edx/app/ecommerce/venvs/ecommerce/lib/python3.5/lib-dynload', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/edx/app/ecommerce/venvs/ecommerce/lib/python3.5/site-packages', '/edx/app/ecommerce/ecommerce/ecommerce', '/edx/app/edx_ansible/edx_ansible/docker/plays', '/edx/app/ecommerce/ecommerce']
Server time: Fri, 29 May 2020 19:30:17 +0000
```

2020-05-29 19:36 UTC, bbaker6225 commented on ecommerce/extensions/api/serializers.py
> +    def get_enterprise_catalog_url(self, obj):
Sorry, the stack trace without `obj` as a parameter

2020-05-29 20:26 UTC, kellmarie commented on ecommerce/extensions/api/serializers.py
> +    def get_enterprise_catalog_url(self, obj):
This is the stack trace without obj as a parameter

2020-06-01 15:50 UTC, kellmarie commented on ecommerce/extensions/api/serializers.py
> +    def get_enterprise_catalog_url(self, obj):
I found a solution where I can use the obj to get the catalog uuid and build the url in the serializer instead of piecing it together in a js file which I also like more as a solution.

2020-06-01 16:35 UTC, kellmarie commented on ecommerce/static/js/models/enterprise_coupon_model.js
> +                enterprise_catalog_url: '',
I defaulted it to be empty string to implicitly show that the field gets populated via the backend similar to how the `code`, `contract_discount_value`, `price`, and `id` fields are all empty. I can still default it to be `/api/v1/enterprise-catalogs/` if you would prefer that or change it to be null to better communicate that it gets populated by python

2020-06-01 18:08 UTC, adamstankiewicz approved these changes

2020-06-01 18:25 UTC, adamstankiewicz commented on ecommerce/enterprise/management/commands/seed_enterprise_devstack_data.py
> +            "enterprise_catalog_content_metadata_url": ecommerce_api_url + '/enterprise/customer_catalogs/',
should this be `ecommerce_api_url` or the enterprise-catalog url?

2020-06-03 22:10 UTC, iloveagent57 requested changes
Just want to cover that one condition where the catalog_uuid is empty.

2020-06-03 22:10 UTC, iloveagent57 commented on ecommerce/enterprise/management/commands/seed_enterprise_devstack_data.py
> +        catalog_uuid = self.enterprise_catalog.get('uuid') if self.enterprise_catalog.get('uuid') else ''
Nit: `get()` takes a second parameter that indicates the default value to return in case the key you're getting doesn't exist, so you could do `self.enterprise_catalog.get('uuid', '')`.

2020-06-03 22:10 UTC, iloveagent57 commented on ecommerce/enterprise/management/commands/seed_enterprise_devstack_data.py
> +            "enterprise_catalog_content_metadata_url": catalog_url + '/get_content_metadata',
If `catalog_uuid` is the empty string, this will end up being something like `http://host/api/v1/catalog//get_content_metadata` (note the double slashes).  You probably want to do something like only include `enterprise_catalog_content_metadata_url` in this dictionary if `catalog_uuid` is truthy:
```python
request_obj = {...}
if catalog_uuid:
    request_obj['enterprise_catalog_content_metadata_url'] = urljoin(enterprise_catalog_api_url, catalog_uuid, 'get_content_metadata')
```

2020-06-03 22:10 UTC, iloveagent57 commented on ecommerce/enterprise/management/commands/seed_enterprise_devstack_data.py
> +            "contract_discount_type": Invoice.PERCENTAGE,
I'm curious why you needed to add this key/value pair.

2020-06-04 01:49 UTC, adamstankiewicz commented on ecommerce/enterprise/management/commands/seed_enterprise_devstack_data.py
> +        enterprise_catalog_api_url = self.site.enterprise_catalog_api_url + 'enterprise-catalogs'
nit: might be able to use `urljoin` here

2020-06-04 01:49 UTC, adamstankiewicz commented on ecommerce/extensions/api/serializers.py
> +        return urljoin(settings.ENTERPRISE_CATALOG_API_URL,
Rather than always returning the URL, potentially with a `//` (double slash) when `uuid` is false, we could probably return `None` if `uuid` is false.

2020-06-04 13:50 UTC, kellmarie commented on ecommerce/enterprise/management/commands/seed_enterprise_devstack_data.py
> +        catalog_uuid = self.enterprise_catalog.get('uuid') if self.enterprise_catalog.get('uuid') else ''
Awesome, I'll update it to use that

2020-06-04 13:51 UTC, kellmarie commented on ecommerce/enterprise/management/commands/seed_enterprise_devstack_data.py
> +            "contract_discount_type": Invoice.PERCENTAGE,
The script just kept failing without it

2020-06-04 16:05 UTC, iloveagent57 approved these changes
👍 looks good

2020-06-04 18:59 UTC, merged