ENT-2735 | Added the payment message on track selection for learners …
openedx-unsupported/ecommerce pull request #2981
Opened 2020-06-03 08:10 UTC by hasnain-naveed

…in subsidy offer.

2020-06-04 12:54 UTC, HammadAhmadWaqas requested changes
good work in refracting the get_course_info_from_catalog. just some suggestions.

2020-06-04 12:54 UTC, HammadAhmadWaqas commented on ecommerce/courses/utils.py
> +def _get_discovery_response(site, cache_key, resource, resource_id=None):
why we need to set `resource_id ` None as default ?

2020-06-04 12:54 UTC, HammadAhmadWaqas commented on ecommerce/courses/utils.py
> +    api = site.siteconfiguration.discovery_api_client
nit: can we move this line after `return course_cached_response.value` so we do not have to get api client if there is cache response.

2020-06-04 12:54 UTC, HammadAhmadWaqas commented on ecommerce/extensions/offer/views.py
> +            course_ids = ast.literal_eval(course_id) if course_id else []
We should use [getlist](https://docs.djangoproject.com/en/2.0/ref/request-response/#django.http.QueryDict.getlist) method to retrieve multiple params.

2020-06-04 12:54 UTC, HammadAhmadWaqas commented on ecommerce/extensions/offer/views.py
> +                    course_keys.append(course.get('title'))
what if we could not find course in discovery?
we should add test to confirm this scenario too.

2020-06-04 12:54 UTC, HammadAhmadWaqas commented on ecommerce/extensions/basket/tests/test_views.py
> +            params=six.moves.urllib.parse.urlencode({'course_id': [course.id]})
can we test it with multiple course_id's?

2020-06-04 12:54 UTC, HammadAhmadWaqas commented on ecommerce/courses/utils.py
>      else:
can we add add `elif` here to confirm resource is `course` instead of just assuming it would be a `course`?
and in else part we can raise an exception that resource is INVALID.
this will also increase readability here.

2020-06-04 12:54 UTC, HammadAhmadWaqas commented on ecommerce/courses/utils.py
> +    else:
I think we should confirm here the product is `seat` type by adding and `elif`. otherwise we could raise an expectation that product is not course_entitlement or seat.

2020-06-04 13:29 UTC, hasnain-naveed commented on ecommerce/courses/utils.py
> +def _get_discovery_response(site, cache_key, resource, resource_id=None):
in case of `get_course_catalogs` it can be None.

2020-06-04 13:32 UTC, hasnain-naveed commented on ecommerce/courses/utils.py
>      else:
in else condition, there can be `course` and `catalogs` as a resource. We needed if condition because we are further filtering out on partner shortcode in case of `course_run`

2020-06-04 13:35 UTC, hasnain-naveed commented on ecommerce/courses/utils.py
> +    else:
This is not added by me. But yeah you are right it can improve the quality of code and will not change the current functionality of this function.

2020-06-04 13:36 UTC, hasnain-naveed commented on ecommerce/extensions/offer/views.py
> +                    course_keys.append(course.get('title'))
then there should an exception. I will add the test case.

2020-06-04 13:40 UTC, hasnain-naveed commented on ecommerce/courses/utils.py
> +    else:
on the second thought, we should not. This function should raise KeyError if the product is not entitlement or seat. We should keep it that way.

2020-06-04 14:24 UTC, HammadAhmadWaqas commented on ecommerce/courses/utils.py
> +    else:
Yes, you are right. we are handling it with `KeyError` in all places where we are using it.

2020-06-04 14:26 UTC, HammadAhmadWaqas commented on ecommerce/courses/utils.py
>      else:
then we can initiate a `params` dict and add partner key if the resource is `course_run`

2020-06-05 07:28 UTC, saleem-latif approved these changes
Just a couple of comments, otherwise Looks Good 👍

2020-06-05 07:28 UTC, saleem-latif commented on ecommerce/coupons/tests/mixins.py
> +        # httpretty.register_uri(
nit: remove commented code.

2020-06-05 07:28 UTC, saleem-latif commented on ecommerce/coupons/tests/mixins.py
> +    def mock_course_detail_endpoint_error1(self, course_identifier, discovery_api_url, error):
Is there a way we can combine this function with `mock_course_detail_endpoint_error`. Maybe you can switch between the two error types via an argument.

2020-06-05 07:28 UTC, saleem-latif commented on ecommerce/courses/utils.py
> +    cache_key = u'courses_api_detail_{}{}'.format(course_resource_id, site.siteconfiguration.partner.short_code)
Is it possible to use `get_cache_key` function here? it would simplify the code a bit.
```
from ecommerce.core.utils import get_cache_key
```

2020-06-05 07:28 UTC, saleem-latif commented on ecommerce/courses/utils.py
> +    cache_key = u'courses_api_detail_{}{}'.format(course_run_key, site.siteconfiguration.partner.short_code)
Same as above, Is it possible to use `get_cache_key` function here? it would simplify the code a bit.

2020-06-05 07:34 UTC, hasnain-naveed commented on ecommerce/coupons/tests/mixins.py
> +    def mock_course_detail_endpoint_error1(self, course_identifier, discovery_api_url, error):
this will be removed.

2020-06-05 08:17 UTC, HammadAhmadWaqas commented on ecommerce/extensions/offer/views.py
> +        if course_ids:
no need to add this if statement. for loop going to handle it automatically.

2020-06-05 08:29 UTC, HammadAhmadWaqas submitted a review, later dismissed

2020-06-05 08:29 UTC, HammadAhmadWaqas commented on ecommerce/extensions/offer/views.py
> +                    course_keys.append(course.get('title'))
@hasnain-naveed I think user will see a broken page with connection error if we could not connect to discovery or could not find a course in discovery. should not we show a 404 page to the user as we are showing for course_run below?

2020-06-05 14:44 UTC, moconnell1453 approved these changes

2020-06-05 14:48 UTC, merged