ENT-2901: Multiple line basket for offer maximum discount
openedx-unsupported/ecommerce pull request #2990
Opened 2020-06-10 16:29 UTC by irfanuddinahmad

JIRA: https://openedx.atlassian.net/browse/ENT-2901

2020-06-11 07:06 UTC, HammadAhmadWaqas requested changes
Overall looks good. Is it possible to add some tests to support we changes?

2020-06-11 07:06 UTC, HammadAhmadWaqas commented on ecommerce/enterprise/conditions.py
> +    )
we do not need to confirm that what is type of product.
Simple query could be something like:
```
basket.all_lines().aggregate(total=Sum('stockrecord__price_excl_tax'))['total'] or 0
```

2020-06-11 09:42 UTC, muhammad-ammar commented
What about updating/adding a test to verify new changes?

2020-06-11 15:21 UTC, moconnell1453 approved these changes

2020-06-12 07:31 UTC, HammadAhmadWaqas approved these changes

2020-06-12 07:34 UTC, merged