ENT-2880, ENT 2881 | Updated CouponRedeemView and VoucherAddLogicMix…
openedx-unsupported/ecommerce pull request #2995
Opened 2020-06-17 10:38 UTC by HammadAhmadWaqas

…in to support multiple products to redeem using voucher including programs.

2020-06-19 12:54 UTC, hasnain-naveed commented on ecommerce/courses/utils.py
> +                    'Unable fetch course ids because products contains a course entitlement product but we failed to'
This logger message has some issues. Can we please simplify this?

2020-06-19 13:05 UTC, hasnain-naveed commented on ecommerce/coupons/views.py
> +                    {'error': _('Could not find course_ids for few of the products.')}
can we add some elaborative logging message with proper prefix?

2020-06-19 13:12 UTC, hasnain-naveed commented on ecommerce/coupons/views.py
> +            msg = _('You have already purchased these courses.')
Can we add the product title here as it was added previously?

2020-06-19 13:27 UTC, hasnain-naveed requested changes

2020-06-19 13:27 UTC, hasnain-naveed commented on ecommerce/coupons/views.py
> +            except (TypeError, AttributeError):
Curious why are we catching `AttributeError` exception here when you are catching this in child function `get_products_course_ids `?

2020-06-19 13:27 UTC, hasnain-naveed commented on ecommerce/coupons/views.py
> +            return render(request, template_name, {'error': _('These products do not exist.')})
This is a very ambiguous message for the end-user.

2020-06-22 07:44 UTC, HammadAhmadWaqas commented on ecommerce/coupons/views.py
> +            return render(request, template_name, {'error': _('These products do not exist.')})
The courses in which you are trying to enroll, not found.

2020-06-22 07:45 UTC, HammadAhmadWaqas commented on ecommerce/coupons/views.py
> +            logger.warning('[Code Redemption Failure] The voucher is not valid for these products. '
`[Code Redemption Failure] The voucher is not valid for these products. `

2020-06-22 07:54 UTC, HammadAhmadWaqas commented on ecommerce/coupons/views.py
> +                    {'error': _('Could not find course_ids for few of the products.')}
`There is some internal error. please contact your admin.`

2020-06-22 08:04 UTC, HammadAhmadWaqas commented on ecommerce/courses/utils.py
> +                    'Unable fetch course ids because products contains a course entitlement product but we failed to'
`Supported Entitlement Product could not be fetched from discovery catalog.`

2020-06-22 10:21 UTC, HammadAhmadWaqas commented on ecommerce/coupons/views.py
> +            except (TypeError, AttributeError):
becasue `get_products_course_ids` can raise `AttributeError` if the `product` in None

2020-06-22 10:45 UTC, HammadAhmadWaqas commented on ecommerce/coupons/views.py
> +            msg = _('You have already purchased these courses.')
there was a single product before. now there could be multiple.

2020-06-23 06:29 UTC, saleem-latif approved these changes
Few comments, other than that Looks Good :+1:

2020-06-23 06:29 UTC, saleem-latif commented on ecommerce/coupons/views.py
> +        """Iterate over all the course_id and check if received_consent_token in valid for any of the course."""
nit:
```Iterate over all the `course_id`s and check if `received_consent_token` is valid for any of the courses.```

2020-06-23 06:29 UTC, saleem-latif commented on ecommerce/coupons/views.py
> +            sku_to_course_id_map.append((sku, course_id))
Wouldn't it be better to use a dictionary here instead of a list of tuples?

2020-06-23 06:29 UTC, saleem-latif commented on ecommerce/courses/utils.py
> +                response = get_course_info_from_catalog(site, product)
Is there a workaround for making an API call inside the loop?

2020-06-23 07:57 UTC, HammadAhmadWaqas commented on ecommerce/courses/utils.py
> +                response = get_course_info_from_catalog(site, product)
for entitlement products, we have to get the course key from catalog. As it is a cached API, it should not make any trouble.

2020-06-26 12:20 UTC, hasnain-naveed commented
@HammadAhmadWaqas we need an extra pair of eyes for this PR as this will change the core functionality of coupons. We should tag someone from the Titan team. From my side, its good to go. But we should add a waffle flag to enable/disable this functionality.  👍

2020-06-26 12:29 UTC, hasnain-naveed approved these changes

2020-06-29 11:56 UTC, moconnell1453 approved these changes

2020-07-06 05:52 UTC, saleem-latif approved these changes

2021-12-17 09:49 UTC, closed without merging