[REV-1209] Add second SDN check with fuzzy name matching enabled and related testing logs
openedx-unsupported/ecommerce pull request #3020
Opened 2020-07-13 18:35 UTC by MatthewPiatetsky

This is to help determine what score could be a reasonable threshold for the fuzzy matching

2020-07-13 21:39 UTC, jhan217 commented on ecommerce/extensions/payment/utils.py
> +                            'Regular SDN check: match. Fuzzy SDN check: match. Fuzzy match top score: [%s]',
Would it be possible/worth logging what the match was so we can better understand the types of matching they're using? e.g. phonetic vs off-by-one-characters, etc.?

2020-07-13 21:40 UTC, jhan217 commented on ecommerce/extensions/payment/utils.py
> +        if waffle.flag_is_active(crum.get_current_request(), 'make_second_sdn_check'):  # pragma: no cover
Not super familiar with the API behavior here, but should this also check to see that we got a json response that has results (vs an empty/non-timeout error response)?

2020-07-13 21:43 UTC, jhan217 commented on ecommerce/extensions/payment/utils.py
> +import crum
What is `crum`?

2020-07-13 21:52 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +                            'Regular SDN check: match. Fuzzy SDN check: match. Fuzzy match top score: [%s]',
The input name is PII; although there are other logs in this area that do log it, I think we'd need to find a more appropriate place or logging method if we felt we needed to add new sensitive logs.

For now, we're just interested in the question "What fuzzy-score threshold(s) would give us reasonable matches compared to the regular lookup", but not (currently) trying to diagnose the matches themselves nor the algorithm.

2020-07-14 12:41 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/utils.py
> +                            'Regular SDN check: match. Fuzzy SDN check: match. Fuzzy match top score: [%s]',
this might not answer whether the match was reasonable since the names could be very different, but would help answer which threshold would give the closest new matches perhaps

2020-07-14 12:42 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/utils.py
> +import crum
its a library we use to get the current request

2020-07-14 12:43 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/utils.py
> +        if waffle.flag_is_active(crum.get_current_request(), 'make_second_sdn_check'):  # pragma: no cover
i think that should be covered by line 237 since if the response has results it will get that otherwise it will get []
[] is falsey so then the if first_check_results boolean will return false

2020-07-14 13:57 UTC, jhan217 commented on ecommerce/extensions/payment/utils.py
> +                            'Regular SDN check: match. Fuzzy SDN check: match. Fuzzy match top score: [%s]',
Ah ok, was just wondering if there was additional data we could collect at this time that might be useful for data analysis / decision making.

2020-07-14 14:02 UTC, jhan217 commented on ecommerce/extensions/payment/utils.py
> +        if waffle.flag_is_active(crum.get_current_request(), 'make_second_sdn_check'):  # pragma: no cover
Sounds good, I wasn't sure if there were any cases we knew of that needed to skip the fuzzy check entirely (e.g. non-timeout errors)

2020-07-14 14:04 UTC, jhan217 commented on ecommerce/extensions/payment/utils.py
> +                # Since this code is purely for testing purposes,
🎱 Might be worth info logging the error in case it's related to the new fuzzy flag

2020-07-14 14:05 UTC, jhan217 approved these changes
Looks fine for temporary code

2020-07-14 17:59 UTC, inventhouse requested changes

2020-07-14 17:59 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +                response = requests.get(
We _must not_ overwrite `response` here; this will cause the method to ultimately return the fuzzy results instead of the normal results

2020-07-14 17:59 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +                second_check_results = response.json().get("results", [])
We should probably log a warning if `fuzzy_response.status_code != 200` something like `'Fuzzy SDN check error: Status code [%d] with message: [%s]', response.status_code, response.content`

2020-07-14 18:14 UTC, jhan217 commented on ecommerce/extensions/payment/utils.py
> +                response = requests.get(
Good catch!

2020-07-14 19:12 UTC, inventhouse requested changes

2020-07-14 19:12 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +import crum
We should also tag all this code with REV-1209 for later cleanup

2020-07-14 19:12 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +        if waffle.flag_is_active(crum.get_current_request(), 'make_second_sdn_check'):  # pragma: no cover
Waffle isn't the right tool for this, but ok for this test; for longer-lived code, a flag in `settings` would be better, for future reference

2020-07-15 00:27 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +                response = requests.get(
The fact that a bug like this is even possible is downright terrifying.

We should move all of the code for the fuzzy test into its own method that gets called with the results of the main `search` in a way that absolutely cannot impact the result of the "real" check.

2020-07-15 20:19 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/utils.py
> +import crum
i'd rather rely on reverting a PR for clean up purposes.  
happy to create a ticket asking to revert this PR if you'd like (though occasionally i find those don't end up getting prioritized in the backlog)

i find sometimes leaving comments like this is misleading because if the code moves around or not all the code got tagged with a comment it leads to missing stuff, i believe this happened with a cleanup effort recently

2020-07-15 20:20 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/utils.py
> +                response = requests.get(
good catch thank you i also came across this in my testing

2020-07-15 20:45 UTC, inventhouse requested changes

2020-07-15 20:45 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +                params = urlencode(params_dict)
Where are the name / city / etc. added to the params dict?  It looks like this will make a mostly empty (but fuzzy!) query.

2020-07-15 20:45 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +import crum
I agree reverting a PR is best, but I would prefer to also tag temporary code to aid cleanup in case the PR doesn't revert cleanly; code getting moved is exactly when the tagging helps most, tag all the things so they don't get missed.

2020-07-15 20:50 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +        if waffle.flag_is_active(crum.get_current_request(), 'make_second_sdn_check'):
Maybe this should also be inside the `try` _just_ in case

2020-07-15 20:56 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +                params = urlencode(params_dict)
Actually, I don't see where params_dict is defined either

2020-07-15 21:12 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/utils.py
> +import crum
except when code is moved it doesn't always move the comment with it, but I included the PR in the comment which might help

2020-07-15 21:14 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/utils.py
> +                params = urlencode(params_dict)
it was in the main function, i didn't add the parameter when creating the new function

2020-07-16 14:12 UTC, inventhouse requested changes

2020-07-16 14:12 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +import crum
Putting the comment on the same line can help with that, but it's something to be be conscientious of when moving code or reviewing PRs that move code; this should be fine though.

2020-07-16 14:12 UTC, inventhouse commented on ecommerce/extensions/payment/utils.py
> +                params = urlencode(params_dict)
This will leak the modified dict back out to the "real" context; it should be copied before adding more params or name/city/country should be passed in mirroring the `search` method API.

2020-07-16 18:51 UTC, inventhouse approved these changes
👍

2020-07-17 13:51 UTC, merged