[WIP] {REV-1249] Dkaplan rev 1249 cybersource refund update
openedx-unsupported/ecommerce pull request #3069
Opened 2020-07-29 21:51 UTC by dianekaplan

2020-07-30 17:42 UTC, julianajlk requested changes

2020-07-30 17:42 UTC, julianajlk commented on ecommerce/extensions/payment/tests/mixins.py
> +                <c:paymentNetworkTransactionID>558196000003814</c:paymentNetworkTransactionID>
I believe you should not have the ID hard coded but have it like <c:paymentNetworkTransactionID>{transaction_id}</c:paymentNetworkTransactionID>, since it will be different every time

2020-07-30 17:42 UTC, julianajlk commented on ecommerce/extensions/payment/tests/mixins.py
> +                <c:paymentNetworkTransactionID>558196000003814</c:paymentNetworkTransactionID>
I would say the same for the other fiedls

2020-07-30 17:55 UTC, dianekaplan commented on ecommerce/extensions/payment/tests/mixins.py
> +                <c:paymentNetworkTransactionID>558196000003814</c:paymentNetworkTransactionID>
That sounds good- we won't have logic to use those fields, but the more realistic the better! In the log info you sent me for your request and reply data, the values for those new fields didn't match any values that we sent in our request (generated on cybersource's side) so I don't think there are any variables in scope for them already. Is the suggestion that we add three more variables as arguments we can pass in the signature, on this line at the link below? 
https://github.com/edx/ecommerce/blob/e899c78325ac492d0a2b1ea0aab4d5e230262b8f/ecommerce/extensions/payment/tests/mixins.py#L211

2020-07-31 09:45 UTC, dianekaplan commented on ecommerce/extensions/payment/tests/mixins.py
> +                <c:paymentNetworkTransactionID>558196000003814</c:paymentNetworkTransactionID>
Update: Juliana and I chatted and she agrees that hardcoding these values won't be problematic since this is the mocked response (not the request)

2020-07-31 13:24 UTC, julianajlk approved these changes

2020-08-04 13:02 UTC, merged