[WIP] [REV-1266] Add ADR for SDN fallback
openedx-unsupported/ecommerce pull request #3076
Opened 2020-08-04 11:01 UTC by MatthewPiatetsky

2020-08-04 13:44 UTC, iloveagent57 approved these changes
The content here is great, very clear.  Two very minor suggestions:
1. I usually add a rough date under "Status" (for example, "August 2020") to indicate when the decision was made and accepted.
2. There are a few RST syntax changes you'll want to make to get the numbered list to render correctly, you can preview the rich diff at https://github.com/edx/ecommerce/pull/3076/files?short_path=90be0df#diff-90be0dff5e3e9a1a10a36012545767a6  
I use this online tool to help me preview RST: http://rst.ninjs.org/

2020-08-04 15:00 UTC, iloveagent57 commented
Beautiful!

2020-08-04 15:56 UTC, jhan217 commented on docs/decisions/0007-sdn-fallback.rst
> +The API has periods of downtime and although that downtime is often within the 99.5% uptime SLA of the service, edX would prefer to take extra precautions when downtime occurs.
Worth expanding on how that downtime impacts edX? e.g. if the service is down, we stop processing transactions/payments and tell the users to come back later? Or do we queue the transaction and wait to process it later?

2020-08-04 16:16 UTC, jhan217 commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data once every day, as this is standard for most of our similar jobs and there wasn't a different explicit standard of data freshne
Does this take into account the above mentioned risk of the CSV having periods of downtime?

2020-08-04 16:16 UTC, jhan217 commented on docs/decisions/0007-sdn-fallback.rst
> +If we are unable to check a transaction against the list we currently allow the transaction to succeed. The hope is that with the fallback in place few transactions will fall through without being ch
Minor: `...fallback in place, fewer transactions...`

2020-08-04 16:16 UTC, jhan217 commented on docs/decisions/0007-sdn-fallback.rst
> +When the `ConsolidatedScreeningListAPI` goes down, we will have a fallback option available to call.
Do we have an expectation of what the benefits of this decision will be? e.g. 99.5% -> 99.999% availability?

2020-08-04 16:42 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +The API has periods of downtime and although that downtime is often within the 99.5% uptime SLA of the service, edX would prefer to take extra precautions when downtime occurs.
i believe we currently allow the transactions per the allow transactions paragraph, so the cost would be potential legal liability (though the uptime isn't really relevant to that)

2020-08-04 16:44 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data once every day, as this is standard for most of our similar jobs and there wasn't a different explicit standard of data freshne
i believe the first paragraph of the decisions describes that we'd have a recent copy of the data in the database if this happened

2020-08-04 16:45 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +When the `ConsolidatedScreeningListAPI` goes down, we will have a fallback option available to call.
i don't think we do

2020-08-04 17:13 UTC, dianekaplan reviewed
Along with these broad-strokes descriptions of the planned fallback behavior, should we also have a bullet for eventing & alerting?  (That we'll build whatever eventing and alerting we need as usual, such as when the Jenkins job has failed to get a fresh list, etc). Not sure if that's beyond the usual scope for a document like this

2020-08-04 17:19 UTC, jhan217 commented on docs/decisions/0007-sdn-fallback.rst
> +The API has periods of downtime and although that downtime is often within the 99.5% uptime SLA of the service, edX would prefer to take extra precautions when downtime occurs.
Might be worth providing the business reasoning on why we are doing this for future readers (to answer the "why does edX care about this?" question for them)

2020-08-04 17:23 UTC, jhan217 commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data once every day, as this is standard for most of our similar jobs and there wasn't a different explicit standard of data freshne
Ok, was just curious about staleness detection and/or a tiny potential edge of scheduling the job to run during their CSV downtime/maintenance window. Probably more of an implementation detail than an architectural decision though.

2020-08-04 17:24 UTC, julianajlk reviewed
This is great, do you think we should have what are the specific requirements for this or is this the context? Should implementation cost be included - I'm sure this was analyzed in the discovery phase and would be good to know this was also a cost effective decision in the ADR.

2020-08-04 17:27 UTC, jhan217 commented on docs/decisions/0007-sdn-fallback.rst
> +When the `ConsolidatedScreeningListAPI` goes down, we will have a fallback option available to call.
It would be nice to address "what benefit to the business do we expect to get out of implementing this change?" for future readers.

2020-08-04 17:32 UTC, jhan217 commented
> This is great, do you think we should have what are the specific requirements for this or is this the context? Should implementation cost be included - I'm sure this was analyzed in the discovery phase and would be good to know this was also a cost effective decision in the ADR.

I've definitely read through code and wondered "why are they doing this?" and "why didn't they do it using <some other design>?" so it would be nice if the ADR also addressed that context as well

2020-08-04 17:41 UTC, inventhouse requested changes
A couple edits, but overall great, thanks!

2020-08-04 17:41 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data once every day, as this is standard for most of our similar jobs and there wasn't a different explicit standard of data freshne
I would say "at least once a day"

The CSV is regenerated hourly, and there is little cost to downloading it that often as long as we don't re-process it if there are no changes, so that's the current plan.

2020-08-04 17:41 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +We considered trying to implement fuzzy matching in the fallback because there is an option to use it in the API. The decision was not to do this because it would add complexity and increase the risk
I would just say that we don't currently use fuzzy matching in the API and want the fallback to work similarly, so that is out-of-scope for this ADR.

Fuzzy matching is still being evaluated, I wouldn't say that there has been a firm decision on that.

2020-08-04 17:41 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +When the `ConsolidatedScreeningListAPI` goes down, we will have a fallback option available to call.
We could say that the fallback is expected to work as long as ecommerce is working

2020-08-04 17:41 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +When activating the fallback one consideration was whether we would retrieve and process the CSV during the lifecycle of the request or do so ahead of time and store the data. The decision was to pro
I would avoid implementation details like "Jenkins"; something like "process the CSV periodically and store the data.", we are investigating other options as we've had issues with using Jenkins for this sort of thing.

2020-08-04 17:46 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data once every day, as this is standard for most of our similar jobs and there wasn't a different explicit standard of data freshne
ah ok i'll update it to say hourly

2020-08-04 17:48 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +We considered trying to implement fuzzy matching in the fallback because there is an option to use it in the API. The decision was not to do this because it would add complexity and increase the risk
Do you have additional context around that that you could provide?  
I thought Seth told me we wouldn't do it, but I guess I misinterpreted something

2020-08-04 17:51 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +When activating the fallback one consideration was whether we would retrieve and process the CSV during the lifecycle of the request or do so ahead of time and store the data. The decision was to pro
Is there additional context around this that you could provide?  
Emma previously told me we'd have a jenkins job for this, fine that wasn't actually decided, but if this is the second thing where my information is outdated, it seems like I need updated context or maybe should mark this task as blocked until things are more nailed down?

2020-08-04 17:57 UTC, MatthewPiatetsky commented
@dianekaplan i think this doc is for providing context around decisions, if we'll do monitoring as necessary that just sounds like business as usual so no extra information necessary i think

2020-08-04 18:09 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +When the `ConsolidatedScreeningListAPI` goes down, we will have a fallback option available to call.
added some info to the context section. info around expected uptime doesn't really seem relevant to context around decisions, but I did add a section clarifying that the code would live in ecommerce, so the dependency on ecommerce should then be implicit.  
If we're going to be using another service of some sort for data updates then "uptime" of the fallback would depend on that as well.

2020-08-04 18:12 UTC, MatthewPiatetsky commented
@julianajlk i don't think an explicit list of requirements is available, but the implicit requirements is what the decisions section touches on
as for cost estimates, I'm not aware of one being done, though regardless from what emma told me it doesn't seem like it would have been relevant to the decision

2020-08-04 20:13 UTC, emma-green commented on docs/decisions/0007-sdn-fallback.rst
> +When activating the fallback one consideration was whether we would retrieve and process the CSV during the lifecycle of the request or do so ahead of time and store the data. The decision was to pro
Hi! I think it's fine to leave it nebulous. I apologize if I said something that was confusing. We will have some sort of asynchronous job do this. Generally, we've done quite a few of these sort of jobs through Jenkins, but we don't need to limit ourselves to Jenkins. I'm happy to entertain a discussion of doing this in a place other than Jenkins.

2020-08-04 20:14 UTC, emma-green commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data hourly because the CSV is updated hourly.
Hmm....We should double-check this with Seth and legal.

2020-08-04 20:15 UTC, emma-green commented on docs/decisions/0007-sdn-fallback.rst
> +For the algorithm in the fallback to match name/address pairs to entries in the list we chose to attempt to replicate the algorithm used by the API as much as possible. Although we don't know what th
Can you describe what properties we will attempt to implement?

2020-08-04 20:18 UTC, emma-green commented on docs/decisions/0007-sdn-fallback.rst
> +When the `ConsolidatedScreeningListAPI` goes down, we will have a fallback option available to call.
The benefit to the business: right now, when the api is down, we are sending people though without an sdn check, which opens us up to potential issues. We don't want to prohibit them from checking out, as we would incur a cost of lost revenue, and frustration on the part of users (as it tends to be down for minutes or hours at a time). This allows us to continue to run an sdn check even when the api is down.

2020-08-04 20:27 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +When activating the fallback one consideration was whether we would retrieve and process the CSV during the lifecycle of the request or do so ahead of time and store the data. The decision was to pro
ok will remove the word jenkins and resolve this conversation (though if I can get caught up on the current context that i'm missing that would be great)

2020-08-04 20:28 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data hourly because the CSV is updated hourly.
double check which part, that we will run it hourly? that's what Ben was saying in the previous thread, but I can reach out to Seth and legal

2020-08-04 20:33 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +For the algorithm in the fallback to match name/address pairs to entries in the list we chose to attempt to replicate the algorithm used by the API as much as possible. Although we don't know what th
from the relevant primer, these were the properties, and there is much more in depth info as well.
1. Order of words within a name doesn’t matter
2. Number of times that a given word within a name appears doesn’t matter
3. Punctuation between words or at the beginning/end of a given word doesn’t matter
4. If a subset of words within a name match, it still counts as a match
5. Capitalization doesn’t matter
6. Primary names and alternate names are essentially one set of words
7. Unicode characters are not translated or transliterated
8. Some similar properties are true for addresses

I could include some of this information, but since ADRs are meant to be concise and directly to the point of the relevant context, I don't think that this information is necessary, as these would be implementation details that would be described in depth in the fallback implementation itself. This section is only really trying to say that we want the fallback to behave in a similar way to the API

2020-08-04 20:55 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +We considered trying to implement fuzzy matching in the fallback because there is an option to use it in the API. The decision was not to do this because it would add complexity and increase the risk
We aren't planning to do it in the fallback because we aren't doing it in the API right now; whether it's a good idea and what thresholds make sense is out-of-scope for the fallback.

2020-08-04 20:57 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data hourly because the CSV is updated hourly.
In the previous thread, I said to say "at least once a day", or you could just say "periodically"; exactly how often isn't really important.

2020-08-04 20:58 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data hourly because the CSV is updated hourly.
I could delete the section regarding frequency of data updates but is there any information we'll have in the future to decide the frequency that we don't already have now? if not it seems like we should be able to decide and add the context for the decision here?

2020-08-05 12:50 UTC, emma-green commented on docs/decisions/0007-sdn-fallback.rst
> +For the algorithm in the fallback to match name/address pairs to entries in the list we chose to attempt to replicate the algorithm used by the API as much as possible. Although we don't know what th
The audience of this adr is not going to have any context about how the api behaves, and it may in fact change the way it behaves in the future, making this out of date.

2020-08-05 13:40 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +For the algorithm in the fallback to match name/address pairs to entries in the list we chose to attempt to replicate the algorithm used by the API as much as possible. Although we don't know what th
I agree that these properties may become out of date, but the fact that we wanted to match the API is the key part of the decision context, since if the API does change, readers will know that the fallback would likely need be changed as well.
we wouldn't want to confuse people into thinking the fallback specifically needs to have these properties if the API does change
as for the ADR becoming outdated I believe if the API does change we'd certainly want a new ADR with the supersededthough in that case we'd need a new ADR and perhaps change this ADR status to superseded according to the ADR OEP

2020-08-05 14:48 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +We considered trying to implement fuzzy matching in the fallback because there is an option to use it in the API. The decision was not to do this because it would add complexity and increase the risk
agree that the reasons don't matter beyond that we decided to not do it in the API, but we should clarify in standup whether Seth did decide to not use it or not

2020-08-05 18:13 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +We considered trying to implement fuzzy matching in the fallback because there is an option to use it in the API. The decision was not to do this because it would add complexity and increase the risk
The reason we are not doing fuzzy matching in the fallback is parity with our call to the API, _not_ complexity or or false positives etc.

2020-08-05 18:14 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +When activating the fallback one consideration was whether we would retrieve and process the CSV during the lifecycle of the request or do so ahead of time and store the data. The decision was to pro
This still says jenkins

2020-08-05 18:17 UTC, inventhouse commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data hourly because the CSV is updated hourly.
I don't think specifying the frequency is useful, and we might reconsider or adjust that at some point; if the upstream regeneration frequency changes, for example

2020-08-05 19:03 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +We considered trying to implement fuzzy matching in the fallback because there is an option to use it in the API. The decision was not to do this because it would add complexity and increase the risk
agreed, that's what I said in the comment above yours, but was waiting to hear from seth regarding the fuzzy matching
he confirmed it was still being evaluated so i deleted this section

2020-08-05 19:04 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +When activating the fallback one consideration was whether we would retrieve and process the CSV during the lifecycle of the request or do so ahead of time and store the data. The decision was to pro
yup was waiting on response to all threads before addressing

2020-08-05 19:07 UTC, MatthewPiatetsky commented on docs/decisions/0007-sdn-fallback.rst
> +We are planning to run the jenkins job to retrieve and process the data hourly because the CSV is updated hourly.
i don't think whether we might reconsider it matters since that could be true for any of the points, but removing if we don't think it is useful

2020-08-11 17:04 UTC, emma-green approved these changes

2020-08-11 19:07 UTC, inventhouse approved these changes

2020-08-11 19:56 UTC, merged