Add SDNInviduals model for looking up an individual when official SDN check is down
openedx-unsupported/ecommerce pull request #3102
Opened 2020-08-18 18:48 UTC by julianajlk

[REV-1280](https://openedx.atlassian.net/browse/REV-1280).
WIP

2020-08-20 19:47 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        Model used to record information from the list received from SDNFallbackMetadata.
Should this be list downloaded from the state department or so? Might be worth specifically mentioning that this is meant to take in one row from that file + processing it (as opposed to the entire file + processing it)

2020-08-20 19:57 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +    csv_import_id = models.ForeignKey('payment.SDNFallbackMetadata', null=True, blank=False, on_delete=models.SET_NULL, verbose_name='CSV import ID')
Is there a reason we'd want to use the verbose_name? If we do, might be worth spelling out "SDN" -- seems silly to use acronyms for a more detailed name..

2020-08-20 19:59 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        choices=COUNTRY_CHOICES,
What do we set for 'Country' when the csv doesn't have anything in that cell?

2020-08-20 19:59 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        max_length=255,
Are we storing the 2-character country code or the full name of the country code? If the former, can we set the max_length to 2?

2020-08-20 20:00 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +    csv_import_id = models.ForeignKey('payment.SDNFallbackMetadata', null=True, blank=False, on_delete=models.SET_NULL, verbose_name='CSV import ID')
Just capitalization for the acronym (SDN vs Sdn), we can go without the verbose name as well.

2020-08-24 13:46 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +        max_length=255,
Storing the 2-character country code, but some individuals may have more than one country in their address

2020-08-24 15:53 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('source', models.CharField(max_length=255)),
why do we need this field if we'll be filtering it to a specific set of values as in our usage of the API?

2020-08-24 15:53 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('sdn_type', models.CharField(max_length=255)),
why do we need this field if we'll be filtering it to a specific set of values as in our usage of the API?

2020-08-24 15:54 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
is there value in having an id other than the sdn_id if we are choosing to include the sdn_id field?

2020-08-25 12:43 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +        max_length=255,
Denormalizing by country so will keep characters to 2

2020-08-25 13:19 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +        choices=COUNTRY_CHOICES,
Updated to set to NULL if empty

2020-08-25 13:35 UTC, jhan217 commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
IIRC the SDN_ID field was used to link the denormalized to the original row

2020-08-25 13:36 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +class SDNFallbackData(models.Model):
Not sure if this is within scope or not, but should there be an `import` method of some sort that converts a string into an SDNFallbackData object?

2020-08-25 13:38 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        source (CharField): Origin of where the data comes from, since the CSV consolidates export screening lists of the Departments of Commerce, State and the Treasury.
Should this be an Enum?

2020-08-25 13:38 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        sdn_type (CharField): For a person with source Specially Designated Nationals (SDN) - Treasury Department, the type is 'Individual'. Other options include 'Entity' and 'Vessel'. Other lists d
Also worth making this an enum?

2020-08-25 13:41 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        addresses (TextField): A space separated list of all lowercased addresses combined into one string. There are records that don't have an address, but because city is a required field in the P
Minor: Not the biggest fan of using "we" in comments because the reader may not have context to know who "we" is. Specific nouns might be more useful e.g. "the script" or "the SDNFallbackData model" or "<the method name>"

2020-08-25 13:46 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +    def test_filter_records(self):
Should we also add test cases for null addresses, null countries, and null types? Are we not filtering on name at all?

2020-08-25 13:47 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +        "Verify all fields are correctly populated witht the minimum requirements"
Technically these are not the minimum requirements because the nullable values are populated.

2020-08-25 13:48 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +        self.sdn_metadata = SDNFallbackMetadata.objects.create(
If you rebase off https://github.com/edx/ecommerce/pull/3112 you should be able to use the factory for this.

2020-08-25 13:48 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        countries (CharField): Countries are extracted from the addresses field and in some instances the ID field in their 2 letter abbreviation. There are records that don't have an address, but be
Should this be singular 'country' because this each field can only have one country, as judged by the character length on this row?

2020-08-25 13:52 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, list_id, country):
What is list_id?

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/tests/test_models.py
> +    def test_names_and_alt_names(self):
I would remove the empty tests, if you want you could start make TODO comments with things to test, but just deleting is fine too since these are out of scope for this ticket

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('csv_import_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.SDNFallbackMetadata')),
we should probably rename this to csv_import since we've learned it represents the object and not the integer id

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +class SDNFallbackData(models.Model):
out of scope for this ticket I believe

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
i was asking about replacing this id with the sdn_id, not vice versa (though we're no longer denormalizing the fields after a slack conversation yesterday)

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +        countries (CharField): Countries are extracted from the addresses field and in some instances the ID field in their 2 letter abbreviation. There are records that don't have an address, but be
we should not this this will also be a space separated list

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +        source (CharField): Origin of where the data comes from, since the CSV consolidates export screening lists of the Departments of Commerce, State and the Treasury.
why would we want to break things if they add a new source that we aren't using?

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +        sdn_type (CharField): For a person with source Specially Designated Nationals (SDN) - Treasury Department, the type is 'Individual'. Other options include 'Entity' and 'Vessel'. Other lists d
why would we want to break things if they add a new type that we aren't using?

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +        countries (CharField): Countries are extracted from the addresses field and in some instances the ID field in their 2 letter abbreviation. There are records that don't have an address, but be
the character length is 255 i think, each field can have multiple countries

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, list_id, country):
it filters by a hardcoded type. list_id could probably be updated to be called list (since it is the object and not the id)

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/tests/test_models.py
> +        "Verify all fields are correctly populated witht the minimum requirements"
I think the minimum requirements comment can just be removed

2020-08-25 14:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/tests/test_models.py
> +    def test_filter_records(self):
matching on name is out of scope for this ticket

2020-08-25 14:26 UTC, julianajlk commented on ecommerce/extensions/payment/tests/test_models.py
> +    def test_names_and_alt_names(self):
It's not included in the most recent commit, resolving since this is outdated.

2020-08-25 14:32 UTC, jhan217 commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('csv_import_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.SDNFallbackMetadata')),
Or `sdn_fallback_metadata_id`? I've seen that convention work really well for foreign key id names, to use the FK's table name + "_id"

2020-08-25 14:34 UTC, jhan217 commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
Ah ok, we're not even denormalizing countries anymore?

2020-08-25 14:36 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        source (CharField): Origin of where the data comes from, since the CSV consolidates export screening lists of the Departments of Commerce, State and the Treasury.
It sounds like a short, finite list of known objects and can be useful to drive behavior changes (e.g. if different sources require different import methods).

2020-08-25 14:37 UTC, julianajlk commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('csv_import_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.SDNFallbackMetadata')),
@MatthewPiatetsky Will do, but when the model is created with "ForeignKey" it will append "_id" suffix to the field automatically. I can add a `db_column` attribute so I can name the field

2020-08-25 14:37 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        sdn_type (CharField): For a person with source Specially Designated Nationals (SDN) - Treasury Department, the type is 'Individual'. Other options include 'Entity' and 'Vessel'. Other lists d
How do we want to handle unexpected new types?

2020-08-25 14:38 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        countries (CharField): Countries are extracted from the addresses field and in some instances the ID field in their 2 letter abbreviation. There are records that don't have an address, but be
Ah ok, didn't realize we decided to not denormalize the country field.

2020-08-25 14:59 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('csv_import_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.SDNFallbackMetadata')),
no i was suggestion we name it csv_import (or sdn_fallback_metadata)
letting it append the id is fine, that's how it represents it on the db side, but on the django side this is the object and not the id, not sure if that makes sense

2020-08-25 14:59 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
no

2020-08-25 15:01 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +        source (CharField): Origin of where the data comes from, since the CSV consolidates export screening lists of the Departments of Commerce, State and the Treasury.
adding new sources is a common use case though, i suppose if it only failed the individual rows that could be fine, but i wouldn't view this as an unchanging list

2020-08-25 15:02 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +        sdn_type (CharField): For a person with source Specially Designated Nationals (SDN) - Treasury Department, the type is 'Individual'. Other options include 'Entity' and 'Vessel'. Other lists d
well, for both this and the regular api we only use individual and throw away the rest, this makes more sense to me than source to be an enum if we wanted to do that (although for many rows there won't be a value at all, not sure if having null makes sense for an enum)

2020-08-25 15:24 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +        countries (CharField): Countries are extracted from the addresses field and in some instances the ID field in their 2 letter abbreviation. There are records that don't have an address, but be
Will update the character length back to 255, we will no longer denormalize the country field.

2020-08-25 17:07 UTC, julianajlk commented on ecommerce/extensions/payment/migrations/0029_sdnfallbackdata.py
> +                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
Since we're no longer denormalizing, makes sense to have just one ID and not have the autogenerated auto-incremented ID. I'll add the primary_key attributes to the sdn_id

2020-08-25 20:01 UTC, MatthewPiatetsky approved these changes

2020-08-25 20:03 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +        sdn_type (CharField): For a person with source Specially Designated Nationals (SDN) - Treasury Department, the type is 'Individual'. Other options include 'Entity' and 'Vessel'. Other lists d
Leaving as is, when the source is not from the SDN list, there is no "type" and the row will be NULL.

2020-08-25 20:10 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +    def setUp(self):
Should there be a test case to verify that deleting the SDNMetadata row will also delete the SDNData rows?

2020-08-25 20:13 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +            [SDNFallbackData.SDN_SOURCE, SDNFallbackData.SDN_TYPE, self.sdn_metadata, 'MX'],
+ test case where there are two countries, including the US?

2020-08-25 20:14 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +        self.sdn_type = "Individual"
Worth using the constant value instead of hardcoding the string?

2020-08-25 20:16 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +        self.source = "SDN"
Is this slightly different than the SDN_SOURCE constant...?

2020-08-25 21:09 UTC, julianajlk commented on ecommerce/extensions/payment/tests/test_models.py
> +        self.sdn_type = "Individual"
Good catch, added the constant at a later stage and forgot to update here too

2020-08-25 21:10 UTC, julianajlk commented on ecommerce/extensions/payment/tests/test_models.py
> +        self.source = "SDN"
Adding to use the constant here as well

2020-08-25 21:18 UTC, dianekaplan commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, csv_import, country):
Just want to make sure I'm understanding- what will this filter_records be used for in real life? (At first I imagined it'll be used to look people up during fallback sdn check, but then I'd expect to be able to pass values for names and addresses too, so it may be for some other purpose? Maybe this is just for AC 4 and then will be expanded later for search?

2020-08-25 21:23 UTC, dianekaplan reviewed
This is great- it's so cool to see all the different pieces start to line up :)

One thing I wasn't sure about- I noticed these two bullets in the ticket's implementation notes and not sure I'm seeing them in these files changed- are they still part of this one?
-  Have some way to identify items for computing how much a new list changed (raw row SHA? row SHA of only important fields?)
- API documentation

2020-08-26 00:28 UTC, emma-green requested changes

2020-08-26 00:28 UTC, emma-green commented on docs/decisions/0007-sdn-fallback.rst
> +We decided not to denormalize the data because having one row in the database per record in the CSV more closely matches the data from the API. If for example we denormalize by country, the query to
Can you please reword this to give a reason why you might denormalize, a reason why not to, and then why the reasons not to outweighed the reasons to?

2020-08-26 00:28 UTC, emma-green commented on ecommerce/extensions/payment/models.py
> +        sdn_type (CharField): For a person with source Specially Designated Nationals (SDN) - Treasury Department, the type is 'Individual'. Other options include 'Entity' and 'Vessel'. Other lists d
It is okay to have an ENUM where one value is NULL. Why would we assume that what we would want to do with a new type is not include it?

2020-08-26 00:28 UTC, emma-green commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, csv_import, country):
Don't we want to use lists other than the sdn list?

2020-08-26 00:28 UTC, emma-green commented on ecommerce/extensions/payment/tests/test_models.py
> +    LOGGER_NAME = 'ecommerce.extensions.payment.models'
why are we logging during tests?

2020-08-26 01:05 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, csv_import, country):
good point, i believe we include two lists, though I forgot the name of the other one.  @inventhouse might know
i think it is configured here
https://github.com/edx/ecommerce/blob/14a4c494cedaa97c68161abf575a4bf0eb6d7978/ecommerce/extensions/payment/utils.py#L161
but I don't think anyone on our team has permissions to access the prod site configuration so we may want to get that

2020-08-26 10:12 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/tests/test_models.py
> +    def setUp(self):
this is a good idea

2020-08-26 11:50 UTC, julianajlk commented on docs/decisions/0007-sdn-fallback.rst
> +We decided not to denormalize the data because having one row in the database per record in the CSV more closely matches the data from the API. If for example we denormalize by country, the query to
I'm not sure I understand your comment - I thought the paragraph covers these points? Except for the reason one outweighs the other could be more explanatory (ie. add "... would not be greatly significant because...")

2020-08-26 12:00 UTC, julianajlk commented on ecommerce/extensions/payment/tests/test_models.py
> +    LOGGER_NAME = 'ecommerce.extensions.payment.models'
I was following other tests when I set this set up (seems to be common practice to use LogCapture in other places) but didn't actually do any logging with this though. Will remove it.

2020-08-26 12:04 UTC, julianajlk commented
> This is great- it's so cool to see all the different pieces start to line up :)
> 
> One thing I wasn't sure about- I noticed these two bullets in the ticket's implementation notes and not sure I'm seeing them in these files changed- are they still part of this one?
> 
> * Have some way to identify items for computing how much a new list changed (raw row SHA? row SHA of only important fields?)
> * API documentation

Thanks for the review! The notes in this ticket are confusing, since it's not in the ACs and the SHA could be done with hashing functions, but would make more sense for this to be added in the metadata? I believe this should be in another ticket. 

"API documentation" I suspect someone forgot to add a link to that, as it's just in the notes.

2020-08-26 12:33 UTC, MatthewPiatetsky commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, csv_import, country):
one of the tickets says it is ISN,SDN, so assuming whoever found that checked our prod config, we can update the code to filter for those two sources (with that format)

2020-08-26 12:53 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, csv_import, country):
Sounds good, will add “Nonproliferation Sanctions (ISN) - State Department” to the source and the logic to use both

2020-08-26 13:07 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, list_id, country):
Changed `list_id` to `sdn_fallback_metadata`

2020-08-26 14:03 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, csv_import, country):
As discussed in https://edx-internal.slack.com/archives/C014U16T2N9/p1598448260003500, filtering will be done by SDN source only.

2020-08-26 14:27 UTC, emma-green commented on docs/decisions/0007-sdn-fallback.rst
> +We decided not to denormalize the data because having one row in the database per record in the CSV more closely matches the data from the API. If for example we denormalize by country, the query to
Yes, so I've found it very helpful to describe decisions like this (and in this order):
- One way you could do it
- Another way you could do it
- Which way you decided to do it and why.

2020-08-26 14:40 UTC, emma-green commented on docs/decisions/0007-sdn-fallback.rst
> +We decided not to denormalize the data because having one row in the database per record in the CSV more closely matches the data from the API. If for example we denormalize by country, the query to
I would imagine rewording this to something like this:
```We considered denormalizing the country data, where we each row would be a unique combination of person, country, and type. This would mean duplicating rows from the CSV on the country. This would help performance when querying by country.

However, importing the data as a one-to-one would more closely matches the data from the API. It would also more closely match the data from the CSV, and be more straight-forward to an engineer reading the code. The database would also require less space.

Right now, the performance gains would not be substantial, therefore, we do not think that the performance gains of denormalizing would not be enough to outweigh the costs to complexity and space.  We have decided to not denormalize the data.```

^This is also a good example of what I am looking for when I ask you to examine the pros and cons of any decision that you need to make. Take note that we are listing the pros of the thing we decided not to do. This allows a future engineer (or just me, if you are chatting with me) to know that you have fully investigated both possibilities.

2020-08-26 15:33 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +        source (CharField): Origin of where the data comes from, since the CSV consolidates export screening lists of the Departments of Commerce, State and the Treasury.
Keeping as is as per today's discussion during stand up with Seth.

2020-08-26 15:33 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +        sdn_type (CharField): For a person with source Specially Designated Nationals (SDN) - Treasury Department, the type is 'Individual'. Other options include 'Entity' and 'Vessel'. Other lists d
Keeping as is as per today's discussion during stand up with Seth.

2020-08-26 16:19 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        Filter records by the CSV import (SDNFallbackMetadata), source, type, and country.
"Filter records by the CSV import (the SDNFallbackMetadata file) and country. This method will only find rows with the source = SDN and type = Individual."

Might also be worth renaming to `filter_sdn_individual_records` or so.

2020-08-26 19:24 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +    def filter_records(cls, csv_import, country):
> Just want to make sure I'm understanding- what will this filter_records be used for in real life? (At first I imagined it'll be used to look people up during fallback sdn check, but then I'd expect to be able to pass values for names and addresses too, so it may be for some other purpose?) Maybe this is just for AC 4 and then will be expanded later for search?

@dianekaplan I believe this will be part of another ticket to filter by name etc. This method should/will be renamed.

2020-08-27 16:24 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +            for sdn_type in type_option:
If we're allowing this search to query for multiple `sdn_types` at once, I'm not sure a for loop is the right approach here since I think the `return` will cause the function to exit, so the function would never get past the first iteration of the loop

2020-08-27 16:30 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +        return SDNFallbackData.objects.filter(sdn_fallback_metadata=current_metadata, source=source)
A common code pattern I've seen used when applying logic based on the parameters (note: my syntax might be off a bit):
 
```def foo(cls, source, sdn_type):
   search_params = { source: source }
   if sdn_type:
       search_params[sdn_type] = sdn_type
   return SDNFallbackData.objects.filter(***search_params)```

This reduces the code duplication (only one return statement) and makes it easier to follow (apply some logic to params [e.g. this one is required, that one is optional]; search based off the params; return the search results).

2020-08-27 16:32 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +    def test_fields(self):
Does this test need the three created rows from the setup?

2020-08-27 16:33 UTC, jhan217 commented on ecommerce/extensions/test/factories.py
> +    sdn_fallback_metadata = "SDNFallbackMetadata"
You'll probably want to use a SubFactory to create the SDNFallbackMetadata object here, e.g. https://factoryboy.readthedocs.io/en/latest/recipes.html

2020-08-27 16:36 UTC, jhan217 commented on ecommerce/extensions/payment/tests/test_models.py
> +        new_data = SDNFallbackData(
You could probably replace this with the factory generated object, since you're not testing the creation of this row.

2020-08-27 16:49 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +            for sdn_type in type_option:
@jhan217 My first intention was to search for only one `sdn_type` so I wasn't concerned about iteration but I suppose we shouldn't stop from doing multiple types

2020-08-27 16:50 UTC, julianajlk commented on ecommerce/extensions/test/factories.py
> +    sdn_fallback_metadata = "SDNFallbackMetadata"
@jhan217 subfactories!! That's perfect. Thanks for the link!

2020-08-28 14:14 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +        return SDNFallbackData.objects.filter(sdn_fallback_metadata=current_metadata, source=source)
Refactored to this: 
`current_metadata=SDNFallbackMetadata.objects.get(import_state="Current")
  query_params = {'source': source, 'sdn_fallback_metadata': current_metadata }
        if sdn_types:
            for sdn_type in sdn_types:
                query_params['sdn_type'] = sdn_type
        return SDNFallbackData.objects.filter(**query_params)`

2020-08-28 14:24 UTC, jhan217 commented on ecommerce/extensions/payment/models.py
> +            for sdn_type in sdn_types:
It might be worth adding a test to see what happens when you have pass in two sdn_types.

2020-08-28 17:15 UTC, julianajlk commented on ecommerce/extensions/payment/models.py
> +            for sdn_type in sdn_types:
Went back and removed the optional arg, to reflect the query functionality to only filter by one source, one type

2020-08-28 18:45 UTC, emma-green approved these changes

2020-08-28 19:51 UTC, jhan217 approved these changes

2020-08-31 12:54 UTC, merged