ENT-3148: Create Snowflake tables for code assignment emails
openedx-unsupported/ecommerce pull request #3194
Opened 2020-10-07 13:57 UTC by sameenfatima78

JIRA: https://openedx.atlassian.net/browse/ENT-3148

2020-10-08 01:53 UTC, moconnell1453 requested changes
Looks good, but you need to reorder your imports so Travis checks pass.

2020-10-08 14:03 UTC, muhammad-ammar commented on ecommerce/extensions/api/serializers.py
> +                    create_offer_assignment_email_sent_record(enterprise_customer, template_id, ASSIGN)
This will create lot of records in case of bulk assign, is this expected behaviour? For example, if we assign codes to 50 learners, this will create 50 records with same data. I don't think this is what we need.

2020-10-09 05:03 UTC, muhammad-ammar requested changes
I am done with first pass of the feedback. Let me know when it is ready for second review.

Changes looks good but we need to add unit tests to ensure new functionality is working as expected.

2020-10-09 05:03 UTC, muhammad-ammar commented on ecommerce/extensions/offer/utils.py
> +def create_offer_assignment_email_sent_record(enterprise_customer_uuid, template_id, email_type):
I think instead of creating this util here we can move this to `OfferAssignmentEmailSentRecord` as a class method.

2020-10-19 17:02 UTC, moconnell1453 approved these changes

2020-10-20 09:58 UTC, sameenfatima78 commented on ecommerce/extensions/api/serializers.py
> +                    create_offer_assignment_email_sent_record(enterprise_customer, template_id, ASSIGN)
Your feedback has been incorporated.

2020-10-20 09:58 UTC, sameenfatima78 commented on ecommerce/extensions/offer/utils.py
> +def create_offer_assignment_email_sent_record(enterprise_customer_uuid, template_id, email_type):
Your feedback has been incorporated.

2020-10-29 13:35 UTC, HammadAhmadWaqas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            template = OfferAssignmentEmailTemplates.objects.get(id=template_id)
I think we will get 500 error if the template_id will not exist.

2020-11-02 08:23 UTC, sameenfatima78 commented on ecommerce/extensions/api/v2/views/enterprise.py
> +            template = OfferAssignmentEmailTemplates.objects.get(id=template_id)
fixed

2020-11-02 11:57 UTC, saleem-latif approved these changes

2020-11-02 13:21 UTC, muhammad-ammar requested changes

2020-11-02 13:21 UTC, muhammad-ammar commented on ecommerce/extensions/offer/models.py
> +        return template_record
what about the below? 
```python
return cls.objects.create(
    template_content_object=template,
    enterprise_customer=enterprise_customer_uuid,
    email_type=email_type
)
```

2020-11-02 13:21 UTC, muhammad-ammar commented on ecommerce/extensions/offer/models.py
> +            email_type (str): The type of the email sent e:g Assign, Remind or Revoke
order of argument in the docstring needs to match the order in the method signature.

2020-11-02 13:21 UTC, muhammad-ammar commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        enterprise_customer = coupon.attr.enterprise_customer_uuid
Instead of this `try...except` at 3 places what if we write a class method in the model?

```python
@classmethod
def get_template(cls, template_id):
    try:
        template = cls.objects.get(id=template_id)
    except ObjectDoesNotExist:
         template = None

    return template
```

and use it like
```python
template = OfferAssignmentEmailTemplates.get_template(template_id)
```

2020-11-02 13:21 UTC, muhammad-ammar commented on ecommerce/extensions/offer/models.py
> +    template_content_type = models.ForeignKey(
Can you mention which models will use this foreign key? Currently I only see `OfferAssignmentEmailTemplates`.

2020-11-02 13:31 UTC, sameenfatima78 commented on ecommerce/extensions/offer/models.py
> +    template_content_type = models.ForeignKey(
Yes, that is not the scope of this ticket, it will be taken care of in ENT-3489 where I will specifically mention the models name. Currently the Foreign Key is associated to only one model.

2020-11-02 13:32 UTC, sameenfatima78 commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        enterprise_customer = coupon.attr.enterprise_customer_uuid
Good suggestion, I will work on that.

2020-11-02 13:49 UTC, HammadAhmadWaqas commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        enterprise_customer = coupon.attr.enterprise_customer_uuid
or without adding any method
`OfferAssignmentEmailTemplates.objects.filter(id=template_id).first()`

2020-11-03 05:41 UTC, sameenfatima78 commented on ecommerce/extensions/offer/models.py
> +        return template_record
I tried it that way but it gave an error saying that it does not recognise the argument `template_content_object`. As the column name in the table is stored as `template_content_object_id`

The current way is the recommended way in documentation as well.

2020-11-03 06:44 UTC, sameenfatima78 commented on ecommerce/extensions/offer/models.py
> +            email_type (str): The type of the email sent e:g Assign, Remind or Revoke
fixed.

2020-11-03 06:44 UTC, sameenfatima78 commented on ecommerce/extensions/api/v2/views/enterprise.py
> +        enterprise_customer = coupon.attr.enterprise_customer_uuid
fixed.

2020-11-03 07:28 UTC, muhammad-ammar approved these changes
LGTM

2020-11-03 09:44 UTC, merged