Implement SDNFallback is SDN API is down
openedx-unsupported/ecommerce pull request #3201
Opened 2020-10-09 20:15 UTC by julianajlk

[REV-1538](https://openedx.atlassian.net/browse/REV-1538).

2020-10-15 19:02 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +                    response
Just noticed the variable assignment is missing, my next commit will add `response =`, and update my test to catch that

2020-10-15 19:04 UTC, julianajlk commented on ecommerce/extensions/payment/core/tests/test_sdn.py
> +            request = RequestFactory().post('/payment/cybersource/submit/')
These mocks (request, site_configuration, etc) are used in my 3 tests but not in the other SDNFallbackTests, not sure how I can avoid repetition in the other tests

2020-10-15 19:36 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +                    response
Could you pass in something like `{ failure_reason: SDNFallback_hit}` instead of the `response` object here?

2020-10-15 19:55 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +            # checkSDNFallback will be called. If it finds a match
🎱 What do you think of reducing the duplicate code & just having one code path for deactivating/logging out the user?

```
deactivate_user_response = null;

# figure out if we need to deactivate the user or not
try: 
  if hit_count > 0:
    deactivate_user_response = sdn_check.search(name, city, country)
except (HTTPError, Timeout):
  if SDNFallback_hit:
     log()
     deactivate_user_response = SDNFallback_hit

# actually deactivate the user if we need to
if deactivate_user_response:
  sdn_check.deactivate_user(...deactivate_user_response)
  logout(request)
```

2020-10-15 21:54 UTC, emma-green requested changes
I left some comments here. The biggest issue that I see is that if the fallback gets a hit, it will error, because it has not set the hit_count variable. Otherwise, everything else is feedback to help you grow as an engineer. If it's not entirely clear what I'm getting at (very likely), let's put some time on the calendar to go through it together.

2020-10-15 21:54 UTC, emma-green commented on ecommerce/extensions/payment/core/sdn.py
> +                    response
A few of thoughts:
- When we look at hits later, we will want one search string that will return hits from both the api and the fallback. We will also want to know if this hit came from the api or fallback. We already have a log that tells us if the api had an issue -- we can reuse this to determine if the fallback should be used.
- If we get a timeout or http error, we will not set the hit_count variable, which will not be great when we return.
- We want to do the same thing (de-activate and logout) regardless of whether the hit came from the api or the fallback.
- (Not your code, I know)It's a best practice to put the minimum number of lines possible into a try clause.

Therefore, you could 
1. move lines 52-61 to after the exception
2. remove lines 71-80
3. change line 66 to be `response = checkSDNFallback(`
4. make sure that the checkSDNFallback returns a dictionary with a hit-count (or add another line to get the hit-count on line 71)
5. figure out what info we would want for if the fallback is used. Is the current log enough? Or should we modify it, or add another log?

Happy to grab some time on a calendar if this would be easier to talk about synchronously.

2020-10-15 21:54 UTC, emma-green commented on ecommerce/extensions/payment/core/tests/test_sdn.py
> +            request = RequestFactory().post('/payment/cybersource/submit/')
make a helper function? 
or 
one test function and use ddt.data(True, False) to determine whether the fallback should return a hit or not? (What I would do, but not everyone would agree. :) )

2020-10-15 21:54 UTC, emma-green commented on ecommerce/extensions/payment/core/tests/test_sdn.py
> +            with mock.patch.object(User, 'deactivate_account') as deactivate_account:
it looks like you are testing the deactivate_user function here, which is unnecessary. You need to test that it is called, but not that it works.

2020-10-16 13:07 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            # checkSDNFallback will be called. If it finds a match
This is better than having a separate deactivate + logout method, thanks! Will add that in

2020-10-16 13:31 UTC, dianekaplan commented
So exciting to finally start using the fallback! 🎉 🎉  

One note/question on scope: it wasn't called out in the ticket, but now that we'll be using the fallback in real life we no longer need the shadow call and comparison code. If @emma-green agrees, we should also include that cleanup now that we're done with it:
- 	extensions/payment/views/cybersource.py- update check_sdn: remove the shadow call to compare_SDNCheck_vs_fallback (and the import)	
- 	sdn.py: remove compare_SDNCheck_vs_fallback function	
- 	test_sdn.py: remove 2 tests calling remove compare_SDNCheck_vs_fallback (and the import)

For the updates so far, my feedback on consolidating/reusing deactivate_and_logout is already covered above, and I'll take a closer look to see if there's anything else. Good job!

2020-10-16 13:54 UTC, julianajlk commented
> So exciting to finally start using the fallback! 🎉 🎉
> 
> One note/question on scope: it wasn't called out in the ticket, but now that we'll be using the fallback in real life we no longer need the shadow call and comparison code. If @emma-green agrees, we should also include that cleanup now that we're done with it:
> 
> * extensions/payment/views/cybersource.py- update check_sdn: remove the shadow call to compare_SDNCheck_vs_fallback (and the import)
> * sdn.py: remove compare_SDNCheck_vs_fallback function
> * test_sdn.py: remove 2 tests calling remove compare_SDNCheck_vs_fallback (and the import)
> 
> For the updates so far, my feedback on consolidating/reusing deactivate_and_logout is already covered above, and I'll take a closer look to see if there's anything else. Good job!

Ah yes, forgot to mention in the description that we will run the shadow for 1 month :)

2020-10-16 14:26 UTC, julianajlk commented
@dianekaplan Ah yes, forgot to mention in the description that we will run the shadow for 1 month :)

2020-10-16 16:14 UTC, emma-green commented on ecommerce/extensions/payment/core/sdn.py
> +            response['total'] = 1
do we actually care about the number of hits? If so, we should be adding one, rather than just setting it to one. And then we can return once, outside of the for loop.

2020-10-16 16:50 UTC, julianajlk commented on ecommerce/extensions/payment/core/tests/test_sdn.py
> +            request = RequestFactory().post('/payment/cybersource/submit/')
I'll go with helper function!

2020-10-16 16:58 UTC, dianekaplan commented
> @dianekaplan Ah yes, forgot to mention in the description that we will run the shadow for 1 month :)

Ah thanks I didn't see- added details to REV-1343 instead- thanks!

2020-10-16 17:24 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            response['total'] = 1
Not sure if we do - before it was True/False. I think it's a good idea to add it and reflect more of what the `sdn_check.search` is doing

2020-10-20 14:35 UTC, dianekaplan commented on ecommerce/extensions/payment/core/sdn.py
> +                hit_count
Little nitpick (here and a couple spots below): the fallback only returns true or false (not number of matches/hits like the SDN API does) so that log message may mislead the reader to thinking they matched exactly one record in the fallback data. Could avoid that by updating log message to "SDNFallback match: True" or "SDNFallback match: False", or something like that.

2020-10-20 14:38 UTC, dianekaplan commented on ecommerce/extensions/payment/core/sdn.py
> +            sdn_check.deactivate_user(
Not sure if it's just my eyes, but from line 67 to here, I think we're still in the except block, right? If the SDN API is still working and returns a hit right away, I think the user won't be deactivated the way the code is right now. Should indentation move left for this block starting from line 67?

2020-10-20 14:40 UTC, dianekaplan commented on ecommerce/extensions/payment/core/sdn.py
> +                hit_count
D'oh! Reading down the rest of the PR, you've changed this behavior, so this comment is correct- nevermind!

2020-10-20 14:41 UTC, dianekaplan commented on ecommerce/extensions/payment/core/tests/test_sdn.py
> +        Verify SDNFallback is called if SDN API returns an errror/timeout.
(teeny typo in comment: errror)

2020-10-20 15:23 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +            hit_count = checkSDNFallback(
Could you rename this to something like `sdn_fallback_hit_count` so it's not as confusing when you read line 66?

2020-10-20 15:23 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +        hit_count = response['total']
Could you remove line 39 and replace it with a `hit_count = response['total'] or 0` here to make it more explicit as to what's going on?

2020-10-20 15:23 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
Do we only ever want to return a max of 1? If so, then why change from a boolean to an integer?

2020-10-20 15:23 UTC, jhan217 commented on ecommerce/extensions/payment/core/tests/test_sdn.py
> +        If there is a hit, log hit and block the user with deactive/logout.
nit: `If there is at least 1 hit` (or match) - would be nice to match terminology with return types (e.g. integer vs boolean)

2020-10-20 15:23 UTC, jhan217 commented on ecommerce/extensions/payment/migrations/0031_sdnfallbackdata.py
> +# Generated by Django 2.2.15 on 2020-10-19 14:53
Why is this changing?

2020-10-20 15:31 UTC, julianajlk commented on ecommerce/extensions/payment/migrations/0031_sdnfallbackdata.py
> +# Generated by Django 2.2.15 on 2020-10-19 14:53
Oops, this should not be here, it was changed when I was trying to fix the uniqueness error so I did migrations again - but that didn't change/fix anything. Will remove it.

2020-10-20 15:35 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            hit_count = checkSDNFallback(
Sure

2020-10-20 15:37 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
Changing from boolean to integer to match more of what regular SDN check returns in the response, Emma had mentioned we would want to know if the fallback had more than 1 hit as well.

2020-10-20 15:41 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
If we'd like to return more than 1 hit, should this return get removed?

2020-10-20 15:43 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +        hit_count = response['total']
I believe this will cause an error where `response` is referenced before assignment

2020-10-20 15:45 UTC, julianajlk commented on ecommerce/extensions/payment/core/tests/test_sdn.py
> +        If there is a hit, log hit and block the user with deactive/logout.
But now both SDN API and SDNFallback are returning an integer.

2020-10-20 16:00 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            sdn_check.deactivate_user(
I believe it's outside of the except block. I am going to the 👀 doctor tomorrow, so it could be my eyes too!

2020-10-20 16:02 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
That's a good question, @emma-green thoughts? There isn't a test for SDN API returning more than 1 hit at the moment either.

2020-10-20 16:03 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +        hit_count = response['total']
Missed the "here", so nevermind to the above error, it would not error out on line 66

2020-10-20 16:08 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
Also, yes to removing the return, it's redundant

2020-10-20 16:10 UTC, emma-green commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
agreed that you need to remove the internal return, because it will always return when it gets to the first one, and will not actually count hits. 

also, a good idea to change the test cases to enable this new functionality.

2020-10-20 16:12 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +        hit_count = response['total']
If it doesn't go through the if statement (if `site_configuration.enable_sdn_check` is False) it will not go through line 66 but it will still need to return the hit_count, will keep it at the top  instead of removing and replacing on line 66

2020-10-20 16:30 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
Should I add a test case for SDN API too? If yes, is this part of this ticket?

2020-10-20 16:33 UTC, jhan217 commented on ecommerce/extensions/payment/core/tests/test_sdn.py
> +        If there is a hit, log hit and block the user with deactive/logout.
Yup, and I think the logic there is to deactivate if there are >=1 hits, so it would be nice if the description matched.

2020-10-20 16:34 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
My 2c - Test case for SDN API is either redundant or out of scope, but we're changing functionality for the SDN Fallback so we should add a test case for multiples for the fallback.

2020-10-20 16:36 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +        hit_count = response['total']
Ah ok

2020-10-20 16:51 UTC, emma-green commented on ecommerce/extensions/payment/core/sdn.py
> +        hit_count = response['total']
you could put it in an else statement?

2020-10-20 18:01 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            return hit_count
Yes, for the SDNFallback adding now.

2020-10-20 20:15 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +            # import pdb; pdb.set_trace()
Might be worth removing this comment

2020-10-20 21:24 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +            # import pdb; pdb.set_trace()
I have another commit coming, not done yet 😅

2020-10-21 14:16 UTC, jhan217 approved these changes
Looks good to me, had a couple of comments on making the log messages more useful. Might be worth checking in with @emma-green for her thoughts + see if it's safe to merge and deploy, since it sounded like there was something going on with the SDN stuff last night.

2020-10-21 14:16 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +                'SDNCheck: SDN API call received an error/timeout. SDNFallback function called for basket [%d].',
🎱 Would be nice to add more detail about the error here (or at least note if it's an httperror or timeout) so if we get a lot of them we have somewhere to start for debugging things (e.g. increase the timeouts, ask them about an increase in 5xx errors, update the url if it 404s)

2020-10-21 14:16 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +                'SDNCheck received %d hit(s).',
🎱 Worth logging the basket id/user id of the person being deactivated so all the information is in one place/log statement, right before the code that does the deactivation? Something like `SDNCheck received %d hit(s), deactivating user id %s, basket id %s`

2020-10-21 14:28 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +                'SDNCheck received %d hit(s).',
User info is being logged in `deactivate_user()`. This log is just to acknowledge there was a hit first. Although only the name is being logged.

2020-10-21 14:29 UTC, julianajlk commented on ecommerce/extensions/payment/core/sdn.py
> +                'SDNCheck: SDN API call received an error/timeout. SDNFallback function called for basket [%d].',
That's a good idea 👍

2020-10-21 15:40 UTC, jhan217 commented on ecommerce/extensions/payment/core/sdn.py
> +                'SDNCheck received %d hit(s).',
Ok, my point was that it would be nice to have all of that info together in one log line so you only have to search for one log line instead of two (and correlate timestamps).

2020-10-22 14:15 UTC, emma-green commented on ecommerce/extensions/payment/core/sdn.py
> +                'SDNCheck received %d hit(s).',
I believe we log this elsewhere: https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/payment/views/cybersource.py#L93

So, this log is superfluous anyhow.

2020-10-23 15:13 UTC, emma-green approved these changes

2020-10-23 15:27 UTC, merged