ENT-3479 | Added save and add more functionality in enterprise coupon…
openedx-unsupported/ecommerce pull request #3203
Opened 2020-10-12 09:53 UTC by hasnain-naveed

… creation page.

2020-10-13 07:54 UTC, sameenfatima78 requested changes
Shouldn't we add test cases to ensure that this new functionality is working as expected?

2020-10-13 07:54 UTC, sameenfatima78 commented on ecommerce/static/js/views/enterprise_coupon_form_view.js
> +                    this.$('.submit-add-more').html(gettext('Create and Add More'));
Nit: I think 'Create and add another' would make more sense.

2020-10-13 08:02 UTC, hasnain-naveed commented
@sameenfatima78 yes, you are right but there are no test cases for this file enterprise_coupon_form_view, you can check the code base.

2020-10-13 08:07 UTC, sameenfatima78 commented
@hasnain-naveed I think they are in this file: https://github.com/edx/ecommerce/blob/master/ecommerce/static/js/test/specs/views/enterprise_coupon_create_edit_view_spec.js

2020-10-13 08:21 UTC, hasnain-naveed commented
> @hasnain-naveed I think they are in this file: https://github.com/edx/ecommerce/blob/master/ecommerce/static/js/test/specs/views/enterprise_coupon_create_edit_view_spec.js

These are the model save test cases. I just added a new button I can add a test case that will be ensuring that the button is visible in case of creation and disable in case of the edit.

2020-10-13 10:40 UTC, hasnain-naveed commented on ecommerce/static/js/views/enterprise_coupon_form_view.js
> +                    this.$('.submit-add-more').html(gettext('Create and Add More'));
It is in A/C/.

2020-10-13 11:27 UTC, sameenfatima78 approved these changes

2020-10-14 08:19 UTC, saleem-latif approved these changes

2020-10-14 09:06 UTC, merged