ENT-3489: Save Nudge Emails Info in OfferAssignmentEmailSentRecord
openedx-unsupported/ecommerce pull request #3246
Opened 2020-11-11 09:23 UTC by sameenfatima78

Jira: https://openedx.atlassian.net/browse/ENT-3489

2020-11-11 10:39 UTC, HammadAhmadWaqas requested changes, later dismissed

2020-11-11 10:39 UTC, HammadAhmadWaqas commented on ecommerce/extensions/api/serializers.py
> +            self._create_offer_assignment_email_sent_record(enterprise_customer_uuid, ASSIGN, new_code, user_emails[0])
Should not this the responsibility of the CouponCodeAssignmentSerializer to create the email sent record as well?
instead of calling it separately.
we can set `sender_category` in context.

@irfanuddinahmad what would you suggest?

2020-11-11 10:49 UTC, HammadAhmadWaqas commented on ecommerce/extensions/api/serializers.py
> +            self._create_offer_assignment_email_sent_record(enterprise_customer_uuid, ASSIGN, new_code, user_emails[0])
as discussed on the call, we will refactor this in follow up PR.

2020-11-11 10:49 UTC, saleem-latif approved these changes

2020-11-11 11:23 UTC, sameenfatima78 commented on ecommerce/extensions/api/serializers.py
> +            self._create_offer_assignment_email_sent_record(enterprise_customer_uuid, ASSIGN, new_code, user_emails[0])
FYI for everyone else: 

Since Assign emails are already being recorded in the `assign` view, moving this piece of code to `CouponCodeAssignmentSerializer` would start recording the assign emails instances twice. 

The reason why we thought to keep the code in View instead of serializer earlier is because we agreed on storing only one record in case of bulk emails but now since it's been decided to store a separate record for every email sent (even bulk), we will be again shifting this code to the serializer in the follow up PR.

2020-11-12 09:51 UTC, irfanuddinahmad approved these changes
As discussed, since we are only inserting data, you can remove the index.

2020-11-18 10:19 UTC, merged