Added awin level product tracking
openedx-unsupported/ecommerce pull request #3264
Opened 2020-11-30 08:47 UTC by adeelehsan

VAN-112

2020-11-30 09:17 UTC, waheedahmed commented on ecommerce/templates/edx/checkout/receipt.html
> +            <form style="display: none;" name="aw_basket_form">
Will not it hide all the content rendered inside it?

One way of doing it could be; manage a list and append all the rows inside it and then create the form outside the loop by just joining that list with the new line `\n` character.

2020-11-30 09:25 UTC, waheedahmed commented on ecommerce/templates/edx/checkout/receipt.html
> +              <textarea wrap="physical" id="aw_basket">
Also, this will show all the content render inside it as a text inside a `textarea`.

2020-12-01 11:22 UTC, waheedahmed requested changes

2020-12-01 11:22 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +            'product_tracking': self.add_product_tracking(order, order.basket.all_lines()),
No need to pass the order lines separately, you can get them inside the function from order. And use `order.lines.all()` instead of `order.basket.all_lines()`

2020-12-01 11:22 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +            'product_tracking': self.add_product_tracking(order, order.basket.all_lines()),
We should move this under a check if `settings.AWIN_ADVERTISER_ID` is defined. No need to do this if `AWIN_ADVERTISER_ID` is not set.

2020-12-01 11:22 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +            products_for_tracking.append("AW:P|{{{id}}}|{{{order_number}}}|{{{course_id}}}|{{{title}}}|{{{price}}}|"
Why we are wrapping the format variables with 3 curly braces while we just need one?

2020-12-01 11:22 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +        return products_for_tracking
I believe we also need to join the list items before returning.

2020-12-01 11:22 UTC, waheedahmed commented on ecommerce/templates/edx/checkout/receipt.html
> +             <form style="display: none;"  name="aw_basket_form">
Use class `hidden` instead of inline styles.

2020-12-01 11:22 UTC, waheedahmed commented on ecommerce/templates/edx/checkout/receipt.html
> +             <form style="display: none;"  name="aw_basket_form">
Also, move this under if clause:
```suggestion
        {% if product_tracking %}
             <form style="display: none;"  name="aw_basket_form">
```

2020-12-01 11:44 UTC, waheedahmed commented on ecommerce/templates/edx/checkout/receipt.html
> +               </textarea>
Make this one line otherwise, it will add spaces at the start of the value.
```suggestion
               <textarea wrap="physical" id="aw_basket">{{ product_tracking }}</textarea>
```

2020-12-01 11:45 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +                                         "{{{quantity}}}|{{{partner_sku}}}|{{{categories}}} \r\n"
Remove white space between the value and new line operator.

2020-12-01 13:08 UTC, adeelehsan commented on ecommerce/templates/edx/checkout/receipt.html
> +             <form style="display: none;"  name="aw_basket_form">
Class hidden does not work.

2020-12-01 13:18 UTC, waheedahmed commented on ecommerce/templates/edx/checkout/receipt.html
> +             <form style="display: none;"  name="aw_basket_form">
It does work, I have tested locally `class="hidden"`.

2020-12-01 13:19 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +            'product_tracking': self.add_product_tracking(order, order.basket.all_lines()),
Remove this now, since we move it under the check.

2020-12-01 13:27 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +                                         "{quantity}|{partner_sku}|{categories}"
`commissionGroupCode` is missing in this data, we should set it to `DEFAULT` if we don't really know what it is.

2020-12-01 13:28 UTC, waheedahmed commented on ecommerce/extensions/checkout/views.py
> +                                                 partner_sku=line.partner_sku, categories=line.product.categories)
Set `categories=""` since we don't set categories for our products.

2020-12-01 16:46 UTC, adeelehsan commented on ecommerce/extensions/checkout/views.py
> +                                         "{quantity}|{partner_sku}|{categories}"
I am assuming awin would set to default if we don't set the value.

2020-12-04 09:58 UTC, waheedahmed approved these changes

2020-12-04 14:05 UTC, waheedahmed approved these changes
👍 once build is green.

2020-12-07 11:14 UTC, merged