Add PayTabs Payment Processor
openedx-unsupported/ecommerce pull request #3297
Opened 2021-01-11 11:06 UTC by kaizoku

This adds a new payment processor into ecommerce to support checkout with PayTabs. This only supports server side checkout, and PayTabs requires that users have all fields filled in which are configured in `extended_profile_fields` (listed in the test steps). Otherwise PayTabs will refuse the transactions.

* Supports server side checkouts with PayTabs
* Requires extended profile fields be set for: first_name, last_name, mailing_address, city, and state
* Sends a dummy phone number to PayTabs so user will be prompted on PayTabs side for a phone number
* Adds an additional requirement for ipware to fulfill PayTabs data requirements

**JIRA tickets**: Implements BB-3315

**Discussions**: Architecture discussed extensively on the wiki and in meetings, then the revised proposal was presented to the Arch Council on Oct. 21 and given thumbs up.

**Dependencies**: None

**Screenshots**:

**Sandbox URL**: TBD - sandbox is being provisioned.

**Merge deadline**: None

**Testing instructions**:

A test account needs to be created on paytabs, and the fields filled in the ecommerce repo in `ecommerce/settings/devstack.py` under the `PAYMENT_PROCESSOR_CONFIG`. Also paytabs needs an externally accessible address to finish the payment. We're using ngrok to expose the devstack ecommerce port for paytabs to callback to. Here is an example config stripped of credentials:
```
'paytabs': {
    'merchant_email': 'test@example.com',
    'secret_key': '************************************'
    'default_phone_number_country_code': '00971',
    'return_base_url': 'https://f544d7fd8e8d.ngrok.io'
},

```

1. Configure ecommerce on devstack to use paytabs as the default payment processor from [the SiteConfiguration options](http://localhost:18130/admin/core/siteconfiguration/1/change/)
2. Add a [waffle switch in ecommerce](http://localhost:18130/admin/waffle/switch/) with the name `payment_processor_active_paytabs` to enable the processor
3. Disable, or add and disable, the [waffle flag](http://localhost:18130/admin/waffle/flag/) named `enable_client_side_checkout` to force checkouts to direct to the PayTabs site
4. Setup paytabs configuration in `ecommerce/settings/devstack.py`.
5. Update the LMS SiteConfiguration with the necessary extended profile fields: `"extended_profile_fields":["first_name","last_name","mailing_address","city","state"]`
6. Go to the [account settings page](http://localhost:18000/account/settings) to fill in the necessary fields configured above.
7. Login as a test student user and [upgrade your demonstration course enrollment to verified](http://localhost:18130/basket/add/?sku=8CF08E5) using ecommerce. This will add the upgrade to the basket, and prompt to "Checkout with PayTabs".

**Author notes and concerns**:

1. There isn't a simple way to bubble error messages back to learner's browsers from within the basket page. If all fields are not set in their account profile, they get a generic "transaction failed" when PayTabs refuses if they are missing even one required field, which would make it difficult for them to determine on their own what they need to set in the account profile editor.
2. We use a dummy phone number for this so that PayTabs will prompt users for a phone number. Is this an acceptable approach? Not all users will have a phone number set, and this allows them to be prompted from within PayTabs.

**Reviewers**
- [ ] @lgp171188
- [ ] edX reviewer[s] TBD

2021-01-11 11:07 UTC, edx-webhook commented
Thanks for the pull request, @kaizoku! I've created [OSPR-5354](https://openedx.atlassian.net/browse/OSPR-5354) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-01-12 17:54 UTC, natabene commented
@kaizoku Thank you for your contribution. Please let me know once it is ready for edX review.

2021-02-08 11:19 UTC, shimulch requested changes

2021-02-08 11:19 UTC, shimulch commented on ecommerce/settings/production.py
> +PAYMENT_PROCESSORS = PAYMENT_PROCESSORS + tuple(ADDL_PAYMENT_PROCESSORS)
@kaizoku ``ADDL_PAYMENT_PROCESSORS`` is not defined until we set it in ``ecommerce.yml``. May be we should initialize it in ``settings/base.py`` or somewhere so that installations that don't require ``ADDL_PAYMENT_PROCESSORS`` works fine.

2021-02-08 11:19 UTC, shimulch commented on ecommerce/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                {% trans "Checkout" as tmsg %}{{ tmsg | force_escape }}
@kaizoku, Is it acceptable to have only ``Checkout`` as text? Couldn't we use settings to add text for each custom provider?

2021-02-08 18:26 UTC, kaizoku commented on ecommerce/templates/oscar/basket/partials/hosted_checkout_basket.html
> +                                {% trans "Checkout" as tmsg %}{{ tmsg | force_escape }}
I chose this not to over complicate things, but we could add some settings or maybe a required variable in the payment processors themselves to describe how they should be displayed if that's preferrable.

2021-02-08 18:26 UTC, kaizoku commented on ecommerce/settings/production.py
> +PAYMENT_PROCESSORS = PAYMENT_PROCESSORS + tuple(ADDL_PAYMENT_PROCESSORS)
I opened a configuration pr (https://github.com/edx/configuration/pull/6282) which should add an empty list to the configuration, but this would run into issues if the variable isn't set to avoid that.

2021-02-08 21:41 UTC, shimulch approved these changes
LGTM :+1:

- [x] I tested this on my local devstack. Installed Paytab via this new pluggable framework. It loads Paytab correctly.
- [x] I read through the code
- [N/A] I checked for accessibility issues
- [N/A] Includes documentation

2021-02-10 06:12 UTC, kaizoku commented
Thanks for tracking here @natabene. This is ready for edX review.

2021-02-10 16:08 UTC, natabene commented
@kaizoku Thank you for letting me know. CC @nedbat This is ready from author's perspective.

2021-05-07 08:00 UTC, gabor-boros commented
@kaizoku Could you please rebase this PR?

2021-05-26 17:00 UTC, natabene commented
@nedbat Are you still interested in pushing this forward?

2021-07-19 13:39 UTC, giovannicimolin commented
@natabene We're still pursuing to get this merged upstream.

2021-08-26 15:31 UTC, gabor-boros commented
@natabene how could we help to push this ticket forward? 😇

2021-09-02 02:09 UTC, natabene commented
@gabor-boros We are looking into how we can speed this up Please stay tuned.

2021-10-22 18:11 UTC, nizarmah commented
Hello @natabene! Do you have any updates regarding this pull request?
Let us know please if there's any way we can help.

2021-10-25 14:05 UTC, natabene commented
@gabor-boros No, not yet. We will revisit this in the next couple of months.

2022-04-07 14:41 UTC, natabene commented
@kaizoku Sorry for the long wait and multiple delays. We finally reached our decision. Since we will be deprecating ecommerce repo, we are not planning to take in any new code. Please see details in this [announcement](https://discuss.openedx.org/t/deprecation-removal-ecommerce-service-depr-22/6839).

2022-04-07 14:41 UTC, closed without merging

2022-04-07 14:43 UTC, openedx-webhooks commented
@kaizoku Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/3297&entry.1484655318=https://github.com/kaizoku&entry.752974735=2021-01-11+11:06&entry.1917517419=2022-04-07+14:41&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->