fix: [REV-2501] sdn fallback false positives for empty processed_name
openedx-unsupported/ecommerce pull request #3628
Opened 2022-01-20 16:58 UTC by pshiu

## Description

During a purchase, Ecommerce checks if the purchaser is on an OFAC sanctions list. Usually, an API does this check, but Ecommerce tries to mimic the API's check if the API happens to be unavailable.

If the purchaser's information has transliterable characters, like `é`, we try to transliterate it to something like `e` before checking it against the sanction lists. However, this check fails when purchasers demographic information consist entirely of untransliterable characters, like names in Thai, Russian, Greek, Korean, Amharic, etc.

This makes Ecommerce incorrectly think learners are on a OFAC sanctions list when the learner purchases a course and parts of the purchaser's information consist entirely of non-transliterable characters. This PR fixes that.

## Supporting information

* Jira: [REV-2501](https://openedx.atlassian.net/browse/REV-2501)
* Research: [Confluence](https://openedx.atlassian.net/wiki/spaces/~931919476/pages/3309010958/REV-2501)

## Testing instructions

* In devstack:
   * [X] Add test for SDN failure.
   * [X] Ensure test fails on master but passes on this PR's branch.
* In stage:
   * [ ] Make successful test purchase using normal name.
   * [ ] Make successful test purchase using non-transliterable characters in city name.
   * [ ] Make unsuccessful test purchase using name in SDN.
* In prod:
   * [ ] Make successful test purchase using normal name.
   * [ ] Monitor SDN fallback dashboard in addition to regular monitoring.

2022-01-20 17:17 UTC, dianekaplan reviewed
This change makes sense, and you've included it in the tests- looks good! 

A couple questions/notes: 
- for your testing steps in stage, is this against the fallback rather than API? Do you have a way to force using it? Or we're taking advantage of the fact that the API call is still broken in order to know we're hitting the fallback?
- will approve after the build checks are green. Those pylint failures are a couple of the 'new ones' in the updated pylint version- funny to have them crop up for enterprise tests if those didn't change

2022-01-20 18:40 UTC, inventhouse requested changes

2022-01-20 18:40 UTC, inventhouse commented on ecommerce/extensions/payment/core/sdn.py
> +    # return because a 0-length set is a subset of every set
If the processing the strings would reduce them to nothing, `process_text` should return a set of the original words so we can still at least _try_ to find them in the list.  (Or we should try to determine exactly how the official API handles these and make our code match theirs)

2022-01-20 18:40 UTC, inventhouse commented on ecommerce/extensions/payment/core/sdn.py
> +    if len(processed_name) == 0 or len(processed_city) == 0:
Somewhat a matter of personal preference, but I would write this check as:

`if processed_name or processed_city:`

since anything with `len() == 0` is false-y in Python and I find the direct check more readable (albeit less explicit)

2022-01-20 19:04 UTC, inventhouse commented on ecommerce/extensions/payment/core/sdn.py
> +    # return because a 0-length set is a subset of every set
Or perhaps `process_text` should always include fragments from the original strings in any case

2022-01-24 14:30 UTC, pshiu commented
@dianekaplan, thanks for the review!

> * for your testing steps in stage, is this against the fallback rather than API? Do you have a way to force using it? Or we're taking advantage of the fact that the API call is still broken in order to know we're hitting the fallback?

Yes, yes, and yes! We can force it by doing a temp PR to configuration-internal for stage, putting in a bogus `SDN_CHECK_API_URL`. But it's obviously easier if we can take advantage of the fact that the API call is currently broken.

2022-01-24 14:46 UTC, pshiu commented on ecommerce/extensions/payment/core/sdn.py
> +    # return because a 0-length set is a subset of every set
The official CSL API is a query builder for Elasticsearch. They use the [ASCII folding token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html), which is based on Lucene's Java [`ASCIIFoldingFilter`](https://lucene.apache.org/core/8_10_1/analyzers-common/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.html). A port for Python exists, so I'm looking into that.

If the port doesn't work out, how about I try to do two checks, one with the `process_text`'ed strings, the other with the original? Both checks must have zero hits for the failover SDN query to pass.

Do note, though, that the fallback CSV we use is defined to be ASCII-only [[link](https://home.treasury.gov/policy-issues/financial-sanctions/sdn-list-data-formats-data-schemas/frequently-asked-questions-on-advanced-sanctions-list-standard)]. Thus, even if the primary starts to offer the Unicode SDN list, the secondary will still not magically follow suit even with these changes.

2022-01-24 14:46 UTC, pshiu commented on ecommerce/extensions/payment/core/sdn.py
> +    if len(processed_name) == 0 or len(processed_city) == 0:
Will do!

2022-01-25 15:38 UTC, pshiu commented
Ready for re-review. I changed the implementation so it passes the transliterated characters through. Let me know what you think.

2022-01-25 15:41 UTC, pshiu commented on ecommerce/extensions/payment/core/sdn.py
> +    # return because a 0-length set is a subset of every set
The port didn't work out, but check out the new solution—would appreciate your thoughts!

2022-01-25 15:54 UTC, dianekaplan commented on ecommerce/extensions/payment/core/sdn.py
> +
I'm still a little new to iterators- just for my own info, could you say more about why it's better to yield the characters one by one rather than swapping the characters that need it and returning the full string?

2022-01-25 17:07 UTC, pshiu commented on ecommerce/extensions/payment/core/sdn.py
> +
1. Great question. I did try the swapping approach, but was worried that `replace_char` would be more than one character. This is technically possible from a Python perspective, although I admit I know of no known case of it. I then tried to do appending, but the logic was a lot less concise than using iterators. I will change `replace_char` to `replace_chars` for clarity.
2. This isn't checking whether the character starts with an L or N but rather that character's Unicode category. L are letters and N are numbers. I'll add a comment to that effect! This is required because the `[A-Za-z0-9]` regex that existed several lines below isn't sufficient anymore now that we are processing Unicode text.

2022-01-25 17:30 UTC, pshiu commented on ecommerce/extensions/payment/core/sdn.py
> +
Done. See 7099456.

2022-01-25 21:55 UTC, inventhouse commented on ecommerce/extensions/payment/core/sdn.py
> +    text = set(filter(None, set(re.split(' ', text))))
Instead of replacing non-letter/number characters with space and then splitting on space, would it be better to simply split on non-word characters with `\W+`?

2022-01-25 22:38 UTC, pshiu commented on ecommerce/extensions/payment/core/sdn.py
> +    text = set(filter(None, set(re.split(' ', text))))
Ah! Great call. Done.

2022-01-26 14:41 UTC, inventhouse approved these changes
Great!

2022-01-26 14:42 UTC, dianekaplan commented on ecommerce/extensions/payment/core/sdn.py
> +
Ah that makes sense- thank you!

2022-01-26 14:47 UTC, dianekaplan approved these changes

2022-01-26 15:46 UTC, pshiu commented
Appreciate the review @dianekaplan and @inventhouse.

2022-02-16 14:36 UTC, merged