feat: add atlas pull support
openedx-unsupported/ecommerce pull request #4051
Opened 2023-11-12 12:29 UTC by shadinaif

Refs: FC-0012 OEP-58

# ⛔️ DEPRECATION WARNING

**This repository is deprecated and in maintainence-only operation while we work on a replacement, please see [this announcement](https://discuss.openedx.org/t/deprecation-removal-ecommerce-service-depr-22/6839) for more information.**

Although we have stopped integrating new contributions, we always appreciate security disclosures and patches sent to [security@edx.org](mailto:security@edx.org)

## Anyone internally merging to this repository is expected to [release and monitor their changes](https://openedx.atlassian.net/wiki/spaces/RS/pages/1835106870/How+to+contribute+to+our+repositories); if you are not able to do this DO NOT MERGE, please coordinate with someone who can to ensure that the changes are released.

## Required Testing
- [ ] Before deploying this change, complete a purchase in the stage environment. 
(^ We can remove that manual check once REV-2624 is done and the corresponding e2e test runs again)

## Description

Describe what this pull request changes, and why these changes were made. How will these changes affect other people, installations of edx, etc.?
Please include links to any relevant ADRs, design artifacts, and decision documents. Make sure to document the rationale behind significant changes in the repo, per [OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.

Useful information to include:
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author", "Developer", and "Operator".
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these changes.

## Supporting information

Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.

## Testing instructions

Please provide detailed step-by-step instructions for testing this change; how did YOU test this change?

## Other information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, OpenEdx vs. edx.org differences, development vs. production environment differences, security, or accessibility.

2023-11-12 12:30 UTC, openedx-webhooks commented
Thanks for the pull request, @shadinaif! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2023-11-15 07:43 UTC, shadinaif commented
please review @OmarIthawi , @brian-smith-tcril

2023-11-15 16:46 UTC, brian-smith-tcril commented
@shadinaif looks like the CI failed

2023-11-18 15:48 UTC, shadinaif commented
Fixed. Please run tests again @OmarIthawi , @brian-smith-tcril

2023-11-20 13:25 UTC, brian-smith-tcril approved these changes

2023-11-20 13:27 UTC, brian-smith-tcril commented
@colinbrash you are listed as "review required from" on the spreadsheet for this repo. I'm hoping to get this merged soon, thanks!

2023-11-20 17:31 UTC, OmarIthawi requested changes
@shadinaif I've tested it locally and it worked except for the compilemssage step

Do you mind checking the error bellow?


```
$ docker build -t temp-ecommerce .
$ docker run -it docker.io/library/temp-ecommerce bash
# atlas --version
v0.5.0
# make OPENEDX_ATLAS_PULL=yes pull_translations
```


Error:

```
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/edx/app/ecommerce/ecommerce/ecommerce/settings/devstack.py", line 6, in <module>
    from ecommerce.settings.production import *
  File "/edx/app/ecommerce/ecommerce/ecommerce/settings/production.py", line 60, in <module>
    with codecs.open(CONFIG_FILE, encoding='utf-8') as f:
  File "/usr/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/edx/etc/ecommerce.yml'
make: *** [Makefile:134: pull_translations] Error 1
```

2023-11-21 06:26 UTC, shadinaif commented
Thank you for the tests 😃  @OmarIthawi

It's running fine after copying the file from `devstack` repo to `/edx/etc/ecommerce.yml` inside the docker container. The file does not exist by default. Check the instructions [here](https://github.com/openedx/ecommerce/blob/master/docs/create_products/create_products_overview.rst). It's set by `devstack` [here](https://github.com/openedx/devstack/blob/b52852492a7077c769104ae2c307f5268ad3ffaa/docker-compose.yml#L358)

2023-11-21 15:29 UTC, OmarIthawi commented
I'll test again and let you know.

2023-11-21 18:33 UTC, OmarIthawi approved these changes
It works on devstack. Thanks @shadinaif!!

2023-11-23 06:28 UTC, shadinaif commented
Hi @brian-smith-tcril , I've rebased on `master`, please run tests and merge

2023-11-29 16:42 UTC, brian-smith-tcril commented
@colinbrash I plan on merging this tomorrow afternoon. Please let me know if there is any reason I should hold off.

2023-12-01 06:55 UTC, shadinaif commented
rebased again

2023-12-07 18:38 UTC, merged

2023-12-07 18:38 UTC, openedx-webhooks commented
@shadinaif 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/4051&entry.1484655318=https://github.com/shadinaif&entry.752974735=2023-11-12+12:29&entry.1917517419=2023-12-07+18:38&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->