fix: Enable enrollment code purchase with mobile seats
openedx-unsupported/ecommerce pull request #4130
Opened 2024-02-14 11:42 UTC by moeez96

# ⛔️ MAIN BRANCH WARNING! 2U EMPLOYEES must make branches against the 2u/main BRANCH

- [ ] I have checked the branch to which I would like to merge.

# ⛔️ DEPRECATION WARNING

**This repository is deprecated and in maintainence-only operation while we work on a replacement, please see [this announcement](https://discuss.openedx.org/t/deprecation-removal-ecommerce-service-depr-22/6839) for more information.**

Although we have stopped integrating new contributions, we always appreciate security disclosures and patches sent to [security@edx.org](mailto:security@edx.org)

## Anyone internally merging to this repository is expected to [release and monitor their changes](https://openedx.atlassian.net/wiki/spaces/RS/pages/1835106870/How+to+contribute+to+our+repositories); if you are not able to do this DO NOT MERGE, please coordinate with someone who can to ensure that the changes are released.

## Description
Enable purchasing enrollment codes in presence of multiple enrollment codes for mobile.

Related Jira links:
https://2u-internal.atlassian.net/browse/REV-3857
https://2u-internal.atlassian.net/browse/LEARNER-9837

2024-02-14 12:47 UTC, jawad-khan reviewed
Can we write test case for it?

2024-02-14 12:54 UTC, jawad-khan approved these changes

2024-02-14 13:33 UTC, DawoudSheraz commented on ecommerce/extensions/fulfillment/modules.py
> +                ~Q(stockrecords__partner_sku__icontains="mobile"),
It would be good to have a unit test for this. Ideally, this should have been caught on unit test level. But since it was not, better to add it for the future.

2024-02-14 16:29 UTC, christopappas requested changes

2024-02-14 16:29 UTC, christopappas commented on ecommerce/extensions/fulfillment/modules.py
> +                ~Q(stockrecords__partner_sku__icontains="mobile"),
+1 to what Dawoud says. we should have a unit test accompany this change

2024-02-16 11:31 UTC, moeez96 commented
@christopappas Unit test added, Please review.

2024-02-16 15:29 UTC, christopappas commented on ecommerce/extensions/fulfillment/modules.py
> +                ~Q(stockrecords__partner_sku__icontains="mobile"),
follow up question for @moeez96:  if i am understanding this, is the only way we know whether or not a seat is mobile is if 'mobile' is in the sku? `icontains` tends to be a slower operation, which is likely fine given this is done in a job, but wanted to ask to see if there's something other than text search that indicates whether something is a mobile seat

additionally, what was the failure mode that prompted us to make this change? it looks like the Q() predicate you added will filter out mobile seats, which is good, but this get() could still fail if there are multiple objects returned. are you comfortable with this approach? or is there reason for us to be even more defensive here? (i am not familiar enough with Seats to have an definitive opinion, so i'm asking)

2024-02-16 15:59 UTC, moeez96 commented on ecommerce/extensions/fulfillment/modules.py
> +                ~Q(stockrecords__partner_sku__icontains="mobile"),
@christopappas That's right. We have a standard set for mobile SKUS format and it must contain the keyword mobile. This standard is integrated with the App Store and Plat Store product identifiers. Unfortunately there is nothing other than text search that indicates a seat is a mobile seat.

About the get(), we can replace this get() with a filter().first() but fulfilling a product requires a seat. If you go ahead in the method, the logic can not put up without a seat object. So if we do not have a seat, we want this to throw out an error/exception rather than fail silently.

2024-02-16 16:02 UTC, christopappas commented on ecommerce/extensions/fulfillment/modules.py
> +                ~Q(stockrecords__partner_sku__icontains="mobile"),
great, thank you for answering my questions. in that case, this looks good to me. thank you for adding the test

2024-02-16 16:02 UTC, christopappas approved these changes

2024-02-16 16:03 UTC, merged