Added fallback approach for android purchase validation
openedx-unsupported/ecommerce pull request #4140
Opened 2024-02-29 10:15 UTC by jawad-khan

# ⛔️ MAIN BRANCH WARNING! 2U EMPLOYEES must make branches against the 2u/main BRANCH

- [ ] I have checked the branch to which I would like to merge.

# ⛔️ DEPRECATION WARNING

**This repository is deprecated and in maintainence-only operation while we work on a replacement, please see [this announcement](https://discuss.openedx.org/t/deprecation-removal-ecommerce-service-depr-22/6839) for more information.**

Although we have stopped integrating new contributions, we always appreciate security disclosures and patches sent to [security@edx.org](mailto:security@edx.org)

## Anyone internally merging to this repository is expected to [release and monitor their changes](https://openedx.atlassian.net/wiki/spaces/RS/pages/1835106870/How+to+contribute+to+our+repositories); if you are not able to do this DO NOT MERGE, please coordinate with someone who can to ensure that the changes are released.

## Required Testing
- [ ] Before deploying this change, complete a purchase in the stage environment. 
(^ We can remove that manual check once REV-2624 is done and the corresponding e2e test runs again)

## Description
Added fallback approach for android purchase validation, This fallback is for temporary reason untill all android users move on to new version.

https://2u-internal.atlassian.net/browse/LEARNER-9860
Useful information to include:
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author", "Developer", and "Operator".
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these changes.

## Supporting information

Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.

## Testing instructions

Please provide detailed step-by-step instructions for testing this change; how did YOU test this change?

## Other information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, OpenEdx vs. edx.org differences, development vs. production environment differences, security, or accessibility.

2024-02-29 10:54 UTC, moeez96 commented on ecommerce/extensions/iap/api/v1/google_validator.py
> +        product_sku = 'mobile.android.usd{}'.format(stockrecord_price)
Can we create a util function for this to get consumable SKU from price? This function can be used in the future in other use cases.

2024-02-29 10:54 UTC, moeez96 commented on ecommerce/extensions/iap/api/v1/google_validator.py
> +                # This fallback is for temporary reason untill all android users move on to new version
`This fallback is temporary until all android products are switched to consumable products.`

2024-02-29 10:54 UTC, moeez96 commented on ecommerce/extensions/iap/api/v1/tests/test_google_validator.py
>  import mock
Can we also add unit tests for the method to get consumable SKU from price as mentioned above?

2024-02-29 20:50 UTC, christopappas commented on ecommerce/extensions/iap/api/v1/google_validator.py
> -        product_sku = receipt['productId']
was this value something like `'mobile.android.usd49'` already?

2024-02-29 20:53 UTC, christopappas commented on ecommerce/extensions/iap/api/v1/google_validator.py
> +    def validate(self, receipt, configuration, basket=None):
should basket actually default to None here? it will fail 100% of times if basket is not provided

2024-02-29 20:56 UTC, christopappas requested changes
Requesting changes because I have a few questions, but also because I think this needs an additional test to cover the case where the fallback occurs.

2024-02-29 20:56 UTC, christopappas commented on ecommerce/extensions/iap/api/v1/tests/test_google_validator.py
>      def test_validate_failure(self, mock_google_verifier):
i believe we need an additional test to verify the behavior of this validate function when it fails with a `GoogleError` the first time, but not the 2nd time

2024-03-01 13:03 UTC, jawad-khan commented on ecommerce/extensions/iap/api/v1/google_validator.py
> -        product_sku = receipt['productId']
It will be now. Previously it was something like mobile.android.{alphanumerics}.

2024-03-01 15:58 UTC, christopappas commented on ecommerce/extensions/iap/api/v1/tests/test_google_validator.py
> +                               side_effect=[errors.GoogleError(), GooglePlayVerifierResponse()]), \
awesome, thanks for adding 🙇

2024-03-01 15:59 UTC, christopappas approved these changes

2024-03-01 21:59 UTC, merged