fix: update celery and libsass versions
openedx-unsupported/ecommerce pull request #4147
Opened 2024-03-19 08:51 UTC by Faraz32123

celery version needs to updated due to below error
```
1.512   File "/openedx/ecommerce/ecommerce/extensions/offer/utils.py", line 15, in <module>
1.513     from ecommerce_worker.email.v1.api import send_offer_assignment_email, send_offer_update_email
1.513   File "/openedx/venv/lib/python3.12/site-packages/ecommerce_worker/email/v1/api.py", line 7, in <module>
1.513     from .tasks import (
1.513   File "/openedx/venv/lib/python3.12/site-packages/ecommerce_worker/email/v1/tasks.py", line 6, in <module>
1.514     from celery import shared_task
1.514   File "/openedx/venv/lib/python3.12/site-packages/celery/__init__.py", line 19, in <module>
1.514     from . import local  # noqa
1.514     ^^^^^^^^^^^^^^^^^^^
1.514   File "/openedx/venv/lib/python3.12/site-packages/celery/local.py", line 17, in <module>
1.515     from .five import PY3, bytes_if_py2, items, string, string_t
1.515   File "/openedx/venv/lib/python3.12/site-packages/celery/five.py", line 7, in <module>
1.515     import vine.five
1.515   File "/openedx/venv/lib/python3.12/site-packages/vine/__init__.py", line 8, in <module>
1.515     from .abstract import Thenable
1.515   File "/openedx/venv/lib/python3.12/site-packages/vine/abstract.py", line 6, in <module>
1.516     from .five import with_metaclass, Callable
1.516   File "/openedx/venv/lib/python3.12/site-packages/vine/five.py", line 364, in <module>
1.516     from inspect import formatargspec, getargspec as _getargspec  # noqa
1.516     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.517 ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/pyenv/versions/3.12.2/lib/python3.12/inspect.py). Did you mean: 'formatargvalues'?
```
libsass version needs to updated due to below error
```
1.603   File "/openedx/ecommerce/ecommerce/theming/management/commands/update_assets.py", line 7, in <module>
1.604     import sass
1.604   File "/openedx/venv/lib/python3.12/site-packages/sass.py", line 609, in <module>
1.604     class SassMap(collections.Mapping):
1.604                   ^^^^^^^^^^^^^^^^^^^
1.604 AttributeError: module 'collections' has no attribute 'Mapping'
```

2024-04-15 10:39 UTC, DawoudSheraz commented on requirements/docs.txt
> +# This file is autogenerated by pip-compile with Python 3.9
we should still use Python 3.8 venv to run `make upgrade`, after adding the constraints, to ensure the dependencies work on 3.8 until redwood.

2024-04-15 10:40 UTC, DawoudSheraz commented on ecommerce/extensions/api/v2/urls.py
> +product_router.register(r'products', product_views.ProductViewSet, basename='partner-product')
query lookups are missing here.

2024-04-15 11:01 UTC, Faraz32123 commented on ecommerce/extensions/api/v2/urls.py
> +product_router.register(r'products', product_views.ProductViewSet, basename='partner-product')
OH my bad, i missed those. let me add those.

2024-04-15 13:19 UTC, Faraz32123 commented on requirements/docs.txt
> +# This file is autogenerated by pip-compile with Python 3.9
done.

2024-04-19 09:54 UTC, DawoudSheraz commented on .github/workflows/migrations-mysql8.yml
> +        pip install --no-binary xmlsec==1.3.13 xmlsec==1.3.13
nit: we should add a comment here why this is needed, alongside the link to the issue.

2024-04-19 09:56 UTC, DawoudSheraz commented on requirements/constraints.txt
> +libsass==0.23.0
Please add a comment to specify why are we pinning to 0.23.0 specifically.

2024-04-19 09:58 UTC, DawoudSheraz approved these changes
1-2 small comments to address before merge. CI is green, so 👍🏽

2024-04-19 09:58 UTC, DawoudSheraz commented
@feanil Hi, can you help with a review here? Thanks

2024-04-26 16:15 UTC, andrey-canon commented
Hi @DawoudSheraz, @feanil I will make a review of this next week :D

2024-04-30 21:45 UTC, andrey-canon requested changes
I tested this branch in addition with https://github.com/overhangio/tutor-ecommerce/pull/72 and I didn't make a whole test  but the application loads  and the partner application(That was the unique application whose url definition changed)worked as expected, however,  when I tried some commands from the makefile  I got the following errors

`make requirements`

![image](https://github.com/openedx/ecommerce/assets/36200299/6b3e2796-0bfd-4568-ba93-6ce618d8748c)

looks like the transifex-client dependency is not compatible with python 3.12

`make requirements.tox`  This command is executed by the `make static` command

This makes a downgrade of pip https://github.com/openedx/ecommerce/blob/master/Makefile#L48 and that generates the following error:
![image](https://github.com/openedx/ecommerce/assets/36200299/24b638e9-ff60-4e68-9114-e64dbd0e8d36)

Could you fix that ?

2024-05-03 12:10 UTC, Faraz32123 commented
Hello @andrey-canon, thanks for your time.
I have fixed `transifex-client` compatibility issue with python3.12. The other issue will be fixed in #4153 and to test that PR related to CI, this PR needs to b merged.

2024-05-03 20:56 UTC, andrey-canon approved these changes
Everything looks okay. I tested the Transifex issue, and it was fixed. However, we cannot ensure that 100% of the application is working unless we run tests. To achieve that, we need to rebase this  [pr](https://github.com/openedx/ecommerce/pull/4153) onto this one. That's why I approve this under the premise that there are some current issues, which will be addressed in subsequent PRs.

CC @feanil

2024-05-06 14:58 UTC, feanil approved these changes

2024-05-06 14:58 UTC, merged