ci: add python 3.11 and 3.12 checks
openedx-unsupported/ecommerce pull request #4153
Opened 2024-04-18 09:22 UTC by Danyal-Faheem

# ⛔️ MAIN BRANCH WARNING! 2U EMPLOYEES must make branches against the 2u/main BRANCH

- [x] I have checked the branch to which I would like to merge.

# ⛔️ DEPRECATION WARNING

## Anyone internally merging to this repository is expected to [release and monitor their changes](https://openedx.atlassian.net/wiki/spaces/RS/pages/1835106870/How+to+contribute+to+our+repositories); if you are not able to do this DO NOT MERGE, please coordinate with someone who can to ensure that the changes are released.

## Required Testing
- [ ] Before deploying this change, complete a purchase in the stage environment. 
(^ We can remove that manual check once REV-2624 is done and the corresponding e2e test runs again)

## Description

- AAdded CI checks as part of the [upgrade process](https://github.com/openedx/public-engineering/issues/256) to python 3.11 and python 3.12.
- Also fixes one part of the [downstream issue](https://github.com/overhangio/tutor-ecommerce/issues/78) in tutor-ecommerce.
- Updated `docker-compose` to `docker compose`.
- Added the `PYTHON_ENV` variable to utilize the matrix values to test against multiple python versions.
- Updated the `toxenv` fle to include `py311` and `py312` as well.
- Build docs against python 3.11 and 3.12 as well.

2024-04-29 11:33 UTC, DawoudSheraz commented
@feanil Hi. Can you run the workflows on this PR, please? Thanks

2024-05-02 20:53 UTC, andrey-canon requested changes
Hi @Danyal-Faheem,  firstly, I would like to ask to fix the automatic tests and secondly, these changes are not doing what is supposed to do since this is triggering 3 different actions  but all of them are running with python  3.8 indeed the 3.12 test shouldn't pass since that depends on https://github.com/openedx/ecommerce/pull/4147

2024-05-03 06:03 UTC, Danyal-Faheem commented
Hi @andrey-canon. Thank you for pointing out the problem. The Dockerfile is currently forcing python3.8 in the containers. I'll update the PR to allow different python versions to be installed.

2024-05-09 16:21 UTC, feanil commented
@Danyal-Faheem do we have an update on this PR?  It looks like once we get it working, we'll need to backport this to Redwood as well.

2024-05-10 06:47 UTC, Danyal-Faheem commented
Hi @feanil, we're still working on this PR. It needs some changes in the Dockerfile as well. We will try to get it done as soon as possible so that we can backport it to redwood.

2024-05-28 10:48 UTC, Faraz32123 commented
@Danyal-Faheem and I have tested the changes, there's still some python tests failing under `test-python` workflow.
We have added pylintrc file to ignore some of the pylint warnings. We also had to upgrade some requirements so that CI checks also work with python 3.(8,11,12).
Thats the update for now!

2024-05-31 09:06 UTC, Faraz32123 commented
Hi @feanil, this PR is ready for review. Can you take a look? Thanks.

2024-05-31 09:43 UTC, DawoudSheraz commented on pylintrc_backup
> +[MASTER]
nit: this file wont be needed.

2024-05-31 09:44 UTC, DawoudSheraz commented on requirements/base.in
> +edx-lint
rather than base, this should be in test.in or dev.in.

2024-05-31 10:00 UTC, DawoudSheraz commented on ecommerce/credit/tests/test_views.py
> +            context = {}
A comment here to explain why this is needed would be helpful. Plus, see if this can be improved. There are a bit too many if-elses in the test.

2024-05-31 10:01 UTC, DawoudSheraz commented on requirements/dev.in
> +needle
Why is this needed?

2024-05-31 10:02 UTC, DawoudSheraz commented on requirements/dev.in
> +astroid==3.2.2
Why is astroid needed here? Furthermore, since the version has been constrained in constraints.txt, it wont be needed here.

2024-05-31 10:03 UTC, DawoudSheraz commented on requirements/dev.in
> +edx-lint
it won't be required here. Once it is added to test.in, it should start appearing in dev.txt

2024-05-31 10:04 UTC, Faraz32123 commented on requirements/dev.in
> +astroid==3.2.2
astroid had a conflict with pylint version. So, it needs to be pinned.
I'll remove it from dev.in as it is in contraints.txt.

2024-05-31 10:54 UTC, Faraz32123 commented on requirements/dev.in
> +needle
Its not longer needed, It was added to resolve conlicts. removing it.

2024-05-31 11:03 UTC, Faraz32123 commented on ecommerce/credit/tests/test_views.py
> +            context = {}
adding a comment for now.

2024-05-31 11:04 UTC, Faraz32123 commented on ecommerce/credit/tests/test_views.py
> +            context = {}
Will also look for the alternative for the if-else.

2024-06-05 09:23 UTC, Faraz32123 commented
> Hi @feanil, this PR is ready for review. Can you take a look? Thanks.

Hello @feanil, Hope so you are doing well. A soft reminder for you. So that this [issue](https://github.com/openedx/ecommerce/issues/4161) can be closed. Thanks.

2024-06-05 09:38 UTC, Faraz32123 commented
Hello @andrey-canon, 
Can u also have a look at this PR for me. Thanks.

2024-06-05 15:52 UTC, andrey-canon commented
> Hello @andrey-canon, Can u also have a look at this PR for me. Thanks.

Hi @Faraz32123, sure, no problem, however I cannot do that this week, so I will  review this next one : D

2024-06-11 07:01 UTC, Faraz32123 commented
Hello @feanil and @andrey-canon, I hope you guys are doing well, a reminder for you guys to review this PR for this [issue](https://github.com/openedx/ecommerce/issues/4161) to be closed. Thanks.

2024-06-12 16:06 UTC, andrey-canon requested changes
Most of the changes look good to me. I just left a suggestion related to the test changes because, personally, I don't see the point of implementing two different ways for different Python versions when one of them is compatible with both (I think I didn't test that). If so could you please apply that to all the tests modifications

2024-06-12 16:06 UTC, andrey-canon commented on ecommerce/credit/tests/test_views.py
> +            # assertDictContainsSubset is depreciated in python version>3.9
```suggestion
            # assertDictContainsSubset is deprecated in Python version > 3.9
```
???

2024-06-12 16:06 UTC, andrey-canon commented on ecommerce/credit/tests/test_views.py
> +            # context.response return ContextList object, belwo statements will convert it to dict
```suggestion
            # response.context returns a ContextList object; the below statements will convert it to a dict
```
??

2024-06-12 16:06 UTC, andrey-canon commented on ecommerce/credit/tests/test_views.py
> +            # assertLessEqual method is used instead of depreciated assertDictContainsSubset method
```suggestion
            # assertLessEqual method is used instead of the deprecated assertDictContainsSubset method
```

2024-06-12 16:06 UTC, andrey-canon commented on ecommerce/core/tests/test_models.py
> +            self.assertDictContainsSubset(expected, last_request.headers)
```suggestion
        self.assertLessEqual(expected.items(), last_request.headers.items())
```

2024-06-12 16:06 UTC, andrey-canon commented on ecommerce/enterprise/tests/test_utils.py
> +        if sys.version_info > (3, 9):
same comment as above

2024-06-13 10:21 UTC, Faraz32123 commented
Hello @andrey-canon, thanks for the review. I have updated the code according to the requested changes. Can u look into it again so that we can finalize it.

2024-06-13 14:23 UTC, andrey-canon commented on ecommerce/core/tests/test_models.py
> +import sys
I think you can remove this from all the files

2024-06-17 17:20 UTC, andrey-canon approved these changes
Thanks for applying all the suggested changes 

CC @feanil LGTM

2024-06-20 17:14 UTC, feanil approved these changes

2024-06-20 17:14 UTC, merged

2024-06-20 19:01 UTC, Faraz32123 commented
Hello @feanil, 
Can you also have a look at the backport [PR](https://github.com/openedx/ecommerce/pull/4165) to redwood and merge it.
Thanks.