[WIP] Joyce zhu/error receipt endpoints
openedx-unsupported/ecommerce pull request #849
Opened 2016-07-07 20:13 UTC by JoyceZhu

@mjfrey , current state of the new receipt endpoint

2016-08-11 16:32 UTC, mjfrey commented on ecommerce/settings/_oscar.py
> +PAYMENT_SUPPORT_EMAIL = 'billing@example.com'
I thought we moved this to the site configuration?  If not we should.

2016-08-11 16:33 UTC, mjfrey commented on ecommerce/settings/test.py
> +PAYMENT_SUPPORT_EMAIL = 'billing@example.com'
same here.

2016-08-11 16:34 UTC, mjfrey commented on ecommerce/core/migrations/0018_otto_receipt_page_switch.py
> +    Switch.objects.get_or_create(name='otto_receipt_page', defaults={'active': True})
we probably want this to default to off.

2016-08-11 16:35 UTC, mjfrey commented on ecommerce/extensions/api/serializers.py
> +            vouchers = [voucher for voucher in obj.basket.vouchers.all()]
doesn't obj.basket.vouchers.all() return all the vouchers?  why the for?

2016-08-11 16:38 UTC, mjfrey commented on ecommerce/extensions/api/serializers.py
> +        discounts = obj.discounts.all()
discount = obj.discounts.all()[0]

then 
discount.amount

2016-08-11 16:43 UTC, mjfrey commented on ecommerce/extensions/checkout/tests/test_views.py
> +    def login(self):
just move this to the setup.  No need to call this for every test as it is already in setUp.  It will be called before every test.

2016-08-11 18:02 UTC, JoyceZhu commented on ecommerce/settings/_oscar.py
> +PAYMENT_SUPPORT_EMAIL = 'billing@example.com'
Yes, this is part of the site config now. Looks like I accidentally kept this while resolving a rebase conflict; I'll remove it.

2016-08-11 19:15 UTC, mjfrey commented
@vkaracic please take a look.

2016-08-11 19:16 UTC, mjfrey commented
@JoyceZhu can you add a screenshot of the new receipt page.

2016-08-11 19:17 UTC, JoyceZhu commented
<img width="1266" alt="screen shot 2016-08-03 at 12 33 55 pm" src="https://cloud.githubusercontent.com/assets/6251669/17601549/b2488d18-5fd6-11e6-89e1-8ab02bfa5082.png">

2016-08-16 11:39 UTC, mjfrey commented
@marjev

2016-09-28 19:31 UTC, MatthewPiatetsky requested changes

2016-09-28 19:31 UTC, MatthewPiatetsky commented on ecommerce/static/js/views/receipt_view.js
> +            AnalyticsUtils.trackingModel.trigger('segment:track', 'Completed Order', {
Hi @JoyceZhu ,
Could you rename this event to Completed Purchase?
The current name in LMS was causing analytics issues.
See this PR
https://github.com/edx/edx-platform/pull/13596
and this ticket
https://openedx.atlassian.net/browse/ECOM-5820
for details.

2016-10-05 08:27 UTC, marjev commented on ecommerce/static/js/views/receipt_view.js
> +            AnalyticsUtils.trackingModel.trigger('segment:track', 'Completed Order', {
Hi @MatthewPiatetsky! I took over this work. I'll do what you suggested. Let me know if you require any additional changes. Thanks!

2016-10-05 14:28 UTC, marjev commented on ecommerce/static/js/views/receipt_view.js
> +            AnalyticsUtils.trackingModel.trigger('segment:track', 'Completed Order', {
Comment addressed.

2016-10-05 14:45 UTC, vkaracic reviewed
I haven't went through the whole code. I see you have pushed some commits so some of my comments could've already been addressed.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/core/migrations/0019_otto_receipt_page_switch.py
> +    Switch = apps.get_model('waffle', 'Switch')
This can be moved out to global namespace so the remove method doesn't have to import it all over again.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/api/serializers.py
> +    shipping_address_format = '{city}, {state} {postcode}'
I doubt that this needs to be a class variable.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/api/serializers.py
> +            return [field for field in relevant_address_fields if field]
Why not return the shipping address as a JSON object?

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
> +        response = self.client.get(self.path, {'username': self.user.username})
Is the dictionary necessary?

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/checkout/signals.py
> +
It's probably best to get the ecommerce and LMS URLs directly from the site configuration.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/checkout/tests/test_signals.py
> +        self.credit_provider_name = 'Hogwarts'
I don't see why moving these was necessary.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/checkout/tests/test_views.py
> +    def test_redirect_to_lms_receipt(self):
This and the above test can be combined with ddt.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/checkout/views.py
> +                url = get_lms_url(receipt_path)
Again, probably best to get the ecomm and LMS URLs from site configuration.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/checkout/views.py
> +            context.update({
I believe context updates should be managed in the `get_context_data` method.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/checkout/views.py
> +        ).format(payment_support_link=payment_support_link)
These can be directly added below, no need for declaring variables.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/fulfillment/modules.py
> +            receipt_page_url = get_lms_url('{}?orderNum={}'.format('/commerce/checkout/receipt', order.number))
URLs from site configuration, again.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +    def test_switch_disabled_lms_url(self):
These two tests can be combined with ddt.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/settings/test.py
> +PLATFORM_NAME = 'My Platform'
Is this necessary for something?

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/routers/receipt_router.js
> +            // Base/root path of the app
Unnecessary comment.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/routers/receipt_router.js
> +            showReceiptPage: function() {
The `order` parameter should be passed through to the view, instead of retrieving it from the URL as it's being done now.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/receipt_view_spec.js
> +                expect(view.$('.value-amount').text()).toContain('5.00');
Instead of hard coding these values, perhaps using ``orderResponseData.number`` and ``orderResponseData.total_excl_tax`` might be better.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/receipt_view_spec.js
> +                var order_without_provider = {
These values are more or less all the same as the ones in the ``orderResponseData`` variable in the ``beforeEach`` method. it would be better to reuse those and exclude values that need to be excluded instead of copying it all.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/receipt_view_spec.js
> +            it('renders voucher code and discount information', function() {
Since nothing is changing in between these tests, they could probably be combined into one.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/receipt_view_spec.js
> +                //$.ajax.reset();
These, including the console log, seem unnecessary.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/receipt_view_spec.js
> +               var malformedOrder = {
Again, these values could be reused.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/test/specs/views/receipt_view_spec.js
> +               var order_without_provider = {
Again, reusing is possible.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/utils/analytics_utils.js
> +                console.log(JSON.stringify(this.trackingModel));
Remove.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/utils/analytics_utils.js
> +                var self = this;
``this`` can be passed along to the ``.each`` function.

2016-10-05 14:45 UTC, vkaracic commented on ecommerce/static/js/views/receipt_view.js
> +            }).retry({times: 5, timeout: 2000, statusCodes: [404]});
Not sure if and why these require retries.

2016-10-07 07:21 UTC, marjev commented on ecommerce/core/migrations/0019_otto_receipt_page_switch.py
> +    Switch = apps.get_model('waffle', 'Switch')
`apps` is not available outside the scope of the methods.

2016-10-07 09:49 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_orders.py
> +        response = self.client.get(self.path, {'username': self.user.username})
Yes, it's filtering by username.

2016-10-07 12:46 UTC, marjev commented on ecommerce/settings/test.py
> +PLATFORM_NAME = 'My Platform'
Nope.

2016-12-16 14:32 UTC, closed without merging