Refactor create coupon
openedx-unsupported/ecommerce pull request #911
Opened 2016-08-25 12:29 UTC by marjev

@mjfrey, @vkaracic, @iivic: Here's the 3rd cleanup PR, so please take a look when you get the time. I've refactored the Coupon API code to release the tension that was building up there.

Since the Coupon UI only allows the end user to assign a single Category to a Coupon, I've cleaned up Backend/API code so that it reflects that use case. Otherwise, we're doing additional work in Backbone instead of simply reading the value returned by Coupon API endpoint.

2016-08-25 12:29 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=911

2016-09-22 07:18 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        response_data = self.client.post(COUPONS_LINK, json.dumps(self.data), 'application/json')
Would it be wise to change all these with ``get_response_json``?

2016-09-22 07:19 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        response_data = self.get_response_json(
Can this fit in one line?

2016-09-22 07:21 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/coupons.py
> +        return Category.objects.get(name=category_data['name'])
Is it necessary to abstract this line?

2016-09-22 07:27 UTC, vkaracic commented on ecommerce/extensions/catalogue/utils.py
> +        A coupon product object.
Capital P for consistency.

2016-09-22 07:29 UTC, vkaracic commented on ecommerce/extensions/catalogue/utils.py
> +            'price_currency': 'USD',
Use the currency settings value here instead of hardcoding it.

2016-09-22 07:43 UTC, vkaracic requested changes
I'm finished with my first pass and left a few comments and questions.

2016-09-27 09:59 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +            'end_datetime': '2020-01-01',
Should we use dates relative to today +1 day if it needs to be in the future and -1 day for the past?

2016-09-27 10:01 UTC, iivic reviewed
One question before I give you a thumbs up.

2016-09-27 10:01 UTC, iivic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +            'start_datetime': '2015-01-01',
Same like comment https://github.com/edx/ecommerce/pull/911/files#diff-3bdba75be46de6780d19faac1f58ded3R231

2016-09-29 12:03 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +        response_data = self.client.post(COUPONS_LINK, json.dumps(self.data), 'application/json')
`get_response_json` returns response data and I'm testing the status code here.

I'll have to clean up tests after the entire Coupons API endpoint cleanup is done. That will be a separate PR and only test related.

2016-09-30 07:50 UTC, marjev commented
@vkaracic, @iivic I've addressed the comments. Could you take another look?

2016-09-30 07:54 UTC, vkaracic commented on ecommerce/extensions/api/v2/tests/views/test_coupons.py
> +            'category': {'name': self.category.name},
You should probably alphabetize this before @iivic sees it! :smile:

2016-09-30 07:57 UTC, iivic commented on ecommerce/coupons/tests/mixins.py
> +            end_datetime=datetime.date(2020, 1, 1),
Why is this date static but you changed others?

2016-09-30 07:57 UTC, iivic commented on ecommerce/coupons/tests/mixins.py
> +            start_datetime=datetime.date(2015, 1, 1),
Why is this date static but you changed others?

2016-09-30 08:13 UTC, vkaracic approved these changes
Few nits, otherwise LGTM.

2016-09-30 08:13 UTC, vkaracic commented on ecommerce/extensions/catalogue/tests/test_utils.py
> +            end_datetime='2020-1-1',
Add a ``now + 1 day`` here too.

2016-09-30 08:13 UTC, vkaracic commented on ecommerce/extensions/catalogue/utils.py
> +        defaults={
Alphabetize.

2016-09-30 08:52 UTC, marjev commented
@vkaracic, @iivic Let's leave the test cleanup for a separate PR. There's a lot of work that needs to be done there. I'll leave that for a final PR once other issues in the Coupons app are resolved.

What you could try is checking out this branch and test it locally before approving this.
Any Coupon Category use-cases you're aware of should be tested. Let's try and catch any issues in dev instead of waiting for this to be tested on sandbox/stage.

2016-09-30 08:52 UTC, marjev commented on ecommerce/extensions/catalogue/utils.py
> +        defaults={
Done.

2016-09-30 09:00 UTC, iivic approved these changes

2016-09-30 11:29 UTC, merged