[WIP][SOL-2058] Get provider data from LMS
openedx-unsupported/ecommerce pull request #935
Opened 2016-09-09 13:52 UTC by marjev

2016-09-09 13:52 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=935

2016-09-14 12:58 UTC, marjev commented
@mjfrey Here's the PR for getting provider data from the LMS API. Can you please review this?

@vkaracic this PR modifies already existing method for getting provider data because the new receipt page will rely on this data. We will use provider data in Django view that loads the template managed by Backbone. Please take a look as the 2nd reviewer.

2016-09-15 12:15 UTC, vkaracic commented on ecommerce/extensions/checkout/tests/test_signals.py
> -                credit_provider='Hogwarts',
Awww :cry:

2016-09-15 12:18 UTC, vkaracic commented on ecommerce/extensions/checkout/utils.py
> +    except SlumberHttpBaseException:
Could these exceptions be grouped together, since the message is pretty much the same?

2016-09-15 12:19 UTC, vkaracic commented on ecommerce/extensions/checkout/tests/test_signals.py
>              content_type="application/json"
Nit: single quotes.

2016-09-15 12:22 UTC, vkaracic commented on ecommerce/extensions/checkout/utils.py
> +            get_lms_url('api/credit/v1/'),
https://github.com/edx/ecommerce/blob/master/ecommerce/core/url_utils.py#L11-L13 so there's that.
Perhaps send the request and construct the URL with: https://github.com/edx/ecommerce/blob/master/ecommerce/core/models.py#L183

2016-09-15 12:23 UTC, vkaracic reviewed
I've finished my first pass.

2016-09-16 09:44 UTC, marjev commented
@vkaracic Comments have been addressed.

2016-09-16 12:58 UTC, vkaracic approved these changes
LGTM

2016-09-26 12:48 UTC, marjev commented
I would like someone from @edx/ecommerce to review this as well.

I made a change to the method that calls LMS API endpoint to get the provider data. It's used only on a couple of places and I think I applied the changes correctly.

The reason why I need the provider data is because the new receipt page that's been implemented in #849 requires that. The plan is to have a method for fetching Provider Data and use it to get the data in the Receipt Page Django View to provide that data directly.

Thanks!

2016-09-26 13:03 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +                request = threadlocals.get_current_request()
Please stop using `threadlocals`. Get the site from the order ALWAYS to avoid brand leakage. Pass the user to signal call, and you don't need a request.

2016-09-26 13:04 UTC, clintonb commented on ecommerce/extensions/checkout/utils.py
>      """Get the provider information for provider id provider.
Huh? What information are you retrieving?

2016-09-26 13:04 UTC, clintonb commented on ecommerce/extensions/checkout/utils.py
> +def get_provider_data(access_token, provider_id, site_configuration):
`get_credit_provider_details`

2016-09-26 13:08 UTC, clintonb commented on ecommerce/extensions/checkout/utils.py
> +        access_token(str): JWT access token
Add spaces after the variable names.

2016-09-26 13:09 UTC, clintonb commented on ecommerce/extensions/checkout/utils.py
> +            ex,
You don't need to pass the exception when using `logger.exception`.

2016-09-26 13:13 UTC, clintonb commented on ecommerce/extensions/checkout/utils.py
>          provider_id(str): Identifier for the provider
credit_provider_id

2016-09-26 13:20 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> -                credit_provider='Hogwarts',
Why was this changed? We occasionally use MIT/Harvard in tests because they are founding partners. ASU is not. If our partnership with them ever dissolves, we may have to remove them entirely from our code base. Avoid this problem now, and use a fake university name (e.g. ACME).

2016-09-26 13:21 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +            body='{"display_name": "Arizona State University"}',
Use a variable that can be shared below.

2016-09-26 13:21 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_utils.py
> +            self.site.siteconfiguration.build_lms_url('api/credit/v1/providers/ASU/'),
Use a variable for the provider ID.

2016-09-26 13:22 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_utils.py
>              body='{"display_name": "Arizona State University"}',
Use a variable for the display name.

2016-09-26 13:22 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_utils.py
> +            access_token=self.access_token,
You can pass all of these as `args` instead of `kwargs`.

2016-09-26 13:24 UTC, clintonb requested changes
`threadlocals` needs to go away. The current usage (on master) is "okay"; but, we should not be expanding its usage.

2016-09-27 10:08 UTC, marjev commented
@clintonb Thanks for the review! Please take another look at my PR.

2016-09-27 13:27 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +                    access_token=order.user.access_token,
This could be problematic due to the fact that the email may be sent (in the case of a re-send) after the user's access token has expired. You should use `order.site.siteconfiguration.access_token`. See https://github.com/edx/ecommerce/blob/master/ecommerce/core/models.py#L223-L250.

2016-09-27 13:27 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +        order.site = self.site
This should be set on the basket. `BasketFactory(site=self.site)` should work. If not, use `basket.site = self.site`.

2016-09-27 13:27 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +        order = factories.create_order(number=1, basket=basket, user=self.user)
Unset `number`, and one will be generated for you.

2016-09-27 13:27 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_utils.py
> +            self.site.siteconfiguration.build_lms_url('api/credit/v1/providers/ASU/'),
The comments in this file still need to be addressed.

2016-09-28 11:08 UTC, marjev commented
@clintonb I think I addressed all the comments you left yesterday + the ones left on the `test_utils.py`. Could you please take another look?

2016-09-28 12:35 UTC, clintonb approved these changes
Remember to squash commits before merging

2016-09-28 12:35 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_signals.py
> +                    'Failed to send credit receipt notification. Credit seat product [{}] has not provider.'.format(
Nit: s/not/no

2016-09-29 07:14 UTC, merged