Credit  checkout via offer landing page.
openedx-unsupported/ecommerce pull request #950
Opened 2016-09-22 15:25 UTC by vkaracic

Dependencies:
https://github.com/edx/ecommerce/pull/946
https://github.com/edx/ecommerce/pull/947

2016-09-22 15:25 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=950

2016-09-26 11:37 UTC, vkaracic commented
@iivic @marjev @mjfrey ready for review. Review only the last commit, the others are cherry-picked in.

2016-09-26 13:38 UTC, marjev commented on ecommerce/extensions/api/v2/tests/views/test_vouchers.py
> +    # added to the test class below.
Is this note still necessary if the segmentation fault issue has been resolved?

2016-09-26 14:08 UTC, mjfrey commented on ecommerce/core/models.py
> +    def is_eligible(self, course_key):
is_eligible_for_credit

2016-09-26 14:09 UTC, mjfrey commented on ecommerce/core/tests/test_models.py
> +    def prepare_eligibility_info(self, eligible=True):
prepare_credit_eligibility_info

2016-09-26 14:10 UTC, mjfrey commented on ecommerce/coupons/decorators.py
> +            voucher = Voucher.objects.get(code=code)
We are now going to call this twice for an offer landing page. Once for the decorator and then for the landing page itself.  Can we cache this?

2016-09-26 14:18 UTC, mjfrey commented on ecommerce/credit/views.py
> +                if discount_type == 'Percentage':
Don't we already do this in the basket view?  Can we factor it out into a util method?

2016-09-26 14:21 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/vouchers.py
> +    def retrieve_course_objects(self, results):
This is not very descriptive.  You return products and stock records not courses.

2016-09-26 14:54 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/vouchers.py
> +    def retrieve_course_objects(self, results):
Can you suggest one?

2016-09-26 15:04 UTC, marjev approved these changes

2016-09-26 16:53 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/vouchers.py
> +            except Course.DoesNotExist:  # pragma: no cover
Can't test this without triggering a SEGFAULT error. Also I don't know how this will ever be triggered?

2016-09-27 09:29 UTC, iivic requested changes
A few things to change/answer.

2016-09-27 09:29 UTC, iivic commented on ecommerce/static/js/pages/credit_checkout.js
> +                        this.$el.find('span.total-price').text(data.price);
Use shorthand for $el.find.

2016-09-27 09:29 UTC, iivic commented on ecommerce/static/sass/partials/views/_credit.scss
> +    border-bottom: 1px solid #A8A8A8;
Use a variable for this color.

2016-09-27 09:29 UTC, iivic commented on ecommerce/tests/mixins.py
> +            'deadline': '2030-09-02T07:51:38Z'
Should we use today + 1 day if the date is in the future?

2016-09-27 12:05 UTC, vkaracic commented on ecommerce/static/sass/partials/views/_credit.scss
> +    border-bottom: 1px solid #A8A8A8;
Why?

2016-09-27 12:05 UTC, vkaracic commented on ecommerce/tests/mixins.py
> +            'deadline': '2030-09-02T07:51:38Z'
Unnecessary over-engineering in my opinion.

2016-09-27 12:23 UTC, iivic commented on ecommerce/tests/mixins.py
> +            'deadline': '2030-09-02T07:51:38Z'
Tests using this data will fail after this date. I would change it just in case ...

2016-09-27 12:26 UTC, iivic commented on ecommerce/static/sass/partials/views/_credit.scss
> +    border-bottom: 1px solid #A8A8A8;
I remember it was a best practice instruction but can't remember why.

2016-09-27 12:46 UTC, vkaracic commented
Comments addressed!

2016-09-27 12:50 UTC, iivic approved these changes

2016-09-27 13:52 UTC, mjfrey commented
👍

2016-09-28 14:39 UTC, merged