Display error message when no offers exist for a coupon.
openedx-unsupported/ecommerce pull request #952
Opened 2016-09-28 11:13 UTC by vkaracic

The offer landing page for a dynamic coupon that has no offers (no seats to display) would display an empty page. This PR contains changes that make the offer landing page display an error message instead of the empty page.
![screenshot from 2016-09-28 12-39-47](https://cloud.githubusercontent.com/assets/2808092/18910515/abf0c666-8578-11e6-9fe3-38b08ef24ad2.png)

https://openedx.atlassian.net/browse/SOL-2090

2016-09-28 11:13 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=952

2016-09-28 11:28 UTC, iivic commented on ecommerce/static/js/views/offer_view.js
> +                if (this.collection.empty) {
Why can't you just check if length == 0 since the fetch isn't async? Empty looks unnecessary to me.

2016-09-28 11:57 UTC, vkaracic commented on ecommerce/static/js/views/offer_view.js
> +                if (this.collection.empty) {
I've returned the async because we probably want to do this asynchronously.

2016-09-28 12:12 UTC, iivic approved these changes

2016-09-29 07:28 UTC, marjev requested changes

2016-09-29 07:28 UTC, marjev commented on ecommerce/static/js/collections/offer_collection.js
> +                this.empty = false;
Redundant.

2016-09-29 07:28 UTC, marjev commented on ecommerce/static/js/collections/offer_collection.js
> +                    return false;
Do you need to return false?

2016-09-29 07:28 UTC, marjev commented on ecommerce/static/js/test/specs/collections/offer_collection_spec.js
> +            it('should set it is empty when no results are fetched', function() {
what is `it` in the test description?

2016-09-29 07:28 UTC, marjev commented on ecommerce/static/js/views/offer_view.js
> +            emptyOffer: function() {
Functions/methods names should usually describe what's been done. I suggest renaming this to `showEmptyOfferErrorMessage` or something similar.

2016-09-29 07:42 UTC, vkaracic commented on ecommerce/static/js/collections/offer_collection.js
> +                    return false;
Yes.

2016-09-29 07:49 UTC, vkaracic commented
Comments addressed!

2016-09-29 07:53 UTC, marjev commented on ecommerce/static/js/collections/offer_collection.js
> +                    return false;
Can't you return the response.results? I thought you're only using `this.empty` flag.

2016-09-29 07:54 UTC, vkaracic commented on ecommerce/static/js/collections/offer_collection.js
> +                    return false;
Displays an empty page without this return instead of the error message.

2016-09-29 10:19 UTC, marjev commented on ecommerce/static/js/collections/offer_collection.js
> +                    return false;
Can you double check that? If I remove `return false;` locally, it works.

2016-09-29 10:37 UTC, marjev approved these changes
LGTM

2016-09-29 11:27 UTC, mjfrey commented
👍

2016-09-29 11:48 UTC, merged