[WIP][SOL-2042] Change the email validation in offer models to disregard sub domains.
openedx-unsupported/ecommerce pull request #961
Opened 2016-10-03 12:18 UTC by vkaracic

https://openedx.atlassian.net/browse/SOL-2042

2016-10-03 12:18 UTC, gsong commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=961

2016-10-03 12:19 UTC, vkaracic commented
@gsong who are you and what have you done to the edX PR bot? :)

2016-10-03 12:28 UTC, gsong commented
@vkaracic I'm part of the OS team at edX. I'm doing more work on the integration between JIRA and GitHub right now, and apparently I'm the bot for now. 😜

2016-10-04 11:53 UTC, marjev requested changes

2016-10-04 11:53 UTC, marjev commented on ecommerce/extensions/offer/models.py
> +
Do we want more standardized docstring here, with a short description, list of arguments and return value description.

2016-10-04 11:53 UTC, marjev commented on ecommerce/extensions/offer/models.py
> +        return True
Did you try using regex here? Something like `<any_set_of_valid_username_characters>@<any_set_of_valid_domain_characters><domain>`.
If a match is found return True, otherwise check for another domain. This way, you won't have to do all this splitting and joining, which is very confusing.

2016-10-05 09:42 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +        return True
Involving regex, if anything, adds to the complexity. I'll try with different variable names and/or comments.

2016-10-05 10:47 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +        return True
I've made some changes, see if it makes more sense now.

2016-10-05 11:40 UTC, marjev commented on ecommerce/extensions/offer/models.py
> +        return True
Try replacing
```
# Example user email: username@sub.example.com
full_user_email_domain = email.split('@')[1]  # 'sub.example.com' part
second_and_top_level_domain = full_user_email_domain.split('.')[-2:]
user_email_domain = '.'.join(second_and_top_level_domain)  # 'example.com' part

for domain in self.email_domains.split(','):
    # If the domain contains sub domain(s)
    if len(domain.split('.')) > 2:
        if full_user_email_domain == domain:
            return True
        else:
            if domain == user_email_domain:
                return True
return False
```
with this:
```
for domain in self.email_domains.split(','):
    pattern=r'(?P<username>\w+)@(?P<subdomain>\w+\.)*{domain}'.format(domain=domain)
    match = re.match(pattern, email)
    if match and match.group(0) == email:
        return True
return False
```

I didn't do a lot of testing but it seems to work.

2016-10-05 12:54 UTC, vkaracic commented on ecommerce/extensions/offer/models.py
> +        return True
That works and is much better than I had. Thanks!

2016-10-05 13:25 UTC, marjev approved these changes
LGTM

2016-10-12 14:01 UTC, iivic approved these changes

2016-10-12 14:03 UTC, merged