[SOL-2073] Change the redirect after enrollment code redemption to the receipt page.
openedx-unsupported/ecommerce pull request #963
Opened 2016-10-03 16:59 UTC by vkaracic

So far when a user clicks 'Enroll' on an enrollment code's offer landing page, the user gets redirect to the dashboard. This PR changes that part of the code so that when a user clicks on that button it gets redirected to the receipt page.

https://openedx.atlassian.net/browse/SOL-2073

2016-10-03 16:59 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=963&repo=edx%2Fecommerce

2016-12-20 15:05 UTC, mjfrey requested changes

2016-12-20 15:05 UTC, mjfrey commented on ecommerce/coupons/views.py
> +            if order.status == 'Complete':
This won't work with async fulfillment.  The order status will never be 'Complete' this fast.  Need a way from the receipt page or some view to wait for fulfillment to complete.

2016-12-21 09:42 UTC, vkaracic commented on ecommerce/coupons/views.py
> +            if order.status == 'Complete':
What do you suggest?

2016-12-21 10:02 UTC, iivic requested changes

2016-12-21 10:02 UTC, iivic commented on ecommerce/coupons/views.py
> +                redirect_path = reverse('checkout:error')
This can be rewritten like
```
if order.status == 'Complete':
    return HttpResponseRedirect(get_receipt_page_url(self.request.site.siteconfiguration, order.number))
return HttpResponseRedirect(reverse('checkout:error'))
```

2016-12-21 10:02 UTC, iivic commented on ecommerce/coupons/views.py
>          else:
This else can be removed.

2017-01-11 12:14 UTC, vkaracic commented
Here's how I intended it:
![out-5](https://cloud.githubusercontent.com/assets/2808092/21848133/d3c90944-d7ff-11e6-8cbf-fcaaa465873d.gif)

2017-01-12 09:16 UTC, vkaracic commented
@iivic @marjev @mjfrey comments addressed, please take another look.

2017-01-12 09:28 UTC, iivic commented on ecommerce/coupons/views.py
> +                time.sleep(2)  # pragma: no cover
Why 2 seconds?

2017-01-12 09:39 UTC, iivic commented on ecommerce/static/js/views/offer_view.js
> +                'click #RedeemEnrollment': 'disableReedemEnrollmentBtn'
This is not part of this PR but for a multi-course coupon on offer landing page there will be multiple links with the id="RedeemEnrollment" or "PurchaseCredit". The id should be unique. This is something we should take care of ....

2017-01-12 11:18 UTC, marjev requested changes

2017-01-12 11:18 UTC, marjev commented on ecommerce/coupons/views.py
> +                    break
why not `return HttpResponseRedirect(reverse('checkout:error'))`?

2017-01-12 11:18 UTC, marjev commented on ecommerce/coupons/views.py
> +                time.sleep(2)  # pragma: no cover
Are the 2 seconds a constant somewhere? It seems to me like this might change so we'll have to do it here as well. Using and importing the constant here might prevent potential future headaches.

2017-01-12 11:18 UTC, marjev commented on ecommerce/templates/oscar/checkout/error.html
>  {% endblock navbar %}
nitpick: not your doing, but can we remove the navbar part from the endblock as well.

2017-01-12 11:56 UTC, vkaracic commented on ecommerce/coupons/views.py
> +                time.sleep(2)  # pragma: no cover
The two seconds are arbitrary, we can add any value here, 2 seems sufficient.
You mean saving this as a constant in the settings? When will this change?

2017-01-12 12:28 UTC, marjev commented on ecommerce/coupons/views.py
> +                time.sleep(2)  # pragma: no cover
If it's related to the business logic of a model, it makes more sense to me to place it under that model where the 2 seconds rule is enforced.
Also, as you said, 2 seconds are arbitrary, which means it can change at any time, e. g. when a problem occurs. When that happens, hypothetically speaking, we should minimize the work that needs to be done by DRY-ing this.

2017-01-12 12:37 UTC, marjev approved these changes

2017-01-12 12:38 UTC, vkaracic commented
@clintonb can you please take a look? Specifically at the way I've implemented the waiting for the order to fulfill?

2017-01-12 13:19 UTC, clintonb commented on ecommerce/core/models.py
> +        return self.build_lms_url('/api/enrollment/v1/enrollment')
Why the change? We should always point to the API root, not a specific resource.

2017-01-12 13:19 UTC, clintonb commented on ecommerce/extensions/order/models.py
> +        get_latest_by = 'date_placed'
I believe this requires a migration.

2017-01-13 12:14 UTC, vkaracic commented
Comments addressed!

2017-01-13 12:15 UTC, iivic approved these changes

2017-01-13 13:21 UTC, clintonb approved these changes

2017-01-13 16:26 UTC, mjfrey approved these changes

2017-01-16 08:41 UTC, merged