Update Enrollment failed message with status code
openedx-unsupported/ecommerce pull request #964
Opened 2016-10-05 10:28 UTC by ahsan-ul-haq

2016-10-05 15:37 UTC, rlucioni commented
@ahsan-ul-haq please include a ticket number (i.e., ECOM-4763) in your commit message.

2016-10-07 12:45 UTC, ahsan-ul-haq commented
@rlucioni please review

2016-10-07 14:17 UTC, rlucioni requested changes
@ahsan-ul-haq please include a JIRA ticket number in your _Git commit_ message. This is not the same as the first comment on a GitHub PR.

2016-10-07 14:17 UTC, rlucioni commented on ecommerce/extensions/fulfillment/modules.py
> +                        "Fulfilling line [%d] of order [%s] failed with status code %d due to a server-side error: %s",
The error message shouldn't assume a server-side error (the error could be on the client, a 400). Please change this to: `Fulfillment of line [%d] on order [%s] failed with status code [%d]: %s`

2016-10-07 14:25 UTC, ahsan-ul-haq commented
@rlucioni made the changes suggested

2016-10-07 14:26 UTC, schenedx approved these changes
👍

2016-10-07 14:28 UTC, rlucioni approved these changes
Approved once you squash and update your commit message.

2016-10-07 19:11 UTC, merged