Updated i18n-tool version, .travis.yml and Makefile files changed
openedx-unsupported/ecommerce pull request #966
Opened 2016-10-07 09:01 UTC by iivic

@clintonb  Are those the required changes?

2016-10-07 09:01 UTC, edx-webhook commented
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=966&repo=edx%2Fecommerce

2016-10-07 12:07 UTC, clintonb requested changes

2016-10-07 12:07 UTC, clintonb commented on Makefile
> +
Add a new target, `validate_translations`, that calls `fake_translations` followed by `changed_translations`.

2016-10-07 12:07 UTC, clintonb commented on .travis.yml
> +    # Check if translation files are up-to-date
Call this before asset compilation. We want to fail on the easy stuff early so that devs can quickly get a fix pushed.

2016-10-07 12:07 UTC, clintonb commented on Makefile
> +changed_translations:
How about `detect_missing_source_translations`, or something that better reflects what we want to achieve?
Also, add a comment mentioning the need to run the extract command first.

2016-10-10 13:31 UTC, iivic commented on .travis.yml
> +    - make detect_changed_source_translations
Is this command name more descriptive? @clintonb

2016-10-10 13:37 UTC, iivic commented
Is detect_changed_source_translations more descriptive? 
I also updated en source files and committed the eo dummy files but I'm not sure if I should have done that and when those files need to be committed.

2016-10-10 14:16 UTC, clintonb approved these changes

2016-10-10 14:18 UTC, clintonb commented
Looks good. I don't think we have rules for the fake translations. However, it makes sense to include them so that we can test for missing translations in non-local environments. Also, remembers to squash commits before merging.

2016-10-11 08:30 UTC, iivic commented
I added `pip install edx-i18n-tools` to the .travis.yml file so that the tests pass. Any objections?

2016-10-11 12:11 UTC, clintonb commented
Big objection: https://github.com/edx/ecommerce/blob/master/requirements/local.txt#L9. 

Please ensure you are testing locally by setting up a fresh virtualenv for each project, and running `make requirements`.

2016-10-11 14:49 UTC, nedbat commented on ecommerce/conf/locale/en/LC_MESSAGES/django.po
> +#: ecommerce/core/models.py:38
It's annoying that the line numbers here change so often and clutter the diffs.  In i18n-tools, the line numbers are removed during the "generate" step which merges .po files together.  You don't need merge, so you aren't getting the line number scrubbing.  Maybe we should change where that happens (to extract) so that other repos get the benefit.

2016-10-11 14:57 UTC, iivic commented
@clintonb  Travis doesn't install edx-i18n-tools because the requirements from local.txt file are not installed. Travis calls `make requirements.js` perhaps `make requirements` should be called instead of 
`pip install -r requirements/test.txt
  pip install -r requirements/docs.txt
  make requirements.js`
because it will install all of that and i18n requirements or should I just move the i18n tools to another requirements file?

2016-10-11 15:04 UTC, iivic commented on ecommerce/conf/locale/en/LC_MESSAGES/django.po
> +#: ecommerce/core/models.py:38
I'm not sure what you're trying to say and what needs to be done here.

2016-10-11 15:18 UTC, clintonb commented on ecommerce/conf/locale/en/LC_MESSAGES/django.po
> +#: ecommerce/core/models.py:38
Nothing needs to be done now. What @nedbat mentioned is a feature request/enhancement that is out-of-scope for your work @iivic.

2016-10-11 15:19 UTC, clintonb commented
@iivic yes, please update `.travis.yml` to run `make requirements`. I'm not sure what that wasn't the case before.

2016-10-12 09:59 UTC, iivic commented
Please take a quick look just to make sure I didn't forget something.

2016-10-12 12:59 UTC, clintonb commented on .travis.yml
> +    - make detect_changed_source_translations
`make validate_translations`

2016-10-12 13:51 UTC, iivic commented
Updated.

2016-10-12 14:20 UTC, clintonb approved these changes

2016-10-12 15:03 UTC, merged