[WIP] Add UTM tracking for order referrals
openedx-unsupported/ecommerce pull request #968
Opened 2016-10-07 16:22 UTC by bderusha

WIP

2016-10-11 13:56 UTC, bderusha commented
@edx/ecommerce Please review

2016-10-11 14:05 UTC, schenedx commented on ecommerce/extensions/basket/tests/test_utils.py
> +        # test affiliate id from cookie saved in referral
I feel this is a different test case. Why put these scenarios into a single test case?

2016-10-11 14:08 UTC, schenedx commented on ecommerce/extensions/basket/utils.py
> +        try:
This looks a bit weird. Maybe it's the first time I am seeing it. That said, maybe we can wrap this second try into a new function like `_get_referral_of_basket()`?

2016-10-11 14:09 UTC, schenedx commented on ecommerce/referrals/models.py
> +    site = models.ForeignKey('sites.Site', null=False, blank=False)
Does this mean the referral is now multi-tenancy ready?

2016-10-11 14:10 UTC, schenedx approved these changes
All minor comments. 👍

2016-10-11 14:16 UTC, bderusha commented on ecommerce/extensions/basket/tests/test_utils.py
> +        # test affiliate id from cookie saved in referral
Because each subsequent test would involve doing the all of the steps before it. 

create cookie data
assert cookie data saved

create cookie data
assert cookie data saved
update cookie
assert new data saved

create cookie data
assert cookie data saved
delete cookie
assert cookie data deleted


It seemed more straightforward to test the entire lifecycle in a single test.

2016-10-11 14:17 UTC, bderusha commented on ecommerce/referrals/models.py
> +    site = models.ForeignKey('sites.Site', null=False, blank=False)
For ecommerce, yes.  For LMS it is not yet

2016-10-11 14:24 UTC, bderusha commented on ecommerce/extensions/basket/utils.py
> +        try:
Agreed that it looks weird.  Will update.

2016-10-11 14:53 UTC, rlucioni requested changes

2016-10-11 14:53 UTC, rlucioni commented on ecommerce/core/models.py
> +        null=True,
From the [Django docs](https://docs.djangoproject.com/en/1.10/ref/models/fields/#null):
> Avoid using null on string-based fields such as CharField and TextField because empty string values will always be stored as empty strings, not as NULL. If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not NULL.

2016-10-11 14:53 UTC, rlucioni commented on ecommerce/extensions/api/v2/views/baskets.py
> +            attribute_cookie_data(basket, request)
@mjfrey would know better, but I think you may also need to update the checkout view.

2016-10-11 14:53 UTC, rlucioni commented on ecommerce/extensions/basket/utils.py
> +    except Exception:  # pylint: disable=broad-except
You could just use a bare except here.

2016-10-11 14:53 UTC, rlucioni commented on ecommerce/extensions/basket/utils.py
> +    # TODO: update this line to use site configuration once config in production (2016-10-04)
Is there a JIRA ticket to track this?

2016-10-11 14:53 UTC, rlucioni commented on ecommerce/extensions/basket/utils.py
> +    referral.utm_source = utm.get('utm_source')
More concisely:
```py
for param in ['utm_source', ...]:
    setattr(referral, param, utm.get(param))
```

2016-10-11 14:53 UTC, rlucioni commented on ecommerce/referrals/models.py
> +    utm_campaign = models.CharField(_('UTM Campaign'), null=True, blank=True, default=None, max_length=255)
Same comment from before about null and blank on a CharField applies here.

2016-10-11 14:58 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/baskets.py
> +            attribute_cookie_data(basket, request)
If you want to track cancel/errors you might want to add tracking to the checkout views.

2016-10-11 14:59 UTC, bderusha commented on ecommerce/extensions/basket/utils.py
> +    except Exception:  # pylint: disable=broad-except
🐻 fixed

2016-10-11 15:08 UTC, bderusha commented on ecommerce/extensions/basket/utils.py
> +    # TODO: update this line to use site configuration once config in production (2016-10-04)
[ECOM-6008](https://openedx.atlassian.net/browse/ECOM-6008)

2016-10-11 19:39 UTC, bderusha commented on ecommerce/extensions/api/v2/views/baskets.py
> +            attribute_cookie_data(basket, request)
Just need to track basket creation.

2016-10-11 19:40 UTC, bderusha commented
@rlucioni changes made please rereview

2016-10-11 20:27 UTC, rlucioni commented on ecommerce/core/models.py
> +        default="",
Did you re-create migrations after making these model changes? If so, this default doesn't seem to have made it into the migrations.

2016-10-12 14:08 UTC, bderusha commented on ecommerce/core/models.py
> +        default="",
Good catch!!!  Updated

2016-10-12 17:35 UTC, rlucioni approved these changes

2016-10-13 13:20 UTC, merged

2016-10-27 21:34 UTC, clintonb commented on ecommerce/referrals/models.py
> +    site = models.ForeignKey('sites.Site', null=False, blank=False)
This should be `null=True`. This is currently breaking on stage. For whatever reason, Django has assigned a default of 6.

2016-10-27 21:34 UTC, clintonb commented on ecommerce/referrals/migrations/0002_auto_20161011_1728.py
> +            field=models.ForeignKey(default=6, to='sites.Site'),
The source of many problems.