[SOL-1953] New Receipt Page Backend
openedx-unsupported/ecommerce pull request #973
Opened 2016-10-18 12:04 UTC by marjev

@mjfrey Here's a Receipt Page PR that only includes Backend changes that can be merged independently. You can start the review process. If there's someone else who should be tagged on this PR as a reviewer, please mention them so that they're aware of this PR.

@vkaracic Please take a look as the 2nd reviewer here.

2016-10-18 12:04 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=973&repo=edx%2Fecommerce

2016-10-18 12:16 UTC, mjfrey requested changes

2016-10-18 12:16 UTC, mjfrey commented on ecommerce/core/migrations/0020_otto_receipt_page_switch.py
> +    Switch = apps.get_model('waffle', 'Switch')
I am thinking this feature should just be part of the site configuration.  So each site can choose its receipt page method.

2016-10-18 12:16 UTC, mjfrey commented on ecommerce/extensions/checkout/signals.py
> +                        '{}?order_number={}'.format(settings.RECEIPT_PAGE_PATH, order.number)
Is there a reason we could not use /commerce/checkout/receipt/{order-number}?  Remove the query parameter.

2016-10-18 12:16 UTC, mjfrey commented on ecommerce/extensions/checkout/utils.py
> +    return format_currency(amount, settings.OSCAR_DEFAULT_CURRENCY, locale=to_locale(get_language()))
format_currency(
            Decimal(benefit.value), settings.OSCAR_DEFAULT_CURRENCY, format=u'#,##0.00',
            locale=to_locale(get_language()))

2016-10-18 12:16 UTC, mjfrey commented on ecommerce/extensions/offer/utils.py
> +def get_discount_percentage(discount_value, product_price):
don't we have these utility functions somewhere already?

2016-10-18 12:41 UTC, vkaracic reviewed
There are a lot of checks for the Otto receipt page waffle switch, is it possible to DRY it somehow?
I finished my first pass.

2016-10-18 12:41 UTC, vkaracic commented on ecommerce/core/migrations/0020_otto_receipt_page_switch.py
> +    Switch = apps.get_model('waffle', 'Switch')
This could probably be a global variable since both functions are using it.

2016-10-18 12:41 UTC, vkaracic commented on ecommerce/extensions/api/serializers.py
> +    def get_shipping_address(self, obj):
@mjfrey I don't think we'll have shipping addresses for seats and coupons, right? I think exposing this is currently unnecessary.

2016-10-18 12:41 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/providers.py
> +    def get(self, request):
Perhaps add a docstring explaining what's going on here.

2016-10-18 12:41 UTC, vkaracic commented on ecommerce/extensions/checkout/tests/test_signals.py
> -        credit_provider_name = 'Hogwarts'
Why was this moved?

2016-10-18 12:41 UTC, vkaracic commented on ecommerce/settings/test.py
> +PLATFORM_NAME = 'My Platform'
Is this necessary?

2016-10-19 07:27 UTC, marjev commented on ecommerce/extensions/offer/utils.py
> +def get_discount_percentage(discount_value, product_price):
not that I'm aware of.

2016-10-20 08:13 UTC, marjev commented
@mjfrey @vkaracic Your comments have been addressed.

2016-10-20 09:13 UTC, vkaracic approved these changes
A couple of nitpicks otherwise LGTM.
Will the documentation need changing / adding parts about the new receipt page?

2016-10-20 09:13 UTC, vkaracic commented on ecommerce/extensions/checkout/utils.py
> +    Returns: str
I believe we're using Google's Python style guide, and according to it the return part should [`describe the type and semantics of the return value`](https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments)

2016-10-20 09:13 UTC, vkaracic commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +    def _get_receipt_url(self):
Could this be a property then?

2016-10-20 10:34 UTC, marjev commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +    def _get_receipt_url(self):
Property of what?

2016-10-20 10:48 UTC, vkaracic commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +    def _get_receipt_url(self):
Of the class. https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/api/v2/tests/views/test_baskets.py#L260

2016-10-20 10:51 UTC, marjev commented
@srpearce Here's the PR for enabling new Receipt Page in ecommerce Django Administration Tool.
The following screenshot shows the necessary change:

![screencapture-localhost-8002-admin-core-siteconfiguration-2-1476960228976](https://cloud.githubusercontent.com/assets/6833568/19556777/0586dfb6-96c3-11e6-8064-ddb1f07e200f.png)

On top of the screenshot are the breadcrumbs showing the exact location of the Administration Page. The new addition is the flag `Enable Otto Receipt Page`. It has to be checked.

This should be done along with the steps documented in [#1315](https://github.com/edx/edx-documentation/pull/1315).

Let me know if you need more info.

2016-10-20 12:26 UTC, marjev commented on ecommerce/extensions/payment/tests/processors/test_paypal.py
> +    def _get_receipt_url(self):
It's for internal use only so it doesn't make sense to make it a property. I also suggested a private usage of this method, hence the underscore in the name.

2016-10-21 13:38 UTC, marjev commented
@mjfrey Latest commit removes `Shipping address` from the Order serializer.

2016-10-21 13:51 UTC, mjfrey commented on ecommerce/extensions/api/serializers.py
> +    billing_address = BillingAddressSerializer(allow_null=True)
Don't you need to remove this as well.

2016-10-21 13:51 UTC, mjfrey commented on ecommerce/extensions/api/serializers.py
> +            'billing_address',
and this

2016-10-21 13:54 UTC, marjev commented on ecommerce/extensions/api/serializers.py
> +    billing_address = BillingAddressSerializer(allow_null=True)
It was already in the serializer. It's not something that Joyce added. Looks like we get that from CyberSource.
I just alphabetized the serializer fields, which is the reason why they're all green.

2016-10-21 13:55 UTC, mjfrey commented
@marjev right -- sorry.

2016-10-21 15:29 UTC, mjfrey approved these changes

2016-10-24 07:32 UTC, merged