[SOL-1823] Add acceptance test for creating dynamic coupon.
openedx-unsupported/ecommerce pull request #975
Opened 2016-10-20 12:32 UTC by vkaracic

This PR contains:
* new flag: ``CHECKOUT_ON_ECOMMERCE`` which is used for the professional education test. If set to ``False`` the test will assert that the user is not enrolled, if it's ``True`` it will check if the redirect to the basket happens. This is changed because when ecommerce checkout is enabled on LMS, clicking the professional course enrollment button does the redirect which causes a timeout error to occur in the old test (it expects the course modes page to be loaded which it never is because of the redirect). If this change is accepted, **it needs [documentation](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/ecommerce/test_ecommerce.html#configure-acceptance-tests) update**.
* new acceptance test for creating a dynamic coupon. Since the ``tearDown`` method in coupon admin tests sends requests to the ecommerce server after every test case to delete the created coupons, adding a new one resulted in the server returning 429 error, so I added a sleep period to circumvent that.

https://openedx.atlassian.net/browse/SOL-1823

2016-10-20 12:32 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=975&repo=edx%2Fecommerce

2016-10-20 13:10 UTC, vkaracic commented
@marjev @iivic @mjfrey please review.

2016-10-21 07:21 UTC, vkaracic commented
@edx/ecommerce can anyone please review this?

2016-10-21 07:22 UTC, marjev reviewed
Just one comment. More of a suggestion.

Perhaps you should tag someone from ecommerce or testeng team to take a look at this. They should be more helpful.

2016-10-21 07:22 UTC, marjev commented on acceptance_tests/mixins.py
> +        time.sleep(10)
http://bok-choy.readthedocs.io/en/latest/guidelines.html#never-use-time-sleep

2016-10-21 07:26 UTC, vkaracic commented on acceptance_tests/mixins.py
> +        time.sleep(10)
I'm aware of that, but this is not a ``PageObject`` class.

2016-10-21 07:31 UTC, marjev commented on acceptance_tests/mixins.py
> +        time.sleep(10)
The problem with this is that we can't really say why the sleep has to last 10s.

2016-10-21 07:37 UTC, iivic requested changes
Few changes before approving.

2016-10-21 07:37 UTC, iivic commented on acceptance_tests/mixins.py
> +        # Tear-down's after every test cause the server to return 429 errors,
Tear-down's ?

2016-10-21 07:37 UTC, iivic commented on acceptance_tests/pages/coupons.py
> +            self.q(css='input#multiple-courses').click()
Can you just select by the id #multiple-courses?

2016-10-21 07:37 UTC, iivic commented on acceptance_tests/pages/coupons.py
> +            self.q(css='textarea#catalog-query').fill('org:TestX')
Same as mentioned.

2016-10-21 07:37 UTC, iivic commented on acceptance_tests/pages/coupons.py
> +            self.q(css='input#professional').click()
Same as mentioned.

2016-10-21 10:57 UTC, vkaracic commented on acceptance_tests/pages/coupons.py
> +            self.q(css='input#multiple-courses').click()
I could but the convention for this part of the code seems to be the selector that I used.

2016-10-21 11:05 UTC, iivic approved these changes

2016-10-25 12:21 UTC, mjfrey commented on acceptance_tests/config.py
> +CHECKOUT_ON_ECOMMERCE = os.environ.get('CHECKOUT_ON_ECOMMERCE')
just make this always true and remove this flag.  Shopping cart is now deprecated.

2016-10-26 08:34 UTC, vkaracic commented on acceptance_tests/config.py
> +CHECKOUT_ON_ECOMMERCE = os.environ.get('CHECKOUT_ON_ECOMMERCE')
In that case should there be a ticket for remove the shopping cart code?

2016-11-02 11:47 UTC, vkaracic commented
@edx/ecommerce again, can someone please review this?

2016-11-02 15:39 UTC, clintonb commented on acceptance_tests/mixins.py
> +        time.sleep(10)
The current rate limit is 50 requests per minute. How many requests are you making, that this is necessary?

2016-11-02 15:39 UTC, clintonb commented on acceptance_tests/test_coupon_admin.py
> +        """ Create a single-course and dynamic coupon via UI. """
Aren't those the only two variants of a coupon? `"Create a coupon via UI."`

2016-11-02 15:39 UTC, clintonb commented on acceptance_tests/test_profed_enrollment.py
> +            # Clicking on the enroll button the user gets redirected to the ecommerce basket.
s/the user gets redirected/redirects the user

2016-11-03 11:36 UTC, vkaracic commented on acceptance_tests/mixins.py
> +        time.sleep(10)
I doubt it's more than 50 but without this I get 429 status code errors. This could be due to my local set-up. Is there a way to run the acceptance tests on stage? If not I guess I could run them on a sandbox and test there.

2017-03-30 14:05 UTC, clintonb commented
If this is no longer needed, please close the PR and delete the branch.

2017-03-30 14:06 UTC, closed without merging