[SOL-2109] Change the default values of max_uses field in coupon form.
openedx-unsupported/ecommerce pull request #976
Opened 2016-10-21 13:41 UTC by vkaracic

When the user selects 'Can be used multiple times by multiple users'
usage limitation option, the default value would be 1 which doesn't
make sense for multi-use vouchers. Instead now it's default is blank
which, if left that way, will default to 10000 which is the arbitrary
limit that Oscar sets for this attribute, and the minimum limit is set
to 2. Values of other usage limitations are left the same.

https://openedx.atlassian.net/browse/SOL-2109

2016-10-21 14:04 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=976

2016-10-21 15:29 UTC, mjfrey commented
👍

2016-10-26 09:15 UTC, iivic requested changes

2016-10-26 09:15 UTC, iivic commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> +                    view.$el.find('[name=voucher_type]').val('Multi-use').trigger('change');
Nitpick: use shortcut for view.$el.find (view.$)

2016-10-26 09:15 UTC, iivic commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> +                    view.$el.find('[name=voucher_type]').val('Once per customer').trigger('change');
Nitpick: use shortcut for view.$el.find (view.$)

2016-10-26 09:15 UTC, iivic commented on ecommerce/static/js/test/specs/views/coupon_form_view_spec.js
> +                    view.$el.find('[name=voucher_type]').val('Multi-use').trigger('change');
Nitpick: use shortcut for view.$el.find (view.$)

2016-10-26 09:15 UTC, iivic commented on ecommerce/static/js/views/coupon_form_view.js
> +                        this.$(maxUsesFieldSelector).attr('min', 2);
Maybe we should do the validation with backbone validation instead of this?

2016-10-26 09:53 UTC, vkaracic commented
Comments addressed.

2016-10-27 07:35 UTC, iivic approved these changes

2016-10-27 08:23 UTC, merged