ECOM-5835 Otto no longer able to refund an order after a refund denial
openedx-unsupported/ecommerce pull request #977
Opened 2016-10-24 08:46 UTC by Ayub-Khan

**ECOM-5835 :**
Otto no longer able to refund an order after a refund denial
**Description :**
*Updated the Refund model's create_with_lines method's code to check for refunded lines status too.
*Added tests

**Reviewvers** 
- [x]  @Qubad786  
- [x]  @attiyaIshaque

2016-10-24 08:49 UTC, awaisdar001 commented
@Ayub-Khan Can you add the problem statement which this PR is addressing?

2016-10-24 08:52 UTC, awaisdar001 commented on ecommerce/extensions/refund/models.py
> +            order_lines: Contains all order lines refunded or not.
nit `order_lines (list of order.Line)`

2016-10-24 08:52 UTC, awaisdar001 commented on ecommerce/extensions/refund/models.py
> +            unrefunded_lines: which have not been refunded.
Same here ^^

2016-10-24 08:59 UTC, awaisdar001 commented on ecommerce/extensions/refund/models.py
> +                for refunded_line in line.refund_lines:
Do we have multiple iterations in this loop? 
Second, Can we replace with `any` method?

2016-10-24 09:00 UTC, Ayub-Khan commented on ecommerce/extensions/refund/models.py
> +            order_lines: Contains all order lines refunded or not.
ok

2016-10-24 09:00 UTC, Ayub-Khan commented on ecommerce/extensions/refund/models.py
> +            unrefunded_lines: which have not been refunded.
ok

2016-10-24 09:01 UTC, awaisdar001 commented on ecommerce/extensions/refund/models.py
> +                for refunded_line in line.refund_lines:
somthing like this?
`refunded = any([refunded_line.status != REFUND.DENIED for refunded_line in line.refund_lines])`

PS. I have tested the syntax.

2016-10-24 16:48 UTC, clintonb requested changes

2016-10-24 16:48 UTC, clintonb commented on ecommerce/extensions/refund/models.py
> +        unrefunded_lines = cls.get_unrefunded_order_lines(lines)
This is simpler, and achieves the same result:

```python
unrefunded_lines = [line for line in lines if not line.refund_lines.exclude(status= REFUND_LINE.DENIED).exists()]
```

2016-10-24 16:48 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +        Refund.create_with_lines should create RefundLines for orders lines which have
Verify refunds can be created for items that were previously denied a refund.

2016-10-24 16:48 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +    def test_create_with_lines_with_existing_refund_status_denied(self):
`test_create_with_lines_with_existing_denied_refund`

2016-10-24 16:48 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +    def test_create_with_lines_with_existing_refund_status_denied(self):
This test is not actually testing the behavior we want to test.

2016-10-25 10:45 UTC, Ayub-Khan reviewed
I have updated the pr . kindly review @awaisdar001  @clintonb

2016-10-25 13:05 UTC, clintonb approved these changes

2016-10-25 13:05 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +            l.check(
Move this to an assertion, `assert_refund_creation_logged`. Use that assertion here and in `test_create_with_lines`.

2016-10-25 13:05 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +    def test_create_with_lines_with_existing_denied_refund(self):
This is great. To fully cover all cases, update `test_create_with_lines_with_existing_refund`. Use `ddt` to iterate over all refund line states except DENIED, and ensure no refunds are created.

2016-10-25 15:58 UTC, Ayub-Khan commented on ecommerce/extensions/refund/tests/test_models.py
> +    def test_create_with_lines_with_existing_denied_refund(self):
good sure.

2016-10-25 15:59 UTC, Ayub-Khan commented on ecommerce/extensions/refund/tests/test_models.py
> +            l.check(
ok

2016-10-26 14:43 UTC, Ayub-Khan commented
@clintonb  addressed all comments have a look

2016-10-26 16:41 UTC, clintonb approved these changes
Fix the test, and you're all set. Also, remember to squash commits.

2016-10-26 16:41 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +    def assert_refund_creation_logged(self, order, line, refund_created):
This is not quite the change I requested. My request was to de-dupe the call to `l.check()`:

```python
def assert_refund_creation_logged(self, refund, order):
    """ Asserts a log entry was created denoting the creation of a refund. """
    l.check(
        (
            LOGGER_NAME,
            'INFO',
            'refund_created: amount="{}", currency="{}", order_number="{}", '
            'refund_id="{}", user_id="{}"'.format(
                refund.total_credit_excl_tax,
                refund.currency,
                order.number,
                refund.id,
                refund.user.id
            )
        )
    )
```

`assert_refund_creation_logged` should be used in `test_create_with_lines_with_existing_refund` and `test_create_with_lines`.

2016-10-28 07:10 UTC, Ayub-Khan commented
@clintonb review updated.

2016-10-28 14:57 UTC, clintonb approved these changes
Remember to squash your commits.

2016-10-28 14:57 UTC, clintonb commented on ecommerce/extensions/refund/tests/test_models.py
> +        Logs the refund creation process for test_create_with_lines_with_existing_refund method
Asserts that refund creation is logged.

2016-11-03 09:00 UTC, Ayub-Khan commented
@clintonb  What to do about those VersionEye tests.

2016-11-03 11:30 UTC, clintonb commented
Ignore them for now. 

2016-11-04 12:04 UTC, Ayub-Khan commented
@clintonb is it ok to merge ? if its failing.

2016-11-04 13:07 UTC, clintonb commented
Yes. See my previous comment.

2016-11-08 09:54 UTC, attiyaIshaque commented
Looks good to me 👍

2016-11-08 09:55 UTC, merged