[SOL-1954, SOL-1955, SOL-1956] New Receipt Page - Frontend
openedx-unsupported/ecommerce pull request #978
Opened 2016-10-24 12:16 UTC by marjev

@mjfrey Here's a frontend part of the Receipt Page PR. I don't want to split this any further because I'm afraid we might lose the bigger picture that this PR offers. Any suggested changes should be applied, if needed, across the entire PR.

@vkaracic please review as well.

Acceptance tests will be the 3rd PR.

2016-10-24 12:16 UTC, edx-webhook commented
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=978&repo=edx%2Fecommerce

2016-10-24 12:29 UTC, mjfrey commented on ecommerce/extensions/checkout/views.py
> +            course = site_configuration.course_catalog_api_client.course_runs(seat.attr.course_key).get()
Don't you need to catch an exception here?  What if we do not find the course from the catalog?

2016-10-24 12:31 UTC, mjfrey commented on ecommerce/extensions/checkout/views.py
> +            course = site_configuration.course_catalog_api_client.course_runs(seat.attr.course_key).get()
actually -- why don't we just use the course info already in otto.  No need to call the catalog service.

2016-10-24 12:33 UTC, mjfrey commented on ecommerce/extensions/checkout/views.py
> +                if processor_response and processor_response.processor_name == 'paypal':
This logic should be part of the ProcessorResponse class as a method.  get_recipient_info.

2016-10-24 12:35 UTC, mjfrey commented on ecommerce/extensions/checkout/views.py
> +            'is_payment_complete': True,
is this ever False?

2016-10-24 12:35 UTC, mjfrey commented on ecommerce/extensions/checkout/views.py
> +            'nav_hidden': True,
same here

2016-10-24 16:06 UTC, mjfrey commented on ecommerce/extensions/checkout/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
this is a helper function not a test.  You should check for this in the actual test that calls it.

2016-10-24 18:14 UTC, mjfrey commented
@clintonb can you take a look?

2016-10-24 23:00 UTC, clintonb requested changes
I'd like to see some changes:
1. Assume all orders have multiple items. If you're making calls to the Catalog API, get the info for all course runs at the same time. Use `/course_runs/?keys=A,B,C`.
2. Extend the existing Oscar view.
3. There is a lot of HTML/text munging in the view. This should be in the template.
4. A lot of the issues I have with the view are due to the fact that you're using the same view to handle CyberSource and render the receipt. Ideally the receipt view should _only_ render the receipt. Use another interstitial view to wait for CyberSource processing.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/app.py
> +            url(r'^receipt/', self.receipt_response.as_view(), name='receipt'),
Why not use the existing Oscar view, `thank-you`? (Example URL: https://ecommerce.edx.org/checkout/thank-you/?order_number=EDX-1234)

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        self.assertEqual(response.status_code, 200)
The status code should be 404.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        response = self.client.post(self.path)
What about `GET` operations?

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +    def post_to_receipt_page(self, post_data):
Add a docstring.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        expected_pattern = r"<title>(\s+)Receipt" if decision == 'ACCEPT' else r"<title>(\s+)Payment Failed"
Split this into two tests—one for accept, the other for reject/error. A helper function will help reduce duplication.

For future reference: An `if-else` in a test is a sign that there should be a separate test case.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        self.assertNotContains(response, "How it Works")
I don't see these strings anywhere in the codebase. Why is this test necessary?

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> -
Restore.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                processor_response = PaymentProcessorResponse.objects.filter(basket=order.basket).latest()
The `PaymentProcessorResponse` was never intended to be used for any purpose outside of debugging, hence our not parsing any of the responses. If you need address info, it needs to be retrieved from the `Order` model.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                'currency': settings.OSCAR_DEFAULT_CURRENCY,
Currency should come from the order.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +            seat = order.lines.first().product
Let's stop doing this now. We are quickly approaching a world where orders contain multiple items. We should not port the single item order paradigm to this page.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                'purchased_datetime': dateutil.parser.parse(order_data['date_placed']).strftime('%d. %B %Y'),
This needs to be localized. See http://stackoverflow.com/a/6991918/592820 for an example implementation.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +from ecommerce.extensions.checkout.utils import add_currency, get_credit_provider_details, get_receipt_page_url
`add_currency` has a couple issues:

1. The name is confusing. `format_price` is less confusing.
2. It defaults to the currency from settings. While we may only use a single currency today, that will not always be the case. Correcting this to accept both a currency and an amount will prevent a lot of headaches in the future.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                recipient_info = None
If you were to keep this code (which I recommend against, since you should not be using `PaymentProcessorResponse`), you should log the exception alongside a helpful message. Otherwise, debugging will be painful.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                'verified': seat.attr.certificate_type == 'verified'
This is redundant given that you have `is_verification_required`.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        self.assertDictContainsSubset(receipt_data, response.context_data['receipt'])
Add the data to `context_data` and remove this assertion.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +class ReceiptResponseView(TemplateView):
This view needs to validate access to the requested order. Orders should be accessible if either of the following conditions is met:

1. The user is a staff user.
2. The user placed the order (e.g. `order.user == request.user`)

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +        payment_support_link = '<a href="mailto:{email}">{email}</a>'.format(email=payment_support_email)
No HTML in views. Return the email address only. The template should handle the rendering. Also, this should probably be part of the core context processor since it already contains the support URL.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +            'error_text': None,
Is this necessary? If this field is not present, will the page still render?

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +            'for_help_text': _(
Why isn't this in the template?

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +            'platform_name': settings.SITE_NAME,
This is part of the core context processor.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/static/js/routers/receipt_router.js
> +                this.currentView = page;
Merge with the line above. No need for the variable if it's not being used.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/templates/oscar/checkout/receipt.html
> +                        <th scope="col" >{% trans "Qty" %}.</th> <!-- Translators: Abbreviation for quantity.-->
This comment should be above the line marked for translation.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/templates/oscar/checkout/receipt.html
> +                            {% if receipt.discount %}
Move the if-statement inside the div, and de-dupe.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/static/js/apps/receipt_app.js
> +require([
The app and router seem unnecessary for a single page.

2016-10-24 23:00 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +            course = site_configuration.course_catalog_api_client.course_runs(seat.attr.course_key).get()
I have a similar question. I see no usage of this data aside from `course.key`, which you already have.

2016-10-25 11:36 UTC, marjev commented on ecommerce/extensions/checkout/views.py
> +            course = site_configuration.course_catalog_api_client.course_runs(seat.attr.course_key).get()
Good catch. This can be removed entirely. This was added because the Old Receipt Page design had Course name on the page.

I'll remove this.

2016-10-25 12:13 UTC, marjev commented on ecommerce/extensions/checkout/views.py
> +            'is_payment_complete': True,
yes, it is, when the payment is not complete, which is some use-case with CyberSource I'm not too familiar with and didn't have time to go into (would take me additional days just to figure that one out).

We'll have to figure out how we want to handle CyberSource use-case in our code. Clinton suggested what seems to be a solid solution to this problem. I'll try to implement it that way.

2016-10-25 12:14 UTC, marjev commented on ecommerce/extensions/checkout/views.py
> +            'nav_hidden': True,
I'll remove this. It seems to have no purpose at all.

2016-10-25 14:49 UTC, marjev commented on ecommerce/extensions/checkout/app.py
> +            url(r'^receipt/', self.receipt_response.as_view(), name='receipt'),
Should I remove this ```url(r'thank-you/$', self.thankyou_view.as_view(), name='thank-you'),```?

I will extend the `ThankYouView` provided by Oscar, but I'm not sure if we want to expose ThankYouView via `thank-you` URL.

2016-10-25 14:51 UTC, clintonb commented on ecommerce/extensions/checkout/app.py
> +            url(r'^receipt/', self.receipt_response.as_view(), name='receipt'),
Yeah, I would replace that thank-you URL with receipt.

2016-10-26 11:13 UTC, marjev commented on ecommerce/extensions/checkout/tests/test_views.py
> +        self.assertNotContains(response, "How it Works")
I don't know. My guess is this was copy/pasted from the LMS.

I'll remove this.

2016-10-28 07:35 UTC, marjev commented on ecommerce/extensions/checkout/views.py
> +                recipient_info = None
I decided to do what you recommended.

2016-10-28 08:45 UTC, marjev commented on ecommerce/static/js/apps/receipt_app.js
> +require([
App simply initializes the router, which initializes the page and passes the Order number to it. Receipt Backbone View uses the Order number to trigger Analytics events that are a requirement for [SOL-1956](https://openedx.atlassian.net/browse/SOL-1956).

If you know a way to do this Django side, without using Backbone Analytics Model, please let me know.

2016-10-28 11:02 UTC, marjev commented
@mjfrey @clintonb Most of the comments have been addressed.

Regarding the `post` method that handles the CyberSource Payments, should I simply add a redirect to the receipt page if the CyberSource Payment didn't fail? I was thinking of using [this view](https://github.com/edx/ecommerce/commit/89ff8dc18dd97523da1132f83075c1612ef29b66#diff-3a39a1e895cafeeed9c6a0c0dffd2dceR37). Let me know what you think.

2016-10-31 13:01 UTC, marjev commented on ecommerce/static/js/apps/receipt_app.js
> +require([
I removed all Backbone.js stuff for now. I'll rethink this. I found what I was looking for and I think that using Backbone for this is definitely an overcomplication.

2016-11-03 09:56 UTC, marjev commented on ecommerce/extensions/checkout/signals.py
> +@receiver(post_payment, dispatch_uid='tracking.post_payment_callback')
@mjfrey I decided to use `post_payment` signal as a trigger for the Segment.io event `Completed Purchase`.

Can you review this code? Do I need to send `post_payment` signal in `handle_processor_response` method for each PaymentProcessor or is that already being done somewhere in Otto/Oscar code?

2016-11-03 12:26 UTC, marjev commented on ecommerce/extensions/checkout/signals.py
> +@receiver(post_payment, dispatch_uid='tracking.post_payment_callback')
FYI @clintonb

2016-11-03 12:51 UTC, marjev commented
@clintonb While I was trying to address the 4th comment you left on the PR, I began to wonder. Since the LMS Receipt Page View has the CyberSource handling logic deeply integrated within, will removing that logic from the ecommerce Receipt Page View require additional changes to the CyberSource handling code?
I still don't know which piece of code sends the POST request to the Receipt Page View (endpoint) to begin with or at least handles to which URL the request will be made to?

FYI @mjfrey

2016-11-04 15:56 UTC, clintonb commented on .gitignore
> +geckodriver.log
`*.log`

2016-11-04 15:56 UTC, clintonb commented on bower.json
> +    "backbone-relational": "~0.9.0",
Since you're touching these, please update them: https://www.versioneye.com/user/projects/5818a6aa89f0a91daa7e6da0?child=summary.

2016-11-04 15:56 UTC, clintonb commented on ecommerce/core/context_processors.py
> +        'support_email': request.site.siteconfiguration.payment_support_email,
This isn't needed by every template. Move it to the context processor for the view that actually uses it.

2016-11-04 15:56 UTC, clintonb commented on ecommerce/extensions/checkout/app.py
> -            url(r'thank-you/$', self.thankyou_view.as_view(),
Delete my recently-committed template override, too. :(

2016-11-04 15:56 UTC, clintonb commented on ecommerce/extensions/checkout/signals.py
> +post_payment = get_class('checkout.signals', 'post_payment')
Remove this since it is not used.

2016-11-04 15:56 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +    def get_object(self):
``` python
def get_object(self):
    kwargs = {
        'number': self.request.GET['order_number'],
    }

    user = self.request.user
    if not user.is_staff:
        kwargs['user'] = user

    return get_object_or_404(Order, **kwargs)
```

2016-11-04 15:56 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +    def update_context_with_order_data(self, context, order):
We can be smarter about this. Rather than do all of this on the backend, push it to the templates. Use partials and/or template tags to clean this up.

2016-11-04 15:56 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +    def post(self, request, *args, **kwargs):  # pylint: disable=unused-argument
Let's move this to a special page for CyberSource.

2016-11-04 15:56 UTC, clintonb commented on ecommerce/extensions/offer/utils.py
> +        # TODO: Fix this; Currency should be a dynamic value;
Are you fixing this?

2016-11-04 15:56 UTC, clintonb commented on ecommerce/static/js/config.js
> +        'edx-ui-toolkit': '../../node_modules/edx-ui-toolkit/src/js',
Does this actually work? If so, we can move many of our bower-based dependencies to npm.

2016-11-04 15:56 UTC, clintonb commented on ecommerce/static/js/pages/receipt_page.js
> +        trackPurchase = function(order_id) {
We should find a way to do this only the first time this loads. Subsequent views of this page should not fire events.

2016-11-04 15:56 UTC, clintonb commented on ecommerce/templates/edx/base.html
> +    {% block header_extras %} {% endblock header_extras %}
This is not used, and should be removed.

2016-11-04 16:19 UTC, mjfrey commented on ecommerce/extensions/checkout/utils.py
> -        format=u'#,##0.00',
we need this format.  Why did you remove it?  This will break when the browser is in some languages.

2016-11-04 16:24 UTC, marjev commented on ecommerce/extensions/offer/utils.py
> +        # TODO: Fix this; Currency should be a dynamic value;
Yes. There are tickets already created for this cleanup work.

2016-11-04 16:29 UTC, marjev commented on ecommerce/extensions/checkout/utils.py
> -        format=u'#,##0.00',
If this format is in place, the $ is not visible on the page (when the currency is set to 'USD'). Removing the format seems to fix the issue.

2016-11-04 16:32 UTC, mjfrey commented on ecommerce/extensions/checkout/utils.py
> -        format=u'#,##0.00',
you need add it.  without this -- the basket page breaks for some locales.

2016-11-05 09:39 UTC, marjev commented on bower.json
> +    "backbone-relational": "~0.9.0",
Only `backbone-relational` or all of them? 
If you meant all of the dependencies, I'm worried about updating the jQuery from 1.12.2 to 3.1.1. That's a rather drastic change and perhaps should be done in a separate PR.

2016-11-07 14:52 UTC, marjev commented on ecommerce/static/js/config.js
> +        'edx-ui-toolkit': '../../node_modules/edx-ui-toolkit/src/js',
This is a leftover from Joyce's original commit. I wasn't able to use variables like `$baseline` so I guess it's not working. I'll remove this.

2016-11-07 14:57 UTC, clintonb commented
Remember to incorporate these changes: https://github.com/edx/edx-platform/pull/12470

2016-11-07 15:00 UTC, clintonb commented
I started a Verification API at https://github.com/edx/edx-platform/commits/clintonb/verification-status-api.

2016-11-07 16:02 UTC, marjev commented on ecommerce/static/js/pages/receipt_page.js
> +        trackPurchase = function(order_id) {
Let me think about this some more.

2016-11-07 16:37 UTC, marjev commented
@clintonb @mjfrey Comments have been addressed. Vedran commented on one because we currently don't have a clear idea on how to get a basket URL for the thawed basket (in case CyberSource payment has failed). Also, I'll have to think about how to trigger the analytics event only once.

2016-11-09 09:29 UTC, marjev commented on bower.json
> +    "backbone-relational": "~0.9.0",
I'll hold off from doing that because updating backbone-relational caused an unrelated test failure. I would like to keep this PR as clean and simple as possible.

2016-11-09 09:57 UTC, marjev commented on ecommerce/static/js/pages/receipt_page.js
> +        trackPurchase = function(order_id) {
Addressed. Please take a look at 0224d38

2016-11-09 12:27 UTC, marjev commented on ecommerce/static/js/pages/receipt_page.js
> +        trackPurchase = function(order_id) {
Actually, this isn't doing what I was hoping it would do, so I'll have to rethink this further, but hopefully I'll manage to send bool value from the PaymentProcessorView with the redirect.

2016-11-15 16:37 UTC, mjfrey commented on ecommerce/templates/oscar/checkout/cybersource_error.html
> +{% extends 'edx/base.html' %}
Do we want to call this payment_error and not use the cyber source name?

2016-11-15 16:51 UTC, marjev commented on ecommerce/templates/oscar/checkout/cybersource_error.html
> +{% extends 'edx/base.html' %}
If I understood correctly, this template is only for CyberSource usecase, because sometimes CyberSource Payment might "fail".

I didn't notice PayPal having this issue. There should be a subtask created on JIRA that describes this case. This template is only being called by CyberSourceInterstitialView.

2016-11-15 21:51 UTC, clintonb requested changes

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +    formatted_price = serializers.SerializerMethodField()
Why not do this client-side?

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/payment/views.py
> +            context = self.get_context_data()
The purpose of this view is to process the response from CyberSource, which is why you're inheriting `CybersourceNotifyView`. As is, all you're doing is redirecting the user. Ultimately, we want to get rid of `CybersourceNotifyView` (or at least minimize our reliance on it) and complete all transactions via `CybersourceInterstitialView`.

Given the complexity, this should be split into a separate PR.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +        payment_successful = self.request.session.pop('payment_successful', None)
Let's be more specific in the naming here. `payment_successful` is too broad. `fire_tracking_events` seems more appropriate. Also, the code can be simplified:

``` python
context['fire_tracking_evnets'] = self.request.session.pop('fire_tracking_evnets', False)
```

2016-11-15 21:51 UTC, clintonb commented on ecommerce/templates/oscar/checkout/cybersource_error.html
> +{% load staticfiles %}
You don't appear to be using this. It should be removed.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/templates/oscar/checkout/cybersource_error.html
> +      {% with "<a class='nav-link' href='mailto:"|add:payment_support_email|add:"'>"|safe as start_link %}
For future reference, we have a custom tag, `captureas`, that will simplify this.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/payment/views.py
> +            return self.render_to_response(context=context, status=500)
`502 Bad Gateway` may be a more appropriate status code.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +        order_data = OrderSerializer(order, context={'request': self.request}).data
Why bother with serialization? Django templates can use accept an `Order` object.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +            'purchased_datetime': dateutil.parser.parse(order_data['date_placed']),
This goes along with my earlier question about serialization. We have an Order object. Use it, and do any special formatting in the template.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                    if hasattr(seat.attr, 'certificate_type') and seat.attr.certificate_type == 'credit':
The attribute you actually care about is `credit_provider`. Just check for it.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                if self.request.user.is_verified(self.request):
If tests aren't failing on this call, they should be because this method does not accept any arguments.

Also, @vkaracic we should be caching this API response. It makes no sense to re-fetch verification data if the verification expires in a year.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/static/js/pages/receipt_page.js
> +            var order_id = $.url('?order_number') || null,
`orderId`

2016-11-15 21:51 UTC, clintonb commented on ecommerce/static/js/pages/receipt_page.js
> +            var order_id = $.url('?order_number') || null,
Why bother with jQuery URL? Pass the order number as a data attribute.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/static/js/config.js
> +        'date-utils': 'bower_components/date-utils/lib/date-utils.min',
This doesn't seem to be used anywhere.

2016-11-15 21:51 UTC, clintonb commented on bower.json
> +    "date-utils": "1.2.16",
This doesn't seem to be used anywhere.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/static/js/apps/receipt_app.js
> +require([
Skip the middle man. We don't need this app file. Just load the page JS directly. Also, update `build.js`.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/static/js/pages/receipt_page.js
> +            trackPurchase: trackPurchase
This is only called by `onReady`. There is no need to expose it. If you get rid of `receipt_app.js`, there is no need to expose anything.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/templates/oscar/checkout/_credit_provider_data.html
> +      data-username="{{ name }}"
Why is this not username?

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +            'name': '{} {}'.format(self.request.user.first_name, self.request.user.last_name),
It seems the only place where this is used, you actually need the username of the person who placed the order. This should be `order.user.username`. If you passed the order to context, this line can go away entirely.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                    if hasattr(seat.attr, 'certificate_type') and seat.attr.certificate_type == 'credit':
Also, this shouldn't necessarily be nested in the check for verification. Say a user has purchased a credit seat but his/her verification expired. We still want to show details for credit retrieval.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                if self.request.user.is_verified(self.request):
We should only check for verification status if a seat requiring verification is in the order.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/templates/oscar/checkout/receipt.html
> +                  {% for key, value in verification_data.items %}
We only need to show one verification link. Although the URLs are course run-dependent, verification is not actually tied to the course run, just the user.

@mjfrey this needs to be updated on LMS.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                if self.request.user.is_verified(self.request):
Also, @vkaracic it seems we are re-raising HTTP errors. I may have suggested this, in which case it was a bad idea. We should log the exceptions (which you are doing), but not raise them.

2016-11-15 21:51 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +        context = self.get_context_data(**kwargs)
You've done a bit too much here, and made this slightly more complicated than it needs to be. I'll post a simpler version shortly.

2016-11-15 21:54 UTC, vkaracic commented on ecommerce/extensions/checkout/views.py
> +                if self.request.user.is_verified(self.request):
Okay, I'll rework it tomorrow. Also the ``is_verified`` method accepts the request so it can construct the LMS URL.

2016-11-15 22:13 UTC, mjfrey commented on ecommerce/templates/oscar/checkout/receipt.html
> +                  {% for key, value in verification_data.items %}
@clintonb can you say more?  What needs to change in LMS?

2016-11-15 22:21 UTC, mjfrey commented on ecommerce/extensions/checkout/views.py
> +                    if hasattr(seat.attr, 'certificate_type') and seat.attr.certificate_type == 'credit':
you can only be eligible for credit if you have already verified.  Credit link will never been shown if not.

2016-11-15 23:25 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                    if hasattr(seat.attr, 'certificate_type') and seat.attr.certificate_type == 'credit':
Not quite. You are considered credit-eligible if you have a row in the credit_eligibility table. Given that credit eligibility is good for a year, it is feasible that someone could verify today, get credit eligibility tomorrow, and return a year from today with credit eligibility but in an unverified state.

By the time the user has reached the receipt page for a credit seat, Otto has already confirmed credit eligibility. We should display the credit information _regardless_ of verification status since, at this point, verification doesn't matter.

2016-11-15 23:27 UTC, mjfrey commented on ecommerce/extensions/checkout/views.py
> +                    if hasattr(seat.attr, 'certificate_type') and seat.attr.certificate_type == 'credit':
yes I see.

2016-11-15 23:28 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                if self.request.user.is_verified(self.request):
I must have missed the addition of the `request` argument. We should avoid making our model methods dependent on `Request` objects. We should instead pass exactly the data we need (e.g. a `Site` object). This will allow them to be used outside of the scope of requests, if necessary.

2016-11-15 23:31 UTC, clintonb commented on ecommerce/extensions/api/serializers.py
> +    formatted_price = serializers.SerializerMethodField()
By which I mean in the template, not via JavaScript.

2016-11-15 23:44 UTC, clintonb commented on ecommerce/templates/oscar/checkout/receipt.html
> +                  {% for key, value in verification_data.items %}
Verification URLs currently follow the following format: `/verify_student/start-flow/<course-id>/`. This somewhat (although, not really) made sense when payment and verification were heavily integrated. Since the rollout of Otto, the two actions are completely separate. From a model standpoint, verifications have never been linked to courses from a model standpoint.

Ideally, verification should be independent of a specific course/enrollment. If we are worried about costs, we can set broad rules for when a user is allowed to verify:

The user is enrolled in a course run that requires verification AND either of the following is true:

1. The  user is currently unverified.
2. The user's verification is expiring in the next 7 days. (Again, this is broad. We could tighten this date to be relative to the earliest unexpired verification deadline of a user's enrollments.)

Aside: Personally, I'm starting to question the need for upgrade/verification deadlines; but, that is a separate conversation.

The URLs can be simplified: `/verify_student/start_flow/`.

2016-11-16 00:55 UTC, mjfrey commented on ecommerce/templates/oscar/checkout/receipt.html
> +                  {% for key, value in verification_data.items %}
I understand, however we should do this optimization after this is moved from LMS.  The current receipt page shows this link for each purchase (course_run).

2016-11-16 01:07 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +        from payment processors which POST back to the page, the view must be CSRF-exempt.
Payment processors should no longer be posting to this page.

2016-11-16 01:18 UTC, clintonb commented on ecommerce/templates/oscar/checkout/receipt.html
> +                  {% for key, value in verification_data.items %}
I don't necessarily consider this an optimization as much as it is paying down debt. Punting this now is just transferring the debt from one system to another.

At a minimum, the verification message should be displayed only once, and debt tickets should be created.

2016-11-16 01:43 UTC, mjfrey commented on ecommerce/templates/oscar/checkout/receipt.html
> +                  {% for key, value in verification_data.items %}
I will create 2 tickets.  One for re-working the LMS verify flow as stated above and the other for this page/view to use the new endpoint.

2016-11-16 03:23 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +                if self.request.user.is_verified(self.request):
@vkaracic I explored this a bit more. I can see a case where it would be useful to know the difference between the API call failing and the user not actually being verified. For example, in the event of a failure, instead of misleading the user to the verification page, we could inform the user that we were unable to check verification status and provide a link to verify in case the user is not verified. This difference is subtle; but, user experience is improved because the user is not confused if we erroneously take him/her to the verification page and he/she is already verified.

Thus, it makes sense to raise a custom error (e.g. `VerificationStatusError`) that wraps up all errors except `HttpNotFoundError`. This way callers have a single error to handle, and can choose how to inform the user.

2016-11-16 04:17 UTC, clintonb commented on ecommerce/templates/oscar/checkout/_credit_provider_data.html
> +      href="{{ provider.url }}">
This won't work as expected in all cases. Particularly, for providers with which we have a full integration (e.g. we send signed data), this will fail. *sigh* I have no good alternatives at the moment. Unfortunately, a resolution to this issue (due to signing key security concerns) may not come quickly.

FYI @mjfrey

2016-11-16 04:20 UTC, clintonb commented on ecommerce/templates/oscar/checkout/_credit_provider_data.html
> +      href="{{ provider.url }}">
Hmm...you could clean this up by forcing all credit requests to be initiated from the student dashboard rather than the receipt page. We already support that behavior. I'm not certain why we ever put this functionality on the receipt page.

2016-11-16 04:56 UTC, clintonb commented on ecommerce/extensions/checkout/views.py
> +        context = self.get_context_data(**kwargs)
I had an idea, which lead to more ideas, which lead to https://github.com/edx/ecommerce/commits/clintonb/receipt-temp. Feel free to incorporate these changes.

2016-11-17 08:55 UTC, marjev commented on ecommerce/extensions/api/serializers.py
> +    formatted_price = serializers.SerializerMethodField()
touché

2016-11-17 12:08 UTC, marjev commented on ecommerce/extensions/payment/views.py
> +            context = self.get_context_data()
I'll remove this from the PR and open a new one. I agree with your statement.

Instead of inheriting logic from `CybersourceNotifyView`, I'll move the logic that handles the Cybersource response. We can go from there in a new PR.

2016-11-21 13:10 UTC, marjev commented
@clintonb @mjfrey All the tests passed. Green coverage as well. I think I addressed all the comments. Please take another look.

I would like to keep this as simple as this and open a new PR for the responsive design once we're sure the current changes (text, design) on the Receipt Page is what we want.

2016-11-21 13:22 UTC, mjfrey commented on ecommerce/extensions/checkout/tests/test_views.py
> +        other_user = self.create_user()
use ddt here to pass in whether or not to be a staff user.

2016-11-21 13:41 UTC, marjev commented on ecommerce/extensions/checkout/tests/test_views.py
> +        other_user = self.create_user()
I would rather split this into two test case scenarios to avoid branching.

2016-11-21 14:16 UTC, marjev commented on ecommerce/extensions/checkout/tests/test_views.py
> +        other_user = self.create_user()
Done.

2016-11-21 14:17 UTC, marjev commented on ecommerce/extensions/offer/utils.py
> +        # TODO: Fix this; Currency should be a dynamic value;
Done.

2016-11-21 15:40 UTC, clintonb requested changes

2016-11-21 15:40 UTC, clintonb commented on ecommerce/core/models.py
> +            log.info('No verification data found for [%s]', self.username)
Use `log.debug`to avoid littering Splunk.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/basket/tests/test_views.py
> +        self.assertEqual(line_data['benefit_value'], format_benefit_value(benefit, settings.OSCAR_DEFAULT_CURRENCY))
`basket.currency`

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +    def test_login_required_post_request(self):
The view should now be `GET` only, since the CyberSource code has been removed from the receipt page.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +    def test_login_required_get_request(self):
Remove.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        self.assertEqual(response.status_code, 302)
```python
testserver_login_url = self.get_full_url(reverse(settings.LOGIN_URL))
expected_url = '{path}?next={next}'.format(path=testserver_login_url, next=urllib.quote(self.path))
self.assertRedirects(response, expected_url, target_status_code=302)
```

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +            path=self.path
Nit: Order the kwargs as they appear in the format string.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        Payment Processor name should be displayed as the Payment method
We should not be displaying the payment processor name to consumers. "CyberSource" means nothing to them. Display the card/payment type.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        source = factories.SourceFactory(order=order)
`source = factories.SourceFactory(order=order, card_type='Dummy Card', label='Test')`

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        return self.client.get('{path}?order_number={order_number}'.format(
This bit of code is duplicated numerous times. Create a helper method:

```python
def get_receipt_response(self, order):
  url = '{path}?order_number={order_number}'.format(path=self.path, order_number=order.number)
  return self.client.get(url)
```

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        httpretty.register_uri(
We are no longer calling the Credit API, so this should go.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt.html
> +         data-total-amount="{{ order.total_excl_tax }}">
`order.total_incl_tax`

2016-11-21 15:40 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt.html
> +         class="pay-and-verify"
Remove this class. This seems to be leftover from the move from LMS.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt.html
> +  <div class="receipt">
There is a lot of nesting going on here. Can we combine these three levels of `<div>`?

2016-11-21 15:40 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt.html
> +            {#            TODO: Make this table responsive.#}
This needs to be done.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt_not_found.html
> +                Please ensure that the URL is correct, and try again.
Nit: this can go on one line.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/templates/oscar/checkout/_credit_provider_data.html
> +{% load i18n %}
This is not used, and should be deleted.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/templates/oscar/checkout/error.html
> +
This empty line is not necessary.

2016-11-21 15:40 UTC, clintonb commented on ecommerce/static/sass/partials/views/_receipt.scss
> +    .order-amount {
Why is this necessary? Why not let the browser fit it all?

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/offer/utils.py
> +def format_benefit_value(benefit, currency):
Are these changes still necessary?

2016-11-21 15:40 UTC, clintonb commented on ecommerce/extensions/checkout/utils.py
> +from django.utils.translation import get_language, to_locale, ugettext_lazy as _
Are any changes to this file still necessary?

2016-11-24 11:37 UTC, marjev commented on ecommerce/extensions/checkout/tests/test_views.py
> +    def test_login_required_get_request(self):
I'll leave this test method and remove the `post` one.

2016-11-24 12:26 UTC, marjev commented on ecommerce/extensions/checkout/tests/test_views.py
> +        Payment Processor name should be displayed as the Payment method
Here's the InVision design:
https://projects.invisionapp.com/share/7D76K432C#/screens/206952822_Receipt_Whole_Cart_Coupon
Looking at it, I came to a conclusion that we want to display Payment Processor name. 
What should be displayed in case payment processor was used?

2016-11-24 13:13 UTC, marjev commented on ecommerce/templates/edx/checkout/receipt.html
> +            {#            TODO: Make this table responsive.#}
Let's do this in the separate PR. We'll have to make the entire page to be responsive.

Also, I want to make sure that texts and the "original" design is done properly before I focus on the responsive design.

2016-11-24 13:27 UTC, marjev commented on ecommerce/static/sass/partials/views/_receipt.scss
> +    .order-amount {
I'll remove that. I don't have an explanation for most of these changes because I pulled them from Joyce's original PR. :/

2016-11-24 14:37 UTC, clintonb commented on ecommerce/templates/edx/checkout/receipt.html
> +            {#            TODO: Make this table responsive.#}
If responsiveness or accessibility support are not happening on this PR, this PR cannot be merged to master. We just met our DOJ obligations regarding accessibility, and we aren't going to risk running afoul of them again. 25% of our users are on mobile, and we will not be alienating them.

2016-11-24 14:41 UTC, clintonb commented on ecommerce/extensions/checkout/tests/test_views.py
> +        Payment Processor name should be displayed as the Payment method
PayPal is an exception since it is both a payment processor class and a payment type. You should be displaying payment/card type from the `Source` model.

2016-11-25 07:21 UTC, marjev commented on ecommerce/templates/edx/checkout/receipt.html
> +            {#            TODO: Make this table responsive.#}
Ok, understood.

What about CyberSource Interstitial View PR? Should that be merged before/after this one?

2016-11-25 14:25 UTC, clintonb commented
That can be merged once it's ready. It is independent of the receipt page. 

2016-11-29 16:44 UTC, marjev commented
@clintonb Comments addressed.

Here are two screenshots showing desktop and mobile design, respectively.

![image](https://cloud.githubusercontent.com/assets/6833568/20719120/4c5fa01e-b65b-11e6-9194-75761ef3f221.png)

![image](https://cloud.githubusercontent.com/assets/6833568/20719143/5f72271c-b65b-11e6-930c-825c79176f51.png)

2016-11-29 22:03 UTC, clintonb requested changes
I may have misinterpreted your message about the responsive design as an indication that this is ready for review; however, it doesn't seem my earlier comments have been addressed. Let me know when this is ready.

2016-11-29 22:03 UTC, clintonb commented on ecommerce/core/templatetags/core_extras.py
> +    Format benefit value.
Format it how? Please provide an example in the docstring.

2016-11-29 22:03 UTC, clintonb commented on ecommerce/core/templatetags/core_extras.py
> +@register.filter(name='organization')
course_organization

2016-11-29 22:03 UTC, clintonb commented on ecommerce/core/templatetags/core_extras.py
> +def course_organization(course_key):
This is not used anywhere. It, and its tests, should be deleted.

2016-11-29 22:03 UTC, clintonb commented on ecommerce/core/templatetags/core_extras.py
> +    return format_benefit_value(benefit)
This method is implemented incorrectly for fixed price discounts. It will always return a string formatted for USD.  This will cause issues for our open source users who do not use USD. This isn't a show-stopper for this PR; but, please file a ticket to fix this, @mjfrey.

2016-11-29 22:03 UTC, clintonb commented on ecommerce/core/templatetags/core_extras.py
> +def benefit_discount(benefit):
This doesn't belong in `core`. `core` is intended for components that will be used throughout the entire project. Move this tag to an `offer_extras` or `offer_tags` in the `offer` app.

2016-11-30 10:46 UTC, marjev commented on ecommerce/core/templatetags/core_extras.py
> +def course_organization(course_key):
https://github.com/edx/ecommerce/pull/978/files#diff-cfe5821c0f7876d15964704fe72e0218R85

2016-11-30 11:07 UTC, marjev commented on ecommerce/core/templatetags/core_extras.py
> +    return format_benefit_value(benefit)
@mjfrey I think the reason behind this implementation is the locale error that you told me about. It would be great if the ticket has a concrete description of the problem.

2016-12-01 12:51 UTC, marjev commented
@clintonb I apologize for pinging you before, without checking what I've pushed. Some of the changes were stashed locally and I forgot to apply those before.

I think all the comments are addressed now.

Latest screenshots:
<img src="https://cloud.githubusercontent.com/assets/6833568/20794390/56a4e166-b7cc-11e6-97b9-ee2fa4d3dfda.png" alt="Desktop version" width="75%" height="auto">

<img src="https://cloud.githubusercontent.com/assets/6833568/20794517/0078f47a-b7cd-11e6-8e2b-15c95403ffe5.png" alt="Mobile version" width="50%" height="50%">

2016-12-15 11:50 UTC, marjev commented
@clintonb anything else needed on this PR?

2016-12-15 13:39 UTC, clintonb approved these changes

2016-12-16 14:09 UTC, merged