[SOL-2074] Omit expired professional courses from offer landing page.
openedx-unsupported/ecommerce pull request #984
Opened 2016-10-26 08:32 UTC by vkaracic

In the coupon offer landing page omit the professional courses which
have a set enrollment end datetime which has passed.

https://openedx.atlassian.net/browse/SOL-2074

According to @griffresch in the ticket:
> edX and Partners often change the enrollment end-date of a course (any type, not just ProfEd).

This might cause problems in the following scenario:

1. Course discovery service (CDS) picks up the enrollment end date metadata for a course.
2. Course enrollment end date is edited to a passed date, to prematurely close the enrollment for example, and because of that the course is no longer listed in the courses API from which the CDS retrieves the course data which means CDS has the old date stored.
3. Even though the course enrollment date has passed, we still get the old date from CDS and show that course is the offer landing page.

I don't know what settings are for the course discovery on stage and production, but that described issue happens to me locally.

Upon further investigation, setting this value (https://github.com/edx/edx-platform/blob/master/lms/envs/common.py#L2696) to ``see_in_catalog`` displays the course who's enrollment end date has passed. So if that setting is set so on stage and production, I could change the code to check directly on the LMS API the enrollment end date instead of CDS. @mjfrey who can ask for the values of these settings?

2016-10-26 08:32 UTC, edx-webhook commented
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=984&repo=edx%2Fecommerce

2016-10-26 12:59 UTC, mjfrey commented
@vkaracic you might want to ask Bill D.

2016-10-26 17:23 UTC, mjfrey commented on ecommerce/extensions/api/v2/views/vouchers.py
> +        for result in results:
can you combine the 2 loops.  Look up the product in here?  If course_seat_types has professional then check the enrollment_end.

2016-10-27 08:36 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/vouchers.py
> +        for result in results:
If I would lookup the product in this loop, that would mean I would have to database call for every iteration which I'd like to avoid.

2016-10-31 12:33 UTC, marjev requested changes

2016-10-31 12:33 UTC, marjev commented on ecommerce/extensions/api/v2/views/vouchers.py
>  import django_filters
nitpick: Not your doing, but perhaps you could just sort these imports properly.

2016-10-31 12:33 UTC, marjev commented on ecommerce/extensions/api/v2/views/vouchers.py
> +                ))
this can be dried like:
```
products.extend(Product.objects.filter(
    course_id__in=nonexpired_course_ids if seat_type == 'professional' else all_course_ids,
    attributes__name='certificate_type',
    attribute_values__value_text=seat_type
 ))
```

Also, looks to me like the loop is unnecessary. You can check if `course_seat_types == 'professional'`. Each other scenario will extend the products with all_course_ids seats.

So, I'd suggest something like:
```
products = Product.objects.filter(
    course_id__in=nonexpired_course_ids if course_seat_types == 'professional' else all_course_ids,
    attributes__name='certificate_type',
    attribute_values__value_text=seat_type
 )
```

2016-10-31 12:33 UTC, marjev commented on ecommerce/extensions/api/v2/views/vouchers.py
> +        for result in results:
In a comment below, you can see my suggestion on how the 2nd loop could be removed. Let me know if I'm missing anything there.

2016-11-01 20:40 UTC, vkaracic commented on ecommerce/extensions/api/v2/views/vouchers.py
> +                ))
So if I understand you correctly, for a scenario where the seat types are `verified,professional` the expired professional seats would be included in the products with your suggestion, right?

2016-11-02 11:44 UTC, vkaracic commented
Comments addressed!

2016-11-03 13:28 UTC, mjfrey approved these changes

2016-11-07 13:57 UTC, vkaracic commented
@marjev comments addressed.

2016-11-07 15:37 UTC, marjev approved these changes

2016-11-08 08:34 UTC, merged