Catch exceptions during paypal payment creation and introduce retry
openedx-unsupported/ecommerce pull request #996
Opened 2016-11-03 21:29 UTC by schenedx

ECOM-5891
@edx/ecommerce Please review
This is to take on @rlucioni's feedback on the same ticket. Introduced another test case as well

2016-11-04 13:52 UTC, MatthewPiatetsky commented
👍

2016-11-04 15:46 UTC, mikedikan commented on ecommerce/extensions/payment/processors/paypal.py
> +                        u"Creating paypal payment for basket [%d] result in an exception. Will retry",
nitpick: change wording here to say 'resulted'

2016-11-04 15:55 UTC, bderusha commented on ecommerce/extensions/payment/processors/paypal.py
> +                    if i < available_attempts:
Should this be `<=` ?

2016-11-04 16:01 UTC, bderusha approved these changes

2016-11-04 16:48 UTC, rlucioni commented on ecommerce/extensions/payment/processors/paypal.py
> +                            u"Creating paypal payment for basket [%d] unsuccessful. Will retry",
> Creating PayPal payment for basket [%d] was unsuccessful. Will retry.

2016-11-04 16:48 UTC, rlucioni commented on ecommerce/extensions/payment/processors/paypal.py
> +                        u"Creating paypal payment for basket [%d] result in an exception. Will retry",
> Creating PayPal payment for basket [%d] resulted in an exception. Will retry.

2016-11-04 16:48 UTC, rlucioni commented on ecommerce/extensions/payment/processors/paypal.py
> +                    raise
To ease the process of investigating these failures, you may want to log something at the ERROR level here explaining that retries have been exhausted before re-raising.

2016-11-04 16:48 UTC, rlucioni commented on ecommerce/extensions/payment/processors/paypal.py
>              available_attempts = self.retry_attempts
Have you verified that `retry_attempts` is actually defined in our production PayPal config? It may not be (this code would still work if it was missing, but no retries would occur).

I'd also encourage you to take this opportunity to clean up the way `self.retry_attempts` is assigned a value. All we really need, on line 51 at class initialization, is:
```py
is_retry_enabled = waffle.switch_is_active('PAYPAL_RETRY_ATTEMPTS')
self.retry_attempts = self.configuration.get('retry_attempts', 1) if is_retry_enabled else 1
```

2016-11-04 18:20 UTC, schenedx commented on ecommerce/extensions/payment/processors/paypal.py
>              available_attempts = self.retry_attempts
Good catch. In https://github.com/edx/configuration/blob/master/playbooks/roles/ecommerce/defaults/main.yml#L105, we never really specified the retry_attempts. Which makes this code useless. I'll make the PR against configuration repo. That said. I don't really see the point of putting the class variable "retry_attempts" behind the waffle switch. What benefit does it have?

2016-11-04 21:52 UTC, rlucioni commented on ecommerce/extensions/payment/processors/paypal.py
>              available_attempts = self.retry_attempts
@schenedx is the configuration repo really the right place for this value? Would we benefit from being able to tune this without redeploying the entire service? If so, the config repo is probably not the best place for this.

2016-11-07 19:55 UTC, schenedx commented
@rlucioni I took in your feedback and created a `PaymentProcessorsConfiguration` singleton model to capture the retry_attempts value. 
@edx/ecommerce Please review again

2016-11-07 20:01 UTC, clintonb reviewed
How frequently will the retry value change? If we aren't changing this on a weekly basis, I see no need for a new model. Just set the value in settings.

2016-11-07 20:14 UTC, rlucioni commented
@clintonb, @schenedx and I were just having that conversation. We think this has the potential to require tuning, and we'd rather not re-deploy the app to tweak the value. I suggested a model in anticipation of this need. It's true that this can reside just as happily in settings, but it won't be as easy to change from there.

2016-11-08 18:11 UTC, schenedx commented
@clintonb I agree with @rlucioni that it would be more beneficial to us if we can put the retry_attempts value in a DB based config model. This way, we can quickly react to needs for a change. I do agree with you in the immediate future, after we selected a value, we don't need to change the value anymore. This change do not impose negative impact in that scenario.

2016-11-08 18:11 UTC, schenedx commented
@rlucioni Do you have more comments for this change?

2016-11-08 19:14 UTC, rlucioni requested changes

2016-11-08 19:14 UTC, rlucioni commented on ecommerce/extensions/payment/models.py
> +    retry_attempts = models.PositiveSmallIntegerField(
This is specifically for PayPal. I hesitate to make it seem applicable to "all payment processors." We may want the flexibility to adjust this by payment processor in the future.

2016-11-08 19:14 UTC, rlucioni commented on ecommerce/extensions/payment/models.py
> +        verbose_name=_('Number of Retry Attempts for Payment Processor Requests'))
> Number of times to retry failing PayPal client actions (e.g., payment creation, payment execution).

2016-11-08 20:29 UTC, schenedx commented on ecommerce/extensions/payment/models.py
> +    retry_attempts = models.PositiveSmallIntegerField(
OK. I will update the name to be `Paypal` specific

2016-11-08 20:46 UTC, rlucioni approved these changes

2016-11-08 20:46 UTC, rlucioni commented on ecommerce/extensions/payment/models.py
> +        verbose_name=_('Number of times to retry failing Paypal client actions'))
I'd modify this provide the examples I quoted before. The "client actions" referred to here are clear to you and me, but may not be to a future maintainer.

2016-11-08 21:00 UTC, schenedx commented on ecommerce/extensions/payment/models.py
> +        verbose_name=_('Number of times to retry failing Paypal client actions'))
Ok

2016-11-08 21:22 UTC, merged

2016-11-09 02:07 UTC, clintonb commented on ecommerce/extensions/payment/models.py
> +            'Number of times to retry failing Paypal client actions (e.g., payment creation, payment execution)'
@schenedx please regenerate a new migration with the updated `verbose_name` value.

2016-11-09 14:59 UTC, schenedx commented on ecommerce/extensions/payment/models.py
> +            'Number of times to retry failing Paypal client actions (e.g., payment creation, payment execution)'
Good catch. I created PR for the new `verbose_name` update migration